### ISSUE TITLE
Button event not fired inside a scroll panel

### ISSUE THREAD

**Issue by cykerway** [wxWidgets/Phoenix#1000]
**Operating system**: Fedora 28
**wxPython version & source**: _(pypi, self-built, etc.)_ 4.0.3 gtk2 (phoenix) wxWidgets 3.0.5
**Python version & source**: _(stock, anaconda, EDM, distro, self-built, etc.)_ distro

**Description of the problem**:

When you put a list of buttons inside a scroll panel, if the window height shows only a tiny portion of the button, clicking on that button will scroll it up and show it full, but the `EVT_BUTTON` event is not fired on that button. if the window height shows a larger portion of that button, then clicking on that button will both scroll it up and fires the `EVT_BUTTON` event. This inconsistent behavior can confuse users.

I think this bug (unless a feature) is in the scrolling algorithm. When scrolling up a partially shown button in a scroll panel, the current implementation sometimes align buttons at top, sometimes at bottom. I believe when the button is below the viewport, the scrolling should always be aligned at bottom, because otherwise the mouse-up event is fired outside of the button you are clicking, which may lead to missing `EVT_BUTTON` events.

```python
#!/usr/bin/env python3
from wx.lib.scrolledpanel import ScrolledPanel
import wx
app = wx.App()
frame = wx.Frame(None, title='scroll panel bug', size=(300, 280))
panel = ScrolledPanel(frame)
sizer = wx.BoxSizer(wx.VERTICAL)
for i in range(16):
    btn = wx.Button(panel, size=(-1, 60), label='button {}'.format(i))
    btn.Bind(wx.EVT_BUTTON, lambda evt: print(evt.GetEventObject().GetLabel()))
    sizer.Add(btn, 0, wx.EXPAND)
panel.SetSizer(sizer)
panel.SetupScrolling(scroll_x=False)
sizer = wx.BoxSizer(wx.VERTICAL)
sizer.Add(panel, 1, wx.EXPAND)
frame.SetSizer(sizer)
frame.Show()
app.MainLoop()
```

Below is the screenshot of this code. You can adjust the frame height by a small amount to give a different behavior.

![a](https://user-images.githubusercontent.com/392675/45534493-480e3400-b7c9-11e8-9bf8-a3127fc5354d.png)

**Comment by cykerway** [comment]
These threads seem to be relevant:

-   <https://groups.google.com/forum/#!topic/wxpython-users/HPhAsMB4Stg>
-   <http://wxpython-users.1045709.n5.nabble.com/R-scrolling-events-question-td2326729.html>

They propose a workaround which seem to fix this problem. If this is indeed the correct way of doing so (a confirmation is greatly appreciated) you may feel free to close this issue. But if possible, IMHO, doing less on focus is better than more. It's somewhat confusing when the panel automatically scrolls after a mere window move (moving the frame in above code will re-scroll to the child with focus).

**Comment by RobinD42** [comment]
Yes, I think in general the preference is that child widgets are scrolled into view when the get the focus. Consider what would happen if the user was using only tab to move through text controls and not clicking on them.

For cases like what you've found, overriding the event handler is an acceptable workaround IMO.
