### ISSUE TITLE
size on OSX not correct

### ISSUE THREAD

**Issue by RealLau** [wxWidgets/Phoenix#1009]
- code:
```
import wx
class Example(wx.Frame):
    def __init__(self, parent, title):
        super(Example, self).__init__(parent, title=title, size=(300, 200))
        self.InitUI()
        self.Centre()
        self.Show()

    def InitUI(self):
        b = wx.Button(self, -1, size=(70, 70), pos=(10, 10))


app = wx.App()
Example(None, title='Grid demo')
app.MainLoop()
```
- effect:
![image](https://user-images.githubusercontent.com/16678624/45803185-820c9800-bceb-11e8-9621-9c017e16943a.png)

- info:
OSX: Sierra 10.13.4
wxpython: 4.0.4

**Comment by RobinD42** [comment]
This is simply the nature of the native button widget on OSX. The widget actually is as tall as you set it to be, but it only paints itself at the stock size.

Your options are:
* Use `SetWindowVariant` to set a different, but still stock, size for the button and its label.
* Add an icon to the button, or use a `wx.BitmapButton` instead, either of which will cause the drawn part of button to resize to accommodate the icon.
* Use a non-native button widget, such as those in `wx.lib.buttons`.
* etc.
