### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by fbender** [wxWidgets/Phoenix#101]
I'm happy see the project is moving along at a fast pace currently.

May you provide us with a rough estimate on when a "stable" version of wxPython Phoenix will be released? Is there a status page we can follow? Do you plan to support wxWidgets 3.1 in the first official Phoenix release, or upgrade afterwards? 

There's quite a few different places where you can find information on the project and its status and they seem to be out of sync, so a quick update on the front page of the wxPython website on current status, plans, and where to find information would be great!

**Comment by eldarkg** [comment]
Yes. I want to know too because [Ubuntu going to migrate from Python 2 to Python 3](https://wiki.ubuntu.com/XenialXerus/ReleaseNotes?_ga=1.137503286.76230679.1461262724#Python_3)

**Comment by RobinD42** [comment]
My hope is that a final 4.0.0 release is just weeks away. Depends on how many blocking issues come up in the betas, but it feels like we are on the home-stretch now.

**Comment by fbender** [comment]
Excellent news! Thanks a lot!
