### ISSUE TITLE
Where can I get the full source?

### ISSUE THREAD

**Issue by TheChymera** [wxWidgets/Phoenix#1015]
Your tag archives state I should not use the “source” links. Nor can I find complete sources [on pypi](https://pypi.org/project/wxPython/#files).

Where can I get a tarball with the full sources of e.g. your latest release?

**Comment by mesalu** [comment]
https://wxpython.org/pages/downloads/

**Comment by mesalu** [comment]
Yep!

**Comment by RobinD42** [comment]
This is a handy way to fetch the source:

```
pip download --no-binary :all: wxpython
```
