### ISSUE TITLE
Python 3* support

### ISSUE THREAD

**Issue by TheChymera** [wxWidgets/Phoenix#1016]
I am looking to update wxpython support on Gentoo Linux. Currently the newest version we have is `=dev-python/wxpython-3.0.2.0`, and it is marked as only compatible with Python 2.7.

Are the more recent versions Python 3* compatible? All the way up to 3.7? I was unable to find this information in the docs.

**Comment by mesalu** [comment]
Yes, Phoenix (wxPython 4.0+) is python3 compatible. 
There are some significant differences in API. Generally speaking, 4.0+ adheres more tightly to the underlying wxWidgets API. 
Here's  a migration guide. https://wxpython.org/Phoenix/docs/html/MigrationGuide.html

**Comment by TheChymera** [comment]
Does it also support Python 2.7?

**Comment by mesalu** [comment]
yes.
https://pypi.org/project/wxPython/#files

**Comment by mesalu** [comment]
Some other useful links:
 https://wxpython.org/pages/downloads/
https://wxpython.org/blog/2017-08-17-builds-for-linux-with-pip/index.html
