### ISSUE TITLE
No FlyOut attribute in AuiPaneInfo.

### ISSUE THREAD

**Issue by 8day** [wxWidgets/Phoenix#1029]
**Operating system**: Windows 7 64 bit.
**wxPython version & source**:          4.0.3 installed from PyPI.
**Python version & source**:            official Python 3.6.6 64 bit for MS.

**Description of the problem**:
[Docs](https://docs.wxpython.org/wx.lib.agw.aui.framemanager.AuiPaneInfo.html#wx.lib.agw.aui.framemanager.AuiPaneInfo.FlyOut) mention `AuiPaneInfo.FlyOut()`, but there's no such attribute in `AuiPaneInfo`.

```python
import wx.aui as aui

#for attr in dir(aui.AuiPaneInfo()):
#    print(attr)
print(hasattr(aui.AuiPaneInfo(), 'FlyOut'))
```

**Comment by infinity77** [comment]
I’m pretty sure is there...

https://github.com/wxWidgets/Phoenix/blob/master/wx/lib/agw/aui/framemanager.py

You are importing wx.aui but the docs refer to wx.lib.agw.aui...

**Comment by mesalu** [comment]
To add to this:
There is a difference (if a bit of a confusing one) between wx.aui and wx.agw.aui.

Phoenix is a Python binding of the C++ library, wxWidgets. 
Within wxWidgets there is a large collection of widgets called AUI. 
@infinity77, along with some other neat tools, contributed a pythonic **re-implementation** of AUI, as part of the `agw` module.

While the two are very similar, they are not perfect matches, as is the case with `FlyOut`.

Phoenix provides both of these contributions. 
- It wraps the C++ contribution as `wx.aui`
- it provides the pythonic re-implementation as `wx.agw.aui`

**Comment by 8day** [comment]
Sorry. I  felt that I was doing something stupid, but couldn't figure out what. I guess first result in Google for searching `AuiManager` was `wx.lib.agw.aui.framemanager.AuiManager` rather than `wx.aui.AuiManager`.

You can close this issue.
