### ISSUE TITLE
wxpython==4.0.3 build error on Ubuntu 18.04.1 LTS 

### ISSUE THREAD

**Issue by view7677** [wxWidgets/Phoenix#1033]
Collecting wxpython==4.0.3 (from sql-editor)
  Using cached https://files.pythonhosted.org/packages/dd/31/bd55ab40e406a026a7fda0bb5eb61f466682544ae91ac26267c750f5e618/wxPython-4.0.3.tar.gz

 checking for GST... configure: WARNING: GStreamer 0.10 not available, falling back to 0.8
    configure: error: GStreamer not available
    Error running configure
    ERROR: failed building wxWidgets
    Traceback (most recent call last):
      File "build.py", line 1321, in cmd_build_wx
        wxbuild.main(wxDir(), build_options)
      File "/tmp/pip-install-tv39du9r/wxpython/buildtools/build_wxwidgets.py", line 375, in main
        "Error running configure")
      File "/tmp/pip-install-tv39du9r/wxpython/buildtools/build_wxwidgets.py", line 85, in exitIfError
        raise builder.BuildError(msg)
    buildtools.builder.BuildError: Error running configure
    Finished command: build_wx (0m21.628s)
    Finished command: build (0m21.628s)
    Command '"/docs/work/python_project/sql_editor/venv/bin/python3" -u build.py build' failed with exit code 1.
    
    ----------------------------------------
Command "/docs/work/python_project/sql_editor/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-tv39du9r/wxpython/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-agd001sq/install-record.txt --single-version-externally-managed --compile --install-headers /docs/work/python_project/sql_editor/venv/include/site/python3.6/wxpython" failed with error code 1 in /tmp/pip-install-tv39du9r/wxpython/

**Operating system**:
**wxPython version & source**:          
**Python version & source**:            

**Description of the problem**:

```python
# Put code sample here
```

**Comment by HelioGuilherme66** [comment]
@view7677 Maybe you need to install `gstreamer-devel` (this is the name of the package on my RPM based Linux).

**Comment by RobinD42** [comment]
On Ubuntu 18.04+ you can use gstreamer 1.0 instead of the 0.10 version. Installing `libgstreamer-plugins-base1.0-dev` get all the needed dependencies.
