### ISSUE TITLE
What to do about wx.SetDefaultPyEncoding?

### ISSUE THREAD

**Issue by ibell** [wxWidgets/Phoenix#1036]
As is clear in the documentation, the function SetDefaultPyEncoding has been removed.  How then should/can we emulate that functionality in Phoenix?  This is a blocking issue for me, and the only way I could get special characters like \xb3 to display properly previously in classic.  But this small example works fine, so I don't know what is going on:

```python
# -*- coding: utf-8 -*-

# First things, first. Import the wxPython package.
import wx

# Next, create an application object.
app = wx.App()

# Then a frame.
frm = wx.Frame(None, title="³")

# Show it.
frm.Show()

# Start the event loop.
app.MainLoop()
```

**Comment by RobinD42** [comment]
Either pass a unicode value to the wx functions/methods, or pass a utf-8 encoded bytes object (in Python2 that's the same as str objects). 

In Python 3 string constants like in your sample are automatically unicode. In Python2 you need to use the `u""` syntax for strings, or ensure that the strings are encoded as utf-8, which the coding line at the top does for you.
