### ISSUE TITLE
`GetValidator` returns `None` instead of Validator instance for "null" validator

### ISSUE THREAD

**Issue by carandraug** [wxWidgets/Phoenix#1054]
If a control uses a "null" validator (such as the default `wx.DefaultValidator`), then the `GetValidator` method returns `None` instead of the actual "null" Validator instance.  Minimal example:

``` 
import wx

app = wx.App()
frame = wx.Frame(None)

print('validator used -', wx.DefaultValidator)
ctrl = wx.TextCtrl(frame, validator=wx.DefaultValidator)
print('validator gotten -', ctrl.GetValidator())

frame.Close()
app.MainLoop()
```

which returns:

```
validator used - <wx._core.Validator object at 0x7fe202adbaf8>
validator gotten - None
```

This is a problem because `None` can't be used in place of a "null" Validator.  That is, something like this:

```
ctrl1 = wx.TextCtrl(..., validator=wx.DefaultValidator)
ctrl2 = wx.TextCtrl(..., validator=ctrl1.GetValidator())
```

will raise:

```
TypeError: TextCtrl(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 'validator' has unexpected type 'NoneType'
```

**Comment by RobinD42** [comment]
Since the C++ method is returning a pointer, not a value, then it uses `NULL` to indicate when there isn't one, and `NULL`s are converted to the Python `None` object.

```
    /**
        Returns a pointer to the current validator for the window, or @NULL if
        there is none.
    */
    virtual wxValidator* GetValidator();
```

https://docs.wxpython.org/wx.Window.html#wx.Window.GetValidator
