### ISSUE TITLE
HyperTreeList fails to position item windows scrolled outside viewing area

### ISSUE THREAD

**Issue by cbeytas** [wxWidgets/Phoenix#1059]
### wxPython 4.0.3 msw
Can be seen in the demo by expanding nodes and using the down arrow to scroll the list down. The windows pile up at the top of the control.
![htldemo](https://user-images.githubusercontent.com/4748055/47599403-6f851e80-d97b-11e8-801d-93e278794b3b.gif)

First problem is in wx.lib.agw.hypertreelist line 3044:
```python
if wnd.GetPosition() != (wndx, ya):
	wnd.SetPosition((wndx, ya))
```
SetPosition doesn't allow setting a position of -1. When the list tries to position a window to -1, it remains at its previous position which causes it to overlap onto the wrong row. It should use Move instead:
```python
	wnd.Move(wndx, ya, flags=wx.SIZE_ALLOW_MINUS_ONE)
```

The second problem happens when the row is scrolled completely out of the window. It is no longer "exposed" so it doesn't get painted. This also means its window positions don't get updated and they remain visible on-screen at their old positions until the item is repainted again.

I'd suggest adding and else statement to the line:
```python
		if self.IsExposed(exposed_x, exposed_y, _MAX_WIDTH, h + draw_row_lines):
```
near the bottom of the PaintLevel method (hypertreelist line 3190). This code checks if shown windows are present, and hides them if the row is no longer visible.
```python
					wx.RendererNative.GetDefault().DrawTreeItemButton(self, dc, rect, flag)
		else:
			# Item not part of invalidated paint area. Check its windows.
			treewidth, treeheight = self.GetClientSize()
			for col in range(self.GetColumnCount()):
				wnd = item.GetWindow(col)
				if wnd and wnd.IsShown():
					# Window is currently shown. Is the row visible?
					rowheight = item.GetHeight()
					xa, ya = self.CalcScrolledPosition(0, item.GetY())
					if ya >= treeheight or (ya + rowheight) < 0:
						# Row is hidden. Hide this window.
						wnd.Hide()
```

**Comment by RobinD42** [comment]
Please create a PR with your changes.

**Comment by cbeytas** [comment]
This also affects CustomTreeCtrl. After having a second look, the problem seems to originate in the `ScrollTo` method (customtreectrl.py line 5930).

It calls `self.SetScrollBars()` to set and move the scroll position. This doesn't update client window positions which the `ScrolledWindow` subclass is supposed to do automatically.
However if `self.Scroll()` is used instead, all the child window positions get updated properly and this problem goes away.

Maybe this behavior is platform-specific or has changed recently? I don't see how no one hasn't complained about this issue yet. Do you have any advice?

**Comment by infinity77** [comment]
Something must have changed in Phoenix as this doesn’t happen in classic as far as I can see...

**Comment by cbeytas** [comment]
Affects Windows7 and Windows XP (Python 2.7) both wxPython 2.8 and Phoenix 4.0.3
Issue does not happen on Ubuntu with python 2.7 and wx2.8gtk.
