### ISSUE TITLE
wx.aui.AuiNotebook.SetArtProvider(wx.aui.AuiDefaultTabArt()) Crash!

### ISSUE THREAD

**Issue by yxdragon** [wxWidgets/Phoenix#1061]
wx.aui.AuiNotebook.SetArtProvider(wx.aui.AuiDefaultTabArt()) make crash.
I saw the demo, wx.lib.agw.aui works.
some question:
diffrence between wx._aui and wx.aui?
wx.lib.agw.aui is writon in pure python, wx.lib.agw.aui and wx.aui, which one should i choose?

**Comment by Metallicow** [comment]
wx.aui is an underlying wxWidgets lib. The person that originally wrote it kinda disappeared a while ago and there was outstanding bugs and features not implemented. Andrea eventually came along and ported the C++ code into python so its bugs could be fixed and improvements be made. The work Andrea did is the wx.lib.agw.aui and is pure python. 

... So to answer your question, which is better... wx.lib.agw.aui is more bug free and polished. the wx.aui might run faster, but has outstanding bugs and missing features, so if you are not using just a simple notebook, most would say go with the python library version.

wxWidgets has AUI on its rewrite list, but it might be quite some time before that ever gets done and sees the light of day on the C++ side of things.

**Comment by yxdragon** [comment]
infact, i just want to draw a bitmap as the notebook's blank background, but I found the code i wrote doesnot work, I think the paint method is overritten by the art provider, How can I draw on the blank background?

**Comment by Metallicow** [comment]
I'm not exactly sure what you are wanting to texture... Could you provide a small sample app and/or a picture of what you want to do. I use wx.lib.agw.aui and the only things I alter in my custom version is notebook tab arts and manager art background from the default gradient.

This is a pic of what I can texture in my apps.
![customauitexture](https://user-images.githubusercontent.com/4668356/47680300-72a72700-db94-11e8-9042-fbe9e1b84c6f.png)

Also, have you looked at the official wx.lib.agw.aui demo?

**Comment by RobinD42** [comment]
> then, wen i use wx.aui.AuiNotebook.SetArtProvider, and give a wx.aui.AuiDefaultTabArt(), it crash, and I print(notebook.GetArtProvider()), it is a wx._aui.AuiDefaultTabArt() object, is it a wx's bug? or I did not use it correctly?

It's a bug. Ownership of the art object was not being transferred correctly from Python to C++, so it was being destroyed immediately after the `SetArtProvider` call since you were not saving a reference to it. Then when the notebook tried to use it then it crashed because it had a bad pointer.

I have a fix on the way.

**Comment by RobinD42** [comment]
Fixed by #1065

**Comment by jensgoe** [comment]
> wxWidgets has AUI on its rewrite list, but it might be quite some time before that ever gets done and sees the light of day on the C++ side of things.

Didn't know that. Where can i find this rewrite list?

**Comment by Metallicow** [comment]
@jensgoe  It was an item on the bug/feature/todo trac at one point iirc. It's buried somewhere in there.

**Comment by yxdragon** [comment]
I use wx.aui at first, but notebook setartprovider crashed, and wx4.03, the page cannot be closed! then I change wx.lib.agw.aui, but on mac, when open two pages, and drag one be left-right, then if we drag the right back to the left one, it crashed.

I just want to add a watermark to the blank notebook (when there is no page), at first I think I should override the tabartprovider's drawbackground, later, I find I should use dockargprovider. and now I add a watermark successfully!

another question, I want use a advencedsplash when open the software, my program need 3s to load, but the splash show in nocolor, untill my program be loaded, and enter mainloop, it looks right.

I 'd like the splash show first, and my program loaded in back. need I use a pubsub here?

my projects here: [https://github.com/Image-Py/imagepy](url)

**Comment by Metallicow** [comment]
@yxdragon I think the best thing to do for your help with splash and other stuff would be to ask on the wxPython mailing lists or make a help wanted issue on your project. Good to hear you got your texture issue figured out :)
