### ISSUE TITLE
auinotebook page can not be closed

### ISSUE THREAD

**Issue by yxdragon** [wxWidgets/Phoenix#1062]
in wx4.0.3, the auinotebook page can not be closed, which works in wx4.0.1

**Comment by RobinD42** [comment]
Please check with a snapshot build of 4.0.4, I believe it has been fixed there for the next release.

**Comment by infinity77** [comment]
@swt2c not sure on what platform this was, but I’m pretty sure AuiNotebook tabs can be closed…
