### ISSUE TITLE
Install 4.0.4 Over Pip

### ISSUE THREAD

**Issue by Mradr** [wxWidgets/Phoenix#1070]
Running 4.0.3 - but having issues with dll files missing. I see someone said to install 4.0.4 - how can I over c:\python37\python -m pip install wxpython ?

**Comment by RobinD42** [comment]
You can get pre-release snapshots of 4.0.4 from https://wxpython.org/Phoenix/snapshot-builds/, or you can give that URL to pip and have it do it for you. If you'd rather stick with 4.0.3 for now, you can just get the VC runtime redistributables from Microsoft and install them on your machine. https://www.microsoft.com/en-us/download/details.aspx?id=52685
