### ISSUE TITLE
wx.html2.WebView with WebKit 2 does not display pictures from the disk

### ISSUE THREAD

**Issue by Jenyay** [wxWidgets/Phoenix#1071]
**Operating system**: Ubuntu 18.04
**wxPython version & source**:          wxPython 4.0.1, 4.0.3
**Python version & source**:            Python 3.6

If you install wxPython using WebKit 2, then images with relative paths or with the file: // protocol will not be displayed. Everything works fine with WebKit 1.

I think this error is related to #981.

**Comment by swt2c** [comment]
Can you provide a specific example of html that doesn't work for you?  I am not seeing any problems with relative or file URLs.

**Comment by Jenyay** [comment]
@swt2c I made a minimal example where the problem is visible - [testwebkit.zip](https://github.com/wxWidgets/Phoenix/files/2547207/testwebkit.zip)

**Comment by swt2c** [comment]
Thanks for the example.  Unfortunately, I still don't see the problem when using your example.  I tried on Fedora 29 and Ubuntu 18.04 - in both cases I tried the distribution packages for wxPython (version 4.0.1).

**Comment by Jenyay** [comment]
Probably these packages are compiled using WebKit 1. I also don’t see problems if I install wxPython 4.0.3 in Ubuntu 18.04. The problem is observed if I install wxPython 4.0.3 in Ubuntu 16.04 or compile from source using WebKit 2.

**Comment by Jenyay** [comment]
I updated the example to it show engine version - [testwebkit_2.zip](https://github.com/wxWidgets/Phoenix/files/2551898/testwebkit_2.zip)

In Ubuntu 18.04 + wxPython 4.0.3 from the wheels everything is working:

![webkit_ok](https://user-images.githubusercontent.com/166281/48047972-d50eb180-e1aa-11e8-8c45-cb429d28abf3.png)

In Ubuntu 18.04 + wxPython 4.0.3 from the compiled sources no images are displayed:

![webkit_error](https://user-images.githubusercontent.com/166281/48048026-0e472180-e1ab-11e8-972c-1835cabbda87.png)

Similarly in Ubuntu 16.04 + wxPython 4.0.3 from the wheels.

**Comment by swt2c** [comment]
> Probably these packages are compiled using WebKit 1. I also don’t see problems if I install wxPython 4.0.3 in Ubuntu 18.04. The problem is observed if I install wxPython 4.0.3 in Ubuntu 16.04 or compile from source using WebKit 2.

Nope, Fedora 29 doesn't even have WebKit 1 packages, and the Ubuntu 18.04 wxwidgets package was build with WebKit2, see build log here:
https://launchpadlibrarian.net/362519168/buildlog_ubuntu-bionic-amd64.wxwidgets3.0_3.0.4+dfsg-3_BUILDING.txt.gz

**Comment by Jenyay** [comment]
Is there a way to explicitly specify the required version of WebKit?

**Comment by swt2c** [comment]
The wxWidgets build process will search for WebKit2 first, and if not found, it will search for WebKit1.  Unfortunately, no there isn't a way to specify WebKit1 only, other than removing the WebKit2 development package so it will not be found.

**Comment by Jenyay** [comment]
I compiled (Ubuntu 18.04) and uploaded wheel with which there is a problem. https://drive.google.com/drive/folders/12LqBgdQPWw0BcetRLJ0iVicpa0rKzTul?usp=sharing

Try the example above with this version.

**Comment by Jenyay** [comment]
Can you reproduce the problem?

**Comment by swt2c** [comment]
No, but I did not try your wheel.

**Comment by Jenyay** [comment]
I understand when an error occurs. The error appears if there are non-Latin characters on the path to the file being opened. For example if the previous code is located at /home/jenyay/temp/webkit/**test**/ then everything works fine. The error occurs when the code is placed at /home/jenyay/temp/webkit/**проверка**/

**Comment by swt2c** [comment]
Aha!  That would explain why I could not reproduce it.  I can reproduce now in wxWidgets.  I'll look into the issue.

**Comment by Jenyay** [comment]
I noticed that in the same case external JavaScript files are not loaded, perhaps, still CSS files, but I did not tested.

**Comment by swt2c** [comment]
As far as I can tell, this is a bug in WebKit2 itself.  It is refusing to load those images.  I am reporting it upstream.

**Comment by Jenyay** [comment]
A bug is similar to a known issue - https://bugs.webkit.org/show_bug.cgi?id=184660. Unfortunately, they are not going to solve it.

**Comment by Jenyay** [comment]
The problem disappeared with the release of WebKitGTK 2.24.1.

**Comment by infinity77** [comment]
@swt2c Given @Jenyay comment above, this might be closed?
