### ISSUE TITLE
error: ‘::wxWebViewHistoryItem’ has not been declared

### ISSUE THREAD

**Issue by bretttolbert** [wxWidgets/Phoenix#1073]
**Operating system**: Ubuntu 18.04.1 LTS
**wxPython version & source**:          pip install wxpython (downloaded wxPython-4.0.3.tar.gz)
**Python version & source**:            Python 2.7.15rc1

**Description of the problem**:
Pip install wxpython fails (build fails with compilation error)

```
    [634/868] Linking build/waf/2.7/gtk3/_html.so
    ../../../../sip/cpp/sip_html2wxWebViewHistoryItem.cpp: In function ‘PyObject* meth_wxWebViewHistoryItem_GetUrl(PyObject*, PyObject*)’:
    ../../../../sip/cpp/sip_html2wxWebViewHistoryItem.cpp:24:12: error: ‘::wxWebViewHistoryItem’ has not been declared
              ::wxWebViewHistoryItem *sipCpp;
                ^~~~~~~~~~~~~~~~~~~~
```

**Comment by swt2c** [comment]
>checking for WEBKIT... configure: WARNING: webkit2gtk not found, falling back to webkitgtk
>checking for WEBKIT... configure: WARNING: webkitgtk not found.
>configure: WARNING: WebKit not available, disabling wxWebView

You need to install `libwebkit2gtk-4.0-dev` package.

**Comment by bretttolbert** [comment]
Thanks! That fixed it.

**Comment by mihaic** [comment]
Shouldn't `configure` fail if WebKit is required, instead of continuing with a warning?

**Comment by swt2c** [comment]
`configure` in this case is the wxWidgets (C++ library) configuration.  wxWidgets itself works just fine without WebKit, it just disables the wxWebView functionality.  The problem here is that wxPython doesn't really have a way of disabling wrapper functionality for missing features in wxWidgets, so the wxPython build fails later on.  The proper solution is probably for wxPython to check which features are missing or present in the wxWidgets build and enable/disable the wrapper functionality accordingly, but it doesn't do that currently.

**Comment by RobinD42** [comment]
Actually it is being done, starting in 4.0.4:

https://github.com/wxWidgets/Phoenix/blob/wxPy-4.0.x/etg/webview.py#L52
https://github.com/wxWidgets/Phoenix/blob/wxPy-4.0.x/etgtools/tweaker_tools.py#L1269

😀

**Comment by swt2c** [comment]
Oh, very nice Robin!

**Comment by swt2c** [comment]
@RobinD42 is there a way this can used other than at the module level?  The specific example I'm thinking of is for wxFileSystemWatcher.  The specific use case is for Debian Hurd, which does not have inotify (admittedly a rather low priority case), but I've got an open bug over at Debian about it.

**Comment by RobinD42** [comment]
It could probably be refactored to allow more narrow selection of items to be stubbed, feel free to give it a try and submit a PR. 

OTOH, the "module" in this case is the `etgtools.ModuleDef` object created in `etg/fswatcher.py` module, and that only has `wxFileSystemWatcher` and `wxFileSystemWatcherEvent` items, so using the stub generator as-is will probably work okay for it.

**Comment by swt2c** [comment]
Actually it *is* that `wxFileSystemWatcher` is missing completely.  `wxUSE_FSWATCHER` ends up getting set to no by configure, and thus it is all missing.  I'll give your earlier suggestion a try later.

**Comment by RobinD42** [comment]
Ok, thanks. I'll add a new issue for it, and if you create a PR you can link it to the new issue.
