### ISSUE TITLE
PIImportTest.test_grid_pi test failure

### ISSUE THREAD

**Issue by swt2c** [wxWidgets/Phoenix#1084]
As you might have noticed, I'm back to trying to fix up the tests again.  :-)  I can't figure out how to fix this one though.  It seems to be related to the naming of the `wxGridSelectionModes`.

```
__________________________ PIImportTest.test_grid_pi ___________________________
self = <unittests.test_pi_import.PIImportTest testMethod=test_grid_pi>
    def test_grid_pi(self):
>       self.runPI('grid.pyi')
unittests/test_pi_import.py:66: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
unittests/test_pi_import.py:32: in runPI
    self.assertEqual(sp.returncode, 0, stdout)
E   AssertionError: Traceback (most recent call last):
E     File "grid.pyi", line 1798, in <module>
E       class Grid(wx.ScrolledWindow):
E     File "grid.pyi", line 1834, in Grid
E       def CreateGrid(self, numRows, numCols, selmode=GridSelectCells):
E   NameError: name 'GridSelectCells' is not defined
```

**Comment by pbrod** [comment]
I also get this error on wxpyhton 4.0.7dev using anaconda with python3.7 on windows 10.

In addition I also get these three errors:

    __________________________ PIImportTest.test_glcanvas_pi ___________________________
    self = <unittests.test_pi_import.PIImportTest testMethod=test_glcanvas_pi>
    
        def test_glcanvas_pi(self):
    >       self.runPI('glcanvas.pyi')
    
    unittests\test_pi_import.py:63: 
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
    unittests\test_pi_import.py:32: in runPI
        self.assertEqual(sp.returncode, 0, stdout)
    Traceback (most recent call last):
     File "glcanvas.pyi", line 48, in <module>
        class GLContext(Object):
    NameError: name 'Object' is not defined
    
    __________________________ PIImportTest.test_stc_pi ___________________________
    self = <unittests.test_pi_import.PIImportTest testMethod=test_stc_pi>
    
        def test_stc_pi(self):
    >       self.runPI('stc.pyi')
    
    unittests\test_pi_import.py:42: 
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
    unittests\test_pi_import.py:32: in runPI
        self.assertEqual(sp.returncode, 0, stdout)
    E  Traceback (most recent call last):
      File "stc.pyi", line 2011, in <module>
        class StyledTextCtrl(wx.Control, wx.TextEntry):
      File "stc.pyi", line 2029, in StyledTextCtrl
        def Create(self, parent, id=ID_ANY, pos=DefaultPosition, size=DefaultSize, style=0, name=STCNameStr):
    NameError: name 'DefaultPosition' is not defined
    
    __________________________ PIImportTest.test_xrc_pi ___________________________
    self = <unittests.test_pi_import.PIImportTest testMethod=test_xrc_pi>
    
        def test_xrc_pi(self):
    >       self.runPI('xrc.pyi')
    
    unittests\test_pi_import.py:57: 
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
    unittests\test_pi_import.py:32: in runPI
        self.assertEqual(sp.returncode, 0, stdout)
    E   Traceback (most recent call last):
      File "xrc.pyi", line 32, in <module>
        class XmlResource(Object):
    NameError: name 'Object' is not defined
