### ISSUE TITLE
Does the lastest wxPython4 do not support the python2.7?

### ISSUE THREAD

**Issue by noval102200** [wxWidgets/Phoenix#1094]
**Operating system**:
windows 10
**wxPython version & source**:          
wxPython 4.0.3
def getDefaultPublisher() -> Publisher:
    """
    Get the Publisher instance created by default when this module
    is imported. See the module doc for details about this instance.
    """
    return _publisher
**Python version & source**:            
python2.7
import noval.util.sysutils as sysutilslib
from wx.lib.pubsub import pub as Publisher

**Description of the problem**:

  File "E:\wekay-NovalIDE-dev\NovalIDE\noval\tool\service\navigation\NavigationService.py", line 6, in <module>
    from wx.lib.pubsub import pub as Publisher
  File "E:\env\lib\site-packages\wx\lib\pubsub\__init__.py", line 38, in <module>
    from pubsub import *
  File "E:\env\lib\site-packages\pubsub\pub.py", line 146
    def getDefaultPublisher() -> Publisher:
                              ^
SyntaxError: invalid **syntax**

I found the latest version wxPython4.0.3 do not support python2.7.which is latest wxPython version that support the python2.7?
```python
# Put code sample here
import noval.util.sysutils as sysutilslib
from wx.lib.pubsub import pub as Publisher
```

**Comment by HelioGuilherme66** [comment]
@noval102200 This is an issue tracker, only to report problems or code suggestions. You should ask questions in other places, like, for example, [wxPython-users](https://groups.google.com/forum/#!forum/wxpython-users)

You did not fill the Issue template with the requested info. If you did, we probably would see that you got the wrong wxPython installation package, because it is compatible with Python 2.7 and 3.x.

**Comment by noval102200** [comment]
@HelioGuilherme66 Thanks very much for you suggestion.I have fill the issute tempalte with detail error information.Thanks for your answer.

**Comment by DietmarSchwertberger** [comment]
The exception is in pubsub, not wxPython. You seem to have a wrong version of pubsub installed that is not compatible with Python 2.7.
Older versions of wx came with their own version of pubsub in wx.lib.pubsub. Newer versions just import the version that is found in site-packages.

**Comment by HelioGuilherme66** [comment]
So the solution would be:
`pip install -U pypubsub==3.3.0`

**Comment by noval102200** [comment]
@Dietmar Schwertberger thanks very much! so how to resolve the problem.does pubsub module is a package which can be installed?
