### ISSUE TITLE
missing wx.CheckListBox.Get/SetItemForeground/BackgroundColour

### ISSUE THREAD

**Issue by mprosperi** [wxWidgets/Phoenix#1095]
**Operating system**: win10
**wxPython version & source**:         4.0.4.a1 (daily snapshot)
**Python version & source**:            3.5 stock

**Description of the problem**:
Get/SetItemForeground/BackgroundColour are missing from Phoenix but presente in Classic. Couldn't find in docs if they were replaced by something else

**Comment by swt2c** [comment]
It looks like those were wxPython specific extensions in Classic for MSW only:
https://github.com/wxWidgets/wxPython/blob/master/src/_listbox.i#L140

Don't know whether Robin left those out deliberately, but they could probably be re-added if he thinks it is a good idea.

**Comment by infinity77** [comment]
@swt2c i guess from @RobinD42 comment that this can be closed
