### ISSUE TITLE
Platform-dependent Colour constructor behaviour.

### ISSUE THREAD

**Issue by mickp** [wxWidgets/Phoenix#1107]
**wxPython version & source**:  pypi

**Python version & source**:     

os | version | source
---|---|---
Linux | 3.7.1 and 3.7.0 | stock Manjaro
Mac | 3.7.0 | homebrew
Win | 3.5.2 | WinPython

It looks like some colour definitions are missing on Mac and Windows.
Below is a table with OS, wx version and the result of running the following code:

```
import wx
app = wx.App()
wx.Colour('chartreuse')
```
OS | wx.version() | wx.Colour('chartreuse')
---|---|---
Linux | 4.0.3 gtk3 (phoenix) wxWidgets 3.0.5 | wx.Colour(127, 255, 0, 25)
Mac | 4.0.3 osx-cocoa (phoenix) wxWidgets 3.0.5 | wx.Colour(-1, -1, -1, 255)
Win | 4.0.3 msw (phoenix) wxWidgets 3.0.5 | wx.Colour(-1, -1, -1, 255)

On the Mac, I also see a debug message:
```wxColour::Set ─ couldn't set to colour string 'chartreuse'```

**Comment by RobinD42** [comment]
The wxGTK port uses the naive X11 colour names file (`rgb.txt` IIRC) to look up colour names. On the other platforms a limited subset is built in to wxWidgets and it is used instead. Luckily I used the time machine to go back almost 18 years and added the `wx.lib.colourdb` module. It has a function called `updateColourDB` that will update wxWidgets' internal coulor database with the list of color names and values found in `rgb.txt` at that time.

```python
>>> import wx
>>> wx.Colour("chartreuse")
wx.Colour(-1, -1, -1, 255)
>>> import wx.lib.colourdb
>>> wx.lib.colourdb.updateColourDB()
>>> wx.Colour("chartreuse")
wx.Colour(127, 255, 0, 255)
```
