### ISSUE TITLE
Python 3.7.1 causes dark theme to work on Mac but buttons barely visible

### ISSUE THREAD

**Issue by abulka** [wxWidgets/Phoenix#1132]
Running wxPython apps, including the official wxPython-demo-4.0.3 under Python 3.7.1 on a Mac configured for the dark theme, causes the dark theme to work on text fields but buttons and labels become barely visible:

<img width="970" alt="screen shot 2019-01-09 at 10 07 48 am" src="https://user-images.githubusercontent.com/11467530/50865295-3ba58b00-13f9-11e9-9c50-b3c405fb94e7.png">

**Operating system**: Mac OS Moave 10.14.2
**wxPython version & source**:   wxPython    4.0.4 via pypi
**Python version & source**:        brew Python 3.7.1

**Description of the problem**:

Running the same wxPython 4.0.4 installation under the earlier Python 3.7.0 works traditionally and nicely - but does not respect the mac dark theme.

Why would upgrading the Python version suddenly make the dark theme work under wxPython, I would have though upgrading wxPython would be needed to make such visual changes?  Anyway, currently I am trying to downgrade back to Python 3.7.0 because wxPython 4.0.4 is arguably not compatible with Python 3.7.1 or Python 3.7.2 on a Mac.

To reproduce:
Running demo under Python 3.7.1 or 3.7.2 shows problematic dark theme effects

```
cd wxPython-demo-4.0.3/src
/usr/local/Cellar/python/3.7.2/bin/python3 demo.py
```

Running demo under Python 3.7.0 or earlier shows no problems (albiet no dark theme either).

```
cd wxPython-demo-4.0.3/src
/usr/local/Cellar/python/3.7.0/bin/python3 demo.py
```

More info on Apple's [dark theme](http://osxdaily.com/2018/10/12/how-enable-dark-mode-theme-macos/) system setting:
<img width="664" alt="screen shot 2019-01-09 at 10 23 51 am" src="https://user-images.githubusercontent.com/11467530/50865291-35afaa00-13f9-11e9-82ed-d0e064692b10.png">

**Comment by abulka** [comment]
Have since discovered that this is a known issue in wxwidgets, see #1020 and is being worked on https://trac.wxwidgets.org/ticket/18146 and discussed https://forums.wxwidgets.org/viewtopic.php?t=45261.  

Is there a more cutting edge build of wxpython that fixes this and that I can install via pypi? My app is unshippable at the moment.

As for my observations that Python 3.7.1 exhibits the issue and 3.7.0 does not - it turns out that if I downgrade to 3.7.0 the issue still happens.  Once you upgrade, something is forever changed. Even when I remove /usr/local/lib/python3.7 and reinstall all the packages (albeit they come from pip's cache) the problem persists, even in Python 3.7.0. Curious.  The dark mode problems were definitely not there in brew Python 3.7.0 (verified on two different machines)...

**Comment by abulka** [comment]
I was able to install a wxPython pre-release which solves the dark mode problem on the Mac:

```
$ pip install -U --pre \
         -f https://wxpython.org/Phoenix/snapshot-builds/ \
         wxPython==4.1.0a1.dev4616+ef1edacc
```

Getting excited, I tried putting this into a `requirements.txt` file, however this entry didn't work:
```
wxPython==4.1.0a1.dev4616+ef1edacc --pre -f https://wxpython.org/Phoenix/snapshot-builds/ ; sys_platform == "darwin"
``` 
_(perhaps I have the syntax wrong?)_

but this entry in `requirements.txt` did work:

```
http://wxpython.org/Phoenix/snapshot-builds/wxPython-4.1.0a1.dev4616+ef1edacc-cp37-cp37m-macosx_10_9_x86_64.whl ; sys_platform == "darwin"
```

Interestingly dark mode works OK when running a wxpython app normally from the terminal, but when bundled into an executable using PyInstaller, dark mode sadly, fails to turn on. On the positive side, at least the wx buttons and everything are now properly visible - just simply not in dark mode.  This has been [reported on stackoverflow](https://stackoverflow.com/questions/58683744/wxpython-macos-dark-mode-support-and-pyinstaller) and likely to be a PyInstaller issue.

**Comment by RobinD42** [comment]
I don't remember details, but IIRC there is an item in the .app bundle's Info.plist file that needs to be set to inform the system that it is darkmode aware. There is probably a way to get PyInstaller to set it, otherwise it should be possible to edit the file after PyInstaller is done.

**Comment by abulka** [comment]
Great tip!  I added `'NSRequiresAquaSystemAppearance': 'No'` to my PyInstaller `.spec` file:

```python
app = BUNDLE(exe,
    ...
    name=...,
    icon=...,
    info_plist={
        ...
        'NSRequiresAquaSystemAppearance': 'No'
    },
    bundle_identifier=None)
```

and now the PyInstaller created .app file launche OK in dark mode.

**Comment by abulka** [comment]
Build `4.1.0a1.dev4616+ef1edacc` seems to have disapeared from 
https://wxpython.org/Phoenix/snapshot-builds/ ?  Do builds normally disappear like this?

Seems the latest `pip` command is
```
pip install -U --pre -f https://wxpython.org/Phoenix/snapshot-builds/ wxPython==4.1.0a1.dev4640+f1aaa8b6
```
and if you want an entry in `requirements.txt` presumably the latest direct link will work
```
https://wxpython.org/Phoenix/snapshot-builds/wxPython-4.1.0a1.dev4640+f1aaa8b6-cp36-cp36m-macosx_10_9_x86_64.whl
```

**Comment by RobinD42** [comment]
> Do builds normally disappear like this?

Yes, older dev snapshots are cleared out when new ones are uploaded.

>  latest pip command is

You can leave off the version number to always get the latest dev snapshot.

**Comment by abulka** [comment]
> You can leave off the version number to always get the latest dev snapshot.

Not sure which bit of that long filename is the 'version number' to leave off. I tried a few variations incl.

`http://wxpython.org/Phoenix/snapshot-builds/wxPython-4.1.0a1`

but nothing worked.  What is the exact `requirements.txt` line that will give me the latest snapshot build?

**Comment by RobinD42** [comment]
I'm not sure what the `requirements.txt` syntax would be. What I was talking about was to leave the version number off the pip command line in order to get the latest build, like:

```
pip install -U --pre -f https://wxpython.org/Phoenix/snapshot-builds/ wxPython
```

There will be a 4.1.0 release soon, so you won't have to deal with this manually for long.

**Comment by hamishmb** [comment]
Mouse clicks and keyboard events don't seem to work for me when dark mode is enabled, for some reason (with is with the 4.1.0 stable release on Catalina). Whenever I click a button or hit enter for something, nothing happens.

**Comment by RobinD42** [comment]
This issue has been mentioned on **Discuss wxPython**. There might be relevant details there:

https://discuss.wxpython.org/t/macos-dark-mode-doesnt-work-with-4-1-0/35000/1
