### ISSUE TITLE
Example "Hello World" program do not run on Python 3.7.1

### ISSUE THREAD

**Issue by LGMailhos** [wxWidgets/Phoenix#1137]
**Operating system**:                        Windows 7
**wxPython version & source**:         4.0.3, Anaconda
**Python version & source**:             3.7.1, Anaconda

**Description of the problem**:

It runs fine on Python 2.7 but on Python 3.7.1 it reports the following error:

PyNoAppError: The wx.App object must be created first!

even after fixing the "super()" parameters for v3.

v2.7: super(HelloFrame, self). __init__(*args,**kw)
v3.7: super().__init__(*args, **kw)

```python
# Put code sample here
```

**Comment by swt2c** [comment]
Which Hello World are you referring to?

**Comment by infinity77** [comment]
@swt2c : yet another one that deserves to be closed.
