### ISSUE TITLE
Add an option in `build.py` to select components

### ISSUE THREAD

**Issue by cykerway** [wxWidgets/Phoenix#1138]
While this is very easy to run:

    python build.py dox etg --nodoc sip build

Can we add some option to selectively enable/disable some components?

I'm trying to build for gtk2 on Fedora 29 but there is not `webkitgtk` any more because it was removed in Fedora 27. (Maybe this is why you [disabled gtk2 builds](https://github.com/wxWidgets/Phoenix/issues/925#issuecomment-417109238) after Fedora 26?)

But currently I don't need webview. In fact I don't have `libwebkitgtk-1.0.so` on my system. But this shouldn't have an effect on other parts of wxWidgets and wxPython. wxWidgets has an `--enable-webview` option, and it automatically disables webview if configure script detects `webkitgtk` is not available. So `build_wx` seems to be working. But I don't see how I can tell `build_py` to ignore webview. Does it sound good if I just comment some lines in `wscript`? Any chance we can get an option in `build.py` for doing that? Thank you.

**Comment by swt2c** [comment]
So, in 4.0.4, there should be stubs automatically generated if wxPython doesn't detect that webview support is built into wxWidgets.  wx.WebView will exist in wxPython, but if you try to instantiate it, it will fail.  Have you tried 4.0.4?

**Comment by cykerway** [comment]
I'm using 4.0.4. What I get is a link failure, if wxWidgets is compiled with `--enable-webview` (I think this is the default) but webkitgtk is unavailable. If so, there should be a warning when configuring wxWidgets. I'm not sure if the stubs would see this as *support is built into wxWidgets*. The compilation fails so I don't have a change to try.

**Comment by cykerway** [comment]
No, I didn't have it on my command line. But the configure script said it didn't find webkitgtk and disabled webview.

**Comment by swt2c** [comment]
Okay, you are right, even with the stubs, wxPython will still try to link with the the webview library unconditionally.

**Comment by cykerway** [comment]
Thanks for confirmation. [This](https://github.com/cykerway/Phoenix/commit/bc1758f437e83be284373ffc2dbd698dc7abe630) is what I'm doing on `wscript`. I haven't experienced anything weird with the build result. If you can confirm this is actually a reasonable way of doing so, that would be great. Fixing the stubs, or having a modular build option in `build.py` would be even better.

**Comment by swt2c** [comment]
Yeah, that's fine for a quick hack for disabling WebView.

Just out of curiosity, why are you wanting/needing to use GTK2?

**Comment by cykerway** [comment]
Ah, I'm old-fashioned old guy?

**Comment by swt2c** [comment]
OK, just checking whether you were running into particular bugs with the GTK3 version.  You will probably have to move on eventually though.  :-)  Even Debian is talking about getting rid of GTK2 in its next version (after Buster).

**Comment by RobinD42** [comment]
Calling this fixed after #1208 and also the ability to generate stubs for missing items.
