### ISSUE TITLE
Missing property/function to set wheel rotation in wx.MouseEvent

### ISSUE THREAD

**Issue by butscher** [wxWidgets/Phoenix#1140]
**Operating system**: Win 7 Pro SP1 64bit
**wxPython version & source**:  4.0.4 32bit from PyPi
**Python version & source**:  3.4.4 32bit stock

**Description of the problem**:

There is no property or function to set the wheel rotation value of a `wx.MouseEvent` (and probably also no way to set wheel axis). Older wxPython versions had `m_wheelRotation` property for this.

**Comment by RobinD42** [comment]
Fixed by #1143
