### ISSUE TITLE
GetMouseEvent() Missing From wx.html.HtmlCellEvent

### ISSUE THREAD

**Issue by tsmorton60** [wxWidgets/Phoenix#1147]
Operating system: any
wxPython version & source: 4.0.5 
Python version & source: any

Description of the problem:

GetMouseEvent() method in wx.html.HtmlCellEvent is not present in Phoenix.

This is needed to determine mouse state (right/left click) with a cell click event.

**Comment by RobinD42** [comment]
Fixed by #1150
