### ISSUE TITLE
wxPython build crashing on Slackware64-Current (Dec 2018)

### ISSUE THREAD

**Issue by BusinessKid** [wxWidgets/Phoenix#1149]
I have Slackware64-Current of December 2018 and the build is failing as detailed here
https://www.linuxquestions.org/questions/showthread.php?p=5951936#post5951936
This appears to be the heart of the matter
---------------------- About 2.5G into install---------
[642/869] Compiling sip/cpp/sip_xmlwxXmlAttribute.cpp
[643/869] Compiling sip/cpp/sip_xrcwxXmlSubclassFactory.cpp
[644/869] Linking build/waf/3.6/gtk3/_html2.cpython-36m-x86_64-linux-gnu.so
/usr/bin/ld: cannot find -lwx_gtk3u_webview-3.0
collect2: error: ld returned 1 exit status

Waf: Leaving directory `/tmp/SBo/wxPython-4.0.4/build/waf/3.6/gtk3'
Build failed
 -> task in '_html2' failed with exit status 1 (run with -v to display more information)
Command '"/usr/bin/python3" /tmp/SBo/wxPython-4.0.4/bin/waf-2.0.8 --wx_config=/tmp/SBo/wxPython-4.0.4/build/wxbld/gtk3/wx-config --gtk3 --python="/usr/bin/python3" --out=build/waf/3.6/gtk3 configure build ' failed with exit code 1.
Finished command: build_py (22m20.866s)
Finished command: build (29m20.533s)
Command '"/usr/bin/python3" -u build.py build' failed with exit code 1.
-----------------------------------------
I get this error using python2 or python3, using pip, or using a Slackbuild (A Slackware script to make a Slackware pkg of source compiles and provide tested options)

For those who don't know Slackware, it's a source compiled distro giving freedom to experienced users. All packages are compiled --with-everything; no -dev packages exist, as it's presumed you want to be able to compile. Full 32/64 systems are possible with their 'compat32' packages. Slackware pkgs are simple, with no dependency checking. Last release was 2016 (due to an ill-disposed BDFL) but the Current is a rolling release, and December's seems stable. I have that iso, although they uploaded a less stable one recently. 
Versions are recent: Kernel-4.19.8; glibc-2.28; gcc-8.2.0; python2.7.15 & python3.6.7; gtk+2.2.24 & gtk+3.3.24, and a pre-installed spew of python and gtk+ miscellaneous oddities. Your 'pip wheel' instruction doesn't get past 1st base, with or without the wxPython  tar.gz. Going at the tar myself, 'python build.py build_wx' compiles, but '…build_py' pukes with the identical error. 
I did check the build with 'pip2 check' & 'pip3 check,' installed the one missing package, and sorted the one versions issue, but the error remains. At this point I need a lifeline.

**Comment by swt2c** [comment]
At the moment, wxPython can't be compiled without WebKit2 support.  If you install the WebKit2 packages you should be able to work around this problem.

**Comment by BusinessKid** [comment]
Thank you. Slackware64 is largely a 'compile it yourself' distro when it comes to less ordinary stuff like this. My target was to compile Invesalius. I had already got 2.5G of increased space in the wxPython compile.  This means I have to
    Install geoclue2, woff2, hyphen, libwebp (and THEIR dependencies)
    Then install webkit2gtk
    Then retry wxPython4.0.4 which has already got 2.5G of disk space, which is just one dependency of Invesalius.
    Then retry Building Invesalius, whose build apparatus I have no confidence in. 

Frankly, I'm a loser if I put myself through all of that when I have a VM with Invesalius installed in Mint.
and a separate backup Mint bootable install with reasonable graphics. Fine for dependency checked systems and derivatives.
