### ISSUE TITLE
wx.ProgressDialog.ShowModal() does not block in Windows

### ISSUE THREAD

**Issue by cwassert** [wxWidgets/Phoenix#1152]
**Operating system**: Windows 10
**wxPython version & source**: wxPython 4.0.4
**Python version & source**: python 3.7.1

**Description of the problem**:
The function ShowModal() of a wx.ProgressDialog does not block (on Linux is does, but in Windows it does not).

The following demo illustrates the problem. Run it and click File->About.
Expected behavior: only `message 1` is printed.
Observed behavior: `message 1` and `message 2` are printed.

```python
import wx

class MainWindow(wx.Frame):
    def __init__(self, parent, title):
        wx.Frame.__init__(self, parent, title=title, size=(200,100))
        filemenu= wx.Menu()
        menuAbout = filemenu.Append(wx.ID_ABOUT, "&About"," Information about this program")
        menuBar = wx.MenuBar()
        menuBar.Append(filemenu,"&File")
        self.SetMenuBar(menuBar)
        self.Bind(wx.EVT_MENU, self.OnAbout, menuAbout)
        self.Show(True)

    def OnAbout(self,e):
        # dlg = wx.MessageDialog(self, "A small text editor", "About Sample Editor", wx.OK)
        dlg = wx.ProgressDialog('Caption', 'Description', parent=self)
        print('message 1')
        dlg.ShowModal()
        print('message 2')
        dlg.Destroy()

app = wx.App(False)
frame = MainWindow(None, "Sample editor")
app.MainLoop()
```

**Comment by liimiing** [comment]
yes，same problem...

**Comment by RobinD42** [comment]
That's because wxWidgets is now using the native progress dialog on Windows and it is designed to not be used modally, IIRC. If that doesn't work for your needs then you can use `wx.GernericProgressDialog` instead.
