### ISSUE TITLE
wx.LOCALE_DONT_LOAD_DEFAULT & wx.LOCALE_LOAD_DEFAULT missing

### ISSUE THREAD

**Issue by topic2k** [wxWidgets/Phoenix#1155]
**Operating system**: Ubuntu & Windows 10

**wxPython version & source**: 4.0.4 gtk3 (phoenix) wxWidgets 3.0.5, pypi
**Python version & source**: Python 2.7.15+ (default, Oct  2 2018, 22:12:08) Ubuntu

**wxPython version & source**: 4.0.4 msw (phoenix) wxWidgets 3.0.5, pypi
**Python version & source**: Python 2.7.15 Stackless 3.1b3 060516 (default, Jun 24 2018, 16:09:29) [MSC v.1500 32 bit (Intel)] on win32

**Description of the problem**:

The constants `wx.LOCALE_DONT_LOAD_DEFAUL`T & `wx.LOCALE_LOAD_DEFAULT` are missing. ([wx.Locale.Init](https://docs.wxpython.org/wx.Locale.html#wx.Locale.Init))

**Comment by swt2c** [comment]
https://github.com/wxWidgets/wxWidgets/pull/1216

**Comment by RobinD42** [comment]
Fixed by #1157
