### ISSUE TITLE
Managing FloatCanvas ??

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [wxWidgets/Phoenix#1166]
I've had a bit of renewed interest in FloatCanvas lately,and I'm wondering how to manage it.

Ideally, we'd keep all code here -- no reason to have a fork anywhere else.

But I want to be able to handle issues, PRs, etc reasonably. I propose:

1) I get commit rights to this repo -- I promise not to mess with anything else :-)

2) we create a FloatCanvas label to keep things organized.

Alternatively, I could fork this entire repo, and manage everything FloatCanvas related there, doing PRs when there is something to update.

NOTE: there's some interest, but I have a lot of other things on my plate, so it won't be a whole lot :-)

@RobinD42: how would you like to manage this?

**Comment by RobinD42** [comment]
Another possibility to consider is to have a separate repo for just FloatCanvas and then reference it from here as a submodule (the way wxWidgets is currently pulled in to the Phoenix source tree). As part of Phoenix's build we can update the FloatCanvas code in `./wx/lib/FloatCanvas`, `./demo/FloatCanvas.py` and etc. from the submodule folder in `./ext`.

**Comment by RobinD42** [comment]
Forgot to mention some benefits: Using a submodule means that FloatCanvas can have it's own branches, can progress at its own pace, and so on without impacting wxPython development. Phoenix would only get a new version of the code when we update the submodule revision reference here.

**Comment by ChrisBarker-NOAA** [comment]
hmm -- that could be a good way to go. Personalhy, I've generally found that submodules are more trouble than they are worth -- but this actually looks like a good use case.

One issue though -- the real code is all in wx/lib/floatcanvas, but there are examples in teh samples dir, and some code in the demo, and hopefully some documentation some day.

Wouldn't it make it kinda hard to keep all of that in sync?

But let's wait and see if I really do find time to work on it before actually doing anything new :-)

Thanks,

-CHB

**Comment by RobinD42** [comment]
Not ideal, maybe too fragile, but my thought was that there would be top-level folders in the submodule repo that would then get copied to the right places in wxPython's tree as part of wxPython's build. So there would be `./wx/lib/floatcanvas`, `./demo`, `./samples`, etc.

**Comment by ChrisBarker-NOAA** [comment]
OK, this seems reasonable enough -- if/when I get around to making real updates, I'll start a repo and give this a try.

closing this for now.
