### ISSUE TITLE
ToolTip never showing

### ISSUE THREAD

**Issue by RoxStefania** [wxWidgets/Phoenix#1172]
ToolTip is not working, I tried to Bind the handler with the wx.EVT_TREE_ITEM_GETTOOLTIP like presented in the demo, but it's never triggered. 

Python 3.5.2
wxPython 4.0.4
OS: Windows 7

self.Bind(wx.EVT_TREE_ITEM_GETTOOLTIP, self.OnToolTip)

class SDHyperTreeList(BaseHyperTreeList):
    def __init__(self):
        self.Bind(wx.EVT_TREE_ITEM_GETTOOLTIP, self.OnToolTip)

    def OnToolTip(self, event):
        event.SetToolTip(wx.ToolTip("----"))

**Comment by RobinD42** [comment]
Please create a small, runnable sample that demonstrates this problem.
