### ISSUE TITLE
py2exe build error on windows

### ISSUE THREAD

**Issue by leileigong** [wxWidgets/Phoenix#1176]
![image](https://user-images.githubusercontent.com/12391734/53558817-c4cc7900-3b83-11e9-9a5e-6c7ce41e01a2.png)

running py2exe
*** searching for required modules ***
*** parsing results ***
*** finding dlls needed ***
error: [Errno 2] No such file or directory: 'api-ms-win-core-libraryloader-l1-2-1.dll'
Process finished with exit code 1

**Comment by leileigong** [comment]
now I got another error, about "libopenblas":

running py2exe
*** searching for required modules ***
*** parsing results ***
*** finding dlls needed ***
error: [Errno 2] No such file or directory: 'libopenblas.JKAMQ5EVHIVCPXP2XZJB2RQPIN47S32M.gfortran-win32.dll'

**Comment by infinity77** [comment]
Is this the result of using py2exe on a simple wxPython application? What packages are you importing?
Seeing this openblas and gfortran stuff popping out reminds me of the pointless numpy/scipy DLL hell on Windows...

**Comment by leileigong** [comment]
it's not a simple wxpython application, also depending other packages. 
for the same application, py2exe works fine on windows10.
and also if switch to wxpython3.0.2, py2exe works fine on windows7 and windows 10.

**Comment by kg-2** [comment]
seems like a py2exe issue- It hasn't been updated in about a decade. Probably time to switch to cx_freeze or pyinstaller

**Comment by leileigong** [comment]
i have switch to pyinstaller.thanks.
