### ISSUE TITLE
ListItem.SetBackgroundColour() has no effect

### ISSUE THREAD

**Issue by chiizujin** [wxWidgets/Phoenix#1178]
**Operating system**: Linux Mint 17.1
**wxPython version & source**: 4.0.4 gtk3 (phoenix) wxWidgets 3.0.5 (pypi)
**Python version & source**: 3.4.3 (distro)

**Description of the problem**:

ListItem.SetBackgroundColour() does not change the item's background colour and appears to have no effect at all. However, ListCtrl.SetItemBackgroundColour() can be used instead.

Although not tested thoroughly, ListItem.SetTextColour() also appears not to work.

```python
# Where "list" is a ListCtrl containing one item:

print(list.GetItem(0).GetBackgroundColour())
# Output (initial value): (-1, -1, -1, 255)
list.GetItem(0).SetBackgroundColour((100, 100, 100))
# Result: Item's background colour does not change.
print(list.GetItem(0).GetBackgroundColour())
# Output: (-1, -1, -1, 255)

# ListCtrl.SetItemBackgroundColour() works as expected:

list.SetItemBackgroundColour(0, (100, 100, 100))
# Result: Item's background colour changes.
print(list.GetItem(0).GetBackgroundColour())
# Output: (100, 100, 100, 255)
```

**Comment by RobinD42** [comment]
IIRC this is due to `GetItem` not returning a reference to the live *native* item in use in the ListCtrl, but rather a new item object that is filled with the relevant details of the real one. So to make a change, you need to call `SetItem` with your modified item object.

**Comment by chiizujin** [comment]
Thanks for the reply, Robin. That works as you suggest.

This achieves the desired result:
```python
item = list.GetItem(0)
item.SetBackgroundColour((100, 100, 100))
list.SetItem(item)
```

**Comment by whereisyong** [comment]
I'm running wxPython 4 on MacOs BigSur, M1. with @RobinD42 's suggestion, I found the SetItemBackgroundColour() still doesn't work, but I can update text.

here below is my test code, can you help check it pls @RobinD42 ? thank you!

import wx
import wx.lib.mixins.listctrl  as  listmix

class MyPanel(wx.Panel):
    def __init__(self, parent):
        wx.Panel.__init__(self, parent)
        self.SetBackgroundColour("white")

        rows = [("Tom", "11"),
                ("Ede", "11"),
                ("Jerry", "10")
                ]
        self.list_ctrl = wx.ListCtrl(self, style=wx.LC_REPORT)
        self.list_ctrl.SetBackgroundColour(wx.Colour(255,246,189,255))
        self.list_ctrl.SetTextColour('black')
        
        self.list_ctrl.InsertColumn(0, "Col1")  
        self.list_ctrl.InsertColumn(1, "Col2")  # Revenue this Q than last Q 

        
        index = 0
        for row in rows:
            self.list_ctrl.InsertStringItem(index, row[0])
            self.list_ctrl.SetStringItem(index, 1, row[1])

            if int(row[1]) <= 10: #current PE is 50% down than 52w high
                item = self.list_ctrl.GetItem(1,1)
                item.SetText("888") # successfully changed
                item.SetBackgroundColour('Blue') #not changed
                self.list_ctrl.SetItem(item)

                print(item.GetText())
                print(item.GetBackgroundColour())

            index += 1
        
        sizer = wx.BoxSizer(wx.VERTICAL)
        sizer.Add(self.list_ctrl, 0, wx.ALL|wx.EXPAND, 5)
        self.SetSizer(sizer)
        

class MyFrame(wx.Frame):
    def __init__(self):
        """Constructor"""
        wx.Frame.__init__(self, None, wx.ID_ANY,"test")
        panel = MyPanel(self)
        self.Show()
        
if __name__ == "__main__":
    app = wx.App(False)
    frame = MyFrame()
    app.MainLoop()

**Comment by lojack5** [comment]
I just ran into this issue recent, and it appears both `ListItem.SetTextColour` (followed by `ListCtrl.SetItem`) and `ListCtrl.SetItemTextColour` do nothing when supplied with `wx.NullColour`.

reproducer:
```
import wx

if __name__ == '__main__':
    app = wx.App()
    frame = wx.Frame(None)
    list = wx.ListCtrl(frame, style=wx.LC_REPORT)
    list.AppendColumn('')
    list.InsertItem(0, 'text')
    print(list.GetItemTextColour(0))
    list.SetItemTextColour(0, 'red')
    print(list.GetItemTextColour(0))
    list.SetItemTextColour(0, wx.NullColour)
    print(list.GetItemTextColour(0))
```
output:
```
(-1, -1, -1, 255)
(255, 0, 0, 255)
(255, 0, 0, 255)
4.2.1a1 msw (phoenix) wxWidgets 3.2.2
```

This is on Windows 11.

In the meantime, I'm looking for a workaround. What would be the correct system color to poll for the default text color, `wx.SYS_COLOUR_LISTBOXTEXT`?
