### ISSUE TITLE
Vertical sizer with checkboxes takes unneeded space

### ISSUE THREAD

**Issue by DarkFenX** [wxWidgets/Phoenix#1181]
Debian Testing x86-64
Xorg, GNOME 3 with standard theme, 3840x2160 with 200% UI scaling
Python 3.7.2
wxPython version: 4.0.4 (wxWidgets 3.0.4) from debian repos

```python

import wx


class MainFrame(wx.Frame):

   def __init__(self):
       wx.Frame.__init__(self, None, wx.ID_ANY, 'test')
       self.Maximize()
       self.Show()
       self.showModal()

   def showModal(self):
       dlg = ModalDialog(self)
       dlg.ShowModal()
       dlg.Destroy()


class ModalDialog(wx.Dialog):

   def __init__(self, parent):
       wx.Dialog.__init__(self, parent, id=wx.ID_ANY, title="Dialog", size=(-1, -1), style=wx.DEFAULT_DIALOG_STYLE)
       mainSizer = wx.BoxSizer(wx.VERTICAL)

       radio1 = wx.RadioButton(self, wx.ID_ANY, 'radio1', style=wx.RB_GROUP)
       mainSizer.Add(radio1, 1, wx.EXPAND | wx.ALL, 5)

       cbSizer1 = wx.BoxSizer(wx.VERTICAL)
       checkbox11 = wx.CheckBox(self, -1, 'checkbox11')
       cbSizer1.Add(checkbox11, 1, wx.EXPAND | wx.TOP | wx.BOTTOM, 3)
       mainSizer.Add(cbSizer1, 1, wx.EXPAND | wx.LEFT, 20)

       radio2 = wx.RadioButton(self, wx.ID_ANY, 'radio2')
       mainSizer.Add(radio2, 1, wx.EXPAND | wx.ALL, 5)

       cbSizer2 = wx.BoxSizer(wx.VERTICAL)
       checkbox21 = wx.CheckBox(self, -1, 'checkbox21')
       cbSizer2.Add(checkbox21, 1, wx.EXPAND | wx.TOP | wx.BOTTOM, 3)
       checkbox22 = wx.CheckBox(self, -1, 'checkbox22')
       cbSizer2.Add(checkbox22, 1, wx.EXPAND | wx.TOP | wx.BOTTOM, 3)
       checkbox23 = wx.CheckBox(self, -1, 'checkbox23')
       cbSizer2.Add(checkbox23, 1, wx.EXPAND | wx.TOP | wx.BOTTOM, 3)
       mainSizer.Add(cbSizer2, 1, wx.EXPAND | wx.LEFT, 20)

       buttonSizer = self.CreateButtonSizer(wx.OK | wx.CANCEL)
       if buttonSizer:
           mainSizer.Add(buttonSizer, 1, wx.EXPAND | wx.ALL, 5)
       self.SetSizer(mainSizer)
       self.Fit()
       self.Center()

app = wx.App(False)
mf = MainFrame()
app.MainLoop()
```

First sizer with checkboxes has enough height to fit 3 rows with checkboxes:
![image](https://user-images.githubusercontent.com/275209/54075848-43789300-42b5-11e9-9243-d5c70f9bb292.png)

However, when amount of checkboxes in the second checkbox sizer is reduced to 1, height of the first checkbox sizer is also reduced (and buttons disappear but it might be another bug).
![image](https://user-images.githubusercontent.com/275209/54075902-b550dc80-42b5-11e9-85e9-125e239e2f16.png)

Overall, looks like it takes height of the highest checkbox sizer I am using in dialog and applies it to all checkbox sizers. If i have 3 radio buttons with 3, 4 and 1 checkboxes beneath each, all of them will have enough vertical space to house 4 checkbox rows.

Expected: take enough vertical space to fit amount of checkboxes this specific sizer has, not more, on a per-sizer-instance basis.

**Comment by cbeytas** [comment]
This is because 'proportion' is set to 1 for every item being added to the sizer.
That instructs the sizer to keep all items proportional to each other, so they will all get assigned the same amount of space. When the largest item is shrunk (3 checkboxes to 1), they all shrink.

Keywords should always be used as it makes it more clear what's happening:
```mainSizer.Add(cbSizer1, proportion=1, flag=wx.EXPAND | wx.LEFT, border=20)```

**Comment by DarkFenX** [comment]
@cbeytas how do sizers know to which sizer they should keep proportion? Are they all just take the same height?

**Comment by blitzmann** [comment]
@DarkFenX it's based on the sizer it's being attached to I believe

If you open up the wx inspector, you can see that the `mainSizer` has for elements in it (i had to change the dialog to a frame for this):

1) Radio button
2) Sizer that contains the checkbox
3) second radio button
4) Second sizer which contains more checkboxes

![image](https://user-images.githubusercontent.com/3904767/54498235-f1e68e80-48da-11e9-97ed-409c40884ab9.png)

So, if they were all set to `porportion=1`, they would all have an equal height. If only a couple at set to 1, then those are are set to 1 are going to take the same size as the largest one that is set to 1.

That's the way I have always understood them. :)

**Comment by DarkFenX** [comment]
My expectation was that with proportion=1 sizers would scale to fill their parent object, and proportions would be depending on content of each sizer (roughly speaking, 2 times more more checkboxes - 2 times more space).

For maintainers - if it was conscious design decision by authors of wx, feel free to close this issue.
