### ISSUE TITLE
Hidden element doesn't receive proper size upon receiving updated label

### ISSUE THREAD

**Issue by DarkFenX** [wxWidgets/Phoenix#1182]
Debian Testing x86-64
Python 3.7.2
wxPython version: 4.0.4 (wxWidgets 3.0.4) from debian repos
DE (affects both):
- Xorg, GNOME 3 with standard theme, 3840x2160 with 200% UI scaling
- wayland, GNOME 3 with standard theme, 1920x1080

```python

import wx


class MainFrame(wx.Frame):

    def __init__(self):
        wx.Frame.__init__(self, None, wx.ID_ANY, 'test')
        # self.Maximize()

        box = wx.BoxSizer(wx.HORIZONTAL)

        lbl1 = wx.StaticText(self, wx.ID_ANY, "0")
        box.Add(lbl1, 0, wx.ALIGN_CENTER | wx.LEFT, 5)

        box.Add(wx.StaticText(self, wx.ID_ANY, "/"), 0, wx.ALIGN_CENTER)

        lbl2 = wx.StaticText(self, wx.ID_ANY, "0")
        box.Add(lbl2, 0, wx.ALIGN_CENTER)

        self.SetSizer(box)
        self.Show()
        box.ShowItems(False)
        lbl1.SetLabel('1')
        lbl2.SetLabel('1')
        box.ShowItems(True)



app = wx.App(False)
mf = MainFrame()
app.MainLoop()
```

![image](https://user-images.githubusercontent.com/275209/54394723-bec7b380-46be-11e9-82d6-83f6137c83aa.png)

As you can see, when I instruct app to show labels, they do not contain any values visually (they do programmatically, in Label and LabelText attributes of lbl1 / lbl2).

**Comment by DarkFenX** [comment]
When I set label while element is shown - size is (8, 19), when i set it while it's hidden - size is (1, 0).

**Comment by blitzmann** [comment]
Can confirm that this problem doesn't present in Windows. Unsure about mac

**Comment by RobinD42** [comment]
You can use `InvalidateBestSize` to tell the sizer to recalculate the sizes on the next layout. So, in your example after the `ShowItems`:

```python
        lbl1.InvalidateBestSize()
        lbl2.InvalidateBestSize()
        self.Layout()
```

**Comment by DarkFenX** [comment]
Thanks, it worked.
