### ISSUE TITLE
wx.Choice cuts off if the items inside of it are larger than it's container

### ISSUE THREAD

**Issue by blitzmann** [wxWidgets/Phoenix#1184]
**Operating system**: Ubuntu (GTK3)
**wxPython version & source**:   4.0.3
**Python version & source**:  3.6
**Description of the problem**:

If I have a wxChoice with items inside of it that are larger than the containing Window, the widget itself seems to continue to grow towards the left, but is hidden by any other elements (or the edge of the window). It would be nice to have a workaround 

```python
import wx


class TestPanel(wx.Panel):
    def __init__(self, parent):
        wx.Panel.__init__(self, parent)
        mainSizer = wx.BoxSizer(wx.HORIZONTAL)
        self.SetSizer(mainSizer)

        # cache current selection to fall back in case we choose to open char editor
        self.charCache = None

        self.charChoice = wx.Choice(self)
        mainSizer.Add(self.charChoice, 1, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT | wx.LEFT, 3)
        self.charChoice.Append("123456789012345678901234567890123456789012345678901234567890")

class Frame(wx.Frame):
    def __init__(self, title, size=(200, 100)):
        wx.Frame.__init__(self, None, title=title, size=size)
        self.statusbar = self.CreateStatusBar()
        main_sizer = wx.BoxSizer(wx.VERTICAL)
        panel = TestPanel(self)
        main_sizer.Add(panel)
        self.SetSizer(main_sizer)

app = wx.App(redirect=False)   # Error messages go to popup window
top = Frame("Test")
top.Show()
app.MainLoop()
```

Looks like this:

![image](https://user-images.githubusercontent.com/3904767/54469218-a2ce1b80-476b-11e9-9adb-1dea4c17bea7.png)

Notice how it shows the selected item right-align (when I would have assumed it would be left aligned), and the widget itself is truncated on the left. It almost seems like it doesn't resize itself to the window.

A more complex example is shown here, and is what spawned this issue:

https://github.com/pyfa-org/Pyfa/issues/1881

If this is a wx issue, I'm open for any python workarounds :) thanks!

**Comment by kg-2** [comment]
This doesn't seem to be a defect. You're limiting your frame width to 200 pixels. If you set your frame size to (600, 200) it works fine. Without looking at the code of your more complex example it looks like the panel needs to call Layout() to resize the items.
