### ISSUE TITLE
wxPython-4.0.4 tar file is incomplete

### ISSUE THREAD

**Issue by HJarausch** [wxWidgets/Phoenix#1186]
The file wxPython-4.0.4.tar.gz contains an empty folder ext/wxWidgets which breaks
building this package.

Many thanks for a hint,
Helmut

**Comment by swt2c** [comment]
Where did you get the tar file?  I believe https://pypi.org/project/wxPython/4.0.4/#files is the canonical location.

**Comment by Metallicow** [comment]
You can't comment at this time — your comment cannot be blank.

**Comment by RobinD42** [comment]
Yes, if `ext/wxWidgets` is empty then that is likely an archive built by GitHub, not the one from PyPI. The difference is that the latter has had wxWidgets checked out into it, and also about 1.3 million lines or so of generated code is also included. To use the source archive from GitHub you'll need to run the extra commands that fetches or generates all the missing code, but to build a released version it's much easier to just use a released source archive IMO.
