### ISSUE TITLE
AUI broken

### ISSUE THREAD

**Issue by jmoraleda** [wxWidgets/Phoenix#1190]
**Operating system**: Linux debian buster up to date  (this is debian testing, but it is in full freeze and will become the latest debian stable release in a few weeks)

**wxPython version & source**:       self built from latest master branch in github repository (including self-built wxWidgets), but the same problem occurs with the version of phoenix and wxwidgets shipped from official debian buster repositories. (4.0.4)

**Python version & source**: Python 3.7.3rc1 installed from official debian buster repositories

**GTK version & source**: 3.24.5 from official debian buster repositiories

AUI has become unusable:
  * In the **AUI_DockingWindowMgr** demo the floating panes cannot be dragged. 
  * In the **Aui_MDI** demo the following errors are seen:
     (demo.py:1380): GLib-GObject-WARNING **: ... : invalid cast from 'wxPizza' to 'GtkWindow'
     (demo.py:1380): Gtk-CRITICAL **: .. : gtk_window_get_has_resize_grip: assertion 'GTK_IS_WINDOW (window)' failed
     Gdk-Message: ... : Unable to load sizing from the cursor theme
 

I think this may be part of a larger problem because there are also several warnings when the demo starts of the form:
(demo.py:29824): Gtk-CRITICAL **: ... : gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook
...
(demo.py:29824): Gtk-CRITICAL **: .... : gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
... and then at other times:
(demo.py:2345): GLib-GObject-WARNING **: 00:04:22.132: instance with invalid (NULL) class pointer
(demo.py:2345): GLib-GObject-CRITICAL **: 00:04:22.132: g_signal_emit_by_name: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
(demo.py:2345): GLib-GObject-CRITICAL **: 00:04:22.132: g_object_get: assertion 'G_IS_OBJECT (object)' failed

I am not familiar with the internals of phoenix and wx, but I am an experienced developer in both C and Python and currently have some time to help debug these issues with help. 
In case it is relevant, I am using gnome under wayland.

**Comment by infinity77** [comment]
Hi, I guess this refers to the wx.aui module. Do you get the same issues by running the pure-Python wx.lib.agw.aui? There is a demo of it in the AGW tree in the wxPython demo.

**Comment by jmoraleda** [comment]
@infinity77 Hi. Yes. my report above referred to the wx.aui module, but I just checked and the problem also exists in the pure -Python wx.lib.agw.aui. When opening the demo, the following warnings appear:

**Comment by jmoraleda** [comment]
Further debugging points out that this is a wayland vs xorg issue, not an AUI issue. Everything works as expected with the same versions of python and gtk  when running gnome under xorg instead of gnome under wayland, so I am closing this bug and will open a new one that address the xorg vs wayland issue more specifically. Thank you.
