### ISSUE TITLE
Build instructions seem outdated

### ISSUE THREAD

**Issue by ReblochonMasque** [wxWidgets/Phoenix#1207]
Build instructions in readme and docs seem outdated, and are missing the newer `pip install` capability.

I am not qualified to update the build instructions; however, I would be glad to add the part regarding #1205 `pip`, and the use of `python.app` #1206 in the readme & the docs.

Cheers.

**Comment by RobinD42** [comment]
https://github.com/wxWidgets/Phoenix/commit/c1cab5ee7c8381498d2ec83cc20aed4fd89b9cc4
