### ISSUE TITLE
'sashPosition=0' doesn't work correctly in SplitVertically of wx.SplitterWindow

### ISSUE THREAD

**Issue by vainquit** [wxWidgets/Phoenix#1212]
**Operating system**:Windows 10
**wxPython version & source**: wxPython 4.0.4
**Python version & source**:  Python 3.68 :: Anaconda custom(64-bit)

**Description of the problem**:
There is a parameter named "sashPosition" in the method SplitVertically(self, window1, window2, sashPosition=0). In official document,it says:
"**sashPosition (int) – The initial position of the sash....... specify 0 (default) to choose the default position (half of the total window width).**"
But it doesn't work correctly in my code. The window indeed is splited into two subwindows,however, the left window is far more thinner than the right one,absolutely not “half of the total window width”.

In fact, there has been a guy who encountered totally the same problem with me, and he has described the problem with more details:
 (https://stackoverflow.com/questions/32195823/wxpython-wxsplitterwindow-splitvertically-always-shows-uneven-split)

But the problem remains.

```python
# Here is my own code sample:
`
import wx

app = wx.App()
frm = wx.Frame(None,size=(600,600))

spl=wx.SplitterWindow(frm,wx.SP_3D)
left=wx.Panel(spl)
right=wx.Panel(spl)
spl.SplitVertically(left,right,sashPosition=0)
left.SetBackgroundColour(wx.RED)
right.SetBackgroundColour(wx.BLUE)

frm.Show()
app.MainLoop()

`

```
![2019-04-24 02 15 40](https://user-images.githubusercontent.com/42118069/56605491-e0f60f00-6636-11e9-807b-fc32c4a12a4b.jpg)

**Comment by RobinD42** [comment]
At the time you call `SplitVertically` the splitter window is still at it's default size, which is probably (20,20), so yes it did work given that size. Instead you'll want to delay the call to `SplitVertically` until after the event loop is running and the frame has had a chance to get it's first `EVT_SIZE` event and resize the splitter to fill the frame. `wx.CallAfter` can help with that.
