### ISSUE TITLE
*updated: inconsistent tab order for obj.Navigate() on OSX 10.14

### ISSUE THREAD

**Issue by kg-2** [wxWidgets/Phoenix#1216]
**Operating system**: OSX 10.14.4 on virtual machine VMWare Workstation 15
**wxPython version & source**:        4.0.4 cocoa osx  wx-widgets 3.0.5, installed via pip
**Python version & source**:            stock 3.6.8

**Description of the problem**: I'm getting multiple segmentation faults at varying times. It's a moderately complex program that works fine on windows.  I'll work on creating a runnable script, in the meantime here's the apple error report

***UPDATE

It turns out that I created an infinite loop by binding EVT_SET_FOCUS to two widgets. When the first widget received the focus, the handler called `Navigate()` which would set the focus to the 2nd widget, which would call `Navigate()` and set the focus back to the 1st widget and repeat forever. I had expected that `Navigate()` would traverse the dialog's children, stopping on the 3rd widget which was not bound to EVT_SET_FOCUS (which it does on windows). It acts like the tab order is different depending on which widget calls `Navigate()`.

```python
import wx
import traceback

app = wx.App()


def on_set_focus(event):
    obj = event.GetEventObject()
    print(f"on_set_focus called for {obj}, navigating")
    obj.Navigate()


def make_dialog(frame):
    # dialog = wx.Dialog(frame, size=(300, 300), style=wx.TAB_TRAVERSAL)
    dialog = wx.Dialog(frame, size=(300, 300), style=0)
    tc = wx.TextCtrl(dialog, wx.ID_ANY, "Text Control", style=wx.TE_MULTILINE | wx.TE_NO_VSCROLL | wx.TE_READONLY |
                                                              wx.TE_CENTRE | wx.NO_BORDER)
    lc = wx.ListCtrl(dialog, pos=(0, 50), size=(150, 50))
    btn2 = wx.Button(dialog, label="Button", pos=(0, 150))

    dialog.Show()

    tc.Bind(wx.EVT_SET_FOCUS, on_set_focus)
    lc.Bind(wx.EVT_SET_FOCUS, on_set_focus)


def run():
    print("starting test")
    frame = wx.Frame(None, title="Test Frame", size=(200, 200))
    frame.Show()
    wx.CallAfter(make_dialog, frame)
    app.MainLoop()


if __name__ == "__main__":
    try:
        run()
    except:
        traceback.print_exc()

```

**Comment by RobinD42** [comment]
On OSX buttons do not get the focus by default. For some reason way back in the dark ages somebody at apple decided that users would never think it possible to tab to a button (and some other types of widgets) and would only ever need/want to interact with them using the mouse.

There is a System Preference to change it (System Preferences -> Keyboard -> Shortcuts -> Full Keyboard Access) to be able to tab to all controls, but you can't count on it being set one way or the other unless you're the only one who ever runs your application. Your focus handlers will need to get a little smarter to prevent the recursion.
