### ISSUE TITLE
GetHandle() returns 0 on Linux

### ISSUE THREAD

**Issue by mitras2** [wxWidgets/Phoenix#1217]
**Operating system**: Manjaro Linux x64 (updated today), GTK 3.24.8-1, GNOME 3.32.1
**wxPython version & source**:        wxPython 4.0.4 (pip) (also tested on wxPython 4.0.2 [venv pip])
**Python version & source**:            Python 3.7.3 (Stock from the Manjaro-Packages, and venv, booth having the same problem)

**Description of the problem**:
I was trying to run the CEFPython-wxPython example app from [https://github.com/cztomczak/cefpython/blob/master/examples/wxpython.py](https://github.com/cztomczak/cefpython/blob/master/examples/wxpython.py). While it did run fine on my Windows machine it always stopped at line 174 `assert self.browser_panel.GetHandle(), "Window handle not available"` because the function `GetHandle()` returned an integer 0 on Linux.
I did a little debugging and found out, that even if I wait up to 8 seconds I do not get an Handle for the Frame or for the Panel. Did a little Debugging on another application of mine and found out that `GetHandle()` always returns an integer 0 there for every Frame and Panel available.

**Comment by RobinD42** [comment]
Is it an X11-based system or Wayland? The [current code](https://github.com/wxWidgets/Phoenix/blob/master/src/window_ex.cpp) for the generic GetHandle implementation uses `GDK_WINDOW_XID` which probably evaluates to 0 for non-X11 builds of GTK/GDK.

If somebody can provide the equivalent code for non-X11 GTK builds I'll apply a PR, but I don't have anything I can test it on currently.

That said, you should probably make sure that CEFPython works with non-X11 handle equivalents.

**Comment by mitras2** [comment]
Thanks for your response:
I just had a look at my system and yes: I am using Wayland (and a GTK-Build for wayland).
Sadly I am not a C++ developer and I'm not into wayland. So I will probably not be able to submit a PR.

Using Manjaro Linux is a very quick way to get a working wayland based system running, if someone with the appropriate knowledge is interested in fixing this problem :-)

In the meantime I'll try to find out whether CEFPython does work with non-X11 handles.

**Comment by ikarlmarx** [comment]
Still not fixed?

**Comment by ikarlmarx** [comment]
I have the same problem when I run GetHandle() in ubuntu 21.10.  But  when I run it in Visual Studio Code, it works well.
Still not fixed?

**Comment by unawarez** [comment]
I'm happy to try writing a patch for this, but I have a couple questions for the maintainers:
1. The [GetHandle docs](https://docs.wxpython.org/wx.Window.html#wx.Window.GetHandle) say this returns a GtkHandle on GTK, but the current code is returning e.g. an XID on X11. So just to be sure, for Wayland this should return a wl_surface pointer, and maybe I could add a documentation edit to the PR as well?
2. Not knowing the type of the handle is an issue for me trying to use GetHandle. If it can be either an X11 or Wayland handle, my code needs to guess which type it is, and if I guess wrong it will crash. Now, I can probably guess right 99.9% of the time, but still it would be nice to avoid this. If GetHandle *did* return a GtkWidget pointer, I could use a bunch of GTK functions to figure out if the GdkDisplay is an X11 or Wayland or etc display. But even then I need to be sure in the first place it's a GtkWidget pointer, and also make sure my code is building against the same GTK version as wxPython. So: would you also be willing to add a new piece of API, something like `GetHandleType`, that returns in some way what the windowing backend/handle type is? The implementation of `GetHandle` will need to figure this out to some extent anyway, so might be able to share that code. If you'd have any interest in merging something like that, I could work on that too.

FWIW my use-case is creating an OS child window, for which you need the parent window handle, and then you need to know which windowing API to call and pass the handle to.

**Comment by swt2c** [comment]
>     1. The [GetHandle docs](https://docs.wxpython.org/wx.Window.html#wx.Window.GetHandle) say this returns a GtkHandle on GTK, but the current code is returning e.g. an XID on X11. So just to be sure, for Wayland this should return a wl_surface pointer, and maybe I could add a documentation edit to the PR as well?

Yes, it seems like a `wl_surface` pointer would be the Wayland equivalent.
 
>     2. Not knowing the type of the handle is an issue for me trying to use GetHandle. If it can be either an X11 or Wayland handle, my code needs to guess which type it is, and if I guess wrong it will crash. Now, I can probably guess right 99.9% of the time, but still it would be nice to avoid this. If GetHandle _did_ return a GtkWidget pointer, I could use a bunch of GTK functions to figure out if the GdkDisplay is an X11 or Wayland or etc display. But even then I need to be sure in the first place it's a GtkWidget pointer, and also make sure my code is building against the same GTK version as wxPython. So: would you also be willing to add a new piece of API, something like `GetHandleType`, that returns in some way what the windowing backend/handle type is? The implementation of `GetHandle` will need to figure this out to some extent anyway, so might be able to share that code. If you'd have any interest in merging something like that, I could work on that too.

We probably can't change the existing implementation (from returning an XID on X11), so we probably need to maintain that.  We could add new stuff, though.  You can probably look at the wxMediaCtrl implementation in wxWidgets, as it has to deal with this same problem.  See https://github.com/wxWidgets/wxWidgets/blob/master/src/unix/mediactrl_gstplayer.cpp#L197 and wxGtkGetIdFromWidget.

**Comment by unawarez** [comment]
Great, thanks for the link. Already found some helpful wxWidgets functions in there. Agreed that changing GetHandle would break all of today's working code. I will start a PR soon-ish and link this issue. Thanks!
