### ISSUE TITLE
Import of wx.html2 fails when installing wxpython via pip

### ISSUE THREAD

**Issue by DarkFenX** [wxWidgets/Phoenix#1220]
Debian testing, amd64. If I install wxpython info venv the following way:
```
$ python3 -m venv ~/venv_wx/
$ cd venv_wx/
$ source bin/activate
$ pip3 install wheel
$ pip3 install -v --no-cache-dir --log venv_wx.log wxPython==4.0.4
```

And import html2, it segfaults:
```
$ python3
Python 3.7.3rc1 (default, Mar 13 2019, 11:01:15) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import wx.html2
Segmentation fault
$
```
Build log: [venv_wx.zip](https://github.com/wxWidgets/Phoenix/files/3152780/venv_wx.zip)

Reportedly, issue did not occur on 4.0.0b2 (unsure about versions after that).

**Comment by swt2c** [comment]
You need to install `libwebkit2gtk-4.0-dev` package before attempting to install wxPython.  I don't know why it segfaulted, though.  I would have expected a missing symbol error.

**Comment by DarkFenX** [comment]
Thanks, it worked. However, I will leave this issue open - I believe it would be better if build failed instead of segfaulting on runtime.

**Comment by swt2c** [comment]
Robin has changed the build process to build dummy wrappers for wx.html2 if the webview libraries aren't found at build time.  So, this will be changed in the next release.

**Comment by RobinD42** [comment]
Plus MedaCtrl, GLCanvas and a few others.
