### ISSUE TITLE
Multiversion installs

### ISSUE THREAD

**Issue by ZeroPointEnergy** [wxWidgets/Phoenix#1222]
With wxpython 3 it was possible to install multiple versions in parallel (https://wiki.wxpython.org/MultiVersionInstalls). Is this still the case as this is a new implementation and is the same mechanism still working?

**Comment by RobinD42** [comment]
No, the multi-version installs were dropped on purpose. The way it was implemented was a major hack, and I regretted it shortly after it was released. 

With virtualenv installed in Python 2.7, or with the built-in venv support in Python 3, there really isn't any need any more for having multiple versions of wxPython in that same environment. Have something that needs a different version of wxPython (or any other dependency), just make a new venv and install what is needed in there and run that Python.

https://docs.wxpython.org/MigrationGuide.html#the-wxversion-module
