### ISSUE TITLE
Syntax Error w/ OS X on application exit

### ISSUE THREAD

**Issue by kg-2** [wxWidgets/Phoenix#1224]
**Operating system**: OS X 10.14
**wxPython version & source**:           pip
**Python version & source**:            stock python 3.6.8

**Description of the problem**: I get a syntax error when closing the UI on mac (works fine on windows). Here's the traceback

> File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wx/core.py", line 2166, in MainLoop
>     rv = wx.PyApp.MainLoop(self)
> wx._core.wxAssertionError: C++ assertion "m_modalNestedLevel == 0" failed at /Users/robind/projects/buildbots/macosx-vm6/dist-osx-py36/Phoenix/ext/wxWidgets/src/osx/cocoa/evtloop.mm(131) in ~wxGUIEventLoop(): 
> 
> 58:76: syntax error: Expected end of line, etc. but found identifier. (-2741)

It's a fairly complex app. If you need a minimum example to reproduce it let me know and I'll see if I can trim it down.

```python
# 
```

**Comment by RobinD42** [comment]
https://github.com/wxWidgets/wxWidgets/blob/WX_3_0_BRANCH/src/osx/cocoa/evtloop.mm#L126

Do you happen to have more than one `wx.App`? Or perhaps a nested call to `MainLoop` or `ShowModal`?

**Comment by kg-2** [comment]
I had a nested call to wx.Exit(), when I removed 1 of them the error went away.
