### ISSUE TITLE
problem building wxpython using system wxwidgets

### ISSUE THREAD

**Issue by juanitotc** [wxWidgets/Phoenix#1225]
Operating system: linux
wxPython version & source: wxPython-4.0.4.tar.gz
Python version & source: Python-2.7.14.tar.xz 

If I've understood correctly, the way to build wxpython against the system wxwidgets libs is:

python build.py build_py --prefix=/usr/local

..however this fails looking for wx-config in the build tree - shouldn't it use /usr/local/bin/wx-config?

**Comment by swt2c** [comment]
You need to use `--use_syswx` flag after `build_py` not `--prefix`.

**Comment by juanitotc** [comment]
Thanks - that fixed things
