### ISSUE TITLE
"Quote UnQuote"

### ISSUE THREAD

**Issue by Metallicow** [wxWidgets/Phoenix#1231]
"Quote UnQuote"

On the invevitable day our benevolent dictator of "GUI-dome" passes and new
and worthy "Pugs" pick up groups form into being, we heresay that quotes as
release identifiers had nothing to do with Eddie.
pls don't run my name thru the mud

I hereby declare the immediate release quote to be "Robin made me do it!"

This is valid unless "The benevolent dictator of 'GUI-dome'"  says otherwize.

Plus besides having not a whole lot to do while building releases, 
we can always talk...

Cheers,
  * "The wxPython Team"

"Add Quote Here"

**Comment by RobinD42** [comment]
Uh...... What?

**Comment by Metallicow** [comment]
On the subject of "the last ..." this or that, It is kinda hard to say really, but...
Collectively we all put a bit of thought into our last release, and most haven't come up with any better way of future releases codenames. There is always that last line... Amen. etc...
Quotes are probably best. Compared with debian's codenames ala toystory characters scheme, this would at least tidy up both ends as far as never running out of future names, dividing the line, and afterward, looking toward the future. Not that I'm trying to dictate or anything, but it is something I've thought about a lot in my code as far as codenaming. Translation is a subject all to itself also, and yes I considered that into what it might become.

**Comment by RobinD42** [comment]
The way the release titles work is I type whatever whatever crosses my mind when I type the release date into CHANGES.rst, with preferences towards the esoteric or quirky. For example, for this release my thought was, "What do you get when Apples crash?" For the previous release it was, "39 years ago today I heard and felt the sonic booms from over 200 miles away."

It's as simple as that. It doesn't need to be anything more.
