### ISSUE TITLE
Blinking/Blinding Cursor in Demo Code Window in wxdemo on Mac

### ISSUE THREAD

**Issue by MarjaE2** [wxWidgets/Phoenix#1238]
**Operating system**: MacOS 10.14.5
**wxPython version & source**:           wxPython v4.0.6. probably either pip or homebrew. I made a number of failed installation attempts and don't know which one succeeded.
**Python version & source**:             Python 3.7. probably either pip or homebrew. I made a number of failed installation attempts and don't know which one succeeded.

**Description of the problem**:

1. The "Demo Code" window of wxdemo hits users with a blinking cursor. Many users find blinking cursors annoying. I have a low-frequency strobe sensitivity, and find it a painful blinding nauseating migraine trigger. I can't see around blinking or flashing objects, it's all a blur.

2. Searching for "cursor" in help yields one apparently unrelated result. Mousing down causes a menu to open and a painful animated arrow to wander around.

3. Searching for "caret" in help yields no results.

4. Documentation assumes all carets are blinding cursors. Note that for me, they blot out the area around the cursor, they don't show anything. https://wxpython.org/Phoenix/docs/html/wx.Caret.html

5. I don't know if wxdemo or other wxPython tools default to system settings. Unfortunately MacOS includes no universal system setting for cursors.

```python
# Put code sample here
```

**Comment by mesalu** [comment]
I'll work on this in a bit. I plan to have the demo code panel fall back to system settings when available. When not available (e.g. OSX) I'll add a command line switch (`--no-caret-blink`) or something to that effect to toggle off caret blinking.
