### ISSUE TITLE
Javascript rendering in wx.html2.WebView for MSW in wxPython-4.1.0.a1

### ISSUE THREAD

**Issue by cutright** [wxWidgets/Phoenix#1256]
**Operating system**: Windows
**wxPython version & source**:          pip install wxPython-4.1.0a1.dev4100+8442697a-cp37-cp37m-win32.whl
**Python version & source**:            python 3.7 stock

**Description of the problem**:  I'm trying to get a web view with javascript (specifically [bokeh](https://github.com/bokeh/bokeh) generated html files) to be displayed in MSW.  I just installed wxPython 4.1.0a1 hoping to use something like:  
```
self.layout = wx.html2.WebView.New(parent)
if wx.Platform == '__WXMSW__':
    self.layout.MSWSetEmulationLevel(level=wx.html2.WEBVIEWIE_EMU_IE11) 
```   
This call appears to be successful (it returns true), but still javascript is not rendering.  I've tried SetPage() as well as LoadURL().  The html source is successfully pushing to my panel but the javascript is not rendering.

Is it acceptable to generate the layout as shown above, then pass `self.layout` into a sizer (specifically into a panel)? Do I need to call something else to allow the javascript to run?  I can see the source code propagates to the view (by right clicking) and the html file created renders as expected when opened by IE directly.  Mac and Linux work as expected with this html file too.

I can provide more details if this isn't an obvious user error.  Thanks!!

**Comment by RobinD42** [comment]
This is likely a wxWidgets-specific issue, not something that wxPython is doing, but can you provide a link to a page that is not working correctly?

> Is it acceptable to generate the layout as shown above, then pass self.layout into a sizer (specifically into a panel)?

It should be, assuming that `parent` is the panel that will have the sizer.

**Comment by cutright** [comment]
I've uploaded an example html file [here](https://www.dropbox.com/s/xw7vrdkcxxdcuoj/test.html?dl=0).

My wxPython layout generates the web view OK in MSW if there is no javascript.  I was able edit the registry with winreg, but this didn't resolve the issue either. Although, maybe I'm setting it with the wrong file; I've tried `__file__` and python.exe.

**Comment by RobinD42** [comment]
I forgot that this was a per-application registry setting. The way the C++ API is written we end up with the name of the code extension module in the registry, like `_core.cp37-win_amd64.pyd`. But what really needs to be there is the name of the `.exe` file. I renamed the registry entry to `python.exe` then your sample worked. This is the key where I modified the item:

`HKEY_CURRENT_USER\Software\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_BROWSER_EMULATION`

I guess we should replace that C++ method with a Python one that creates a registry item named with `sys.executable` instead...

**Comment by cutright** [comment]
Thanks! I've still not gotten it to work, but it could be that it won't work on Windows 7?

This is the code I'm using, and I run it in my main.py before launching the wx.App object.
```
def set_reg(name, reg_path, value):
    try:
        winreg.CreateKey(winreg.HKEY_CURRENT_USER, reg_path)
        registry_key = winreg.OpenKey(winreg.HKEY_CURRENT_USER, reg_path, 0, winreg.KEY_WRITE)
        winreg.SetValueEx(registry_key, name, 0, winreg.REG_DWORD, value)
        winreg.CloseKey(registry_key)
        return True
    except WindowsError:
        return False

def get_reg(name, reg_path):
    try:
        registry_key = winreg.OpenKey(winreg.HKEY_CURRENT_USER, reg_path, 0, winreg.KEY_READ)
        value, regtype = winreg.QueryValueEx(registry_key, name)
        winreg.CloseKey(registry_key)
        return value
    except WindowsError:
        return None

if wx.Platform == '__WXMSW__':
    reg_path = r"Software\\Microsoft\\Internet Explorer\\Main\\FeatureControl\\FEATURE_BROWSER_EMULATION"
    set_reg(sys.executable, reg_path, 11001)
    print(get_reg(sys.executable, reg_path))
```

**Comment by RobinD42** [comment]
Since you're using a raw string then you can change the double backslashes to singles. Also, try using `os.path.basname(sys.executable)` instead of the full path name.

**Comment by cutright** [comment]
Success!  Using `os.path.basename(sys.executable)` as you suggested did the trick.

I have to save my html to a file and use `LoadURL()` rather than passing the string into `SetPage()`, but I can work with that.  Thanks!!
![image001](https://user-images.githubusercontent.com/4778878/59202208-9d615100-8b61-11e9-8bf3-c3923511c062.png)

**Comment by zhangzhengxin** [comment]
> Success! Using `os.path.basename(sys.executable)` as you suggested did the trick.
> 
> I have to save my html to a file and use `LoadURL()` rather than passing the string into `SetPage()`, but I can work with that. Thanks!!
> ![image001](https://user-images.githubusercontent.com/4778878/59202208-9d615100-8b61-11e9-8bf3-c3923511c062.png)

Could you share more information on how to make it work? I tried to use  SetPage() or LoadURL() but could not make it work. Even save to an html file, still not rendering. Attached is a sample html I was trying to render.

[test.zip](https://github.com/wxWidgets/Phoenix/files/4705451/test.zip)

**Comment by cutright** [comment]
I had success with `LoadURL`. Something like the following should work if you've followed the reg edit discussion above.

```
from bokeh.io.export import get_layout_html

web_file = 'some/file/path.html'
html_str = get_layout_html(your_bokeh_layout_object)
with open(web_file', 'wb') as f:
    f.write(html_str.encode("utf-8"))
layout.LoadURL(web_file)
```

where `layout = wx.html2.WebView.New(parent)`

I am on MSW 7, bokeh 1.4, and wxpython 4.0.7post2.  Bokeh 2.0 broke my application, but I didn't care enough to find out why.  wxpython 4.1 due to a wxwidgets change in how it handled alignment flags.  My Mac had no issues with bokeh 2.0.

Below are links to all of the relevant code in my project.  

https://github.com/cutright/DVH-Analytics/blob/dbbfc30feb3e93af3e36060655eebddef4f28413/dvha/models/plot.py#L130-L145

https://github.com/cutright/DVH-Analytics/blob/dbbfc30feb3e93af3e36060655eebddef4f28413/dvha/main.py#L1186-L1200

https://github.com/cutright/DVH-Analytics/blob/dbbfc30feb3e93af3e36060655eebddef4f28413/dvha/tools/windows_reg_edit.py#L31-L35

https://github.com/cutright/DVH-Analytics/blob/dbbfc30feb3e93af3e36060655eebddef4f28413/dvha/tools/windows_reg_edit.py#L10-L18
