### ISSUE TITLE
wx.ArtProvider.GetBitmap() crashes

### ISSUE THREAD

**Issue by NicoPy** [wxWidgets/Phoenix#1260]
**Operating system**: Window10
**wxPython version & source**: 4.0.6
**Python version & source**:  3.6

**Description of the problem**:
This simple line crashes the running script : 
```wx.ArtProvider.GetBitmap(wx.ART_FILE_OPEN)```

Traceback (most recent call last):
  File "Z:\Eclipse\ZodbViewer\src\zodbViewer.py", line 335, in <module>
    frmZODB = ZODBFrame(None, -1, "")
  File "Z:\Eclipse\ZodbViewer\src\zodbViewer.py", line 110, in __init__
    self.__create_image_list()
  File "Z:\Eclipse\ZodbViewer\src\zodbViewer.py", line 129, in __create_image_list
    wx.ArtProvider.GetBitmap(wx.ART_FILE_OPEN)
wx._core.wxAssertionError: C++ assertion "strcmp(setlocale(LC_ALL, NULL), "C") == 0" failed at ..\..\src\common\intl.cpp(1579) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
Things are going to break, please only change locale by creating wxLocale objects to avoid this!

The same problem appears with wx.ART_FILE_SAVE_AS and wx.ART_FILE_SAVE
There is no problem with wx.ART_FOLDER
I have not tried all values.

**Comment by RobinD42** [comment]
What is the default locale on your system?
Do you use the `locale` module in your code?
What are the values of any `LANG` and/or `LC_*` variables in your environment?
What other modules do you import in your application? Could any of them be changing the application's locale settings?

**Comment by cbeytas** [comment]
The same thing happens to all my wx programs since wxPython 3.0. wxPython 2.8 didn't have this issue.
Right after creating a wx.App, set a Locale and you'll be fine.
```
app = wx.App(redirect=False)
locale = wx.Locale(wx.LANGUAGE_DEFAULT)
```

**Comment by NicoPy** [comment]
The problematic code has been written by someone else, so I did a complete review.
The locale module is effectively used. I removed it and everything works well now.
Thanks Robin.
