### ISSUE TITLE
time.clock has been deprecated since Python 3.3 and removed in 3.8

### ISSUE THREAD

**Issue by dhomeier** [wxWidgets/Phoenix#1264]
Thus `from time import clock` in [floatcanvas]( https://github.com/wxWidgets/Phoenix/blob/1e7506600cb11593cf4d86a6a0c63a0e10e53baa/wx/lib/floatcanvas/FloatCanvas.py#L51) fails as of [Python 3.8b1](https://github.com/python/cpython/pull/13270).
Canonical fix would be to [change](https://docs.python.org/3/library/time.html#time.clock) it to  `from time import perf_counter as clock` (or `process_time`, for best measurement of either total elapsed system time or the current Python process, respectively) or simply replace the `clock()` calls with either of the substitutes throughout.

**Comment by RobinD42** [comment]
This was fixed in 59e70e7c764fb84dc76d4d7efea011d70b04f733
