### ISSUE TITLE
TypeError: StyledTextCtrl.FindText(): 'findEnd' is not a valid keyword argument

### ISSUE THREAD

**Issue by Metallicow** [wxWidgets/Phoenix#1266]
wxPython 4.1.0a1.dev4155+1e750660 msw (phoenix) wxWidgets 3.1.3 Scintilla 3.7.2

@RobinD42 
This is a bit odd when I'm looking at this one as to whether it might be interpreted to be interpreted or not because it does show in the calltip, but returns a TypeError. Is this a theta, sequence, or maybe an over/undersight intending the user to specify a target/range beforehand?

**Comment by RobinD42** [comment]
Looks like it needs to be set as an output parameter.
