### ISSUE TITLE
wx.ListBox 'FindString' causes error

### ISSUE THREAD

**Issue by AllenDang** [wxWidgets/Phoenix#1273]
**Operating system**: MacOS v10.14.5
**wxPython version & source**:          4.0.6 pip
**Python version & source**:           3.7.3

**Description of the problem**:
wx.ListBox.FindString('test') failed with below error message:

`wx._core.wxAssertionError: C++ assertion "bCase && !bFromEnd" failed at /Users/robind/projects/buildbots/macosx-vm6/dist-osx-py37/Phoenix/ext/wxWidgets/src/common/arrstr.cpp(226) in Index(): search parameters ignored for auto sorted array`

**Comment by RobinD42** [comment]
It looks like the array's Index method expects case-sensitivity to be true for sorted arrays. Does it work if you do `FindString('test', True)` instead.

**Comment by AllenDang** [comment]
Thanks! It' works!
