### ISSUE TITLE
sized_controls.SizedDialog failing with no WS_EX_VALIDATE_RECURSIVELY

### ISSUE THREAD

**Issue by ckhan** [wxWidgets/Phoenix#1278]
**Operating system**: Windows 7  64-bit (also on MacOS Sierra)
**wxPython version & source**:   4.1.0a1.dev4130+927b6d94 from snapshot build
**Python version & source**:   Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] on win32

**Description of the problem**:

`sized_controls.SizedDialog` seems to be broken in latest builds:

```python
#!/usr/bin/python

import wx
print wx.__version__

import wx.lib.sized_controls as sc

app = wx.App()
frame = wx.Frame(None, title='simple.py')
dlg = sc.SizedDialog(parent=frame, title="test dialog")
wx.StaticText(dlg.GetContentsPane(), label="a dialog")
frame.Show()
dlg.ShowModal()
app.MainLoop()
```
Returns this error:
```
Traceback (most recent call last):
  File "scdialog-broken-41.py", line 19, in <module>
    dlg = sc.SizedDialog(parent=frame, title="test dialog")
  File "u:/usr/extras/wx-4.1.0a1-win\wx\lib\sized_controls.py", line 600, in __init__
    self.SetExtraStyle(wx.WS_EX_VALIDATE_RECURSIVELY)
AttributeError: 'module' object has no attribute 'WS_EX_VALIDATE_RECURSIVELY'
```

**Comment by RobinD42** [comment]
This issue has been mentioned on **Discuss wxPython**. There might be relevant details there:

https://discuss.wxpython.org/t/wxpython-4-1-0-released/34564/1
