### ISSUE TITLE
Mac Class FIFinderSyncExtensionHost is implemented in both

### ISSUE THREAD

**Issue by wangzhaohe** [wxWidgets/Phoenix#1281]
**Operating system**: Mac 10.14.5
**wxPython version & source**: 4.06
**Python version & source**:  python3.7.3

**Description of the problem**:

Runnig in demo.py. A waring message displayed after clicked wx.DirDialog.

(wx) pp:demo swot$ python demo.py
objc[31105]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fffb08023d8) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x11958ff50). One of the two will be used. Which one is undefined.

<img width="972" alt="屏幕快照 2019-06-29 上午8 56 17" src="https://user-images.githubusercontent.com/2628013/60377808-46f27e80-9a4c-11e9-8d31-62cc28722c05.png">

**Comment by elguaxo** [comment]
I'm getting the same error when using wx.FileDialog!
My setup: macOS 10.13.6, Python 3.8.5 and wxPython 4.1.0

Any hints?

**Comment by RobinD42** [comment]
The warning message is pretty much self-explanatory. AFAIK it is safe to ignore it.
