### ISSUE TITLE
ActiveX_PDFWindow.py module error

### ISSUE THREAD

**Issue by Ecco37** [wxWidgets/Phoenix#1290]
**Operating system:** Windows 10
**wxPython version & source:** 4.0.6 pip
**Python version & source:** 3.7.3

**Description of the problem:**
"ActiveX_PDFWindow.py" module failed with below error message:
---------------------------------------------------------
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
wx.version: 4.0.6 msw (phoenix) wxWidgets 3.0.5 - Windows 10
Traceback (most recent call last):
  File "C:\Users\Mimi\AppData\Local\Programs\Python\Python37\lib\site-packages\wx\lib\activex.py", line 154, in MSWTranslateMessage
    res = self.ipao.TranslateAccelerator(msg)
OSError: exception: access violation reading 0xFFFFFFFF8D7EEBD0

**Comment by SteveDoyle2** [comment]
I'm also having this issue though I'm using the  IEHtmlWindow class.  It seems like it's a more general activex problem.

From nearly 2 years ago, some more detailed description, along with a (bad) workaround by adding a try-except pass.
https://stackoverflow.com/questions/47670838/oserror-exception-access-violation-in-iewin-iehtmlwindow

**Comment by SteveDoyle2** [comment]
I've used this workaround for the last month and don't seem to have any issues with it.

**Modify:**

    C:\Python37\lib\site-packages\wxpython-4.0.6-py3.7-win-amd64.egg\wx\lib\activex.py

**Original method:**

    def MSWTranslateMessage(self, msg):
        # Pass native messages to the IOleInPlaceActiveObject
        # interface before wx processes them, so navigation keys and
        # accelerators can be dealt with the way that the AXControl
        # wants them to be done. MSWTranslateMessage is called before
        # wxWidgets handles and eats the navigation keys itself.
        res = self.ipao.TranslateAccelerator(msg)
        if res == hr.S_OK:
            return True
        else:
            return super(ActiveXCtrl, self).MSWTranslateMessage(msg)

**New method:**

    def MSWTranslateMessage(self, msg):
        # Pass native messages to the IOleInPlaceActiveObject
        # interface before wx processes them, so navigation keys and
        # accelerators can be dealt with the way that the AXControl
        # wants them to be done. MSWTranslateMessage is called before
        # wxWidgets handles and eats the navigation keys itself.
        try:
            res = self.ipao.TranslateAccelerator(msg)
        except OSError:
            return False

        if res == hr.S_OK:
            return True
        else:
            return super(ActiveXCtrl, self).MSWTranslateMessage(msg)

**Comment by retsyo** [comment]
I met this today
SteveDoyle2's solution fixes it

**Comment by RobinD42** [comment]
It looks like a similar change has already been applied, in 6c2251229f23ac3258ab3360319b12a28917b5f5
