### ISSUE TITLE
Scrolling through Grid gives GTKwarning

### ISSUE THREAD

**Issue by Akshath-Singhal** [wxWidgets/Phoenix#1297]
OS: Ubuntu 18.04
wxPython version: pypi 4.0.6, 3.0.2
Python version: distro 2.7.15, 3.6.8

Using grids inside frame leads to GTK warning when scrolling through grid after editing the contents of a cell. The problem begins after the Editor has been ended :
(wxglade_out.py:3029): Gtk-CRITICAL **: 23:59:48.646: gtk_widget_set_allocation: assertion '_gtk_widget_get_visible (widget) || _gtk_widget_is_toplevel (widget)' failed

Its floods the console making it difficult to use the program.

It works fine on Ubuntu 16.04(libgtk3.18.9) but not on Ubuntu 18.04(libgtk3.22).

A solution for getting rid of this would be helpful. Either by eliminating the warning or atleast by not displaying it in console.

```python
#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.8.0 on Wed Jul  3 19:57:39 2019
#

import wx
import wx.grid

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 300))
        self.panel_2 = wx.Panel(self, wx.ID_ANY)
        self.display_list = wx.grid.Grid(self, wx.ID_ANY, size=(1600,1100))
        self.__set_properties()
        self.__do_layout()
        for i in range(24):
            for j in range(24):
                self.display_list.SetCellValue(i,j,str(i))
        self.Refresh()
        self.Update()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("frame")
        self.display_list.CreateGrid(25, 25)       
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_2.Add(self.display_list, 0, wx.EXPAND, 0)
        sizer_2.Add(self.panel_2, 0, wx.EXPAND, 0)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

# end of class MyFrame

class MyApp(wx.App):
    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()

```

**Comment by RobinD42** [comment]
GTK warnings are an unfortunate fact of life, and not just for wxWidgets/wxPython. A little googling will turn up lots of complaints about it from other applications as well. And there doesn't seem to be an official way to suppress them, other than redirecting output to /dev/null or something similar.

Several years ago there was some small attempts to make changes in wxWidgets so the warnings are not triggered, but as soon as the code was run on another version of gtk, or even the same version on a different distro, then some of them came back, and others showed up. So the bottom line is that in at least almost all cases these warnings are not really problems that need to be worried about.
