### ISSUE TITLE
PropertyGrid.IntProperty fails to display int64 values

### ISSUE THREAD

**Issue by Fenolftalein** [wxWidgets/Phoenix#1299]
**Operating system**: macOS, Windows 

**Description of the problem**:
`wx.propgrid.IntProperty` in reality doesn't support 64-bit integer values, although documentation says that everything should be ok! 

Source: https://wxpython.org/Phoenix/docs/html/wx.propgrid.PGProperty.html#phoenix-title-intproperty

This is important issue for my project as I use `long long` values (parsed from proto-data), so I hope that it could be solved without writing custom Editor/Property.

**Steps to reproduce**:
1) run `PropertyGrid.py` from *wxPython-demo-4.0.4/demo*
2) enter `long long int` value in IntProperty
3) Click `SetPropertyValues`-button

Traceback:
```
python3 PropertyGrid.py 
Python 3.7.3 (default, Mar 27 2019, 09:23:39) 
[Clang 10.0.0 (clang-1000.11.45.5)]
wx.version: 4.0.4 osx-cocoa (phoenix) wxWidgets 3.0.5
00:03:42: Int selected
00:03:47: Int changed to "112344519123"
Traceback (most recent call last):
  File "./PropertyGrid.py", line 851, in OnSetPropertyValues
    d = self.pg.GetPropertyValues(inc_attributes=True)
  File "/usr/local/lib/python3.7/site-packages/wx/propgrid.py", line 1160, in _PropertyGridInterface_GetPropertyValues
    dict_[name] = getter(p)
TypeError: Unexpected type ("longlong") in wxVariant.
```

**Comment by swt2c** [comment]
What's weird is that I can't reproduce this, even on a Mac.  Can you clarify exactly what value you mean by `long long int` ?  The value `112344519123` at least works for me.
