### ISSUE TITLE
When applied wx.BORDER_NONE to a wx.Button, it becames invisible

### ISSUE THREAD

**Issue by WJMazepas** [wxWidgets/Phoenix#1303]
**Operating system**: Raspbian GNU/Linux 9 (stretch)
**wxPython version & source**: 4.0.4 gtk2 (phoenix) wxWidgets 3.0.5 via self-built       
**Python version & source**: 3.7.0 via self-built        

**Description of the problem**:

Im running on my Raspberry, in my linux machine this bug does not happen. 
Any wx.Button that i apply wx.BORDER_NONE to the style, becomes invisible. Its only visible while im hovering with my mouse on the button. 

```python
# Put code sample here
```

**Comment by RobinD42** [comment]
The various wx ports are free to interpret the wx.BORDER_NONE style on native widgets however it makes sense for the platform. For GTK builds it also depends on the current theme. Try different themes and see what results you get.
