### ISSUE TITLE
BitmapComboBox misses Popup method

### ISSUE THREAD

**Issue by mchlnix** [wxWidgets/Phoenix#1307]
**Operating system**: Linux
**wxPython version & source**:          4.0.6 - pypi
**Python version & source**:            3.6

**Description of the problem**:

The `wx.adv.BitmapComboBox` class does not have a `Popup` method, like `ComboBox` does. 

Since it does not seem to be a sub class of `ComboBox` in Linux, calling its `Popup` method does also not work. Is there a workaround and is this intentional?

**Comment by RobinD42** [comment]
This issue has been mentioned on **Discuss wxPython**. There might be relevant details there:

https://discuss.wxpython.org/t/wxpython-4-1-0-released/34564/1
