### ISSUE TITLE
Does wxPython extend wxWidgets? Any list of (additional/missing) widgets?

### ISSUE THREAD

**Issue by Xeverous** [wxWidgets/Phoenix#1317]
This is not a real issue, just a couple of questions for which I have not found an answer in the FAQ of wxPython or wxWidgets themselves.

- Is there any list of all widgets with their screenshots? I often don't know what to choose or if such widget exists at all. I have only found https://docs.wxpython.org/gallery.html which happens to contain random screenshots which presents most of the widgets.
- The above leads me to another question - does wxPython Phoenix only wrap the wxWidgets library or does it extend (eg implement more widgets) in any way? Are there any additional widgets? Any missing ones?
- Is there something only possible from wxPython? Something only possible from the C++ side?

I'm asking this because I have a program which so far has no GUI and while wxWidgets looks good, I can not easily verify if it has all the widgets/features I want. I am skilled in C++ but wxWidgets itself has relatively bad API (far away from modern C++ expectations and conventions; basically similar problem to Python 2 vs 3) and would rather use some wrapper like Phoenix (Python 3) or [Boost.UI](https://kosenko.github.io/boost.ui/) (C++11).

**Comment by Metallicow** [comment]
After installing wxPython you can download the latest version of the demo from https://wxpython.org/Phoenix/snapshot-builds/ and unzip it to a directory and run the demo which shows a lot of the widgets but not everything you can do. Once you get an idea of what you want, if there isnt an example to show you how to implement it you can ask on the mailing list. Also there are other custom widgets in various repositories around the net. Or you can code your own widget to what you want. Not everything is on github. Also there is the wxPython Wiki. Most questions related to the Q&A section are on the mailing list.

**Comment by Xeverous** [comment]
Ok thanks, but the most important question for me is still unanswered: does wxPython Phoenix implement any additional widgets or does it only wrap existing ones in wxWidgets?

**Comment by infinity77** [comment]
Hi,

On Mon, 29 Jul 2019 at 23.10, Xeverous <notifications@github.com> wrote:

> Ok thanks, but the most important question for me is still unanswered:
> does wxPython Phoenix implement any additional widgets or does it only wrap
> existing ones in wxWidgets?
>
>
The answer to your question lies into Metallicow’s answer: try the wxPython
demo and see for yourself.

The short, direct answer is “yes”, Phoenix has a lot more widgets than the
ones wrapped in wxWidgets. Many examples are in the wx.lib package and its
sub-packages.

If you had bothered to google a little bit, you would have found that the
Phoenix documentation has screenshots on many controls, most wrapped on
wxWidgets but many implemented in pure Python to extend the GUI
capabilities of wxPython:

https://wxpython.org/Phoenix/docs/html/wx.lib.html

But really, it takes a moment to install the wxPython demo and get so much
more out of it than looking at pictures.

Andrea.

**Comment by Xeverous** [comment]
Ok, I will definitely try the demo when I'm back home.

> most wrapped on wxWidgets but many implemented in pure Python

This is good news because it means that many widgets can be easily implemented. I will check what and how is done.

**Comment by Metallicow** [comment]
umm yea. what Andrea said.
