### ISSUE TITLE
Catalina EVT_PAINT issue.

### ISSUE THREAD

**Issue by brian-a-clark** [wxWidgets/Phoenix#1324]
**Operating system**: OSX 10.15 Catalina (Beta 5)
**wxPython version & source**:  pip installed
**Python version & source**:         2.7.16
**Description of the problem**:    On Catalina, simple GUI elements are rendering incorrectly (see screenshots) and EVT_PAINT events are not propagated.

```python
import wx

class MyButton(wx.Button):

  def __init__(self, *args, **kwargs):
    wx.Button.__init__(self, *args, **kwargs)
    self.Bind(wx.EVT_PAINT, self.OnPaint)
    print "Bound"

  def OnPaint(self, _):
    print "Painting"

def Main():
  app = wx.App()
  frame = wx.Frame(None)
  frame.MinSize = (600, 400)
  button = MyButton(frame, wx.ID_ANY)
  button.SetBackgroundColour(wx.BLACK)
  sizer = wx.BoxSizer(wx.HORIZONTAL)
  sizer.Add(button)
  frame.Show()
  app.MainLoop()

if __name__ == "__main__":
  Main()
```

On Mojave:
$ python test.py
Bound
Painting
![Mojave screenshot](https://user-images.githubusercontent.com/5254969/62902611-247fa080-bd2e-11e9-914e-17c1dac5e2a2.png)

On Catalina:
$ python test.py
Bound

(never gets EVT_PAINT)
<img width="512" alt="Catalina screenshot" src="https://user-images.githubusercontent.com/5254969/62902550-ef734e00-bd2d-11e9-89a0-e23ea69f3ad0.png">

Any thoughts?

**Comment by brian-a-clark** [comment]
Also, running with python 3.7.4 has the same issue, fwiw.

**Comment by brian-a-clark** [comment]
**wxPython version & source:** pip installed 4.0.6

**Comment by RobinD42** [comment]
The behavior of catching paint and other low-level events for native widgets is "undefined", meaning that it may or may not work.

**Comment by brian-a-clark** [comment]
Hi Robin, thanks for the reply.  We think we've found the issue and I'll be submitting a PR to wxWidgets today or later this week.

**Comment by brian-a-clark** [comment]
https://github.com/wxWidgets/wxWidgets/pull/1487

**Comment by brian-a-clark** [comment]
FYI, the PR was merged this morning.
