### ISSUE TITLE
TreeCtrl very slow with millions of nodes (only on multi-select type)

### ISSUE THREAD

**Issue by htn9937** [wxWidgets/Phoenix#1329]
Operating system: Windows 10 64-bit
wx.version: 4.0.4 msw (phoenix)
Python version & source: 3.7

**Description of the problem**:
I am creating a tree with millions of nodes, but when I switched to using multiple-select on a tree control (wx.TR_MULTIPLE), actions on tree become slower, I only click to select a node and it takes me a few seconds. This does not happen when I use the single-select style (wx.TR_SINGLE).

I used `PrependItem` because it is faster than `AppendItem` when I add the whole nodes.

```python
import wx


class MyTree(wx.TreeCtrl):
    def __init__(self, parent, id, pos, size, style):
        wx.TreeCtrl.__init__(self, parent, id, pos, size, style)
        self.Bind(wx.EVT_TREE_SEL_CHANGED, self.item_changed)

    def item_changed(self, evt):
        print(self.GetItemData(evt.GetItem()))


class TreePanel(wx.Panel):
    def __init__(self, parent):
        wx.Panel.__init__(self, parent)
        self.tree = MyTree(self, wx.ID_ANY, wx.DefaultPosition, wx.DefaultSize, wx.TR_HAS_BUTTONS | wx.TR_MULTIPLE)
        self.root = self.tree.AddRoot('ROOT')
        node1 = self.tree.AppendItem(self.root, 'Node 1', data='node 1')
        for i in range(1000000):
            self.tree.PrependItem(node1, 'Sub node 1: ' + str(i), data='Sub node 1: ' + str(i))
        self.tree.Expand(self.root)
        sizer = wx.BoxSizer(wx.VERTICAL)
        sizer.Add(self.tree, 1, wx.EXPAND)
        self.SetSizer(sizer)


class MainFrame(wx.Frame):
    def __init__(self):
        wx.Frame.__init__(self, parent=None, title='TreeCtrl Demo')
        panel = TreePanel(self)
        self.Show()


if __name__ == '__main__':
    app = wx.App(redirect=False)
    frame = MainFrame()
    app.MainLoop()
```

**Comment by infinity77** [comment]
The reason is here:

https://github.com/wxWidgets/wxWidgets/blob/master/src/msw/treectrl.cpp#L3002

That `DoUnselectAll` calls `GetSelections` which in turns traverse the whole tree (if I understand correctly) to check for selected items. You shouldn't use a wx.TreeCtrl for millions of items anyway, it's not a good design choice. Either switch to DataViewTreeCtrl or create/delete items on the fly when you expand/collapse parent nodes:

https://wiki.wxpython.org/TreeControls#Lazy_Evaluation_Tree_Controls

If you really, seriously have 1 million children for a single parent, then you might want to re-think your presentation logic.

**Comment by htn9937** [comment]
I also tried with `wx.dataview.DataViewTreeCtrl` but I found out that It is too slow. I only add 1000 nodes and it takes almost 10 seconds. Here is my demo code:

```python
import wx
import wx.dataview as dv


class MyFrame(wx.Frame):
    def __init__(self, parent, title):
        wx.Frame.__init__(self, parent, wx.ID_ANY, title, size=(400, 800))
        self.tree = dv.DataViewTreeCtrl(self)
        root = self.tree.AppendContainer(dv.NullDataViewItem, 'ROOT', 0)
        for i in range(1000):
            self.tree.AppendItem(root, 'Some text', data='Dt')


app = wx.App()
frame = MyFrame(None, 'wx.lib.buttons Test')
frame.Show()
app.MainLoop()
```
Do I make some things wrong? 

In my app, there is really has a node with more than 1 million children. I am using "Lazy Evaluation Tree Controls" but the issue is still there, I have to expand the whole children node.
I tested on Linux and the action select node still fast.  It almost takes effect immediately. (No matter the type is `wx.TR_MULTIPLE` or  `wx.TR_SINGLE`.

**Comment by infinity77** [comment]
There might be a way to create a "virtual" DataViewTreeCtrl, but I am no expert in this area. That said, having a parent item with 1 million children in a tree will not help any user in navigating your interface. How is the user supposed to find what she needs?
I believe on Linux wxWidgets still uses the generic implementation of wxTreeCtrl, which is not the same as the Windows one.

**Comment by htn9937** [comment]
I have a way to help the user to do that (like list some nodes have an issue and jump to that node on the tree when user click on my list). The problem with my app is that my user wants to show millions of nodes on the tree. When they choose a node to edit, and the action select node must fast.
