### ISSUE TITLE
pdfviewer using PyMuPDF broken with recent versions of PyMuPDF. PATCH included

### ISSUE THREAD

**Issue by jmoraleda** [wxWidgets/Phoenix#1350]
The following snippet of code (extracted from https://wxpython.org/Phoenix/docs/html/wx.lib.pdfviewer.html?highlight=pdf#usage by removing the button panel) demonstrates the problem:

``` python
import wx
import wx.lib.sized_controls as sc

from wx.lib.pdfviewer import pdfViewer

class PDFViewer(sc.SizedFrame):
    def __init__(self, parent, **kwds):
        super(PDFViewer, self).__init__(parent, **kwds)

        paneCont = self.GetContentsPane()

        self.viewer = pdfViewer(paneCont, wx.ID_ANY, wx.DefaultPosition,
                                wx.DefaultSize,
                                wx.HSCROLL|wx.VSCROLL|wx.SUNKEN_BORDER)

        self.viewer.SetSizerProps(expand=True, proportion=1)


if __name__ == '__main__':
    import wx.lib.mixins.inspection as WIT
    app = WIT.InspectableApp(redirect=False)

    pdfV = PDFViewer(None, size=(800, 600))
    pdfV.viewer.LoadFile(r'path_to_any_pdf_file.pdf')
    pdfV.Show()

    app.MainLoop()
```
The code works correctly with older versions of PyMuPDF(up to 1.14) but fails with more recent versions (1.15 and above). This is the complete output written to the console:
```
python .\pdftest.py
pdfviewer using PyMuPDF (GPL)
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\wx\core.py", line 3259, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "C:\Program Files\Python37\lib\site-packages\wx\lib\pdfviewer\viewer.py", line 433, in Render
    self.pdfdoc.RenderPage(gc, pageno, scale=self.scale)
  File "C:\Program Files\Python37\lib\site-packages\wx\lib\pdfviewer\viewer.py", line 518, in RenderPage
    bmp = wx.Bitmap.FromBufferRGBA(pix.width, pix.height, pix.samples)
ValueError: Invalid data buffer size.
```
*FIX*

The issue is that PyMuPDF  used to produce RGBA values, but now produces RGB values, thus the code as it stands works on older installations, but fails on newer installations. In particular, `Bitmap.FromBuffer` should be used instead of `Bitmap.FromBufferRGBA`. 

This is a patch that will correctly handle both the older and newer versions of PyMuPDF.

```diff
diff --git a/wx/lib/pdfviewer/viewer.py b/wx/lib/pdfviewer/viewer.py
index 7b75724b..284069e1 100644
--- a/wx/lib/pdfviewer/viewer.py
+++ b/wx/lib/pdfviewer/viewer.py
@@ -516,7 +516,11 @@ class mupdfProcessor(object):
         matrix = fitz.Matrix(scale, scale)
         try:
             pix = page.getPixmap(matrix=matrix)   # MUST be keyword arg(s)
-            bmp = wx.Bitmap.FromBufferRGBA(pix.width, pix.height, pix.samples)
+            if [int(v) for v in fitz.version[1].split('.')] >= [1,15,0]:
+                # See https://github.com/wxWidgets/Phoenix/issues/1350
+                bmp = wx.Bitmap.FromBuffer(pix.width, pix.height, pix.samples)
+            else:
+                bmp = wx.Bitmap.FromBufferRGBA(pix.width, pix.height, pix.samples)
             gc.DrawBitmap(bmp, 0, 0, pix.width, pix.height)
             self.zoom_error = False
         except (RuntimeError, MemoryError):
```

**Comment by Derriick** [comment]
I confirm that this patch works perfectly for me.
@jmoraleda maybe if you made a pull request this change would be accepted? (I can do it, but it would be a bit of a theft of idea)

**Comment by jmoraleda** [comment]
This is a patch that will correctly handle both the older and newer versions of PyMuPDF.

```diff
diff --git a/wx/lib/pdfviewer/viewer.py b/wx/lib/pdfviewer/viewer.py
index 7b75724b..284069e1 100644
--- a/wx/lib/pdfviewer/viewer.py
+++ b/wx/lib/pdfviewer/viewer.py
@@ -516,7 +516,11 @@ class mupdfProcessor(object):
         matrix = fitz.Matrix(scale, scale)
         try:
             pix = page.getPixmap(matrix=matrix)   # MUST be keyword arg(s)
-            bmp = wx.Bitmap.FromBufferRGBA(pix.width, pix.height, pix.samples)
+            if [int(v) for v in fitz.version[1].split('.')] >= [1,15,0]:
+                # See https://github.com/wxWidgets/Phoenix/issues/1350
+                bmp = wx.Bitmap.FromBuffer(pix.width, pix.height, pix.samples)
+            else:
+                bmp = wx.Bitmap.FromBufferRGBA(pix.width, pix.height, pix.samples)
             gc.DrawBitmap(bmp, 0, 0, pix.width, pix.height)
             self.zoom_error = False
         except (RuntimeError, MemoryError):
```

**Comment by Metallicow** [comment]
The issue number doesn't need to be in the patch, just in the reference in the PullREQ desc so people can track when the change occured.

**Comment by jmoraleda** [comment]
@Metallicow Thank you. Feel free to remove the comment in the patch if you decide to apply it. I feel it is too small a contribution for me to make a pull request.

**Comment by Metallicow** [comment]
Well, basically someone needs to make a PullREQz is what I'm trying to say. It makes it easier for Robin to just click merge because the builders will take a bit of time and it might for example cause an error.
Plus little things like this involve external libraries, so if someone else makes your pullreqz, then it may be extra time/hassle to do so, since they will need to test it also. Just having someone else say it works for them also, isn't really a definite answer when it involves 3rd party libs. Thats probably why it hasn't been done yet... so just a small tip for you in the future if you open a issue again and post a small patch.

...Also if I ever get to removing some of the old cruft in files that involved little changes from various authors and they just posted that stuff in the library files(old classic stuff), those names should be added to the copyright lines or to a general contributers.txt. So basically on github, if you dont have at least one contribution, your handle wont show up in the contributers section of the insights tab. I know its only a 2liner, but it still counts for those that want a handle credit. just saying.

**Comment by jmoraleda** [comment]
I have found that the change in default behavior of `getPixmap` in MuPDF with respect to whether `getPixmap` returns an image with or without an alpha channel did not happen between 1.15 and 1.16 but somewhere in between 1.16 patches, so my previous patch to the pdfviewer will not work for some versions. 

I think an altogether cleaner solution to this problem that is also future proof against future changes in MuPDF default behavior is to not rely on the default and instead explicitly indicate in the call to `getPixmap` whether an alpha channel should be returned.

I am submitting a patch to this effect.
