### ISSUE TITLE
aui toolbar not docking when it was just loaded as a floating pane. FIX included.

### ISSUE THREAD

**Issue by jmoraleda** [wxWidgets/Phoenix#1364]
If a perspective is just loaded that contains an AuiToolbar in a floating pane, that toolbar cannot be docked back:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/wx/lib/agw/aui/framemanager.py", line 3217, in OnMoveEvent
    self.OnMoveStart(event)
  File "/usr/local/lib/python3.7/dist-packages/wx/lib/agw/aui/framemanager.py", line 3273, in OnMoveStart
    self._owner_mgr.OnMotion_DragToolbarPane(point)
  File "/usr/local/lib/python3.7/dist-packages/wx/lib/agw/aui/framemanager.py", line 9877, in OnMotion_DragToolbarPane
    ret, pane = self.DoDrop(self._docks, self._panes, pane, clientPt, self._action_offset)
AttributeError: 'AuiManager_DCP' object has no attribute '_action_offset'
```

This error is due to a bug in line `9877` of `wx/lib/agw/aui/framemanager.py` where the wrong variable `self._action_offset` is used. The correct variable to use in that line is `self.self._toolbar_action_offset`. In context, this is the correct call:
```
        if self.CanDockPanel(pane):
            # do the drop calculation
            ret, pane = self.DoDrop(self._docks, self._panes, pane, clientPt, self._toolbar_action_offset)
```

Once the correct variable is used, everything works as expected.

**Comment by Metallicow** [comment]
It appears you are using a linux flavor, but upon loading a frame perspective on Win7 the dock looks like this.
![loadedframeperspective](https://user-images.githubusercontent.com/4668356/82156171-51be2980-983f-11ea-88fe-fb81ef7688a2.png)
The miniframe header can be moved, but the gripper dots cant.
When tearing the toolbar out of the manager and when the left up mouse event occur, the gripper disappears. Are you trying to say you can't use a miniframe header on your OS?

**Comment by jmoraleda** [comment]
Hello @Metallicow Thank you. 

The issue happens when using the native AUI in `wx.aui` not the python AUI. 

What I do to trigger the bug is first to undock a toolbar and save the perspective and exit my app. 
When I restart my app, it loads the perspective again. Evidently the toolbar is undocked since it was saved undocked. When I then try to dock it then I get:

```
2020-05-17 22:55:11 ERROR [wx.lib.agw.aui.framemanager]: An unexpected error occurred in wx.lib.agw.aui.framemanager
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/wx/lib/agw/aui/framemanager.py", line 3224, in OnMoveEvent
    self.OnMoveStart(event)
  File "/usr/local/lib/python3.8/dist-packages/wx/lib/agw/aui/framemanager.py", line 3280, in OnMoveStart
    self._owner_mgr.OnMotion_DragToolbarPane(point)
  File "/usr/local/lib/python3.8/dist-packages/wx/lib/agw/aui/framemanager.py", line 9884, in OnMotion_DragToolbarPane
    ret, pane = self.DoDrop(self._docks, self._panes, pane, clientPt, self._action_offset)
AttributeError: 'AuiManager_DCP' object has no attribute '_action_offset'
```
In my experiments if I undock the toolbar, I can dock it again if there is no save and reload perspective involved.

I will try put together a little sample code with saving and loading and perspectives that shows the bug in action.

**Comment by infinity77** [comment]
“The issue happens when using the native AUI in wx.aui not the python AUI.”

I guess you meant the reverse, right? The traceback appears to be triggered in wx.lib.agw.aui, so it’s the python version of it. That said, I believe you found a bug and it seems to me that the fix is all right.

**Comment by jmoraleda** [comment]
Hello @infinity77 Thank you. Of course you are right. My bad. It happens in the pure python aui as the stack trace shows.
