### ISSUE TITLE
wx.Button / wx.BitmapButton giving error on using SetBitmapFocus or SetBitmapPressed

### ISSUE THREAD

**Issue by hpkkumar007** [wxWidgets/Phoenix#1367]
**Operating system**: Win 10
**wxPython version & source**:  4.0.6 msw (phoenix) wxWidgets 3.0.5 [from pip]
**Python version & source**:  Python 3.7.4 [from installer]

**Description of the problem**: Using wxFormBuilder v3.9.0, and with that wxButton or wx.BitmapButton both are not working for methods like SetBitmapFocus or SetBitmapPressed

Code generated from wxFormBuilder:
```python
self.start_button = wx.Button( self.m_panel, wx.ID_ANY, wx.EmptyString, wx.DefaultPosition, wx.Size( 100,40 ), 0|wx.BORDER_RAISED )
self.start_button.SetBitmap( wx.ArtProvider.GetBitmap( wx.ART_GO_FORWARD, wx.ART_BUTTON ) )
self.start_button.SetBitmapPressed( wx.ArtProvider.GetBitmap( wx.ART_GO_FORWARD, wx.ART_CMN_DIALOG ) )
```

Error thrown is: 
```python
Traceback (most recent call last):
  File "Tool.py", line 591, in <module>
    frame = MainFrame(None)
  File "Tool.py", line 365, in __init__
    super(MainFrame, self).__init__(parent)
  File "C:\test\gui.py", line 200, in __init__
    self.start_button.SetBitmapPressed( wx.ArtProvider.GetBitmap( wx.ART_GO_FORWARD, wx.ART_CMN_DIALOG ) )
wx._core.wxAssertionError: C++ assertion "(which == State_Normal) || bitmap.IsNull()" failed at ..\..\src\msw\anybutton.cpp(707) in wxAnyButton::DoSetBitmap(): Must set normal bitmap with the new size first
```

and also other issues like:
```python
AttributeError: 'BitmapButton' object has no attribute 'SetBitmapHover'
AttributeError: 'BitmapButton' object has no attribute 'SetBitmapSelected'
```

I tried searching on net and github, if I am doing any mistake in coding, but no right solution available.
Please suggest if this is really a bug, or if I may be doing something wrong.

Please ask, if any more details required.

Thanks in advance,
KK

**Comment by RobinD42** [comment]
> in wxAnyButton::DoSetBitmap(): Must set normal bitmap with the new size first

This indicates that you are using bitmaps of different sizes. They need to be the same.

> AttributeError: 'BitmapButton' object has no attribute 'SetBitmapHover'
> AttributeError: 'BitmapButton' object has no attribute 'SetBitmapSelected'

For a long time now the C++ implementation of these methods have been simple wrappers around the `*Pressed` and `*Current` APIs. Since the wrapper code for wxPython is now driven mostly by what is in the C++ documentation, and since those wrappers are no longer in the documentation, then we don't get wrappers for them. 

I can add them back, but in this case I think that it is wxFormBuilder that needs to change.
