### ISSUE TITLE
STC AutoCompShow() only fires when lengthEntered matches exactly

### ISSUE THREAD

**Issue by hschneider66** [wxWidgets/Phoenix#1368]
**Operating system**: macOS 10.14.6
**wxPython version & source**:         4.0.6
**Python version & source**:            2.7.15 Homebrew

**Description of the problem**:

When I use e.g. self.AutoCompShow(3, kw) the popup menu appears only if I enter **exactly** 3 characters. If I enter less or more, it is not triggered. The 1st argument should be the **minimum** number of characters, not a fixed value to trigger the AutoComp popup.

**Comment by RobinD42** [comment]
The STC is a wrapper around the [Scintilla](https://scintilla.org) library. Any changes in functionality will have to be implemented there before it can make it to the wx code.

**Comment by hschneider66** [comment]
Thanks for the reply.

I found a workaround, which triggers AutoCompShow as expected. The trick is to dynamically get the length of the last word entered:

```
            line = CurrentWidget.GetLine(CurrentWidget.GetCurrentLine())
            lastWord = line.split(' ')[-1]
            self.AutoCompShow(len(lastWord)-1, kw)

```
