### ISSUE TITLE
EVT_SEARCH doesn't exist, but appears in documentation

### ISSUE THREAD

**Issue by 730730** [wxWidgets/Phoenix#1370]
**Operating system**: W10
**wxPython version & source**: 4.0.6 msw (phoenix) wxWidgets 3.0.5 (pypi)        
**Python version & source**: v3.6.1:69c0db5 (stock)      

**Description of the problem**: I was [looking at the documentation](https://wxpython.org/Phoenix/docs/html/wx.SearchCtrl.html#events-events-emitted-by-this-class) for SearchCtrl and tried to Bind() the EVT_SEARCH event. However, at runtime this throws an error saying it doesn't exist. I went inside the module to check out event names and I couldn't find it, but I could find EVT_SEARCHCTRL_SEARCH_BTN, which, according to the comments, is deprecated, but it does work as expected (succesfully used Bind() and clicking the SearchCtrl's button triggers the method it was bound to).
Not sure whether this is an oversight or just that one documentation page being outdated.

**Comment by RobinD42** [comment]
The documentation link you used is for the development version (4.1) of the docs. The documentation for the released version is at https://docs.wxpython.org/

In 4.1 the `EVT_SEARCHCTRL_SEARCH_BTN` event type has been renamed to `EVT_SEARCH`, although both names will stick around for a while to help maintain compatibility.
