### ISSUE TITLE
Tooltip partly not working in combination with StaticBoxSizer

### ISSUE THREAD

**Issue by roland171281** [wxWidgets/Phoenix#1371]
**Operating system**: UBUNTU 18.04
**wxPython version & source**: 4.0.6 installed via pip 
**Python version & source**: stock 2.7.15

**Description of the problem**:
When I'am trying to add a tooltip at staticText inside a StaticBoxSizer they will not be shown under LINUX (UBUNTU 18.04). Under WIN64 it's working without any problems. Also all other Sizertypes are working.

```python
# Put code sample here
import wx

class Test(wx.Frame):
    def __init__(self, parent):
        wx.Frame.__init__(self, parent, id=wx.ID_ANY, title="test", size=wx.Size(1000, 550))
        sizer1 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "staticbox"), wx.VERTICAL)
        label1 = wx.StaticText(self, wx.ID_ANY, "just a tooltip test")
        label1.SetToolTip("testtooltip")
        sizer1.Add(label1, 1, wx.ALL | wx.EXPAND, 0)
        self.SetSizer(sizer1)

app = wx.App()
gui = Test(None)
gui.Show(True)
app.MainLoop()
```

**Comment by RobinD42** [comment]
Try making the static text be a child of the static box instead of the panel.

**Comment by roland171281** [comment]
Hi Robin,
thank you for your fast reply and the solution -> works perfect!
Best regards and have a nice day,
Roland

Am Di., 24. Sept. 2019 um 01:06 Uhr schrieb Robin Dunn <
notifications@github.com>:
