### ISSUE TITLE
CheckListBox GetCheckedItems\GetCheckedStrings always return empty list.

### ISSUE THREAD

**Issue by AllenDang** [wxWidgets/Phoenix#1385]
**Operating system**: MacOS 10.14.6
**wxPython version & source**:          Phenix/latest/self-build
**Python version & source**:            3.7.4

**Description of the problem**:
CheckListBox GetCheckedItems\GetCheckedStrings always return empty list.

```python
clClubChoices = clubs.name.to_list()
self.clClub = wx.CheckListBox(
      self, wx.ID_ANY, wx.DefaultPosition, wx.DefaultSize, clClubChoices, 0

)
checkedIndexes = self.clClub.GetCheckedStrings()
print(checkedIndexes)
```

**Comment by swt2c** [comment]
Please provide a runnable example that shows the problem.

**Comment by AllenDang** [comment]
My bad, I found the problem.
I tried to retrieve the check items before Dialog.ShowModal().
