### ISSUE TITLE
  Failed building wheel for wxPython

### ISSUE THREAD

**Issue by Hmiller97** [wxWidgets/Phoenix#1388]
I am using Virtual box with a Ubuntu OS. 
When I type 'python --version' I get: Python 2.7.15+.

I run the command 'pip install -r pip_required_gds.txt' that references installs, one of them being wxpython. Everything else works correctly except wxpython. Below is what it runs:

Collecting wxPython (from -r pip_required_gds.txt (line 2))
Collecting pytz (from -r pip_required_gds.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/e7/f9/f0b53f88060247251bf481fa6ea62cd0d25bf1b11a87888e53ce5b7c8ad2/pytz-2019.3-py2.py3-none-any.whl
Collecting wxPython (from -r pip_required_gds.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/9a/a1/9c081e04798eb134b63def3db121a6e4436e1d84e76692503deef8e75423/wxPython-4.0.6.tar.gz
Collecting numpy (from wxPython->-r pip_required_gds.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/d7/b1/3367ea1f372957f97a6752ec725b87886e12af1415216feec9067e31df70/numpy-1.16.5-cp27-cp27mu-manylinux1_x86_64.whl
Collecting pillow (from wxPython->-r pip_required_gds.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/11/21/b8f96afde78ff1d36fc8f71b08fdf2763d407ee9bb3dd026a17023760ca7/Pillow-6.2.0-cp27-cp27mu-manylinux1_x86_64.whl
Collecting six (from wxPython->-r pip_required_gds.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Building wheels for collected packages: wxPython
  Running setup.py bdist_wheel for wxPython ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-GzFPrP/wxPython/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpQ63d_2pip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  WARNING: Building this way assumes that all generated files have been
  generated already.  If that is not the case then use build.py directly
  to generate the source and perform the build stage.  You can use
  --skip-build with the bdist_* or install commands to avoid this
  message and the wxWidgets and Phoenix build steps in the future.
  
  "/usr/bin/python" -u build.py build
  Traceback (most recent call last):
    File "build.py", line 30, in <module>
      import pathlib2
  ImportError: No module named pathlib2
  Command '"/usr/bin/python" -u build.py build' failed with exit code 1.
  
  ----------------------------------------
  Failed building wheel for wxPython
  Running setup.py clean for wxPython
Failed to build wxPython
Installing collected packages: pytz, numpy, pillow, six, wxPython
  Running setup.py install for wxPython ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-GzFPrP/wxPython/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-x0EMi7-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    WARNING: Building this way assumes that all generated files have been
    generated already.  If that is not the case then use build.py directly
    to generate the source and perform the build stage.  You can use
    --skip-build with the bdist_* or install commands to avoid this
    message and the wxWidgets and Phoenix build steps in the future.
    
    "/usr/bin/python" -u build.py build
    Traceback (most recent call last):
      File "build.py", line 30, in <module>
        import pathlib2
    ImportError: No module named pathlib2
    Command '"/usr/bin/python" -u build.py build' failed with exit code 1.
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-GzFPrP/wxPython/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-x0EMi7-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-GzFPrP/wxPython/

**Operating system**:
**wxPython version & source**:          
**Python version & source**:            

**Description of the problem**:

```python
# Put code sample here
```

**Comment by RobinD42** [comment]
This has already been fixed for the next releases, but in the meantime your build environment needs to include pathlib2 as a dependency.
