### ISSUE TITLE
wx.ListCtrl has no attribute EnableCheckBoxes

### ISSUE THREAD

**Issue by benbou8231** [wxWidgets/Phoenix#1394]
**Operating system**: Windows 10 (Version 1709, Build 16299.1387)
**wxPython version & source**: 4.0.6 from pypi
**Python version & source**: 3.7.3 from python.org (v3.7.3:ef4ec6ed12)

**Description of the problem**:
When I try to call the method EnableCheckBoxes() of wx.ListCtrl an error message is displayed: AttributeError: 'ListCtrl' object has no attribute 'EnableCheckBoxes'

https://wxpython.org/Phoenix/docs/html/wx.ListCtrl.html#wx.ListCtrl.EnableCheckBoxes

```python
import wx

class MyPanel(wx.Panel):
    def __init__(self, parent):
        wx.Panel.__init__(self, parent)

        self.list_ctrl = wx.ListCtrl(self, style=wx.LC_REPORT)
        self.list_ctrl.EnableCheckBoxes()

class MyFrame(wx.Frame):
    def __init__(self):

        wx.Frame.__init__(self, None, wx.ID_ANY)
        panel = MyPanel(self)
        self.Show()
 
if __name__ == "__main__":
    app = wx.App(False)
    frame = MyFrame()
    app.MainLoop()
```

Please note that the problem can also be reproduced with the demo.

python C:\Phoenix-master\demo\ListCtrl.py

**Comment by RobinD42** [comment]
That is the link for the in-development version of wxPython (4.1.0alpha). The docs for the released version (4.0.6) are located at https://docs.wxpython.org/
