### ISSUE TITLE
wx.AppConsole.UsesEventLoop is not available

### ISSUE THREAD

**Issue by pauldmccarthy** [wxWidgets/Phoenix#1399]
Howdy,

As part of integrating my application with `jupyter notebook`, I am trying to figure out how to detect if a `wxpython` application is running with *any* event loop, not necessarily the main loop.

The [`wx.AopConsole.UsesEventLoop`](https://docs.wxwidgets.org/trunk/classwx_app_console.html#af393b68a318373e43ee731bec38bdc29) method seems like the thing I need, but it is [not exposed in the Python wrapper](https://github.com/wxWidgets/Phoenix/blob/32815309d40c2e7988505aeca1097bc97ee2644c/etg/app.py#L58).

Is there any reason for this? Can I submit a PR to make it available in a future version?

Thanks!

**Comment by pauldmccarthy** [comment]
Update: This will cease to be an issue for me personally if my [IPython PR](https://github.com/ipython/ipython/pull/11911) gets merged, as I am proposing that the IPython input hook now uses the `MainLoop`, rather than a separate event loop.

**Comment by RobinD42** [comment]
I'm not sure why it was excluded, (9 years ago according to git), but I see no reason to do so now so I'll add it back in for the next release.

**Comment by pauldmccarthy** [comment]
Cool, thanks! It turns out that my use-case is a bit more complicated - I wanted to be able to detect whether an event loop is running, so I could decide whether to schedule tasks asynchronously or run them directly.  But IPython/Jupyter start/stop the wx event loop (mainloop or otherwise) periodically, so I've had to do things differently. 

But thanks for the change!
