### ISSUE TITLE
PopupMenu(menu, pos) positions the menu wrong

### ISSUE THREAD

**Issue by topic2k** [wxWidgets/Phoenix#1404]
**Operating system**: Ubuntu 19.04
**wxPython version & source**: 4.1.0a1.dev4421+ec1600d2 gtk3 (phoenix) wxWidgets 3.1.3 (self-build from [snapshot](https://wxpython.org/Phoenix/snapshot-builds))
**Python version & source**: 3.8.0 from [Ubuntu packages](https://packages.ubuntu.com/search?keywords=python3.8)

Calling `PopupMenu(menu, pos)` places the popup menu on wrong position if the window is not on the leftmost display. The problem occurs only with `pos` parameter, just calling `PopupMenu(menu)` correctly places the menu under the mouse pointer.
The problem is only with Ubuntu, on Win10 (Python 3.8.0, wxPython 4.1.0a1.dev4420) it works correctly.

<details>
<summary>On first display (leftmost)</summary>

![vlcsnap-2019-10-22-14h48m30s169](https://user-images.githubusercontent.com/6463113/67287452-76d20000-f4db-11e9-963a-e3068378c304.png)

</details>

<details>
<summary>On second display</summary>

![vlcsnap-2019-10-22-14h49m05s454](https://user-images.githubusercontent.com/6463113/67287458-79ccf080-f4db-11e9-9258-d216685006fe.png)

</details>

<details>
<summary>small runnable application</summary>

```python
import wx
from wx.lib.mixins.inspection import InspectableApp


class TestFrame(wx.Frame):

    def __init__(self):
        super(TestFrame, self).__init__(None, size=(600, 300))

        btn = wx.Button(self, wx.ID_ANY, label='click me')
        btn.Bind(wx.EVT_BUTTON, self.on_button)
        szr = wx.BoxSizer()
        szr.Add(btn)

    def on_button(self, event):
        obj = event.GetEventObject()
        print('MousePosition:', wx.GetMousePosition())
        print('ObjectPosition:', obj.GetPosition())
        print()
        pum = wx.Menu()
        pum.Append(wx.ID_ANY, 'Item 1')
        pum.Append(wx.ID_ANY, 'Item 2')
        pum.Append(wx.ID_ANY, 'Item 3')
        obj.PopupMenu(pum, (20, 20))


if __name__ == '__main__':
    app = InspectableApp()
    win = TestFrame()
    win.Show()
    app.MainLoop()

```

</details>

**Comment by RobinD42** [comment]
It looks like this probably a wxWidgets problem. Please create a ticket for this at https://trac.wxwidgets.org/, if one doesn't already exist, and add a link to the ticket here so we can track it.

**Comment by topic2k** [comment]
On trac.wxwidgets.org i've found a [changeset](https://trac.wxwidgets.org/changeset/36712/svn-wx)/[commit](https://github.com/wxWidgets/wxWidgets/commit/75ce4782c74d2d3f86c1798ea8d8a38e54c3a8bc) from 2006 where you are stating that 

>  It is now recommended to not pass the position to PopupMenu and to let the platform position the menu itself

I guess that is still valid. I'm going to do a pull request where the position parameter is removed (in places i could test)
