### ISSUE TITLE
interpreter crash with ribbonbar_demo

### ISSUE THREAD

**Issue by mprosperi** [wxWidgets/Phoenix#141]
the ribbonbar_demo.py in the samples directory crashes the interpreter clicking on the appearance tab (no problem with the agw version of ribbon demo). With py3.4 64bit on win7

**Comment by swprojects** [comment]
I've only briefly tested ribbonbar_demo.py so I don't really what is going on with the code.

but from testing, the problem isn't clicking on the appearance tab. if you hover anywhere, other than the primary colour/secondary colour section, it won't crash.

primary colour/secondary colour both add some instance of RB.RibbonGallery to their respective panel.  

The mouse hover event RB.EVT_RIBBONGALLERY_HOVER_CHANGED is handled by OnHoveredColourChange. 

So I traced the error to: 
gallery.SetArtProvider(provider)

So if you comment this line out in the demo, it won't crash. For example

```python
def OnHoveredColourChange(self, event):
        # Set the background of the gallery to the hovered colour, or back to the
        # default if there is no longer a hovered item.        
        gallery = event.GetGallery()
        provider = gallery.GetArtProvider()

        if event.GetGalleryItem() != None:            
            if provider == self._ribbon.GetArtProvider():
                provider = provider.Clone()  
                # gallery.SetArtProvider(provider) 
                
            provider.SetColour(RB.RIBBON_ART_GALLERY_HOVER_BACKGROUND_COLOUR,
                               self.GetGalleryColour(event.GetGallery(), event.GetGalleryItem(), None)[0])

        else:
            if provider != self._ribbon.GetArtProvider():
                gallery.SetArtProvider(self._ribbon.GetArtProvider())
                del provider
```

maybe, inspecting "gallery.SetArtProvider(provider)" will help you get to the root of the problem

**Comment by swt2c** [comment]
Thanks @swprojects for the reproducer and analysis.  I couldn't reproduce initially.  Anyway, the problem is the Clone() right above there.  I'll submit a PR to correct.
