### ISSUE TITLE
"long" type still used in the demo!

### ISSUE THREAD

**Issue by ricpol** [wxWidgets/Phoenix#1414]
Sorry to bother with yet another micro-issue, but I found that demo/MaskedNumCtrl.py at line 331 has 
```python
numvalue = long(value)
```
where it obviously should be 
```python
numvalue = int(value) # even for py 2.7
```
... unless of course you really want to keep it for its archeological value ;-)

Anyways, this actually causes a small problem in the masked.NumCtrl demo (in python 3) where you can't select a few integer values in the bottom combobox.

**Comment by RobinD42** [comment]
Fixed in 8e054e3 and another commit somewhere...
