### ISSUE TITLE
Caret Move Event on wx.TextCtrl

### ISSUE THREAD

**Issue by mush42** [wxWidgets/Phoenix#1420]
Hello,

I'm developing an accessible eBook reader using wxPython. The main text of the openned book is shown in a wx.TextCtrl. For performance reasons , the text is paginated, and the user is required to press enter/backspace to navigate the pages.

Many users requested a continuous reading mode, where pages are turned automatically when the caret reaches the end of the content. This, of course, requires tracking the movement of the caret.

It seams that wx.TextCtrl has no way to track the movement of the caret. I'm aware of using wx.EVT_KEY_UP to do this, but when using a screen reader to read the content of an edit control, the screen reader uses accessibility APIs to move the caret.

My question is: how to track the movement of the caret in a wx.TextCtrl?

Related issue: mush42/bookworm#3

Regards,

**Comment by RobinD42** [comment]
There isn't an event for it, but you could use a timer and check the textctrl's `GetInsertionPoint` method to get where the caret is positioned and see if it has moved since the last time you checked
