### ISSUE TITLE
Strange crash with wxFrame, wxGridTable, wxGrid, Gdk and X Window System

### ISSUE THREAD

**Issue by hekkup** [wxWidgets/Phoenix#1421]
**Operating system**: Ubuntu 18.04.3 LTS
**wxPython version & source**: 4.0.6 from pypi
**Python version & source**: 3.6.8, stock

**Description of the problem**:

I'm getting a strange error from Gdk layer or something. Application crashes with the dumped message attached below. I know there are issues with my application, including thread synchronization, but this looked such a strange one that I wanted to report it.

I have a frame2 derived from a frame1 derived from wxFrame (three layers), a data table derived from GridTableBase, and a wxGrid having the data table as data model. The grid is created in the middle layer (frame1). There's a thread in an external module which calls every 2 seconds a listener function in the highest-level frame2. The listener function updates the table, which forces update in the grid. There's not any synchronization happening currently. This call chain and the lack of synchronization is in itself a source of a lot of possibilities for the root cause of the crash, but the fact that Gdk is involved _might_ indicate some issues with wxPython.

**Dump:**
```
(myApp.py:20221): Gdk-ERROR **: 14:16:12.701: The program 'myApp.py' received an X Window System error.
This probably reflects a bug in the program.
The error was 'RenderBadPicture (invalid Picture parameter)'.
  (Details: serial 27699 error_code 143 request_code 139 (RENDER) minor_code 26)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Trace/breakpoint trap (core dumped)
```

**Comment by RobinD42** [comment]
You need to ensure that you are not doing anything in the worker thread that creates, updates, or otherwise manipulates UI elements. If you need to trigger some change from the thread that updates the UI then it should trigger something that will defer the actual change over to the main GUI thread to do the real UI work. The `wx.CallAfter` function is an easy way to do that for most cases.

**Comment by hekkup** [comment]
Duh. Right. Thanks!
