### ISSUE TITLE
agw lib use undefined RendererNative.DrawTitleBarBitmap method

### ISSUE THREAD

**Issue by acollange** [wxWidgets/Phoenix#1425]
**Operating system**: Windows 10
**wxPython version & source**: wxPython 4.0.7
**Python version & source**:  3.7

Agw lib use RendererNative.DrawTitleBarBitmap which is no defined in wxPython 4.0.7
Below the traceback

```python
  File "C:\...\python\lib\site-packages\wx\lib\agw\infobar.py", line 379, in __init__
    bmp = GetCloseButtonBitmap(self, sizeBmp, colBg)
  File "C:\...\python\lib\site-packages\wx\lib\agw\infobar.py", line 226, in GetCloseButtonBitmap
    wx.RendererNative.Get().DrawTitleBarBitmap(win, dc, wx.Rect(size), wx.TITLEBAR_BUTTON_CLOSE, flags)
AttributeError: 'RendererNative' object has no attribute 'DrawTitleBarBitmap'

```

**Comment by infinity77** [comment]
I guess it’s just missing from the wrappers somehow... as it exists in wxWidgets:

https://docs.wxwidgets.org/3.0/classwx_renderer_native.html#a0bfb492af0725bd49a1402baa5f68e12

**Comment by RobinD42** [comment]
It looks like I explicitly disabled it in the wrapper extraction steps, but there's no comments as to why it was done. I'll take another look at it when I have some time.
