### ISSUE TITLE
wx.lib.plot scrollbars do not show ever

### ISSUE THREAD

**Issue by kurisutsukato** [wxWidgets/Phoenix#1428]
**platform**: all
**wxPython Version & source**: 4.0.3 pypi          
**Python Version & source**: 2.7           

**The scrollbars of a wx.lib.plot.PlotCanvas are not shown ever**:

The issues can be observed in the demo or by running the following code.

```python
from wx.lib.plot import PlotCanvas, PlotGraphics, PolyLine
import wx
import numpy as np

app = wx.App()
f = wx.Frame(None)
canvas = PlotCanvas(f)
f.Fit()
f.Show()

x = np.linspace(0,10,100)
y = x**2

line = PolyLine(np.array([x,y]).T)
pg = PlotGraphics([line])
canvas.Draw(pg)
canvas.showScrollbars = True
canvas.enableZoom = True

app.MainLoop()
```

**Comment by RobinD42** [comment]
This issue has been mentioned on **Discuss wxPython**. There might be relevant details there:

https://discuss.wxpython.org/t/wxpython-4-1-0-released/34564/1
