### ISSUE TITLE
Build failed on MacOS Catalina 10.15.1

### ISSUE THREAD

**Issue by AllenDang** [wxWidgets/Phoenix#1431]
**Operating system**: MacOS Catalina 10.15.1
**wxPython version & source**:          Checkout from github latest with git submodule update --init --recursive
**Python version & source**:            python 3.7.4

**Description of the problem**:
The build command is: python build.py dox etg --nodoc sip build

Error message is:
Checking for /Users/allendang/Downloads/Phoenix/bin/sip-4.19.16-darwin...
Not found.  Attempting to download...
Connection successful...
Data downloaded...
Checking for /Users/allendang/Downloads/Phoenix/bin/sip-4.19.16-darwin...
ERROR: Could not execute /Users/allendang/Downloads/Phoenix/bin/sip-4.19.16-darwin, got "[Errno 86] Bad CPU type in executable: '/Users/allendang/Downloads/Phoenix/bin/sip-4.19.16-darwin'"
       Set SIP in the environment to use a local build of sip instead

**Comment by RobinD42** [comment]
Yep, I've got a fix on the way for this.

**Comment by RobinD42** [comment]
Fixed by #1432
