### ISSUE TITLE
AttributeError: type object 'WebView' has no attribute 'MSWSetEmulationLevel

### ISSUE THREAD

**Issue by somelinguist** [wxWidgets/Phoenix#1434]
**Operating system**:                         Windows 10 1903
**wxPython version & source**:          4.0.7.post1 from pypi
**Python version & source**:              stock CPython 3.8.0 in venv, 64bit

Calling `wx.html2.WebView.MSWSetEmulationLevel(wx.html2.WEBVIEWIE_EMU_IE11)` gives the following error:

`AttributeError: type object 'WebView' has no attribute 'MSWSetEmulationLevel'`

```python
import wx
import wx.html2

class MyFrame(wx.Frame):
    def __init__(self, parent):
        wx.Frame.__init__(self, parent)
        sizer = wx.BoxSizer(wx.VERTICAL)
        wx.html2.WebView.MSWSetEmulationLevel(wx.html2.WEBVIEWIE_EMU_IE11)
        self.view = wx.html2.WebView.New(self)
        sizer.Add(self.view, 2, wx.EXPAND|wx.ALL, 5)
        self.SetSizer(sizer)
        self.view.LoadURL('http://localhost')
        self.Layout()

if __name__ == "__main__":
    app = wx.App(False)
    frame = MyFrame(None)
    frame.Show()
    app.MainLoop()

```

**Comment by RobinD42** [comment]
That method was added in 4.1, at the moment you'll need to use a preview snapshot to get a build that includes it.
