### ISSUE TITLE
Script crashes when wx.LogError is passed a string containing '%'

### ISSUE THREAD

**Issue by malown** [wxWidgets/Phoenix#1435]
**Operating system**: Windows 10
**wxPython version & source**:  4.0.7.post1 (installed via pip)
**Python version & source**:  3.7.5 (installed via chocolatey)

**Description of the problem**:

When you pass a string that contains a percentage sign to wx.LogError the interpreter stops without any error message or exception raised

```python
import wx

class App(wx.App):
    def __init__(self):
        super().__init__()

        self.frame = wx.Frame(parent=None)

        wx.Button(self.frame, label="Crash").Bind(wx.EVT_BUTTON, self.button)

        self.frame.Show()

    def button(self, evt):
        wx.LogError("Test %")

if __name__ == '__main__':
    App().MainLoop()
```

**Comment by RobinD42** [comment]
wx's logging functions use the [C printf family](http://www.cplusplus.com/reference/cstdio/printf/) of functions and the '%' is used to signal a formatting character that will pull an extra parameter of the specified type from the stack. This is one of the infamous shoot-yourself-in-the-foot features of C. If you want to have a '%' in the string then you need to double it and use '%%'.
