### ISSUE TITLE
Python 3.5 wheels are missing on Pypi with wxPython 4.0.7.post2 release

### ISSUE THREAD

**Issue by eamars** [wxWidgets/Phoenix#1438]
Hello 
I noticed wheel for wxPython 4.0.7.post2 for Python 3.5 gone missing on Pypi. The minimum Python 3 support is Python 3.6 now. 

I wonder Is the Python 3.5 wheel release will no longer be supported in the future?

**Comment by RobinD42** [comment]
I used wxPython 4.1's buildbot to do the build since the old buildbot wasn't running at the time, and I've turned off Python3.5 builds for 4.1.  I've started a set of builds of 4.0.7.post2 for Python3.5, and will upload them to pypi in a couple hours.

**Comment by RobinD42** [comment]
Done.
