### ISSUE TITLE
Unknown Locale

### ISSUE THREAD

**Issue by kg-2** [wxWidgets/Phoenix#1440]
**Operating system**: windows 10
**wxPython version & source**:          pip nightly 4.1.0a1.dev4490+863383ba
**Python version & source**:            stock 3.7.4

**Description of the problem**:

I'm running into python bug [20088](https://bugs.python.org/issue20088) because the default wxpython locale of "en-GB" doesn't include the encoding ("en-GB.UTF-8")

I would receive a `ValueError unknown locale "en-US"` whenever `locale.getlocale()` was called. I'm working around the error by calling `local.setlocale(locale.LC_ALL, "en-US.UTF-8")` after the `wx.App()` has been initiated. I tried to create a `wx.Locale()` object explicitly, but it kept raising `AssertionErrors` thinking that I had called `locale.setlocale`

```python
import locale
import traceback

good_locale = "en-GB.UTF-8"
bad_locale = "en-GB"


def test_locale(_locale):
    locale.setlocale(locale.LC_ALL, _locale)

    try:
        locale.getlocale()
    except ValueError:
        print(f"failed to retrieve {_locale}")
    else:
        print(f"successfully set/retrieved {_locale}")


try:
    test_locale(good_locale)
    test_locale(bad_locale)
except:
    traceback.print_exc()

input()

```

**Comment by ricpol** [comment]
This a Python issue (and not one that will be fixed anytime soon I'm afraid). 
wx.Locale must be set with its own, unrelated, language codes https://wxpython.org/Phoenix/docs/html/wx.Language.enumeration.html and I *think* there is no way to pass a previously set Python locale to a wxPython mainloop. 
Try this:
```python
class App(wx.App):
    def OnInit(self):
        print('Default as understood by wxPython:',
                  wx.Locale.GetLanguageName(wx.Locale.GetSystemLanguage()))
        self.locale = wx.Locale(wx.LANGUAGE_SPANISH)
        wx.Frame(None).Show()
        return True

    def OnExit(self):
        print('Set by wxPython:', wx.Locale.GetLanguageName(self.locale.GetLanguage()))
        return True

print('Default as understood by Python:', locale.getdefaultlocale())
locale.setlocale(locale.LC_ALL, 'Russian_Russia') # windows spelling
print('Set by Python:', locale.getlocale())

app = App(False)
app.MainLoop()

print('Passed by wxPython to Python on exit:', locale.getlocale())
```
