### ISSUE TITLE
wx.Colour does not accept float values in debug mode

### ISSUE THREAD

**Issue by DarkFenX** [wxWidgets/Phoenix#1442]
**Operating system**: Debian Testing, Xorg with 200% scaling
**wxPython version & source**: 4.0.7 gtk3 (phoenix) wxWidgets 3.0.4 from debian repos
**Python version & source**: 3.7.5 from debian repos

**Description of the problem**:
wx.Colour takes float as values during normal execution (from both console and pycharm), but does not take them in pycharm debug mode:
```
Traceback (most recent call last):
  File "/mnt/fast/dfx_space/software/pycharm/helpers/pydev/pydevd.py", line 2073, in <module>
    main()
  File "/mnt/fast/dfx_space/software/pycharm/helpers/pydev/pydevd.py", line 2067, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/mnt/fast/dfx_space/software/pycharm/helpers/pydev/pydevd.py", line 1418, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/mnt/fast/dfx_space/software/pycharm/helpers/pydev/pydevd.py", line 1425, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/mnt/fast/dfx_space/software/pycharm/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/dfx/Workspace/eve/pyfa/wxtest.py", line 3, in <module>
    wx.Colour(1.0, 1.0, 1.0, 1)
TypeError: Colour(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 1 has unexpected type 'float'
  overload 3: argument 1 has unexpected type 'float'
  overload 4: argument 1 has unexpected type 'float'
```

```python
import wx

wx.Colour(1.0, 1.0, 1.0, 1)
```

Pycharm it launches the following way: `/usr/bin/python3.7 /mnt/fast/dfx_space/software/pycharm/helpers/pydev/pydevd.py --multiproc --qt-support=auto --client 127.0.0.1 --port 33023 --file /home/dfx/Workspace/eve/pyfa/wxtest.py`

**Comment by DarkFenX** [comment]
I know that wx docs provide integers as the only valid way to pass arguments to `wx.Colour`, but I am still curious to what causes inconsistencies to this behavior.

**Comment by RobinD42** [comment]
Are you sure that the same wxPython is being used in both cases? I seem to recall seeing errors like this in some early 4.0.x builds of wxPython due to a regression in an older sip.

The code that's processing those args basically just does some checking and then ends up using Python's `PyLong_AsUnsignedLongMask` API do do the conversion. That API will call the object's `__int__` method if the object is not already an integer.  For example:

```
>>> import wx
>>> wx.version()
'4.0.7.post2 osx-cocoa (phoenix) wxWidgets 3.0.5'
>>> 
>>> class MyFloat(float):
...     def __int__(self):
...         print('__int__ called')
...         return super().__int__()
...         
>>> 
>>> 
>>> mf = MyFloat(123.45)
>>> int(mf)
__int__ called
123
>>> wx.Colour(123.45, 1, 1)
wx.Colour(123, 1, 1, 255)
>>> 
>>> wx.Colour(mf, 1, 1)
__int__ called
wx.Colour(123, 1, 1, 255)
>>> 
```

**Comment by DarkFenX** [comment]
I checked it by printing `wx.__file__` on line preceding the call to `wx.Colour`.

Non-debug run: `/usr/lib/python3/dist-packages/wx/__init__.py`
Debug run: `/usr/lib/python3/dist-packages/wx/__init__.py`

What are

**Comment by RobinD42** [comment]
That should be sufficient to make the determination.

I guess the next step is to see if there is any difference between the `os.environ` in the two cases.

**Comment by DarkFenX** [comment]
There is:
```
$ diff ~/Desktop/nondebug.txt ~/Desktop/debug.txt 
9a10
> IDE_PROJECT_ROOTS: /home/dfx/Workspace/eve/pyfa
24c25
< PYTHONPATH: /home/dfx/Workspace/eve/pyfa:/mnt/fast/dfx_space/software/pycharm/helpers/pycharm_matplotlib_backend:/mnt/fast/dfx_space/software/pycharm/helpers/pycharm_display
---
> PYTHONPATH: /home/dfx/Workspace/eve/pyfa:/mnt/fast/dfx_space/software/pycharm/helpers/pycharm_matplotlib_backend:/mnt/fast/dfx_space/software/pycharm/helpers/pycharm_display:/mnt/fast/dfx_space/software/pycharm/helpers/third_party/thriftpy:/mnt/fast/dfx_space/software/pycharm/helpers/pydev:/home/dfx/.PyCharm2019.2/system/cythonExtensions
27a29
> IPYTHONENABLE: True
38a41
> PYDEVD_LOAD_VALUES_ASYNC: True
39a43
> LIBRARY_ROOTS: /usr/lib/python3.7:/usr/lib/python3.7/lib-dynload:/home/dfx/.local/lib/python3.7/site-packages:/usr/local/lib/python3.7/dist-packages:/usr/lib/python3/dist-packages:/home/dfx/.PyCharm2019.2/system/python_stubs/-1247971762:/mnt/fast/dfx_space/software/pycharm/helpers/python-skeletons:/mnt/fast/dfx_space/software/pycharm/helpers/typeshed/stdlib/3:/mnt/fast/dfx_space/software/pycharm/helpers/typeshed/stdlib/2and3:/mnt/fast/dfx_space/software/pycharm/helpers/typeshed/third_party/3:/mnt/fast/dfx_space/software/pycharm/helpers/typeshed/third_party/2and3
49a54
> PYTHONDONTWRITEBYTECODE: 1
```

**Comment by DarkFenX** [comment]
`$ IDE_PROJECT_ROOTS=/home/dfx/Workspace/eve/pyfa PYTHONPATH=/home/dfx/Workspace/eve/pyfa:/mnt/fast/dfx_space/software/pycharm/helpers/pycharm_matplotlib_backend:/mnt/fast/dfx_space/software/pycharm/helpers/pycharm_display:/mnt/fast/dfx_space/software/pycharm/helpers/third_party/thriftpy:/mnt/fast/dfx_space/software/pycharm/helpers/pydev:/home/dfx/.PyCharm2019.2/system/cythonExtensions IPYTHONENABLE=True PYDEVD_LOAD_VALUES_ASYNC=True LIBRARY_ROOTS=/usr/lib/python3.7:/usr/lib/python3.7/lib-dynload:/home/dfx/.local/lib/python3.7/site-packages:/usr/local/lib/python3.7/dist-packages:/usr/lib/python3/dist-packages:/home/dfx/.PyCharm2019.2/system/python_stubs/-1247971762:/mnt/fast/dfx_space/software/pycharm/helpers/python-skeletons:/mnt/fast/dfx_space/software/pycharm/helpers/typeshed/stdlib/3:/mnt/fast/dfx_space/software/pycharm/helpers/typeshed/stdlib/2and3:/mnt/fast/dfx_space/software/pycharm/helpers/typeshed/third_party/3:/mnt/fast/dfx_space/software/pycharm/helpers/typeshed/third_party/2and3 PYTHONDONTWRITEBYTECODE=1 PYTHONIOENCODING=UTF-8 PYTHONUNBUFFERED=1 python3 wxtest.py` launched from console does not crash.

Following is the os.environ difference between debug run and this run:
```
$ diff -U0 ~/Desktop/console.txt ~/Desktop/debug.txt 
--- /home/dfx/Desktop/console.txt	2019-11-20 09:46:03.751662102 +0300
+++ /home/dfx/Desktop/debug.txt	2019-11-20 09:33:36.190773297 +0300
@@ -2 +1,0 @@
-COLORTERM: truecolor
@@ -4,0 +4,2 @@
+GIO_LAUNCHED_DESKTOP_FILE: /home/dfx/.local/share/applications/jetbrains-pycharm.desktop
+GIO_LAUNCHED_DESKTOP_FILE_PID: 3985
@@ -8,2 +8,0 @@
-GNOME_TERMINAL_SCREEN: /org/gnome/Terminal/screen/07df424b_569d_4b92_a663_0d74ef04972c
-GNOME_TERMINAL_SERVICE: :1.153
@@ -31,0 +31 @@
+OLDPWD: /mnt/fast/dfx_space/software/pycharm/bin
@@ -33,0 +34,2 @@
+PYCHARM_DISPLAY_PORT: 63342
+PYCHARM_HOSTED: 1
@@ -44 +46 @@
-SHLVL: 2
+SHLVL: 1
@@ -47 +49 @@
-TERM: xterm-256color
+TERM: linux
@@ -49 +50,0 @@
-VTE_VERSION: 5802
@@ -59,2 +60 @@
-_: /usr/bin/python3
-
+_: /usr/bin/startx
```

**Comment by martinpetrus** [comment]
Seems to be a compatibility issue between python 3.10 and wxWidgets (see [this comment](https://github.com/wxWidgets/Phoenix/issues/2038#issuecomment-982048206)).

I tried to add a couple of type conversions which seemed to do the trick (see [#2391](https://github.com/pyfa-org/Pyfa/issues/2391#issue-1082246469))

**Comment by swt2c** [comment]
Not an incompatibility, but rather a change in Python 3.10 to disallow passing floats to extension modules where ints are expected.

**Comment by swt2c** [comment]
I suspect in @DarkFenX case, switching to debug mode somehow disabled the silent coercion to int that was happening before.
