### ISSUE TITLE
bug in lib.agw.customtreectrl method GetCurrentCheckedImage

### ISSUE THREAD

**Issue by ras37srq** [wxWidgets/Phoenix#1444]
Windows 10:
wx.__version__  =  '4.0.7.post2':   
python =  Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 22:20:52)

Problem:
      Exception:      Error:  '>' not supported between instances of 'list' and 'int'

      In method GetCurrentCheckedImage of class GenericTreeItem in customtreectrl.py, the 3rd and 4th code lines are:

`        checked = self.IsChecked()

        if checked > 0:`

      It appears the method self.IsChecked() can return values of either 0 (zero) or [] (empty list).

Fix:
      Change ` if checked > 0:`
      To:    `if checked:`

**Comment by RobinD42** [comment]
Can you provide a small sample and/or steps needed to reproduce the issue?  I don't think it is expected to get a list there, so the real problem is probably somewhere else.

**Comment by ras37srq** [comment]
Robin,
      Thank you for the prompt reply.

      Unfortunately it would be very difficult and extremely time-consuming for me to do that.  This is embedded in a very large application which uses a lot of features of the CustomTreeCtrl and those are scattered around a large View class (View as in MVP, Model/View/Presenter).  I just cannot afford the time to do that right now.

     I can guarantee you, though, that I set a breakpoint at that location and saw .IsChecked return both 0 and [].  I looked at .IsChecked briefly and saw that the problem would be deeper, like in .GetValue or lower.  I can also say that I changed that line to ‘if checked:’ and saw no ill ramifications from doing so.

     If you or others require finding the root cause and are unwilling to make that change, what about putting ‘assert isinstance(checked, int)’ there and somebody somewhere is likely to trigger it and perhaps be more able to give you a debuggable example than am I.

     Sorry.

Best regards … Bob

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by RobinD42** [comment]
How about a compromise? Add an `isinstance` assert into `GenericTreeItem.Check` and `GenericTreeCtrl.Set3StateValue` and let's see if it can be determined where the `[]` is coming from in your case. The only valid values should be True/False or one of the wx.CheckBoxState enum values (0,1,2).

**Comment by ras37srq** [comment]
Robin,

     Found it.  The problem was that in one place I call .CheckItem with the value of checked being a variable whose value is a list.  The logic works fine in my code because I indeed want the item unchecked if the list is empty (so, False), and checked if the list is not empty (so True).

     .CheckItem just accepts whatever you give it and the list works fine throughout the logic in .CheckItem which then hands that value to .Check which sets self._checked.   So all is fine in the setting, but when my program later calls .GetCurrentCheckedImage and the code checks it against an integer value, then the exception occurs.

     My code was technically non-compliant because it is documented that the ‘checked’ arg to .CheckItem should be bool, so I’m easily fixed by changing my  call to coerce and be .CheckItem(node, bool(listThing))  .   However, with  the manifestation of giving a non-bool arg to .CheckItem cause an exception far from the root cause, I would think it would be helpful to either type-check in .CheckItem to raise an exception there, or in .GetCurrentCheckedImage to make the ‘if checked:’ change, or both.

     Again, thank you so much for your prompt and constructive response.  I’m impressed by all you’ve done for WxPython for all these years; many of us are truly grateful.

Cheers … Bob
