### ISSUE TITLE
no LICENSE file 

### ISSUE THREAD

**Issue by kdschlosser** [wxWidgets/Phoenix#1461]
I might be going crazy here.. or maybe I am not. In the setup.cfg file there is a line for the license

`license-file = LICENSE.txt`

I would imagine that the LICENSE.txt file would need to be located in the same folder as the setup program.. I am not seeing it. Nor is there any license information at the top of the setup.py file.

I thought that phoenix uses the same license as wxWidgets, and when i went to look for the LICENSE.txt file for wxWidgets there is not one to be found.

I am sure that there is license information somewhere but it is not easily found, it should be right there in the root of the project directory.

I wanted to know what the license is. I thought that is was a "special" or custom license not one of the typically used Mozilla, GNU, MIT and Apache licenses. If that is the case then would someone be able to inform me of the compatibility to the commonly used licenses. I would also like to know what the requirements are that need to be fulfilled in order to use the license that Phoenix uses? This is for purposes of having code added to phoenix.

**Comment by RobinD42** [comment]
The file is copied into place as part of the build, is included in the source tar file, and is installed as part of the package metadata when installed with pip. As can be seen in `setup.py` [here](https://github.com/wxWidgets/Phoenix/blob/master/setup.py#L42), and in the sidebar at [PyPI](https://pypi.org/project/wxPython/), it is the same as the license used by wxWidgets. It is essentially LGPL with an exception.
