### ISSUE TITLE
UnboundLocalError

### ISSUE THREAD

**Issue by c-rei** [wxWidgets/Phoenix#1469]
I had referred your sample, and make an application for multi-languages.
But I have come across something weird. My environment is below.

**Operating system**:  Windows 7
**wxPython version**:   Version 4.0.4
**Python version**:        Version 3.6.9

**Description of the problem**:

Some where I got an error like below, but no error with similar code elsewhere.
Could you give my any advises?
 
  UnboundLocalError: local variable '_' referenced before assignment

My Code is : 
        dlg = wx.MessageDialog(self,
                                _("Disconnect to one drive.\nAre you sure you want to continue?"),
                                _('Message'),
                                wx.YES_NO | wx.NO_DEFAULT | wx.ICON_INFORMATION
                                )
        res = dlg.ShowModal()
        dlg.Destroy()
        if res !=  wx.ID_YES:
            return

**Comment by RobinD42** [comment]
You are probably missing something like `_ = wx.GetTranslation` at module scope.

**Comment by c-rei** [comment]
Mr. Robin
Thanks your responses.

I'v declared _ = wx.GetTranslation at module scope like below, and I'v known the reason of this issue.
import builtins
builtins.__dict__['_'] = wx.GetTranslation

At the same function, I used _ to ignore some return from other library.
data, _ = winreg.QueryValueEx(jsc_key, folder_id)

So when I call the _("Some message which will be translated"), this error occurred.
I'v changed my code like this     data, ss = winreg.QueryValueEx(jsc_key, folder_id).
