### ISSUE TITLE
Crash when accessing wx via introspection

### ISSUE THREAD

**Issue by SReicheltPTV** [wxWidgets/Phoenix#1479]
**Operating system**: Windows 10
**wxPython version & source**: 4.0.4 msw (phoenix) wxWidgets 3.0.5 (via pip)
**Python version & source**: stock 3.7.4 (also occurs in 3.8)

**Description of the problem**:

wxPython on Windows causes the Python interpreter to crash if any of `wx.NullGraphicsBitmap.NativeBitmap`, `wx.NullGraphicsMatrix.NativeMatrix`, or `wx.NullGraphicsPath.NativePath` are accessed. Unfortunately, this can easily happen via introspection in an interactive shell. E.g. unfolding "wx" in the "Ingredients" tab in PyCrust immediately leads to a crash.

**Example test case**:

```python
import wx
wx.NullGraphicsBitmap.NativeBitmap
```

**Comment by Metallicow** [comment]
I can confirm the crash with PyCrust. Just typing and firing `wx.NullGraphicsBitmap.NativeBitmap` in the PyShell caused it to crash on Win7. Didn't even have to unfold anything.
wxPython 4.0.7.post2 msw (phoenix) wxWidgets 3.0.5 Scintilla 3.21
Python 2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 20:49:36) [MSC v.1500 32 bit (Intel)] on win32

**Comment by RobinD42** [comment]
A fix is on the way...

**Comment by SReicheltPTV** [comment]
Thank you very much!
