### ISSUE TITLE
a translate issue

### ISSUE THREAD

**Issue by thundertwo** [wxWidgets/Phoenix#1484]
**Operating system**:
**wxPython version & source**:          
**Python version & source**:            

**Description of the problem**:
just a translate issue

```python
# Put code sample here
wx.ID_EXIT 
the wx.ID_EXIT return 推出此程序 
but the right should return 退出此程序
```

**Comment by RobinD42** [comment]
In what context are you seeing this issue?

**Comment by thundertwo** [comment]
https://www.wxpython.org/pages/overview/
in this web Hello World! part 2 
source code : the 56 lines : exitItem = fileMenu.Append(wx.ID_EXIT)

**Comment by Metallicow** [comment]
推出此程序 translates to Launch this program
退出此程序 translates to Exit this program
according to google. I speak american english.
Yes, that seems to be a error. Launching and exiting are two different things. 
Reloading means to exit then launch.
Hope this helps...
