### ISSUE TITLE
Missing userData in dynamic event handling

### ISSUE THREAD

**Issue by AndreaLu** [wxWidgets/Phoenix#1486]
I just wanted to report what appears to be a missing feature in the python port that I have seen in other platforms.
Quoting your documentation:
[wx.Event page](https://wxpython.org/Phoenix/docs/html/wx.Event.html#wx.Event.GetEventUserData)
> wx.EvtHandler.Connect and wx.EvtHandler.Bind allow associating optional userData pointer with the handler and this method returns the value of this pointer.

But then the event handling page does not report any version of Bind or Connect that allow such thing
[wx.EvtHandler page](https://wxpython.org/Phoenix/docs/html/wx.EvtHandler.html#wx.EvtHandler.Bind)

**Comment by RobinD42** [comment]
The user data field in the event tables is used by wxPython to store the `PyObject*` of the bound event handler function, so it's not available for use from Python. The hiding of that method probably got lost in the transition from Classic to Phoenix.  I'll take care of that for the next release.

**Comment by AndreaLu** [comment]
Thank you very much.

**Comment by AndreaLu** [comment]
Thank you very much.
Which practice would you recommend to keep track of data in dynamically created controls?
I'm currently using a dictionary to associate the control ID accessible from the event object to a reference to my data, but it doesen't look very eleganto to me.

**Comment by RobinD42** [comment]
There are lots of ways to associate a value with a widget that is usable from within an event handler.  The best choice is really whatever makes the most sense to you that works. Some ideas:

* As you've mentioned already, associate the control's ID to the data object. This is not a bad idea, although maybe not very "pythonic"

* You could create new classes that derive from the stock widget classes and add on the knowledge about accessing the app data objects.

* You could use `functools.partial` or even just a simple lambda to add an extra parameter to your event handlers. For example, something like this:

  ```
  self.Bind(wx.EVT_WHATEVER, lambda event: self.OnWhatever(event, someDataObj))
  ...
  def OnWhatever(self, event, dataObj):
      dataObj.doSomething()
  ```

  ```
