### ISSUE TITLE
VersionInfo description incorrect

### ISSUE THREAD

**Issue by cbeytas** [wxWidgets/Phoenix#1489]
wxPython Phoenix
If you Ctrl-Alt-MiddleClick on a window in any wxPython program it will show you `VersionInfo()` obtained from the `wx.GetLibraryVersionInfo()` function. It always reports `Version 3.0.5 (Unicode:wchar_t, debug level: 1)` no matter what platform or version of Phoenix.

![wxversion_gtk](https://user-images.githubusercontent.com/4748055/72703997-58ed5900-3b25-11ea-8168-2c391b188402.png)
![wxversion_msw](https://user-images.githubusercontent.com/4748055/72704001-5ab71c80-3b25-11ea-99c1-d08147c0036f.png)

**Comment by infinity77** [comment]
That’s correct, as the information it refers to is related to wxWidgets, not wxPython Phoenix. That specific keyboard-mouse interaction is defined here:

https://github.com/wxWidgets/wxWidgets/blob/master/src/common/wincmn.cpp#L3189

Also, if I understand correctly, you cannot remove it unless you modify wxWidgets sources, or maybe by handling the corresponding event, unless it is handled in wx.App.FilterEvent, in which case you need to do something about it there (I never tried but it should be possible).

And I am not sure it is a bug. The Phoenix version has been bumped up on purpose to distinguish it from Classic.

**Comment by Metallicow** [comment]
Looks good to me, as it says wxWidgets, not wxPython
Phoenix bumped the version number by 1 when 4.0 came out because of the big change.
...So basically the wxWidgets version should be one less than the wxPython "phoenix" version you are using
```python
import sys
import wx
wxVER = 'wxPython %s' % wx.version()
pyVER = 'python %d.%d.%d.%s' % sys.version_info[0:4]
versionInfos = '%s %s' % (wxVER, pyVER)
print(versionInfos )
```
