### ISSUE TITLE
ListCtrl scrollbar dark corner and sometimes issues with tearing

### ISSUE THREAD

**Issue by swprojects** [wxWidgets/Phoenix#149]
I am not sure if this is normal behavior but it looks a little strange to me or a mistake with my code?

os: Windows 10 64bit, 
version: '3.0.3.dev2445+ca34d71 msw (phoenix)'
ide: spyder ( Anaconda 64bit)

code (just a listctrl in a  standard frame):
```python
import wx

class Frame(wx.Frame):

    def __init__(self, title):
        wx.Frame.__init__(self, None, title=title)
        
        panel = wx.Panel(self)
        sizer = wx.BoxSizer(wx.HORIZONTAL)
        
        lc = wx.ListCtrl(panel, style=wx.LC_REPORT)
        lc.InsertColumn(0, "column 1")
        lc.InsertColumn(1, "column 2")
        for x in range(0, 100):
            lc.Append([str(x), str(x)])
        sizer.Add(lc, 1, wx.ALL|wx.EXPAND, 5)
        
        panel.SetSizer(sizer)
        
app = wx.App()
frame = Frame(title="list issue")
frame.Show()
app.MainLoop()
```

The issues: 
- when I drag the vertical scroll bar and release the mouse button, it leaves a dark rectangle on the scroll bar. 

![list](https://cloud.githubusercontent.com/assets/10121727/17808971/2c0978a8-660b-11e6-8a46-b4a1c050d71e.png)

- I have also had issues with "tearing" where  the listctrl partially disappears. This happens randomly when dragging the scrollbar. I have to rerun the code a number of times in order to reproduce this particular problem  

![tearing](https://cloud.githubusercontent.com/assets/10121727/17809206/dd3479ba-660c-11e6-9510-05f1b026abf0.png)

**Comment by swprojects** [comment]
just tried the code example on python 2.7.6 32bit wx 2.8.12.1.

And has none of the issues listed above

**Comment by swt2c** [comment]
Can you try a 3.0 version of Classic?

**Comment by swprojects** [comment]
just tried on Python 2.7.12 , '3.0.2.0 msw (classic)'.

now the same issue arises

**Comment by swt2c** [comment]
That's kind of what I figured.  It seems likely that this is a wxWidgets issue, not anything in wxPython itself.

**Comment by swprojects** [comment]
closing this.. I think this issue (or a related one to double buffering) has already been raised on wxWidgets and patched. I will submit one otherwise.
