### ISSUE TITLE
GLCanvas shows image in lower left corner only with 200% scaling on Ubuntu 18.04

### ISSUE THREAD

**Issue by petrasovaa** [wxWidgets/Phoenix#1497]
**Operating system**: Ubuntu 18.04
**wxPython version & source**:         4.0.7.post2 from pypi
**Python version & source**:           3.6.9

**Description of the problem**:
In GLCanvas demo, the image is shown only in the lower left quarter of the window. This happens on my external 4k monitor with 200% scaling. With 300% scaling it looks like 1/9 of the window.

**Comment by swt2c** [comment]
You need to take the scale factor into account when setting the viewport as OpenGL operates in physical pixels.  See the linked PR which fixes the issue for the demo.

**Comment by petrasovaa** [comment]
Thanks, that helps!
