### ISSUE TITLE
TreeCtrl sends tree events after the tree is destroyed

### ISSUE THREAD

**Issue by dmclean652** [wxWidgets/Phoenix#1500]
**Operating system**:       Windows 7
**wxPython version & source**:          4.0.7.post2
**Python version & source**:            stock, 3.7.5

**Description of the problem**:

A TreeCtrl with the style wx.TR_HIDE_ROOT will create wx.EVT_TREE_SEL_CHANGED events after the parent windows is closed. If the TreeCtrol does not have that style then the extra event is not created.

For this problem to happen, the hidden root requires at least 2 child nodes.

Running the demo code:
1. Run the code, press the "open dialog" button in the frame
2. Click the close button in the dialog.

You will see a print statement for when the Destroy() call is performed on the dialog, and then you will see  a print statement for the wx.EVT_TREE_SEL_CHANGED event. If you change HIDE_ROOT to False then the extra event does not happen after the Destroy() call.

In my application this is a more serious error. When my code tries to inspect the event I get a C++ error indicating that the tree has already been destroyed.

Am I doing something wrong? Or is there a work around for this?

Thanks!

```python
import wx

HIDE_ROOT = True

class TreeFrameSample(wx.Frame):
    def __init__(self, parent, title):
        wx.Frame.__init__(self, parent, title=title)
        btn = wx.Button(self, label="Open dialog")
        btn.Bind(wx.EVT_BUTTON, self.openDlg)
        self.Show(True)

    def openDlg(self, evt):
        dlg = TestDlg(self)
        dlg.ShowModal()

class TestDlg(wx.Dialog):
    def __init__(self, parent):
        wx.Dialog.__init__(self, parent, title='Test dialog')

        self.tree = TestTree(self, HIDE_ROOT)
        btnCancel = wx.Button(self, id=wx.CANCEL, label="Cancel")

        sizer = wx.BoxSizer(wx.VERTICAL)
        sizer.Add(self.tree, 7, flag=wx.EXPAND | wx.ALL, border=5)
        sizer.Add(btnCancel, 1, flag=wx.EXPAND | wx.ALL, border=5)
        self.SetSizer(sizer)

        btnCancel.Bind(wx.EVT_BUTTON, self.__onCancel)
        self.tree.Bind(wx.EVT_TREE_SEL_CHANGED, self.__onSelectFile)

    def __onCancel(self, evt):
        print ("Canceling")
        self.Close()
        self.Destroy()

    def __onSelectFile(self, evt):
        print("Dialog: " + str(evt) + " - " + str(self))

class TestTree(wx.TreeCtrl):
    def __init__(self, parent, bHideRoot=True):
        style = wx.TR_MULTIPLE | wx.TR_DEFAULT_STYLE | wx.TR_EDIT_LABELS
        if bHideRoot:
            style |= wx.TR_HIDE_ROOT

        wx.TreeCtrl.__init__(self, parent, style=style)
        root = self.AddRoot("Hidden")
        self.AppendItem(root, "Root 1")
        self.AppendItem(root, "Root 2")

app = wx.App(False) 
frame = TreeFrameSample(None, "Tree test")
app.MainLoop()
```

**Comment by RobinD42** [comment]
First of all, modal dialogs should use `EndModal` to close themselves, and the `Destroy` should be done after the `ShowModal` returns. (Or you can use the dialog as a context manager and the `Destroy` will happen automatically upon exit from the context manager.

Secondly, if you use `wx.ID_CANCEL` as the id of the button then the default functionality for cancelling the dialog will automatically be invoked in the default event handler. (Validators, if any, are checked and `EndModal` is called.)

Finally, events being sent during or after a widget is destroyed is possible for some types of widgets. In the case of the tree ctrl it may change the selection as items are being removed from the tree, and so selection events can be sent. One workaround is to simply check for `not self.IsBeingDeleted()` before doing anything in the event handler.

**Comment by RobinD42** [comment]
Actually, Validators are not checked for the default `wx.ID_CANCEL` event handler, but they are for the `wx.ID_OK` handler.

**Comment by dmclean652** [comment]
Hi Robin,

Thank you very much for the reply. I've cleaned up the example as per your suggestions. Now the example below shows exactly the problem my application does: when the dialog is closed an extra event is sent to the tree control and when calling IsBeingDeleted() I get:

RuntimeError: wrapped C/C++ object of type TestDlg has been deleted

If you change "HIDE_ROOT = False" then the C++ error does not occur.

```python
import wx

HIDE_ROOT = True

class TreeFrameSample(wx.Frame):
    def __init__(self, parent, title):
        wx.Frame.__init__(self, parent, title=title)
        sizer = wx.BoxSizer(wx.VERTICAL)
        btn = wx.Button(self, label="Open dialog")
        btn.Bind(wx.EVT_BUTTON, self.openDlg)
        sizer.Add(btn, flag=wx.EXPAND | wx.ALL)
        self.SetSizer(sizer)
        self.Show(True)

    def openDlg(self, evt):
        dlg = TestDlg(self)
        dlg.ShowModal()
        dlg.Destroy()

class TestDlg(wx.Dialog):
    def __init__(self, parent):
        wx.Dialog.__init__(self, parent, title='Test dialog')
        self.tree = TestTree(self, HIDE_ROOT)
        sizer = wx.BoxSizer(wx.VERTICAL)
        sizer.Add(self.tree, 7, flag=wx.EXPAND | wx.ALL, border=5)
        sizer.Add(wx.Button(self, id=wx.ID_CANCEL), 1, flag=wx.EXPAND | wx.ALL, border=5)
        self.SetSizer(sizer)

        self.tree.Bind(wx.EVT_TREE_SEL_CHANGED, self.__onSelectFile)

    def __onSelectFile(self, evt):
        print("Dialog: is being destroyed: " + str(self.IsBeingDeleted()))

class TestTree(wx.TreeCtrl):
    def __init__(self, parent, bHideRoot=True):
        style = wx.TR_MULTIPLE | wx.TR_DEFAULT_STYLE | wx.TR_EDIT_LABELS
        if bHideRoot:
            style |= wx.TR_HIDE_ROOT

        wx.TreeCtrl.__init__(self, parent, style=style)
        root = self.AddRoot("Hidden")
        self.AppendItem(root, "Root 1")
        self.AppendItem(root, "Root 2")

app = wx.App(False)  # Create a new app, don't redirect stdout/stderr to a window.
frame = TreeFrameSample(None, "Tree test")
app.MainLoop()
```

**Comment by RobinD42** [comment]
Ok, it looks like the event is still happening after `IsBeingDeleted` is usable. You can do a boolean check of widget objects to see if the C++ part of the widget still exists. Try it like this:

```python
    def __onSelectFile(self, evt):
        if not self.tree:
            print('skipping')
            return
        print('selection event: {}'.format(self.tree))
        # do something with self.tree here
```

**Comment by dmclean652** [comment]
Thank you Robin! That works around around the problem.
