### ISSUE TITLE
AGW AUI Hard Crash when closing a Floating pane with `Use Fly-Out Floating Panes` option

### ISSUE THREAD

**Issue by Metallicow** [wxWidgets/Phoenix#1501]
**Operating system**:
**wxPython version & source**:  wxPython 4.0.7 and wxPython 4.1.0a1.dev4559+9b9b1c8f msw (phoenix) wxWidgets 3.1.4
**Python version & source**:  Python 2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 20:49:36) [MSC v.1500 32 bit (Intel)] on win32

**Description of the problem**:
Open the agw AUI wxPy demo and select the option `Use Fly-Out Floating Panes` from the Options Menu. Click the OK box that it shows to close it. Now rip a pane out of the main interface so it it floating. You will notice the fly-out/roll-up behaviour is still working. Click on the `X` to close the floating pane. At this step it hard crashes.

**Comment by RobinD42** [comment]
@infinity77 can you take a look at this one? 

The crash report on Mac indicates it is happening when sending a timer event, so there is probably a timer that needs to be stopped before the window it belongs to is destroyed.

**Comment by infinity77** [comment]
@RobinD42 , I’d love to help fixing this (and #1491), but are the moment I’m on a 3-months parental leave holiday and I’m actually stuck in Key West, Florida, for at least a month. Not sure if and when I will be able to get home... but if I do, I’ll definitely take a look - unless somebody else beats me to it...
