### ISSUE TITLE
Check if the file exists when not using the browse button with wx.FilePickerCtrl

### ISSUE THREAD

**Issue by Legorooj** [wxWidgets/Phoenix#1503]
I've come accross a "bug" in my code - when passing `wx.FLP_MUST_EXIST` to my `wx.FilePickerCtrl`, I've found that it checks whether or not the file exists when you use the `browse` button, but not when you just type in the filename to the TextCtrl.

I've got around that by checking afterwards with `os.path.isfile(self.file.GetPath())`, but maybe include it in the wxPython code by default when the MUST_EXIST flag is passed?

**Comment by ricpol** [comment]
This is well known and documented https://wxpython.org/Phoenix/docs/html/wx.FilePickerCtrl.html#styles-window-styles and it comes from wxWidgets, not wxPython. See the comments here https://github.com/wxWidgets/wxWidgets/blob/master/src/common/filepickercmn.cpp#L111 for a more detailed explanation. See also this rather cryptic note for "SetPaht" https://wxpython.org/Phoenix/docs/html/wx.FilePickerCtrl.html#wx.FilePickerCtrl.SetPath

IMO, if you want the FLP_MUST_EXIST behaviour, you are better off without the text control. Which means, the default FLP_DEFAULT_STYLE combining FLP_MUST_EXIST with FLP_USE_TEXTCTRL (at least on windows/mac) is... not the smartest thing to do, I'm afraid.

That said, it would be easy to implement a wxPython version of the widget that behaves like you want...

**Comment by Metallicow** [comment]
This edge case should probably only apply if pressing enter in the textctrl. Otherwise, you should make a pure python version of the widget, because the behavior will be whatever the default OS widget will do.
If activating the event by pressing enter doesn't work like the OS widget does, then you should add your complaint in a ticket at wxWidgets.
...to check the string on every text event isn't always the normal behavior of that widget on all operating systems.

**Comment by ricpol** [comment]
@Metallicow 
It's a design issue, I guess... if the file must exist, and you type in "bogus<enter>", then what status the browser part of the widget should be in? 
Here is the relevant commit dealing with the problem https://github.com/wxWidgets/wxWidgets/commit/3ccea0978ce5a3f4f68c3abdb3f4aa0e60f49fc4 The commit message is pretty explanatory... This choice was made 8 years ago and at this point I don't think that a new ticket would change things... Besides, here is a related ticket, opened 4 years ago: https://trac.wxwidgets.org/ticket/17252 : I think the comment here speaks volumes... 

However, if the OP comes up with a behaviour design that suites his needs, then the good news is that there should be no need to write a pure-python version of the widget from scratch - I think that just pushing a custom handler that checks the path before the event propagates should do the trick.

**Comment by Legorooj** [comment]
Thanks for pointing out that it came from wxWidgets. I've simply got a validator on the ok button on my dialogs and wizards that shows a message box etc.
