### ISSUE TITLE
password input get removed after invoking Disable()

### ISSUE THREAD

**Issue by lpxia** [wxWidgets/Phoenix#1505]
**Operating system**: MacOS Mojave, Version 10.14.6 (18G87) 
**wxPython version & source**:       wxPython               4.0.7.post2    
**Python version & source**:      Python 3.7.4      

**Description of the problem**:
The password input get removed after invoking Disable() via clicking button.
In following example, run the application on MAC, enter password, click button, the password input will become empty.

```python
# Put code sample here
# -*- coding: utf-8 -*-

import wx
import wx.xrc


class MyFrame1 ( wx.Frame ):

	def __init__( self, parent ):
		wx.Frame.__init__ ( self, parent, id = wx.ID_ANY, title = wx.EmptyString, pos = wx.DefaultPosition, size = wx.Size( 511,357 ), style = wx.DEFAULT_FRAME_STYLE|wx.TAB_TRAVERSAL )

		self.SetSizeHints( wx.DefaultSize, wx.DefaultSize )

		bSizer1 = wx.BoxSizer( wx.VERTICAL )

		fgSizer1 = wx.FlexGridSizer( 0, 2, 0, 0 )
		fgSizer1.SetFlexibleDirection( wx.BOTH )
		fgSizer1.SetNonFlexibleGrowMode( wx.FLEX_GROWMODE_SPECIFIED )

		self.m_staticText1 = wx.StaticText( self, wx.ID_ANY, u"MyLabel", wx.DefaultPosition, wx.DefaultSize, 0 )
		self.m_staticText1.Wrap( -1 )

		fgSizer1.Add( self.m_staticText1, 0, wx.ALL, 5 )

		self.m_textCtrl1 = wx.TextCtrl( self, wx.ID_ANY, wx.EmptyString, wx.DefaultPosition, wx.DefaultSize, wx.TE_PASSWORD )
		fgSizer1.Add( self.m_textCtrl1, 0, wx.ALL, 5 )

		self.m_button1 = wx.Button( self, wx.ID_ANY, u"MyButton", wx.DefaultPosition, wx.DefaultSize, 0 )
		fgSizer1.Add( self.m_button1, 0, wx.ALL, 5 )


		bSizer1.Add( fgSizer1, 1, wx.EXPAND, 5 )


		self.SetSizer( bSizer1 )
		self.Layout()

		self.Centre( wx.BOTH )

		# Connect Events
		self.m_button1.Bind( wx.EVT_BUTTON, self.disableInput )


	def __del__( self ):
		pass


	# Virtual event handlers, overide them in your derived class
	def disableInput( self, event ):
		event.Skip()


class MyTest(MyFrame1):

    def disableInput(self, event):
        self.m_textCtrl1.Disable()
        self.m_textCtrl1.Enable()

if __name__ == '__main__':
    app = wx.App()
    main_win = MyTest(None)
    main_win.Show()
    app.MainLoop()


```

**Comment by lpxia** [comment]
actually, not only password input, any input will become empty... after removing wx.TE_PASSWORD, it's the same thing.

**Comment by RobinD42** [comment]
I expect that this is the normal behavior of the native widget as I don't see anything in the wx code that would explicitly clear the value when disabling. You could try creating a ticket for this at trac.wxwidgets.org and see what they think about changing this. In the meantime you can work around this by getting the control's value before the disable, and resetting the value after.

**Comment by Metallicow** [comment]
It probably is the operating system behavior. On win7 disabling the control still shows the ****** hidden password text.

**Comment by lpxia** [comment]
Yes. Windows is fine.
For MAC, we need read the value for all inputs before invoking Disable().
