### ISSUE TITLE
AttributeError when using wx.lib.intctrl.IntCtrl

### ISSUE THREAD

**Issue by haimat** [wxWidgets/Phoenix#1508]
**Operating system**: Ubuntu Linux 18.04 LTS
**wxPython version & source**: 4.0.7.post2 (built via `pip`)
**Python version & source**: 3.6.9 64-bit (distro)

**Description of the problem**:
When I initialize a `wx.lib.intctrl.IntCtrl` widget I get the following error:

    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/wx/lib/intctrl.py", line 509, in OnText
        if value != self.__oldvalue:
    AttributeError: 'IntCtrl' object has no attribute '_IntCtrl__oldvalue'

Looking at the sources this makes sense, because of this line in the method `OnText()`:

    if value != self.__oldvalue:

Here the attribute `__oldvalue` is being referfence, but it has not been set or initialized before.  
As a workaround, I am using a child class to fix this issue locally:

    class MyIntCtrl(wx.lib.intctrl.IntCtrl):
        def __init__(self, *args, **kw):
            self._IntCtrl__oldvalue = None
            super().__init__(*args, **kw)

**Comment by ricpol** [comment]
Apparently it is a regression from this commit 
https://github.com/wxWidgets/Phoenix/commit/78cd863d2b5783e6d8cd25490e9e51cbf271d4f1#diff-503b41e3ef7ca3ee96a397d59eb8a1e1
