### ISSUE TITLE
setBitMap doesn't work Raspberry Pi 4

### ISSUE THREAD

**Issue by OngakuShima** [wxWidgets/Phoenix#1518]
**Operating system**:Raspian for Raspberry Pi 4
**wxPython version & source**:   wxPython 4.0.4       
**Python version & source**:   python 3.7.3         

**Description of the problem**:The included program should produce a drop down menu with a graphic 'ppp' and the word Quit  and Ctrl+Q from clicking on File.
The graphic comes from the file ppp.png.   It works correctly on a Mint 17 system, but not on Raspberry Pi
I don't know how to include the png file here but probably any png file will show the problem.

```python
#!/usr/bin/python

# menu1.py

import wx

class MyMenu(wx.Frame):
    def __init__(self, parent, id, title):
        wx.Frame.__init__(self, parent, id, title, wx.Point(-250,-250), wx.Size(200, 150))

        menubar = wx.MenuBar()
        file = wx.Menu()
        quit = wx.MenuItem(file, 105, '&Quit\tCtrl+Q', 'Quit the Application')
        quit.SetBitmap(wx.Image('ppp.png', wx.BITMAP_TYPE_PNG).ConvertToBitmap())

        file.AppendItem(quit)

        menubar.Append(file, '&File')
        self.SetMenuBar(menubar)

class MyApp(wx.App):
    def OnInit(self):
        frame = MyMenu(None, -1, 'menu1.py')
        frame.Show(True)
        return True

app = MyApp(0)
app.MainLoop()
```

**Comment by RobinD42** [comment]
Do other GTK applications on the Pi show icons in their menus? If not, then it is likely that there is a system option that is disabling them.

**Comment by OngakuShima** [comment]
Yes, icons generally show up on the Pi.  This problem came up with the application 'easy ABC', which uses wxPython.  Indeed, the menubar that the dropdown comes from displays icons.

**Comment by Metallicow** [comment]
@OngakuShima Try setting the bitmap *after* you append the item to the menu. Does that fix the problem?

Also you can attach the image by drag and dropping it into the reply box; github will automatically put it in the post.

Yes, on some linux systems you have to set a system option to see menu item bitmaps. Tho this is usually a global option, so as Robin states if you can see other menu item icons then this is probably something specific in the code.

**Comment by OngakuShima** [comment]
Setting the bitmap after the AppendItem also fails.
Attempting to attach image:
![ppp](https://user-images.githubusercontent.com/3950651/74919676-d6c1b000-53c2-11ea-9048-be38972139e3.png)
