### ISSUE TITLE
FloatSpin produces annoying Gtk-CRITICAL warnings

### ISSUE THREAD

**Issue by petrasovaa** [wxWidgets/Phoenix#1529]
**Operating system**: Ubuntu 18.04
**wxPython version & source**:          4.0.7.post2 gtk3 (phoenix) wxWidgets 3.0.5
**Python version & source**:            3.6.9

**Description of the problem**:

In FloatSpin demo, when you hover over the +- buttons, terminal is flooded with 

    (demo.py:18615): Gtk-CRITICAL **: 10:21:27.231: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkSpinButton

**Comment by RobinD42** [comment]
See comment at https://github.com/wxWidgets/Phoenix/issues/1297#issuecomment-509337692

**Comment by petrasovaa** [comment]
Just a note to this, the + button is actually not rendered correctly, part of it is missing, which I thought was connected to the warning. I don't know if that's something wx can fix though.

**Comment by RobinD42** [comment]
That may be related to a best size calculation issue with gtk3. I think there was a recent change in wxWidgets to address this.

**Comment by eoyilmaz** [comment]
> Just a note to this, the + button is actually not rendered correctly, part of it is missing, which I thought was connected to the warning. I don't know if that's something wx can fix though.

Just for reference, because Google took me here, it may also help others. I had the same error, and I fixed it by increasing the ``wxSpinCtrl`` size to 142 or more in my case. As you guessed, It was actually related to the fact that the ``wxSpinCtrl`` size was small and the  ``+`` button was not fitting there.
