### ISSUE TITLE
I got different result when i visit same website through IE11 and wx.html2.webview. 

### ISSUE THREAD

**Issue by yickowang** [wxWidgets/Phoenix#1543]
**Operating system**:					Windows10 Pro
**wxPython version & source**:			wxPython 4.07p2
**Python version & source**: 			Python 3.8.1 

**Description of the problem**:			I get different result when i visit same website through IE11 and wx.html2.webview. 

The Python Code is very simple.
I want to visit the website through wx.html2.webview control, but the website have not set the correct SSL certificate.Normally, the IE11 will display a warning page and i still can visit the web through the link "Go to the webpage(not recommended) in the page, see the picture below.
![1](https://user-images.githubusercontent.com/40831103/76231531-58895880-6260-11ea-8058-6a3aca8a2d91.png)

But when i visit the website through wx.html2.webview,i found that the warning page still display but the link is not disappear, only display “Error code:0", see the picture below.

![2](https://user-images.githubusercontent.com/40831103/76231560-60e19380-6260-11ea-99e6-66a2c6105336.png)

Before run the app, i have added the regedit value.
Computer\HKEY_CURRENT_USER\Software\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_BROWSER_EMULATION
python.exe   DWORD  11000(0x00002af8)
![3](https://user-images.githubusercontent.com/40831103/76231567-64751a80-6260-11ea-9ee7-a5cf0bec40e9.png)

anyone can give me some suggestion?thanks.

**Comment by vin1antme** [comment]
To make "Go on to the webpage" link available add the following setting to registry: 
`HKEY_CURRENT_USER\Software\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_SSLUX\python.exe = (DWORD) 00000001` (according to the article [https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/general-info/ee330735(v=vs.85)#ssl-security-alert-display](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/general-info/ee330735(v=vs.85)#ssl-security-alert-display))

**Comment by RobinD42** [comment]
The same thing can be done by calling `wx.html2.WeView.MSWSetEmulationLevebl(webview.WEBVIEWIE_EMU_IE11)`

**Comment by mimieiei** [comment]
Do you solve it? 
I met the same problem and make sure I have python.exe in HKEY_CURRENT_USER\SOFTWARE\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_BROWSER_EMULATION.(I can't find FEATURE_SSLUX). And try to call wx.html2.WeView.MSWSetEmulationLevebl(wx.html2.WEBVIEWIE_EMU_IE11) also, but still get the not secure page and can't find the go to webpage.

**Comment by vin1antme** [comment]
Yes. FEATURE_SSLUX should be added manually.

**Comment by mimieiei** [comment]
I added FEATURE_SSLUX and added python.exe(DWORD) 00000001 in it. =)

But now the error code becomes DLG_FLAGS_SEC_CERT_CN_INVALID, and when I click "go to webpage" it still just throw a blank page. 

Could you give me some suggestions for that? 
Thanks in advance.

**Comment by vin1antme** [comment]
The certificate of the site you are visiting is broken, so try to navigate another sites; or clear browser's cache and try manually install site's certificate into browser.
