### ISSUE TITLE
Missing close for io.open, add close or use a with block in frame.py.

### ISSUE THREAD

**Issue by pbrod** [wxWidgets/Phoenix#1555]
Replace code starting at:
https://github.com/wxWidgets/Phoenix/blob/ef1edacc205708cec7a0be4feb35cd524d8723bb/wx/py/frame.py#L926

with

```python
    with io.open(self.startupScript, 'r', newline=None, encoding='utf-8') as fid:
        text = fid.read()
```

**Comment by pbrod** [comment]
Same issue occurs here as well:

https://github.com/wxWidgets/Phoenix/blob/ef1edacc205708cec7a0be4feb35cd524d8723bb/bin/mymd5.py#L9

**Comment by Metallicow** [comment]
...as long as it is Py2/3 phoenix compatible, it looks good to me. @RobinD42 will be last person to verify/push anything thru.
