### ISSUE TITLE
No need to call keys, directly check with the in operator.

### ISSUE THREAD

**Issue by pbrod** [wxWidgets/Phoenix#1556]
For example this line
https://github.com/wxWidgets/Phoenix/blob/ef1edacc205708cec7a0be4feb35cd524d8723bb/demo/DrawXXXList.py#L109

could be written as

```python
    if (c, t) not in cache: 
```

This issue occures several places throughout the code.
A quick search for ".keys()" on the code base gives the following list of possible places to change the code:

demo.Throbber (4 matches)
etgtools.sphinx_generator
samples.doodle.doodle
samples.doodle.superdoodle
samples.floatcanvas.BB_HitTest
samples.floatcanvas.GroupDeleteDemo
samples.floatcanvas.GroupDemo
samples.floatcanvas.MiniDemo
samples.roses.wxroses (2 matches)
sphinxtools.postprocess (7 matches)
sphinxtools.utilities
unittests.test_windowid
unittests.wtc (2 matches)
wx.lib.agw.artmanager
wx.lib.agw.fmcustomizedlg (2 matches)
wx.lib.agw.shortcuteditor (2 matches)
wx.lib.agw.supertooltip
wx.lib.calendar (2 matches)
wx.lib.evtmgr
wx.lib.fancytext (2 matches)
wx.lib.filebrowsebutton
wx.lib.inspection
wx.lib.masked.maskededit (20 matches)
wx.lib.masked.numctrl (4 matches)
wx.lib.masked.timectrl
wx.lib.nvdlg (2 matches)
wx.lib.plot.polyobjects (2 matches)
wx.lib.pubsub.core.topicargspec (3 matches)
wx.lib.pubsub.core.topicdefnprovider
wx.lib.pubsub.py2and3 (2 matches)
wx.lib.pubsub.utils.misc
wx.lib.pubsub.utils.topictreeprinter
wx.py.buffer (2 matches)
wx.py.dispatcher (3 matches)
wx.py.filling
wx.py.introspect (3 matches)
wx.py.magic
wx.py.PyCrust (2 matches)
wx.py.PyShell (2 matches)
wx.py.PySlices (2 matches)
wx.py.PySlicesShell (2 matches)
wx.py.PyWrap
wx.tools.dbg

**Comment by Metallicow** [comment]
Please make a submit post and then a Pull Req. 
Even tho they may be cosmetic items, and or improve performance, they take time to review and the ones with multiple files take longer time overall. It may take a bit of time to get too...

**Comment by Metallicow** [comment]
Submissions need to be Py2/3 Phoenix compatible.

**Comment by pbrod** [comment]
Yes, of course.
