### ISSUE TITLE
Use of tempfile.mktemp is deprecated and poses a security risk.

### ISSUE THREAD

**Issue by pbrod** [wxWidgets/Phoenix#1557]
The  code starting at

https://github.com/wxWidgets/Phoenix/blob/ef1edacc205708cec7a0be4feb35cd524d8723bb/wx/lib/infoframe.py#L306

could be replaced with something like this:
```python
    f = tempfile.NamedTemporaryFile(mode='w', delete=False)
    filename = os.path.abspath(f.name)
```

**Comment by Metallicow** [comment]
this is something to be looked over.
