### ISSUE TITLE
wxAnimationDecoder is not available

### ISSUE THREAD

**Issue by kdschlosser** [wxWidgets/Phoenix#1567]
**Operating system**: Windows 7 x64 SP1
**wxPython version & source**:    4.0.7.post1 msw (phoenix) wxWidgets 3.0.5 (pypi)
**Python version & source**: 3.7.5 Stackless 3.7 (tags/v3.7.5-slp:f7925f2a02, Oct 20 2019, 15:28:53) [MSC v.1916 64 bit (AMD64)]

**Description of the problem**:

I would like to be able to extend the animation portion of wxPython/wxWidgets to support APNG's I have found that wxAnimation has the method AddHandler but this method has not been added to wx.adv.Animation. In order for me to use that method I would need to subclass wxAnimationDecoder to pass to the method.

It appears to be fairly straight forward to be able to create a custom decoder and it would be nice if this was available to do instead of being limited to GIF and ANI. 

I am not sure if there might also be an issue because of wxAnimationType being used to identify the decoder being used.

If the ability to extend the animation portions of wx existed it would make it really easy to write GUI code that would handle security cameras and things of that nature. because the rendering of the images to the screen is handled in c code it would perform a lot better then wring a custom control to handle the animation in python. we just need a way to be able to add additional decoders.

```python
from wx.adv import AnimationDecoder
```

**Comment by RobinD42** [comment]
I'm checking to see if there was a reason why `wxAnimationDecoder` was not made public (IOW, documented in the public interface), but in the meantime you can probably cover most of your use case simply be deriving a new class from `wx.adv.Animation` and overriding the appropriate methods.

**Comment by kdschlosser** [comment]
I have actually found that there are problems that run deeper... not all of the methods of wxAnimationCtrl have a python binding to them. because of this they cannot be overridden easily.

This is the list of the methods that need to be exposed in addition to the ones that are already exposed in order to write a custom a custom animation decoder.

* wxAnimationCtrl

  * OnTimer
  * OnPaint
  * OnSize
  * SetUseWindowBackgroundColour
  * IsUsingWindowBackgroundColour
  * DrawCurrentFrame
  * GetBackingStore
  * FitToAnimation
  * DisposeToBackground
  * IncrementalUpdateBackingStore
  * UpdateStaticImage
  * RebuildBackingStoreUpToFrame
  * DrawFrame
  * DisplayStaticImage

* wxAnimation.GetFramePosition

  * GetFrameSize
  * GetDisposalMethod
  * GetTransparentColour
  * GetBackgroundColour

* wxAnimationDecoder

  * Load
  * CanRead
  * GetType
  * ConvertToImage
  * GetFrameSize
  * GetFramePosition
  * GetDisposalMethod
  * GetDelay
  * GetTransparentColour
  * GetAnimationSize
  * GetBackgroundColour
  * GetFrameCount
  * DoCanRead

Here is a link to a repository that I made that will show how wx.AnimationCtrl renders the frame if a custom animation decoder is made.

This is a port of the code in wxWidgets, it is as close as I could come to making it identical.

https://github.com/kdschlosser/wxAnimation

```python
import wx
import wxAnimation

# provide the location and filename of an APNG file.
path = r'C:\PATH_TO\SOME_APNG.apng'

class Frame(wx.Frame):

    def __init__(self):

        wx.Frame.__init__(self, None, -1)

        anim = wxAnimation.Animation(path, wxAnimation.ANIMATION_TYPE_PNG)
        ctrl = wxAnimation.AnimationCtrl(self, -1, anim)
        sizer = wx.BoxSizer()
        sizer.Add(ctrl)
        self.SetSizer(sizer)
        self.Show()
        ctrl.Play()



app = wx.App()
frame = Frame()
app.MainLoop()
```
You will need to provide a path to an apng file for it to run. There is an apng file that you can use from https://en.wikipedia.org/wiki/APNG (bouncing ball) that will show the problem.

Because each animation type supports different rendering techniques without the ability to override some of the methods listed the frame is not able to be rendered properly. In the case of APNG files there are blend operations that need to be considered before rendering the frame. 

Ideally the rendering of a frame needs to be moved from wxAnimartionCtrl to wxAnimationDecoder so the decoder then becomes responsible for rendering the frame properly. anything related to the "backing store" should also be moved to the decoder as well. These are decoder specific functions/features and whether they exist or not depend on the decoder. 

That repository I created as a replacement for wx.adv.AnimationCtrl. The choice would be yours to make if you wanted to bother with creating the bindings to the missing methods/classes and still end up with the same issues when rendering causing the user to have to write complex code in order to work around the problem. Or if you wanted to use something like what I have written where correcting the issues will not require a new release of wxWidgets to be made.

I originally didn't think that I would be able to port the code like I did and also still be able to use the stock wxAnimationCtrl for handling GIF and ANI.

**Comment by RobinD42** [comment]
Well, what you identify as missing methods for `wxAnimation` (at least) are only present in the generic version of `wxAnimation`. The native class used on wxGTK does not have those methods and if they were exposed in the interface then wxPython would have build errors there. It is probably also why I have this TODO in the etg script: https://github.com/wxWidgets/Phoenix/blob/master/etg/animate.py#L48 😃 

I'll give this some more thought and see what looks like a good approach to take.

**Comment by kdschlosser** [comment]
Thanks Robin. I appreciate the time and effort.

one last question tho. what is the purpose to wxAnimation? It really serves no real purpose that I have found other then managing the handlers. adding handlers can be done using a static method that can be attached to wx.AnimationDecoder and so can the loading of the correct decoder. I do not see any purpose other then that. Unless it has some special use case for another platform that I did not come across. You mentioned the use of wxAnimation being different under Darwin., I will have to go and check it out.

I have also discovered that the backing store does not work 100% correct. when using it to decode anything other then AVI's and GIF's. It causes a skip and also a rendering redraw issue. I believe this may have to do with how each format specification handles the dispose operations. In APNG the dispose operation that is supposed to be used before a frame gets drawn is in the frame before it. I believe the dispose operations are also going to be decoder dependent and would probably reside better in the decoder instead of in wxAnimationCtrl.

**Comment by RobinD42** [comment]
> one last question tho. what is the purpose to wxAnimation?  

My guess is that it is intended as a bridge or facade for dealing with the  differences between the generic and native versions of the classes. If just the generic version was implemented then the ctrl could indeed use the decoders directly, but IIUC the native ctrl for gtk does not use the decoders at all. So the extra layer is implemented to be able to hide the implementation details in both cases.

**Comment by kdschlosser** [comment]
I figured it was something like that.... For the sake of discussion. Could the decoder class could be subclassed and be made to work to handle GTK? From the brief look I had it seems like wxAnimation and wxAnimationDecoder could be merged into a single class and the methods for GTK would simply move with it. How GTK handles the file formats may not be considered a "traditional" decoder of sorts. But the end result is the image format gets decoded.

I am working on adding FLIF support to the repository I linked earlier. I have to run tests on it and also compile more extension modules in order to support Linux, OSX and Windows. have to set up the CI and write the build script.

**Comment by Metallicow** [comment]
Looks like a good start for a pure-python impl. In the end, If you get far enough, this will probably want to be fine tuned to accept any type of images that might be animation worthy.
... and you might even be able to make a masterpiece out of it ...
[The Making of Woody](https://www.youtube.com/watch?v=6wyKqZeMdUI&list=UUdkBa5GZKEAfiTjqfqotWhQ&index=21)

**Comment by kdschlosser** [comment]
That is what @RobinD42 is doing by adding the bindings needed to get this working in a manner that is better then my "hack". Having all of the mechanics exposed to be able to either do a complete python decode or to act as a go between for a decoder that is written in c code is the important thing. The biggest hurdle to overcome is moving the rendering of a frame into the actual decoder. This may not be 100% needed if the methods in AnimationCtrl get exposed it would lend to better code organization on the application end of things. One thing it would allow for is the ability for a decoder to be released as an "add on" and no monkey patching would need to be done in order for it to work properly. Which would not be the case if the rendering of the frame stays in wxAnimationCtrl. The backing store would also need to be moved as well. FLIF does not use a backing store. each frame is actually a complete rendering of either the whole image or it is an "overlay". There is only a delay. so there is no need for a backing store because it does not make use of any kind of dispose operations. Those backing store operations could cause an issue with an FLIF animation due to the time it takes to perform them so if the operations were moved to the decoder then whether or not they need to be used would be dictated by the decoder it's self and not the animationctrl. That is where the need to monkey patch would come from if someone wanted to distribute a decoder as an add on. This is how the program I wrote would end up being used. either as a standalone import or it could be written to override the existing AnimationCtrl and Animation classes entirely.

Having to have repeat code is sometimes a necessary evil as with the case here. While APNG, ANI and GIF share the same dispose operations and would need to make use of the backing store you have a decoder like FLIF which does not have a need for it. Once I get into looking at other animation formats I will know more about how common that type of rendering operation is. It could be added to wxAnimationDecoder and if it is needed then it can get used and if not it sits there dormant which will also work.

**Comment by RobinD42** [comment]
This will auto-close when the PR is merged.

**Comment by RobinD42** [comment]
@kdschlosser, the snapshot built last night includes the overhaul of the `wxAnimation` classes. If things were done correctly then you should be able to derive a class from `AnimationDecoder` to implement your APNG animation. If you do implement this please let me know how it goes. There were some changes to the API in order to be able to have both native and generic controls available, see the dev docs and the updated sample in the demo.

If you'd like to contribute the APNG decoder to the `wx.lib` then that would be great too. If you do I suggest following the pattern in `wxpTag.py` where simply importing the module takes care of creating an instance of the decoder and adds it to the handler list.

**Comment by kdschlosser** [comment]
OK I will give it a test run over the next week or so and we will see what I come up with.
Do you think I should make more of a codec instead of strictly being a decoder? This would allow a user to add any type of image file that wx supports so an animation could be created. Then it can be optionally saved as an APNG if wanted.

**Comment by RobinD42** [comment]
I'll leave that up to you.
