### ISSUE TITLE
RuntimeError when opening/closing/opening WIT

### ISSUE THREAD

**Issue by topic2k** [wxWidgets/Phoenix#158]
Python: 2.7.9
wxPython: 3.0.3.dev2454+53f3c37 msw (phoenix)

Run the demo, open WIT (`F6` or menu `Help` -> `Open Widget Inspector`) , close WIT and again open it via `F6` or menu. Now i get a RuntimeError:
```
Traceback (most recent call last):
  File "D:\devel\wxPhoenix\demo\Main.py", line 2472, in OnOpenWidgetInspector
    InspectionTool().Show(wnd, True)
  File "C:\Python27sl\lib\site-packages\wx\lib\inspection.py", line 104, in Show
    app=self._app)
  File "C:\Python27sl\lib\site-packages\wx\lib\inspection.py", line 160, in __init__
    style=wx.NO_BORDER,
  File "C:\Python27sl\lib\site-packages\wx\py\crust.py", line 47, in __init__
    *args, **kwds)
  File "C:\Python27sl\lib\site-packages\wx\py\shell.py", line 342, in __init__
    self.execStartupScript(startupScript)
  File "C:\Python27sl\lib\site-packages\wx\py\shell.py", line 421, in execStartupScript
    self.push('')
  File "C:\Python27sl\lib\site-packages\wx\py\shell.py", line 972, in push
    self.more = self.interp.push(command)
  File "C:\Python27sl\lib\site-packages\wx\py\interpreter.py", line 82, in push
    command=command, more=more, source=source)
  File "C:\Python27sl\lib\site-packages\wx\py\dispatcher.py", line 147, in send
    response = _call(receiver, signal=signal, sender=sender, **kwds)
  File "C:\Python27sl\lib\site-packages\wx\py\dispatcher.py", line 176, in _call
    return receiver(**kwds)
  File "C:\Python27sl\lib\site-packages\wx\py\filling.py", line 69, in push
    self.display()
  File "C:\Python27sl\lib\site-packages\wx\py\filling.py", line 159, in display
    if self.IsExpanded(item):
RuntimeError: wrapped C/C++ object of type FillingTree has been deleted
```

**Comment by RobinD42** [comment]
Thanks. I can duplicate the issue here and will look further into it soon.

**Comment by swt2c** [comment]
I have already started looking into this one, do you want me to keep going?

**Comment by RobinD42** [comment]
Sure, if you want to keep going that would be great.  

It looks like it isn't removing dead items from the dispatcher (`wx.py.dispatcher`) that were in the former inspection tool frame.  So when the next message is sent for the new `InspectionFrame` dispatcher is still trying to send it to the old components that were listening for the message, which no longer exist.  I thought that this may be a Python3 issue, but it looks like @topic2k is using 2.7.  IIRC dispatcher is using weak references to know when something should be removed, so maybe there is some difference between how SIP tracks instances and refcounts that is different enough from how Classic worked that is causing this issue.

**Comment by RobinD42** [comment]
There is an updated version of Patrick's dispatcher module at https://pypi.python.org/pypi/PyDispatcher.  If there doersn't seem to be any way to solve this issue as is, then it may be worthwhile to see if there is anything in the new version that can help.

**Comment by swt2c** [comment]
Yes, you got as far as I did (albeit probably much quicker than I did).

I'll keep investigating.

**Comment by swt2c** [comment]
OK Robin, I'm a bit stumped here.  I don't *think* the dispatcher stuff is the problem as I call `sys.getrefcount()` before and after the call to `dispatcher.connect()` and the refcount is the same.

However, there is still something retaining references to the FillingTree.  Incidentally, the same thing happens with FillingText too if I comment out the dispatcher.connect() registration in FillingTree.  There are some circular references involved here (FillingTree and FillingText have references to each other) but I would think there's plenty of time for the garbage collector to run and clear that out?

**Comment by RobinD42** [comment]
The fundamental difference between Classic and Phoenix that is probably the root of the problem is that in Classic the wrapped classes were actually pure python classes that reflected all method calls to the wrapped functions in the extension module.  In Phoenix the wx classes are Extension Types (essentially Python new-style classes implemented in C with a type object) so there is a lot tighter integration with Python than in Python where it was all essentially just a bunch of standalone functions in the C wrapper code.

There is a way to make Extension Types weak-referenceable, and I thought SIP was doing that, but I'll check for sure.  If it is then there may be some other issue related to the Extension Types, or perhaps how SIP is tracking the objects internally, or something similar.  If that's the case then we'll probably need to do something like to adding code to explicitly disconnect the dispatcher message handlers, or perhaps switch to something else that doesn't need to use weak-references to the wrapped classes.

**Comment by RobinD42** [comment]
Ok, it looks like the Extension Types are set up to be weak referenceable, but through some experimentation it appears as if the removal from the weakref dictionaries or etc. is not always happening as soon as the windows are closed or destroyed, so I think that SIP is holding on to its internal reference for a while.  

There is also another issue with Extension Types that we need to watch out for, and that is GC.  Cycles involving Extension Types are normally excluded from GC support.  While this is also fixable at the C API level, it imposes some overhead and probably isn't wise to blindly do it for everything.  The docs suggest that it be done for containers, so I'm not sure if it is applicable/desirable for every type.

Anyway, for this specific issue it looks like the best idea for now is to explicitly disconnect the message receivers when the old window instances are no longer valid.  I'll be pushing/merging a PR for that in a little while.

**Comment by swt2c** [comment]
> Ok, it looks like the Extension Types are set up to be weak referenceable, but through some experimentation it appears as if the removal from the weakref dictionaries or etc. is not always happening as soon as the windows are closed or destroyed, so I think that SIP is holding on to its internal reference for a while. 

Just for my own information, can you explain how you verified that the Extension Types are set up to be weak referenceable?  As far as I could tell, based on looking at this: https://docs.python.org/2/extending/newtypes.html#weak-reference-support, I could not see where this was enabled.

> There is also another issue with Extension Types that we need to watch out for, and that is GC. Cycles involving Extension Types are normally excluded from GC support. While this is also fixable at the C API level, it imposes some overhead and probably isn't wise to blindly do it for everything. The docs suggest that it be done for containers, so I'm not sure if it is applicable/desirable for every type.

Indeed, as I noted earlier, there are some reference cycles coming into play here.  If SIP's Extension Types are not set up for GC, then that may indeed be the underlying problem that we're running into here.

**Comment by RobinD42** [comment]
I saw something in the code that made me think that the weakref support was being added indirectly, but I can't find it now. I've asked Phil for clarification on it and am waiting for an answer.

I also did some experimentation and for the simple types like `wx.Size` weak references to them do behave properly. Widget classes do also, but usually with a delay before the weakref's are cleared.
