### ISSUE TITLE
DirDialog not working whilst FileDialog does

### ISSUE THREAD

**Issue by alaricLEA** [wxWidgets/Phoenix#1583]
Windows 10 Home. 1909. 64bit.
wxPython 4.0.7 post2 pip
Python 3.7.3 pip

Hi.

I've been using wxPython for a number of years and recently found old functionality is no longer working in my program. The DirDialog does not work whilst the FileDialog does. I've tried with and without a parent frame. Strangely both dialogs work fine via the demos and when in isolation, so there's something about the way I've built my GUI that seems to be the problem but I've honestly no idea where to start.... Any suggestions would be very welcome.

This works.......
                dlg = wx.FileDialog(None)
                dlg.ShowModal()

This does not. The whole thing freezes without showing a prompt.....
                dlg = wx.DirDialog(None)
                dlg.ShowModal()

**Comment by Metallicow** [comment]
Please provide a full working sample app. Does this work with Py2?

**Comment by alaricLEA** [comment]
I'm trying to put a working sample together - my code is very fragmented. Hopefully post soon.

Yes it works perfectly on the same computer with python 2.7.15 and wxPython 4.0.6msw.

**Comment by alaricLEA** [comment]
Sample code below. 
I've managed to track it to importing an Intel depth camera module called pyrealsense2.
I'd be very grateful for any suggestions.
---------------------------------------------------------------------------------
import wx
import pyrealsense2 as rs   # Commenting this out will produce the dialog

class Main():

    def __init__(self):
        self.app = wx.App(False)       
        self.frame = wx.Frame(None, -1, '', size =(1000,500),style=wx.DEFAULT_FRAME_STYLE | wx.NO_FULL_REPAINT_ON_RESIZE)
        self.frame.Centre()
        self.frame.Show(True)
        
        dlg = wx.DirDialog(None, 'If you see this then its working')
        dlg.ShowModal()

main = Main()

**Comment by alaricLEA** [comment]
Update: I've also tried with a tkinter dialog and I get the same issue so assuming this is a pyrealsense2 issue rather than wxPython.
