### ISSUE TITLE
Incorrect amount of days in March 2020

### ISSUE THREAD

**Issue by DKMR** [wxWidgets/Phoenix#1585]
**Operating system**: Windows 10 x64
**wxPython version & source**: pypi wxPython 4.0.7.post2
**Python version & source**: stock Python 3.82 x64

**Description of the problem**:
According to the return value of _wx.DateTime.GetNumberOfDays()_, the current month of March 2020 has 30 days instead of 31. This will raise the following error:

> wx._core.wxAssertionError: C++ assertion "(0 < day) && (day <= GetNumberOfDays(month, year))" failed at ..\..\src\common\datetime.cpp(1221) in wxDateTime::Set(): Invalid date in wxDateTime::Set()

Running `print(wx.DateTime.GetNumberOfDays(3, 2020))` will return 30.

This is a problem because I can't initialise _wx.DateTime_ with _FromDMY()_ function since it considers day 30 to be the max number of days in March.

**Comment by Metallicow** [comment]
Does python do this too, or just wxPython/wxWidgets?

**Comment by RobinD42** [comment]
Contrary to popular belief, 3 is not March. 

```
>>> wx.DateTime.Jan, wx.DateTime.Feb, wx.DateTime.Mar, wx.DateTime.Apr
(0, 1, 2, 3)
```
