### ISSUE TITLE
wx.Bitmap.SetSize crop image instead of resize it

### ISSUE THREAD

**Issue by valosekj** [wxWidgets/Phoenix#1588]
**Operating system**: Debian 10 Buster with MATE Environment 1.20.4
**wxPython version & source**:  wxPython==3.0.2.0
**Python version & source**:  Python 2.7.16

**Description of the problem**:

Both `wx.Bitmap.SetSize` or `wx.StaticBitmap(size=)` crop image instead of resize it.
Under OSX same code works as expected and resize image.

Example with `wx.Bitmap.SetSize`:
```python
import wx

class Panel(wx.Panel):
    def __init__(self, parent, path):
        super(Panel, self).__init__(parent, -1)
        image = wx.Image(path, wx.BITMAP_TYPE_ANY).ConvertToBitmap()
        image.SetSize((image.GetWidth() // 3, image.GetHeight() // 3))

        bitmap = wx.StaticBitmap(self, -1, image, pos=(20,20))

if __name__ == '__main__':
    app = wx.PySimpleApp()
    frame = wx.Frame(None, -1)
    panel = Panel(frame, 'path_to_image.png')
    frame.Show()
    app.MainLoop()

```

I can use `wx.Image.Scale` which works fine but decreases quality of the image.

Any help? Thanks!

**Comment by RobinD42** [comment]
According to the docs (https://docs.wxpython.org/wx.Bitmap.html#wx.Bitmap.SetSize) it looks like it's actually the OSX version which is incorrect. Using `wx.Image.Scale` is the way to go.

**Comment by valosekj** [comment]
> According to the docs (https://docs.wxpython.org/wx.Bitmap.html#wx.Bitmap.SetSize) it looks like it's actually the OSX version which is incorrect. Using `wx.Image.Scale` is the way to go.

Thanks for reply! Is there any way how to preserve original quality of image when using `wx.Image.Scale`? I have tried all its interpolation methods (https://wxpython.org/Phoenix/docs/html/wx.ImageResizeQuality.enumeration.html) and all of them reduce quality.

**Comment by RobinD42** [comment]
No, there isn't any way that I know of to do a completely lossless resizing of a raster image, only better or worse interpolation algorithms. 

You may have better luck with using the Pillow package to do the scaling. It can do it in-memory, and then the PIllow `Image` can be converted back to a `wx.Image` (google for how to do that.)

Another possibility would be to use an external command line utility, like ImagMagick, to resize the image and then load the resulting file into a `wx.Image` or `wx.Bitmap`.
