### ISSUE TITLE
Query: Float AUI pane within main window?

### ISSUE THREAD

**Issue by jonfitt** [wxWidgets/Phoenix#1589]
I'm looking at the AUI demo. I see I can float a pane. But is it possible to have that pane float inside the main window?

Think sticky notes on a board. I want to be able to move them around the board canvas, but as the board moves, the sticky notes would move with it.

**Comment by RobinD42** [comment]
No, I don't think the AUI classes support anything like that. It's mainly about being able to dock and undock panels, not pin them at arbitrary positions relative to another window. It might be something that could be added if you're interested in implementing it.

OTOH, it you want your panes to be located *only* within the window then another approach might be better. Perhaps something where you just draw the panes on the "parent" window and add mouse event handlers for moving them around and such. Perhaps built on FLoatCanvas or OGL. Just food for thought...
