### ISSUE TITLE
Module wx has no attribute PU_CONTAINS_CONTROLS

### ISSUE THREAD

**Issue by hhannine** [wxWidgets/Phoenix#1593]
**Operating system**: Windows 10
**wxPython version & source**:  PyPI 4.0.7.post2
**Python version & source**: stock: Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)] on win32

**Description of the problem**:
Trying to put a TextCtrl in a PopupWindow but the style wx.PU_CONTAINS_CONTROLS suggested by  the documentation is not found.

I've built a small PopupTransientWindow that has a TextCtrl. This has worked on Linux well enough. However on Windows the popup does not get focus.

```python
# runnable in console
import wx
wx.PU_CONTAINS_CONTROLS
```
outputs: AttributeError: module 'wx' has no attribute 'PU_CONTAINS_CONTROLS'.

**Comment by RobinD42** [comment]
You are using wxPython 4.0.x but you are apparently looking at the 4.1.x (in-development, pre-release) version of the docs. The docs for the latest release version of wxPython are located at http://docs.wxpython.org/.

4.1.0 is coming soon.
