### ISSUE TITLE
Windows 10: wx.Button cut off or not drawn if client area overlaps with a wx.StaticBitmap

### ISSUE THREAD

**Issue by hhannine** [wxWidgets/Phoenix#1595]
**Operating system**: Windows 10
**wxPython version & source**:  both on PyPI 4.0.7-post2 AND on wx.version: 4.1.0a1.dev4694+bf0d92fb msw (phoenix) wxWidgets 3.1.4    
**Python version & source**:  Python 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AMD64)]          

**Description of the problem**:
If a wx.Button is put on top of or to the edge of a wx.StaticBitmap partially or fully overlapping in client area, on Windows the part of the Button clashing with the StaticBitmap is not drawn. On linux the Button is fully drawn on top of the StaticBitmap. My implementation moves the buttons when the frame is resized which reveals that the buttons that are cut off don't have the parts at all that should be over the StaticBitmap. 

I've added some buttons to the StaticBitmap demo, shown below.
Please find attached images of the issue.
![buttons_on_top_staticbitmap_linux](https://user-images.githubusercontent.com/47873564/79051874-49207500-7c3b-11ea-9292-f779bd103e11.png)
![buttons_on_top_staticbitmap_win10](https://user-images.githubusercontent.com/47873564/79051875-4a51a200-7c3b-11ea-9f1d-e015b2805a57.png)

```python
# StaticBitmap.py with some buttons, runnable
#!/usr/bin/env python

import  wx
import  images


USE_GENERIC = 0

if USE_GENERIC:
    from wx.lib.stattext import GenStaticText as StaticText
    from wx.lib.statbmp  import GenStaticBitmap as StaticBitmap
else:
    StaticText = wx.StaticText
    StaticBitmap = wx.StaticBitmap


#----------------------------------------------------------------------

class TestPanel(wx.Panel):
    def __init__(self, parent, log):
        wx.Panel.__init__(self, parent, -1)
        self.log = log
        ##self.SetBackgroundColour("sky blue")

        StaticText(self, -1, "This is a wx.StaticBitmap.", (45, 15))

        bmp = images.Test2.GetBitmap()
        mask = wx.Mask(bmp, wx.BLUE)
        bmp.SetMask(mask)
        StaticBitmap(self, -1, bmp, (80, 50), (bmp.GetWidth(), bmp.GetHeight()))

        bmp = images.Robin.GetBitmap()
        StaticBitmap(self, -1, bmp, (80, 150))

        btn1 = wx.Button(self, -1, label="TestButton", pos=(100, 140))
        btn2 = wx.Button(self, -1, label="TestButton2", pos=(100, 200))
        btn3 = wx.Button(self, -1, label="TestButton3", pos=(100, 290))



#----------------------------------------------------------------------

def runTest(frame, nb, log):
    win = TestPanel(nb, log)
    return win

#----------------------------------------------------------------------

overview = """\
A StaticBitmap control displays a bitmap.

A bitmap can be derived from most image formats using the wx.Image class.

"""

if __name__ == '__main__':
    import sys,os
    import run
    run.main(['', os.path.basename(sys.argv[0])] + sys.argv[1:])

```

**Comment by RobinD42** [comment]
Officially the behavior of overlapping sibling widgets is undefined. If you want to place an image behind buttons or other widgets, then the best way to do it is to give the parent an `EVT_PAINT` handler and draw the image there with a `wx.PaintDC`.
