### ISSUE TITLE
Want to focus to readonly text ctrl from keyboard

### ISSUE THREAD

**Issue by yamahubuki** [wxWidgets/Phoenix#1596]
We can often focus on wx.TextCtrl using the TAB key.
However, if TextCtrl has TE_READONLY style, cannot focus from keyboard.

Of course, the user cannot change the contents of this control.
However, once you have the focus, you can copy the content to the clipboard or read it while scrolling.

In addition, the problem may mean that visually impaired users may not recognize the control.

Therefore, please make sure that you can focus on the keyboard regardless of whether TextCtrl has TE_READONLY style.

**Comment by RobinD42** [comment]
Try deriving a new class from `wxTextCtrl` and overriding the `AcceptsFocusFromKeyboard` method. Since it's a native control it may or may make any difference, depending on how much the system let's us do with that control.

**Comment by yamahubuki** [comment]
thank you for telling.
I succeeded.
