### ISSUE TITLE
missing wx.grid.GRIDTABLE_REQUEST_VIEW_GET_VALUES in wxpy4.1

### ISSUE THREAD

**Issue by mprosperi** [wxWidgets/Phoenix#1603]
**Operating system**:
**wxPython version & source**:          pre-4.1a
**Python version & source**:            3.7.7 stock (win10)

**Description of the problem**: wx.grid.GRIDTABLE_REQUEST_VIEW_GET_VALUES is not available in 4.1 but is still used in Grid_MegaExample.py. Can't find if it has been renamed with respect to 4.0.7

>>> wx.grid.GRIDTABLE_REQUEST_VIEW_GET_VALUES
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'wx.grid' has no attribute 'GRIDTABLE_REQUEST_VIEW_GET_VALUES'

**Comment by RobinD42** [comment]
It looks like it's been removed from the C++ code because it "never did anything..."

Thanks for reporting it, I'll update the sample.

**Comment by RobinD42** [comment]
Fixed in 260d08e32d1290ab75501c313a22f6c54f9fe6ae
