### ISSUE TITLE
ProgressDialog crashes on wxpython 4.1.0

### ISSUE THREAD

**Issue by DarkFenX** [wxWidgets/Phoenix#1610]
**Operating system**: windows 10 64 bit, 200% UI scaling
**wxPython version & source**:  4.1.0 msw (phoenix) wxWidgets 3.1.4 from pip
**Python version & source**: python 3.8.2 64 bit from python.org

**Description of the problem**:
`ProgressDialog` crashes (at least on windows). The error message is:
```
Traceback (most recent call last):
  File "wxtest.py", line 16, in <module>
    mf = MainFrame()
  File "wxtest.py", line 9, in __init__
    dlg.ShowModal()
wx._core.wxAssertionError: C++ assertion ""IsRunning()"" failed at ..\..\src\common\evtloopcmn.cpp(95) in wxEventLoopBase::Exit(): Use ScheduleExit() on not running loop
```
```python
import wx


class MainFrame(wx.Frame):

    def __init__(self):
        super().__init__(None, wx.ID_ANY, 'Application')
        with wx.ProgressDialog(parent=self, title='title', message='message', maximum=100) as dlg:
            dlg.ShowModal()
        self.Layout()
        self.Show()


if __name__ == '__main__':
    app = wx.App(False)
    mf = MainFrame()
    app.MainLoop()
```
It works on GTK. For windows, there is a substitute which works -`GenericProgressDialog`.

**Comment by jmkd3v** [comment]
Hi - I'm also encountering this issue on Windows, but not on macOS. The error message only appears if you call `ShowModal()` - if you instead call `ShowWindowModal()`, the app locks up for a second and then crashes:
```
Process finished with exit code -1073741819 (0xC0000005)
```

**Comment by DietmarSchwertberger** [comment]
Your code is not correct. There's no point in calling `ShowModal` for a `ProgressDialog`.
If your call to `ShowModal` was successful, it would just block. It would certainly not show a progress.

See the wxPython demo for how to use the dialog, or here:

```
import wx

class MainFrame(wx.Frame):

    def __init__(self):
        super().__init__(None, wx.ID_ANY, 'Application')
        self.Layout()
        self.Show()
        wx.CallLater(300, self.show_progress)

    def show_progress(self):        
        #style = wx.PD_APP_MODAL | wx.PD_CAN_ABORT | wx.PD_ESTIMATED_TIME | wx.PD_REMAINING_TIME
        #| wx.PD_CAN_SKIP
        #| wx.PD_ELAPSED_TIME
        #| wx.PD_AUTO_HIDE
        style = wx.PD_APP_MODAL | wx.PD_AUTO_HIDE  # default style
        style = wx.PD_AUTO_HIDE  # probably only window modal

        maximum = 100
        with wx.ProgressDialog(parent=self, title='title', message='message', maximum=maximum, style=style) as dlg:
            keepGoing = True
            count = 0    
            while keepGoing and count < maximum:
                count += 1
                wx.MilliSleep(250)
                wx.Yield()
    
                if count >= maximum / 2:
                    (keepGoing, skip) = dlg.Update(count, "Half-time!")
                else:
                    (keepGoing, skip) = dlg.Update(count)

if __name__ == '__main__':
    app = wx.App(False)
    mf = MainFrame()
    app.MainLoop()
```

**Comment by DietmarSchwertberger** [comment]
Please close the ticket. Next time, better post on discuss.wxpython.org .

**Comment by DarkFenX** [comment]
Thanks, will try it later

**Comment by jmkd3v** [comment]
> Your code is not correct. There's no point in calling `ShowModal` for a `ProgressDialog`.

How are we supposed to use window modals like ShowWindowModal then? There's no "ShowWindow" at the moment.

**Comment by DietmarSchwertberger** [comment]
See code example above. The progresss dialog does always show immediately and it is always modal. Additionally, you can use `PD_APP_MODAL`.

**Comment by jmkd3v** [comment]
I'm not talking about disabling other windows, I specifically mean the **window modal** behavior where windows are shown within other windows rather than in separate windows. This only really applies on macOS as far as I can tell.

**Comment by DietmarSchwertberger** [comment]
Is there a native progress dialog on macOS?
It seems wx is using a wxGenericProgressDialog on macOS.

**Comment by jmkd3v** [comment]
This isn't a progress-bar specific behavior. I'm specifically referring to the function of `ShowWindowModal` vs the function of `ShowModal` - `ShowModal` always uses a separate window, but `ShowWindowModal` will make the dialog appear *within the root frame* rather than as a separate window entirely on macOS.

**Comment by DietmarSchwertberger** [comment]
If you have problems with ShowWindowModal, then please create a ticket about that. (Probably you need to create a C++ sample and report it as wxWidgets bug.)
There's no point in reporting problems with ProgressDialog and Show...Modal.

**Comment by jmkd3v** [comment]
> If you have problems with ShowWindowModal, then please create a ticket about that. 

I do not have problems with it - the problem is that the solution you are suggesting (not calling ShowModal at all) means you can't have the window-within-window behavior.

**Comment by DietmarSchwertberger** [comment]
If other dialogs do show such behaviour, then you might think about deriving such a macOS specific version from GenericProgressDialog.
(Actually, it will probably be side by side with GenericProgressDialog.)
You could do that in Python. If it's working, you could port to C++ and submit a PR for wxWidgets. Otherwise, you may 'just' submit a PR for wxPython to add it to wx.lib.
