### ISSUE TITLE
EVT_STC_AUTOCOMP_SELECTION_CHANGE broke being generated

### ISSUE THREAD

**Issue by Metallicow** [wxWidgets/Phoenix#1613]
**Operating system**:
**wxPython version & source**:  wxPython 4.1.1a1.dev4719+b475c35a msw (phoenix) wxWidgets 3.1.4 Scintilla 3.7.2
**Python version & source**: Python 2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 20:49:36) [MSC v.1500 32 bit (Intel)] on win32

```python
EVT_STC_AUTOCOMP_SELECTION_CHANGE = wx.PyEventBinder( wxEVT_STC_AUTOCOMP_SELECTION_CHANGE, 1)
```
is not being generated in stc.py

This was working in snapshot builds before. something happened...
```
        if wx.VERSION[0:3] > (4, 1, 0, 0, '')[0:3]:
            self.Bind(stc.EVT_STC_AUTOCOMP_SELECTION_CHANGE, self.OnSTCAutoCompSelectionChange)
```

**Comment by Metallicow** [comment]
Looks like the etg file needs updated to add that line.
Still exists in new Scintilla Docs
https://www.scintilla.org/ScintillaDoc.html#Notifications

**Comment by RobinD42** [comment]
This issue has been mentioned on **Discuss wxPython**. There might be relevant details there:

https://discuss.wxpython.org/t/wxpython-4-1-1-released/35043/1
