### ISSUE TITLE
wx.DIALOG_EX_CONTEXTHELP

### ISSUE THREAD

**Issue by JoenyBui** [wxWidgets/Phoenix#163]
I've been trying to create a help button for my application, but I wasn't able to implement the help button without removing the minimize and maximize button.  Is this something that just can't happen with wx?

**Comment by RobinD42** [comment]
Please add info about your platform and wx version, and also some sample code (minimal, but runnable) that shows how you are creating the dialog which isn't working as expected.

**Comment by JoenyBui** [comment]
I'm on Window 10, 64-bit version and wxpython 3.0.  The basic code is the following:

`

	import wx

	class TestFrame(wx.Frame):

		def __init__(self, parent, *args, **kwargs):
			wx.Frame.__init__(self, parent, *args, **kwargs)

			self.SetExtraStyle(wx.DIALOG_EX_CONTEXTHELP)

	if __name__ == '__main__':
		app = wx.App(False)

		frame = TestFrame(None)
		frame.Show(True)

		app.SetTopWindow(frame=frame)

		app.MainLoop()
`

Once I add self.SetExtraStyle(wx.DIALOG_EX_CONTEXTHELP), it removes the minimize and maximize button.  Is there a way to have all three?

**Comment by RobinD42** [comment]
I suspect that this is a limitation imposed by Windows.  In addition to some comments alluding to this limitation in general Win32 programming topics, I've also seen reports of the same issue from Qt users, so it is not limited to wxWidgets.

Closing this issue.
