### ISSUE TITLE
Gtk-Critical: assertion failed

### ISSUE THREAD

**Issue by verschneidert** [wxWidgets/Phoenix#1639]
**Operating system**: Raspbian Buster
**wxPython version & source**: 4.0.7 post2, built according to [this](https://wiki.wxpython.org/BuildWxPythonOnRaspberryPi)         
**Python version & source**: Python 3.7.3           

**Description of the problem**: Whenever I run a program that uses wx I get the message: _(wxGUIv0.75.1.py:892): Gtk-CRITICAL **: 12:54:54.156: gtk_distribute_natural_allocation: assertion 'extra_space >= 0' failed_
(The number in the bracket is changing every time.)
The wx.Frame shows up without any problem and seems to be working fine, but sooner or later (roughly after 1min up to 3min runtime) it will freeze completely (the program keeps running though, it continues giving print output – as it is intended to – in the Terminal). In addition to that, something very strange happens: When I open a new window (eg. File Manager) and drag it over the wx.Frame, the part of the File Manager that lays over the wx.Frame will be "brand marked" onto the wx.Frame. This only occurs when the wx.Frame is already frozen and when the other window was opened after the wx.Frame froze.

```python
# Put code sample here
```

**Comment by swt2c** [comment]
Unfortunately, there isn't enough information here to help you.  GTK tends to produce a lot of output, not all of which is useful.  In a lot of cases, it is because you have not allocated enough space in your UI for the widgets to fit.

Can you provide a [SSCCE](http://sscce.org/) that reproduces the problem?

**Comment by verschneidert** [comment]
Well, while making the SSCCE I found what was causing the freeze. I did not use wx.CallAfter to communicate to the main thread. This issue works now, although I get a `free(): invalid pointer` error after some runtime, but that is another topic.
Thanks anyways!
