### ISSUE TITLE
wx.stc SetStyling does not work in 4.1.0

### ISSUE THREAD

**Issue by deonis1** [wxWidgets/Phoenix#1641]
**Operating system**: Linux, Ubuntu 18.04-20.04
**wxPython version & source**:       wxPython 4.1.0 from pip install wxpython
**Python version & source**:            python3.5-3.8 ubuntu repo

**Description of the problem**:   

Custom styling with text.StartStyling(start, wx.stc.STC_INDICS_MASK)  text.SetStyling(length, wx.stc.STC_INDIC2_MASK) no longer return styled text.  Was working fine in version 4.0.1-4.07

See https://github.com/deonis1/linxtl (Module/colour.py) for more details

**Comment by Metallicow** [comment]
Here is the doc strings. Seems the StyledTextCtrl1.py demo broke on StartStyling.

wxPython 4.0.7.post2 and wxPython 4.1.1a1
```
SetStyling(length, style)

Change style from current styling position for length characters to a
style and move the current styling position to after this newly styled
segment.
```

wxPython 4.0.7.post2
```
StartStyling(start, mask=255)
```
wxPython 4.1.1a1
```
StartStyling(start)

Set the current styling position to start.
```

**Comment by Metallicow** [comment]
@deonis1 
This Issue will be closed when demo commit is merged by Robin. 
Reference the changes I did to fix the demo for wxPy4.0/4.1 Scintilla changes and apply that to your code.

**Comment by RobinD42** [comment]
For the record, it looks like `StartStyling` was changed upstream in the Scintilla code.
