### ISSUE TITLE
wx.stc FindText function returns tupple instead of int in version 4.1.0

### ISSUE THREAD

**Issue by deonis1** [wxWidgets/Phoenix#1642]
**Operating system**: Linux, Ubuntu 18.04-20.04
**wxPython version & source**:       wxPython 4.1.0 from pip install wxpython
**Python version & source**:            python3.5-3.8 ubuntu repo
**Description of the problem**:   FindText function returns tuple instead of int like in previous version 4.01-4.0.7   

See https://github.com/deonis1/linxtl (Module/colour.py) for more details

**Comment by Metallicow** [comment]
You are very observant. You will notice it returns it as a selection like 2 tuple now.
so you need to change your return var to accept 2 values or use [0] or [1] depending on which one you need. You can still expect -1 for wx.NOTFOUND.

You will notice Scintilla has been updated so you will have a little bit of work to do wrapping a function if you want it to work the old way. This is not a bug. Its a you need to upgrade/adapt type of thing.
```python
print(wx.stc.StyledTextCtrl.GetLibraryVersionInfo().GetVersionString())
```

When wx updates Scintilla(Its a 3rd party piece) usually there is a quite a bit of changes. 
Changelog is here for base Scintilla to give you an idea.
https://www.scintilla.org/ScintillaHistory.html

**Comment by Metallicow** [comment]
But yeah just for reference this is what was done on wxPy side.
https://github.com/wxWidgets/Phoenix/pull/1271/files

**Comment by deonis1** [comment]
I agree it is not a bug but there are multiple other issues with styling and so. Not a big fan of these changes.

**Comment by Metallicow** [comment]
@deonis1 since I'm feeling nice today here is how I wrapped a backwards compatibility function.
You will not need the decorator btw...

```python
    if wx.VERSION[0:3] < (4, 1, 0, 0, '')[0:3]:
        @overwrittenmethod
        def FindText(self, minPos, maxPos, text, flags=0):  # -> (int, findEnd)
            """
            Override StyledTextCtrl.FindText

            findEnd isnt in a tuple in earleir versions so add it to prevent error
            """
            findBegin = super(BaseSTC, self).FindText(minPos, maxPos, text, flags)
            if findBegin == -1:
                return (-1, -1)
            findEnd = findBegin + len(text)
            return (findBegin, findEnd)
```

**Comment by Metallicow** [comment]
@RobinD42 This can be closed.

**Comment by deonis1** [comment]
Thank you for the free code!
