### ISSUE TITLE
CustomTreeCtrl: items invisible with dark themes on Ubuntu

### ISSUE THREAD

**Issue by petrasovaa** [wxWidgets/Phoenix#1647]
**Operating system**: Ubuntu 18.04
**wxPython version & source**:          pypi, 4.1.0
**Python version & source**:            3.6.9

**Description of the problem**:
With dark themes agw.CustomTreeCtrl has issues with displaying tree items, they are pretty much invisible unless selected, see screenshot from wxpython demo.
This was reported in an old [ticket](http://trac.wxwidgets.org/ticket/13377), probably it's caused by hardcoded values.
![Selection_012](https://user-images.githubusercontent.com/7494312/82705883-7999fc80-9c46-11ea-8562-79b6fbcd27c9.png)

**Comment by infinity77** [comment]
The issue is certainly due to setting the background color of CustomTreeCtrl to wx.WHITE in the initialization. There might be other problems later - in terms of text color, for example, but they should be tackled later. It’s an easy fix, although I have no idea what the default background color should be (I.e., what SystemSettings to use?).

**Comment by infinity77** [comment]
Also, the background color (and text color and so on) should probably be made dynamic by binding the wx.SYS_COLOUR_CHANGED and adapt those colors on the fly, so people who like playing with themes can have an instant feedback for it.

**Comment by cbeytas** [comment]
There is a fix already for this in commit https://github.com/wxWidgets/Phoenix/pull/1128/commits/ac0f578a01e4e4fc9c1e50a349a154367217d05d

**Comment by petrasovaa** [comment]
> There is a fix already for this in commit [ac0f578](https://github.com/wxWidgets/Phoenix/commit/ac0f578a01e4e4fc9c1e50a349a154367217d05d)

This is in #1128. I tested that particular commit locally and it doesn't seem to help though.

**Comment by cbeytas** [comment]
I just checked Ubuntu 18.04 dark theme and it works even without that commit.

Like infinity77 said, the background color is probably being forced somewhere with `SetBackgroundColour(wx.WHITE)`. The demo does this as well.

If you find the line you can delete it, but without https://github.com/wxWidgets/Phoenix/commit/ac0f578a01e4e4fc9c1e50a349a154367217d05d it will cause everyone with a "light" theme to get an ugly background.

**Comment by infinity77** [comment]
@petrasovaa , just for fun I went to take a look at the GRASS code. Not sure if this is the issue, but on line 199 in the file gui/wxPython/gui_core/treeview.py you have this:

self.SetBackgroundColour("white")

**Comment by Metallicow** [comment]
Back when I was porting the demo to phoenix I recall coming across the issue that the text was invisible.
Figuring out what the background color should be and inverting it should work I would think and if user has applied a personal color then do that or some such.
Here is where I removed the sanity hack I did to make sure I could see the text.
https://github.com/wxWidgets/Phoenix/commit/fa0001c49c2457c0d0587ab207152fcdd059d78d#diff-c8d144a0eb60caedab6fb2d0c2dff908
I don't recall if anything else was done afterwards regarding the text color.

**Comment by petrasovaa** [comment]
> @petrasovaa , just for fun I went to take a look at the GRASS code. Not sure if this is the issue, but on line 199 in the file gui/wxPython/gui_core/treeview.py you have this:
> 
> self.SetBackgroundColour("white")
> 
> Of course that may not be the issue at all - I’ve browsed the code for exactly 1 minute and I have no clue whatsoever about the GRASS UI architecture.
> 
> The same can be seen at line 179 of gui/wxPython/lmgr/layertree.py

Sorry, you are right, I missed that. So this one is invalid, I opened a new one related to HyperTreeList.
