### ISSUE TITLE
wxDemo: "Allow floating panes" can't be checked

### ISSUE THREAD

**Issue by jcnorris00** [wxWidgets/Phoenix#1652]
**Operating system**: MS Windows 10, Ubuntu 18.04 with GTK+ 3.0
**wxPython version & source**:         4.1.0 (pypi)
**Python version & source**:            3.8.3 (Windows), 3.6.9 (Ubuntu)

**Description of the problem**: When selecting "Allow floating panes" under the Options menu, the following error occurs:

```
Traceback (most recent call last):
  File "/home/jnorris/.wxPython/wxPython-demo-4.1.0/demo/Main.py", line 2307, in OnAllowAuiFloating
    self.allowAuiFloating = event.Checked()
AttributeError: 'CommandEvent' object has no attribute 'Checked'
```

I'm pretty sure that this will happen on every platform but MS Windows and Ubuntu are the only ones that I have access to.

**Comment by topic2k** [comment]
I think the code in that line is wrong and must be changed to:
```self.allowAuiFloating = event.IsChecked()```
