### ISSUE TITLE
Font sizes incorrect using wx.GraphicsContext under Windows

### ISSUE THREAD

**Issue by david-hughes** [wxWidgets/Phoenix#167]
With wx.lib.pdfviewer under Windows when using wx.GraphicsContext or Cairo.GraphicsContext I have had to apply a scale factor to the font sizes in the ratio of points-per-inch/screen-pixels-per inch (normally 72/96 = 0.75) as the fonts come out too big in some circumstances. However the scaling affects the wx.Font.PointSize, which can only take integer values. In my own application the original fonts are nearly all 12 point, which scales exactly to 9 point but when, for example, text is 10 point (-> 7.5) it can only be scaled to 8 point (too big) or 7 point (too small). 

In general, the scaling needs to be applied to gc.SetFont which sets the font size and dc.GetFullTextExtent which returns the font metrics. The behaviour of wx.GraphicsContext and Cairo.GraphicsContext are slightly different:

wx.GraphicsContext requires scaling applied to both SetFont and GetFullTextExtent when rendering either to a screen or to a printer DC.

Cairo.GraphicsContext requires scaling applied only to GetFullTextExtent when rendering to a screen DC but to both SetFont and GetFullTextExtent when rendering to a printer DC.

It is not necessary to apply any sort of scaling when using OS X. Is there any advice on how this problem might best be addressed so that no scaling is required under Windows?

**Comment by david-hughes** [comment]
The attached are scanned from outputs printed using pdfviewer from a file supplied by Bob Vandy. He has massaged the content so it doesn't refer to real people or places. The file names reflect the different scenarios and in each case the underlining of the sub-headings is done by drawing a horizontal line, which is the actual width the text should match.

[ViaPyMuPDF.pdf](https://github.com/wxWidgets/Phoenix/files/458799/ViaPyMuPDF.pdf)
[ScaledTo7point.pdf](https://github.com/wxWidgets/Phoenix/files/458802/ScaledTo7point.pdf)
[ScaledTo8point.pdf](https://github.com/wxWidgets/Phoenix/files/458801/ScaledTo8point.pdf)
[NoScaling.pdf](https://github.com/wxWidgets/Phoenix/files/458800/NoScaling.pdf)

**Comment by RobinD42** [comment]
Sorry for the delay...

I've also wondered why `wxGraphicsFont` wasn't given the ability to use fractional point sizes via floating-point values, whether directly or via `wxFont` also allowing floating-point point sizes. I've run into other cases where the truncation of fractional values for drawing text has been a PITA.

I think you'll probably need to have this discussion on wx-dev or in a Trac ticket to get any traction on it as I'm not able to do anything in wxPython about it.  In the meantime, IIRC, the `GraphicsFont` in `wx.lib.graphics` does support fractional point sizes, although you have to set the point size after initializing it with a `wx.Font` or something like that. (It's been a long while since I played with that module...)

**Comment by adrientetar** [comment]
Ah, I've been hitting this bug. So is this a wxWidgets issue or wxPython? I'm confused.

**Comment by RobinD42** [comment]
wxWidgets

**Comment by vadz** [comment]
Sorry, I don't understand what is the problem here: we do have `wxGraphicsContext::CreateFont(double sizeInPixels, ...)` which is supposed to allow creating fonts with fractional size directly and I'd expect the overload taking `wxFont` to work too. What doesn't work exactly?

**Comment by adrientetar** [comment]
Right, CreateFont works, and also it seems using wxFont.SetPixelSize instead of SetPointSize works as well for integer sizes. So I think this can be closed after all. thanks!

**Comment by RobinD42** [comment]
> What doesn't work exactly?

I think it is a desire to be able to have support for fractional point sizes.

**Comment by vadz** [comment]
But the comment just above says that this does work...

**Comment by RobinD42** [comment]
For size in pixels, yes. But the original comment is about a needing a way to create a font with a fractional pointsize, such as 7.5.

**Comment by vadz** [comment]
We have no API for fractional point sizes anywhere, so the way to handle them is to convert size in points to pixels. We could, perhaps, provide a simple helper function doing this, but we're not going to have yet another way of specifying font sizes I'm afraid.
