### ISSUE TITLE
exception with ListCtrl demo

### ISSUE THREAD

**Issue by mprosperi** [wxWidgets/Phoenix#168]
selecting the ListCtrl demo script from the demo tree raises this  (py3.4-64bit on win7)

![exception](https://cloud.githubusercontent.com/assets/15137443/18364721/ae5e9c7a-760f-11e6-8365-0718405a08c1.png)

**Comment by swt2c** [comment]
Might be Windows-specific?  I don't see on Linux.

**Comment by david-hughes** [comment]
The first parameter of wx.ListCtrl.InsertItem() is a user supplied integer value called index. According to wxPython in Action it is the row in the list where the new item will be displayed, but its actual value doesn't seem to have any effect and, in the demo, all the items are being inserted with the same initial index value. There appears to be a convention in the demo programs that this value is set to sys.maxsize, I don't know why. That's OK with 32 bit Python but using any value greater than that, as with 64 bit Python, raises the above error.

Calling InsertItem() with an index value of zero seems to be OK and unless anyone objects to this, I'll create a PR to get all occurrences like this altered in the Phoenix repository.

**Comment by RobinD42** [comment]
I believe `sys.maxsize` is used to make the `InsertItem` to act like an Append instead. IOW, "inserting" using a value larger than the current number of items in the list in order to add it to the end.  I think switching it to zero would probably end up with the list in a reversed initial ordering, so a better fix would be to use `GetItemCount()` for the first parameter.

**Comment by david-hughes** [comment]
That's what I thought, but whatever value I used in the demo program it displayed the same list. I **eventually** discovered that the inclusion of style wx.LC_SORT_ASCENDING causes the list to be ordered initially by the contents of column 0 even without any mixins, callbacks or other sorting related code.

**Comment by david-hughes** [comment]
I have submitted pull request #174 which, I hope, fixes this issue.

**Comment by RobinD42** [comment]
#174 merged
