### ISSUE TITLE
Assertion with double click in PyColourChooser

### ISSUE THREAD

**Issue by DietmarSchwertberger** [wxWidgets/Phoenix#1683]
**Operating system**:  Windows 10, 64 bit
**wxPython version & source**: pypi `wx.version: 4.1.0 msw (phoenix) wxWidgets 3.1.4`
**Python version & source**: stock 3.6.4, 32 bit

**Description of the problem**: When double clicking in the colour chooser, an assertion is raised.
See screenshot below for the result of running demo/PyColourChooser.py
I have double-clicked inside the colour gradient rectangle (as still being indicated by the small circle.

I did not run the demo in the debugger, but wxGlade and there the assertion is raised in wx.lib.pycolourchooser:
```
pycolourchooser.py,  line 474, in onPaletteUp
  self.palette.ReleaseMouse() # Must call once for each CaputreMouse()
```
The error message is:
```
wx._core.wxAssertionError: C++ assertion ""!wxMouseCapture::stack.empty()"" failed at ..\..\src\common\wincmn.cpp(3370) in wxWindowBase::ReleaseMouse(): Releasing mouse capture but capture stack empty?
```

![PyColourChooser](https://user-images.githubusercontent.com/5512021/84809203-05b30000-b00a-11ea-9609-2bd83509623c.png)

**Comment by Metallicow** [comment]
Not surprising, the pycolorchooser didn't always work as expected, and probably really needs a rewrite. I don't have any double click issues with one I whipping up in SourceCoder from my MCOW coloring module, but I do get this weird crash when I double click on something like `wx.BLACK` in my STC and it pops up a small dialog with colors like wx.WHITE, wx.BLUE, wx.GREEN, etc and then crashes after I cancel the choice dialog. Still haven't figured out why it happens... tho I know it doesn't happen in wxPy4.0.x

**Comment by DietmarSchwertberger** [comment]
Thanks a lot.
