### ISSUE TITLE
wx.GetTranslation doesn't work when used as a default argument

### ISSUE THREAD

**Issue by blitzmann** [wxWidgets/Phoenix#1693]
**Operating system**: Windows 10
**wxPython version & source**:    4.0.6
**Python version & source**:        3.6

**Description of the problem**:

Text isn't translated when wx.GetTranslation is used as a default argument -- only the raw value is used.

Imagine we have the following code:

```python
    def PrintTranslation(self, text=wx.GetTranslation("English Text")):
        print(text)
```

If the locale is set to German and we have a German translation, this will still print out the English text.

This is the current workaround:

```python
    def PrintTranslation(self, text=None):
        text = text or wx.GetTranslation("English Text")
        print(text)
```

I'm not really sure if this is a bug with wxPython, or a limitation with python in general when dealing with default arguments. I feel like it might just be a limitation... come to think of it, I don't think I've ever attempted a function call as a default argument, so maybe that's just not a thing. But I wanted to open this up just in case and to also just get more information about ways to deal with this (the workaround we have is fine for now, but curious if there's better / more consensus-based solutions)

I've also opened up a discussion on the forum about this: https://discuss.wxpython.org/t/translations-dont-happen-when-set-as-default-argument/34719

See the attachment for a full working example (run wxLocale.py)
[locale_test.zip](https://github.com/wxWidgets/Phoenix/files/4808384/locale_test.zip)

**Comment by infinity77** [comment]
https://discuss.wxpython.org/t/translations-dont-happen-when-set-as-default-argument/34719/2
