### ISSUE TITLE
Consistancy 101: How to avoid noise

### ISSUE THREAD

**Issue by Metallicow** [wxWidgets/Phoenix#1694]
Consistancy 101: How to avoid noise

Github/Git is good at tracking changes. Those changes at times, are things most
of us do not recognise are happening are actually slowing us and our programs down.
Ex: Such as trailing whitespace and unnecessary commenting.

Believe it or not, comments are the biggest part of most coders cussing
under their breath. WHY! YOU ASK?

...well look no farther than Guido's recommendations, PEP8 and what is now called pycodestyle.
It is all community based, ... so that means millions of users have to
```python
try:
    generallyAgree
except ConsistancyError:
    spendMoreTime
```
making things more consistant.

Take this example. It is generally ok, but if you ever seen the wiki, you know
that no 2 "Separator" lines by different people hardly ever match. Lots of noise,
or you just delete all offending lines or replace them with your own.

```python
#-Python Imports.-------------------------------------------------------------
```

used to be just fine but now pycodestyle complains about this minimal issue.

```python
# Python Imports.-------------------------------------------------------------
```

Most often you see this type of stuff in "Seperations" of code logic.

Why should it matter, some ask?...
Well look at those lines as "Rulers" instead of just seperators.
Any line over 79 will throw a warning(yep, more noise in the commit logs)
Seems most coders using long line indicators(like STC has 1 or more now)
usually have them setup to 79, 80, 100, or 120 chars.
Mine personally are set to 80 and 120 as seen in the screenie.

FunnyFact: Dash `-` takes less time to draw than Hashtag `#`

Another peev I haz with pycodestyle is inline-comments.

Take this example.

```python
if True: run() # sonovapythonista
```

pycodestyle will complain, thus creating noise, that usually only your monitor hears the swearing.

```python
if True: run()  # Don't swear at me!
```

pycodestyle expects 2 spaces instead of 1 which wasnt a issue before.

Conclusion:
I'd like to get all these resolved. I tried to when wxPython was being ported
to Phoenix, but I only haz so much time, and also Robin only has so much time
to review. Porting the whole demo and trying to make a new framework wore me out.
It would be nice if the community can come up with something that works in tandem
with each other and push all the remaining noise thru as a single commit.
And in the future we will also have less noise because things will be 1 liners
for the most part.

If any other users has any quips with consistancy of the library as a whole,
I'd like them to get their ideas/solutions out there now.
I'd REALLY LIKE wxPython 4.2 to be clean of these irritating issues.

@RobinD42 of course if you need to update the wxpy coding guidelines.txt a bit that would be nice also as a guideline for others. A few things might change if using py3.8 syntax etc etc. I just realize this still hasn't been completed in years lol

**Comment by Metallicow** [comment]
![consistancy](https://user-images.githubusercontent.com/4668356/85256772-58d1ec00-b42a-11ea-89f3-b3b1545c89a9.png)

**Comment by Metallicow** [comment]
And even with full color annotated view in SourceCoder according to pycodestyle itself, even it shows inconsistancy in the rules it is supposed to enforce...
![pycodestyle](https://user-images.githubusercontent.com/4668356/85280280-706e9c00-b44d-11ea-90d0-5233e045fd24.png)

**Comment by mesalu** [comment]
Off topic, not a bug.

**Comment by infinity77** [comment]
PEP-8 and coding styles are a guide and a list of suggestions, not rules to follow blindly. As far as I am concerned, I couldn’t care less about number of blank lines or line length or SmallCaps versus this_function_name(). 
It’s not that there aren’t more important issues to address than coding styles...
