### ISSUE TITLE
Custom wx.PGEditors crashing.

### ISSUE THREAD

**Issue by jarts-cousins** [wxWidgets/Phoenix#1696]
Custom propertyEditor for the property Grid crashed python.

Windows 10 Enterprise
wxPython 4.1.1a1.dev4833+b452a252
Python 3.7 

Custom PGEditors was crashing - 
(1) updated to wxPython 4.1.0,  but still issues.
(2) Updated to the "bleeding edge" release because it appeared that some PGEditor issues had been addressed in https://github.com/wxWidgets/Phoenix/issues/1636

Have reduced it down to this example. Clicking on the first property crashes python.
Process finished with exit code -1073741819 (0xC0000005)

import wx.propgrid as wxpg
import wx

def initPGEditors():
    pgTestEditor = TestEditor()
    wxpg.PropertyGrid.RegisterEditorClass(pgTestEditor)

class TestEditor(wxpg.PGTextCtrlEditor):
    def __init__(self):
        wxpg.PGTextCtrlEditor.__init__(self)
        self.btns = None                            # examples and doc don't show need for local button storage

    def GetName(self):
        return "TestEditor"

    def CreateControls(self, propGrid, aProperty, pos, size):
        buttons = wxpg.PGMultiButton(propGrid, size)
        # Add regular buttons
        buttons.Add(wx.ArtProvider.GetBitmap(wx.ART_FILE_OPEN))  # button id 0
        buttons.Add(wx.ArtProvider.GetBitmap(wx.ART_CROSS_MARK))  # button id 1

        wnd = super(TestEditor, self).CreateControls(propGrid, aProperty, pos, buttons.GetPrimarySize())
        # Finally, move buttons-subwindow to correct position - right hand side of property
        # returned wx.propgrid.PGWindowList contains our custom button list.
        buttons.Finalize(propGrid, pos)
        wnd.SetSecondary(buttons)
        self.btns = buttons
        return wnd

    def OnEvent(self, propGrid, aProperty, ctrl, event):
        # b = propGrid.GetEditorControlSecondary()      # doesn't exist but is in the example
        ret = super(TestEditor, self).OnEvent(propGrid, aProperty, ctrl, event)
        return ret

class MyFrame(wx.Frame):
    def __init__(self, *args, **kw):
        super(MyFrame, self).__init__(*args, **kw)
        self.pg = wxpg.PropertyGrid(self, wx.ID_ANY, wx.DefaultPosition, wx.DefaultSize,
                                    wxpg.PG_DEFAULT_STYLE | wxpg.PG_SPLITTER_AUTO_CENTER, "Test Configuration")

        ed = wxpg.PropertyGrid.GetEditorByName("TestEditor")
        astrprop = wxpg.StringProperty('test3', 'test3', 'xyz')
        self.pg.Append(astrprop)
        astrprop.SetEditor(ed)

        astrprop = wxpg.StringProperty('test1', 'test1', '1234')
        self.pg.Append(astrprop)
        astrprop.SetEditor(ed)

        astrprop = wxpg.StringProperty('test2', 'test2', 'abcd')
        self.pg.Append(astrprop)
        astrprop.SetEditor(ed)

        sizer = wx.BoxSizer(wx.VERTICAL)
        sizer.Add(self.pg, 1, wx.EXPAND)
        self.SetSizer(sizer)

class MyApp(wx.App):
    def OnInit(self):
        initPGEditors()
        self.frm = MyFrame(None, title='test', pos=wx.DefaultPosition, size=(900, 600))
        self.frm.Show(True)
        self.SetTopWindow(self.frm)
        return True

app = MyApp()
app.MainLoop()

[crash.py.txt](https://github.com/wxWidgets/Phoenix/files/4828957/crash.py.txt)

**Comment by swt2c** [comment]
#1697 should fix this.  BTW, you also should not need to store the buttons after this fix.
