### ISSUE TITLE
wxPython installed on Ubuntu 20.04 LTS fails to import in Python 3.8

### ISSUE THREAD

**Issue by mwyngloddwr** [wxWidgets/Phoenix#1720]
**Operating system**:  Windows 10 Pro 18363.900 Ubuntu 20.04 LTS installed from Windows Store.

ian@ifg:~$ cat /etc/issue
Ubuntu 20.04 LTS \n \l

**wxPython version & source**:          wxPython-4.1.0-cp38-cp38-linux_x86_64.whl
                                                             https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-20.04/

**Python version & source**:         Python 3.8.2 (default, Apr 27 2020, 15:53:34)  

**Description of the problem**:  

The following is a copy of the code I used, apparently successfully, to install wxPython.  It is subsequently listed in the Python modules.  But when I attempt to import the module, earlier versions of which I have successfully used in my own Python apps/modules, I get the error message that it fails to import, apparently because of a missing socket file in the wx modules included in my site-packages. 

**ian@ifg:~$ sudo pip3 install /mnt/c/Users/ian/Desktop/wxPython-4.1.0-cp38-cp38-linux_x86_64.whl

Processing /mnt/c/Users/ian/Desktop/wxPython-4.1.0-cp38-cp38-linux_x86_64.whl**
Requirement already satisfied: numpy; python_version >= "3.0" in /usr/local/lib/python3.8/dist-packages (from wxPython==4.1.0) (1.19.0)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from wxPython==4.1.0) (1.14.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.8/dist-packages (from wxPython==4.1.0) (7.2.0)
Installing collected packages: wxPython
Successfully installed wxPython-4.1.0

ian@ifg:~$ python3
Python 3.8.2 (default, Apr 27 2020, 15:53:34)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> import wx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "/usr/local/lib/python3.8/dist-packages/wx/core.py", line 12, in <module>
    from ._core import *
ImportError: libgtk-3.so.0: cannot open shared object file: No such file or directory
>

I have previously used successfully an earlier wx version tarball to build a .whl for Ubuntu 18.04 LTS but I have been unable so far to install the required additional dependency packages on 20.04 because I am unfamiliar with the new snap installations. 

```python
![Windows 10 Ubuntu 20 04 LTS - wxPython 4 1 0  installation fails to import](https://user-images.githubusercontent.com/51515752/87068860-1d973180-c20e-11ea-8ce4-b494e5b875ce.png)
# Put code sample here
```

**Comment by swt2c** [comment]
Try installing `libgtk-3-0` with apt:
```
apt install libgtk-3-0
```

**Comment by mwyngloddwr** [comment]
Thank you swt2c for pointing me in the right direction.  There were in fact 3 misssing dependencies on this platform: libgtk-3.so.0 in package libgtk-3-0; libSDL2-2.0.so.0 in package libsdl2-2.0-0; and libnotify.so.4 in package libnotify4.  My initial failure was because I could not install or find 'gtk'.  Your prompt led me to search for, find and install apt-file which enabled me to identify the 3 packages containing the dependencies using 'apt-file search' - something if I once knew how to do, I'd forgotten.  Once these were installed using apt the wx module imported without problem.  I am most grateful.
