### ISSUE TITLE
SVGimage.CreateFromBytes changes angle brackets in input string object to null-bytes

### ISSUE THREAD

**Issue by suurjaak** [wxWidgets/Phoenix#1727]
After calling `wx.svg.SVGimage.CreateFromBytes`, the given input string no longer has the same value. Somehow, the string object has been modified in-place, with angle brackets and some other characters changed to \0, even though Python strings are immutable.

Sample application:

    import wx.svg

    s = '<svg height="26" width="26"></svg>'
    print('before: %r' % s)
    wx.svg.SVGimage.CreateFromBytes(s)
    print('after:  %r' % s)

Output:

    before: '<svg height="26" width="26"></svg>'
    after:  '\x00svg\x00height\x00"26\x00 width\x00"26\x00\x00\x00/svg\x00'

Python version: 2.7.18.
wx version: 4.1.0 (wxWidgets 3.1.4).

**Comment by swt2c** [comment]
Perhaps this is a Python 2 specific problem (which may not likely be fixed?).  Your example works fine on Python 3, although you have to change it slightly to provide bytes:

```
s = b'<svg height="26" width="26"></svg>'
print('before: %r' % s)
wx.svg.SVGimage.CreateFromBytes(s)
print('after:  %r' % s)
```

```
before: b'<svg height="26" width="26"></svg>'
after:  b'<svg height="26" width="26"></svg>'
```

**Comment by suurjaak** [comment]
Nope, not a Python 2 specific problem. Same result with the latest Python 3.8.4:

```python
import wx.svg

s = b'<svg height="26" width="26"></svg>'
print('before: %r' % s)
wx.svg.SVGimage.CreateFromBytes(s)
print('after:  %r' % s)
```

Output:

```python
before: b'<svg height="26" width="26"></svg>'
after:  b'\x00svg\x00height\x00"26\x00 width\x00"26\x00\x00\x00/svg\x00'
```

Tested both on Windows and Linux, both 32-bit and 64-bit. Same result.

---

Looking at wxPython source code, it's using the Nano SVG library, that actually warns about this (from `ext\nanosvg\src\nanosvg.h`):

```c
// Parses SVG file from a null terminated string, returns SVG image as paths.
// Important note: changes the string.
NSVGimage* nsvgParse(char* input, const char* units, float dpi);
```

Which uses `nsvg__parseXML`, and indeed, it modifies the string in-place (from `ext\nanosvg\src\nanosvg.h`):

```c
int nsvg__parseXML(char* input,
    void (*startelCb)(void* ud, const char* el, const char** attr),
    void (*endelCb)(void* ud, const char* el),
    void (*contentCb)(void* ud, const char* s),
    void* ud)
{
  char* s = input;
  char* mark = s;
  int state = NSVG_XML_CONTENT;

  while (*s) {
    if (*s == '<' && state == NSVG_XML_CONTENT) {
      // Start of a tag
      *s++ = '\0';
    ..
```

And `SVGImage.CreateFromBytes` invokes `nsvgParse` directly with the string (from `wx\svg\_nanosvg.pyx`):

```python
def CreateFromBytes(cls, bytes buffer, str units='px', float dpi=96):
    units_b = units.encode('utf-8')
    cdef SVGimageBase img = cls()
    img._set_ptr(nsvgParse(buffer, units_b, dpi),
                 'Unable to parse SVG buffer')
    return img
```

**Comment by swt2c** [comment]
Strange.  I definitely don't see it on Linux with Python 3.8.3 on Fedora.  I'm using the latest development branch, but I don't think anything nanosvg related has been changed?

**Comment by RobinD42** [comment]
@mesalu made some changes last month to "preserve bytes immutability". See https://github.com/wxWidgets/Phoenix/commit/ecb78f75b129639e5e749fcc0f8f8610c6ed5c16#diff-87985e7096dcc2a499b7ce0cd503484e

**Comment by RobinD42** [comment]
Here is the merge commit for the full change: 3923a16606b2523c0ae4d08bb1635a02da9fc0c8

**Comment by swt2c** [comment]
> @mesalu made some changes last month to "preserve bytes immutability". See ecb78f7#diff-87985e7096dcc2a499b7ce0cd503484e

Thank you for explaining why I didn't see the problem.  :-)
