### ISSUE TITLE
ComboCtrl can't dropdown with mouse

### ISSUE THREAD

**Issue by wossx** [wxWidgets/Phoenix#1731]
**Operating system**:  Windows 7
**wxPython version & source**:          wxPython-4.1.1a1.dev4883+75f1081f-cp38-cp38-win32.whl
**Python version & source**:            stock 3.8

**Description of the problem**:
The last wxWidgets reference update messed up the ComboCtrl mouse dropdown. The F4 works.
You can try it in the demo/ComboCtrl.

**Comment by Metallicow** [comment]
yep, It appears to have broke.

**Comment by swt2c** [comment]
File a wxWidgets bug.  https://trac.wxwidgets.org/

**Comment by wossx** [comment]
[https://trac.wxwidgets.org/ticket/18844](url)
