### ISSUE TITLE
wx.lib.intctrl.IntCtrl and wx.lib.agw.floatspin.FloatSpin do not override Value-property

### ISSUE THREAD

**Issue by suurjaak** [wxWidgets/Phoenix#1734]
`IntCtrl.SetValue(123)` works as it should, but `IntCtrl.Value = 123` fails, because the `Value` property has not been overridden in IntCtrl and thus falls back to the `TextEntry.SetValue` setter.

Ditto wx.lib.agw.floatspin.FloatSpin.

Sample app:

```python
import wx, wx.lib.intctrl

app = wx.App()
frame = wx.Frame(None)

c = wx.lib.intctrl.IntCtrl(frame)
c.SetValue(123)
c.Value = 123

frame.Show()
app.MainLoop()
```

Output:

    Traceback (most recent call last):
      File "test.py", line 8, in <module>
        c.Value = 123
    TypeError: TextEntry.SetValue(): argument 2 has unexpected type 'int'

**Comment by RobinD42** [comment]
PRs are welcome

**Comment by suurjaak** [comment]
Will do. 

Question: I notice there are a number of getters and setters in IntCtrl and FloatCtrl, like GetMin-GetMax etc. Is it okay if I define properties for those as well?

**Comment by RobinD42** [comment]
> Question: I notice there are a number of getters and setters in IntCtrl and FloatSpin, like GetMin-GetMax etc. Is it okay if I define properties for those as well?

Sorry, I didn't see the question before. I'm okay with adding properties, especially if they are similar to what is implemented elsewhere in wxPython. Just make sure that the property doesn't hide something in the base classes which means something different.
