### ISSUE TITLE
Drag & Drop result always wx.DragNone

### ISSUE THREAD

**Issue by DietmarSchwertberger** [wxWidgets/Phoenix#1737]
**Operating system**:  Windows 10, 64 bit
**wxPython version & source**:          wxPython 4.1.0 msw (phoenix) wxWidgets 3.1.4      from Pypi
**Python version & source**:            stock 3.6.4 32 bit, stock 3.6.4 64 bit

**Description of the problem**: 

`DropTarget.OnDragOver` correctly receives wx.DragMove and wx.DragCopy

But `DropTarget.OnData` always receives `wx.DragCancel` and also `DoDragDrop` does always return `wx.DragNone` .

See attached program.

[2020-07-21_DragDrop.py.txt](https://github.com/wxWidgets/Phoenix/files/4955524/2020-07-21_DragDrop.py.txt)

Result with 4.0.1 is OK:
```
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:38:48) [MSC v.1900 32 bit (Intel)]
wxPython 4.0.1 msw (phoenix)
Start dragging
OnDragOver: wx.DragMove
...
OnDragOver: wx.DragMove
OnDragOver: wx.DragMove
OnData: wx.DragMove
result: wx.DragMove
```

Result with wxPython 4.1.0:
```
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)]
wxPython 4.1.0 msw (phoenix) wxWidgets 3.1.4
Start dragging
OnDragOver: wx.DragMove
...
OnDragOver: wx.DragMove
OnData: wx.DragNone
result: wx.DragNone
```

**Comment by DietmarSchwertberger** [comment]
The result is alwo wx.DragNone between applications.

**Comment by DietmarSchwertberger** [comment]
Well, DoDragGrop will return the value that OnData returns.
So as workaround I use the latest value from OnDragOver.

**Comment by swt2c** [comment]
How do you 'Move' vs 'Copy'?  I see 'Copy' when I drag.

**Comment by DietmarSchwertberger** [comment]
On Windows Move is the default. Switching can be done via Ctrl key.

**Comment by DavidStirling** [comment]
Can confirm that we're also seeing this problem on Windows, specifically with v4.1.0

**Comment by RobinD42** [comment]
This has already been fixed. Please try a 4.1.1 snapshot build.
