### ISSUE TITLE
Failed to install wxPython on NVIDIA Ubuntu port on ARM x64

### ISSUE THREAD

**Issue by LumaRay** [wxWidgets/Phoenix#1740]
Hello.

I'm trying to install wxPython on NVIDIA Jetson Nano, which has Ubuntu preinstalled.

The architecture is ARMv8 x64.

Python 3.6

Ubuntu 18.04LTS

I get this error:

```
    Checking for header Python.h                    : Distutils not installed? Broken python installation? Get python-config now!
    The configuration failed
```

Complete log: [ARMx64-wxPython.txt](https://github.com/wxWidgets/Phoenix/files/4964281/ARMx64-wxPython.txt)

**Comment by LumaRay** [comment]
```
jure@jure-desktop:~$ python-config
Usage: /usr/bin/python-config --prefix|--exec-prefix|--includes|--libs|--cflags|--ldflags|--extension-suffix|--help|--configdir
```

**Comment by swt2c** [comment]
I think that you are missing the `python3-dev` Ubuntu package.  `python-config` is for Python 2.

**Comment by LumaRay** [comment]
Thanks! That helped!
