### ISSUE TITLE
wx.LC_HRULES on Virtual ListCtrl makes other elements not render

### ISSUE THREAD

**Issue by martijnalexion** [wxWidgets/Phoenix#1741]
**Operating system**: Windows 10.19042 64-bit
**wxPython version & source**:          4.1.0 from pypi
**Python version & source**:            Python 2.7.11 from Windows installer 32-bit

**Description of the problem**:
On a Virtual ListCtrl. If you add the style wx.LC_HRULES and the listview is partically outside of the screen. 
All the other elements dont render properly.

![image](https://user-images.githubusercontent.com/58816160/88285485-74613880-ccef-11ea-861f-c03356336178.png)

```python
import string
import random
import wx


class ListCtrl(wx.ListCtrl):
	def OnGetItemText(self, item, column):
		return random.choice(string.ascii_letters) * 3


app = wx.App()
dialog = wx.Dialog(None, size=(250, 250))
panel = wx.Panel(dialog)
listctrl = ListCtrl(panel, style=wx.LC_VRULES|wx.LC_HRULES|wx.LC_REPORT|wx.LC_VIRTUAL, size=(1000, 100), pos=(10, 20))
listctrl.AppendColumn("Column #1")
listctrl.AppendColumn("Column #2")
listctrl.AppendColumn("Column #3")
listctrl.AppendColumn("Column #4")
listctrl.AppendColumn("Column #5")
listctrl.SetItemCount(200)

label = wx.StaticText(panel, label="Test", pos=(0, 0))
textctrl = wx.TextCtrl(panel, size=(200, 20), pos=(50, 0))
textctrl.SetValue("Drrrrr")
dialog.Show()
app.MainLoop()

```

**Comment by swt2c** [comment]
One problem I see: your ListCtrl is bigger than your Dialog.  Your Dialog is 250x250 and your ListCtrl is 1000x100.  Your ListCtrl doesn't fit within the Dialog.

**Comment by martijnalexion** [comment]
That's the point. If I adjust the ListCtrl to fit inside the dialog the problem doesn't show.
BTW: This also happens when you put everything on a Scrolledpanel.

If a part of the ListCtrl falls outside the Dialog, all other elements don't render properly.
Like the StaticText with Test & the TextCtrl with Drrrr.
If you remove the style wx.LC_HRULES from the ListCtrl, everything works.

This is what it should look like. This is **without** the wx.LC_HRULES style.
![image](https://user-images.githubusercontent.com/58816160/88302279-f3fa0200-cd05-11ea-83ea-f40692e96f5d.png)

This is with the wx.LC_HRULES:
![image](https://user-images.githubusercontent.com/58816160/88302476-2e639f00-cd06-11ea-9102-027f8d45501d.png)

**Comment by swt2c** [comment]
Okay, I understand now.

This doesn't seem to be something specific to wxPython itself but rather behavior of the underlying C++ library, wxWidgets.  I would encourage you to open a wxWidgets bug at https://trac.wxwidgets.org/.

**Comment by martijnalexion** [comment]
Posted it on wxWidgets (https://trac.wxwidgets.org/ticket/18850). 
Closing this issue for now.
