### ISSUE TITLE
FloatCanvas GUIMode GUIZoomIn and GUIZoomOut not zooming properly

### ISSUE THREAD

**Issue by DKWoods** [wxWidgets/Phoenix#1753]
Operating System:  All
wxPython 4.1.1a1.dev4867

Compared to wxPython 3.0.2.0, the FloatCanvas GUIModes of GUIZoomIn and GUIZoomOut do not function correctly when you click in a FloatCanvas.  Specifically, GUIZoomOut does not actually zoom out, and it changes the image center.

At some point, the FloatCanvas.py Zoom method was changed from expecting the centerCoords parameter as either "world" or "pixels" to expecting either "World" or "Pixels".  In the GUIMode.py file, GUIZoomIn and GUIZoomOut still use the old, all-lower-case form for this parameter, specifying "pixel" rather than "Pixel".

**Comment by swt2c** [comment]
To me, it looks like the capitalization change was accidental in 8304c859f8e0ff0408c8c367c25f4ea4a28559c2.  After all, the documentation for `Zoom()` still shows lower case.  It seems like at the very least the documentation should be changed too, or perhaps even better, maybe `Zoom()` should just call .lower() on the centerCoords and thus could be case-insensitive?
