### ISSUE TITLE
dataview DataViewSpinRenderer SystemError

### ISSUE THREAD

**Issue by shadowxy1** [wxWidgets/Phoenix#1756]
**Operating system**: Windows 7
**wxPython version**: pip install wxpython 4.1.0
**Python version & source**: 3.8.1 32bit

Description of the problem:
Too verify the behaviour of my app, i replaced the following code in demo ("DVC_CustomRenderer" line 149).
In version 4.0.7 everything works fine.

```python
col = self.dvc.AppendTextColumn("Id", 0, width=40)
col.Alignment = wx.ALIGN_RIGHT
col.MinWidth = 40
```

to

```python
col = self.dvc.AppendColumn(dv.DataViewColumn("Id", dv.DataViewSpinRenderer(0, 1000), 0, width=40))
```

and i get the following error (in demo and app):

SystemError: PyEval_EvalFrameEx returned a result with an error set
wx._core.wxAssertionError: C++ assertion ""Assert failure"" failed at ..\..\src\
common\variant.cpp(393) in wxVariant::GetLong(): Could not convert to a long

The above exception was the direct cause of the following exception:

SystemError: PyEval_EvalFrameEx returned a result with an error set

**Comment by swt2c** [comment]
I can confirm this.  I think the problem is technically there in 4.0.7 but 4.1.0 has the assert.

**Comment by RobinD42** [comment]
There's actually a helpful log message on macOS that may not be there in the generic version of the DVC used on Windows:

```
06:28:28 PM: Debug: Wrong type returned from the model for column 0: long required but actual type is string
```

So what's happening is that the `DataViewSpinRenderer` wants to get integer (long) values from the model, but the model is providing the values for that column as strings. Changing this method in the demo's `TestModel` class fixes your example:

```python
    def GetValueByRow(self, row, col):
        val = self.data[row][col]
        if col == 0:
           return int(val)
        return val
```
