### ISSUE TITLE
Propertygrid password string not working

### ISSUE THREAD

**Issue by LumaRay** [wxWidgets/Phoenix#1760]
Hello!
I'm trying to add password string property this way:
```
        pr = wx.propgrid.StringProperty(label="Пароль", name=self.S_NORMAL_PASSWORD, value="123456")
        pr.SetAttribute(wx.propgrid.PG_STRING_PASSWORD, True)
        self.property_grid_1.Append(pr)
```
But for some reason this leads to the window not showing at all. I have debugged this and found that the execution stops at `pr.SetAttribute(wx.propgrid.PG_STRING_PASSWORD, True)` and no error is shown in the debug output.
`pr.SetAttribute(wx.propgrid.PG_STRING_PASSWORD, 1)` has the same effect.
Using `pr.SetAttribute(wx.propgrid.PG_PROP_PASSWORD, True)` leads to "TypeError: PGProperty.SetAttribute(): argument 1 has unexpected type 'int'"

**Comment by RobinD42** [comment]
Have you compared what you are doing with what's in the demo's `PropertyGrid` module?

**Comment by LumaRay** [comment]
Well in wxWidgets' Samples I have found this:
```
    // Password property example.
    pg->Append( new wxStringProperty("Password",wxPG_LABEL, "password") );
    pg->SetPropertyAttribute( "Password", wxPG_STRING_PASSWORD, true );
    pg->SetPropertyHelpString( "Password",
        "Has attribute wxPG_STRING_PASSWORD set to true" );
```
As far as I understand, this is the same as I do, except that I refer to a property by its instance rather than by a name.

**Comment by swt2c** [comment]
I see the problem - there's an assert happening if you create a wxStringProperty and then try to change the password attribute BEFORE the property has been added to a wxPropertyGrid.  I don't know if that's supposed to be supported or not.  Is there a reason why you can't Append the property first and THEN set the password attribute?

**Comment by LumaRay** [comment]
Thanks @swt2c setting the attribute after appending the property to the propertygrid worked for me.
