### ISSUE TITLE
Demo ArtProvider failed

### ISSUE THREAD

**Issue by Nutznieser** [wxWidgets/Phoenix#1768]
**Operating system**: Windows 10
**wxPython version & source**: Newest from Github        
**Python version & source**: Python 3.8           

**Description of the problem**:
If I run the wxPython demo, the `ArtProvider` failed with an error. See snapshot.
The error is raising since version `wxPython-4.1.1a1.dev4919+57702fa7`. In earlier versions all works well.

![pythonw_2020-08-12_11-52-43](https://user-images.githubusercontent.com/24735031/90002035-68371e00-dc92-11ea-855b-a60a5e025be7.png)

**Comment by swt2c** [comment]
This is because the wx.ART_XXX ID's changed in wxWidgets.  @StefanBruens seems to be working on a solution: https://github.com/wxWidgets/wxWidgets/pull/1996
