### ISSUE TITLE
wxpython version 4.1.0 demo missing file version.py

### ISSUE THREAD

**Issue by Larz60p** [wxWidgets/Phoenix#1771]
**Operating system**: Linux Mint Cinnamon 19
**wxPython version & source**:  4.1.0
**Python version & source**:  3.8.3 python.org

**Description of the problem**: 
missing version.py file.
trying to run produces missing module error

with virutal environment activated (snippit only to show version installed):
>>> import wx
>>> wx.version()
'4.1.0 gtk3 (phoenix) wxWidgets 3.1.4'
>>> quit()

from command line:

(venv) src$ cd Phoenix4.1.0/demo/
(venv) demo$ python demo.py

Traceback (most recent call last):
  File "demo.py", line 3, in <module>
    import Main
  File "/media/captainkirk/Trailmapper/Trailmapper/Illinois/src/Phoenix4.1.0/demo/Main.py", line 75, in <module>
    import version
ModuleNotFoundError: No module named 'version'

```python
# Put code sample here
```

**Comment by Larz60p** [comment]
Temporary fix (until version.py found)

in main.py
comment out line 75 # import version

comment out lines 2679 - 2683 (MyApp)

        # if LooseVersion(version.VERSION_STRING) != LooseVersion(wx.VERSION_STRING):
        #     wx.MessageBox(caption="Warning",
        #                   message="You're using version %s of wxPython, but this copy of the demo was written for version %s.\n"
        #                   "There may be some version incompatibilities..."
        #                   % (wx.VERSION_STRING, version.VERSION_STRING))

**Comment by Metallicow** [comment]
@Larz60p see https://github.com/wxWidgets/Phoenix/pull/1690
Use a snapshot version until 4.1.1 or comment out the code as you have done.
@RobinD42 fixed this. This can be closed.

**Comment by electricalgorithm** [comment]
Same problem continues.
