### ISSUE TITLE
demo.py: the module version is deprecated for python3?

### ISSUE THREAD

**Issue by SwaySZ** [wxWidgets/Phoenix#1791]
**Operating system**:
**wxPython version & source**:          
**Python version & source**:            

**Description of the problem**:

```python
# Put code sample here
```
python3  ModuleNotFoundError: No module named 'version'

**Comment by RobinD42** [comment]
The file `demo/version.py` is now generated as part of the build, so you're probably using a version direct from git, or using the demo archive from the 4.1.0 release (IIRC) which forgot to include the file. I suggest getting the demo archive from one of the recent snapshot builds or you can just add the file yourself. It just needs to contain a line like: `VERSION_STRING = "4.1.0"`.

Also, see #1711 and #1690 (Always search for existing issues!) :-)
