### ISSUE TITLE
Problem with wx.SVG

### ISSUE THREAD

**Issue by MrVasilii** [wxWidgets/Phoenix#1798]
**Operating system**: Win7 x64
**wxPython version & source**:          4.1.0
**Python version & source**:            Python 3.7.8

**Description of the problem**:

Why wx.svg can't see tag <text> on SVG file?

Code SVG file:

```
<?xml version="1.0" encoding="utf-8" ?>
<svg baseProfile="tiny" height="200px" version="1.2" width="500px" xmlns="http://www.w3.org/2000/svg" xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:xlink="http://www.w3.org/1999/xlink"><defs /><rect fill="white" height="195" rx="20" ry="20" stroke="black" stroke-width="5" width="495" x="2" y="2" /><text fill="black" font-family="sans-serif" font-size="115pt" text-anchor="middle" x="250" y="152.0">PIP</text></svg>
```

**Comment by RobinD42** [comment]
I assume you mean the text tag...

The nanosvg library that the SVG support is built upon does not support text elements in a SVG file, however you can load the file into a SVG editor and convert the text to a path or shape. Here is how to do it in the free BoxySVG editor: https://www.youtube.com/watch?v=SkZR_9nI9k0
