### ISSUE TITLE
Building wxPython for Jetson Nano (Ubuntu 18.04 aarch64)

### ISSUE THREAD

**Issue by LumaRay** [wxWidgets/Phoenix#1800]
Hello.

As wxPython 4.1.0 has troubles with PropertyGrid on Ubuntu 18.04, I try to get its 4.1.1a1 update installed on x86_64 and aarch64 platforms.

I have managed to build it on x86_64 Ubuntu using something like:

```
sudo apt install dpkg-dev build-essential python3.6-dev and libpython3.6-dev freeglut3-dev libgl1-mesa-dev libglu1-mesa-dev libgstreamer-plugins-base1.0-dev libgtk-3-dev libjpeg-dev libnotify-dev libpng-dev libsdl2-dev libsm-dev libtiff-dev libwebkit2gtk-4.0-dev libxtst-dev doxygen python-requests python-setuptools python-pip
pip install python-config
cd ~
git clone https://github.com/wxWidgets/Phoenix
cd ~/Phoenix
git submodule update --init --recursive
python3 build.py dox etg --nodoc sip build
sudo python3 build.py install
```

However this doesn't seem to work on aarch64...
The doxygen and sip from Phoenix fail to work on aarch64: https://wxpython.org/Phoenix/tools/
Those seem to be compiled for x86_64 only...
I have managed to build doxygen on aarch64 using this command:
```
cd ~
git clone https://github.com/doxygen/doxygen.git
cd doxygen
mkdir build
cd build
cmake -G "Unix Makefiles" ..
make
make install
export DOXYGEN=~/doxygen/build/bin/doxygen
```
However I'm stuck with building sip...
```
jure@jure-desktop:~/Phoenix$ sudo python3 build.py --nodoc sip
Will build using: "/usr/bin/python3"
3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0]
Python's architecture is 64bit
cfg.VERSION: 4.1.1a1

Running command: sip
Checking for /home/jure/Phoenix/bin/sip-4.19.24-linux64...
ERROR: Could not execute /home/jure/Phoenix/bin/sip-4.19.24-linux64, got "[Errno 8] Exec format error: '/home/jure/Phoenix/bin/sip-4.19.24-linux64'"
       Set SIP in the environment to use a local build of sip instead
Finished command: sip (0.75s)
```
I just don't understand how to build the executable that wxPython's build script uses...
I have found only how to build python package of sip...
Please help! I need clear instructions how to build sip-4.19.24-linux64 for aarch64

**Comment by LumaRay** [comment]
I have just done this:
```
cd ~
wget "https://www.riverbankcomputing.com/static/Downloads/sip/4.19.24/sip-4.19.24.tar.gz"
tar -zxf sip-4.19.24.tar.gz
cd sip-4.19.24/
sudo python3 configure.py
sudo make
sudo make install
export SIP=~/sip-4.19.24/sipgen/sip
```
But still I get this error:
```
ERROR: Could not execute /home/jure/Phoenix/bin/sip-4.19.24-linux64, got "[Errno 8] Exec format error: '/home/jure/Phoenix/bin/sip-4.19.24-linux64'"
       Set SIP in the environment to use a local build of sip instead
```
I don't get it: why export SIP doesn't work?

**Comment by LumaRay** [comment]
Just tried this:
`mv /tmp/sip-4.19.24/sipgen/sip /home/jure/Phoenix/bin/sip-4.19.24-linux64`
But then got:
```
jure@jure-desktop:~/Phoenix$ sudo python3 build.py --nodoc sip
Will build using: "/usr/bin/python3"
3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0]
Python's architecture is 64bit
cfg.VERSION: 4.1.1a1

Running command: sip
Checking for /home/jure/Phoenix/bin/sip-4.19.24-linux64...
ERROR: MD5 mismatch, got "137353c44cd01c57a64f385a8b590532"
       expected          "b44a45191f5f84db10e2ba1c4cecd8ff"
       Set SIP in the environment to use a local build of sip instead
Finished command: sip (0.71s)
```

**Comment by LumaRay** [comment]
Changed linux64 md5 checksum in build.py:95
```
sipMD5 = {
    'darwin'   : '2a22cb7a35eb14384b0829593a366c29',
    'win32'    : '49e0aa36397d7629fea95418452961fb',
    'linux32'  : 'ea773f6fd92d5f23530730428a86df2f',
    'linux64'  : '137353c44cd01c57a64f385a8b590532',
}
```
IT FINALLY STARTED BUILDING!

**Comment by swt2c** [comment]
Glad that you got it working.  Setting the SIP environment variable should have worked, though.  Perhaps it didn't because you used `sudo`?  You don't need root privileges to build wxPython.

**Comment by LumaRay** [comment]
I've tried both sudo and non-sudo export SIP, no luck, it didn't want to "see" it there.
This is strange of course...
Finally I have successfully built and installed wxPython for aarch64 using
```
python3 build.py dox etg --nodoc sip build
sudo python3 build.py install
```
And it works!

**Comment by RobinD42** [comment]
Unless you need to make changes you should be able to do the build without `doxygen` and `sip` simply by using the source tarball[1] instead of a git checkout, and not doing the `dox`, `etg`, or `sip` commands on the `build.py` command line.

[1] IOW, the source archive from a release on pypi, or one from a snapshot build [here](https://wxpython.org/Phoenix/snapshot-builds/).
