### ISSUE TITLE
Updating wxWidgets with commit 55feac3de breaks compilation with gcc errors  "expected id-expression before ‘(’ token"

### ISSUE THREAD

**Issue by jackL999** [wxWidgets/Phoenix#1802]
**Operating system**:
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS

**gcc version**:  9.3.0 (Ubuntu 9.3.0-10ubuntu2)
**wxPython version & source**:        commit 47c4a913d3aa3c6523cad05df0997677c08fc4b9
**Python version & source**:            Python 3.8.2 

**Description of the problem**:
Updating wxWidgets with commit 55feac3de breaks compilation with gcc errors  "expected id-expression before ‘(’ token"
This seems to be due to a known problem described here https://github.com/wxWidgets/wxWidgets/pull/1996 with a proposed solution given here 
https://github.com/wxWidgets/wxWidgets/commit/79c98b31a4bd4975a5d4038df5765882775fae02

gcc version 9.3.0 (Ubuntu 9.3.0-10ubuntu2) errors
In file included from ../../../../sip/cpp/sip_corecmodule.cpp:264:
../../../../sip/cpp/sip_corecmodule.cpp: In function ‘PyObject* PyInit__core()’:
../../../../ext/wxWidgets/include/wx/artprov.h:33:44: error: expected id-expression before ‘(’ token
   33 | #define wxART_MAKE_ART_ID(id)              (#id)
      |                                            ^
../../../../ext/wxWidgets/include/wx/artprov.h:55:36: note: in expansion of macro ‘wxART_MAKE_ART_ID’
   55 | #define wxART_ADD_BOOKMARK         wxART_MAKE_ART_ID(wxART_ADD_BOOKMARK)
      |                                    ^~~~~~~~~~~~~~~~~
../../../../sip/cpp/sip_corecmodule.cpp:19958:67: note: in expansion of macro ‘wxART_ADD_BOOKMARK’
19958 |     sipAddTypeInstance(sipModuleDict,sipName_ART_ADD_BOOKMARK,& ::wxART_ADD_BOOKMARK,sipType_wxString);
      |                                                                   ^~~~~~~~~~~~~~~~~~
../../../../ext/wxWidgets/include/wx/artprov.h:31:44: error: expected id-expression before ‘(’ token
   31 | #define wxART_MAKE_CLIENT_ID(id)           (#id "_C")
      |                                            ^
../../../../ext/wxWidgets/include/wx/artprov.h:46:36: note: in expansion of macro ‘wxART_MAKE_CLIENT_ID’
   46 | #define wxART_BUTTON               wxART_MAKE_CLIENT_ID(wxART_BUTTON)

**Comment by swt2c** [comment]
Are you sure that you rebuilt wxWidgets and wxPython cleanly?  I was able to just build 47c4a913d3aa3c6523cad05df0997677c08fc4b9 fine.  Also, the CI builds seem to have worked as well.
