### ISSUE TITLE
Update / track wxWidgets 3.1.4

### ISSUE THREAD

**Issue by NicklasTegner** [wxWidgets/Phoenix#1809]
Basically title. wxWidgets 3.1.4 was released on 22. jul. 2020 with some really nice features and fixes that will surely futureproof phoenix and wx widgets.

**Comment by swt2c** [comment]
wxPython master branch already is tracking 3.1.4+...

**Comment by NicklasTegner** [comment]
so, when a new version of wxpython comes out, it will use 3.1.4 or?

**Comment by swt2c** [comment]
Yes.  You can try out the snapshot builds (or build it yourself) if you want to try it now.

**Comment by Metallicow** [comment]
just wait..... we are all human......
