### ISSUE TITLE
wx.lib.mixins is missing ?

### ISSUE THREAD

**Issue by TonyFlury** [wxWidgets/Phoenix#1814]
**Operating system**: Ubuntu 19.10
**wxPython version & source**:        4.1.0 from pypi
**Python version & source**:            Python 3.7 - stock - apt-get install python3.7
**Description of the problem**:

Following the documentation at [4.1.0 - wx.lib.mixins.rubberband](https://docs.wxpython.org/wx.lib.mixins.rubberband.html?highlight=rubberband#module-wx.lib.mixins.rubberband)

But on my stock wxPython installation wx.lib does not have a mixins modules at all :

Traceback : 
```
 File "/home/tony/Development/python/Fractal Explorer/fractalexplorer/floatCanvas.py", line 31, in <module>
    class FloatCanvas(wx.lib.mixins.rubberband, wx.lib.floatcanvas.FloatCanvas.FloatCanvas):
AttributeError: module 'wx.lib' has no attribute 'mixins'
```
Is it my installation or am I doing something wrong ?

**Comment by infinity77** [comment]
Hi,

It seems to me that the mixins folder is there, at least on GitHub. Is it possible that you’re invoking an older version of Phoenix/wxPython?

**Comment by TonyFlury** [comment]
It is definitely 4.10 
- output from ```pip list```:
```
Package                       Version   Location                                      
----------------------------- --------- ----------------------------------------------
---   
wheel                         0.34.2    
wxPython                      4.1.0     
zipp                          3.2.0     
```
I have resolved the issue though - so thank you for your help - I had to explicitly import the class i needed. doing a ```import wx``` was enough for me to access ```wx.lib```, but not ```wx.lib.mixins``` - odd but now solved.
