### ISSUE TITLE
Update bundled wxWidgets to upstream Master

### ISSUE THREAD

**Issue by imciner2** [wxWidgets/Phoenix#1816]
**Operating system**:
**wxPython version & source**:          Master branch

**Description of the problem**:

Can the included version of wxWidgets inside ext/ be bumped to the current wxWidgets master? The bundled version is in the awkward point between when the EGL canvas was added and the option to disable the EGL canvas using configure was added - so it is forcing the EGL canvas which breaks some downstream programs.

**Comment by RobinD42** [comment]
I think I was already doing it at about the same time you filed this issue. 😃
