### ISSUE TITLE
python interpreter crashing instead of getting PyNoAppError

### ISSUE THREAD

**Issue by remdragon** [wxWidgets/Phoenix#182]
Phoenix is crashing the interpreter, and when I boiled my code down to the bare minimum I discovered it was an issue where I was catching an exception and then trying to display it in a MessageDialog before I had created the wx.App object.

Attached is the result of the code simplification.

Here's is the program's output from wxPython-classic:

3.0.2.0 msw (classic)
Traceback (most recent call last):
  File "crash_phoenix.py", line 6, in <module>
    dlg = wx.MessageDialog ( parent=None, message='boom', caption='Crash', style=wx.OK|wx.ICON_ERROR )
  File "C:\Python27\lib\site-packages\wx-3.0-msw\wx_windows.py", line 3631, in **init**
    _windows_.MessageDialog_swiginit(self,_windows_.new_MessageDialog(_args, *_kwargs))
wx._core.PyNoAppError: The wx.App object must be created first!

However, when run from phoenix, it crashes the python interpreter

3.0.3.dev2648+23be602 msw (phoenix)
(crash)

[crash_phoenix.zip](https://github.com/wxWidgets/Phoenix/files/516932/crash_phoenix.zip)

**Comment by RobinD42** [comment]
Royce Mitchell wrote:
>
> Phoenix is crashing the interpreter, and when I boiled my code down to
> the bare minimum I discovered it was an issue where I was catching an
> exception and then trying to display it in a MessageDialog before I
> had created the wx.App object.
>
> Attached is the result of the code simplification.
>
> Here's is the program's output from wxPython-classic:
>
> 3.0.2.0 msw (classic)
> Traceback (most recent call last):
> File "crash_phoenix.py", line 6, in
> dlg = wx.MessageDialog ( parent=None, message='boom', caption='Crash',
> style=wx.OK|wx.ICON_ERROR )
> File "C:\Python27\lib\site-packages\wx-3.0-msw\wx_windows.py", line
> 3631, in *init*
> /windows/.MessageDialog_swiginit(self,/windows/.new_MessageDialog(/args,
> */kwargs))
> wx._core.PyNoAppError: The wx.App object must be created first!
>
> However, when run from phoenix, it crashes the python interpreter
>

Yep, this is a known issue.  I haven't yet worked out how to best
implement that check with the new implementation tech.  It's on the TODO
list though.

-- 
Robin Dunn
Software Craftsman
http://wxPython.org

**Comment by RobinD42** [comment]
Phoenix is now checking for the existence of a wxApp object at appropriate places.
