### ISSUE TITLE
wxCustomDataObject.GetData shouldn't release the GIL

### ISSUE THREAD

**Issue by swt2c** [wxWidgets/Phoenix#1833]
As discovered by @opoplawski in https://github.com/enthought/pyface/issues/784, the `wxCustomDataObject.GetData` method crashes (sometimes?) because it calls `PyMemoryView_FromBuffer` after releasing the GIL.  `GetData` shouldn't release the GIL.

I'll send a PR shortly to fix this.

**Comment by swt2c** [comment]
@opoplawski should be fixed in Fedora in python-wxpython4-4.0.7-11.fc34 which is building now.

**Comment by opoplawski** [comment]
pyface tests run fine now, thanks!

**Comment by swt2c** [comment]
Not a bug in master branch.
