### ISSUE TITLE
Frozen Apps raise exception on write to stdout

### ISSUE THREAD

**Issue by GadgetSteve** [wxWidgets/Phoenix#1834]
**Operating system**: Win10, possibly others
**wxPython version & source**:   4.1.0 msw (phoenix) wxWidgets 3.1.4 from pypi       
**Python version & source**:     3.8 & 3.9        

**Description of the problem**:
If you have stdout.write rather than print statements in your code, _e.g. for outputting information either to a file or the console,_ which is a quite common pattern and then freeze it with CX_Freeze, pyInstaller, or any of the other executable generation tools then when the write occurs **in the built executable only** you will get an exception about None object not having a write method.

Taking the cxFreeze wxPython example as a base:
```python
# Modified wxapp.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import wx
import sys

OUTFILE = sys.stdout # Modification 1

class Frame(wx.Frame):
    def __init__(self):
        wx.Frame.__init__(self, parent=None, title='Hello from cx_Freeze')
        panel = wx.Panel(self)
        closeMeButton = wx.Button(panel, -1, 'Close Me')
        self.Connect(closeMeButton.GetId(), -1, wx.EVT_BUTTON.typeId,
                self.OnCloseMe)
        self.Connect(self.GetId(), -1, wx.EVT_CLOSE.typeId, self.OnCloseWindow)
        pushMeButton = wx.Button(panel, -1, 'Push Me')
        self.Connect(pushMeButton.GetId(), -1, wx.EVT_BUTTON.typeId,
                self.OnPushMe)
        sizer = wx.BoxSizer(wx.HORIZONTAL)
        sizer.Add(closeMeButton, flag=wx.ALL, border=20)
        sizer.Add(pushMeButton, flag=wx.ALL, border=20)
        panel.SetSizer(sizer)
        topSizer = wx.BoxSizer(wx.VERTICAL)
        topSizer.Add(panel, flag=wx.ALL | wx.EXPAND)
        topSizer.Fit(self)

    def OnCloseMe(self, event):
        self.Close(True)

    def OnPushMe(self, event):
        wx.MessageBox('I was pushed!', 'Informational message')
        OUTFILE.write("Button was  pushed!") # Modification 2

    def OnCloseWindow(self, event):
        self.Destroy()


class App(wx.App):
    def OnInit(self):
        frame = Frame()
        frame.Show(True)
        self.SetTopWindow(frame)
        return True


app = App(1)
app.MainLoop()

```

```python
# Setup.py
# -*- coding: utf-8 -*-

# A simple setup script to create an executable running wxPython. This also
# demonstrates the method for creating a Windows executable that does not have
# an associated console.
#
# wxapp.py is a very simple 'Hello, world' type wxPython application
#
# Run the build process by running the command 'python setup.py build'
#
# If everything works well you should find a subdirectory in the build
# subdirectory that contains the files needed to run the application

import sys
from cx_Freeze import setup, Executable

base = None
if sys.platform == 'win32':
    base = 'Win32GUI'

executables = [
    Executable('wxapp.py', base=base)
]

setup(name='hello',
      version='0.1',
      description='Sample cx_Freeze wxPython script',
      executables=executables
      )

```
Build with: `py -3.8 setup.py build_exe` then run the resulting executable and click the push me button.
![image](https://user-images.githubusercontent.com/5593690/97403495-6d4c5680-18ec-11eb-9b39-831c38f9a2cc.png)

Turning on redirection suppresses the error of course.

**Comment by GadgetSteve** [comment]
I suspect, but am not 100% sure _because I do not know what `PyFunctionDef` does_ that this could be addressed by changing wxPhoenix\etg\app.py so that the the default for `stdout` & `stderr` is `os.devnull` rather than `None` but this might need to be addressed in the wx library instead.

**Comment by GadgetSteve** [comment]
After some experimentation it turns out that the App having an `__init__` method which calls `wx.App.__init__` prevents this problem - not sure if this helps or not - maybe a warning on creating a wx>app without an `__init__` method would be enough to resolve the issue.

**Comment by RobinD42** [comment]
FTR, the key point you discovered is probably whether or not the `wx.App.RedirectStdio` method was called. By default that is not done, but it can be turned on by passing `redirect=True` to `wx.App.__init__`.  There should be no need to have an `__init__` in a derived class unless you need it for something else. The inherited `__init__`, or a `app = wx.App(redirect=True)` is sufficient. You can also tell it to redirect to a file if you'd rather have it go there instead of the popup window.

`RedirectStdio` will save the current values of `sys.std[out|err]` so they can be restored later if needed. Now add to that the fact that most freeze tools will do something to `sys.std[out|err]` when building Win32 GUI executables, (like perhaps setting them to `None`) because **there is no console** to attach them to. So if you want to have a valid stdout and stderr even in a frozen GUI app, then you should check for `sys.frozen` and do whatever you need.

**Comment by GadgetSteve** [comment]
Robin,
Thanks for the clarification. As this is an obscure corner case that can be hard to debug I think that I will raise tickets on pyinstaller, cxFreeze, etc., to suggest using sys.std[err|out] = open(os.devnull, 'w') rather than None.
