### ISSUE TITLE
wx.BusyInfo does not stick to parent

### ISSUE THREAD

**Issue by brennmat** [wxWidgets/Phoenix#1835]
**Operating system**: Debian Linux / Gnome-3
**wxPython version & source**: wxPython 4.0 from Debian repositories
**Python version & source**: Python 3 from Debian repositories

**Description of the problem**:
The wx.BusyInfo frame does not "stick" to its parent frame: it does not stay centered on the parent frame, and it does not move with the parent (like a normal modal dialog would). Also, maybe worse, if you bring another application to the front / focus, the BusyInfo stays on top, although it should be covered by the windows of the other application.

Here's the relevant code snipped from my application:
```
# Show busy box while tuning:
with wx.WindowDisabler():
	wait = wx.BusyInfo( "Tuning m/z scale...", parent=self._app.frame_main )
	while tune.is_running:
		sleep(0.1)
		wx.GetApp().Yield()
	del wait
```

**Comment by RobinD42** [comment]
The busyinfo's message is displayed on an ordinary `wx.Frame` that is created like this:

```
    m_InfoFrame = new wxFrame(flags.m_parent, wxID_ANY, wxString(),
                              wxDefaultPosition, wxDefaultSize,
                              wxSIMPLE_BORDER |
                              wxFRAME_TOOL_WINDOW |
                              wxSTAY_ON_TOP);
```

So it's actually a separate top-level window, not something that is tied directly to the parent other than the default of auto-destroying when the parent is closed. If you need something else then you'll need to implement it.

**Comment by brennmat** [comment]
On Fri, Nov 6, 2020 at 12:20 AM Robin Dunn <notifications@github.com> wrote:

> The busyinfo's message is displayed on an ordinary wx.Frame that is
> created like this:
>
>     m_InfoFrame = new wxFrame(flags.m_parent, wxID_ANY, wxString(),
>                               wxDefaultPosition, wxDefaultSize,
>                               wxSIMPLE_BORDER |
>                               wxFRAME_TOOL_WINDOW |
>                               wxSTAY_ON_TOP);
>
> So it's actually a separate top-level window, not something that is tied
> directly to the parent other than the default of auto-destroying when the
> parent is closed. If you need something else then you'll need to implement
> it.
>
Thanks for this! I should have looked this up myself, but I don't know how
/ where I can find the code. Any suggestions where I can find those things
in the future?

I guess the STAY_ON_TOP flag causes much of my troubles. I played around
with it, and it seems to cause the frame to stay on top of all windows,
even if those windows belong to *another* application. As far as I
understand, this should NOT happen according to the information posted here:
https://stackoverflow.com/questions/23403141/make-wx-busyinfo-stay-on-top-in-wxpython

**Comment by RobinD42** [comment]
> Any suggestions where I can find those things in the future?

Familiarity with the wxWIdgets source, or at least having a local copy of it for searching, is helpful. That particular snippet came from : https://github.com/wxWidgets/wxWidgets/blob/master/src/generic/busyinfo.cpp#L36

> As far as I understand, this should NOT happen according to the information posted here...

I'm not totally sure, but even if it may have worked that way in the distant past, it's clearly stated in the docs at 
https://docs.wxpython.org/wx.BusyInfo.html that "Note that a wx.BusyInfo is always built with the STAY_ON_TOP window style (see wx.Frame window styles for more info)."

**Comment by brennmat** [comment]
> I'm not totally sure, but even if it may have worked that way in the distant past, it's clearly stated in the docs at
> https://docs.wxpython.org/wx.BusyInfo.html that "Note that a wx.BusyInfo is always built with the STAY_ON_TOP window style (see wx.Frame window styles for more info)."

Yes, I have seen that. I thought the STAY_ON_TOP flag would apply to the windows of a given wx.App. However, it looks like it applies all windows of _any other application_ as well. I honestly consider this a bit rogue. It's wrong to interfere with other applications in this way.

**Comment by Metallicow** [comment]
wx.STAY_ON_TOP means exactly that. This shouldn't be confused with wx.FRAME_FLOAT_ON_PARENT style flag.
@RobinD42 I think that Busy/BusyInfo should use float behaviour as default, as I do on occasion have a typo in my code when calling one of these and it hangs in process at least on windows and is a PITA to get rid of(or relog into your OS account). The wxPy demo suffered from this for a long time(maybe it still does...).

**Comment by Metallicow** [comment]
My personal opinion is that until the process locking issue gets fixed on the wxWidgets end, then just AVOID using this at all costs. Yes, it is that big of a pain in the ass.

**Comment by RobinD42** [comment]
There's no need to denigrate something that has been that way for decades. If you don't like the way it works then just create a PR for wxWidgets that allows the developer to choose current behavior or to optionally use `wxFRAME_FLOAT_ON_PARENT` instead. Or reimplement it in Python and file a PR here.

**Comment by infinity77** [comment]
Or you could easily switch to wx.lib.agw.pybusyinfo and hack it the way you want it to behave. I mean, all this chitty chatty for wx.BusyInfo?

**Comment by RobinD42** [comment]
Oops, I should have checked for an existing AGW busyinfo. Thanks @infinity77!
