### ISSUE TITLE
demo/agw/RibbonBar.py has two errors

### ISSUE THREAD

**Issue by tianfan007** [wxWidgets/Phoenix#1838]
the file demo/agw/RibbonBar.py can't run well.
I need change line 8 " import images" to " from PIL import as images" 
 but there still has another error ,I dont know how to fix it.
The program will be throw an error: “ModuleNotFoundError: No module named 'run'”

**Operating system**:ubuntu 20.04
**wxPython version & source**:    4.1.0    
**Python version & source**:     3.8.5     

**Description of the problem**:

```python
# Put code sample here
```

**Comment by Metallicow** [comment]
images isn't part of PIL. it is a demo framework file that houses the PyEmbeddedImages.
run.py is a wxPython demo framework starter when running files individually. It is not part of wx library.

**Comment by tianfan007** [comment]
> images isn't part of PIL. it is a demo framework file that houses the PyEmbeddedImages.
> run.py is a wxPython demo framework starter when running files individually. It is not part of wx library.

what's the path of the file run.py?how to set the env for running demo files

**Comment by Metallicow** [comment]
run.py is located here https://github.com/wxWidgets/Phoenix/blob/master/demo/run.py
To launch the demo framework use `demo.py` or `Main.py`
If launching the individual demo files, they will use `run.py` which is in the same directory

**Comment by Metallicow** [comment]
You can also download a snapshot of the demo here https://wxpython.org/Phoenix/snapshot-builds/
Example: 
wxPython-demo-4.1.1a1.dev5026+8a26e17b.tar.gz
and then extract that to a directory on the desktop/etc...

**Comment by tianfan007** [comment]
> You can also download a snapshot of the demo here https://wxpython.org/Phoenix/snapshot-builds/
> Example:
> wxPython-demo-4.1.1a1.dev5026+8a26e17b.tar.gz
> and then extract that to a directory on the desktop/etc...

Thanks!!! It works well

**Comment by Metallicow** [comment]
@tianfan007 Your welcome.
I'm not sure if you used a translator or not, but it translated fairly well enough so that I could understand your issue.
There is a lot to explore in wxPython Demo.
Have fun, and happy coding. :)
