### ISSUE TITLE
LogNull context manager not working in 4.0?

### ISSUE THREAD

**Issue by cbeytas** [wxWidgets/Phoenix#1842]
wxPython 4.0.7 in Windows 7/10 with Python 3.8

The [Context Manager](https://discuss.wxpython.org/t/python-context-managers/23970/4) for `wx.LogNull` doesn't seem to be working. This used to work in wxPython 2.x/3.x

```
with wx.LogNull():
    image = wx.Image(image_path)
```
Now it throws `AttributeError: __exit__`

**Comment by RobinD42** [comment]
This issue has been mentioned on **Discuss wxPython**. There might be relevant details there:

https://discuss.wxpython.org/t/wxpython-4-1-1-released/35043/1
