### ISSUE TITLE
PropertyGrid does not export values of collapsed properties

### ISSUE THREAD

**Issue by LumaRay** [wxWidgets/Phoenix#1843]
Hello.
I have wxPython 4.1.1a1 compiled on Ubuntu 18.04 x64.
I use this to get values of the grid to save them into a file:
`w.property_grid_1.GetPropertyValues(inc_attributes=True)`
Now if I manually collapse some categories/subcategories (I have like a tree) of properties, those properties are not exported until I expand their parent categories and retry to export.
Same thing if I collapse them by code:
```
prc = wx.propgrid.PropertyCategory("Общие свойства")
self.property_grid_1.Append(prc)
...
pra = wx.propgrid.PropertyCategory("Окно просмотра")
self.property_grid_1.AppendIn(prc, pra)
...
self.property_grid_1.Collapse(pra)
```
Turning `inc_attributes=False` doesn't fix the issue.
So now I have to reexpand everything before calling GetPropertyValues, which is very inconvenient.

**Comment by LumaRay** [comment]
Besides, when I try to call `self.property_grid_1.expandAll()` it throws a "no such method" exception. That is strange as I clearly see this function in the PropertyGridInterface documentation.

**Comment by RobinD42** [comment]
> self.property_grid_1.expandAll() 

Was the lower case 'e' above a typo, or is that how it is in your code? (It should be `ExpandAll`.)

**Comment by LumaRay** [comment]
> Was the lower case 'e' above a typo, or is that how it is in your code? (It should be `ExpandAll`.)
Hello Robin, thanks for the note, my bad, got used to camel case naming and typed that unconsciousely. ExpandAll works.
But is there any way to fix the main issue and export all the collapsed properties as well while leaving them in that state?

**Comment by RobinD42** [comment]
I think allowing you to pass the iterator flags into `GetPropertyValues` would be a good fix. Currently it is using just `PG_ITERATE_PROPERTIES`, but to get the hidden items you probably need to add the `PG_ITERATE_HIDDEN` as well. `GetPropertyValues` method is a Python method that is monkey-patched into the class, so it should be fairly easy for you to test a different implementation if you want. I'll add a PR shortly that implements the fix.
