### ISSUE TITLE
Installed from pip missing hyperlinks modules

### ISSUE THREAD

**Issue by GabrielH0we** [wxWidgets/Phoenix#185]
Hello. I tried to use Phoenix with Mullvad Linux application. Installed Phoenix from pip (pip install wx). 

First of all, pip installation doesn't check, if webkitgtk installed. Phoenix doesn't compile without webkitgtk.

And second, when Phoenix is installed, I can't launch Mullvad Linux application with it. It says, that hyperlinks module is missing. I installed all modules from requirements file before installing Phoenix.

```
import wx.lib.hyperlink
ImportError: No module named hyperlink
```

**Comment by HelioGuilherme66** [comment]
You should try to install from the wheel package, then no need to compile.

**Comment by GabrielH0we** [comment]
Thanks. I'll remember that.
But it compiles just fine. hyperlink module is not there though. Will it be there if I install it from wheel?

**Comment by HelioGuilherme66** [comment]
Searching further, I found this important document [classic vs Phoenix](https://wxpython.org/Phoenix/docs/html/classic_vs_phoenix.html) and there we see that the module moved to [`wx.lib.agw.hyperlink`](https://wxpython.org/Phoenix/docs/html/wx.lib.agw.hyperlink.html#module-wx.lib.agw.hyperlink).
