### ISSUE TITLE
Gridmovers event/mouse error

### ISSUE THREAD

**Issue by wossx** [wxWidgets/Phoenix#1851]
**Operating system**: Win 7/10
**wxPython version & source**:          4.1.1a1.dev5026+8a26e17b msw (phoenix) wxWidgets 3.1.5
**Python version & source**:              Stock 3.8

**Description of the problem**:

In demo - 'Grid / A wx.Grid with draggable rows and columns' (GridDragable.py) click (only click, not drag) on row or column label results the following error message:
```
wx._core.wxAssertionError: C++ assertion ""!wxMouseCapture::stack.empty()"" failed at ..\..\src\common\wincmn.cpp(3374) in wxWindowBase::ReleaseMouse(): Releasing mouse capture but capture stack empty?

The above exception was the direct cause of the following exception:

SystemError: PyEval_EvalFrameEx returned a result with an error set
```

**Comment by wossx** [comment]
Sorry. That's problem only on windows 7. 
Probably wxwidgets theme.

**Comment by mprosperi** [comment]
to me happens in win10 #1841

**Comment by wossx** [comment]
And indeed. I was inattentive, again. :-(
It's happens both in win10 and in win7.

If I delete the 'evt.Skip()' from the end of GridRowMover.OnPress() (and from GridColMover), then the message disappear.
But I do not see all the consequences of this.

**Comment by wossx** [comment]
same as #1841
