### ISSUE TITLE
Sizer.Clear(delete_windows=True) crashes application

### ISSUE THREAD

**Issue by Correct-Syntax** [wxWidgets/Phoenix#1854]
**Operating system**: Windows 10
**wxPython version & source**:  4.1.0 from the wxPython extras installed via pip       
**Python version & source**:   3.8.6, installed via the Python windows installer (downloaded from python.org)     

**Description of the problem**:

I am trying to have a panel that is updatable via calling the ``UpdatePanelContents`` method.  The below code works for the most part on Linux and Windows normally.

```python
import wx
import wx.lib.scrolledpanel as scrolledpanel

class NodePropertyPanel(wx.lib.scrolledpanel.ScrolledPanel):
    def __init__(self, parent, size=wx.DefaultSize):
        scrolledpanel.ScrolledPanel.__init__(self, parent, wx.ID_ANY, size=size)
        self._parent = parent
        self._selectedNode = None

        self._mainSizer = wx.BoxSizer(wx.VERTICAL)

        self.SetSizer(self._mainSizer)
        self._mainSizer.Fit(self)

        self.SetupScrolling(scroll_x=False)

    @property
    def Parent(self):
        return self._parent

    @property
    def AUIManager(self):
        return self._parent._mgr

    def UpdatePanelContents(self, selected_node):
        self._mainSizer.Clear(delete_windows=True)

        if selected_node != None: 

            scrollbar_size = wx.SystemSettings.GetMetric(wx.SYS_VSCROLL_X)
            calc_size = wx.Size(self.Size[0]-scrollbar_size-10, self.Size[1])

            self.panel_staticbox = wx.StaticBox(self, id=wx.ID_ANY,
                                                label=selected_node.GetLabel(),
                                                size=calc_size)

            # This gets the recommended amount of border space to use for items
            # within in the static box for the current platform.
            top_bd, other_bd = self.panel_staticbox.GetBordersForSizer()

            staticbox_sizer = wx.BoxSizer(wx.VERTICAL)
            staticbox_sizer.AddSpacer(top_bd)

            inner_sizer = wx.BoxSizer(wx.VERTICAL)

            flagsExpand = wx.SizerFlags(1)
            flagsExpand.Expand().Border(wx.ALL, 18)
            staticbox_sizer.Add(inner_sizer, flagsExpand)

            self.panel_staticbox.SetSizer(staticbox_sizer)

            panel_sizer = wx.BoxSizer(wx.VERTICAL)
            panel_sizer.Add(self.panel_staticbox, 1, wx.EXPAND|wx.ALL, other_bd)

            # Node Properties UI
            selected_node.NodePanelUI(self.panel_staticbox, inner_sizer) # this creates widgets inside the inner_sizer and staticbox

            self._mainSizer.Add(panel_sizer, wx.EXPAND|wx.ALL)

        else:
            # Delete the window if the node is not selected
            self._mainSizer.Clear(delete_windows=True)
        
        # I found that I needed this as this panel is inside of a AUI panel
        self.AUIManager.Update()

        self.Parent.Refresh()
        self.Parent.Update()
```

However, When calling this ``UpdatePanelContents`` method (on Windows only -Linux is O.k.) in a different part of the code, it does update the panel with the new widgets, but then crashes without any errors.

**I guess a good question would be: Is this the right way to create an updatable panel? (I am wanting a panel that can have the widgets set, but then cleared and new widgets to be set in the panel.)**

Thank you for your time!

**Comment by Correct-Syntax** [comment]
**Edit**: Sometimes, on Linux Mint I get a segmentation fault and it crashes. So, my thought is that I am doing something wrong. Any ideas?

**Comment by DietmarSchwertberger** [comment]
Segmentation faults often happen when an element is destroyed while there are pending events for this element.
I don't like this behaviour...

In wxGlade I'm using `sizer.Clear(delete_windows=True)` only indirectly.
E.g. my context menu handler will only call Clear via `CallAfter`. With this approach things seem to work fine.
The `CallAfter` is equivalent to calling `DestroyLater` on each element.
You may try both approaches.

https://wxpython.org/Phoenix/docs/html/wx.Window.html#wx.Window.DestroyLater

Before using CallAfter and DestroyLater, wxGlade crashed a lot...

**Comment by Correct-Syntax** [comment]
> Segmentation faults often happen when an element is destroyed while there are pending events for this element.

O.k. This is probably what I am doing wrong. 

Crash scenario: I have the panel with widgets. Next, the user selects an option from the combobox. Selecting a certain option calls the Method in question to refresh/clear the panel so that new widgets can be placed in the panel. Soon after doing this, the app crashes (usually).

So, if this is indeed wrong what would be a way to make sure this doesn't happen?

**Comment by DietmarSchwertberger** [comment]
The combobox is being destroyed?

**Comment by Correct-Syntax** [comment]
Basically, yes. I am not sure how to do this differently though.

**Comment by DietmarSchwertberger** [comment]
Destroying a control inside it's event handler is not a good idea. Yes, CallAfter is an option.

**Comment by Correct-Syntax** [comment]
Thanks @DietmarSchwertberger. wx.CallAfter was indeed the solution to the problem. 👍
