### ISSUE TITLE
AulToolBar cannot handle a tool that Destroy's the toolbar

### ISSUE THREAD

**Issue by jmoraleda** [wxWidgets/Phoenix#1856]
If the action associated with a tool in an AuiToolBar destroys the toolbar (either explicitly or as a result of a more complex set of actions), the AuiToolBar complains as follows:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/wx/lib/agw/aui/auibar.py", line 3747, in OnLeftUp
    self.DoIdleUpdate()
  File "/usr/local/lib/python3.7/dist-packages/wx/lib/agw/aui/auibar.py", line 3260, in DoIdleUpdate
    handler = self.GetEventHandler()
RuntimeError: wrapped C/C++ object of type AuiToolBar has been deleted
```

The following program exemplifies the issue (click on the toolbar button to see the error).:

```python
import wx
import wx.lib.agw.aui as aui

class TestFrame(wx.Frame):
    def __init__(self):
        super().__init__(None)

        self.aui_mgr = aui.AuiManager_DCP()
        self.aui_mgr.SetManagedWindow(self)

        main_book = aui.AuiNotebook(self)
        note = "press the toolbar button to destroy the toolbar and see the problem"
        main_book.AddPage(wx.StaticText(main_book, label=note), "note")

        self.tb = aui.AuiToolBar(self)
        self.tb.AddSimpleTool(
            tool_id=id(self.tb),
            label='destroy_toolbar',
            bitmap=wx.ArtProvider().GetBitmap(wx.ART_ERROR)
        )
        self.Bind(wx.EVT_TOOL, lambda _: self.tb.Destroy(), id=id(self.tb))
        self.tb.Realize()

        self.aui_mgr.AddPane(main_book, aui.AuiPaneInfo().Center())
        self.aui_mgr.AddPane(self.tb, aui.AuiPaneInfo().Top(). ToolbarPane())

app = wx.App()
win = TestFrame()
win.Show()
app.MainLoop()
```

The problem is that after the call associated with the action returns, the toolbar still does some processing. In particular it explicitly invokes `DoIdleUpdate`. 

The solution is straightforward: `DoIdleUpdate` should test that the toolbar has not been destroyed before doing any further work. I will submit a pull request to address the issue.

----------------   

Digression: I recognize that an action that Destroys the toolbar is unusual. In my real world case, it is part of a "logout" button that completely destroys the frame that is the parent of the toolbar and redirects the user to a different log on frame.

**Comment by RobinD42** [comment]
There are more than a few cases where destroying _something_ within an event handler for that _something_ that will cause a crash. Usually this is because the _something_ will continue to do things to itself after the event handler has returned. Using `DestroyLater` instead of `Destroy` would probably avoid the issue in most cases.

**Comment by jmoraleda** [comment]
Hi Robin. Thank you. In my use case `DestroyLater` still fails because one of the actions that is done as part of clicking on the toolbar is displaying a dialog. If at any point I show a dialog _after_ calling `DestroyLater` then the problem still exists. This is a concrete example:

```python
import wx
import wx.lib.agw.aui as aui

class TestFrame(wx.Frame):
    def __init__(self):
        super().__init__(None)

        self.aui_mgr = aui.AuiManager_DCP()
        self.aui_mgr.SetManagedWindow(self)

        main_book = aui.AuiNotebook(self)
        note = "press the toolbar button to destroy the toolbar and see the problem"
        main_book.AddPage(wx.StaticText(main_book, label=note), "note")

        self.tb = aui.AuiToolBar(self)
        self.tb.AddSimpleTool(
            tool_id=id(self.tb),
            label='destroy_toolbar',
            bitmap=wx.ArtProvider().GetBitmap(wx.ART_ERROR)
        )
        self.Bind(wx.EVT_TOOL, self.on_destroy_toolbar, id=id(self.tb))
        self.tb.Realize()

        self.aui_mgr.AddPane(main_book, aui.AuiPaneInfo().Center())
        self.aui_mgr.AddPane(self.tb, aui.AuiPaneInfo().Top(). ToolbarPane())

    def on_destroy_toolbar(self, _event):
        self.tb.DestroyLater()
        with wx.MessageDialog(self, "Notice the toolbar has already been destroyed!",
                              "Warning", wx.OK | wx.ICON_EXCLAMATION) as dlg:
            dlg.ShowModal()

app = wx.App()
win = TestFrame()
win.Show()
app.MainLoop()
```

In this example, moving the `DestroyLater` after the dialog is closed does solve the problem without any negative consequences.  But  in my real case, moving the `DestroyLater` until after the dialog closes is not desirable because the dialog is long-lived (it asks a new user for credentials to log in), but since the action we are performing by clicking on the toolbar is a logout of the current user, it should guarantee that all closing actions (invoked by the CLOSE events of the windows being destroyed) are executed asap without waiting for a new user to log it, some time later (if ever).

Do you think that my suggested modification in the pull request for the event handler to check that the object (toolbar) still exists after the action is performed is not a good idea?
