### ISSUE TITLE
Release tag for version 4.1.1 missing on GitHub

### ISSUE THREAD

**Issue by SuperSandro2000** [wxWidgets/Phoenix#1858]
**Operating system**: MacOS
**wxPython version & source**: nixpkgs
**Python version & source**: Python 3.8 nixpkgs

**Description of the problem**: 

Version 4.1.1 which I found here https://pypi.org/project/wxPython/#history is not on GitHub.

I would like to switch wxPython in nixpkgs to the GitHub source to easily fetch upstream patches if needed.

**Comment by RobinD42** [comment]
Thanks. I forgot to push the tag, I guess. It's there now.
