### ISSUE TITLE
4.1.1: Alpha channel missing from Bitmaps / Icons rendered with black instead of transparency.

### ISSUE THREAD

**Issue by DietmarSchwertberger** [wxWidgets/Phoenix#1859]
**Operating system**: Window 10, 64 bit
**wxPython version & source**:      4.1.1 PyPi
**Python version & source**:          Stock 3.9.0 64 bit

**Description of the problem**:  Some icons are rendered with black background in toolbar or tree ctrl.

See example code below which creates a toolbar with two icons. The help book is rendered with a black background.
![grafik](https://user-images.githubusercontent.com/5512021/100543440-73698600-3250-11eb-8539-0776a2b49272.png)

Correct display with e.g. 4.1.0:
![grafik](https://user-images.githubusercontent.com/5512021/100543459-9f850700-3250-11eb-8a99-72f794517276.png)

I have similar effects with bitmaps loaded from files and/or in the TreeCtrl.
The same bitmaps are fine when being used e.g. on a ToggleButton.

It seems that the alpha channel is not loaded:
```python

# wx.ART_NEW has a alpha data:
>>> wx.AlphaPixelData( wx.ArtProvider.GetBitmap(wx.ART_NEW, wx.ART_TOOLBAR, (24, 24)) )
<wx._core.AlphaPixelData object at 0x000001EF1079DD38>

# wx.ART_HELP_BOOK does not (NativePixelData would work):
>>> wx.AlphaPixelData( wx.ArtProvider.GetBitmap(wx.ART_HELP_BOOK, wx.ART_TOOLBAR, (24, 24)) )
Traceback (most recent call last):
  Debug Console, prompt 19, line 1
wx._core.wxAssertionError: C++ assertion ""Assert failure"" failed at ..\..\src\msw\bitmap.cpp(1423) in wxBitmap::GetRawData(): incorrect bitmap type in wxBitmap::GetRawData()

```

```python
import wx

class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetTitle("frame")

        # Tool Bar
        self.frame_toolbar = wx.ToolBar(self, -1)
        self.frame_toolbar.AddTool(wx.ID_ANY, "New", wx.ArtProvider.GetBitmap(wx.ART_NEW, wx.ART_TOOLBAR, (24, 24)), wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.frame_toolbar.AddTool(wx.ID_ANY, "Help book", wx.ArtProvider.GetBitmap(wx.ART_HELP_BOOK, wx.ART_TOOLBAR, (24, 24)), wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.SetToolBar(self.frame_toolbar)
        self.frame_toolbar.Realize()
        # Tool Bar end
        self.Layout()


class MyApp(wx.App):
    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
```

**Comment by RobinD42** [comment]
wxWidgets has (or perhaps used to have) a feature that was patterned after Win32 behavior from way back in the early days of Windows, where a bitmap with no explicit mask or alpha would automatically get one wherever there are pixels of a certain color. I don't know if that was removed, which means that that stock bitmap should have been updated, or if the toolbar is not correctly using the mask any longer, or it's some other regression of some kind. Either way, this is a wxWidgets issue so it should be reported there.

**Comment by DietmarSchwertberger** [comment]
Thanks. Will do so. The XPMs I'm loading are showing similar problems. I did not look into these yet whether they have an explicit alpha channel or not. (I hate formats like XPM.)
For the wx bug report: what specific wx versions is 4.1.1 referenceing vs. 4.1.0? I did not expect such a change with an update in the last digit.

**Comment by DietmarSchwertberger** [comment]
Seems to be fixed since November 21st in the wx repository already. Did not find the ticket when I searched first as I was searching for "alpha".

wx tickets were #18974, #18975.

Thanks. I'm wondering though whether it would make sense to have something like a "wxpython unstable" branch on PIP. The experience with the introduction of 4.0.0 and 4.1.1 was not the best.

**Comment by DietmarSchwertberger** [comment]
I think we should keep this open until a new wxPython version is released.

**Comment by RobinD42** [comment]
The next snapshot build will include the wxWidgets fix.

**Comment by RobinD42** [comment]
This issue has been mentioned on **Discuss wxPython**. There might be relevant details there:

https://discuss.wxpython.org/t/bitmap-background-set-to-black-in-new-version/35594/2
