### ISSUE TITLE
Intermittent GLCanvas failure

### ISSUE THREAD

**Issue by w3sip** [wxWidgets/Phoenix#1861]
We're in a process of transitioning our old code, which works fine with 3.0.2 to Phoenix. With Phoenix 4.1.0, we see an intermittent crash that had been traced to an interesting phenomena: 

Consider this initialization code:
```
class GLCanvasSV( GLCanvas ):
    def __init__( self, parent, location='(none)'):
        print("%d-%s.%s parent=%s" % (id(self), self.__class__.__name__, inspect.currentframe().f_code.co_name,str(parent)))
        GLCanvas.__init__(
            self, parent, id=wx.ID_ANY, attribList=[ wx.glcanvas.WX_GL_DOUBLEBUFFER, wx.glcanvas.WX_GL_RGBA, wx.glcanvas.WX_GL_DEPTH_SIZE],
        )
        if self.GetParent() is None:
            print("Detected orphan GLCanvas (1). Parent chain:")
            printWinChain(parent)
            assert self.GetParent(), "New GLCanvas has no parents!"
```

The `parent` object is always valid. However, every once in awhile `self.GetParent()` ends up returning `None`, causing a crash further down the road. When that happens, this is the output for `printWinChain`:

```Detected orphan GLCanvas (1). Parent chain:
   140597830583632 Panel
      140597830582992 FixedMultiSplitterWindow
         140597830582832 Panel
            140597830508048 FixedMultiSplitterWindow
               140597830508208 MonitorView
                  140597807351440 FrontEndFrame
Done printing glcanvas inheritance chain
```

The code for `printWinChain` is trivial:
```def printWinChain(winTop):
    win = winTop
    tab = "   "
    offset = tab
    while not win is None:
        print("%s%d %s" % (offset,id(win),win.__class__.__name__))
        offset += tab
        win = win.GetParent()
    print("Done printing glcanvas inheritance chain")
```

Any advice on how to track this (to emphasize again, very much intermittent and rare) failure is much appreciated.

**Comment by RobinD42** [comment]
It is definitely weid, it seems like it should be possible. If you can find a way to reproduce it in a small standalone application then I can take a closer look at it.

**Comment by w3sip** [comment]
This was actually quite simple. Our constructor still passed attribList, rather than dispAttrs -- interestingly enough, it never asserted or logged a deprecation warning, but resulted in the above non-deterministic behavior. Switching to GLAttributes() fixed it.
