### ISSUE TITLE
wxPython 4.1.1 regression: stock menu bitmaps drawn with black backgrounds instead of alpha.

### ISSUE THREAD

**Issue by jeremyd2019** [wxWidgets/Phoenix#1865]
**Operating system**:                       Windows 10 1909
**wxPython version & source**:        4.1.1 from `pip install wxPython`
**Python version & source**:            3.8.6 32-bit from python.org 

**Description of the problem**:

Regression from wxPython 4.1.0: stock menu bitmaps drawn with black backgrounds instead of alpha.

Screenshot from `pip install wxPython==4.1.0`:
![example-4 1 0](https://user-images.githubusercontent.com/4524874/101220154-0a13b980-363a-11eb-9f05-a3beeca2762a.png)

Screenshot from `pip install wxPython==4.1.1`:
![example-4 1 1](https://user-images.githubusercontent.com/4524874/101220210-21eb3d80-363a-11eb-988f-6d712b806164.png)

```xml
<!-- Put code sample here -->
...
  <object class="wxFrame" name="mainframe">
    <object class="wxMenuBar" name="menuBar">
      <object class="wxMenu" name="wxID_EDIT">
        <label>&amp;Edit</label>
        <object class="wxMenuItem" name="wxID_PREFERENCES">
          <label>&amp;Preferences...</label>
          <bitmap stock_id="wxART_HELP_SETTINGS"/>
          <accel>Ctrl-E</accel>
          <XRCED>
            <events>EVT_MENU</events>
          </XRCED>
        </object>
...
```

**Comment by DietmarSchwertberger** [comment]
see #1859

**Comment by jeremyd2019** [comment]
Thanks
