### ISSUE TITLE
Crash in CustomDragAndDrop: second drag and drop kills it

### ISSUE THREAD

**Issue by gwhenne** [wxWidgets/Phoenix#1869]
**Operating system**: Mac OS 11.1 (10.14.6 too)
**wxPython version & source**:          4.1.1 fresh download from wxPython
**Python version & source**:            Python 3.8.6 fresh download from python.org

**Description of the problem**:

1. `wxdemo`
2. Open CustomDragAndDrop sample
3. Make a drawing
4. Drag and Drop - works OK
5. Make another drawing
6. Drag and Drop
7. Hard crash, no error message

If there's no immediate fix, are there any workarounds? It's a blocker for us.

```python
# Put code sample here
```

**Comment by swt2c** [comment]
This is a known problem it seems in wxWidgets.  It is stuck at the moment, waiting for someone to make a reproducer in C++.  See
https://groups.google.com/g/wx-users/c/geCt_mgeYj4/m/LVIeQqXKAAAJ

**Comment by RobinD42** [comment]
This issue has been mentioned on **Discuss wxPython**. There might be relevant details there:

https://discuss.wxpython.org/t/drag-and-drop-within-wxtreectrl-on-macos/34790/14

**Comment by RobinD42** [comment]
The fix in the wxMac C++ code is here: https://github.com/wxWidgets/wxWidgets/commit/108b48f691bac96152c4980a485575356ed7c884 and will be included in the next snapshot build.
