### ISSUE TITLE
Linker error when building Phoenix with current wxWidgets master

### ISSUE THREAD

**Issue by jensgoe** [wxWidgets/Phoenix#1870]
**Operating system**: Win10
**wxPython version & source**: source self-built
**Python version & source**: source self-built

**Description of the problem**:

- change submodule wxWidgets to current master (3.1.5)
- compile

[546/958] Compiling sip\cpp\sip_advwxCalculateLayoutEvent.cpp
   Bibliothek "_core.lib" und Objekt "_core.exp" werden erstellt.
sip_corewxPlatformInfo.cpp.4.o : error LNK2019: Verweis auf nicht aufgel�stes externes Symbol ""__declspec(dllimport) public: static enum wxBitness __cdecl wxPlatformInfo::GetBitness(class wxString const &)" (__imp_?GetBitness@wxPlatformInfo@@SA?AW4wxBitness@@AEBVwxString@@@Z)" in Funktion "meth_wxPlatformInfo_GetBitness".
C:\\dev\\github\\Phoenix\\build\\waf\\3.7\\x64\\release\\_core.cp37-win_amd64.pyd : fatal error LNK1120: 1 nicht aufgel�ste Externe

My guess it is related to:
https://github.com/wxWidgets/wxWidgets/pull/2122

**Comment by RobinD42** [comment]
Yep, I ran into that too. I've got a workaround on the way.

**Comment by RobinD42** [comment]
Fixed (worked around rather) in c4442cbc561e7c148520e6c02c78ec7fe893649f.
