### ISSUE TITLE
Incorrect ID on ScrolledThumbnail events

### ISSUE THREAD

**Issue by eagerm** [wxWidgets/Phoenix#1882]
**Operating system**:
**wxPython version & source**:         4.1.1 - built by pip3
**Python version & source**:            Python 3.8 (Centos 8.3)

**Description of the problem**:

The events generated by ScrolledThumbnail (and also by ThumbnailCtrl) include an event ID.  The ID is not for the thumbnail which generated the event, but is for the scrolledthumbnail control itself.  The affected events are: wxEVT_THUMBNAILS_SEL_CHANGED
wxEVT_THUMBNAILS_POINTED
wxEVT_THUMBNAILS_DCLICK
wxEVT_THUMBNAILS_CHAR

Run test program in a directory which contains JPG or GIF images and mouse over thumbnails, select or double click, or enter char (other than a, s, d).  The same ID is generated, as well as identifying the ScrolledThumbnail instance.  

```python
import os
import wx

import wx.lib.agw.scrolledthumbnail as ST

class MyFrame(wx.Frame):

    def __init__(self, parent):
        wx.Frame.__init__(self, parent, -1, "ScrolledThumb Demo", size=(400,300))

        self.scroll = ST.ScrolledThumbnail(self, -1, size=(400,300))
        self.scroll.Bind(ST.EVT_THUMBNAILS_SEL_CHANGED, self.doSelChanged)
        self.scroll.Bind(ST.EVT_THUMBNAILS_POINTED, self.doPointed)
        self.scroll.Bind(ST.EVT_THUMBNAILS_DCLICK, self.doDclick)
        self.scroll.Bind(ST.EVT_THUMBNAILS_CHAR, self.doChar)

    def ShowDir(self, dir):
        dir = os.getcwd()
        files = os.listdir(dir)
        thumbs = []
        for f in files:
            if os.path.splitext(f)[1] in [".jpg", ".gif", ".png"]:
                thumbs.append(ST.Thumb(dir, f, caption=f, imagehandler=ST.NativeImageHandler))
        self.scroll.ShowThumbs(thumbs)

    def doSelChanged(self, event):
        id = event.GetId()
        print ("SEL_CHANGED:  id = %d" % (id))
        print (wx.Window.FindWindowById(id))

    def doPointed(self, event):
        id = event.GetId()
        print ("Pointed:  id = %d" % (id))
        print (wx.Window.FindWindowById(id))

    def doDclick(self, event):
        id = event.GetId()
        print ("Dclick:  id = %d" % (id))
        print (wx.Window.FindWindowById(id))

    def doChar(self, event):
        id = event.GetId()
        print ("Char:  id = %d" % (id))
        print (wx.Window.FindWindowById(id))


app = wx.App(False)
frame = MyFrame(None)
frame.ShowDir(os.getcwd())
frame.Show(True)

app.MainLoop()
```

Proposed fix:  Return ID of selected Thumb or first Thumb if multiple thumbnails are selected.  Return list of selected thumbs.

**Comment by RobinD42** [comment]
The standard in wx is that the event ID is the ID of the widget that sent the event, not for items within the widget. Think about the `wx.ListBox`... When an item is selected the event object's ID is the listbox's ID, not the index of the item. If you need that then you can use `GetSelection` or `GetSelections`. (IIRC you can also get the selection from `event.GetInt()` but that is only there for very old legacy reasons, and is not really used anymore.)

Given that pattern I think the thumbnail widgets are doing the correct thing already.

Of course, for every rule there are exceptions. The `EVT_MENU` events from a menu or toolbar uses the id of the menu items for the event ID. But again, this inconsistency is kept for legacy reasons. All new widgets should use the listbox pattern instead.

**Comment by eagerm** [comment]
On 1/5/21 2:29 PM, Robin Dunn wrote:
> The standard in wx is that the event ID is the ID of the widget that 
> sent the event, not for items within the widget. Think about the 
> |wx.ListBox|... When an item is selected the event object's ID is the 
> listbox's ID, not the index of the item. If you need that then you can 
> use |GetSelection| or |GetSelections|. (IIRC you can also get the 
> selection from |event.GetInt()| but that is only there for very old 
> legacy reasons, and is not really used anymore.)
> 
> Given that pattern I think the thumbnail widgets are doing the correct 
> thing already.

I looked into this more and I agree.  The ID should be the widget id, 
perhaps for the unlikely case that there is more than one 
ScrolledThumbnail widget in an application.

The event object has a "thumbs" member when a key stroke event 
(wxEVT_THUMBNAILS_CHAR) is generated.  I extended all of the events 
generated by ScrolledThumbnail to have this member.

-- 
Michael Eager
