### ISSUE TITLE
UnicodeDecodeError on `import wx`

### ISSUE THREAD

**Issue by quarthex** [wxWidgets/Phoenix#1886]
**Operating system**: Windows 10
**wxPython version & source**: 4.1.0 from PyPI
**Python version & source**: 2.7.14 32bits

**Description of the problem**:

I encountered the issue in the context of an application bundled with cx_Freeze.
The bundled application is installed in a directory that contains non-ASCII symbols.

```
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
    module.run()
  File "C:\Python27\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
    exec(code, m.__dict__)
  …
  File "C:\Python27\lib\site-packages\wx\__init__.py", line 17, in <module>
    from wx.core import *
  File "C:\Python27\lib\site-packages\wx\core.py", line 321, in <module>
    Locale.AddCatalogLookupPathPrefix(_localedir)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 21: invalid continuation byte
```

One can see in the following snippet that `_localedir` may contain non-ASCII symbols if `__file__` does.
It may be fixed by decoding  `_localedir` into a `unicode` or by using `os.path.relpath`.
https://github.com/wxWidgets/Phoenix/blob/12db41dad117598b8c850278597dd277e3812834/etg/intl.py#L62-L64

**Comment by RobinD42** [comment]
Please add the following lines into the code just before the call to `AddCatalogLookupPathPrefix` and let us know if that takes care of the problem for you.

```
        if isinstance(_localedir, (bytes, bytearray)):
            _localedir = _localedir.decode(_sys.getfilesystemencoding())
```

**Comment by quarthex** [comment]
Hello,

Sorry for the delay. As I bypassed the bug by using installation path in plain-ASCII, I moved forward and forgot to investigate further…

Your additional two lines do the job. I just tested it.

**Comment by quarthex** [comment]
Hello @RobinD42,

Can we close this issue because of 66f62480f3b19a549d05967b36c24ac8e396acb0?
