### ISSUE TITLE
CubeColorDialog drawing issues - Linux Mint 20 LTS

### ISSUE THREAD

**Issue by Correct-Syntax** [wxWidgets/Phoenix#1891]
**Operating system**: Linux Mint 20
**wxPython version & source**:   version 4.1.0 from **wxpython extras** (wxpython.org), wheel was installed via pip       
**Python version & source**:   3.8, came with system         

**Description of the problem**:
See screenshot below showing the problem in the wxpython demo.  This also happens outside of the wxpython demo.

Below is the what is printed to the console (multiple times):
```shell
(main.py:3766): Gtk-CRITICAL **: 00:25:09.762: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkSpinButton
```
![color-dialog](https://user-images.githubusercontent.com/60711001/100545511-ca0b9b80-3221-11eb-9f11-fe66445e48ec.png)

**Comment by swt2c** [comment]
This is an unfortunate result of the larger GtkSpinButton's in GTK3.  The dialog will have to be resized to make more space for the buttons.

**Comment by Correct-Syntax** [comment]
o.k. thanks for looking into this. 

I am not sure what is required to get this working. You said the dialog needs to be larger -so it that likely the only issue here?

**Comment by swt2c** [comment]
Yeah, something's constraining those SpinButtons - you can see if you make the window bigger, it doesn't help.  So there are some hard-coded widths in there somewhere.  I looked very briefly and couldn't see exactly where.

**Comment by swt2c** [comment]
Found it.  I'll send a PR over.  It fixes it for me with GTK3's default theme on Fedora.  Hopefully it works for whatever theme Mint uses.

**Comment by Correct-Syntax** [comment]
Great! I hope it will resolve the issue. Thanks!

**Comment by RobinD42** [comment]
This issue has been mentioned on **Discuss wxPython**. There might be relevant details there:

https://discuss.wxpython.org/t/cubecolourdialog-leaving-trails-on-some-controls/35262/2
