### ISSUE TITLE
How to change button border radius as well as border color & width?

### ISSUE THREAD

**Issue by beanhacker** [wxWidgets/Phoenix#1893]
as title, i can not find method to change button border radius as well as border color & width, How to do it? thanks!

**Comment by RobinD42** [comment]
wxPython uses the platform's native widgets where ever possible, and the native widgets don't typically allow those kinds of changes. Instead you can use generic widgets, such as the generic buttons in the `wx.lib.buttons` module. You may be able to do what you want with them directly, or you can derive your own button class that changes how the button is drawn or changes other behavior.

**Comment by DietmarSchwertberger** [comment]
Have a look at the demo under Custom Controls -> GenericButtons.

https://discuss.wxpython.org/ is a better place for such questions.
