### ISSUE TITLE
interpreter crash with FlatMenu demo

### ISSUE THREAD

**Issue by mprosperi** [wxWidgets/Phoenix#190]
clicking on a menu in the menu bar
(with Python 3.4-64bit, win7-64bit)

**Comment by swt2c** [comment]
Confirmed on Linux/GTK+3 too.

**Comment by Metallicow** [comment]
In the demo, just opening a top level menu hard crashes the demo.
Win 7

**Comment by infinity77** [comment]
Is this with Python 3 only? I have just tried on Windows 7, Python 2.7 and the FlatMenu demo works perfectly all right for me...

**Comment by Metallicow** [comment]
@infinity77 
@RobinD42 
This is working now. Tested on wxPython-4.0.0rc1.dev3477+0aa026a Windows 7
This can be closed.

**Comment by david-hughes** [comment]
I can also confirm the FlatMenu demo is working OK under Windows 10 where
Python is version 3.6.1
wx version is 4.0.0b2 msw (phoenix)
