### ISSUE TITLE
Tab key does not navigate out of a ComboCtrl

### ISSUE THREAD

**Issue by CSH37** [wxWidgets/Phoenix#1905]
I am running Ubuntu Feral Fossa 64 bit - Python 3 with wxPython 4.0
When adding a ComboCtrl to a panel, the tab navigation gets stuck at this control
I had previously run Xenial in 32 bit with Python 2.7 and wxPython 3.8 which did not have this problem.

This is the code which uses the ComboCtrl sample in the documentation (not included here):

```
class test_cc(wx.Frame):
    def __init__(self):
        super().__init__(None, title="Test ComboCtrl")
        panel = wx.Panel(self)

        sizer = wx.BoxSizer(wx.VERTICAL)
        sizer.Add(wx.StaticText(panel, label="ComboCtrl test"))
        sizer.Add(wx.TextCtrl(panel))
        sizer.Add(wx.TextCtrl(panel))
        comboCtrl = wx.ComboCtrl(panel, wx.ID_ANY, "")

        popupCtrl = ListCtrlComboPopup()

        # It is important to call SetPopupControl() as soon as possible
        comboCtrl.SetPopupControl(popupCtrl)

        # Populate using wx.ListView methods
        popupCtrl.AddItem("First Item")
        popupCtrl.AddItem("Second Item")
        popupCtrl.AddItem("Third Item")

        sizer.Add(comboCtrl)
        sizer.Add(wx.ComboBox(panel, ))
        sizer.Add(wx.TextCtrl(panel))
        panel.SetSizer(sizer)
        top_sizer = wx.BoxSizer()
        top_sizer.Add(panel)
        self.SetSizerAndFit(top_sizer)

app = wx.App(0)
box = test_cc()
box.Show(True)
app.MainLoop()
```

**Comment by RobinD42** [comment]
It appears that this has been fixed in one of the 4.1.x releases.

**Comment by Jorilx** [comment]
Since Debian 10 ships with wxPython 4.0.4, do you think it could be possibile to "monkey-patch" it with this fix?
(I've tried looking at the changelog but couldn't figure out when the fix came in)

**Comment by swt2c** [comment]
Probably not as the fix probably came in wxWidgets, which is C++ code.

**Comment by Jorilx** [comment]
Could it have been fixed with [this commit](https://github.com/wxWidgets/wxWidgets/commit/f775501ba0a3b514cd0417e947c307c850d1dfec)?
