### ISSUE TITLE
Suggestion for your issue template

### ISSUE THREAD

**Issue by kdschlosser** [wxWidgets/Phoenix#1908]
I suggest you add a collapsible section for the example code. This makes it much nicer if the person creating an issue has a code block that is long. It makes it nicer not to have to scroll down a whole bunch to see the comments to an issue. The expanding section looks like this

<details>
  <summary>Click me to expand!</summary>
  
I am Expanded!!

</details >

Here is what the template looks like with the expandable/collapsible section added
```
<!-- For bugs or other problems please provide the following details in addition to
     your issue report, if applicable. See also https://wxpython.org/pages/how-to-submit-issue/

     For issues about building on Linux, please read this page before reporting it here:
     https://wxpython.org/blog/2017-08-17-builds-for-linux-with-pip/
-->

**Operating system**:
**wxPython version & source**:          <!-- pypi, self-built, etc. -->
**Python version & source**:            <!-- stock, anaconda, EDM, distro, self-built, etc. -->

**Description of the problem**:

<!-- if possible please include a small runnable application that demonstrates the problem -->


<details>
  <summary>Code Example (click to expand)</summary>
  
` ` `python
# Put code sample here
` ` `

</details>
```

you will need to remove the spaces around the acute, backtick, left quote, back prime, birk, blugle, grave, grave accent, quasiquote, push, or unapostrophe, whichever the name you want to call it. the tick marks that define a code block.

just a suggestion.

**Comment by RobinD42** [comment]
Thanks, I've been thinking about doing this too.

**Comment by kdschlosser** [comment]
hey what can I say... great minds think alike!!!
