### ISSUE TITLE
AuiManager fails in ubuntu 16.04/py35

### ISSUE THREAD

**Issue by jusjusjus** [wxWidgets/Phoenix#191]
Hi, I have troubles with Aui docks under python 3.5 which I build from Phoenix sources under Ubuntu 16.04.  The following minimal script fails when trying to resize the docked panel.

```python
import wx
import wx.lib.agw.aui as aui

class Window(wx.Frame):

    def __init__(self, *args, **kwargs):
        wx.Frame.__init__(self, *args, **kwargs)

        manager = self.manager = aui.AuiManager(self)

        panel1 = wx.Panel(self, -1, size=wx.Size(-1, -1))
        panel2 = wx.Panel(self, -1, size=wx.Size(-1, -1))

        info1 = aui.AuiPaneInfo().Center()
        info2 = aui.AuiPaneInfo().Left()

        manager.AddPane(panel1, info1)
        manager.AddPane(panel2, info2)
        manager.Update()

app = wx.App()
win = Window(None)
win.Show(True)
app.MainLoop()
```

No error message is thrown.  Under python 2.7, no problems.
Thanks, jus

**Comment by RobinD42** [comment]
Please try again with the next snapshot build as it will have some fixes related to this.  I didn't get any crashes but there was some assertion errors thrown, so maybe your wxWidgets was built without the assertions turned on.  Also, you'll want to make sure that you are calling the AUI manager's `UnInit`method when the managed frame is closing, for example something like this as an `EVT_CLOSE` handler:

```
    def OnCloseWindow(self, evt):
        self.manager.UnInit()
        evt.Skip()
```

Closing, but feel free to reopen if there is still an issue.
