### ISSUE TITLE
DateTime.FromTimeT() generates invalid dates

### ISSUE THREAD

**Issue by StokesMIDE** [wxWidgets/Phoenix#1910]
**Operating system**: Windows 10 (build 10.0.18363)
**wxPython version & source**: 4.1.1 from PyPI
**Python version & source**: Stock 3.7.4 and stock 3.9.1

**Description of the problem**:
`DateTime.FromTimeT()` is failing in Python 3.7.4 and 3.9.1. The results are slightly different, although that may simply be the reporting; it looks like the same root problem.

In 3.7.4, the method executes, but generates bad values (equivalent Python `datetime` used to show expected behavior):
```python-console
>>> import datetime, wx
>>> datetime.datetime.fromtimestamp(1611851055)
datetime.datetime(2021, 1, 28, 11, 24, 15)
>>> wx.DateTime.FromTimeT(1611851055)
<wx.DateTime: "Fri Dec 16 17:16:15 59183">
```

In 3.9.1, the same call to `wx.DateTime.FromTimeT()` produces a series of wxPython Debug Alert dialogs before the Python interpreter shuts down:
![FromTimeT-1](https://user-images.githubusercontent.com/14080057/106171538-a4d2d500-615f-11eb-85e3-45e55bc90ecb.png)
![FromTimeT-2](https://user-images.githubusercontent.com/14080057/106171549-a7cdc580-615f-11eb-826d-327e971a9aca.png)
![FromTimeT-3](https://user-images.githubusercontent.com/14080057/106171552-a9978900-615f-11eb-98b2-ad00e001a5d8.png)

In 3.7.4, the `wx,DateTime.FromTimeT()` results are the same whether a `wx.App` is running or not. In 3.9.1, the debug alerts only show up if a `wx.App` has *not* been instantiated; without it, the interpreter simply shuts down.

I can't verify it at the moment, but I believe `DateTime.FromTimeT()` was working in wxPython 4.0.7; I skipped 4.1.0.

**Comment by swt2c** [comment]
This might be a Windows-specific problem.  I don't see any problems on Linux.

I wonder if this is related to the Locale issues on Windows with 4.1.x?

**Comment by swt2c** [comment]
Scratch that about the Locale issues - don't think it's related.

Still could be Windows specific though.  Are you using 32-bit or 64-bit Python on Windows?

**Comment by StokesMIDE** [comment]
This may well be Windows-specific; I could not reproduce it on MacOS.

I'm using the 64b Python: `Python 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)] on win32`.

**Comment by RobinD42** [comment]
It looks like there may be something going on with converting to the C `time_t` type. I'm taking a closer look now.

**Comment by StokesMIDE** [comment]
FWIW, it looks like the start of the epoch is wrong. The dates are far future, but consistent.
```python-console
>>> wx.DateTime.FromTimeT(0)
<wx.DateTime: "Mon Dec  2 05:12:16 55185">
>>> wx.DateTime.FromTimeT(1)
<wx.DateTime: "Mon Dec  2 05:12:17 55185">
```

**Comment by RobinD42** [comment]
I had an incorrect typedef, so on Windows where `long` is a 32-bit value half of the `time_t` bits were being dropped. Fix is on the way.

**Comment by VolkerSiep** [comment]
I have a similar observation. The following code

    from datetime import datetime
    import wx   

    tick = 1664478821  # 29.9.2022 21:13:41
    print(datetime.fromtimestamp(tick))
    print(wx.DateTime().FromTimeT(tick))

generates

    2022-09-29 21:13:41
    Sat Feb 22 01:42:13 79873

Packages:
    python                    3.10.6          h9a09f29_0_cpython    conda-forge
    wxpython                  4.1.1           py310h494077a_7    conda-forge

I'm on a Windows 10 PC with miniconda installation.

**Comment by Jalkhov** [comment]
Something new about this? I am having similar problem with following code:

```
import wx

dt = wx.DateTime(29, 1, 2023)
```

Got this alert

![imagen](https://user-images.githubusercontent.com/36505934/214865219-41b39f96-2356-4c77-b95b-0e261dbc9f7d.png)

I am on Windows 10
