### ISSUE TITLE
Getting locale issue with matplotlib wxbitmap in israel

### ISSUE THREAD

**Issue by ryancinsight** [wxWidgets/Phoenix#1919]
**Operating system**: Windows 10
**wxPython version & source**:     4.1.2 pypi
**Python version & source**:           python 3.8

**Description of the problem**: Getting locale issue with matplotlib wxbitmap in israel

Traceback (most recent call last):
  File "MRANALYSIS3", line 382, in single
  File "MRANALYSIS3", line 626, in Create_DataBase
  File "MRANALYSIS3", line 986, in GETROIS
  File "asyncio.base_events", line 616, in run_until_complete
  File "MRANALYSIS3", line 981, in plot
  File "MRANALYSIS3", line 959, in plotter
  File "matplotlib.pyplot", line 1177, in subplots
  File "matplotlib.pyplot", line 540, in figure
  File "matplotlib.backends.backend_wx", line 1913, in new_figure_manager
  File "matplotlib.backend_bases", line 3358, in new_figure_manager
  File "matplotlib.backends.backend_wx", line 1917, in new_figure_manager_given_figure
  File "matplotlib.backends.backend_wx", line 1026, in __init__
  File "matplotlib.backends.backend_wx", line 1187, in _set_frame_icon
  File "matplotlib.backends.backend_wx", line 1180, in _load_bitmap
wx._core.wxAssertionError: C++ assertion "strcmp(setlocale(0, 0), "C") == 0" failed at ..\..\src\common\intl.cpp(1694) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.

```python
            async def plotter(i):
                fig, (ax1,ax2,ax3) = plt.subplots(1,3,figsize=(30,10))
                plt.rcParams.update({'font.size': 20})
                fig.suptitle(f'{os.path.basename(os.path.normpath(self.PARENT_DIR))}_{i}')
                ax1.axis('off')
                ax2.axis('off')
                ax3.axis('off')
                ax1.set_title('PRE')
                ax2.set_title('POST')
                ax3.set_title('LabelMap')
                ax1.imshow(sitk.GetArrayFromImage(self.PRE[:,:,i]),cmap=plt.cm.Greys_r, vmin = 0, vmax = 200)
                ax2.imshow(sitk.GetArrayFromImage(self.POST[:,:,i]),cmap=plt.cm.Greys_r, vmin = 0, vmax = 200)
                ax3.imshow(sitk.GetArrayFromImage(self.Overlay0[:,:,i]),cmap=plt.cm.Greys_r, vmin = 0, vmax = 200)
                fig.savefig(f'{OUTBMPALL}{os.path.basename(os.path.normpath(self.PARENT_DIR))}_{i}.png')
                extent = ax1.get_window_extent().transformed(fig.dpi_scale_trans.inverted())
                fig.savefig(f'{OUTBMPPRE}{os.path.basename(os.path.normpath(self.PARENT_DIR))}_{i}.png',bbox_inches=extent)
                extent = ax2.get_window_extent().transformed(fig.dpi_scale_trans.inverted())
                fig.savefig(f'{OUTBMPPOST}{os.path.basename(os.path.normpath(self.PARENT_DIR))}_{i}.png',bbox_inches=extent)
                extent = ax3.get_window_extent().transformed(fig.dpi_scale_trans.inverted())
                fig.savefig(f'{OUTBMPLABEL}{os.path.basename(os.path.normpath(self.PARENT_DIR))}_{i}.png',bbox_inches=extent)
                plt.close()
                await asyncio.sleep(0.1)
            async def plot(z_list):
                x = await asyncio.gather(*[plotter(i) for i in z_list]) 
            loop = asyncio.get_event_loop()
            loop.run_until_complete(plot(z_list))
```
This is on colleagues laptop in israel, rest of colleagues in us have no issue with executable so it's a little perplexing.

**Comment by swt2c** [comment]
4.1.1 is the latest on pypi, is that what you actually mean?

Can you try with one of the latest snapshot releases?  There was a fix related to locales committed recently.

**Comment by ryancinsight** [comment]
yes I meant 4.1.1, the last one on pypi, I'll let you know if the snapshot fixed it soon.

**Comment by ryancinsight** [comment]
@swt2c you are correct the recent snapshot:
wxPython-4.1.2a1.dev5165+64e5d863-cp38-cp38-win_amd64.whl

Corrected the locale issue. All the best!
