### ISSUE TITLE
PropertyGrid issues

### ISSUE THREAD

**Issue by DietmarSchwertberger** [wxWidgets/Phoenix#192]
Any use of PropertyGridManager crashes Python (3.5 with one of the recent snapshots)

The demo does not start. I've attached a version which at least starts, but then crashes...
I had to deactivate the event stuff in TestPanel.__init__
[PropertyGrid.zip](https://github.com/wxWidgets/Phoenix/files/573330/PropertyGrid.zip)

Missing from the implementation:
 - EVENTS
 - LABEL_AS_NAME is missing. Not sure whether this is required; it was defined as LABEL_AS_NAME = "@!"

Regards,

Dietmar

**Comment by RobinD42** [comment]
The event related things are being added. The LABEL_AS_NAME item is now called PG_LABEL_STRING in the C++ code, with a PG_LABEL macro that in effect evaluates to that too, and they have now been added for Phoenix as well.
