### ISSUE TITLE
Can't install 4.1.1 against Python 3.8.7 on Debian Jessie but can install 4.1.0

### ISSUE THREAD

**Issue by CiderMan** [wxWidgets/Phoenix#1927]
**Operating system**: debian:jessie container
**wxPython version & source**:  installed/built with pip
**Python version & source**: 3.8.7 built from source

**Description of the problem**:
I have installed all the dependencies listed other than Python -- since I have built 3.8.7 from source (with `--enable-shared`), I assume that I have everything that is needed:
```
   apt-get install -y dpkg-dev build-essential freeglut3-dev libgl1-mesa-dev libglu1-mesa-dev \
      libgstreamer-plugins-base1.0-dev libgtk-3-dev libjpeg-dev libnotify-dev libpng-dev \
      libsdl2-dev libsm-dev libtiff-dev libwebkit2gtk-4.0-dev libxtst-dev
```
Having created a venv with my Python build, I can successfully run `pip install wxpython==4.1.0`, which downloads and builds wxPython. However, when I try `pip install wxpython==4.1.1`, I get errors in the build starting with:

```
    /tmp/pip-install-ap4guj0b/wxpython/ext/wxWidgets/src/unix/glegl.cpp: In member function ‘wxGLContextAttrs& wxGLContextAttrs::CoreProfile()’:
    /tmp/pip-install-ap4guj0b/wxpython/ext/wxWidgets/src/unix/glegl.cpp:48:19: error: ‘EGL_CONTEXT_OPENGL_PROFILE_MASK’ was not declared in this scope
         AddAttribBits(EGL_CONTEXT_OPENGL_PROFILE_MASK,
                       ^
    /tmp/pip-install-ap4guj0b/wxpython/ext/wxWidgets/src/unix/glegl.cpp:49:19: error: ‘EGL_CONTEXT_OPENGL_CORE_PROFILE_BIT’ was not declared in this scope
                       EGL_CONTEXT_OPENGL_CORE_PROFILE_BIT);
                       ^
    /tmp/pip-install-ap4guj0b/wxpython/ext/wxWidgets/src/unix/glegl.cpp: In member function ‘wxGLContextAttrs& wxGLContextAttrs::MajorVersion(int)’:
    /tmp/pip-install-ap4guj0b/wxpython/ext/wxWidgets/src/unix/glegl.cpp:57:22: error: ‘EGL_CONTEXT_MAJOR_VERSION’ was not declared in this scope
             AddAttribute(EGL_CONTEXT_MAJOR_VERSION);
                          ^
    /tmp/pip-install-ap4guj0b/wxpython/ext/wxWidgets/src/unix/glegl.cpp: In member function ‘wxGLContextAttrs& wxGLContextAttrs::MinorVersion(int)’:
    /tmp/pip-install-ap4guj0b/wxpython/ext/wxWidgets/src/unix/glegl.cpp:67:22: error: ‘EGL_CONTEXT_MINOR_VERSION’ was not declared in this scope
             AddAttribute(EGL_CONTEXT_MINOR_VERSION);
                          ^
 ```
... and so on. Is there a new dependency with 4.1.1 or is there a minimum version required for one of the pre-requisite packages?

Thanks in advance,

Steve.

**Comment by CiderMan** [comment]
I'm guessing that this might be an issue with the [changes on 1st September 2020](https://github.com/wxWidgets/wxWidgets/commits/master/src/unix/glegl.cpp)?

**Comment by swt2c** [comment]
Yeah, you probably need `libegl-dev` now as well.

**Comment by CiderMan** [comment]
Thanks for the reply. There is no `libegl-dev` in Jessie and `libegl1-mesa-dev`, `libwayland-egl1-mesa`, `libegl1-mesa` are all installed by the dependencies above.
In desperation, I've even tried installing `libva-egl1`, `glee-dev`, `libgtkglext1-dev` and `libgegl-dev` but still no dice!

**Comment by swt2c** [comment]
So, looks like Jessie doesn't have EGL 1.5.  The wxWidgets build process is supposed to fall back to GLX in that case, but it doesn't seem to be doing so.  I'll have to investigate further.

**Comment by swt2c** [comment]
I looked and I didn't realize Jessie was so old (end of life since mid-2020).  I'm going to say that it's probably not worth trying to support EGL < 1.5.  Even CentOS 7 has EGL 1.5.

**Comment by CiderMan** [comment]
OK, understood. Thanks! I'll have to stick with 4.1.0 for now but hopefully this will be the kick I can use to move us on to something more current!
