### ISSUE TITLE
wx.DirDialog doesn't word with wx.DD_MULTIPLE

### ISSUE THREAD

**Issue by hagemouse** [wxWidgets/Phoenix#1944]
wx: new version
python: 3.8.5

dlg = wx.DirDialog (self, style= wx.DD_MULTIPLE )
dlg.ShowModal()
dlg.getpaths(list)

but I get nothing

Anybody can help?
thank you.

**Comment by Infernio** [comment]
Ran into this as well. Seems like DirDialog doesn't support this, I used [MultiDirDialog](https://wxpython.org/Phoenix/docs/html/wx.lib.agw.multidirdialog.MultiDirDialog.html) for now.

**Comment by alphacheng** [comment]
Ran into this as well. thanks to infernio. MultiDirDialog may be useful.

**Comment by RobinD42** [comment]
This issue has been mentioned on **Discuss wxPython**. There might be relevant details there:

https://discuss.wxpython.org/t/correct-usage-of-wx-dirdialogs-getpaths-with-dd-multiple-style/35850/5

**Comment by alegnn** [comment]
Ran into this as well. Using MultiDirDialog but I'd love to see this issue fixed!
