### ISSUE TITLE
compiling wxPython 4.0.7-post2 fails on Debian10 

### ISSUE THREAD

**Issue by schloegl** [wxWidgets/Phoenix#1952]
**Operating system**:  Debian10(buster)
**wxPython version & source**:          
              4.0.7-post2 (obtained with "pip download wxPython==4.0.7.post2")
**Python version & source**:            
               stock  (Python 3.7.3 from Debian10) 

**Description of the problem**:
    compilation as suggested here https://wxpython.org/blog/2017-08-17-builds-for-linux-with-pip ),
`    pip wheel -v wxPython-4.0.7.post2.tar.gz  2>&1 | tee build.log
`
[build.log](https://github.com/wxWidgets/Phoenix/files/6357948/build.log)

fails with this error: 

```
 copying symlink wx/libwx_baseu-3.0.so -> build/lib.linux-x86_64-3.7/wx/libwx_baseu-3.0.so
  error: [Errno 2] No such file or directory: 'build/lib.linux-x86_64-3.7/wx/libwx_baseu-3.0.so'
  Building wheel for wxPython (setup.py): finished with status 'error'

```
although these packages 
```
libwxbase3.0-dev:amd64
libwxbase3.0-0v5:amd64

```
for providing  /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so are installed.

I'm trying to install "deeplabcut[gui]", but I  can not do this because wxPython 4.0.7 fails to install, and with 4.1.1 the application crashes. A bug report has been submitted here: 
https://github.com/DeepLabCut/DeepLabCut/issues/1198

**Comment by swt2c** [comment]
Duplicate of #1769.  Try downloading your version of pip to 41.0.1.

**Comment by schloegl** [comment]
the suggestion of https://github.com/rdaiello in https://github.com/DeepLabCut/DeepLabCut/issues/682
solved the issue for me.

`pip install setuptools==43.0.0
`
