### ISSUE TITLE
wx.BusyCursor contrext manager

### ISSUE THREAD

**Issue by Conkey100** [wxWidgets/Phoenix#196]
The BusyCursor no longer seems to have a context manager. The following works as expected in clasic:
import time
import wx
app = wx.App()
wx.Frame(None).Show()
with wx.BusyCursor():
    time.sleep(5)
app.MainLoop()

In Phoenix it raises "AttributeError: __exit__". Getting rid of the "with" block and using 
wait = wx.BusyCursor() ... del wait
works as expected.

**Comment by RobinD42** [comment]
Thanks.  I'm fixing it now and it will be in the next snapshot build.
