### ISSUE TITLE
Update to wxWidgets 3.1.5

### ISSUE THREAD

**Issue by imciner2** [wxWidgets/Phoenix#1961]
**Description of the problem**:

Version 4.1.1 bundles a post-3.1.4 but pre-3.1.5 version of wxWidgets as its internal version. Upstream wxWidgets has released 3.1.5 about a month ago, so it would be appreciated if a new release of Phoenix was made that uses 3.1.5 as its base wxWidgets version.

**Comment by imciner2** [comment]
Note that it probably needs https://github.com/wxWidgets/wxWidgets/pull/2366 as a patch to build - otherwise almost the entire `wxConfigBase` class doesn't have doxygen information.

**Comment by StefanBruens** [comment]
Also https://github.com/wxWidgets/Phoenix/issues/1961

**Comment by imciner2** [comment]
It probably also needs the following two commits from the docs update PR:

- https://github.com/wxWidgets/wxWidgets/pull/2367/commits/8482b501291460d665b22ee26f3b751e400aa886
- https://github.com/wxWidgets/wxWidgets/pull/2367/commits/c2d176e4a336ed1e5e9900a8a3e0befdbbf38f35

**Comment by niki-sp** [comment]
wxWidgets 3.1.5 has bug in wxBitmap MSW code for masks. wxWidgets/src/msw/bitmap.cpp from 3.1.6 fixes that
