### ISSUE TITLE
Segfault if pressing the expand arrow for a ribbonbar in an aui floating pane.

### ISSUE THREAD

**Issue by tatarize** [wxWidgets/Phoenix#1966]
**Operating system**: Linux
**wxPython version & source**: 4.1.1
**Python version & source**: 3.7.3

**Description of the problem**: Segfault if pressing the expand arrow for a ribbonbar in an aui floating pane.

https://gist.github.com/tatarize/d6de848fcfcd45e83dfb0bf4ec9178f4

Run crash demo. Press the down arrow on Shapes or Selection. (Sorry for the longer demo, just stuffed the ribbon bar demo into the aui demo)

* On GDK, operation systems expanding a minimized ribbonbar window while floating in an AUI pane causes Segfault.

https://user-images.githubusercontent.com/3302478/120142815-cf777d80-c193-11eb-8625-cee77e6fbd66.mp4

**Comment by swt2c** [comment]
Reproduced and reported upstream: https://trac.wxwidgets.org/ticket/19249

**Comment by tatarize** [comment]
This was fixed upstream.

Thank you.
