### ISSUE TITLE
TextCtrl CTOR breaks for text length above 65536 (MSW)

### ISSUE THREAD

**Issue by Traktormaster** [wxWidgets/Phoenix#1975]
**Operating system**:  Windows 10 64bit
**wxPython version & source**:         4.1.1 msw (phoenix) wxWidgets 3.1.5 installed from pypi wheel
**Python version & source**:            stock python 3.8.8

**Description of the problem**: If the TextCtrl is created with a text length of 65536 or greater it breaks unpredictably. If the same text is set with `SetValue` it works.

The error is very strange, it does not raise an exception from the init/ctor, but it (seems to be deterministically) cause one exception later.

The reproduction demo app has two buttons. Each show the same modal dialog that creates the text control, but populates its contents in different ways. Clicking the "ctor" version shows the stdout/stderr window with:
```
Traceback (most recent call last):
  File "C:/Users/gg/PycharmProjects/dev/text.py", line 60, in _on_btn0
    with TextCtor(self) as d:
  File "C:/Users/gg/PycharmProjects/dev/text.py", line 18, in __init__
    buttons = self.CreateButtonSizer(wx.OK)
wx._core.wxAssertionError: C++ assertion ""hWnd"" failed at ..\..\src\msw\window.cpp(580) in wxWindow::SetFocus(): can't set focus to invalid window

```
NOTE: The exception is raised after the TextCtrl creation and it will change if the code following it is different.

The demo reproduces the problem on MSW, the error is not present on Linux/GTK.

<details>
  <summary>Code Example (click to expand)</summary>

```python
import sys

import wx

BIG_TEXT = "\n".join(["x" * 100] * 1000)


class AbstractTextDialog(wx.Dialog):
    def __init__(self, parent):
        wx.Dialog.__init__(self, parent, wx.ID_ANY, "TextCtor", style=wx.DEFAULT_DIALOG_STYLE | wx.RESIZE_BORDER)
        self.SetSizeHints(320, 320)
        self.SetSize(600, 400)

        layout = wx.BoxSizer(wx.VERTICAL)
        self._text = self._create_text()
        layout.Add(self._text, 1, wx.ALL | wx.EXPAND, 4)
        buttons = self.CreateButtonSizer(wx.OK)
        if buttons:
            layout.Add(buttons, 0, wx.ALL | wx.EXPAND, 4)

        self.SetSizer(layout)

    def _create_text(self):
        raise NotImplementedError()


class TextCtor(AbstractTextDialog):
    def _create_text(self):
        text = wx.TextCtrl(self, wx.ID_ANY, BIG_TEXT, style=wx.TE_MULTILINE | wx.TE_READONLY | wx.TE_DONTWRAP)
        return text


class TextPostSet(AbstractTextDialog):
    def _create_text(self):
        text = wx.TextCtrl(self, wx.ID_ANY, style=wx.TE_MULTILINE | wx.TE_READONLY | wx.TE_DONTWRAP)
        text.SetValue(BIG_TEXT)
        return text


class Window(wx.Frame):
    def __init__(self):
        wx.Frame.__init__(self, None, wx.ID_ANY, "test")

        self._list = 0

        layout = wx.BoxSizer(wx.VERTICAL)

        self._btn0 = wx.Button(self, wx.ID_ANY, "set value in TextCtrl ctor")
        layout.Add(self._btn0)
        self.Bind(wx.EVT_BUTTON, self._on_btn0, self._btn0)

        self._btn1 = wx.Button(self, wx.ID_ANY, "set value of TextCtrl with SetValue")
        layout.Add(self._btn1)
        self.Bind(wx.EVT_BUTTON, self._on_btn1, self._btn1)

        self.SetSizer(layout)

    def _on_btn0(self, event):
        with TextCtor(self) as d:
            d.ShowModal()

    def _on_btn1(self, event):
        with TextPostSet(self) as d:
            d.ShowModal()


def main():
    app = wx.App(True)
    w = Window()
    w.Show()
    return app.OnRun()


if __name__ == "__main__":
    sys.exit(main())

```
</details>

**Comment by cbeytas** [comment]
Summary: Always use the `wx.TE_RICH` style on TextCtrls that may hold close to, or more than 64k characters of text. This flag only has effect on MSW, it is ignored on other platforms.

The original Windows text control was limited to 65535 characters. Internally it doubles line feeds `'\n'` to `'\r\n'` so those count twice. This is a limitation of the native widget I believe. There seems to be some code in wxPython that tries to switch to the new style automatically after the control has been created and more text is added (either with `SetValue` or `AppendText`) but it doesn't always work.

The documentation for `wx.TextCtrl` really needs to mention this. It has burned me before too.

**Comment by Traktormaster** [comment]
Oh, thank you for bringing this to my attention!

I'm not using any *rich* text features, so I've always skipped reading the description of those flags. This problem should be documented in a separate section like "Limitations" or "Platform limitations". I'm sure I would have read this detail if it was under such a section.

I'll close this issue, because it is actually known and documented, although not communicated well enough. Especially not in relation to how obscure and unexpected the issues it can cause.
