### ISSUE TITLE
wxBitmap is not handling data correctly when handed data

### ISSUE THREAD

**Issue by jimburnsphd** [wxWidgets/Phoenix#1977]
**Operating system**:
**wxPython version & source**:          
**Python version & source**:            
Win10, wxPython 4.1.1, Python 3.9.5

**Description of the problem**:
wxBitmap will not accept buffered data correctly.  Same buffered data can be passed to PIL successfully however.

<details>
  <summary>wxBitmap is not handling data correctly when handed data</summary>

```python
# Put code sample here
```
</details>

full runnable sample here
<http://burns.digitalsurvival.net/downloads/wxBitmap/test_wxBitmap_data.py>

two dependencies:
an image: <http://burns.digitalsurvival.net/downloads/wxBitmap/bmf_lmno_font.tga>
a font: <http://burns.digitalsurvival.net/downloads/wxBitmap/comic.ttf>

**Comment by niki-sp** [comment]
i got this with fixed src/msw/bitmap.cpp
`test wxApp> gui_sys_create_gui()
test wxApp>    wxSBM_testimage  Width:  464
test wxApp>    wxSBM_testimage Height:  480
test wxApp>    wxSBM_testimage  Depth:  24
test wxApp>   face bitmap, Pixel Mode:  2
test wxApp>   face bitmap,      Width:  23
test wxApp>   face bitmap,       Rows:  38
test wxApp>   face bitmap,      Pitch:  23
test wxApp>   length of tempBM_buffer:  874
test wxApp>       pilimg_test8   Mode:  L
test wxApp>       pilimg_test8  Width:  23
test wxApp>       pilimg_test8 Height:  38
test wxApp>       pilimg_test8  Bands:  ('L',)
test wxApp>      pilimg_test24   Mode:  RGB
test wxApp>      pilimg_test24  Width:  23
test wxApp>      pilimg_test24 Height:  38
test wxApp>      pilimg_test24  Bands:  ('R', 'G', 'B')
test wxApp>  length of tempBM8_buffer:  874
test wxApp> length of tempBM24_buffer:  2622
test wxApp>         wxBM8_temp   IsOK:  True
test wxApp>         wxBM8_temp  Width:  23
test wxApp>         wxBM8_temp Height:  38
test wxApp>         wxBM8_temp  Depth:  8, (should be 8)
test wxApp>        wxBM24_temp   IsOK:  True
test wxApp>        wxBM24_temp  Width:  23
test wxApp>        wxBM24_temp Height:  38
test wxApp>        wxBM24_temp  Depth:  24, (should be 24)
test wxApp>    wxSBM_testFT_WX  Width:  23
test wxApp>    wxSBM_testFT_WX Height:  38
test wxApp>    wxSBM_testFT_WX  Depth:  8, (should be 8)
test wxApp>   wxSBM_testFT_PIL  Width:  23
test wxApp>   wxSBM_testFT_PIL Height:  38
test wxApp>   wxSBM_testFT_PIL  Depth:  24, (should be 8)
`
![Screenshot from 2021-07-21 13-40-19](https://user-images.githubusercontent.com/17176395/126476333-81772a5e-dbd8-42fa-971d-638ce21b7519.png)
is this correct?

**Comment by jimburnsphd** [comment]
Awesome, I'll look into it.  

I'm a newbie to the github community, can you explain what this means for us using the pre-compiled python library?  

And can you say anything on what you did or found?  

Thanks so much!  Jim

**Comment by niki-sp** [comment]
> I'm a newbie to the github community, can you explain what this means for us using the pre-compiled python library?
I can send you set of recompiled wxWidgets DLLs which i hope are drop-in replacements.

> And can you say anything on what you did or found?
I found problem with masked bitmap and got "next" version of src/msw/bitmap.cpp as a fix
