### ISSUE TITLE
Wxwidgets + X11 + cygwin + win 10 compile  

### ISSUE THREAD

**Issue by manugoswami** [wxWidgets/Phoenix#1984]
Hi Developers,

WxWidgets fails to compile in cygwin -- windows 10

steps below

sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
cd /cygdrive/D/ons_cb_try/ons_wxwidgets/wxWidgets315
mkdir build-debug
cd build-debug
../configure --with-x11 --enable-debug

error below

eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
g++ -shared -o /cygdrive/D/ons_cb_try/ons_wxwidgets/wxWidgets315/build-debug/lib/cygwx_x11univu_media-3.1-5.dll  mediadll_mediactrlcmn.o mediadll_unix_mediactrl.o mediadll_mediactrl_gstplayer.o -L/cygdrive/D/ons_cb_try/ons_wxwidgets/wxWidgets315/build-debug/lib -L/cygdrive/D/ons_cb_try/ons_wxwidgets/wxWidgets315/build-debug/lib    -L/cygdrive/D/ons_cb_try/ons_wxwidgets/wxWidgets315/build-debug/lib  -Wl,--out-implib=/cygdrive/D/ons_cb_try/ons_wxwidgets/wxWidgets315/build-debug/lib/libwx_x11univu_media-3.1.dll.a          -lpangoxft-1.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lintl -lfontconfig -lfreetype -lXft -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lintl -lfontconfig -lfreetype -lX11 -lXext -lXinerama -lSM -lcairo -lpng -lz -ljpeg -ltiff -llzma  -lwxregexu-3.1  -lz -lsecret-1 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lintl -lpthread -liconv -lcurl -llzma  -lwx_x11univu_core-3.1 -lwx_baseu-3.1  -lz -lsecret-1 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lintl -lpthread -liconv -lcurl -llzma
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: mediadll_mediactrlcmn.o: in function `wxForceLinkbasewxmediabackends::wxForceLinkbasewxmediabackends()':
/cygdrive/D/ons_cb_try/ons_wxwidgets/wxWidgets315/build-debug/../src/common/mediactrlcmn.cpp:533: undefined reference to `_wx_link_dummy_func_basewxmediabackends()'
collect2: error: ld returned 1 exit status
make: *** [Makefile:14301: /cygdrive/D/ons_cb_try/ons_wxwidgets/wxWidgets315/build-debug/lib/cygwx_x11univu_media-3.1-5.dll] Error 1

eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

warm regards,
manu

**Comment by manugoswami** [comment]
Hi developers,

Any update, still issue is there. Wxwidgets fails to build for X11 in win 10. 

Kindly support to resolve urgently.

command sequence below

mkdir build_gtk2_shared_monolithic_unicode
cd build_gtk2_shared_monolithic_unicode
../configure --prefix=/cygdrive/D/ons_cb_try/ons_wx_widgets/ons_wxWidgets-315      --enable-xrc --enable-monolithic --enable-unicode --with-x11  --enable-debug
make

eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: monodll_mediactrlcmn.o: in function `wxForceLinkbasewxmediabackends::wxForceLinkbasewxmediabackends()':
/cygdrive/D/ons_cb_try/ons_wx_widgets/ons_wxWidgets-315/build_gtk2_shared_monolithic_unicode/../src/common/mediactrlcmn.cpp:533: undefined reference to `_wx_link_dummy_func_basewxmediabackends()'
collect2: error: ld returned 1 exit status
make: *** [Makefile:14118: /cygdrive/D/ons_cb_try/ons_wx_widgets/ons_wxWidgets-315/build_gtk2_shared_monolithic_unicode/lib/cygwx_x11univu-3.1-5.dll] Error 1

**Comment by manugoswami** [comment]
Hi developers,

Kindly at least confirm if wxwidgets can be built on X11+ CYGWIN + WIN 10 or not? 

Am i doing something new here which no-one has even tried it before ?  Or is it well known that it is not possible to build wxwidgets in X11 + CYGWIN + WIN10

Warm Regards,

Manu

**Comment by swt2c** [comment]
You might have better response if you ask on the wxWidgets mailing list or perhaps file a bug on wxWidgets Trac.  This issue tracker is for *wxPython*, the Python bindings for wxWidgets.
