### ISSUE TITLE
PyProgress is broken in demo

### ISSUE THREAD

**Issue by Correct-Syntax** [wxWidgets/Phoenix#1985]
**Operating system**: Windows 10, 64-bit
**wxPython version & source**: wxpython extras wheel, 4.1.1        
**Python version & source**:  python 3.9, from python.org          

**Description of the problem**:

In the wxpython demo, the pyprogress is broken with the below error:

<details>
  <summary>Error message (click to expand)</summary>

```python
Traceback (most recent call last):
  File "agw\PyProgress.py", line 107, in OnStartProgress
    dlg = PP.PyProgress(None, -1, "PyProgress Example",
  File "C:\Python39\lib\site-packages\wx\lib\agw\pyprogress.py", line 495, in __init__
    buttonSizer.Add(self._btnAbort, 0, sizerFlags, LAYOUT_MARGIN)
wx._core.wxAssertionError: C++ assertion "!(flags & wxALIGN_RIGHT)" failed at ..\..\src\common\sizer.cpp(2168) in wxBoxSizer::DoInsert(): Horizontal alignment flags are ignored in horizontal sizers

```
</details>

**Comment by swt2c** [comment]
Thanks, PR submitted.
