### ISSUE TITLE
Performance in AuiNotebook

### ISSUE THREAD

**Issue by sanhda** [wxWidgets/Phoenix#1989]
**Operating system**: Window
**wxPython version & source**:          
**Python version & source**: 3.8           

Hello everyone,

I'm working with wxpython AuiNotebook and have 1 problem with performance.

I have 1 notebook with 10 tabs and each tab take around 0.3-0.5s to load. Then it take 3-5s to load the entire notebook in my application.

Thank you so much if anyone could tell me how could I reduce the loading time for my application.

**Comment by infinity77** [comment]
That depends mostly on what you are doing in each tab itself. What do your tabs contain? Are you calling Freeze() on the AuiNotebook before adding all pages and Thaw() on the AuiNotebook when you’re done adding pages? Are you passing “select=False” when you do AddPage to the AuiNotebook?

**Comment by sanhda** [comment]
Thank you for your replay,
Each tab contain some ComboBox, NumCtrl and StaticBitmap.
I did call Freeze() and Thaw() before adding pages but not very helpful.
I used select=False for AddPage.

Is there anything else that could speed up the application?

**Comment by infinity77** [comment]
Yes, there is: provide more information and a sample app.

A couple of points:

1. Do you actually *need* all 10 tabs at startup? If not, consider creating those tabs when needed.
2. If yes, how about creating the full tab for the selected tab only (leaving the others as empty panels), then binding the EVT_AUINOTEBOOK_PAGE_CHANGED event and populating the full tab only when the user switches to the tab?

**Comment by sanhda** [comment]
Thank you for the advices,

1. I really need 10 tabs at startup.
2. Is it possible to make tabs run parallel by threading?

**Comment by infinity77** [comment]
No.

Anything that creates or interacts with wxPython objects needs to belong to the same thread as the wx.App . This is not a limitation of wxPython but of the underlying platform/OS.

But even if you could, wxPython objects are so complex that Python could only process one thread at the time (GIL friend, as usual) and you will get exactly zero speed-ups.

As far as I can see, you only have 3 possibilities:

- Keep things as they are, live with the 5 seconds startup
- Create the tabs only when needed
- Create empty tabs - except the selected one - and populate the empty ones when the user switches page to them

**Comment by sanhda** [comment]
Thank you so much.
