### ISSUE TITLE
310 Python IndentationErrors in docs/sphinx/rest_substitutions

### ISSUE THREAD

**Issue by cclauss** [wxWidgets/Phoenix#1996]
Discovered in #1994

Python 3 treats IndentationErrors as ___syntax errors___.

$ `flake8 ./docs/sphinx/rest_substitutions/snippets/python/converted --count --select=E9 --show-source --statistics`
```
[ ... ]
310   E999 IndentationError: unexpected indent
```

**Operating system**:
**wxPython version & source**:          
**Python version & source**:            

**Description of the problem**:

<details>
  <summary>Code Example (click to expand)</summary>

```python
# Put code sample here
```
</details>

**Comment by infinity77** [comment]
The warnings from flake are irrelevant (or used to be irrelevant) as the snippets in the rest_substitutions are used when the docs are built, pre-processed and put in the right format.

**Comment by cclauss** [comment]
Please read the commit message.  Python 3 will halt if any of these lines of code are run.

**Comment by infinity77** [comment]
But they will not be run as they are, that’s my point. They’re used to build the documentation. I should know it, I wrote quite a few bits of the documentation builder. 

Do you have an example **from the documentation itself** that doesn’t run?

**Comment by swt2c** [comment]
Those are code snippets, not runnable code.
