### ISSUE TITLE
Cannot build Windows binaries for Python 3.10: MSVC 14 fails with internal compiler error

### ISSUE THREAD

**Issue by BoarGules** [wxWidgets/Phoenix#2015]
**Operating system**:                       Windows 10 64-bit, version 21H1 (OS Build 19043,1237)
**wxPython version & source**:        wxPython-4.1.1.tar.gz from PyPI
**Python version & source**:            3.10.0 Stock install from python.org
**Description of the problem**:

I am doing a vanilla install in a new instance of Python 3.10 using `pip` 21.2.4. In response to `pip install wxPython`, `pip` attempts to build the Windows binaries. Two of the C++ files fail to compile. The compile of `sip_corewxDropTarget.cpp` fails as follows:

```
sip_corewxDropTarget.cpp
  [ 67/958] Compiling sip\cpp\sip_corewxDropSource.cpp
  sip_corewxWindowList.cpp
  c:\users\paulk\appdata\local\temp\pip-install-nj9hqgea\wxpython_c7c4dc1b0063453ba31539105792b5b2\sip\cpp\sip_corewxwindowlist.cpp(226): fatal error C1001: An internal error has occurred in the compiler.
  (compiler file 'msc1.cpp', line 1468)
   To work around this problem, try simplifying or changing the program near the locations listed above.
  Please choose the Technical Support command on the Visual C++ Help menu, or open the Technical Support help file for more information
  Internal Compiler Error in C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\CL.exe.  You will be prompted to send an error report to Microsoft later.
  INTERNAL COMPILER ERROR in 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\CL.exe'
      Please choose the Technical Support command on the Visual C++ Help menu, or open the Technical Support help file for more information
```
A similar failure occurs soon after for file `msc1.cpp`. 

Since this is a problem with the compiler and not the code, and it is unlikely that MS will offer a fix for such an old version, the obvious solution would be to use a later compiler. 

But the PyPI installer for `wxPython` insists on MSVC 14 and ignores any later version. I confirmed this by running the install on a system that had only MSVC 2019 installed. 

This insistence is due to a bug that existed in `setuptools` at the time, which was fixed about a year ago. The bug was that the presence check for the compiler in `distutils.msvc9compiler` (in the `setuptools` project's monkeypatch of `distutils`, not the now-deprecated real thing) was specific to a single version of the MS compiler. The code tries to find the file `vcvarsall.bat`, which exists in 14.x, but does not exist in 16.0 and later: its newer counterpart is `VsDevCmd.bat`. 

So even though the message says *Microsoft Visual C++ 14.0 **or greater** is required*, the code did not in fact know how to find any higher version (https://github.com/pypa/pip/issues/8969). This was fixed about a year ago and will now accept more recent MS compilers.

So the cure appears to be packaging `wxPython` with a more recent version of `distutils` that is prepared to accept a compiler that is not 2 versions behind.

I think the log extract above is a sufficient indication of the problem but I'm putting in the complete log as an attachment.
[wxPython build failure.txt](https://github.com/wxWidgets/Phoenix/files/7304467/wxPython.build.failure.txt)

**Comment by swt2c** [comment]
Does the problem still occur if you install the latest version of setuptools before trying to build wxPython?

**Comment by BoarGules** [comment]
Since this is turns out to be a `setuptools` issue I will report it there.
