### ISSUE TITLE
wx Slider move in opposite direction than expected

### ISSUE THREAD

**Issue by pbrod** [wxWidgets/Phoenix#2035]
**Operating system**:
Windows 10

**wxPython version & source**:        
wxpython                  4.1.1                    pypi_0    pypi  

**Python version & source**:           
anaconda: Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]

**Description of the problem**:

The wx.Slider move in opposite direction than expected. 
For example when I push 'page up', 'arrow up' or roll the mouse wheel up, it causes the slider to decrease its value.
Similarly if I push the 'page down', 'arrow down' or roll the mouse wheel down, it causes the slider to increase its value.
I would expect the opposite behaviour; up -> increase the slidervalue and down -> decrease the slider value.

It can be seen by running the [slider demo](https://github.com/wxWidgets/Phoenix/blob/master/demo/Slider.py)

**Comment by swt2c** [comment]
It does seem a little counter-intuitive, but that does seem to be the way the native widgets behave, at least on GTK.

**Comment by komoto48g** [comment]
Up-key is decremental. If you press the up-key in word or any editors, line-number or page-number will decrease.

**Comment by pbrod** [comment]
I also noticed that the 'left arrow' does the same thing as 'arrow up' on a slider.
Similarly 'right arrow' and 'down arrow' also does the same thing.
So it is a feature.
