### ISSUE TITLE
There is no way to deselect rows in a grid

### ISSUE THREAD

**Issue by freakyd** [wxWidgets/Phoenix#204]
I used to use this grid.Deselect(row) so I could clear a single row selection. Now I don't see that there is a way to deselect a row. You can deselect a row by selecting a new row, but that's definitely not what I need to do. I need to select then deselect a row by clicking on the label of the same row, toggling the row selection. I read the documentation and looked at the examples, but there was no clear answer.

**Comment by freakyd** [comment]
Currently what I do is grid.ClearSelection() followed by for row in selectedrows: grid.SelectRow(row,True)
that results in the same operation as grid.Deselect(row). But of course it could be extra operations, as far as I can see.

**Comment by swt2c** [comment]
This was due to `DeselectRow()` being missing from the interface headers in wxWidgets.

@RobinD42 can you please updates the wxWidgets submodule as I got this fixed in dc7acca.

**Comment by RobinD42** [comment]
The newly wrapped methods will be in tonight's build.
