### ISSUE TITLE
`copy_file` monkey patch fails when `bdist_wheel`

### ISSUE THREAD

**Issue by cykerway** [wxWidgets/Phoenix#2040]
This monkey patch seems to give errors when `bdist_wheel` as it can create (temporary) broken links. I'm having trouble reproducing it, but I can give a brief description here:

If `a` symlinks to `b` at source, and `a` is created before `b` at destination, then `a` becomes a broken link there. Somewhere in the bdist_wheel process is not happy with it and throws a file-not-exist error. I guess this is because `os.path.exists(...)` returns false on broken links during some verification.

I can build the wheel when commenting out this monkey patch, but you know then all links are followed and the wheel is bigger.

Env: wxPython 4.0.7 on Fedora 35. (GTK2 if that matters.)

https://github.com/wxWidgets/Phoenix/blob/9a8a9b019ceba2a5140d98ae3ce2a53ec8c3d577/setup.py#L278-L297

----

Not sure if this is related: https://github.com/pypa/pip/issues/3500

**Comment by cykerway** [comment]
Should you get interested, this diff shows the problem I encountered:

https://github.com/cykerway/Phoenix/commit/2be3e6a3cca44b8f821a3ce02554e804060e1664#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R277-R295

**Comment by swt2c** [comment]
I think this works around this same issue in master branch:
https://github.com/wxWidgets/Phoenix/commit/aa8430ad391d93391988451f43ecedd76ca4dd77

**Comment by swt2c** [comment]
> OK I can confirm the master branch has fixed it. Any chance we can have this patch backported to its Fedora SRPM? AFAIK the latest wxPython on Fedora 35 is still 4.0.7 which was released ~2 years ago. Would it be possible to upgrade to something like 4.1.1?

I'm thinking probably not on the backport because the Fedora package doesn't build a wheel.  It also doesn't use the bundled copy of wxWidgets - it uses the system copy of wxWidgets, which is at 3.0.5.1.  That's the main reason that the Fedora package has remained at 4.0.7.  I would consider upgrading wxPython once there is a stable release of wxWidgets 3.2.0, or perhaps another release on the 3.1.x branch.

**Comment by cykerway** [comment]
Right, I forgot the close relationship between wxPython and wxWidgets.

I just compiled wxPython 4.1.1. The problem doesn't exist in 4.1.1. Good.
