### ISSUE TITLE
Looks like on Mac wx.TheClipboard.IsSupported doesn't return correct value

### ISSUE THREAD

**Issue by tianzhuqiao** [wxWidgets/Phoenix#2042]
**Operating system**: macOS 11.4
**wxPython version & source**:       4.1.1
**Python version & source**:            3.7.0
**Description of the problem**:

Looks like "**wx.TheClipboard.IsSupported(wx.DataFormat(wx.DF_TEXT))**" always return false even if it does has text in clipboard. 

For example, first copy some text to clipboard; however the following code doesn't print anything 
```python
wx.TheClipboard.Open()
if wx.TheClipboard.IsSupported(wx.DataFormat(wx.DF_TEXT)):
    data = wx.TextDataObject()
    if wx.TheClipboard.GetData(data):
        print(data.GetText())
wx.TheClipboard.Close()
```
The following code print the text in clipboard correctly 
```python
wx.TheClipboard.Open()
data = wx.TextDataObject()
if wx.TheClipboard.GetData(data):
    print(data.GetText())
wx.TheClipboard.Close()
```
</details>

**Comment by swt2c** [comment]
Does it work if you use `wxDF_UNICODETEXT` instead?

**Comment by tianzhuqiao** [comment]
Thanks @swt2c.  `wxDF_UNICODETEXT`  returns `True` correctly. Is `wxDF_TEXT` only for ANSI string? It may be good to mention that in the doc
https://wxpython.org/Phoenix/docs/html/wx.DataFormat.html

**Comment by tianzhuqiao** [comment]
And the clipboard doesn't work for the [pyshell demo](https://github.com/wxWidgets/Phoenix/blob/master/demo/PyShell.py), as it only check the wxDF_TEXT.
https://github.com/wxWidgets/Phoenix/blob/9a8a9b019ceba2a5140d98ae3ce2a53ec8c3d577/wx/py/shell.py#L1364

Is it recommended to check both `wx.DF_TEXT` and  `wx.DF_UNICODETEXT`, or call `wx.TheClipboard.GetData` directly without checking?

**Comment by swt2c** [comment]
It appears as if `wx.DF_UNICODETEXT` should always be checked if wxWidgets is compiled with Unicode support, which I believe should always be the case in recent versions.  I'll try to update the examples and documentation.
