### ISSUE TITLE
`ScrolledPanel` crashes after quick `Destroy`

### ISSUE THREAD

**Issue by cykerway** [wxWidgets/Phoenix#2045]
**Operating system**: Fedora 35
**wxPython version & source**:   4.0.7       
**Python version & source**:      3.9      

**Description of the problem**:

`ScrolledPanel` calls `wx.CallAfter` in its method `SetupScrolling`. This causes app crash when this `ScrolledPanel` has a short life time. I'm wondering if it's possible to do similar job without using `wx.CallAfter`.

~~~python
wx.CallAfter(self._SetupAfter, scrollToTop) # scroll back to top after initial events
~~~

<details>
  <summary>Code Example (click to expand)</summary>

```python
#!/usr/bin/env python3

import wx
from wx.lib.scrolledpanel import ScrolledPanel

class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        super().__init__(*args, **kwds)
        self.panel = ScrolledPanel(self)
        self.panel.SetupScrolling()
        self.panel.Destroy()    # crash

if __name__ == '__main__':
    app = wx.App()
    MyFrame(None).Show()
    app.MainLoop()
```
</details>

**Comment by komoto48g** [comment]
I think this should be improved because any functions that can be called from `CallAfter` or `CallLater` should have `if self:` statement (dead-object guard). The `CallAfter` is required because it must be called after all layouts are complete.

**Comment by cykerway** [comment]
I monkey patched this onto version 4.0.7 and it worked. By the way, where does the doc say `if self:` is the correct way of checking a destroyed window object?

**Comment by komoto48g** [comment]
Here it is.
https://wxpython.org/Phoenix/docs/html/wx.Window.html#wx.Window.__nonzero__

**Comment by cykerway** [comment]
LOL thanks I was looking for `__bool__` and ain't got nothing.
