### ISSUE TITLE
Unable to combine some event ids in StdDialogButtonSizer

### ISSUE THREAD

**Issue by gddc** [wxWidgets/Phoenix#2057]
**Operating system**: Windows 11
**wxPython version & source**:  4.1.1 msw (phoenix) wxWidgets 3.1.5 (pypi)
**Python version & source**:      Python 3.9

**Description of the problem**:

Combining some ids in wx.StdDialogButtonSizer causes others to not layout properly (see sample). The first example fails to layout the two buttons with ID_OK and ID_SAVE. The second example, which uses ID_OK and ID_CANCEL, works as expected.

<details>
  <summary>Code Example (click to expand)</summary>

```python
import wx

def broken():
    dlg = wx.Dialog(None)
    bs = dlg.CreateButtonSizer(0)
    bs.AddButton(wx.Button(dlg, id=wx.ID_OK))
    bs.AddButton(wx.Button(dlg, id=wx.ID_SAVE))
    bs.Realize()
    dlg.SetSizerAndFit(bs)
    dlg.ShowModal()

def working():
    dlg = wx.Dialog(None)
    bs = dlg.CreateButtonSizer(0)
    bs.AddButton(wx.Button(dlg, id=wx.ID_OK))
    bs.AddButton(wx.Button(dlg, id=wx.ID_CANCEL))
    bs.Realize()
    dlg.SetSizerAndFit(bs)
    dlg.ShowModal()

if __name__ == "__main__":
    app = wx.App()
    broken()
    working()
```
</details>

**Comment by DietmarSchwertberger** [comment]
That's expected behaviour. You can have one button each for affirmative, cancel and negative action.
Having two affirmative buttons OK and SAVE at the same time would not comply to any style guide of any platform and so there is no point in using StdDialogButtonSizer.
