### ISSUE TITLE
GStreamer 0.10 is not available in Ubuntu 16.10

### ISSUE THREAD

**Issue by ccfiel** [wxWidgets/Phoenix#206]
I got this error doing a pip install wx using ubuntu 16.10. I did also try to install 

```
wget http://fr.archive.ubuntu.com/ubuntu/pool/main/g/gst-plugins-base0.10/libgstreamer-plugins-base0.10-0_0.10.36-1_amd64.deb
wget http://fr.archive.ubuntu.com/ubuntu/pool/universe/g/gstreamer0.10/libgstreamer0.10-0_0.10.36-1.5ubuntu1_amd64.deb
sudo dpkg -i libgstreamer*.deb
```

Still got the same problem. Any ideas?

```
  chhecking for cairo_push_group... yes
  checking for GST... configure: WARNING: GStreamer 0.10 not available, falling back to 0.8
  checking for GST... configure: WARNING: GStreamer 0.8/0.10 not available.
  configure: error: GStreamer not available
  Error running configure
  ERROR: failed building wxWidgets
  Traceback (most recent call last):
    File "build.py", line 1184, in cmd_build_wx
```

**Comment by eldarkg** [comment]
@ccfiel You need to install next packages from [Ubuntu 16.04](http://packages.ubuntu.com/xenial/):
gir1.2-gst-plugins-base-0.10_0.10.36-2_amd64.deb
gir1.2-gstreamer-0.10_0.10.36-1.5ubuntu1_amd64.deb
libgstreamer0.10-0_0.10.36-1.5ubuntu1_amd64.deb
libgstreamer0.10-dev_0.10.36-1.5ubuntu1_amd64.deb
libgstreamer-plugins-base0.10-0_0.10.36-2_amd64.deb
libgstreamer-plugins-base0.10-dev_0.10.36-2_amd64.deb

**Comment by swt2c** [comment]
wxWidgets 3.0 should now have gstreamer 1.0 support via 501b377.

@RobinD42 can you please bump the wxWidgets subproject commit to pick up these changes?

**Comment by RobinD42** [comment]
@swt2c, yep. I did it as soon as I noticed your change had been merged.  I'm waiting on one more build and a test of an additional change and then I'll push them.
