### ISSUE TITLE
AttributeError: 'WebView' object has no attribute 'AddScriptMessageHandler'

### ISSUE THREAD

**Issue by JT-Potato** [wxWidgets/Phoenix#2061]
**Operating system**: Windows 11 Build 22000.376
**wxPython version & source**:  PyPi, wxPython 4.1.1        
**Python version & source**:  Stock Python 3.9.9          

**Description of the problem**:
`AttributeError: 'WebView' object has no attribute 'AddScriptMessageHandler'`
Using the Edge backend, I can't add a scriptmessagehandler for inter-process communication.

Actually, if anybody has a guide on how to get IPC working on wxPython, I'd appreciate it a lot. Documentation and tutorials for wxPython seem quite rare (aside from wxPython's own documentation)

<details>
  <summary>Code Example (click to expand)</summary>

```python
import wx 
import wx.html2 

class MyBrowser(wx.Dialog): 
  def __init__(self, *args, **kwds): 
    wx.Dialog.__init__(self, *args, **kwds) 
    sizer = wx.BoxSizer(wx.VERTICAL) 
    self.browser = wx.html2.WebView.New(parent=self, backend=wx.html2.WebViewBackendEdge)
    self.browser.AddScriptMessageHandler("webview")
    sizer.Add(self.browser, 1, wx.EXPAND, 10) 
    self.SetSizer(sizer) 
    self.SetSize((700, 700)) 

if __name__ == '__main__': 
  app = wx.App() 
  dialog = MyBrowser(None, -1) 
  dialog.browser.LoadURL("http://www.google.com") 
  dialog.Show() 
  app.MainLoop() 
```
</details>

**Comment by swt2c** [comment]
`AddScriptMessageHandler` was added after wxPython 4.1.1, so you'll need to wait for the next release for that.

**Comment by JT-Potato** [comment]
Do we have a roadmap for the next few releases? If not, I could fall back on using webservers, but the issue with webservers is whether or not there would be another app running on the same port. Are there any workarounds, then?

**Comment by swt2c** [comment]
> Do we have a roadmap for the next few releases? 4.1.1 has been around for over a year now, with no signs of a new version soon.

It seems like a new release might be coming soon?

> If not, I could fall back on using webservers, but the issue with webservers is whether or not there would be another app running on the same port. Are there any workarounds, then?

You could try running one of the snapshot builds: https://wxpython.org/pages/downloads/

**Comment by JT-Potato** [comment]
The snapshot builds do work, thanks for the suggestion! I hope they're stable enough.
Are there any resources on how to communicate from Python to JS? I'm not 100% sure how to use an events system with `AddUserScript` and how `WEBVIEW_INJECT_AT_DOCUMENT_START` works when scripts are injected during the runtime of the app.

**Comment by swt2c** [comment]
If you can speak C++, the best reference is probably the C++ webview sample:
https://github.com/wxWidgets/wxWidgets/blob/master/samples/webview/webview.cpp

This functionality is too new that wxPython hasn't caught up with documentation or demos.

**Comment by JT-Potato** [comment]
I'll start looking through it. Thanks!

**Comment by small-brain-ferret** [comment]
wow so cool sheesh shie ! epic shie !
