### ISSUE TITLE
Ubuntu 20.04 / wxPython 4.1.1: PyPlot Example + Enable Point Label = Empty white Sheet

### ISSUE THREAD

**Issue by roland171281** [wxWidgets/Phoenix#2075]
**Operating system**: Kubuntu 20.04 
**wxPython version & source**:  pip3 wxpython 4.1.1 and apt wxpython 4.0.7
**Python version & source**:       Python 3.8.10 (apt)

**Description of the problem**:
Execute PyPlot.py from examples and enable "Options ->  Enable Point Label".
This causes that the diagram will be erased (empty) and only the point labels are drawed or there is just a black area.

WIN64+Py3.7+WxPython4.0.7post2 works fine.
CENTOS7+Python 3.6.8+WxPython4.1.1 from pip3 fails.

If I'm using the "darwin" mac method for dcs buffer (plotcanvas.py@2220) it works fine again.
I replaced the sys.platform logics to only react on windows.

<details>
  <summary>Code Example (click to expand)</summary>

```python
    def _drawPointLabel(self, mDataDict):
        """Draws and erases pointLabels"""
        width = self._Buffer.GetWidth()
        height = self._Buffer.GetHeight()
        if sys.platform == "win32":
            tmp_Buffer = wx.Bitmap(width, height)
            dcs = wx.MemoryDC()
            dcs.SelectObject(tmp_Buffer)
            dcs.Clear()
        else:
            tmp_Buffer = self._Buffer.GetSubBitmap((0, 0, width, height))
            dcs = wx.MemoryDC(self._Buffer)
        self._pointLabelFunc(dcs, mDataDict)  # custom user pointLabel func
        
        dc = wx.ClientDC(self.canvas)
        dc = wx.BufferedDC(dc, self._Buffer)
        # this will erase if called twice
        dc.Blit(0, 0, width, height, dcs, 0, 0, self._logicalFunction)
        if sys.platform != "win32":
            self._Buffer = tmp_Buffer
```
</details>

Thank you for your hard work and if you need more information just let me know!

**Comment by swt2c** [comment]
Hi, I do see the same problem you do on Linux.  However, if I make the changes to allow the "macos" code to run on Linux, the point labels are drawn, but they do not get cleared when moving to a different point (ie, they accumulate on the plot).  Is that the expected behavior?

**Comment by swt2c** [comment]
You are right, I messed up the logic when I tested it earlier.  It does work fine and I made a pull request with your suggestions.  Thanks!

**Comment by roland171281** [comment]
Hi Scott,
no problem - thank you for the immediate response and the pull request.
Have a nice day
Roland
