### ISSUE TITLE
pip install get stuck (run forever) windows 7 / Python 3.6

### ISSUE THREAD

**Issue by WiliTest** [wxWidgets/Phoenix#208]
I just posted [on the forum](https://groups.google.com/forum/#!searchin/wxpython-dev/3.6%7Csort:relevance/wxpython-dev/veUI2u5ira4/kSViaQ_4AwAJ), I thought I should also report the issue here. So just in case:

I tried to pip install on win7 x64 using pip: 
`pip install --upgrade  --trusted-host wxpython.org --pre -f http://wxpython.org/Phoenix/snapshot-builds/ wxPython_Phoenix`

I don't get any error, the installation never stop (I ran it 2 times, waiting 20mn, no success)

```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.


C:\Windows\system32>pip install --upgrade  --trusted-host wxpython.org --pre -f
http://wxpython.org/Phoenix/snapshot-builds/ wxPython_Phoenix
Collecting wxPython_Phoenix
  Downloading https://wxpython.org/Phoenix/snapshot-builds/wxPython_Phoenix-3.0.
3.dev2749+f803d20.tar.gz (50.8MB)
    100% |████████████████████████████████| 50.8MB 1.5MB/s
Requirement already up-to-date: six in c:\users\Me\appdata\local\programs\pyth
on\python36\lib\site-packages (from wxPython_Phoenix)
Installing collected packages: wxPython-Phoenix
  Running setup.py install for wxPython-Phoenix ... -
```

**Comment by RobinD42** [comment]
Answered [here](https://groups.google.com/d/msg/wxpython-dev/veUI2u5ira4/7GgOXD3GBAAJ).

**Comment by sudochop** [comment]
@RobinD42 I'm running in to this issue as well but that link doesn't work. Could you help? Thanks!

**Comment by RobinD42** [comment]
The important part of that message is: 

> Depending on your machine it could take a very long time to build, and IIRC pip seems to be hiding most of the build output these days so it may still be in the process of building at 20minutes but you can't tell. You may have better luck getting the source tarball and follow the instructions in README.rst for building it with the build.py script, then you can see the output from the build and know whether it is truly stuck or still chugging along.

If you use pip's verbosity flag then you should be able to see the output of the build as it happens. Also, there are newer instructions on building from source using pip [here](https://wxpython.org/blog/2017-08-17-builds-for-linux-with-pip/index.html).

**Comment by sudochop** [comment]
Thanks for the quick reply. Yup just took a long time and `--verbose` hides all the output until it's done so it looks like nothing is happening.

**Comment by Beijing-corn87** [comment]
Can you just monitor its usage in htop (in linux) ?
