### ISSUE TITLE
Installation of wxPython on WIndows 11

### ISSUE THREAD

**Issue by RandyERaymond** [wxWidgets/Phoenix#2089]
**Operating system**: 
Processor	Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz   3.19 GHz
Installed RAM	32.0 GB (31.8 GB usable)
System type	64-bit operating system, x64-based processor
Edition	Windows 11 Home
Version	21H2
Installed on	‎11/‎3/‎2021
OS build	22000.438

**wxPython version & source**:          N/A
**Python version & source**:            Python 3.10.2

**Description of the problem**: 

<< this is the Windows batch file that I run >>
D:\MyPrograms\Python310\scripts\pip3.exe install wxPython==4.1.1
pause

<< this is the result >>
C:\WINDOWS\system32>D:\MyPrograms\Python310\scripts\pip3.exe install wxPython==4.1.1
Collecting wxPython==4.1.1
  Using cached wxPython-4.1.1.tar.gz (66.0 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pillow in d:\myprograms\python310\lib\site-packages (from wxPython==4.1.1) (9.0.0)
Requirement already satisfied: six in d:\myprograms\python310\lib\site-packages (from wxPython==4.1.1) (1.16.0)
Requirement already satisfied: numpy in d:\myprograms\python310\lib\site-packages (from wxPython==4.1.1) (1.22.1)
Building wheels for collected packages: wxPython
  Building wheel for wxPython (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'D:\MyPrograms\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Randa\\AppData\\Local\\Temp\\pip-install-av8bm_zb\\wxpython_30cc754fe32f42abaf39e061131793f3\\setup.py'"'"'; __file__='"'"'C:\\Users\\Randa\\AppData\\Local\\Temp\\pip-install-av8bm_zb\\wxpython_30cc754fe32f42abaf39e061131793f3\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Randa\AppData\Local\Temp\pip-wheel-opz2icp2'
       cwd: C:\Users\Randa\AppData\Local\Temp\pip-install-av8bm_zb\wxpython_30cc754fe32f42abaf39e061131793f3\
  Complete output (49 lines):
  D:\MyPrograms\Python310\lib\site-packages\setuptools\dist.py:723: UserWarning: Usage of dash-separated 'license-file' will not be supported in future versions. Please use the underscore name 'license_file' instead
    warnings.warn(
  D:\MyPrograms\Python310\lib\site-packages\setuptools\dist.py:300: DistDeprecationWarning: use_2to3 is ignored.
    warnings.warn(f"{attr} is ignored.", DistDeprecationWarning)
  running bdist_wheel
  running build
  Will build using: "D:\MyPrograms\Python310\python.exe"
  3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]
  Python's architecture is 64bit
  cfg.VERSION: 4.1.1

  Running command: build
  Running command: build_wx
  Command '"D:\MyPrograms\Python310\python.exe" -c "import setuptools, distutils.msvc9compiler as msvc; mc = msvc.MSVCCompiler(); mc.initialize(); print(mc.cc)"' failed with exit code 1.
  Traceback (most recent call last):

    File "<string>", line 1, in <module>

    File "D:\MyPrograms\Python310\lib\site-packages\setuptools\_distutils\msvc9compiler.py", line 371, in initialize

      vc_env = query_vcvarsall(VERSION, plat_spec)

    File "D:\MyPrograms\Python310\lib\site-packages\setuptools\msvc.py", line 140, in msvc9_query_vcvarsall

      return EnvironmentInfo(arch, ver).return_env()

    File "D:\MyPrograms\Python310\lib\site-packages\setuptools\msvc.py", line 1740, in return_env

      [self.VCIncludes,

    File "D:\MyPrograms\Python310\lib\site-packages\setuptools\msvc.py", line 1282, in VCIncludes

      return [join(self.si.VCInstallDir, 'Include'),

    File "D:\MyPrograms\Python310\lib\site-packages\setuptools\msvc.py", line 840, in VCInstallDir

      raise distutils.errors.DistutilsPlatformError(msg)

  distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.2 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  Finished command: build_wx (0.395s)
  Finished command: build (0.395s)
  WARNING: Building this way assumes that all generated files have been
  generated already.  If that is not the case then use build.py directly
  to generate the source and perform the build stage.  You can use
  --skip-build with the bdist_* or install commands to avoid this
  message and the wxWidgets and Phoenix build steps in the future.

  "D:\MyPrograms\Python310\python.exe" -u build.py build
  Command '"D:\MyPrograms\Python310\python.exe" -u build.py build' failed with exit code 1.
  ----------------------------------------
  ERROR: Failed building wheel for wxPython
  Running setup.py clean for wxPython
Failed to build wxPython
Installing collected packages: wxPython
    Running setup.py install for wxPython ... error
    ERROR: Command errored out with exit status 1:
     command: 'D:\MyPrograms\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Randa\\AppData\\Local\\Temp\\pip-install-av8bm_zb\\wxpython_30cc754fe32f42abaf39e061131793f3\\setup.py'"'"'; __file__='"'"'C:\\Users\\Randa\\AppData\\Local\\Temp\\pip-install-av8bm_zb\\wxpython_30cc754fe32f42abaf39e061131793f3\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Randa\AppData\Local\Temp\pip-record-4acusde_\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\MyPrograms\Python310\Include\wxPython'
         cwd: C:\Users\Randa\AppData\Local\Temp\pip-install-av8bm_zb\wxpython_30cc754fe32f42abaf39e061131793f3\
    Complete output (51 lines):
    D:\MyPrograms\Python310\lib\site-packages\setuptools\dist.py:723: UserWarning: Usage of dash-separated 'license-file' will not be supported in future versions. Please use the underscore name 'license_file' instead
      warnings.warn(
    D:\MyPrograms\Python310\lib\site-packages\setuptools\dist.py:300: DistDeprecationWarning: use_2to3 is ignored.
      warnings.warn(f"{attr} is ignored.", DistDeprecationWarning)
    running install
    D:\MyPrograms\Python310\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running build
    Will build using: "D:\MyPrograms\Python310\python.exe"
    3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]
    Python's architecture is 64bit
    cfg.VERSION: 4.1.1

    Running command: build
    Running command: build_wx
    Command '"D:\MyPrograms\Python310\python.exe" -c "import setuptools, distutils.msvc9compiler as msvc; mc = msvc.MSVCCompiler(); mc.initialize(); print(mc.cc)"' failed with exit code 1.
    Traceback (most recent call last):

      File "<string>", line 1, in <module>

      File "D:\MyPrograms\Python310\lib\site-packages\setuptools\_distutils\msvc9compiler.py", line 371, in initialize

        vc_env = query_vcvarsall(VERSION, plat_spec)

      File "D:\MyPrograms\Python310\lib\site-packages\setuptools\msvc.py", line 140, in msvc9_query_vcvarsall

        return EnvironmentInfo(arch, ver).return_env()

      File "D:\MyPrograms\Python310\lib\site-packages\setuptools\msvc.py", line 1740, in return_env

        [self.VCIncludes,

      File "D:\MyPrograms\Python310\lib\site-packages\setuptools\msvc.py", line 1282, in VCIncludes

        return [join(self.si.VCInstallDir, 'Include'),

      File "D:\MyPrograms\Python310\lib\site-packages\setuptools\msvc.py", line 840, in VCInstallDir

        raise distutils.errors.DistutilsPlatformError(msg)

    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.2 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    Finished command: build_wx (0.401s)
    Finished command: build (0.401s)
    WARNING: Building this way assumes that all generated files have been
    generated already.  If that is not the case then use build.py directly
    to generate the source and perform the build stage.  You can use
    --skip-build with the bdist_* or install commands to avoid this
    message and the wxWidgets and Phoenix build steps in the future.

    "D:\MyPrograms\Python310\python.exe" -u build.py build
    Command '"D:\MyPrograms\Python310\python.exe" -u build.py build' failed with exit code 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'D:\MyPrograms\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Randa\\AppData\\Local\\Temp\\pip-install-av8bm_zb\\wxpython_30cc754fe32f42abaf39e061131793f3\\setup.py'"'"'; __file__='"'"'C:\\Users\\Randa\\AppData\\Local\\Temp\\pip-install-av8bm_zb\\wxpython_30cc754fe32f42abaf39e061131793f3\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Randa\AppData\Local\Temp\pip-record-4acusde_\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\MyPrograms\Python310\Include\wxPython' Check the logs for full command output.

---------------------------------------------------
Sincerely Randy Raymond

**Comment by oleksis** [comment]
The wxPython 4.1.1 build script for Python 3.10 no work properly. Try [this wheel](https://gist.github.com/oleksis/8637f096b97e18e00786e46465e97b34#download-wheel) and check the build process

**Comment by RandyERaymond** [comment]
I appreciate your comment, but I do not know how to do builds. I used to simply install from a Windows installation, and have switched to the PyPi process with PIP. Now that does not work. 

Does the wxPython 3.9 script work? Are you saying I should move to a lower version of wxPython? If so, you really should remove version 3.10 from the Windows scripting install options. I have already uninstalled my previous version so this will be a bit of a time waster for me. That is okay, as long as I know. But you should inform your users of that.

Sincerely, Randy Raymond

**Comment by oleksis** [comment]
@RandyERaymond  [the wheel i share (wxPython 4.1.2a1)](https://github.com/oleksis/youtube-dl-gui/releases/download/v1.8.2/wxPython-4.1.2a1-cp310-cp310-win_amd64.whl) work with Python 3.10. The project is working in the stable version compatible with Python 3.10

**Comment by efahl** [comment]
Or you can install the latest build, which also includes support for Py 3.10 (along with some bug fixes and removal of deprecated code).  
```
python -m pip install --force --pre -f https://wxpython.org/Phoenix/snapshot-builds wxPython
```

**Comment by RandyERaymond** [comment]
This worked great! I downloaded the wheel file, and then installed it. I really appreciate your help with this.

Sincerely

**Comment by cnervi** [comment]
> python -m pip install --force --pre -f https://wxpython.org/Phoenix/snapshot-builds wxPython

I love you

**Comment by djongepier** [comment]
Worked for me too, thank you very much!

**Comment by cnervi** [comment]
@djongepier this:
`pip install wxPython310`
works as well

**Comment by tester0077** [comment]
Neither 
pip install wxPython310
nor 
python -m pip install --force --pre -f https://wxpython.org/Phoenix/snapshot-builds wxPython
works for me :-(
Error output:
python -m pip install --force --pre -f https://wxpython.org/Phoenix/snapshot-builds wxPython
Looking in links: https://wxpython.org/Phoenix/snapshot-builds
Collecting wxPython
  Using cached https://wxpython.org/Phoenix/snapshot-builds/wxPython-4.2.1a1.dev5539%2B906adf71.tar.gz (73.7 MB)
  Preparing metadata (setup.py) ... done
Collecting pillow
  Using cached Pillow-9.3.0-cp311-cp311-win_amd64.whl (2.5 MB)
Collecting six
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting numpy
  Using cached numpy-1.24.0rc2-cp311-cp311-win_amd64.whl (14.8 MB)
Installing collected packages: six, pillow, numpy, wxPython
  Attempting uninstall: six
    Found existing installation: six 1.16.0
    Uninstalling six-1.16.0:
      Successfully uninstalled six-1.16.0
  Attempting uninstall: pillow
    Found existing installation: Pillow 9.3.0
    Uninstalling Pillow-9.3.0:
      Successfully uninstalled Pillow-9.3.0
  Attempting uninstall: numpy
    Found existing installation: numpy 1.24.0rc2
    Uninstalling numpy-1.24.0rc2:
      Successfully uninstalled numpy-1.24.0rc2
  DEPRECATION: wxPython is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for wxPython ... error
  error: subprocess-exited-with-error

  × Running setup.py install for wxPython did not run successfully.
  │ exit code: 1
  ╰─> [42 lines of output]
      C:\Users\arnold\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\dist.py:770: UserWarning: Usage of dash-separated 'license-file' will not be supported in future versions. Please use the underscore name 'license_file' instead
        warnings.warn(
      C:\Users\arnold\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\config\setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      C:\Users\arnold\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\dist.py:316: DistDeprecationWarning: use_2to3 is ignored.
        warnings.warn(f"{attr} is ignored.", DistDeprecationWarning)
      running install
      C:\Users\arnold\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      WARNING: Building this way assumes that all generated files have been
      generated already.  If that is not the case then use build.py directly
      to generate the source and perform the build stage.  You can use
      --skip-build with the bdist_* or install commands to avoid this
      message and the wxWidgets and Phoenix build steps in the future.

      "C:\Users\arnold\AppData\Local\Programs\Python\Python311\python.exe" -u build.py build
      Will build using: "C:\Users\arnold\AppData\Local\Programs\Python\Python311\python.exe"
      3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]
      Python's architecture is 64bit
      cfg.VERSION: 4.2.1a1.dev5539+906adf71

      Running command: build
      Running command: build_wx
      Traceback (most recent call last):
        File "C:\Users\arnold\AppData\Local\Temp\pip-install-ew1azfdz\wxpython_f7e13a2857174ab184918d091daf8b0c\build.py", line 2372, in <module>
          main(sys.argv[1:])
        File "C:\Users\arnold\AppData\Local\Temp\pip-install-ew1azfdz\wxpython_f7e13a2857174ab184918d091daf8b0c\build.py", line 208, in main
          function(options, args)
        File "C:\Users\arnold\AppData\Local\Temp\pip-install-ew1azfdz\wxpython_f7e13a2857174ab184918d091daf8b0c\build.py", line 1452, in cmd_build
          cmd_build_wx(options, args)
        File "C:\Users\arnold\AppData\Local\Temp\pip-install-ew1azfdz\wxpython_f7e13a2857174ab184918d091daf8b0c\build.py", line 1462, in cmd_build_wx
          checkCompiler()
        File "C:\Users\arnold\AppData\Local\Temp\pip-install-ew1azfdz\wxpython_f7e13a2857174ab184918d091daf8b0c\build.py", line 795, in checkCompiler
          info = getMSVCInfo(PYTHON, arch, set_env=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\arnold\AppData\Local\Temp\pip-install-ew1azfdz\wxpython_f7e13a2857174ab184918d091daf8b0c\buildtools\config.py", line 993, in getMSVCInfo
          from attrdict import AttrDict
      ModuleNotFoundError: No module named 'attrdict'
      Finished command: build_wx (0.6s)
      Finished command: build (0.6s)
      Command '"C:\Users\arnold\AppData\Local\Programs\Python\Python311\python.exe" -u build.py build' failed with exit code 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.     
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> wxPython

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by DJMoffinz** [comment]
have tried all methods in this thread so far and i have the same problem as tester0077, but am on windows 10
```
OS Name	Microsoft Windows 10 Home
Version	10.0.19045 Build 19045
Python 3.11.3
```

**Comment by oleksis** [comment]
Read this [comment](https://github.com/wxWidgets/Phoenix/issues/2296#issuecomment-1426606107) for install wxPython on Windows (Python 3.11)
