### ISSUE TITLE
Check box background is white

### ISSUE THREAD

**Issue by kitovyj** [wxWidgets/Phoenix#209]
Windows 10 64-bit:  Checkbox controls' background is white, not the default window background color(other controls are ok).

**Comment by RobinD42** [comment]
Unless I am misunderstanding something I believe that this behavior is correct.

**Comment by RobinD42** [comment]
Please reopen and add a screenshot if you disagree, and an example of checkboxes in another native app that are different colors than the wx checkbox would be helpful too.
