### ISSUE TITLE
High DPI in Windows 10

### ISSUE THREAD

**Issue by keck-in-space** [wxWidgets/Phoenix#2097]
**Operating system**: Windows 10
**wxPython version & source**: pypi 4.1.1
**Python version & source**:  Python 3.9.10, installed from website

**Description of the problem**:

I do not know how to enable high DPI support on Windows. I tried searching the docs, and found this [link](https://docs.wxpython.org/high_dpi_overview.html#microsoft-windows), which states "Todo: This section still needs to be updated to include Python-specific instructions."

Are there any Python specific instructions? I wasn't able to find the file mentioned in the section linked above.

**Comment by enkore** [comment]
The long and short of it is that you need to have an .exe with a manifest specifying HiDPI or it won't work properly across Windows 10 versions - HiDPI will never work correctly with pythonw.exe running a script. You can either use any of the python-to-exe tools (py2exe, pyinstaller, nuitka, ...) or write your own bootstrapper in C or C#. The correct manifest is this one: https://github.com/wxWidgets/wxWidgets/blob/419f899b3d100b7c2bdc22ffebdb969c19fe1a42/include/wx/msw/wx_dpi_aware_pmv2.manifest

**Comment by keck-in-space** [comment]
Great. Thank you!
