### ISSUE TITLE
wxpython 4.1.1 from pip fails on Pop/Ubuntu 21.10

### ISSUE THREAD

**Issue by DestyNova** [wxWidgets/Phoenix#2100]
**Operating system**: 
**wxPython version & source**:          4.1.1 from pypi
**Python version & source**:            3.9.7 (not 100% sure how I have this; apt tells me it's 3.9.4, and the laptop is only a few months old)

**Description of the problem**:

In Ubuntu 21.10, the library `libwebkitgtk-3.0.so.0` doesn't seem to be provided anymore, but it's needed by the `wx.html2` module:

```
$ pip3 install wxpython
Collecting wxpython
Using cached wxPython-4.1.1-cp39-cp39-linux_x86_64.whl
Requirement already satisfied: pillow in /home/omf/.local/lib/python3.9/site-packages (from wxpython) (9.0.0)
Requirement already satisfied: numpy in /home/omf/.local/lib/python3.9/site-packages (from wxpython) (1.22.1)
Requirement already satisfied: six in /home/omf/.local/lib/python3.9/site-packages (from wxpython) (1.16.0)
Installing collected packages: wxpython
Successfully installed wxpython-4.1.1

$ python3
Python 3.9.7 (default, Sep 10 2021, 14:59:43) 
[GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import wx.html2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/omf/.local/lib/python3.9/site-packages/wx/html2.py", line 15, in <module>
    from ._html2 import *
ImportError: libwebkitgtk-3.0.so.0: cannot open shared object file: No such file or directory
```
Instead, we have `libwebkit2gtk-4.0.so.37` which I was hoping would be compatible. But when I tried making a hardlink named `libwebkitgtk-3.0.so.0`, importing `wx.html2` then failed with:

```
ImportError: /home/omf/.local/lib/python3.9/site-packages/wx/libwx_gtk3u_webview-3.1.so.5: undefined symbol: webkit_web_view_can_redo
```

I'll try building from source.

**Comment by swt2c** [comment]
Where did you get `wxPython-4.1.1-cp39-cp39-linux_x86_64.whl`?  wxPython doesn't provide wheels for Ubuntu 21.10.  You'll have to build it yourself for now.  But make sure you have the package `libwebkit2gtk-4.0-dev` installed before you build if you want to use wx.html2.

**Comment by DestyNova** [comment]
Hi, that was probably a remnant from trying to install the older wheel. But the result was the same with the version installed with `pip install wxpython`.
I was able to build it from source just now with no problems by following the [wheel-building instructions](https://wxpython.org/blog/2017-08-17-builds-for-linux-with-pip/index.html):

```
# download and build
mkdir tmp && cd tmp
sudo apt install python3.9-venv
python3 -m venv builder_py
source builder_py/bin/activate
cd ..
pip install -U pip
pip install -U six wheel setuptools
pip download wxPython
pip wheel -v wxPython-4.1.1.tar.gz 2>&1 | tee build.log
pip install wxPython-4.1.1-cp39-cp39-linux_x86_64.whl
python -c 'import wx.html2;print("ok")'
deactivate

pip3 install --force-reinstall wxPython-4.1.1-cp39-cp39-linux_x86_64.whl
```
Would it be possible to update the binary distributed version so people can get it working in Ubuntu 21.10 w/ `pip3 install wxpython`?

**Comment by swt2c** [comment]
There isn't a binary distributed version for Linux. `pip3 install wxpython` will compile it.

**Comment by DestyNova** [comment]
Ah, okay. In that case, I guess the problem might have been a cached copy of the old compiled version from before I upgraded to 21.10. I'll close this then.
