### ISSUE TITLE
wxPyDeprecationWarning: wx.lib.pubsub has been deprecated, plese migrate your code to use pypubsub, available on PyPI.   warnings.warn('wx.lib.pubsub has been deprecated, plese migrate your '

### ISSUE THREAD

**Issue by x-itec** [wxWidgets/Phoenix#2103]
**Operating system Win64 Win11**:
**wxPython version4.1.1*:          
**Python version3.8**:            

**Description of the problem**:
...\python38\lib\site-packages\wx\lib\pubsub\__init__.py:23: wxPyDeprecationWarning: wx.lib.pubsub has been deprecated, plese migrate your code to use pypubsub, available on PyPI.
  warnings.warn('wx.lib.pubsub has been deprecated, plese migrate your '

WXDEMO

<details>
  <summary>Code Example (click to expand)</summary>

```python
# Put code sample here
```
</details>

**Comment by rkb0208** [comment]
Hey did you figure this out? I am having the same issue
