### ISSUE TITLE
create custom PGEditor failed.

### ISSUE THREAD

**Issue by linzhanyu** [wxWidgets/Phoenix#2114]
**Operating system**: windows10
**wxPython version & source**:          pypi, 4.1.0
**Python version & source**:            python 3.8.8.

**Description of the problem**:

AttributeError: module 'wx.propgrid' has no attribute 'PG_SUBID1'

<details>
  <summary>Code Example (click to expand)</summary>

```python
# Put code sample here
```
import wx.propgrid as wxpg

class SliderPropertyEditor(wxpg.PGEditor):
    ...
    def CreateControls(self, propgrid, property, pos, sz):
        ...
        self.tc = wx.TextCtrl(propgrid.GetPanel(), wxpg.PG_SUBID1, s,(x,y), (textWidth,h),wx.TE_PROCESS_ENTER)
        self.btn = wx.Slider(propgrid.GetPanel(), wxpg.PG_SUBID2, property.GetValue(),-1,100,(x+textWidth, y),(w-textWidth, h-y), wx.SL_HORIZONTAL  )

</details>

**Comment by swt2c** [comment]
In wxPython 4.1.0+, the controls are no longer required to use IDs PG_SUBID1 and PG_SUBID2, and those constants have been removed.
