### ISSUE TITLE
libfontconfig import error: "undefined symbol: uuid_generate_sha1"

### ISSUE THREAD

**Issue by Talw3g** [wxWidgets/Phoenix#2115]
**Operating system**: Debian bookworm (testing)
**wxPython version & source**:   4.1.1, pypi
**Python version & source**:   3.9, miniconda3

**Description of the problem**:

I installed wxPython 4.1.1 with pip, inside a conda env running python 3.9 : after installing the required libs, build went fine and wxPython installed successfully.
But when I try to run my program (which only imports "App" from wx), I get the following error: 
```bash
Traceback (most recent call last):
  File "/home/thibault/CalculateurOmega/app.py", line 9, in <module>
    from wx import App as wxApp
  File "/home/thibault/miniconda3/envs/omega/lib/python3.9/site-packages/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "/home/thibault/miniconda3/envs/omega/lib/python3.9/site-packages/wx/core.py", line 12, in <module>
    from ._core import *
ImportError: /lib/x86_64-linux-gnu/libfontconfig.so.1: undefined symbol: uuid_generate_sha1, version UUID_2.31
```

<details>
  <summary>I've checked that libfontconfig is installed, v2.13.1-4.4 (see apt-cache policy output)...</summary>

```bash
libfontconfig1-dev:
  Installed: 2.13.1-4.4
  Candidate: 2.13.1-4.4
  Version table:
 *** 2.13.1-4.4 500
        500 http://deb.debian.org/debian testing/main amd64 Packages
        100 /var/lib/dpkg/status
libfontconfig-dev:
  Installed: 2.13.1-4.4
  Candidate: 2.13.1-4.4
  Version table:
 *** 2.13.1-4.4 500
        500 http://deb.debian.org/debian testing/main amd64 Packages
        100 /var/lib/dpkg/status
libfontconfig1:
  Installed: 2.13.1-4.4
  Candidate: 2.13.1-4.4
  Version table:
 *** 2.13.1-4.4 500
        500 http://deb.debian.org/debian testing/main amd64 Packages
        100 /var/lib/dpkg/status

```
</details>

... and _core points to the right libfontconfig (I think ?):
```bash
~/miniconda3/envs/omega/lib/python3.9/site-packages/wx $ ldd _core.cpython-39-x86_64-linux-gnu.so | grep libfontconfig
        libfontconfig.so.1 => /lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007f1e0c571000)
```

Please let me know if you need any more info !

**Comment by Talw3g** [comment]
Thanks for your quick reply !
I had ruled out the Debian trail when I saw the libfontconfig changelog:
```
2022-01-29 - Johannes Schauer Marin Rodrigues <josch@debian.org>
fontconfig (2.13.1-4.4) unstable; urgency=medium
* Non-maintainer upload.
* Update patch from last upload with fixed uuid_generate_sha1() call
```

But then it might just be this release that caused the problem!
I've never filed ad Debian bug, so I'll be grateful if you could do it!

Thanks

**Comment by swt2c** [comment]
Actually, I'm not sure that this is a (current) Debian bug.  I just tried reproducing the problem myself on up-to-date Debian Unstable (e.g., I did `pip install wxpython` in a venv) and I was unable to reproduce it.  Is it possible that you didn't have all the dependencies installed at first, resulting in some sort of partial compilation?  Is your Debian Testing fully up to date?

**Comment by Talw3g** [comment]
I've updated Debian when trying to solve the issue, but to no avail...
I've had to restart the pip install several times because of missing libraries, so it might be just that. I will try to restart from scratch in a new conda env tomorrow and will keep you posted !

**Comment by swt2c** [comment]
Yes, that is exactly what I was thinking about.  You might also need to clear whatever cache pip/conda uses.  I think pip is ~/.pip/cache.

**Comment by Talw3g** [comment]
I've tried with a new conda env and the "--no-cache-dir" option for pip: no good... But it dit work with a standard python venv !
Since the issue seems to lie more within conda than wxWidgets , I will close this issue.
Thanks again for your help :)
