### ISSUE TITLE
set_globals() given 6 arguments instead of 7

### ISSUE THREAD

**Issue by programmingkidx** [wxWidgets/Phoenix#2124]
**Operating system**: Mac OS 12.2.1
**CPU**: Apple M1
**wxPython version & source**: git commit af8cca5189ff1241fc7d2112e70131ac3788a0db
**Python version & source**: 3.9.10

**Description of the problem**: Building wxPython fails because the set_globals() function is given the wrong number of arguments.

<details>

> Running command: sip
> Running SIP code generator on: sip/gen/_core.sip
> build.py: An internal error occurred...
> Traceback (most recent call last):
>   File "/Users/user/wxpython/Phoenix/build.py", line 2321, in <module>
>     main(sys.argv[1:])
>   File "/Users/user/wxpython/Phoenix/build.py", line 202, in main
>     function(options, args)
>   File "/Users/user/wxpython/Phoenix/build.py", line 1287, in cmd_sip
>     sip_runner(src_name,
>   File "/Users/user/wxpython/Phoenix/buildtools/wxpysip.py", line 98, in sip_runner
>     handle_exception(e)
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sipbuild/exceptions.py", line 81, in handle_exception
>     raise e
>   File "/Users/user/wxpython/Phoenix/buildtools/wxpysip.py", line 65, in sip_runner
>     set_globals(SIP_VERSION, SIP_VERSION_STR, int(abi_major), int(abi_minor),
> TypeError: function takes exactly 7 arguments (6 given)
> Finished command: sip (0.12s)

</details>

**Comment by swt2c** [comment]
Are you using sip 5.5.0?

**Comment by swt2c** [comment]
Only sip 5.5.0 is currently supported.

**Comment by programmingkidx** [comment]
I suggest the documentation wxPython be updated to include a note stating that SIP 5.5.0 is required. This page would be a good place to provide this information: https://github.com/wxWidgets/Phoenix/.

Thank you.

**Comment by swt2c** [comment]
Sure.  Additionally, the requirements are specified in `requirements.txt` as per standard Python practices.

**Comment by programmingkidx** [comment]
SIP 5.5.0 can be found here: https://distfiles.macports.org/py-sip/sip-5.5.0.tar.gz.
Extract the files then build it like this: python3 setup.py install
Then install it: sudo python3 setup.py install
