### ISSUE TITLE
Why my wxPython interface manual refresh required?

### ISSUE THREAD

**Issue by xinxin2021** [wxWidgets/Phoenix#2127]
It's like this:
![Snipaste_2022-03-13_18-34-32](https://user-images.githubusercontent.com/82391092/158055600-6cc7fef6-a5fd-43dc-bced-99bb45b65868.png)
Maximization and minimization can solve most of this problem.
There are still a few problems that cannot be solved.
Who can solve this(these)?
Thanks!

**Comment by DietmarSchwertberger** [comment]
This is a bug tracker, not a support forum.
Please close the issue and post to discuss.wxpython.org instead.
