### ISSUE TITLE
wx.Choice doesn't obey its size parameter

### ISSUE THREAD

**Issue by kitovyj** [wxWidgets/Phoenix#213]
wx.Choice, being placed on a panel without a sizer at given position with a given size, changes its size depending on current font size... Windows 10 64-bit.

Boxers and sizers are good, but the interfaces built using just boxers and sizers look ugly and unprofessional.... I think manual tweaking and manual positioning/sizing should always be possible.

**Comment by RobinD42** [comment]
As far as I can tell that is the behavior of the native widget, and wx does nothing to enable nor prevent that. You'll need to reset the size to your preference after setting the font.
