### ISSUE TITLE
ModuleNotFoundError: No module named 'wx.combo'

### ISSUE THREAD

**Issue by mbastida123** [wxWidgets/Phoenix#2130]
**Operating system**: Microsoft Windows 10
**wxPython version & source**:         4.1.1&pypi 
**Python version & source**:            3.9.10&stock

**Description of the problem**:
Hi, I have found some errors similar to mine but they where old and related to the wxpython3 <-> wxpython4 compatibility.

When I:
`import wx.combo`

I get:
`ModuleNotFoundError: No module named 'wx.combo'`

I have tried uninstalling and installing wxpython with no luck.

**Comment by swt2c** [comment]
`wx.combo` seems to have gone away in wxPython 4.  It's classes are I think in the main wx namespace.  What classes are you trying to use?

**Comment by DietmarSchwertberger** [comment]
@mbastida123 : I don't see what would be the bug. Would you please close the issue?
