### ISSUE TITLE
wxPython 4.1.2a1 build from sources fails with system wxWidgets 3.1.6

### ISSUE THREAD

**Issue by wally-mageia** [wxWidgets/Phoenix#2136]
**Operating system**: Linux, Mageia Cauldron, 64bit
**wxPython version & source**: [wxPython-4.1.2a1.dev5310+af8cca51](https://wxpython.org/Phoenix/snapshot-builds/wxPython-4.1.2a1.dev5310+af8cca51.tar.gz)         
**Python version & source**: [Python 3.10.4](https://madb.mageia.org/rpm/show/application/0/release/cauldron/arch/x86_64/name/python3-3.10.4-1.mga9.x86_64.rpm/source/0/t_media/3)          

**Description of the problem**:
[wxWidgets 3.1.6](https://www.wxwidgets.org/news/2022/04/wxwidgets-3.1.6-released/) was released April 4th 2022. Latest wxPython snapshot-build 4.1.2a1.dev5310+af8cca51 fails with system wxWidgets 3.1.6.

```
$ /usr/bin/python3 -u build.py dox touch etg --nodoc sip build_py --use_syswx --gtk3

...snip...

[114/924] Compiling sip/cpp/sip_corewxArrayInt.cpp
../../../../sip/cpp/sip_corewxToolBar.cpp: In function ‘PyObject* meth_wxToolBar_AddTool(PyObject*, PyObject*, PyObject*)’:
../../../../sip/cpp/sip_corewxToolBar.cpp:1242:37: error: call of overloaded ‘AddTool(int&, const wxString&, const wxBitmap&, const wxString&, wxItemKind&)’ is ambiguous
 1242 |             sipRes = sipCpp->AddTool(toolId,*label,*bitmap,*shortHelp,kind);
      |                      ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/wx-3.1/wx/toolbar.h:67,
                 from /usr/include/wx-3.1/wx/wx.h:87,
                 from ../../../../wx/include/wxPython/wxpy_api.h:41,
                 from ../../../../sip/cpp/sipAPI_core.h:20329,
                 from ../../../../sip/cpp/sip_corewxToolBar.cpp:10:
/usr/include/wx-3.1/wx/tbarbase.h:311:24: note: candidate: ‘wxToolBarToolBase* wxToolBarBase::AddTool(int, const wxString&, const wxBitmapBundle&, const wxString&, wxItemKind)’
  311 |     wxToolBarToolBase *AddTool(int toolid,
      |                        ^~~~~~~
In file included from /usr/include/wx-3.1/wx/wx.h:14:
/usr/include/wx-3.1/wx/tbarbase.h:527:24: note: candidate: ‘wxToolBarToolBase* wxToolBarBase::AddTool(int, const wxBitmap&, const wxBitmap&, bool, wxCoord, wxCoord, wxObject*, const wxString&, const wxString&)’
  527 |     wxToolBarToolBase *AddTool(int toolid,
      |                        ^~~~~~~
/usr/include/wx-3.1/wx/defs.h:648:43: note: in definition of macro ‘wxDEPRECATED’
  648 | #define wxDEPRECATED(x) wxDEPRECATED_DECL x
      |                                           ^
/usr/include/wx-3.1/wx/tbarbase.h:526:5: note: in expansion of macro ‘wxDEPRECATED_INLINE’
  526 |     wxDEPRECATED_INLINE(
      |     ^~~~~~~~~~~~~~~~~~~

Waf: Leaving directory `/builddir/build/BUILD/wxPython-4.1.2a1.dev5310+af8cca51/build/waf/3.10/gtk3'
Build failed
 -> task in '_core' failed with exit status 1 (run with -v to display more information)
Command '"/usr/bin/python3" /usr/bin/waf --wx_config=wx-config --gtk3 --python="/usr/bin/python3" --out=build/waf/3.10/gtk3 configure build ' failed with exit code 1.

```

**Comment by swt2c** [comment]
Yes, I'm working on updating master to use wx 3.1.6...

**Comment by wally-mageia** [comment]
I know there is quite a lot to do, but is there any ETA for the update? Or any progress page to follow, and perhaps help?

**Comment by swt2c** [comment]
I've got the updates implemented (at least for Linux), but I need to write unittests for the new functionality in 3.1.6.  I'll push my WIP branch so you can test it, if you'd like.

**Comment by chris2553** [comment]
> I've got the updates implemented (at least for Linux), but I need to write unittests for the new functionality in 3.1.6. I'll push my WIP branch so you can test it, if you'd like.

Yes, I'd like that, please.

**Comment by wally-mageia** [comment]
> > I've got the updates implemented (at least for Linux), but I need to write unittests for the new functionality in 3.1.6. I'll push my WIP branch so you can test it, if you'd like.
> 
> Yes, I'd like that, please.

Yes, please.
