### ISSUE TITLE
wxPython-4.1.2a2 32-bit version for Python 3.10 on Windows

### ISSUE THREAD

**Issue by rchrj** [wxWidgets/Phoenix#2137]
**Operating system**: Windows 10
**wxPython version & source**: wxPython-4.1.2a2
**Python version & source**: Python 3.10

**Description of the problem**:
wxPython 4.1.1 won't install on Windows 10 and Python 3.10. There are snapshot builds of 4.1.2a2 for it but only for 64-bit. How to get it running in Python 3.10 (32-bit)?

**Comment by DivingDuck** [comment]
I like to support this as well. It would be nice having 32 bit versions on had as long as Windows 10 32bit isn't end of support.

**Comment by DKMR** [comment]
Hi @rchrj 

You can compile wxPython from snapshots available [here](https://wxpython.org/Phoenix/snapshot-builds/?C=M;O=D). Keep in mind you will need Visual Studio 2015 at minimum according to provided instructions, as well as some specific Python packages.

Take a look at `README.rst` file in the downloaded snapshot to get a better understanding of the process. You can get the list of required Python packages from `/requiremets/devel.txt` file.

From there on it shouldn't be too difficult, managed to compile it myself for the first time today on Linux just by following these instructions. If you need any assistance, I'll be happy to help!

**Comment by kikislater** [comment]
But there is no such branch or tag 4.1.2a1 in this repository ! 
Released of python-wxpython is quite confusing ... 
Nothing is working with 4.1.1 and grass gis (latest release) for example instead we update with some python-wxpython upstream release.

Any plan to release a 4.1.2 version as 4.1.1 is not an official release and doesn't work ?

**Comment by swt2c** [comment]
Snapshot builds being built for 32-bit windows.
