### ISSUE TITLE
Move to Gstreamer 1.0

### ISSUE THREAD

**Issue by ase1590** [wxWidgets/Phoenix#214]
Gstreamer 0.10 is being deprecated by WxWidgets as of recently, and support for gstreamer 1.0 for wxmedia is now available. 

https://github.com/wxWidgets/wxWidgets/pull/225

wxpython should preferably be able to be built without the need for legacy gstreamer 0.10
If this is already possible, the compilation dependencies need to be updated to reflect this.

**Comment by ase1590** [comment]
looks like support was added already?
https://github.com/wxWidgets/Phoenix/issues/206

If so, the readme needs to be updated.

**Comment by mesalu** [comment]
the head of WX_3_0_BRANCH now contains a commit by Scott Talbert for configuring for gstreamer1.0

You can successfully build Phoenix by updating ext/wxWidgets to head of said branch.

That being said, I haven't proven it actually works yet. Presently I'm getting an Xv related error that I haven't had time to dig into yet.

**Comment by swt2c** [comment]
It works for me, at least on Fedora (well, technically I only tested with C++ code, not Python yet).  There's a problem with the video showing up in a separate window, but that is Wayland-related.  Let me know if you find any problems with the GStreamer support.

**Comment by RobinD42** [comment]
The wx change is now included in Phoenix snapshots and the build is using gstreamer 1.0 if it's available.
