### ISSUE TITLE
Cannot build (via pip install) on Win10 at all (with available VS2019 build tools)

### ISSUE THREAD

**Issue by rwarren** [wxWidgets/Phoenix#2165]
**Operating system**: Win10
**wxPython version & source**:   pypi 4.1.1
**Python version & source**:  3.10.4 official Windows install (32b and 64b; also tried back to 3.8)

**Description of the problem**:

`pip install wxpython` fails on any Win10 configurations I've tested (with VS2019 build tools) because distutils cannot find the VC tools in any of the currently available VS2019 Build Tools that [MS provides](https://visualstudio.microsoft.com/vs/older-downloads/).

Unless I'm doing something really strange (always possible!) this seems to be an upstream issue with setuptools/distutils, which I've reported [here](https://github.com/pypa/setuptools/issues/3329).  distutils just can't find the compiler.  Possibly because MS changed the directory schema for installs (even retroactively for old versions!?)? It isn't clear to me why this is failing so completely for me and I can't find any other reports of it.

Specifically, you get this traceback (snipped to the relevant bit):

```console
      Running command: build
      Running command: build_wx
      Command '"C:\venvs\udbs_unit_copy\Scripts\python.exe" -c "import setuptools, distutils.msvc9compiler as msvc; mc = msvc.MSVCCompiler(); mc.initialize(); print(mc.cc)"' failed with exit code 1.
      Traceback (most recent call last):

        File "<string>", line 1, in <module>

        File "C:\venvs\udbs_unit_copy\lib\site-packages\setuptools\_distutils\msvc9compiler.py", line 371, in initialize

          vc_env = query_vcvarsall(VERSION, plat_spec)

        File "C:\venvs\udbs_unit_copy\lib\site-packages\setuptools\msvc.py", line 140, in msvc9_query_vcvarsall

          return EnvironmentInfo(arch, ver).return_env()

        File "C:\venvs\udbs_unit_copy\lib\site-packages\setuptools\msvc.py", line 1740, in return_env

          [self.VCIncludes,

        File "C:\venvs\udbs_unit_copy\lib\site-packages\setuptools\msvc.py", line 1282, in VCIncludes

          return [join(self.si.VCInstallDir, 'Include'),

        File "C:\venvs\udbs_unit_copy\lib\site-packages\setuptools\msvc.py", line 840, in VCInstallDir

          raise distutils.errors.DistutilsPlatformError(msg)

      distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.2 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      Finished command: build_wx (0.503s)
      Finished command: build (0.503s)
      WARNING: Building this way assumes that all generated files have been
      generated already.  If that is not the case then use build.py directly
      to generate the source and perform the build stage.  You can use
      --skip-build with the bdist_* or install commands to avoid this
      message and the wxWidgets and Phoenix build steps in the future.

      "C:\venvs\udbs_unit_copy\Scripts\python.exe" -u build.py build
      Command '"C:\venvs\udbs_unit_copy\Scripts\python.exe" -u build.py build' failed with exit code 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> wxpython

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

**To reproduce:**
1. Get a fresh Win10 machine (with no Visual Studio or VS Build Tools on it)
2. Install python (any version from 3.8 up)
3. install VS2019 build tools for C++ (with Win10SDK as well, and ensuring the latest MSCV142 tools are installed)
4. Ideally set up and activate a venv for testing
5. `pip install setuptools -U`   (just in case)
6. `pip install wxpython` will fail

**Comments**

Any known workarounds to get wxpython installed onto Win10 would be appreciated! 😀

**Comment by kinweilee** [comment]
I'm having similar issues with Visual Studio and pip. This work around helps with the compiler detection, however I can't quite get wxpython to fully compile. 

Run a command prompt with Administrator privileges and create two hard links to create a dummy '14.2' folder

`mklink /j "C:\Program Files (x86)\Microsoft Visual Studio 14.2" "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional"`
`mklink /j "C:\Program Files (x86)\Microsoft Visual Studio 14.2\VC\Redist\MSVC\v142\onecore" "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Redist\MSVC\14.29.30133\onecore"
`
Testing with:
`python.exe -c "import setuptools, distutils.msvc9compiler as msvc; mc = msvc.MSVCCompiler(); mc.initialize(); print(mc.cc)"`
which successfully gives:
`C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29910\bin\HostX64\x64\cl.exe`

However with my issue I still get a failure with compiling/installing an older version of wxpython via pip `pip install wxpython==4.1.0` , as it is unable to find a suitable architecture.
`msvc: Impossible to find a valid architecture for building ['msvc 14.2'] - ['msvc 17.2', 'msvc 16.9']`

related information I found regarding someone who has successfully build wxpython 4.1.2a1 using the hard links:
[https://gist.github.com/oleksis/8637f096b97e18e00786e46465e97b34)/oleksis/8637f096b97e18e00786e46465e97b34](url)

**Operating System** Windows 10
**Python version** 3.10.4

**Comment by RobinD42** [comment]
The build scripts were recently updated (several commits starting around 999ad33c967de67d69f4053aa0960aec0ee9a0c6) to rely more on setuptools for compiler detection and such, and less on distutils. (There's some bits of distutils usage that still need cleaned up...) I did have an issue on one of the build machines with VS 2019 but upgrading to VS 2022 took care of it so I didn't spend much time on it. If setuptools and our build scripts are able to find everything about the VS install then there shouldn't be any need to preset things in the environment with one of the "Command Prompt" helpers.

If you're able to track down what might be the issue with VS 2019 let me know. I suspect that there may have been some components that were not installed by default with 2019 but which are in 2022, but like I said, I didn't spend much time on tracking down the cause of the problem.

**Comment by DKMR** [comment]
This is interesting, fired up a fresh Windows 10 Pro VM and installed 64-bit Python 3.9.13 as well as the latest version of wxPython via `pip`. Keep in mind I didn't have any dev tools installed at this moment, just base Windows and Python.
![Scnsht1](https://user-images.githubusercontent.com/7292091/172573490-ee0283b2-21d2-40ce-9e9d-50ace8021c57.PNG)

The setup process was successful and importing _wx_ seems to work fine.

As you mentioned VS 2019, specifically only the build tools, I fetched a copy of 2019 tools from [Wayback machine](https://web.archive.org/web/20200717145425/https://download.visualstudio.microsoft.com/download/pr/c10c95d2-4fba-4858-a1aa-c3b4951c244b/54dedc13fbb321033e5d3297ac7c5ad8de484be2871153fe20599211135c9448/vs_BuildTools.exe) and installed the following:
![vstls2019](https://user-images.githubusercontent.com/7292091/172573939-23e54910-ef95-4969-a1b4-82141606e233.PNG)

Uninstalled ALL Python packages and ran the setup process again.
![Scnsht2](https://user-images.githubusercontent.com/7292091/172574108-62eb28b2-4fde-4535-a8ab-17ff814ac395.PNG)

As expected, _wx_ can be imported without errors.

I'm curious to why your `pip install wxpython` is trying to build wx.

**Comment by kinweilee** [comment]
In your case you are installing from a wheel, which is a precompiled module. If pip finds a relevant *.whl it will use that otherwise it will revert to compiling from source.

**Comment by DKMR** [comment]
I understand the process, what's not that clear to me is why his `pip install` defaults to compiling wxPython instead of using prebuilt wheels.

Anyways, I've confirmed this issue when compiling with VS 2019 and VS 2022, and my guess is that it's also present in some older releases as well. It boils down to how _msvc9compiler.py_ from distutils gathers information about your VS environment.

The solution was to add a few registry keys for which _msvc9compiler.py_ looks and fails to find (64-bit only);
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\VisualStudio\14.0\Setup\VC
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\VisualStudio\14.2\Setup\VC


A string value _ProductDir_ is required in both places and it should point to where your vcvarsall.bat file is. See the example below:
![Registry](https://user-images.githubusercontent.com/7292091/172720197-b296f405-68ad-41dc-800a-c5c39192b2fb.PNG)

After forcing a rebuild with `--no-binary` flag with `pip` I was able to compile wxPython 4.1.1 using Python 3.9.13, VS 2019 and VS 2022.
![Screenshot 2022-06-08 232411](https://user-images.githubusercontent.com/7292091/172720523-0b96e782-ce75-48fc-8a7f-2407a25e37b6.png)

**Comment by RobinD42** [comment]
> I understand the process, what's not that clear to me is why his pip install defaults to compiling wxPython instead of using prebuilt wheels.

Because there are no binaries on PyPI for Python 3.10 yet. There are some 4.1.2 preview builds however:

```
pip install -U --pre -f https://wxpython.org/Phoenix/snapshot-builds wxPython
```

**Comment by DKMR** [comment]
> As stated by @RobinD42 this is because I am trying to install wxPython with python 3.10

I'm curious as to why you mentioned the following in your **To reproduce:** section

> Install python (any version from 3.8 up)

You could've simply mentioned *only* 3.10.

> B) I also wondered if anyone had a wxpython-specific workaround.

There is a workaround

**Comment by rwarren** [comment]
> I'm curious as to why you mentioned the following in your To reproduce: section

Because I totally forgot I tried earlier python versions when I initially reported this!! 🙄 You are right, I definitely did go back to 3.8 when initially trying to be thorough in understanding this problem.  I tried a lot of things back then.

So... I don't know why a build is being forced in my cases with earlier python versions. Perhaps because of my 32-bit python build? I do see `win32` wheels builds in place (like `wxPython-4.1.1-cp39-cp39-win32.whl`).  Will try again and report back.

> There is a workaround

Curiously, I don't have the same structure you have in your registry. Notably, I don't have the `14.2` dir, nor do I have the `Setup` dir:
![image](https://user-images.githubusercontent.com/2751728/173412947-72b8a556-3a0c-4ddb-afc6-24aa6910ec9e.png)

Did you need to manually create all missing dirs?

**Comment by DKMR** [comment]
@rwarren Yup, you probably have 14.0 with "VC" as the only key. You need to manually create:
14.0 > Setup > VC > "ProductDir" = "XYZ\Visual Studio 2022\VC\Auxiliary\Build"
14.2 > Setup > VC > "ProductDir" = "XYZ\Visual Studio 2022\VC\Auxiliary\Build"

I didn't have 14.2 as well. Visual Studio 2008 used this hierarchy while installing. Hope this helps :)

**Comment by rwarren** [comment]
Success!  The registry workaround did the trick, although I did need to manually install `requests` first.

Breaking it down...

I modified the registry as indicated. For anyone else landing here, you can just make and execute a `.reg` file (eg. `py310build.reg`) with these contents:
```ini
Windows Registry Editor Version 5.00

; These registry keys are needed to coerce python into detecting VS2019 build tools
;  - adjust `ProductDir` paths as necessary (the dir should be where `vcvarsall.bat` is located)

[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\VisualStudio\14.2\Setup\VC]
"ProductDir"="C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Auxiliary\\Build"

[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\VisualStudio\14.0\Setup\VC]
"ProductDir"="C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Auxiliary\\Build"
```

When I tried to build, I got a traceback indicating that `requests` was missing. Snipped output below:

```
      Running command: build
      Running command: build_wx
      MSVC: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x86\cl.exe
      Downloading microsoft.web.webview2 1.0.622.22...
      Traceback (most recent call last):
        File "C:\Users\war12184\AppData\Local\Temp\pip-install-02c0dp9g\wxpython_1661b9c937c042a2a0a0b60bbd75d04a\build.py", line 676, in getMSWebView2
          import requests
      ModuleNotFoundError: No module named 'requests'
      Finished command: build_wx (0m8.661s)
      Finished command: build (0m8.661s)
      WARNING: Building this way assumes that all generated files have been
      generated already.  If that is not the case then use build.py directly
      to generate the source and perform the build stage.  You can use
      --skip-build with the bdist_* or install commands to avoid this
      message and the wxWidgets and Phoenix build steps in the future.
```

After doing a manual `pip install requests`, a subsequent `pip install wxpython` then successfully built wxpython.

**Comment by liudonghua123** [comment]
I have the same issue, and I fixed using the same method. see https://github.com/pypa/setuptools/issues/3329#issuecomment-1178434103.
