### ISSUE TITLE
Modeless show FileDialog and FolderDialog

### ISSUE THREAD

**Issue by nicolaspapp** [wxWidgets/Phoenix#2166]
**Operating system**:  Windows 10
**wxPython version & source**:     PYPI - Version 4.1.1     
**Python version & source**:    Tried both in Python 2.7 and 3.7 stock       

**Description of the problem**:
The current implementation we have for our app freezes top window. This is because FileDIalogs are being open as Modal blocking program flow. I would like to switch to modeless mode but it doesn't seem to show any dialog. Is there any way of using FileDIalog as a modeless dialog?

<details>
  <summary>Minimalist Code Example (click to expand)</summary>

```python
import wx
   
app = wx.App(redirect=True)
top = wx.Frame(None, title="Hello World", size=(300,200))
top.Show()

wildcard = 'CSV files (*.csv)|*.csv'
style = wx.FD_OPEN | wx.FD_FILE_MUST_EXIST
dialog = wx.FileDialog(top, '', '', '', wildcard, style)
dialog.Show(show=True)
#if dialog.ShowModal() == wx.ID_OK:
#    print('ok')
#dialog.Destroy()

app.MainLoop()
```
</details>

**Comment by RobinD42** [comment]
No, the file and dir dialogs are not real `wx.Dialogs` but are just wrappers around the corresponding platform APIs. So we're limited on what is allowed by the platform for the common dialogs. instead you can create a custom dialog class based on the `wx.FileCtrl` class.

**Comment by nicolaspapp** [comment]
Ok this is a great alternative. Much appreciated!
