### ISSUE TITLE
Support sip-build (sip 6.6.1+)

### ISSUE THREAD

**Issue by swt2c** [wxWidgets/Phoenix#2169]
sip 6.6.1 has implemented a completely new parser based on ply and has removed the private API we're using currently.  We need to support the modern way of using sip (i.e., using pyproject.toml/project.py).  Some distributions (e.g., Debian Unstable) have already moved to 6.6.1.

Assigning this to myself, unless @RobinD42 or @mitya57 are already working on it.

**Comment by swt2c** [comment]
Okay, got this working and all bugs fixed in sip.  Just waiting on a new sip release now with the bug fixes.

**Comment by RobinD42** [comment]
Thanks @swt2c! Can you submit a draft PR for it? I'd like to see what it took to make the switch.
