### ISSUE TITLE
wx.TreeCtrl: Only last call to EnsureVisible is handled while tree is frozen

### ISSUE THREAD

**Issue by igt-gteubl** [wxWidgets/Phoenix#2170]
**Operating system**: Windows 10
**wxPython version & source**:        wxPython==4.1.1 (conda-forge)
**Python version & source**:            Python 3.10.4 (conda-forge)

**Description of the problem**:
When the tree **IS frozen**, after the call to `wx.TreeCtrl.Thaw`, only the parents of the item specified by the **last call to `EnsureVisible`** are expanded.

This makes it impossible to, for example, expand all tree items matching a certain name while the tree is frozen.

<details>
  <summary>Code Example (click to expand)</summary>

```python
import wx

def main():
    def EnsureVisible(freeze):
        if freeze:
            TheApp.m_frame.tree.Freeze()
        TheApp.m_frame.tree.EnsureVisible(level1_1)
        TheApp.m_frame.tree.EnsureVisible(level2_1)
        if freeze:
            TheApp.m_frame.tree.Thaw()
    TheApp.m_frame = wx.Frame(None)
    TheApp.m_frame.tree = wx.TreeCtrl(TheApp.m_frame)
    root = TheApp.m_frame.tree.AppendItem(TheApp.m_frame.tree.GetRootItem(), "Root")
    level1 = TheApp.m_frame.tree.AppendItem(root, "Level1")
    level1_1 = TheApp.m_frame.tree.AppendItem(level1, "Leaf")
    level2 = TheApp.m_frame.tree.AppendItem(root, "Level2")
    level2_1 = TheApp.m_frame.tree.AppendItem(level2, "Leaf")

    sizer = wx.BoxSizer(wx.VERTICAL)
    btn_sizer = wx.BoxSizer(wx.HORIZONTAL)
    btn = wx.Button(TheApp.m_frame, wx.ID_ANY, "1) EnsureVisible")
    btn.Bind(wx.EVT_BUTTON, lambda evt: EnsureVisible(False))
    btn_sizer.Add(btn)
    btn = wx.Button(TheApp.m_frame, wx.ID_ANY, "2) CollapseAll")
    btn.Bind(wx.EVT_BUTTON, lambda evt: TheApp.m_frame.tree.CollapseAll())
    btn_sizer.Add(btn)
    btn = wx.Button(TheApp.m_frame, wx.ID_ANY, "3) Freeze+EnsureVisible")
    btn.Bind(wx.EVT_BUTTON, lambda evt: EnsureVisible(True))
    btn_sizer.Add(btn)
    sizer.Add(TheApp.m_frame.tree, 1, wx.EXPAND|wx.ALL, 5)
    sizer.Add(btn_sizer, 0, wx.EXPAND|wx.ALL, 5)
    TheApp.m_frame.SetSizer(sizer)
    TheApp.m_frame.Show()
    TheApp.MainLoop()

TheApp = wx.App()
if __name__ == "__main__":
    main()
```
</details>

**Comment by RobinD42** [comment]
It looks like this is intentional (or at least a side effect of what is intended.) See https://github.com/wxWidgets/wxWidgets/blob/master/src/msw/treectrl.cpp#L1996. When the tree is frozen the code saves just the last item passed to `EnsureVisible` and then defers the actual `EnsureVisible` until the widget is thawed.

You can probably get what you want using one of the `Expand` methods instead.
