### ISSUE TITLE
Performance degradation in dev5330-dev5355 when scrolling big binary file loaded to StyledTextCtrl when HiDPI awareness is set.

### ISSUE THREAD

**Issue by wadim-al** [wxWidgets/Phoenix#2171]
**Operating system**: Windows 10 x64 Pro 21H2 19044.1645
**wxPython version & source**: [snapshot 4.1.2a1.dev5355+6a5e93d0-cp310-cp310-win_amd64.whl](https://wxpython.org/Phoenix/snapshot-builds/wxPython-4.1.2a1.dev5355+6a5e93d0-cp310-cp310-win_amd64.whl)
**Python version & source**: [Official Python 3.10.4 64 bit Win](https://www.python.org/ftp/python/3.10.4/python-3.10.4-amd64.exe)

**Description of the problem**: When a huge binary file is loaded to StyledTextCtrl, the contents can be scrolled quickly in wxPython-4.1.2a1.dev5310+af8cca51, but since wxPython-4.1.2a1.dev5330+3e6be81d if the HiDPI awareness is set, the scrolling is considerably slower.  OS scaling is set to 125%, monitor resolution is 2560x1440.

**Steps**:
1. pip3 uninstall wxpython
2. pip3 install wxPython-4.1.2a1.dev5355+6a5e93d0-cp310-cp310-win_amd64.whl
3. Run min repro (attached)
4. Scroll the contents -> slow
5. pip3 uninstall wxpython
6. pip3 install wxPython-4.1.2a1.dev5310+af8cca51-cp310-cp310-win_amd64.whl
7. Run min repro (attached)
8. Scroll the contents -> quick

**Image for testing**: [Image 7.5 mb](https://user-images.githubusercontent.com/29713984/169653674-e8157bd2-86f0-49c0-8ff6-a4f076857381.jpg)
**Min repro source**: [stcperftext.py.txt](https://github.com/wxWidgets/Phoenix/files/8747693/stcperftext.py.txt)

[Video of wxPython-4.1.2a1.dev5355+6a5e93d0 with lags](https://youtu.be/VLa_n0htWm4)
[Video of wxPython-4.1.2a1.dev5310+af8cca51 having no lag](https://youtu.be/j5ZPDqYr7zE)

<details>
  <summary>Code Example (click to expand)</summary>

```python
import ctypes
import io
import wx
import wx.stc
def interleaveStyle(data): # hack to fully load a binary file to scintilla
    ba = bytearray(data)
    ba2 = bytearray()
    for b in ba:
        ba2.append(b)
        ba2.append(0x00)
    return ba2
class Frame(wx.Frame):
    def __init__(self):
        super().__init__(None)
        sizer = wx.BoxSizer(wx.VERTICAL)
        self.SetSizer(sizer)
        scintilla = wx.stc.StyledTextCtrl(self)
        scintilla.SetScrollWidthTracking(True)
        sizer.Add(scintilla, 1, wx.EXPAND, 0)
        self.Layout()
        self.Maximize()
        self.Show()
        with io.open("img.jpg", "rb") as f:
            data = f.read()
            styledData = interleaveStyle(data) # hack to fully load a binary file to scintilla
            scintilla.AddStyledText(styledData)
try:
    ctypes.windll.shcore.SetProcessDpiAwareness(2) # hack to enable hidpi awareness
except Exception as e:
    print(e)
app = wx.App()
frame = Frame()
app.MainLoop()
```

</details>

**Comment by wadim-al** [comment]
Reproduced in wxWidgets 3.1.6 C++ itself, 3.1.5 is ok, reported https://github.com/wxWidgets/wxWidgets/issues/22450

**Comment by RobinD42** [comment]
wxWidgets changes related to this have been merged.
