### ISSUE TITLE
Consider migrating from six to python-future

### ISSUE THREAD

**Issue by RobinD42** [wxWidgets/Phoenix#218]
It seems more comprehensive and would require less conditionals in the code, since you mostly just write py3-compatible code and py2 compatibility is handled in python-future.

**Comment by efiring** [comment]
Here's a wilder idea: why not just make Phoenix Python 3-only?  It looks to me like Phoenix is in danger of failing entirely, as people who need Python 3 move to alternative GUI toolkits (mainly Qt). Increasingly, projects are making plans and schedules for dropping Python 2.7 support.

**Comment by mesalu** [comment]
@RobinD42 
Is this still on the table? 
With 2.7 EOL looming in the not too distant future I'm not convinced it'd be worth the effort to swap compatibility layers.

**Comment by RobinD42** [comment]
Nope. Even if Python2 wasn't on the way out I've heard some things about python-future that would make it less likely to be worth the switch.
