### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by aaronw2** [wxWidgets/Phoenix#2184]
python3 build.py cleanall
Traceback (most recent call last):
  File "/home/aaronw/ftp/wxwidgets/Phoenix/build.py", line 49, in <module>
    from buildtools.wxpysip import sip_runner
  File "/home/aaronw/ftp/wxwidgets/Phoenix/buildtools/wxpysip.py", line 20, in <module>
    from sipbuild.code_generator import (set_globals, parse, generateCode,
ImportError: cannot import name 'parse' from 'sipbuild.code_generator' (/home/aaronw/.pyenv/versions/3.10.4/lib/python3.10/site-packages/sipbuild/code_generator.abi3.so)

**Operating system**: Linux
**wxPython version & source**:          attempt to self-build
**Python version & source**:            self-built 3.10.4

**Description of the problem**:

The build.py script fails with the above error.  Sip 6.6.1 is installed. Other build.py commands also fail the same way.

<details>
  <summary>Code Example (click to expand)</summary>

```python
# Put code sample here
```
</details>

**Comment by swt2c** [comment]
sip 5.5.1 is (currently) required, see requirements/devel.txt.

**Comment by aaronw2** [comment]
Duplicate of #2169
