### ISSUE TITLE
demo doesn't run from git checkout

### ISSUE THREAD

**Issue by BrendanSimon** [wxWidgets/Phoenix#2186]
Operating system: OS X 12.4
wxPython version: [4.1.2a1.dev5434+7d45ee6a](https://wxpython.org/Phoenix/snapshot-builds/wxPython-4.1.2a1.dev5434+7d45ee6a-cp39-cp39-macosx_10_10_universal2.whl)
Python version: 3.9.13

Description of the problem:

wxdemo fails to run from git checkout.  However it does work if I download the wxdemo tar.gz archive.

```
demo git:(master) python demo.py
Traceback (most recent call last):
  File "/Users/brendan/Sandbox/wxPhoenix/demo/demo.py", line 3, in <module>
    import Main
  File "/Users/brendan/Sandbox/wxPhoenix/demo/Main.py", line 75, in <module>
    import version
ModuleNotFoundError: No module named 'version'
```

**Comment by RobinD42** [comment]
`demo/version.py` is generated as part of the build, so it isn't in git.

**Comment by abulka** [comment]
Interested in this too, as `wxdemo` doesn't download anymore for me under python 3.10 (due to the good ole int/float change - seems `ProgressDialog()` is still using floats and crashes) - see #2341 and I'm trying to download and run wxdemo manually from GitHub.
