### ISSUE TITLE
Please provide a release whenever supported wxWidgets version is bumped

### ISSUE THREAD

**Issue by StefanBruens** [wxWidgets/Phoenix#2195]
The latest tagged version (4.1.1) only supports wxWidgets up to 3.1.5, but in the meanwhile 3.1.6 and 3.1.7 have been released.

Distributions trying to track latest wxWidgets have a hard time to provide current wxWidgets and wxPython, either wxWidgets falls behind, or a more or less random git checkout for wxPython is required. See e.g. https://github.com/wxWidgets/Phoenix/issues/2136

As current git master supports wxWidgets up to 3.1.7, it would be nice to have a recent wxPython release.

**Comment by StefanBruens** [comment]
The issue is made worse by ABI/API breakages in SIP:
- Almost no distribution ships SIP 5.x
- Several have 6.5.x, but that has a minor breakage in the code_generator.{set_globals,generateCode):  
  https://www.riverbankcomputing.com/hg/sip/annotate/a16b972e11a1/code_generator/pybinding.c#l109
- Almost no distribution has 6.6.x (only Arch and openSUSE Tumbleweed (pending))

**Comment by swt2c** [comment]
Yeah, I think that's the intent.  The problem is just lack of Robin's time to make releases.

**Comment by DietmarSchwertberger** [comment]
The question is whether a distribution should really track the 'latest' wx version. Odd number releases like 3.1.x are considered development releases. Only the even numbers are considered stable. I would like to see similar with wxPython. The 4.1 update caused much trouble.

**Comment by StefanBruens** [comment]
@DietmarSchwertberger - actually, distributions have to.
Audacity needs at least 3.1.3, FreeFileSync even 3.1.6. KiCad builts the Windows binaries against 3.1.5, IIRC (and would do for LInux, if the newer version was more widely available). If you want to use Python 3.10, you are also screwed with wx3.0/wxPython4.0.
