### ISSUE TITLE
DataViewModel Cleared method freezes in gtk3

### ISSUE THREAD

**Issue by jmoraleda** [wxWidgets/Phoenix#2203]
I have an encountered a reproducible but non-deterministic bug in `Cleared` of `wx.dataview.DataViewModel`. The effect of the bug is that `Cleared` never returns, which of course means the UI thread becomes unresponsive and the application no longer works and must be killed.

To trigger the problem I call "Cleared" with a new pseudo-random model using a timer once a second. The bug will occur after a few of these calls (could be a handful, could be a few hundred, but it never takes more than a handful minutes at one call per second.) The problem is not caused by my code or a particular model because the script that I use to trigger the problem resets the seed of the number generator to make sure that my experiments are reproducible, and as mentioned it does not always freeze in the same iteration and I have verified that the models are indeed the same for the same iteration in different runs.

I actually don't think the bug is in wxPython or even wxWidgets but in gtk itself, but I am reporting it here to see if other people who know more about the internals can shed some light.

The bug occurs with the native control but not with the generic (The bug does not occur if I compile wxWidgets `--disable-nativedvc`). Furthermore, the bug only occurs if I compile wx in release mode (the bug does not occur if  I compile with `--debug`. I have left it running for several hours without it triggering,)

I have attached a remote debugger to the process once the UI thread _freezes_. Because it only works in release mode, I have limited trace information, but these are three trace snapshots obtained by pausing the and resuming the UI thread.

based on these traces, I hypothesize that the bug is in `gtk_tree_view_set_model`.

I am on the latest debian linux stable and I compile wxPython and wxWidgets from source based on the latest master branch.

![image](https://user-images.githubusercontent.com/23492126/177872229-ba2d2f52-c0ee-47f2-bb6d-44973dfea349.png)
![image](https://user-images.githubusercontent.com/23492126/177872622-50ae8fb7-af25-48d9-be4e-a9ef3b953130.png)
![image](https://user-images.githubusercontent.com/23492126/177872918-7eadadaa-3153-4578-bfa3-00935a47deae.png)

I am not attaching the script that I use to trigger the bug because it is fairly complex because as a DataViewModel I use an intermediate class that offers an object oriented API to the wx DataViewModel but I could build a separate more minimal script if we think it could help.

**Comment by swt2c** [comment]
It looks like you are making calls into wxPython from multiple threads?

**Comment by jmoraleda** [comment]
Thank you @swt2c . I have looked into whether I am making calls to wx functions from outside the UI thread carefully as it is typically the source of all C++ obscure errors I have found in the past. But I don't think that is the problem in this case. 

In the simplified script I have made to reproduce the problem of my larger app I have only two threads: The wx UI thread executing a typical wx main loop and a thread that uses a python `threading.Event.wait` on a loop to make a call to this function once a second:

```    
    def update_data(self):
        def post_update_event():
            self.random_change()
            wx.PostEvent(wx.GetApp(), EventProxyUpdated())
        wx.CallAfter(post_update_event)
```

`random_change` makes a _pseudo random_ change to my non-wx data structure that keeps track of which item is a parent of whom.

EventProxyUpdated is a custom wx event that I have bound to a method that essentially just calls `Cleared` on the model.

**Comment by swt2c** [comment]
OK, I misinterpreted your multiple process listing above as multiple threads.

**Comment by jmoraleda** [comment]
Ok. So the error was indeed in my code.

I will explain it in a little detail in case it might help someone.

I mentioned in the original message that I have created a wrapper that offers an object oriented API to the wx DataViewModel. This api allows the model to be a tree of _nodes_. Furthermore when the end user modifies the tree, the wrapper looks at the _value_ of the nodes to decide if a node after the modification is _the same_ as a node before the modification, which allows to preserve selections and expansions in the controls associated with the model. To achieve this feature, the nodes have custom implementations of  `__eq__` and  `__hash__`. The problem was caused because the nodes mapped themselves to items when communicating with wx, using `id(node)` mimicking the behavior of wx PyDataViewModel. This means that the item ids were not consistent with `__eq__` and `__hash__`. I have not gone into gtk code to understand why this caused the infinite loop, but through repeated testing it is clear that making item equality consistent with node equality, that is replacing the item ids used to represent a node with `hash(node)` fully solves the problem.

Thank you @swt2c  and all that took a look at the problem. By the way this wrapper enables the creation and manipulation of very complex models much easier than the C++ inherited API, IMHO. If there was interest in offering this functionality as part of `wxPython` I would be happy to open source it and make a pull request for it.
