### ISSUE TITLE
PyMuPDF 1.19.0 and newer breaks wx.lib.pdfviewer.pdfViewer

### ISSUE THREAD

**Issue by Infernio** [wxWidgets/Phoenix#2204]
**Operating system**: Windows 11
**wxPython version & source**: 4.1.1, pypi
**Python version & source**: CPython 3.9.13, stock

**Description of the problem**:
Since PyMuPDF 1.19.0 (I believe that's the version that broke it, based on the deprecation docs in the PyMuPDF repo), several names have changed (e.g. `Document.pageCount` is now `Document.page_count`).

Code example:
```python
import wx
from wx.lib.pdfviewer import pdfViewer
app = wx.App(False)
frame = wx.Frame(None)
viewer = pdfViewer(frame, nid=-1, pos=(-1, -1), size=(-1, -1), style=0)
viewer.LoadFile('test.pdf') # put a PDF file called 'test.pdf' in the working dir
```

Running this example (after putting a PDF file in the working dir) causes the following traceback:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python39\lib\site-packages\wx\lib\pdfviewer\viewer.py", line 208, in LoadFile
    self.pdfdoc = mupdfProcessor(self, pdf_file)
  File "C:\Python39\lib\site-packages\wx\lib\pdfviewer\viewer.py", line 499, in __init__
    self.numpages = self.pdfdoc.pageCount
AttributeError: 'Document' object has no attribute 'pageCount'
```

I did some digging in the PyMuPDF repo, and I believe these are the only relevant name changes for wxPython:
```
Document.pageCount -> Document.page_count
Document.loadPage -> Document.load_page
Page.getPixmap -> Page.get_pixmap
```

The question I suppose is what to do about this? I could open a PR to change them, but that would require everyone to use at least PyMuPDF 1.19.0 (actually 1.18.7 I think, based on the git history).

**Comment by swt2c** [comment]
You could make a PR that supports both the old and new names?

**Comment by Infernio** [comment]
See #2205.
