### ISSUE TITLE
"build_py" no longer working in snapshot tarballs

### ISSUE THREAD

**Issue by stefantalpalaru** [wxWidgets/Phoenix#2207]
Snapshot tarballs created this month, like https://wxpython.org/Phoenix/snapshot-builds/wxPython-4.2.0a1.dev5447+fd6b4814.tar.gz are missing "sip/siplib" and that breaks "build_py".

I think the problem was introduced by https://github.com/wxWidgets/Phoenix/commit/1a77d37cfd9ec4bd6ed98b50d4d08b14ec94fa15 and https://github.com/wxWidgets/Phoenix/commit/028783d9beb234d7ccedffe41aa87e38cc391d1e.

**Comment by swt2c** [comment]
Thanks, it was not related to those changes, but due to removal of siplib from git.
