### ISSUE TITLE
I was unable to install wxPython for python3 on Ubuntu 16.04

### ISSUE THREAD

**Issue by CodeGolfWhatsapp** [wxWidgets/Phoenix#221]
How install?
my email: renan490@gmail.com

**Comment by swprojects** [comment]
More information would be useful. Have you installed all the prerequisites?

https://github.com/wxWidgets/Phoenix#id8

 What does your terminal output say?

I just successfully installed on Linux Mint 18. A few things you may need to do in addition to the installing pre-requisites:

```pip3 install python-config```

Then you may need to set environment variable PYTHON_CONFIG to python_config file. In my case:

```export PYTHON_CONFIG="/usr/local/lib/python3.5/config-3.5m/python-config.py" ```

I also had to install libwebkit-dev 

```pip3 install libwebkit-dev ```

Then you need to install as root

```sudo pip3 install wx```

Thought It seems to take ages to build on Linux (at the "running setup.py" stage for more than 15 minutes :\) compared to Windows

**Comment by RobinD42** [comment]
See https://wxpython.org/Phoenix/snapshot-builds/README.txt, especially the section near the bottom about linux.
