### ISSUE TITLE
Unable to create a DataViewColumn

### ISSUE THREAD

**Issue by Conkey100** [wxWidgets/Phoenix#2217]
**Operating system**: Windows 10
**wxPython version & source**:  4.1.1, pypi        
**Python version & source**:  3.9.12, Anaconda          

**Description of the problem**:
I tried to create a DataViewColumn: self.col = dv.DataViewColumn('test', dv.DataViewTextRenderer, 0)
I got the following error:

```python
Traceback (most recent call last):
  File "scratch_6.py", line 20, in <module>
    frm = DataFrame(None)
  File "scratch_6.py", line 11, in __init__
    self.col = dv.DataViewColumn('test', dv.DataViewTextRenderer, 0)
TypeError: DataViewColumn(): arguments did not match any overloaded call:
  overload 1: argument 2 has unexpected type 'sip.wrappertype'
  overload 2: argument 1 has unexpected type 'str'
  overload 3: argument 1 has unexpected type 'str'
```

According to the documentation, the first argument ('title') should be a string.

Using AppendTextColumn, AppendToggleColumn, etc seems to work fine - it is only using the constructor that seems to cause the error

<details>
  <summary>Code Example (click to expand)</summary>

```python
import wx
import wx.dataview as dv

class DataFrame(wx.Frame):
    def __init__(self, *args, **kwargs):
        super(DataFrame, self).__init__(*args, **kwargs)
        self.pnl = wx.Panel(self)
        self.szr = wx.BoxSizer(wx.VERTICAL)

        self.dvc = dv.DataViewCtrl(self.pnl)
        self.col = dv.DataViewColumn('test', dv.DataViewTextRenderer, 0)
        self.dvc.AppendColumn(self.col)

        self.pnl.SetSizer(self.szr)
        self.pnl.Layout()


if __name__ == '__main__':
    app = wx.App()
    frm = DataFrame(None)
    frm.Show()
    app.MainLoop()

```
</details>

**Comment by swt2c** [comment]
The second parameter in the `DataViewColumn` constructor needs to be a `DataViewRenderer` *instance* not *class*.

`self.col = dv.DataViewColumn('test', dv.DataViewTextRenderer, 0)`
->
`self.col = dv.DataViewColumn('test', dv.DataViewTextRenderer(), 0)`

**Comment by Conkey100** [comment]
Thanks - don't know how I missed that. Closing.
