### ISSUE TITLE
ListCtrl.InsertItem(item) crash if no id is provided

### ISSUE THREAD

**Issue by sparcz** [wxWidgets/Phoenix#222]
Platform: Windows 7 64 bit
Python --version: Python 3.5.2
wx.version(): 3.0.3.dev2759+07a7440 msw (phoenix)

I try to construct a basic ListControl component for my application and have big trouble using the new (Phoenix) api. I managed to get around it eventually by providing an ID. Without that id it fails with the following  message:

> wx._core.wxAssertionError: C++ assertion "rv != -1" failed at ..\..\src\msw\listctrl.cpp(1730) in wxListCtrl::InsertItem(): failed to insert an item in wxListCtrl

`
    
    class RegisterList(wx.ListCtrl):

    def __init__(self, parent, id=wx.ID_ANY, pos=wx.DefaultPosition, size=wx.DefaultSize, style=wx.LC_ICON, validator=wx.DefaultValidator, name=wx.ListCtrlNameStr):
        wx.ListCtrl.__init__(self, parent=parent, id=id, pos=pos, size=size, style=style, validator=validator, name=name)
        
        self.__row_num = 0
        self.InsertColumn(0, 'Reg #')
        self.InsertColumn(1, 'Register Name', width=150)
        self.InsertColumn(2, 'Value')

        # Inserting some test data
        self.insert_register(10024, "Engine Hours", 1337)
        self.insert_register(1034, "Engine Hours", 1338)

    def insert_register(self, reg_num, reg_name, reg_value):
        item = wx.ListItem()
        item.SetText(str(reg_num))

        # Without this row, an exception will be raised
        item.SetId(1020)
        self.InsertItem(item)

        self.SetItem(self.__row_num, 1, reg_name)
        self.SetItem(self.__row_num, 2, str(reg_value))

        self.__row_num += 1
`

**Comment by swprojects** [comment]
It might be because item ID cannot be -1 which is the default unset value?

However, how about doing it like this?

```python

def insert_register(self, reg_num, reg_name, reg_value):
        
        self.InsertItem(self.__row_num, str(reg_num))    
        self.SetItem(self.__row_num, 1, reg_name)
        self.SetItem(self.__row_num, 2, str(reg_value))
    
        self.__row_num += 1
```

**Comment by RobinD42** [comment]
Or even:
```python
    item.SetId(self.__row_num)
```
