### ISSUE TITLE
DataViewCtrl becomes unresponsive on Ubuntu 16.04 (and Debian 9)

### ISSUE THREAD

**Issue by arthur00** [wxWidgets/Phoenix#223]
I have an app that parses XML and displays it in the DataViewCtrl module of WxPython. It works fine on Ubuntu 14.04 and Debian 8, but as soon as I move to 16.04 or Debian 9, clicking on the arrows to expand the tree takes about 3-4 seconds, in which time the screen becomes unresponsive. Scrolling and collapsing the arrows cause a similar effect.

On inspecting the profiler, I see most time is spent in (millions of calls to)  GetParent of the DataViewModel (and subsequently, ObjectToItem and ItemToObject). I can't tell whether this behavior is different from its counterpart in Ubuntu 14.04 and Debian 8. 

Unfortunately, using the demo DataViewCtrl this behavior cannot be reproduced - it would probably need a few more levels and a few extra thousand lines. I believe I have somewhere around 3000 rows and about 5 levels in the tree. My object (used for ObjectToItem) is a simple python object containing 4 string properties and 1 lxml objectify node.

I've installed wxPython using the pip wheel for 16.04, so I'm (at this very moment) compiling the source to see if the results are the same.

Any help needed would be appreciated :)

Thank you,

--
Arthur Valadares

**Comment by RobinD42** [comment]
Was it a gtk2 or gtk3 build? The `DataViewCtrl` on Linux uses a GTK widget for the implementation so gtk2/3 could possibly make a big difference in performance with different implementations of that widget.  Either way, this is likely a wxWidgets issue and should be filed there.

**Comment by arthur00** [comment]
This was a gtk2 issue, although gtk3 does behave differently in newer distros. I have opened a ticket in wxWidgets (http://trac.wxwidgets.org/ticket/17793), so feel free to close it here. There are some more details in the wxWidgets bug report for future reference.
