### ISSUE TITLE
Add wheels for linux to the snapshot builds.

### ISSUE THREAD

**Issue by dougthor42** [wxWidgets/Phoenix#224]
> Wheels are one honking great idea -- let's do more of those!

-- A direct misquote from [The Zen of Python](https://www.python.org/dev/peps/pep-0020/)

You're already making wheels for a ton of different platforms and versions - that's awesome! However, it would also be pretty dang cool if we could get a wheel for Linux.

Sadly I don't know the caveats that go along with this request. For example, does a wheel made on an Ubuntu distribution work on RedHat? All I know is that I've been able to make a couple linux wheels of wxPython Phoenix (example [here](https://github.com/dougthor42/dougthor42.github.io/blob/master/tools/wxPython_Phoenix-3.0.3.dev1956%2Baab2833-cp34-cp34m-linux_x86_64.whl)).

In theory, it's as easy as running `python setup.py bdist_wheel` after the standard build succeeds, but in practice it's probably much different.

**Comment by dougthor42** [comment]
Actually I just noticed the `./linux/3.0.3.dev2749+f803d20/` directory in there, cool!

So I'll modify this request:

+ add more recent builds
+ change the directory structure so that the build version is not part of the folder structure.
    + This will allow people to use `pip --find-links` and always get the latest version for their OS, as it doesn't look like `pip` will recurse into subdirectories that are not package names [[1]](https://packaging.python.org/self_hosted_repository/#manual-repository)[[2]](https://github.com/pypa/pip/blob/master/pip/index.py#L101).
    + Might I suggest something like:
    ```
    - snapshot-builds
      - linux
        - gtk2
          + centos-7
          + ubuntu-14.04
          + ubuntu-16.04
        - gtk3
          + centos-7
          + ubuntu-14.04
          - ubuntu-16.04
            . wxPython_Phoenix-3.0.3.dev2749+f803d20-cp27-cp27mu-linux_x86_64.whl
            . wxPython_Phoenix-3.0.3.dev2749+f803d20-cp35-cp35m-linux_x86_64.whl
            . wxPython_Phoenix-3.0.3.dev2804+0a44abb-cp35-cp35m-linux_x86_64.whl
            . wxPython_Phoenix-3.0.3.dev2804+0a44abb-cp36-cp36m-linux_x86_64.whl
    ```

**Comment by RobinD42** [comment]
> add more recent builds

Oops, I forgot to start the script when the other builds were running. It's running now.

> change the directory structure

Good idea. I'll update the build and upload script.

**Comment by dougthor42** [comment]
Wonderful, that works great!
