### ISSUE TITLE
ultimatelistctrl.py

### ISSUE THREAD

**Issue by da-dada** [wxWidgets/Phoenix#2244]
on line **10938** there should be a **positive stretch factor** otherwise a multiline column label may be corrupted

**Comment by RobinD42** [comment]
This issue has been mentioned on **Discuss wxPython**. There might be relevant details there:

https://discuss.wxpython.org/t/ultimatelistctrl-setheaderheight-does-not-work/36089/5

**Comment by da-dada** [comment]
the same faux pas is on line **10976**
