### ISSUE TITLE
Move method cant move window out of screen on Linux

### ISSUE THREAD

**Issue by Wheele9** [wxWidgets/Phoenix#228]
i have a  wxpython app, which runs on Windows 7 and 10 superbly. With self.Move(x,y) I can move my window. If x, or y is negative, part of my window or the whole window is out of screen. I want to achieve this behavior on Linux. On ubuntu 16.04 I tried on unity and kde, but it didnt work, the whole window is always visible. I'm using wxPython-Phoenix  3.0.3.dev2749+f803d20 with python 3.5.2 on ubuntu 16.04LTS.  I've attached a basic version, which works well on windows, not on linux. (only txt attachments are available)

[tut2.txt](https://github.com/wxWidgets/Phoenix/files/765033/tut2.txt)

**Comment by swt2c** [comment]
It doesn't move at all for me on Fedora (GTK+3 and on Wayland, so could be a bug related to either of those).  But this probably isn't something specific to wxPython.

**Comment by Wheele9** [comment]
Yeah I start to see, that wxPython behaves quite differently unfortunately on linux.

**Comment by RobinD42** [comment]
I expect the WM or DE will have more of an influence on this than anything else. Back when I was still using Desktop Linux a lot I had noticed a trend where preferences were set by default that would force windows to remain visible on screen.
