### ISSUE TITLE
Pip install of wxPython 4.2.0 fails on CentOS7 with Python 3.9.9

### ISSUE THREAD

**Issue by basser** [wxWidgets/Phoenix#2289]
Hi everyone, 

we are having trouble installing wxPython 4.2 on a CentOS 7 system. 

So far we have been running with wxPython 4.1.1 but encountered an issue when undocking Panes in the agw.AuiManager.
This seems to be fixed with 4.2 (confirmed at least on Windows), so we tried to make the switch, 
but had no luck installing the new version on the customer's target machine, which is a CentOS 7.
It looks like a rabbit hole so deep, that I don't dare venturing in alone 
– so any ideas what could be causing this or how to tackle or work around it would be highly appreciated.

Thank You.

Operating system: CentOS7
wxPython version & source: 4.2.0 via pypi 
Python version & source: 3.9.9 built from source
with GCC 4.8.5 20150623 (Red Had 4.8.5-44)

`python3.9 -m pip install wxPython` fails with the following message:
(attached a detailed log: [error.txt](https://github.com/wxWidgets/Phoenix/files/9682638/error.txt))

```
      [ 15/937] Compiling sip/cpp/sip_corewxAccessible.cpp
      In file included from ../../../../sip/cpp/sipAPI_core.h:13:0,
                       from ../../../../sip/cpp/sip_corewxListView.cpp:10:
      ../../../../sip/siplib/sip.h:35:55: error: typedef 'sipExceptionHandler' is initialized (use decltype instead)
       typedef bool (*sipExceptionHandler)(std::exception_ptr);
                                                             ^
      // see attached error.txt for the full log   
                                
      ../../../../sip/siplib/sip.h:1667:68: error: ISO C++ forbids declaration of 'sipExceptionHandler' with no type [-fpermissive]
           sipExceptionHandler (*api_next_exception_handler)(void **statep);
                                                                          ^
      ../../../../sip/siplib/sip.h:1667:68: error: 'sipExceptionHandler' declared as function returning a function

      Waf: Leaving directory `/tmp/pip-install-kz5kfutv/wxpython_d301e473fdeb41eca4c0e5504f72cce7/build/waf/3.9/gtk3'
      Build failed
```

For what it's worth: wxPython4.1.1 installs on the same machine without a problem.

**Comment by FeridunFildis** [comment]
I resolve the issue as follows:
- located and commented out the line containing typedef bool (*sipExceptionHandler)(std::exception_ptr)
- inserted the following lines: 

bool sipExceptionHandlerFunc(std::exception_ptr);
typedef decltype(&sipExceptionHandlerFunc) sipExceptionHandler

I hope it helps.

**Comment by iluvpomeranians** [comment]
@Basser I'm running into the same problem right now. The latest wheel file they had for CentOs7 was for python3.6 which gives wxPython 4.1.1 but I need 4.2.0. Can you go into detail on what you did to get 4.2.0? 

Thanks
