### ISSUE TITLE
Is 3.0 and 3.1 snapshot builds possible at the same time?

### ISSUE THREAD

**Issue by Metallicow** [wxWidgets/Phoenix#229]
@RobinD42 
Is 3.0 and 3.1 Phoenix snapshot builds possible at the same time?
That way we can get the other new widgets and scintilla updates...
Can the 2 versions be built along side each other?
...and if not, then will there be a Classic 3.1 build anytime soon?

**Comment by RobinD42** [comment]
I'll give it some thought.

**Comment by RobinD42** [comment]
Since there is just one of me the answer is "probably not." However the current plan is to switch to wxWidgets 3.1 after wxPython 4.0.0 is finalized so hopefully it won't be too long.
