### ISSUE TITLE
"invalid window" error in window.cpp(1273) when creating dialog from menu option 

### ISSUE THREAD

**Issue by Qamar6** [wxWidgets/Phoenix#2292]
**Operating system**: Windows 10 Pro 21H2 x64
**wxPython version & source**:         4.2.0 
**Python version & source**:            3.9.13 64 bit 

**Description of the problem**:
In my small test app (see code below) MenuBar is created on MainFrame as a child.
MenuBar has one menu "Field" which consists of one submenu option "Settings".
When user presses this option dialog "MyDialog" has to be created and shown modally, but creation doesn't work.
I see this error in console instead;

Traceback (most recent call last):
  File "D:\...\TST_Dialog_issue.py", line 24, in Menu203
    dlg = MyDialog(self, wx.ID_ANY, "Field settings")
  File "D:\...\TST_Dialog_issue.py", line 10, in __init__
    self.Create(parent, id, title, pos, size, style, name)
wx._core.wxAssertionError: C++ assertion ""((HWND)GetHWND())"" failed at ..\..\src\msw\window.cpp(1273) in wxWindow::GetLayoutDirection(): invalid window

![123](https://user-images.githubusercontent.com/115096788/194109155-3451c81d-e90f-417d-a67c-b195ab96d8f3.jpg)

Note that in other conditions dialog creation works fine.
For example, when it is called right in MainFrame.__init__() (without MenuBar) it is created successfully.

And other menu options (without dialog calling) works properly too.

Last configuration on which this code worked good in my case: Win7 x32 + Python 3.8 + wxPython 4.0.7.post2

<details>
  <summary>Code Example (click to expand)</summary>

```python
import wx

class MyDialog(wx.Dialog):
    def __init__(self, parent, id, title, size=wx.DefaultSize, pos=wx.DefaultPosition, style=wx.DEFAULT_DIALOG_STYLE, name='dialog'):
        wx.Dialog.__init__(self)
        
        self.SetExtraStyle(wx.DIALOG_EX_CONTEXTHELP)
        self.Create(parent, id, title, pos, size, style, name)

class MenuBar(wx.MenuBar):
    def __init__(self, Parent):
        wx.MenuBar.__init__(self,style=0)

        menu2 = wx.Menu()
        menu2.Append(203, "Settings", "Settings", wx.ITEM_NORMAL)
        self.Append(menu2, "Field")

        Parent.SetMenuBar(self)
        Parent.Bind(wx.EVT_MENU, self.Menu203, id=203)

    def Menu203(self, event): 
        dlg = MyDialog(self, wx.ID_ANY, "Field settings")
        dlg.CenterOnScreen()
        val = dlg.ShowModal()


class MainFrame(wx.Frame):
    def __init__(self):
        wx.Frame.__init__(self, None, title="Dialog TST")
        MenuBar(self)

if __name__ == "__main__":
    app = wx.App()
    MainFrame().Show()
    app.MainLoop()
    
```
</details>

**Comment by tautv** [comment]
It works if you remove the parent from the Dialog on this line:
```dlg = MyDialog(self, wx.ID_ANY, "Field settings")```
to:
```dlg = MyDialog(None, wx.ID_ANY, "Field settings")```

Seems like the problem is that assigning dialog to parent of ```class MenuBar(wx.MenuBar)``` is tripping this over.

I'd set a var for Menu's parent:
```class MenuBar(wx.MenuBar):
    def __init__(self, Parent):
        wx.MenuBar.__init__(self,style=0)
        self.parent = Parent```
and then can use 
```dlg = MyDialog(self.parent, wx.ID_ANY, "Field settings")```


Hope this helps!

**Comment by Qamar6** [comment]
Hi [tautv](https://github.com/tautv)!
Thanks so much! It really works.

But however it seems stragne that it worked on old configuration (Python 3.8 + wxPython 4.0.7.post2) and doesn't on new one.

Thanks a lot anyway.
