### ISSUE TITLE
wx.DateTime.FromDMY() zero based month index

### ISSUE THREAD

**Issue by laurenpetch** [wxWidgets/Phoenix#2300]
Hi, 

I'm working with wxpython 4.1.1 in a python 3.7 environment. I've just noticed that the `wx.DateTime.FromDMY()` function appears to use zero based month indexing (i.e. to get 31st October i need to enter `wx.DateTime.FromDMY(31, 9, year=2022)`

It errors if i put a combination with too many days for the month such as `wx.DateTime.FromDMY(31, 10, year=2022)`

But then if I put the month as 12 it seems to revert it to October (or possibly the current month?)

We've been using this piece of code for a couple of years with months from 1 - 12 and haven't noticed the issue but possibly I just missed it. Is this the correct behaviour? If so I can just  update the code to account for it.

Thanks

**Comment by swt2c** [comment]
So it looks like `wx.DateTime.FromDMY()` technically takes a `wx.DateTime.Month` object for the month parameter.  This maps to a C++ enum that starts, the numbering from 0, so the month of October is:

```
>>> wx.DateTime.Month.Oct
9
```
It's definitely unfortunate that this enum doesn't start at 1, but it does seem like that is how it is.  :(
