### ISSUE TITLE
wxPython builds without errors but import fails with symbol not found error on macOS M1

### ISSUE THREAD

**Issue by Bleistein** [wxWidgets/Phoenix#2304]
**Operating system**: macOS 13.0.1
**wxPython version & source**: wxPython-4.2.0.tar.gz
**Python version & source**:  homebrew 3.11

**Description of the problem**: The build is done according to the description https://wxpython.org/blog/2017-08-17-builds-for-linux-with-pip/. The build finishes without errors on a Macbook Pro **M1**. The final check of the **import fails**.

```
python3 -c "import wx; a=wx.App(); wx.Frame(None,title='hello world').Show(); a.MainLoop();"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/homebrew/lib/python3.11/site-packages/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "/opt/homebrew/lib/python3.11/site-packages/wx/core.py", line 12, in <module>
    from ._core import *
ImportError: dlopen(/opt/homebrew/lib/python3.11/site-packages/wx/_core.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '__ZN10wxBoxSizer20InformFirstDirectionEiii'
```

**Comment by swt2c** [comment]
Do you happen to have the complete build log?

**Comment by swt2c** [comment]
I don't see any log.  It looks like you perhaps tried to email it?  Perhaps Github doesn't allow that.

**Comment by Bleistein** [comment]
[build.log](https://github.com/wxWidgets/Phoenix/files/10039711/build.log)

**Comment by Bleistein** [comment]
We are able to successfully build and execute wxPython on an intel based Macbook Pro with identical software releases. Looks like the problem is specific to the M1 (arm64) setup.

**Comment by swt2c** [comment]
Indeed, these lines in the log are likely relevant:
```
  ld: warning: ignoring file /private/var/folders/x0/45nfh45123q1qt0ft24809lh0000gp/T/pip-req-build-0g83upwk/build/wxbld/lib/libwx_osx_cocoau_core-3.2.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
  ld: warning: ignoring file /private/var/folders/x0/45nfh45123q1qt0ft24809lh0000gp/T/pip-req-build-0g83upwk/build/wxbld/lib/libwx_baseu-3.2.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
  ld: warning: ignoring file /private/var/folders/x0/45nfh45123q1qt0ft24809lh0000gp/T/pip-req-build-0g83upwk/build/wxbld/lib/libwx_osx_cocoau_propgrid-3.2.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
```

**Comment by swt2c** [comment]
Yes, it looks like wxWidgets was built for x86_64, so that's the problem.  For whatever reason, enable_universal_binary=default is leading to an x86_64 build on your machine.

I'm not sure how to work around this with a pip build, so you may have to build a wheel with the development instructions, something like: `python build.py --mac_arch=arm64 bdist_wheel`.

**Comment by Bleistein** [comment]
We set up the development environment and compiled with

```
python build.py dox etg --nodoc sip build
```

This was generating intel cpu files. I did not dig in further how build.py detects the cpu architectur, but there is nothing special on our configuration used here. So it looks like the autodetect somewhere in the scipt is in trouble or we are an edge case...

```
sysctl -a | grep brand
machdep.cpu.brand_string: Apple M1 Max
```
We then recompiled with

```
python build.py --mac_arch=arm64 dox etg --nodoc sip build
```

and created arm64 files without problems.

Create a wheel with the command You proposed

```
python build.py --mac_arch=arm64 bdist_wheel
```
worked fine. Thank You!

**Comment by Bleistein** [comment]
The reason why the M1 CPU configuration is not properly detected is that in the file build.py, line 413 no default for the macOS configuration is set. So the build process is at the mercy of default decisions in different parts of the build chain. I added the current "universal" definition that in my opinion is the best default for macOS related builds. The only disadvantage is a increased build time...

```
       ("mac_arch",       ("arm64,x86_64",    "Comma separated list of architectures to build on Mac")),
```

To avoid the "complicated" build from source it is also possible to specify build arguments in the environment so a normal "pip build" is possible.

```
export WXPYTHON_BUILD_ARGS="--mac_arch=arm64,x86_64"
pip install wxPython
```
