### ISSUE TITLE
AGW AUI unusable after vetoing close event

### ISSUE THREAD

**Issue by petrasovaa** [wxWidgets/Phoenix#2313]
I am trying to veto a close event when closing a window with agw AUI manager. The problem is that the UI is then unusable, (un)docking doesn't work, although the actual widgets still can be used. It can be reproduced in the demo/agw/AUI.py by adding this to OnClose handler:
```
    def OnClose(self):
        dlg = wx.MessageDialog(
            self,
            'Do you really want to close this window?',
            'Confirm',
            wx.YES_NO | wx.NO_DEFAULT | wx.ICON_QUESTION
        ).ShowModal()

        if dlg == wx.ID_NO:
            event.Veto()
            return
    ...
```
https://github.com/wxWidgets/Phoenix/blob/master/demo/agw/AUI.py#L1537

This is how it looks like normally:
![AUI Test Frame_001](https://user-images.githubusercontent.com/7494312/205213319-fa604858-5674-42cc-a85a-2fdfd3c42299.png)

And here with the changes (looks the same after closing the dialog with No):
![AUI Test Frame_002](https://user-images.githubusercontent.com/7494312/205213405-36ccfda1-b519-4b10-8be2-f4c72000626f.png)

**Operating system**: Ubuntu Linux
**wxPython version & source**:          4.2.0 gtk3 (phoenix) wxWidgets 3.2.0
**Python version & source**:           3.8.13

**Comment by Metallicow** [comment]
Andrea is sorta retired. If this is what you are trying to do, then yes it can be done, Submit a pull request.
I think I integrated something similar when I forked AGW.AUI for my own project...
If you cannot reproduce a "code chunk" to pull request(PullReqz), then the rest of us can feel your pain until, one of us just implements it or takes your word for it. Please bear with us. Ex: Plz br wit me

If no one responds in a month, don't feel bad to bump the issue.

**Comment by Metallicow** [comment]
Maybe just force-messaging here @infinity77 directly might answer your inquiry.... He may not be aware of you...

**Comment by petrasovaa** [comment]
I listed those version there, maybe it got overlooked. I was looking into the issue myself, but couldn't figure it out with my limited knowledge of wx inner workings and didn't have time for deeper analysis...

**Comment by tmszi** [comment]
@petrasovaa Problematic is `wx.EVT_CLOSE` event handler ordering

First is handled `AuiManager()` class `OnClose()` method `wx.EVT_CLOSE` event handler:

https://github.com/wxWidgets/Phoenix/blob/a1184286703cf24c4b88e5bc14cf2979c1b1ea00/wx/lib/agw/aui/framemanager.py#L4403-L4410

Which will automatically uninitialize the AUI Manager (line 4410)  every time,  and causing all AUI Manager panels to "freeze".

Second is handled `AuiFrame()` class `OnClose()` method `wx.EVT_CLOSE` event handler demo example with customized `OnClose()` method with confirm quit dialog :

```python
def OnClose(self, event):
    dlg = wx.MessageDialog(
        self,
        'Do you really want to close this window?',
        'Confirm',
        wx.YES_NO | wx.NO_DEFAULT | wx.ICON_QUESTION
    ).ShowModal()

    if dlg == wx.ID_NO:
        event.Veto()
        return
```
