### ISSUE TITLE
Wheel build failure due to GTK 3.0 dependency

### ISSUE THREAD

**Issue by junwoo091400** [wxWidgets/Phoenix#2326]
Operating system: Ubuntu 22.04
wxPython version & source: PyPi
Python version & source: Python 3.10.6

**Description of the problem**:
![image](https://user-images.githubusercontent.com/23277211/209834654-2b70791e-54be-498f-a9d7-fc0b6becb119.png)

`pip install wxpython==4.2.0` fails with error above.

It seems that GTK dependency was the cause for the failure to build a wheel. However, I would expect that such dependencies should be detected/installed if the package requires it.

Would there be a way to automatically install the dependency (GTK 3)? Otherwise, are all users of the `wxpython` module supposed to be aware of this dependency that needs to be manually installed?

**Comment by junwoo091400** [comment]
Seems like it is noted down here: https://github.com/wxWidgets/Phoenix/blob/master/README.rst:

"On Ubuntu the following development packages and their dependencies should be installed in order to build Phoenix"

So I have manually installed the `libgtk-3-dev` via `apt-get`, but I am still wondering if this is an ideal situation for newcomers who are interested in installing the package via pip and just start using it :thinking:

**Comment by swt2c** [comment]
There's no way pip can install C/C++ dependencies automatically, unfortunately.

You can, however, install wxPython from the Ubuntu package repositories.  The package name is `python3-wxpython4`.

**Comment by junwoo091400** [comment]
> There's no way pip can install C/C++ dependencies automatically, unfortunately.

Oof gotcha, that's a tricky situation, of having C dependency :cry:. But thanks for clarification!

It was just being used in a program called Gooey: https://github.com/chriskiehl/Gooey/blob/be4b11b8f27f500e7326711641755ad44576d408/requirements.txt#L1, and unfortunately I think the users would then need to be warned there regarding issue then!

Thanks for the clarification :pray:
