### ISSUE TITLE
wx.lib.agw.aui.AuiNotebook => "Dragging a tab" bug

### ISSUE THREAD

**Issue by Nutznieser** [wxWidgets/Phoenix#233]
If you want drag-and-drop a tab of a wx.lib.agw.aui.AuiNotebook the application hangs after releasing the left mouse and the following error message occurs. (Environment: Python 3.5.3 | wxPython_Phoenix-3.0.3.dev2812+b3485d4-cp35-cp35m-win32 | Windows 10)

```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python 3.5\lib\site-packages\wx\lib\agw\aui\auibook.py", line 2023, in OnLeftUp
    self.ReleaseMouse()
wx._core.wxAssertionError: C++ assertion "!wxMouseCapture::stack.empty()" failed at ..\..\src\common\wincmn.cpp(3319) in wxWindowBase::ReleaseMouse(): Releasing mouse capture but capture stack empty?
```
I checked the problem also with the new demo on https://github.com/wxWidgets/Phoenix. If you start the "AUI test frame" from the demo and you try dragging the tabs, the same bug appears => self.ReleaseMouse() raise an wx._core.wxAssertionError ...

**Comment by mprosperi** [comment]
#93 duplication

**Comment by RobinD42** [comment]
Thanks for noticing the duplication @mprosperi. Closing.
