### ISSUE TITLE
wx.ThreadEvent not implemented

### ISSUE THREAD

**Issue by reticulatus** [wxWidgets/Phoenix#2338]
**Operating system**: Linux Mint 21.1
**wxPython version & source**: wxPython 4.2.0 installed from https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04 using pip.
**Python version & source**: 3.10.6 from Linux Mint 21.1

**Description of the problem**:
The description of wx.QueueEvent in the wxPython docs for 4.2.0 (https://docs.wxpython.org/wx.EvtHandler.html#wx.EvtHandler.QueueEvent) describes using ThreadEvent instead of wx.CommandEvent.

However, when I try to create a ThreadEvent object I get an AttributeError:

AttributeError: module 'wx' has no attribute 'ThreadEvent'

**Comment by swt2c** [comment]
Yes, it seems it has been commented out for 12 years :-)
https://github.com/wxWidgets/Phoenix/blame/master/etg/event.py#L77

It looks like it shouldn't be too hard to add it, other than the `SetPayload() / GetPayload()` methods.
