### ISSUE TITLE
"python build.py dox && python build.py build_wx --jobs=4 && python build.py etg --nodoc && python build.py sip && python build.py build_py --jobs=4" fails due to "../../../sip/cpp/sip_html2cmodule.cpp:386:4: error: ‘wxWebView’ in namespace ‘::’ does not name a type"

### ISSUE THREAD

**Issue by krichter722** [wxWidgets/Phoenix#234]
`python build.py dox && python build.py build_wx --jobs=4 && python build.py etg --nodoc && python build.py sip && python build.py build_py --jobs=4` fails due to `../../../sip/cpp/sip_html2cmodule.cpp:386:4: error: ‘wxWebView’ in namespace ‘::’ does not name a type` on Ubuntu 16.10, see https://richtercloud.de:451/index.php/s/ZPC8gwGLWPOtJBy for complete build log.

experienced with b3485d4d

**Comment by swt2c** [comment]
```
checking for WEBKIT... configure: WARNING: webkitgtk not found.
configure: WARNING: WebKit not available, disabling wxWebView
```

You don't have the webkit development packages installed.  On Ubuntu, that should be libwebkitgtk-dev.

**Comment by krichter722** [comment]
> You don't have the webkit development packages installed. On Ubuntu, that should be libwebkitgtk-dev.

That fixed the build, thank you. I suggest to make one of the commands above fail with a verbose error message complaining that either the package/library needs to be installed or the component has to be deactived (if possible), rather than confront the user with a build failure.

**Comment by swt2c** [comment]
Looks like @mesalu is working on just that: https://github.com/wxWidgets/Phoenix/pull/212

**Comment by mesalu** [comment]
Class stubs, to disable features when a library is not present, are also on the horizon. Right now it's looking like that will be the preferred approach. 
I think with some clean up dependency checking will still be a nice quality-of-life feature. I think @RobinD42 and I are going to discuss this a bit once we both get some more free time.
