### ISSUE TITLE
OGL library no longer draws arrowheads 

### ISSUE THREAD

**Issue by abulka** [wxWidgets/Phoenix#2349]
**Operating system**: mac ventura on M1 mac mini
**wxPython version & source**:  4.2.0 via pip
**Python version & source**:   python 3.10.3 via pyenv and venv

**Description of the problem**:

The OGL library no longer draws arrowheads at the ends of lines - possibly python 3.10 float/int related though I don't see any exceptions.

To reproduce, simply run the `wxdemo` and view the OGL demo - notice all the arrowheads are missing.

![Screenshot 2023-02-17 at 12 09 22 pm](https://user-images.githubusercontent.com/11467530/219524683-0aa5b774-7c40-479c-bd5d-42fc56c517a0.png)

**Comment by abulka** [comment]
Seems like the fix is to add
```python
points = [[int(x), int(y)] for x, y in points]  # ints needed for Python >= 3.10
```
prior to calls to `dc.DrawPolygon(points)` in e.g. `/wx/lib/ogl/lines.py` and possibly other places within the ogl library.  I wonder if there is a way to catch any attempt to pass floats to all the `dc` primitive operations, thus flush out any remaining bugs like this.

P.S. Should this issue have been raised in https://github.com/wxWidgets/wxWidgets/issues ?

**Comment by RobinD42** [comment]
This issue has been mentioned on **Discuss wxPython**. There might be relevant details there:

https://discuss.wxpython.org/t/ogl-lineshape-no-arrow-displayed/36523/2
