### ISSUE TITLE
wxPython build fails

### ISSUE THREAD

**Issue by rossKayHe** [wxWidgets/Phoenix#2353]
**Operating system**:                       Windows 10 Home build 19045.2486
**wxPython version & source**:        py -m pip install -Uv wxpython
**Python version & source**:            Pythion 3.11.2
**Description of the problem**:

fails to install

<details>
<log>
 Running command Running setup.py install for wxpython
  C:\Users\rossj\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\dist.py:771: UserWarning: Usage of dash-separated 'license-file' will not be supported in future versions. Please use the underscore name 'license_file' instead
    warnings.warn(
  C:\Users\rossj\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\config\setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
    warnings.warn(msg, warning_class)
  C:\Users\rossj\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\dist.py:317: DistDeprecationWarning: use_2to3 is ignored.
    warnings.warn(f"{attr} is ignored.", DistDeprecationWarning)
  running install
  C:\Users\rossj\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
    warnings.warn(
  running build
  Will build using: "C:\Users\rossj\AppData\Local\Programs\Python\Python311\python.exe"
  3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)]
  Python's architecture is 64bit
  cfg.VERSION: 4.2.0

  Running command: build
  Running command: build_wx
  CL.exe: NOT FOUND
  Downloading microsoft.web.webview2 1.0.1185.39...
  Connection successful...
  Data downloaded...
  wxWidgets build options: ['--wxpython', '--unicode']
  Updating wx/msw/setup.h
  setting build options...
  Error building
  ERROR: failed building wxWidgets
  Traceback (most recent call last):
    File "C:\Users\rossj\AppData\Local\Temp\pip-install-n60q7xfg\wxpython_0bcf8f38a36442e6b359fd63bb6cf524\build.py", line 1563, in cmd_build_wx
      wxbuild.main(wxDir(), build_options)
    File "C:\Users\rossj\AppData\Local\Temp\pip-install-n60q7xfg\wxpython_0bcf8f38a36442e6b359fd63bb6cf524\buildtools\build_wxwidgets.py", line 503, in main
      exitIfError(wxBuilder.build(dir=buildDir, options=args), "Error building")
    File "C:\Users\rossj\AppData\Local\Temp\pip-install-n60q7xfg\wxpython_0bcf8f38a36442e6b359fd63bb6cf524\buildtools\build_wxwidgets.py", line 72, in exitIfError
      raise builder.BuildError(msg)
  buildtools.builder.BuildError: Error building
  Finished command: build_wx (0m1.563s)
  Finished command: build (0m1.563s)
  WARNING: Building this way assumes that all generated files have been
  generated already.  If that is not the case then use build.py directly
  to generate the source and perform the build stage.  You can use
  --skip-build with the bdist_* or install commands to avoid this
  message and the wxWidgets and Phoenix build steps in the future.

  "C:\Users\rossj\AppData\Local\Programs\Python\Python311\python.exe" -u build.py build
  Command '"C:\Users\rossj\AppData\Local\Programs\Python\Python311\python.exe" -u build.py build' failed with exit code 1.
  error: subprocess-exited-with-error

  × Running setup.py install for wxpython did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: 'C:\Users\rossj\AppData\Local\Programs\Python\Python311\python.exe' -u -c '
  exec(compile('"'"''"'"''"'"'
  # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
  #
  # - It imports setuptools before invoking setup.py, to enable projects that directly
  #   import from `distutils.core` to work with newer packaging standards.
  # - It provides a clear error message when setuptools is not installed.
  # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
  #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
  #     manifest_maker: standard file '"'"'-c'"'"' not found".
  # - It generates a shim setup.py, for handling setup.cfg-only projects.
  import os, sys, tokenize

  try:
      import setuptools
  except ImportError as error:
      print(
          "ERROR: Can not execute `setup.py` since setuptools is not available in "
          "the build environment.",
          file=sys.stderr,
      )
      sys.exit(1)

  __file__ = %r
  sys.argv[0] = __file__

  if os.path.exists(__file__):
      filename = __file__
      with tokenize.open(__file__) as f:
          setup_py_code = f.read()
  else:
      filename = "<auto-generated setuptools caller>"
      setup_py_code = "from setuptools import setup; setup()"

  exec(compile(setup_py_code, filename, "exec"))
  '"'"''"'"''"'"' % ('"'"'C:\\Users\\rossj\\AppData\\Local\\Temp\\pip-install-n60q7xfg\\wxpython_0bcf8f38a36442e6b359fd63bb6cf524\\setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' install --record 'C:\Users\rossj\AppData\Local\Temp\pip-record-8z64udce\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\rossj\AppData\Local\Programs\Python\Python311\Include\wxpython'
  cwd: C:\Users\rossj\AppData\Local\Temp\pip-install-n60q7xfg\wxpython_0bcf8f38a36442e6b359fd63bb6cf524\
  Running setup.py install for wxpython ... error
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> wxpython

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

```python
# Put code sample here
```
</details>

**Comment by lebao3105** [comment]
wxPython does not support Python 3.11 yet.

**Comment by rossKayHe** [comment]
oh it's the python version then...

**Comment by rotch-jntm** [comment]
Please help me see what is wrong with this code, thank you.
[window.docx](https://github.com/wxWidgets/Phoenix/files/10919810/window.docx)

**Comment by lebao3105** [comment]
> Please help me see what is wrong with this code, thank you.
> 
> [window.docx](https://github.com/wxWidgets/Phoenix/files/10919810/window.docx)
> 
> 

On this line:
'''python
b = wx.Button(parent=zpanel, label='OK',pos=(100,50))
'''

You have passed zpanel as a parameter of wx.Button - it should be '''panel''' instead.

**Comment by rossKayHe** [comment]
What is the latest supported  version?

**Comment by lebao3105** [comment]
> What is the latest supported  version?

It's Python 3.10

**Comment by monkut** [comment]
not working for me with 3.9 on ubuntu 22.04.. no apparent error messages 

```
      The configuration failed
      (complete log in /tmp/pip-install-g5kpfyhp/wxpython_9c4890352b0646b1bff15d89367e4dcf/build/waf/3.9/gtk3/config.log)

```

And the log file gets cleaned up after install attempt, so I can't check the log.

**Comment by swt2c** [comment]
wxPython 4.2.1 is now out with Windows wheels built for Python 3.10 and 3.11. Please try installing 4.2.1.
