### ISSUE TITLE
wxPython Not installing on Python 3.11

### ISSUE THREAD

**Issue by planetminguez** [wxWidgets/Phoenix#2358]
**Operating system**:
**wxPython version & source**:          
**Python version & source**:            

**Description of the problem**:
While trying to install wxPython 4.20 on macOS Ventura 13.1 it gets stuck on 'Building wheel" and has for quit some time. It gets stuck on there for at least 30 mins ...I have to shutdown(fans running on high and all!!! Mac(2019) intel model.This has been going on for a few weeks now. Installation simply won't install it via pip.Please fix

```python
# Put code sample here
```
</details>

**Comment by swt2c** [comment]
There aren't any wheels for Python 3.11, so the wheel has to be built.  This takes a while, so it sounds like you are seeing expected behavior.

**Comment by planetminguez** [comment]
over a hour to the point where all fans kick on and Laptop has to be shut down from over heating on a 2020 MacBook?

**Comment by swt2c** [comment]
Yes, it can take over an hour to build, depending on how many cores you have.

Seems like a cooling problem with your laptop, though, if it can't run without overheating.

**Comment by alexhuangdz** [comment]
Hope author and provide a wxpython installation wheel for python3.11 release.

**Comment by JLTs66** [comment]
For the problem, same on Windows 11.

@planetminguez 
> over a hour to the point where all fans kick on and Laptop has to be shut down from over heating on a 2020 MacBook?
Don't buy a crappy laptop. Since after 2013, all Mac Book is just a heresy; a engineering shame.

**Comment by JLTs66** [comment]
Wheels for Python 3.11 doesn't works. Are probably made for python 3.10.

**Comment by planetminguez** [comment]
I dunno still won't .......

**Comment by oailton** [comment]
I was able to install wxPython 4.2.0 on Python 3.11, Windows 11 by first installing the attrdict package from PyPI and editing its files mappings.py, mixins.py, merge.py and default.py changing occurrencies of "from colections import" to "from collections.abc import". I have Visual Studio 2022 Professional. Is this an expected scenario? Have I misunderstood something?

**Comment by lebao3105** [comment]
> I was able to install wxPython 4.2.0 on Python 3.11, Windows 11 by first installing the attrdict package from PyPI and editing its files mappings.py, mixins.py, merge.py and default.py changing occurrencies of "from colections import" to "from collections.abc import". I have Visual Studio 2022 Professional. Is this an expected scenario? Have I misunderstood something?
> 
> 
> 
> 

You don't need to install attrdict - use attrdict3 instead. The problem here is there are no offical wheels for Python 3.11 and it takes time to build and install wxPython from source.

**Comment by oailton** [comment]
> > I was able to install wxPython 4.2.0 on Python 3.11, Windows 11 by first installing the attrdict package from PyPI and editing its files mappings.py, mixins.py, merge.py and default.py changing occurrencies of "from colections import" to "from collections.abc import". I have Visual Studio 2022 Professional. Is this an expected scenario? Have I misunderstood something?
> 
> You don't need to install attrdict - use attrdict3 instead. The problem here is there are no offical wheels for Python 3.11 and it takes time to build and install wxPython from source.

Thanks, you are right, I just retried with attrdict3 and it worked (20 minutes to build wheel). But, shouldn't pip be able to pickup attrdict3 by itself as a dependency of wxPython?

**Comment by planetminguez** [comment]
This issue has been resolved
