### ISSUE TITLE
Have September 2022 changes to PDF viewer been released

### ISSUE THREAD

**Issue by johns1c** [wxWidgets/Phoenix#2370]
Have the September 2022 fixes to the PDF viewer to avoid passing floats got into PyPi yet?  

running under Windows 11 and Python 3.10.4 in a virtual environment .  Had problems with viewer.py
which were easily fixed - then checked git  and it was fixed in last September.  Is it just waiting for a release or is this
an oversight?

also the  example given on #2204 seemed to need a few extra lines of code  to display the first page of the PDF)  once the fix is made, although, of course, the wxpython demo includes code to display and page through a pdf.

# My Environment (as of 2023-04-03)

```
(Catview) C:\Users\Chris Johnson\Python\Catview>py -V
Python 3.10.4

(Catview) C:\Users\Chris Johnson\Python\Catview>pip show  wxPython
Name: wxPython
Version: 4.2.0
Summary: Cross platform GUI toolkit for Python, "Phoenix" version
Home-page: http://wxPython.org/
Author: Robin Dunn
Author-email: robin@alldunn.com
License: wxWindows Library License (https://opensource.org/licenses/wxwindows.php)
Location: c:\users\chris johnson\python\catview\lib\site-packages
Requires: numpy, pillow, six
Required-by:
```

# Simple test code to display first page of a pdf 

```
import sys
import wx
from wx.lib.pdfviewer import pdfViewer
file = sys.argv[1] 
app = wx.App(False)
frame = wx.Frame(None)
viewer = pdfViewer(frame, nid=-1, pos=(-1, -1), size=(-1, -1), style=0)
viewer.LoadFile(file) # put a PDF file called 'test.pdf' in the working dir
frame.Layout()
frame.Show()
app.MainLoop()
```

**Comment by swt2c** [comment]
> Have the September 2022 fixes to the PDF viewer to avoid passing floats got into PyPi yet?

No.

> running under Windows 11 and Python 3.10.4 in a virtual environment . Had problems with viewer.py
which were easily fixed - then checked git and it was fixed in last September. Is it just waiting for a release or is this
an oversight?

Waiting for a release.  Unfortunately, @RobinD42 is the only one who can make releases.
