### ISSUE TITLE
Unable to install - error: legacy-install-failure

### ISSUE THREAD

**Issue by pallebone** [wxWidgets/Phoenix#2388]
**Operating system**: Debian Bookworm with python 3.7 in a virtual environment

**wxPython version & source**:  4.1.1
**Python version & source**: 3.7

**Description of the problem**:

I am not able to install wxPython with pip :(

pip install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-20.04 wxPython==4.1.1 --log /home/aragorn/wxpython_install.log 

Here is the log file. I have tried many different conmmands and suggestions but none seem to work. Unclear what to do to fix it.

Kind regards
Peter

[wxpython_install.log](https://github.com/wxWidgets/Phoenix/files/11417370/wxpython_install.log)

**Comment by swt2c** [comment]
Not entirely sure what the problem is, but likely some incompatibility with whatever version of setuptools you're using and Debian.

Do you really need those exact versions: Python 3.7 and wxPython 4.11?  If not, wxPython 4.2.0 is available from the Debian Bookworm package repositories, compatible with Python 3.11.

**Comment by pallebone** [comment]
Sadly this program requires these exact versions, so I cant change it :(

https://www.amuletmc.com/installing-from-source

**Comment by pallebone** [comment]
I will ask them if I can try a later python version if you think that would help?

**Comment by pallebone** [comment]
Still working on this and will come back to you.

**Comment by pallebone** [comment]
> You are getting the same error when you're trying to install pyopengl, so it seems less likely this has anything to do with wxPython or pyopengl. What version of setuptools are you using?
> 
> ```
> 2023-05-09T15:42:04,517   Traceback (most recent call last):
> 2023-05-09T15:42:04,517     File "<string>", line 2, in <module>
> 2023-05-09T15:42:04,517     File "<pip-setuptools-caller>", line 34, in <module>
> 2023-05-09T15:42:04,517     File "/tmp/pip-install-wfpskz2s/pyopengl-accelerate_525b78bad83540f7aa777d15a324ef59/setup.py", line 128, in <module>
> 2023-05-09T15:42:04,517       setup (
> 2023-05-09T15:42:04,517     File "/home/aragorn/Downloads/Python-3.9.16/ve/lib/python3.9/site-packages/setuptools/__init__.py", line 108, in setup
> 2023-05-09T15:42:04,517       return distutils.core.setup(**attrs)
> 2023-05-09T15:42:04,517     File "/home/aragorn/Downloads/Python-3.9.16/ve/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
> 2023-05-09T15:42:04,517       return run_commands(dist)
> 2023-05-09T15:42:04,517     File "/home/aragorn/Downloads/Python-3.9.16/ve/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
> 2023-05-09T15:42:04,517       dist.run_commands()
> 2023-05-09T15:42:04,517     File "/home/aragorn/Downloads/Python-3.9.16/ve/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
> 2023-05-09T15:42:04,517       self.run_command(cmd)
> 2023-05-09T15:42:04,517     File "/home/aragorn/Downloads/Python-3.9.16/ve/lib/python3.9/site-packages/setuptools/dist.py", line 1213, in run_command
> 2023-05-09T15:42:04,517       super().run_command(command)
> 2023-05-09T15:42:04,517     File "/home/aragorn/Downloads/Python-3.9.16/ve/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
> 2023-05-09T15:42:04,518       cmd_obj.run()
> 2023-05-09T15:42:04,518     File "/home/aragorn/Downloads/Python-3.9.16/ve/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 360, in run
> 2023-05-09T15:42:04,518       self.run_command("install")
> 2023-05-09T15:42:04,518     File "/home/aragorn/Downloads/Python-3.9.16/ve/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
> 2023-05-09T15:42:04,518       self.distribution.run_command(command)
> 2023-05-09T15:42:04,518     File "/home/aragorn/Downloads/Python-3.9.16/ve/lib/python3.9/site-packages/setuptools/dist.py", line 1213, in run_command
> 2023-05-09T15:42:04,518       super().run_command(command)
> 2023-05-09T15:42:04,518     File "/home/aragorn/Downloads/Python-3.9.16/ve/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
> 2023-05-09T15:42:04,518       cmd_obj.run()
> 2023-05-09T15:42:04,518     File "/home/aragorn/Downloads/Python-3.9.16/ve/lib/python3.9/site-packages/setuptools/command/install.py", line 68, in run
> 2023-05-09T15:42:04,518       return orig.install.run(self)
> 2023-05-09T15:42:04,518     File "/home/aragorn/Downloads/Python-3.9.16/ve/lib/python3.9/site-packages/setuptools/_distutils/command/install.py", line 709, in run
> 2023-05-09T15:42:04,518       self.run_command(cmd_name)
> 2023-05-09T15:42:04,518     File "/home/aragorn/Downloads/Python-3.9.16/ve/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
> 2023-05-09T15:42:04,518       self.distribution.run_command(command)
> 2023-05-09T15:42:04,518     File "/home/aragorn/Downloads/Python-3.9.16/ve/lib/python3.9/site-packages/setuptools/dist.py", line 1213, in run_command
> 2023-05-09T15:42:04,518       super().run_command(command)
> 2023-05-09T15:42:04,518     File "/home/aragorn/Downloads/Python-3.9.16/ve/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
> 2023-05-09T15:42:04,518       cmd_obj.ensure_finalized()
> 2023-05-09T15:42:04,519     File "/home/aragorn/Downloads/Python-3.9.16/ve/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
> 2023-05-09T15:42:04,519       self.finalize_options()
> 2023-05-09T15:42:04,519     File "/home/aragorn/Downloads/Python-3.9.16/ve/lib/python3.9/site-packages/setuptools/command/install_lib.py", line 17, in finalize_options
> 2023-05-09T15:42:04,519       self.set_undefined_options('install',('install_layout','install_layout'))
> 2023-05-09T15:42:04,519     File "/home/aragorn/Downloads/Python-3.9.16/ve/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 296, in set_undefined_options
> 2023-05-09T15:42:04,519       setattr(self, dst_option, getattr(src_cmd_obj, src_option))
> 2023-05-09T15:42:04,519     File "/home/aragorn/Downloads/Python-3.9.16/ve/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
> 2023-05-09T15:42:04,519       raise AttributeError(attr)
> 2023-05-09T15:42:04,519   AttributeError: install_layout
> ```

(ve) aragorn@Aragorn:~/Downloads/Python-3.9.16$ pip list
Package    Version
---------- -------
Cython     0.29.34
numpy      1.24.3
pip        23.0.1
PyOpenGL   3.1.6
setuptools 66.1.1
wheel      0.38.4

For clarity here is what I am doing:
Steps:
1) https://www.python.org/downloads/source/      - download Python 3.9.16 - Dec. 6, 2022 Gzipped source tarball
2) Extract to a folder eg: ~/Downloads/Python-3.9.16 and cd to this directory to be able to build from source
3) mkdir ~/.localpython
4) ./configure --prefix=$HOME/.localpython
5) make && make install
(Python is now built in a directory)
7) virtualenv ve -p $HOME/.localpython/bin/python3.9
8) source ve/bin/activate   

pip install PyOpenGL
pip install cython
pip install numpy
pip install pyopengl-accelerate --log /home/aragorn/log.txt

pip install wxPython generates similar issues as you note.

Unclear why Python 3.9 cannot build these packages to me.

**Comment by pallebone** [comment]
I was able to build against one of the dependencies that was not working when the developer released a new version https://github.com/mcfletch/pyopengl/issues/97

As this now builds it has allowed an install of wxPython also

Please let me have a few days testing if possible as I will rebuild from scratch and check what I can and cant do and report back.

Kind regards
Pete

**Comment by pallebone** [comment]
Thank you I can now build with setuptools              67.8.0

Kind regards
Peter
