### ISSUE TITLE
Linux: Cannot reposition wx.Frame using SetSize(x=#, y=#, flags=wx.SIZE_USE_EXISTING)

### ISSUE THREAD

**Issue by davidfstr** [wxWidgets/Phoenix#2389]
**Operating system**: Ubuntu 22.04 LTS
**wxPython version & source**: pypi, 4.1.1 gtk3 (phoenix) wxWidgets 3.1.5
**Python version & source**: CPython 3.10.6

**Description of the problem**:

If you attempt to reposition a wx.Frame on Linux using wx.Window.SetSize(), the frame does not change position. I have a minimal repro below. The same code works on macOS (10.14.6) and Windows (7).

<details>
  <summary>Code Example (click to expand)</summary>

The app below create a frame with a single button called "Move Right". When you press that button, the program attempts to move the frame using SetSize(). On Linux (wxGTK) the frame does not move. On macOS and Windows the frame _does_ move.

```python
import wx

app = wx.App()

frame = wx.Frame(parent=None, title="MyFrame")

def on_move_button_clicked(event):
    old_position = frame.Position
    frame.SetSize(
        old_position.x + 50,
        old_position.y,
        wx.DefaultCoord,
        wx.DefaultCoord,
        wx.SIZE_USE_EXISTING)

move_button = wx.Button(frame, label="Move Right")
move_button.Bind(wx.EVT_BUTTON, on_move_button_clicked)

frame.SetSize(100, 100)
frame.Show()

app.MainLoop()
```
</details>

**Potentially related issues**:

* https://github.com/wxWidgets/Phoenix/issues/2214

**Comment by davidfstr** [comment]
It is also not possible to reposition a wx.Frame using `frame.Position = wx.Point(x, y)` on Linux/wxGTK. Repro by replacing the `on_move_button_clicked` in the Code Example above with:

```python
def on_move_button_clicked(event):
    old_position = frame.Position
    frame.Position = wx.Point(old_position.x + 50, old_position.y)
```

**Comment by davidfstr** [comment]
It is also not possible to reposition a wx.Frame using `frame.Move(x, y)` on Linux/wxGTK. Repro by replacing the `on_move_button_clicked` in the Code Example above with:

```python
def on_move_button_clicked(event):
    old_position = frame.Position
    frame.Move(old_position.x + 50, old_position.y)
```

**Comment by swt2c** [comment]
It seems that it doesn't work when I try it on Wayland, but it works under X11.

e.g., this allows it to work for me:
`GDK_BACKEND=x11 python3 issue_2389.py`

Some quick googling suggests that it isn't possible to move or set the position of top-level windows under Wayland.

**Comment by davidfstr** [comment]
Confirmed. If I replace `import wx` at the front of my program with the workaround:

```
import os
os.environ['GDK_BACKEND'] = 'x11'
import wx
```

then frames can be repositioned using the above-mentioned methods

**Comment by swt2c** [comment]
Good luck with that.  I suspect the developers will tell you that it was a deliberate decision.  :-)

**Comment by davidfstr** [comment]
> Seems like the next step would be to actually file a bug on Wayland.

I'm not going to actually do this, since I'm just going to disable the feature requiring SetSize() on Linux, leaving it available on Windows and macOS.

So I don't plan on taking any further action on this issue myself at this time.

**Comment by swt2c** [comment]
Closing this as there's nothing to be done in wxPython.
