### ISSUE TITLE
Create the wheel for Python 3.11 on Windows

### ISSUE THREAD

**Issue by Ambro86** [wxWidgets/Phoenix#2394]
Hello, thank you for this project that I use often. Having Python 3.11 on Windows 64bit, I tried installing it via pip, however it gives me this error:
ImportError: cannot import name 'Mapping' from 'collections'
Could you make the wheels available for Python 3.11?

**Comment by Ambro86** [comment]
Update. I managed to compile the wheel for Python 3.11, modifying the attrdict module files, replacing the lines where it said import collections in import collections.abc
It told me that the build was successful. But if I try to open a script with Wxpython it gives me this error:
    from ._core import *
ModuleNotFoundError: No module named 'wx._core'
Do you know how to solve?

**Comment by Ambro86** [comment]
Update2. Those who want to solve the problem reported here read the information at this link, where they will also find the unofficial Wheels for Python 3.11
https://stackoverflow.com/questions/74738959/modulenotfounderror-no-module-named-wx-core-when-importing-wx-in-python-3-11

**Comment by swt2c** [comment]
wxPython 4.2.1 is now out with Windows wheels built for Python 3.10 and 3.11. Please try installing 4.2.1.
