### ISSUE TITLE
Cannot find ._core

### ISSUE THREAD

**Issue by moppi79** [wxWidgets/Phoenix#2396]
Debian 11 (X11, KDE )
xPython-4.2.0:          
Stock Python:            

**Description of the problem**:

After Succsefull Install 
pip install -U  -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/debian-11/ wxPython

i have only tryed the "hello World" script. 
but is Crashing on the import from the wx.

```

import wx

#print ('hallo')


# Next, create an application object.
app = wx.App()

# Then a frame.
frm = wx.Frame(None, title="Hello World")

# Show it.
frm.Show()

# Start the event loop.
app.MainLoop()

```

root@moppinote:/net# python3 wetter_desk.py 
Traceback (most recent call last):
  File "/net/wetter_desk.py", line 1, in <module>
    import wx
  File "/usr/local/lib/python3.9/dist-packages/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "/usr/local/lib/python3.9/dist-packages/wx/core.py", line 12, in <module>
    from ._core import *
ImportError: libpcre2-32.so.0: cannot open shared object file: No such file or directory

 i have tried on 2 PC's with the same Debian 11 Distro.

**Comment by swt2c** [comment]
Try `apt install libpcre2-32-0`

**Comment by moppi79** [comment]
Ok Thx. 

i have one sleepless night and a bunch of Self doubt. 
but it was a Simple Solution, Really Thank you :) 
and sorry for circumstances
