### ISSUE TITLE
Unable to pip install wxPython

### ISSUE THREAD

**Issue by Danm926** [wxWidgets/Phoenix#2398]
I am trying to pip install wxPython (see below for versions) I keep getting  the following error.  Please help an old programmer (fortran, basic) learn to use Python/wxPython/WxFormBuilder

C:\Windows\System32>python -V
Python 3.11.3

C:\Windows\System32>pip -V
pip 23.1.2 from C:\Users\danm9\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip (python 3.11)

C:\Windows\System32>pip install wxPython
Collecting wxPython
  Using cached wxPython-4.2.0.tar.gz (71.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "C:\Users\danm9\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\danm9\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\danm9\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\danm9\AppData\Local\Temp\pip-build-env-r1sa4qgt\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\danm9\AppData\Local\Temp\pip-build-env-r1sa4qgt\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\danm9\AppData\Local\Temp\pip-build-env-r1sa4qgt\overlay\Lib\site-packages\setuptools\build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\danm9\AppData\Local\Temp\pip-build-env-r1sa4qgt\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 27, in <module>
        File "C:\Users\danm9\AppData\Local\Temp\pip-install-610h7_vu\wxpython_c2240db09eb9474fa33e3ca32ad98937\buildtools\config.py", line 30, in <module>
          from attrdict import AttrDict
      ModuleNotFoundError: No module named 'attrdict'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by swt2c** [comment]
`pip install attrdict3` first then install wxPython

**Comment by Danm926** [comment]
pip install attrdict3 installed successfully but I got the same error when
I tried pip install wxPython

**Comment by swt2c** [comment]
Please include the entire error message you got after installing attrdict3.

**Comment by Danm926** [comment]
C:\Windows\System32>pip install attrdict3
Requirement already satisfied: attrdict3 in
c:\users\danm9\appdata\local\programs\python\python311\lib\site-packages
(2.0.2)
Requirement already satisfied: six in
c:\users\danm9\appdata\local\programs\python\python311\lib\site-packages
(from attrdict3) (1.16.0)

C:\Windows\System32>pip install wxPython
Collecting wxPython
  Using cached wxPython-4.2.0.tar.gz (71.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File
"C:\Users\danm9\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py",
line 353, in <module>
          main()
        File
"C:\Users\danm9\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py",
line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File
"C:\Users\danm9\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py",
line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File
"C:\Users\danm9\AppData\Local\Temp\pip-build-env-zg78qssp\overlay\Lib\site-packages\setuptools\build_meta.py",
line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings,
requirements=['wheel'])

 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File
"C:\Users\danm9\AppData\Local\Temp\pip-build-env-zg78qssp\overlay\Lib\site-packages\setuptools\build_meta.py",
line 323, in _get_build_requires
          self.run_setup()
        File
"C:\Users\danm9\AppData\Local\Temp\pip-build-env-zg78qssp\overlay\Lib\site-packages\setuptools\build_meta.py",
line 488, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File
"C:\Users\danm9\AppData\Local\Temp\pip-build-env-zg78qssp\overlay\Lib\site-packages\setuptools\build_meta.py",
line 338, in run_setup
          exec(code, locals())
        File "<string>", line 27, in <module>
        File
"C:\Users\danm9\AppData\Local\Temp\pip-install-bi6unm69\wxpython_faa359c4d0ce4887ae06d1ccbb992ee4\buildtools\config.py",
line 30, in <module>
          from attrdict import AttrDict
      ModuleNotFoundError: No module named 'attrdict'
      [end of output]

  note: This error originates from a subprocess, and is likely not a
problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem
with pip.

**Comment by swt2c** [comment]
I don't know why you're still seeing the attrdict3 error, but wxPython 4.2.0 isn't going to work with Python 3.11 anyway.  I'd suggest using an older Python version, or you can use one of the wheels that are being built by the CI service:
https://alldunn.visualstudio.com/wxPython-CI/_build/results?buildId=1101&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by Danm926** [comment]
Ok, thanks.

**Comment by swt2c** [comment]
wxPython 4.2.1 is now out with Windows wheels built for Python 3.10 and 3.11. Please try installing 4.2.1.
