### ISSUE TITLE
can't install wxpython

### ISSUE THREAD

**Issue by Trigon2** [wxWidgets/Phoenix#2400]
**Operating system**: Windows 11
**wxPython version & source**:            wxPython-4.2.0. 
**Python version & source**:            pip-23.0.1 

**Description of the problem**: while installing wxpython using command prompt I gives me error as following

# Put code sample here
```
Collecting wxPython
  Using cached wxPython-4.2.0.tar.gz (71.0 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Hp\AppData\Local\Temp\pip-install-unwif7tk\wxpython_35dfb496cbe6407ebe7a134637921cb2\setup.py", line 27, in <module>
          from buildtools.config import Config, msg, opj, runcmd, canGetSOName, getSOName
        File "C:\Users\Hp\AppData\Local\Temp\pip-install-unwif7tk\wxpython_35dfb496cbe6407ebe7a134637921cb2\buildtools\config.py", line 30, in <module>
          from attrdict import AttrDict
        File "C:\Users\Hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\attrdict\__init__.py", line 5, in <module>
          from attrdict.mapping import AttrMap
        File "C:\Users\Hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\attrdict\mapping.py", line 4, in <module>
          from collections import Mapping
      ImportError: cannot import name 'Mapping' from 'collections' (C:\Users\Hp\AppData\Local\Programs\Python\Python311\Lib\collections\__init__.py)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.





</details>

**Comment by Wolf-SO** [comment]
What is your Python version?

**Comment by kevinlindstrom** [comment]
I just had the same issue, and it appears to be an issue introduced after python3.9. 

I simply reverted to version 3.9 and was able to install.

However, if you must have a newer python version, this [stackoverflow](https://stackoverflow.com/questions/69381312/in-vs-code-importerror-cannot-import-name-mapping-from-collections) thread has useful information for how to fix this from an import error in your own code: . Obviously, this package isn't your own, but you could potentially download the source code and try to modify the install process if you absolutely need this and a newer version.

Good luck, hope this helps.

**Comment by swt2c** [comment]
wxPython 4.2.1 is now out with Windows wheels built for Python 3.10 and 3.11.  Please try installing 4.2.1.

**Comment by Wolf-SO** [comment]
> wxPython 4.2.1 is now out with Windows wheels built for Python 3.10 and 3.11. Please try installing 4.2.1.

I can confirm that it works as expected in Win10, Python 3.11.2. 
(Pip also automatically uninstalled the unofficial local 4.2.1a1 wheel I used before.)
