### ISSUE TITLE
4.2 & 4.1.1 wxPython won't install but 4.1.0 worked --- USING PYTHON 2.7

### ISSUE THREAD

**Issue by codylt16** [wxWidgets/Phoenix#2402]
**Operating system**: Win11
**wxPython version & source**:   4.2 & 4.1.1       
**Python version & source**:   Python 2.7 with Pycharm         

**Description of the problem**:
attempting to "pip install wxpython" & "pip install wxpython==4.1.1" getting the same error. was able to install 4.1.0 "pip install wxpython==4.1.0".

It could be as simple as Python2.7 not supported which is fine, but i did not see that on any websites or python forums.

<details>
  <summary>Code Example (click to expand)</summary>
Here is me attempting to run a pip and the same error i got for both "pip install wxpython" & "pip install wxpython==4.1.1"

PS C:\Users\fake_directory\PyCharmProjects> pip install -U wxPython    
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting wxPython
  Using cached wxPython-4.2.0.tar.gz (71.0 MB)
Requirement already satisfied, skipping upgrade: pillow in c:\python27\lib\site-packages (from wxPython) (6.2.2)
Requirement already satisfied, skipping upgrade: six in c:\python27\lib\site-packages (from wxPython) (1.16.0)
Requirement already satisfied, skipping upgrade: numpy<1.17 in c:\python27\lib\site-packages (from wxPython) (1.16.6)
Building wheels for collected packages: wxPython
  Building wheel for wxPython (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\python27\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'c:\\users\\FakeName~1\\appdata\\local\\temp\\pip-install-8q1wjt\\wxpython\\setup.py'"'"'; __file__='"'"'c:\\users\\FakeName~1\\appdata\\local\\temp\\pip-install-8q1wjt\\wxpython\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'c:\users\FakeName~1\appdata\local\temp\pip-wheel-qaswuf'
       cwd: c:\users\FakeName~1\appdata\local\temp\pip-install-8q1wjt\wxpython\
  Complete output (14 lines):
  running bdist_wheel
  running build
  WARNING: Building this way assumes that all generated files have been
  generated already.  If that is not the case then use build.py directly
  to generate the source and perform the build stage.  You can use
  --skip-build with the bdist_* or install commands to avoid this
  message and the wxWidgets and Phoenix build steps in the future.

  "c:\python27\python.exe" -u build.py build
    File "build.py", line 805
      msg(f"CL.exe: {CL}")
                        ^
  SyntaxError: invalid syntax
  Command '"c:\python27\python.exe" -u build.py build' failed with exit code 1.
  ----------------------------------------
  ERROR: Failed building wheel for wxPython
  Running setup.py clean for wxPython
Failed to build wxPython
Installing collected packages: wxPython
    Running setup.py install for wxPython ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\python27\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'c:\\users\\FakeName~1\\appdata\\local\\temp\\pip-install-8q1wjt\\wxpython\\setup.py'"'"'; __file__='"'"'c:\\users\\FakeName~1\\appdata\\local\\temp\\pip-install-8q1wjt\\wxpython\\setup.py'"'"';f=getattr(tokenize, '"'"
'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'c:\users\FakeName~1\appdata\local\temp\pip-record-mwktgi\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\python27\Include\wxPython'
         cwd: c:\users\FakeName~1\appdata\local\temp\pip-install-8q1wjt\wxpython\
    Complete output (14 lines):
    running install
    running build
    WARNING: Building this way assumes that all generated files have been
    generated already.  If that is not the case then use build.py directly
    to generate the source and perform the build stage.  You can use
    --skip-build with the bdist_* or install commands to avoid this
    message and the wxWidgets and Phoenix build steps in the future.

    "c:\python27\python.exe" -u build.py build
      File "build.py", line 805
        msg(f"CL.exe: {CL}")
                          ^
    SyntaxError: invalid syntax
    Command '"c:\python27\python.exe" -u build.py build' failed with exit code 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\python27\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'c:\\users\\FakeName~1\\appdata\\local\\temp\\pip-install-8q1wjt\\wxpython\\setup.py'"'"'; __file__='"'"'c:\\users\\FakeName~1\\appdata\\local\\temp\\pip-install-8q1wjt\\wxpython\\setup
.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'c:\users\FakeName~1\appdata\local\temp\pip-record-mwktgi\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\python27\Include\wxPython' Check the logs for full command output.
PS C:\Users\fake_directory\PyCharmProjects> 

```python
# Put code sample here
```
</details>

**Comment by swt2c** [comment]
Python 2 is no longer supported.
