### ISSUE TITLE
On windows 11 only  could not convert frame to dialog

### ISSUE THREAD

**Issue by dcalleba** [wxWidgets/Phoenix#2423]
**windows11**:
**wxPython 4.2.1**:          
**Python version 3.9 *:            

**Description of the problem**:

<details>
  Traceback (most recent call last):
  File "c:\pyt39\bdj1.py", line 14158, in <module>
    frame.Show()
TypeError: could not convert 'MyFrame' to 'Dialog'

```python
class MyFrame(wx.Frame, Taxi, LoginDialog):
...
...
 frame = MyFrame()
    frame.Show()
```
</details>

**Comment by infinity77** [comment]
@swt2c : not sure there's much details here to go on. The code is non-existent, might as well close it.
