### ISSUE TITLE
Add full support to DataViewCheckIconTextRenderer

### ISSUE THREAD

**Issue by konstantinbo** [wxWidgets/Phoenix#2424]
**Operating system**: Windows 10
**wxPython version & source**:          4.2.1

**Python version & source**:            Python 3.10.11

**Description of the problem**: 
DataViewCheckIconTextRenderer is [documented ](https://docs.wxpython.org/wx.dataview.DataViewCheckIconTextRenderer.html) but doesn't work. In particular there is even an error during instantiation:
`TypeError: wx._dataview.DataViewCheckIconTextRenderer represents a C++ abstract class and cannot be instantiated`. 
Furthermore the corresponding `DataViewCheckIconText` class is completely missing.

<details>
  <summary>Code Example (click to expand)</summary>

```python
import wx
import wx.dataview as dv

class SampleFrame(wx.Frame):
    def __init__(self, *args, **kw):
        super(SampleFrame, self).__init__(*args, **kw)

        pnl = wx.Panel(self)

        self.dvlc = dv.DataViewListCtrl(pnl)
        self.dvlc.AppendTextColumn('foo', width=40)

        dvcit = dv.DataViewCheckIconText("bar", wx.NullBitmap, wx.CHK_CHECKED)  # raises AttributeError

        checkIconTextCol = dv.DataViewColumn(
            title='bar',
            renderer=dv.DataViewCheckIconTextRenderer(),  # raises TypeError
            model_column=1,
            width=wx.COL_WIDTH_AUTOSIZE,
        )
        self.dvlc.AppendColumn(checkIconTextCol)

        self.dvlc.AppendItem(["foo", dvcit])

        sizer = wx.BoxSizer(wx.VERTICAL)
        sizer.Add(self.dvlc, 1, wx.EXPAND)
        pnl.SetSizer(sizer)

app = wx.App()
frame = SampleFrame(None, title="Demo")
frame.Show()
app.MainLoop()
```
</details>

This requires another pull request contained in wxWidgets to work: [Issue 23668](https://github.com/wxWidgets/wxWidgets/issues/23668)

**Comment by konstantinbo** [comment]
Thanks for the quick merge!
I just noticed additionally that the documentation is currently missing for this "new" feature ([wx.dataview](https://docs.wxpython.org/wx.dataview.1moduleindex.html)).
Should I open another issue for this?

**Comment by swt2c** [comment]
> Thanks for the quick merge! I just noticed additionally that the documentation is currently missing for this "new" feature ([wx.dataview](https://docs.wxpython.org/wx.dataview.1moduleindex.html)). Should I open another issue for this?

Probably not needed.  It appears to the documentation gets updated when there is a new release.  I believe the updates should appear automatically due to the changes you made to the wxWidgets interface headers.

In fact, if you want to check the snapshot builds of the documentation to make sure it is there, that would be helpful:
https://wxpython.org/Phoenix/snapshot-builds/
