### ISSUE TITLE
wxp.3.0.3 AUI panes do not resize

### ISSUE THREAD

**Issue by psionprime** [wxWidgets/Phoenix#243]
I thought I had just messed up a style bit but the sample from:

https://wxpython.org/Phoenix/docs/html/wx.lib.agw.aui.html

does not allow the panes to move either.

I'm happy to dig into it on my own if someone can point me in the right direction please.

I've been developing many apps with the library with great success but apparently never tried to move the panes before now.

Thanks for your efforts !

**Comment by stevenj** [comment]
I had this problem as well.  Look at the code to AUI_DockingWindowMgr.py in the demo suite.  Its resizing works. (Although it gives no feedback until you stop dragging.)  The difference is:

import wx.aui as aui
instead of:
import wx.lib.agw.aui as aui

try that.

Also, if you want resizing to give some active feedback try this:
self._mgr.SetFlags(self._mgr.GetFlags() ^ aui.AUI_MGR_LIVE_RESIZE)

**Comment by acollange** [comment]
Are you using GTK ?
Because I have found something strange in the Update() method of AuiManager (agw version).

`    def Update(self):
        if '__WXGTK__' in wx.PlatformInfo:
            self.Bind(wx.EVT_WINDOW_CREATE, self.DoUpdateEvt)
        else:
            self.DoUpdate()

    def DoUpdateEvt(self, evt):
        wx.CallAfter(self.DoUpdate)`

The GTK code branch is useless.
Calling DoUpdate() instead of Update() should fix your problem.

Is somebody able to tell us what is the purpose of this Bind event here ?

**Comment by psionprime** [comment]
I am using GTK (Linux Mint 18.1) I think this should remain open as the tips indicate a work-around. I am curious to the thinking of the maintainers if the tips actually are the proper method and the example needs updated or it is something else.... just the nomenclature awg vs aui and Update vs DoUpdate is ambiguous.

Text and my ability to render it sucks so please don't take what I pointed out as negative. I, for one, very much appreciate the Phoenix team and others' efforts.

Thanks for the tips !

**Comment by RobinD42** [comment]
> Is somebody able to tell us what is the purpose of this Bind event here ?

I'm not sure about that case, but typically that is done when you need to modify the window immediately after it has been created, but on X-Windows the UI part of the widget is not created immediately so some things can't be done yet. The UI part of the widget is not actually created until the current commands are flushed to the X Server and it responds back that it was successful. That is when `EVT_WINDOW_CREATE` is sent. (IIRC, the X terminology is that the widget has been "mapped".)

In that particular case however I agree that it seems incorrect. Although AuiManager is not a Window, it will be pushed onto the managed window's event handler stack with `PushEventHandler` so it is possible that Update will be called for the first time before the UI portion of that window is created, but that won't be true for subsequent calls so there should be something in there to check for that case and do the right thing.

If you can work out the details a PR would be appreciated. We may also want to check with @infinity77 and @wernerfb to see if one of them remembers why it is this way.

**Comment by acollange** [comment]
> The GTK code branch is useless.

It seems that my assertion was bad ;-)
Thanks Robin to remind us how non trivial the X-Windows mechanic can be !
I have opened the PR #270 for this issue.

**Comment by RobinD42** [comment]
Is this resolved in current builds with #270 applied?

**Comment by acollange** [comment]
No. This change has a bad side-effect. See issue #317.

**Comment by acollange** [comment]
Done a new PR (#351) about this issue for GTK port.

**Comment by mesalu** [comment]
Associated PR merged. Closing.
