### ISSUE TITLE
'str' to 'wxString' converstation is broken, when emoji is inside string

### ISSUE THREAD

**Issue by timrid** [wxWidgets/Phoenix#2446]
**Operating system**: Windows 10
**wxPython version & source**: wxPython 4.2.1 from pypi
**Python version & source**: Python 3.11

**Description of the problem**:
Whem some special emojis like 🔄 are inside a python string, that is converted to an wxString (internally in wxPython), the last character of the string is lost. It is also not shown in the gui.

The changes in https://github.com/wxWidgets/Phoenix/commit/29520a122a5a7c34cbd9951102562297a6b5afb5 creates the problem. I compiled it with and without the changes and only with the changes the error occures. I guess that `PyUnicode_GET_LENGTH` is not an 1:1 replacement for `PyUnicode_GET_SIZE`.

I created the following small example to illustrate the problem.

```python
import wx

app = wx.App(False)
txt = wx.Button()

def test_string(input):
    txt.SetLabel(input)
    output = txt.GetLabel()
    print(f"{input=}, {output=}")

test_string("asdf")  # Output is: "asdf" -> ok
test_string("⟳ asdf")  # Output is: "⟳ asdf" -> ok
test_string("🔄 asdf")  # Output is: "🔄 asd" -> error: last char is missing
test_string("🔄🔄 asdf")  # Output is: "🔄🔄 as" -> error: last two chars are missing
test_string("🔄")  # Output is: "\ud83d" -> error
```

**Comment by timrid** [comment]
I am not quiet sure why, but with the following additional change `PyUnicode_GET_LENGTH` works.
```python
wxPyUnicode_AsWideChar(item, wxStringBuffer(string, len+1), len+1);
```
I can create an PR, but I am not sure if it works with every os and every python version.

**Comment by swt2c** [comment]
Thanks @timrid for the bug report and analysis.  I had feared that `PyUnicode_GET_LENGTH` was not an 1:1 replacement for `PyUnicode_GET_SIZE`.  Unfortunately, the documentation/examples for the Python C APIs is not very extensive.

I'll try to take a look.

**Comment by timrid** [comment]
I also looked at the Python C API. The docs are not so useful. But when i looked in the cpython code i saw [this comment](https://github.com/python/cpython/blob/d7a788332666eabade922bf5d976df8c362ecb14/Objects/unicodeobject.c#L2904C1-L2916C2) for `PyUnicode_AsWideChar`. 

```c
/* Convert a Unicode object to a wide character string.

   - If w is NULL: return the number of wide characters (including the null
     character) required to convert the unicode object. Ignore size argument.

   - Otherwise: return the number of wide characters (excluding the null
     character) written into w. Write at most size wide characters (including
     the null character). */
Py_ssize_t
PyUnicode_AsWideChar(PyObject *unicode,
                     wchar_t *w,
                     Py_ssize_t size)
{
    ...
``` 

So i guess that

```c
size_t len = PyUnicode_GET_SIZE(uni);
```

can be replaced with 

```c
size_t len = PyUnicode_AsWideChar(uni, NULL, 0);
```
