### ISSUE TITLE
wxpython.org is down

### ISSUE THREAD

**Issue by demmerichs** [wxWidgets/Phoenix#2474]
Your website is currently down!
See also here https://www.saashub.com/wxpython-status

**Comment by jmoraleda** [comment]
I confirm that. It has been down since at least yesterday.

**Comment by noeldiviney** [comment]
I also confirm. I get timeouts here in Melbourne Australia. I can ping the ip address sucessfully, however.
Noel

**Comment by reticulatus** [comment]
It's working for me now.

**Comment by jmoraleda** [comment]
Confirmed. It is working for me too. I think we can close this issue.

**Comment by badabing2005** [comment]
This an issue again
