### ISSUE TITLE
Snapshot builds only creating osx builds

### ISSUE THREAD

**Issue by seanbudd** [wxWidgets/Phoenix#2489]
It appears that the snapshots page is only building OSX builds now, with the last Windows build in August.
https://wxpython.org/Phoenix/snapshot-builds/?C=M;O=D

[NVDA](https://github.com/nvaccess/nvda) would love a snapshot build which includes this commit 0dcd0640ca0e773c709a55262da6f3874540a317

e.g. `wxPython-4.2.2a1.devXXX+XXX-cp311-cp311-win32.whl`

**Comment by komoto48g** [comment]
I don't think a "snapshot build" is necessarily the latest. But you can get the wheel from Azure: https://alldunn.visualstudio.com/wxPython-CI/_build/results?buildId=1203&view=results

See also related discussion: https://discuss.wxpython.org/t/wheel-file-request/36499

**Comment by seanbudd** [comment]
Thanks - this link is helpful

**Comment by Metallicow** [comment]
![lastbuild](https://github.com/wxWidgets/Phoenix/assets/4668356/c20f9c9d-863f-47ca-b447-e71ce019d039)


8-31-2023
August 31st, 2023

last build on snapshot for MSW

**Comment by RobinD42** [comment]
This issue has been mentioned on **Discuss wxPython**. There might be relevant details there:

https://discuss.wxpython.org/t/where-are-dev-builds-for-windows-and-linux/36789/5

**Comment by swt2c** [comment]
Snapshot builds for Windows have been fixed.
