### ISSUE TITLE
Possible documentation problem with wx.Image.AddHandler

### ISSUE THREAD

**Issue by N46AN** [wxWidgets/Phoenix#250]
**Basic Info:**
wxver - wxPython_Phoenix-3.0.3.dev2812+b3485d4-cp35-cp35m-linux_x86_64
pyver - Python 3.5.3 (default, Jan 19 2017, 14:11:04) [GCC 6.3.0 20170118] on linux
uname - Linux debian 4.9.0-2-amd64 #1 SMP Debian 4.9.13-1 (2017-02-27) x86_64 GNU/Linux
os-release - Debian GNU/Linux 9 (stretch)

**Step to reproduce:**
Follow the sample usage as documented in https://wxpython.org/Phoenix/docs/html/wx.Image.html#wx.Image.AddHandler
```
wx.Image.AddHandler(wx.PNGHandler)
```

**Expected Result**
PNGHandler should be loaded.

**Actual Result**
AttributeError: module 'wx' has no attribute 'PNGHandler'

----------------------------

Note that in https://wxpython.org/Phoenix/docs/html/wx.Image.html#wx.Image.AddHandler the link ' Available image handlers' is not pointing to the actual documentation page.

**Comment by N46AN** [comment]
Well, I see that the image format handlers are marked as MISSING in https://wxpython.org/Phoenix/docs/html/classic_vs_phoenix.html?highlight=pnghandler
So where can I find some further imfomation about how to use a specific type of wx.ImageHandler?

**Comment by RobinD42** [comment]
All the built-in image handlers are already added during wxPython's core module initialization (in the C code), so there isn't any need for you to call `AddHandler` for those yourself.  That said, they probably should still be included like in Classic, so I'll look into that.

**Comment by mesalu** [comment]
Fixed by #411.
