### ISSUE TITLE
Virtual ListCtrl does not reliably render more than about 364k rows

### ISSUE THREAD

**Issue by CypherGrue** [wxWidgets/Phoenix#2522]
**Operating system**: Ubuntu 23.10
**wxPython version & source**: 4.2.1 (distro python3-wxgtk4.0 4.2.1+dfsg-1)
**Python version & source**: 3.11.6 (distro python3 3.11.4-5)

**Description of the problem**:

Virtual ListCtrl does not reliably render more than about 364k rows

```
import wx

class ListCtrl(wx.ListCtrl):
    def __init__(self, parent, ident, style):
        wx.ListCtrl.__init__(self, parent, ident, style=style)
        self.InsertColumn(0, 'Column', width=550)

    def OnGetItemText(self, i, col):
        return str(int(i))

class Frame(wx.Frame):
  
    def __init__(self, *args, **kwargs):
        super(Frame, self).__init__(*args, **kwargs)
        self.coinlist = ListCtrl(self, wx.ID_ANY, wx.LC_REPORT|wx.LC_VIRTUAL)
        self.coinlist.SetItemCount(400*1000)
        self.Show()

if __name__ == '__main__':
    app = wx.App()
    Frame(None, -1, 'Window', size=(600,300))
    app.MainLoop()
```
![Screenshot from 2024-01-30 14-06-31](https://github.com/wxWidgets/Phoenix/assets/5720904/3ed50f27-0102-4a66-a745-9a3842e7d0fd)
![Screenshot from 2024-01-30 14-03-57](https://github.com/wxWidgets/Phoenix/assets/5720904/477e7ad1-e1fe-41a3-a09e-b7484710e8a5)
![Screenshot from 2024-01-30 14-16-28](https://github.com/wxWidgets/Phoenix/assets/5720904/792cde2e-1aee-470c-b699-4591d238ebfa)

**Comment by reticulatus** [comment]
I tested your code using Python 3.10.12 + wxPython 4.2.1 gtk3 (phoenix) wxWidgets 3.2.2.1 on Linux Mint 21.3 and it worked fine, even when I increased the item count.

![Screenshot at 2024-01-30 15-12-43](https://github.com/wxWidgets/Phoenix/assets/6072789/78ff9e02-90a4-467b-b626-fe842ba62fda)

The main differences between our setups is that I am using Python 3.10 and you are using 3.11, plus I installed wxPython 4.2.1 using pip, whereas you are using the version from your distribution.

**Comment by reticulatus** [comment]
What version of GTK3 do you have?

```
richardt@Pavilion:~ $ dpkg -l  libgtk-3-0
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name             Version          Architecture Description
+++-================-================-============-====================================
ii  libgtk-3-0:amd64 3.24.33-1ubuntu2 amd64        GTK graphical user interface library
```

**Comment by CypherGrue** [comment]
```
$ dpkg -l  libgtk-3-0
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name             Version          Architecture Description
+++-================-================-============-====================================
ii  libgtk-3-0:amd64 3.24.38-5ubuntu1 amd64        GTK graphical user interface library
ii  libgtk-3-0:i386  3.24.38-5ubuntu1 i386         GTK graphical user interface library
```

**Comment by CypherGrue** [comment]
Tried downgrading
libgtk-3-0 to 3.24.33-1ubuntu2,
libgtk-3-0-dev to 3.24.33-1ubuntu1,
then rebuilt and ran, issue still present.

Have tried gnome, cinnamon desktop envs with xorg and not.

Have noticed that just at the position where rows begin disappearing, if I shrink the window vertically it causes the rows to reappear. But this does not work further down.

**Comment by CypherGrue** [comment]
Tested that my overlay scrollbar setting is not causing this.

I took ubuntu VM images from linuxvmimages.com (not affiliated nor recommended), then saved wxtest.cpp to the Desktop and ran:

```
sudo apt install libwxgtk3.2-dev
g++ -o wxtest wxtest.cpp `wx-config --cxxflags --libs`  && ./wxtest
```

On 23.10, issue is present
On 23.04, issue is absent

**Comment by CypherGrue** [comment]
Downgrading every package in the dependency tree, the culprit appears to be libcairo2

libcairo2_1.18.0-1_amd64.deb: issue is present
libcairo2_1.16.0-7_amd64.deb: issue is absent

**Comment by CypherGrue** [comment]
cairo 1.17.4 good
cairo 1.17.6 good
cairo 1.17.8 bad
cairo 1.18.0 bad

**Comment by CypherGrue** [comment]
cairo 5dafd741 good
cairo 9fbf8f48 good
cairo 47a21c6e bad FAULT Clamp path coordinates
cairo 451dcd31 bad
cairo ccb306b8 bad
cairo 91364546 bad
cairo ff08edfc bad
cairo 4913f079 bad
cairo aeafbf55 bad

**Comment by CypherGrue** [comment]
I don't know much about guis, but it looks like cairo change 451dcd31 clamps double values to fixed point values, but the 32-bit fixed point type uses 8 bits for the fractional part, leaving 24 bits for pixels. Dividing the pixels by the number of rows in my list yields 2^24/364000=46.09 pixels per row. And I have 46/2=23 pixels per row on my screen, I guess half the range being used for negative numbers. Observation seems to confirm the bisection, my list is being clamped by this change.

**Comment by swt2c** [comment]
Really nice work @CypherGrue in troubleshooting the issue.  Unfortunately, I don't think we can do much to help in wxPython, but I'd suggest bringing your issue upstream to the cairo devs.

**Comment by CypherGrue** [comment]
Thanks.

Raised https://gitlab.freedesktop.org/cairo/cairo/-/issues/824

**Comment by CypherGrue** [comment]
This boomerang back down. Cairo dev suggests that the issue is that the library is not being used correctly.
https://gitlab.freedesktop.org/cairo/cairo/-/issues/824#note_2264420

Maybe the wx virtual window is too big or something, or an issue in gtk? I am going to drop this here, as no more time. Good luck.
