### ISSUE TITLE
Snapshot build(s) have stopped building

### ISSUE THREAD

**Issue by Metallicow** [wxWidgets/Phoenix#2530]
**Description of the problem**:

It appears that some of the OS builds broke on

https://wxpython.org/Phoenix/snapshot-builds/

The last visible version I got is wxPython 4.2.2a1.dev5626+a1184286 msw (phoenix) wxWidgets 3.2.3 Scintilla 3.7.2
which is 2023-08-31 for windows.

... This happens from time to time for some odd reason. I guessing they need to be triggered manually to start again or somesuch...

**Comment by decodeais** [comment]
I wanted to test the result of my pull request #2528 but I did not succeed to compile the wheel. When I looked for a Linux wheel in the repository I found an empty folder.

**Comment by Metallicow** [comment]
I'm not sure if @RobinD42 is the only one that can trigger the builds. I recall at one point it was setup to build at least once a day if any commits had went thru. It appears the automated buildbot choked on something on the microsoft windows builds and has stopped. This has happened before. It appears the mac builds are still building. Eventually the other builds disappear from the page when this happens after a certain amount of time or commits builds.(probably end up in a garbage bin at that point, idunno)
It would be nice to see some py3.12 builds also if that work has been done rather than having to manually build/patch pyfiles. It is so much easier to just download the latest installer/snapshot buildand stick it on a thumbdrive to transfer between machines if you have one online and others offline. I guess at this point we have to wait for a reply/fix from Robin unless someone else has the keys to the vault.

**Comment by decodeais** [comment]
My Trouble is not so big because I succeeded to build the python3.11 wheel for Linux 10 ours ago after hundred circles of try and error . The problem now is to find a place where to save the file for all the others of our project. The wxPython would be the best place. We need a wheel for Raspbian to.There is the problem that the compiler needs morethan 5h on this device.

**Comment by Metallicow** [comment]
... Sorry not this time. My personal rasp pi builds are hosted eslewhere cause of this on slow pi. This was not a rasp pi build. Also I had to cut the download in half because of github upload reqz... hopefully that has changed upwards. I don't sadfully have a Rasp pi 5 yet :(, but yes I do hear ya as far as trying to build an image. It should be much better now, tho you might want to build it off shore on another OS... hahaha 11 hours.... was the best for me. I'd like to hear from the new rasp pi 5 users lol.

... Also just because I hosted a older image before wxPasbPi doesn't mean I am going to host a build farm for it ....

... Hopefully Robins build-bot isn't that slow ...

**Comment by decodeais** [comment]
I have still problems compiling the wheel with the 4.2.2 version. It is for cycle trainer project with a lot of users. It would not be good to break the installation for the future. Now I am working with a patched 4.2.1. 
I have seen that it is possible to change the python within the wheel as a workaround. 
The generation with 4.2.1 works, but 4.2.2 seems to be broken.
Excuse my poor english an week knowledge of Python, but it's a nice training for me. 
If you have an idea what's going wrong, please tell me. I am only a user who want's to help the guy who developed the software.

**Comment by RobinD42** [comment]
This issue has been mentioned on **Discuss wxPython**. There might be relevant details there:

https://discuss.wxpython.org/t/where-are-dev-builds-for-windows-and-linux/36789/5

**Comment by decodeais** [comment]
May be this will help somebody who is searching.
It is  really possible make a own snapshot build. It took a while but I build wheels for Python3.10 /11 with this script  https://github.com/wxWidgets/Phoenix/issues/2534#issuecomment-1967240640  and it worked for Linux Mint and Raspbian.

**Comment by swt2c** [comment]
Snapshot builds have been fixed:
https://wxpython.org/Phoenix/snapshot-builds/
