### ISSUE TITLE
Importing wx.media on Windows

### ISSUE THREAD

**Issue by ErikKoinberg** [wxWidgets/Phoenix#2531]
I am trying to use wx.media after having used pip install, but the wx.media module is not present. How to import that as well on Windows?

I am using an current version of Windows 10, 64 bit, python 3.12 64-bit. I am using the latest version of wxPython 4 installed using pip install wxpython.

**Comment by swt2c** [comment]
You left out a lot of important details:
- What version of wxPython?
- What version of Python?
- 32-bit or 64-bit?
- Did you build wxPython yourself?  Presumbably you did because the wheels on PyPI appear to have the wx.media module.

**Comment by ErikKoinberg** [comment]
I added a bit more details.

**Comment by swt2c** [comment]
Please also report what you tried and any error messages that you observed.

**Comment by DietmarSchwertberger** [comment]
I think I have installed my wx 4.2.1 for Python 3.12 64 bit from pip and I see the media module:

 - D:\Python\Python312-64_wx421\Lib\site-packages\wx\media.py
 - D:\Python\Python312-64_wx421\Lib\site-packages\wx\_media.cp312-win_amd64.pyd
 - D:\Python\Python312-64_wx421\Lib\site-packages\wx\wxmsw32u_media_vc140_x64.dll

**Comment by DietmarSchwertberger** [comment]
I would suggest to close the isssue. It's not reproducible and the reporter seems to have lost interest.
