### ISSUE TITLE
BusyCursor docs are outdated

### ISSUE THREAD

**Issue by KazzyJr** [wxWidgets/Phoenix#2535]
**wxPython version & source**:          4.2.1, pypi

**Description of the problem**: wx.BusyCursor docs should detail the context manager case, which the cursor is actually meant to be used like.

<details>
  <summary>Code Example (click to expand)</summary>

```python
with wx.BusyCursor():
    for i in range(50000):
        DoACalculation()
```
</details>

**Comment by DietmarSchwertberger** [comment]
I will also add a PR for wxWidgets to extend "see also..." with a hint to wx.BusyInfo.
