### ISSUE TITLE
Recent sip related change to build.py breaks building from source on GTK

### ISSUE THREAD

**Issue by jmoraleda** [wxWidgets/Phoenix#2538]
Typically I build from source in GTK using
```
python build.py dox etg --nodoc sip build
```
but that command now fails with 

```
Running command: sip
sip-build --no-compile
sip-build: pyproject.toml: the '[tool.sip.metadata]' section is missing
Command 'sip-build --no-compile' failed with exit code 1.
```
@swt2c Perhaps this is due by the recent change in `build.py` of the form `[tool.sip.metadata]` -> `[project]`?

What is the correct way to build now? Thank you.

**Comment by swt2c** [comment]
That should be fine building that way.  Are you building with the latest version of sip?

**Comment by jmoraleda** [comment]
Thank you for your super prompt response @swt2c I really appreciate it.

 I was using 6.7.7, (which is the default in debian stable), but I just installed 6.8.3, (which is in debian sid)  and it indeed works fine.
