### ISSUE TITLE
"python setup.py bdist_wheel" Error while installing wxPython 

### ISSUE THREAD

**Issue by Mr-MVP** [wxWidgets/Phoenix#2544]
**Operating system**: Windows 11
**wxPython version & source**: 4.2.1(latest)    
**Python version & source**: 3.10.12(latest)           

**Description of the problem**:

I am trying to install wxPython in google colab. But it throws an error. Ive researched about it and tried installing attrdict and attrdict3 as well but to no avail. Can anybody please help me setup it. I just want to create and test some new IDs using wxPython 

![Screenshot 2024-04-02 040506](https://github.com/wxWidgets/Phoenix/assets/143615627/bc3df072-2827-4fc8-ae44-82b8dc399681)

**Comment by swt2c** [comment]
This is strange, because there should be wheels available for Windows and Python 3.10.  This isn't an ARM architecture machine is it?

**Comment by swt2c** [comment]
Closing due to lack of follow-up.
