### ISSUE TITLE
AttributeError: module 'wx.html2' has no attribute 'New'

### ISSUE THREAD

**Issue by Shadowbyte-Syndicate** [wxWidgets/Phoenix#2548]
**Operating system**:
**wxPython version & source**:          
**Python version & source**:            

**Description of the problem**:

<details>
  <summary>Code Example (click to expand)</summary>

```python
# Put code sample here
```
</details>

**Comment by reticulatus** [comment]
The wxPython documentation clearly shows that wx.html2 is a module that provides a number of classes. It is not intended to have a `New` attribute:

https://docs.wxpython.org/wx.html2.1moduleindex.html

The main class that is used to build an application is `wx.html2.WebView` and that class does have a `New()` method:

https://docs.wxpython.org/wx.html2.WebView.html#wx.html2.WebView.New

See the wxPython Demo for an example of how to use the wx.html2 module.
