### ISSUE TITLE
EditLabel on CustomTreeCtrl doesn't automatically select the entire text

### ISSUE THREAD

**Issue by AlessandroMattiazzi** [wxWidgets/Phoenix#2549]
Python 3.10.6 32bit   windows 10

when renaming an item on TreeCtrl with the function EditLabel the entire text is automatically selected,
instead on CustomTreeCtrl when using the same function the cursor is automatically located at the start of the text and no selection is done

https://github.com/wxWidgets/Phoenix/assets/93250143/f38e3beb-e45f-4d39-a47e-5ec8e4f5a43d

**Comment by infinity77** [comment]
@swt2c  I am having issues in creating PRs - I have no clue on how to switch from my work-related enterprise account to my personal one.

That said, this is easily fixable at line 1,430 of wx.lib.customtreectrl.py, by adding this:

```python
        if self._startValue:
            self.SelectAll()
```

**Comment by AlessandroMattiazzi** [comment]
Thanks it works perfectly for me
