### ISSUE TITLE
wx.Bitmap() cannot find image error

### ISSUE THREAD

**Issue by wxmurph** [wxWidgets/Phoenix#2556]
**Operating system**: Windows 11
**wxPython version & source**:   wxPython version 4.2.1 msw (phoenix) wxWidgets 3.2.2.1 pypi       
**Python version & source**:   Python 3.11.4 pypi         

**Description of the problem**: Cannot find bmp file, compiled programs are working fine, but the source files for the working programs give error: 07:41:13: can't open file 'Photo.bmp' (error 2: The system cannot find the file specified.)
07:41:13: Failed to load image from file "Photo.bmp".
07:41:13: can't open file 'Blank1.bmp' (error 2: The system cannot find the file specified.)
07:41:13: Failed to load image from file "Blank1.bmp".
# The bitmap file is present in the same directory.

 

<details>
  <summary>Code Example (click to expand)</summary>

```python
# Put code sample here
```# Here is the code snippet: import wx
import time

class Window(wx.Frame): 

    def __init__(self, title):
        super().__init__(parent = None, title = title)
        panel = wx.Panel(self, wx.ID_ANY)
        
        photoButton = wx.Bitmap("Photo.bmp", wx.BITMAP_TYPE_ANY )
        photoBlank = wx.Bitmap("Blank1.bmp", wx.BITMAP_TYPE_ANY)

        self.timer1 = wx.Timer(self)
        self.Bind(wx.EVT_TIMER, self.photoTimer, self.timer1)
        self.togglePhotoBtn = wx.Button(panel, style = (wx.NO_BORDER), pos = (31,7),
            size = (100, 32))
        self.togglePhotoBtn.SetBitmap(photoButton)
        self.togglePhotoBtn.Bind(wx.EVT_BUTTON, self.Photo)
        self.image_bitmap1 = wx.StaticBitmap(panel)
        self.image_bitmap1.SetPosition((10,48))
        
    def Photo(self, event):
        self.timer1.Start(100)
        photoBlank = wx.Bitmap("Blank1.bmp", wx.BITMAP_TYPE_ANY)
        self.togglePhotoBtn.SetBitmap(photoBlank)        
        
    def photoTimer(self, event):
        self.timer1.Stop()
        photoButton = wx.Bitmap("Photo.bmp", wx.BITMAP_TYPE_ANY)
        self.togglePhotoBtn.SetBitmap(photoButton)
        
        wildcard = "Image files (*.jpg;*.jpeg;*.png;*.bmp)|*.jpg;*.jpeg;*.png;*.bmp"
        dialog = wx.FileDialog(self, "Select an image", wildcard=wildcard, style=wx.FD_OPEN)
        if dialog.ShowModal() == wx.ID_OK:
            image_path1 = dialog.GetPath()
            self.display_resized_image1(image_path1)
            photoButton = wx.Bitmap("Photo.bmp",wx.BITMAP_TYPE_ANY )
            self.togglePhotoBtn.SetBitmap(photoButton)
        dialog.Destroy()
        
        
        self.SetSize(1332,933)
        self.Centre()
        self.Show()
        
if __name__ == "__main__":
    app = wx.App()
    Window("Button Test")
    app.MainLoop()
</details>

**Comment by infinity77** [comment]
Do you get anything meaningful if you do something like:

print(os.path.isfile(“Photo.bmp”))

?

**Comment by wxmurph** [comment]
I typed in the code print(os.path.isfile(“Photo.bmp”)) along with Import os and received: False


________________________________

**Comment by wxmurph** [comment]
If you want to test the program directly, here are the bitmap files in the same directory as the Button test
________________________________

**Comment by infinity77** [comment]
On Fri, 7 Jun 2024 at 17.15, wxmurph ***@***.***> wrote:

> I typed in the code print(os.path.isfile(“Photo.bmp”)) along with Import
> os and received: False


Then what do you expect wxPython to do? If the os.path.isfile() returns
False then Python didn’t find your file in the file system.

How are you running your app from code? Try not to use relative paths like
“Photo.bmp”, give it the full path - possibly dynamically generated from
the app source dir.

This is basic Python, I don’t think the bug report is valid.



>
> ________________________________
> From: Andrea Gavana ***@***.***>
> Sent: Friday, June 7, 2024 8:09 AM
> To: wxWidgets/Phoenix ***@***.***>
> Cc: wxmurph ***@***.***>; Author ***@***.***>
> Subject: Re: [wxWidgets/Phoenix] wx.Bitmap() cannot find image error
> (Issue #2556)
>
> Do you get anything meaningful if you do something like:
>
> print(os.path.isfile(“Photo.bmp”))
>
> ?
>
