### ISSUE TITLE
nanosvg needs recompiling with newer Cython

### ISSUE THREAD

**Issue by bje-** [wxWidgets/Phoenix#2567]
Newer versions of Cython include code to handle a C API change in Python 3.13. I tried doing this myself, but ran into a lot of bother.

**Comment by bje-** [comment]
I should add that with this one fix (I hacked the generated file as a workaround), wxPython compiles fine for Python 3.13.

**Comment by bje-** [comment]
I was able to get Cython working.

**Comment by swt2c** [comment]
Fixed by #2573.
