### ISSUE TITLE
Numpy2 removed numpy.sometrue. 

### ISSUE THREAD

**Issue by iandobbie** [wxWidgets/Phoenix#2574]
Windows 10 22H2
'4.2.1 msw (phoenix) wxWidgets 3.2.2.1'
Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)] on win32

I am not yet sure exactly the code path that is calling this but I will track down how to trigger this in a simple way but my application generates an exception. The core issue is in floatcanvas/FloatCanvas.py at line 604 

        if N.sometrue(self.PanelSize <= 2 ):

numpy no longer has a numpy.sometrue() function

**Comment by iandobbie** [comment]
If you just try to run Phoenix/samples/floatcanvas/MicroDemo.py you actually get two different numpy2 errors. 

  File ".../floatcanvas/lib/python3.12/site-packages/wx/lib/floatcanvas/FloatCanvas.py", line 782, in ZoomToBB
    (BoundingBox[0,1]+BoundingBox[1,1])/2 ),N.float_)

Numpy.float_ has been removed from numpy2

and then 

  File ".../floatcanvas/lib/python3.12/site-packages/wx/lib/floatcanvas/FloatCanvas.py", line 604, in Draw
    if N.sometrue(self.PanelSize <= 2 ):
       ^^^^^^^^^^

numpy.sometrue has also been removed. 

Changing these sections to N.float64 and N.any respectively fixed these issues.

**Comment by reticulatus** [comment]
Yes, `numpy.sometrue()` has been raising DeprecationWarnings for a while now, see https://github.com/wxWidgets/Phoenix/issues/2498
