### ISSUE TITLE
Update waf to 2.0.25 (for Python 3.12)

### ISSUE THREAD

**Issue by wegank** [wxWidgets/Phoenix#2575]
**Operating system**: NixOS
**wxPython version & source**: 4.2.1, pypi         
**Python version & source**: 3.12, distro           

**Description of the problem**:

In Python 3.12, `distutils` has been dropped from stdlib and is provided by `setuptools` instead, but `import distutils` is [not guaranteed](https://github.com/cython/cython/pull/5754#issuecomment-1752102480) to succeed without importing `setuptools` first, and in particular, waf 2.0.24 fails to launch in a Nix build environment. As this issue has been [fixed](https://gitlab.com/ita1024/waf/-/blob/old-waf-2.0/ChangeLog?ref_type=heads#L19) in waf 2.0.25, and building with waf 2.0.25 [works on our side](https://github.com/NixOS/nixpkgs/pull/326142), we'd like to request an update here.

<details>
  <summary>Code Example (click to expand)</summary>

```python
# Put code sample here
```
</details>

**Comment by jfly** [comment]
For the record, we discussed this upgrade [over here](https://github.com/NixOS/nixpkgs/pull/326142#discussion_r1681447077):

- waf 2.0.25 works
- waf 2.1.1 does not work (because of https://gitlab.com/ita1024/waf/-/merge_requests/2371)
- waf 2.1.2 works
