### ISSUE TITLE
wheels for manylinux

### ISSUE THREAD

**Issue by alasdairwilson** [wxWidgets/Phoenix#2582]
Do you not provide prebuild wheels for linux? Is there a reason for this, the build time is very large so it would be good to avoid it if this is possible.

**Comment by swt2c** [comment]
Yes there is a reason: wxPython has a very large number of library dependencies, including GUI libraries which vary widely between Linux distributions, making it very difficult, if not impossible, to make a wheel that works on all Linux distributions.
