### ISSUE TITLE
setuptools.msvc removed in setuptools 74

### ISSUE THREAD

**Issue by swt2c** [wxWidgets/Phoenix#2590]
It seems that setuptools.msvc was removed in setuptools 74.  Pinned setuptools on Windows for now, but need to figure out whether this can be replaced with something else.

**Comment by komoto48g** [comment]
In setuptools 74.1.0 "msvc.py" is reverted. But soon, the patch will be needed.

**Comment by swt2c** [comment]
Thanks @komoto48g!
