### ISSUE TITLE
Bug Report for wx.stc and wx.richtextctrl

### ISSUE THREAD

**Issue by Joonhyun-Kim** [wxWidgets/Phoenix#2606]
**Operating system**:
**wxPython version & source**:          
**Python version & source**:            

**Description of the problem**:

<details>
  <summary>Code Example (click to expand)</summary>

```python
# Put code sample here
```
</details>

#### Title:  
Korean Characters Disappear When Entering Punctuation with Shift Key in wx.stc.StyledTextCtrl and wx.RichTextCtrl (Windows 11)

#### Description:

- **Environment**:
  - OS: Windows 11 (Issue present)
  - OS: Windows 10 Pro (Issue not present)
  - wxPython version: 4.2.1
  - Python version: 3.12.5

- **Issue**:
  When typing Korean characters in `wx.stc.StyledTextCtrl` or `wx.RichTextCtrl` on Windows 11, entering specific punctuation (e.g., `^`, `"`) using the Shift key causes the last entered Korean character to disappear.

  Example: After typing "안녕" (Hello in Korean), if I press Shift + `6` (to insert `^`) or Shift + `'` (to insert `"`), the last character "녕" disappears. This results in "안^" or "안"".

- **Steps to Reproduce**:
  1. On Windows 11, open an editor using `wx.stc.StyledTextCtrl` or `wx.RichTextCtrl`.
  2. Type Korean characters (e.g., "안녕").
  3. Press Shift + a punctuation key (e.g., `"`, `^`).
  4. The last Korean character disappears, and only the punctuation remains.

- **Expected Behavior**:
  The Korean characters should remain in the text, and the punctuation should be added without any characters being deleted.

- **Actual Behavior**:
  The last Korean character disappears, and only the punctuation is inserted.

- **Additional Information**:
  - The issue occurs on Windows 11 but does not appear on Windows 10 Pro.
  - The issue happens in both `wx.stc.StyledTextCtrl` and `wx.RichTextCtrl`.

**Comment by swt2c** [comment]
I have a hunch this might be the same problem as: https://github.com/wxWidgets/Phoenix/issues/2446

Can you please try one of the latest snapshot builds and see if the problem is resolved there:
https://wxpython.org/Phoenix/snapshot-builds/

**Comment by swt2c** [comment]
Please also try v4.2.2 (just released) and let us know if the problem has been fixed.

**Comment by swt2c** [comment]
Closing due to lack of response...

**Comment by Metallicow** [comment]
If you cannot speak good english, there is not much we can do for you. Sorry to say...
