### ISSUE TITLE
can't import wx

### ISSUE THREAD

**Issue by alvis-spac** [wxWidgets/Phoenix#2612]
**Operating system**:windows10
**wxPython version & source**:wxPython4.2.2          
**Python version & source**: python3.12.2          

**Description of the problem**:
import wx
from wx.core import *
from ._core import *
ImportError: DLL load failed while importing _core:Cannot find the specified module

<details>
  <summary>Code Example (click to expand)</summary>

```python
# Put code sample here
```
</details>

**Comment by swt2c** [comment]
Working fine for me on Windows 10 AMD64 with Python 3.12.6.

32-bit or 64-bit?  Or ARM64?  How did you install wxPython?

**Comment by alvis-spac** [comment]
My windows10  is x64. I install wxPython with PycharmCommunity2023 Terminal--pip install wxPython.
Confuse me is that I use other third-party libaries is normal in this way--install and import.

**Comment by DietmarSchwertberger** [comment]
Working fine here with Python 3.12.0 and 3.12.5:
![grafik](https://github.com/user-attachments/assets/80d7b961-54d0-4dbf-95a2-b249a8a4ce5e)

What does your site-packages and wx directory look like?
![grafik](https://github.com/user-attachments/assets/812ff64c-af60-4df0-ab40-e33df4ac907c)

![grafik](https://github.com/user-attachments/assets/611fb52d-052d-445f-be53-dac9002ac8ab)
...

![grafik](https://github.com/user-attachments/assets/7549cbd2-b62d-4cff-9dfc-f0c56c689abf)

**Comment by alvis-spac** [comment]
The installation process is automated and I did not modify any directories.
![333](https://github.com/user-attachments/assets/90c64d2f-715f-48a7-847b-7be5609c1326)
![1111](https://github.com/user-attachments/assets/96a35e7e-86d4-446d-a9dd-7b6cd48a883a)
![1221](https://github.com/user-attachments/assets/5938da19-b965-4c8f-8038-97fb4dedf862)
![444](https://github.com/user-attachments/assets/5cd67ad4-b804-4464-91dc-63d1b834ae48)

**Comment by DietmarSchwertberger** [comment]
Do you have e.g. `wxmsw32u_core_vc140_x64.dll` in the `site-packages` directory?
Personally I don't use Virtual Environments, so I don't know whether this is causing the issues.

Maybe, you want to run `DependenciesGui.exe` to check the dependencies of `_core.cp312-win_amd64.pyd`.
It's available from here: https://github.com/lucasg/Dependencies
Just run it and drag the .pyd file to it's window.

This is correct:
![grafik](https://github.com/user-attachments/assets/dc2a19e7-af3b-485f-891e-cb3ed0e30138)

This is when I remove the `wxmsw...dll`:
![grafik](https://github.com/user-attachments/assets/074e3ae4-7db8-434a-99ca-e659c7c6a070)

**Comment by DietmarSchwertberger** [comment]
I have tried with a virtual environment and this did work for me.
Strange enough, there is also similar bug report #2614 for MacOS.

**Comment by alvis-spac** [comment]
Thanks bro! When I don't install wxpython in a virtual environment, it works fine.

**Comment by swt2c** [comment]
I suspect the root cause here is probably some sort of DLL search path problem with the OP's environment.

**Comment by RobinD42** [comment]
This issue has been mentioned on **Discuss wxPython**. There might be relevant details there:

https://discuss.wxpython.org/t/interesting-install-issue/39992/17
