### ISSUE TITLE
discuss.wxpython.org outage

### ISSUE THREAD

**Issue by swt2c** [wxWidgets/Phoenix#2631]
The wxPython Discourse site (discuss.wxpython.org) is currently offline.  Recently, the site was receiving a large amount of spam posts.  In an attempt to address the spam, I tried to upgrade the Discourse version.  Unfortunately, this failed and Robin is investigating.

**Comment by tierra** [comment]
I've been able to bring Discourse back up and online, even running an upgraded version of Discourse.

There's still some work to be done to clean up and mitigate spam, but at least it's back up and running now.

**Comment by swt2c** [comment]
I just went and removed all the spam posts.  Everything should be back to normal (hopefully!) now.  Will still take a look to see if there are further anti-spam stuff we can turn on.

**Comment by tierra** [comment]
I installed and configured Akismet now. If that's not effective, we can turn on always-moderated first posts.

Just trying to avoid the need for manual approvals on all new posts if we can, as I don't think there's anyone with the time to spend actively moderating all new posts every day.

**Comment by swt2c** [comment]
> I think that, as the spammers have now got back in, perhaps new users' first posts should need moderator approval before they appear.

@reticulatus where are you seeing that the spammers have gotten back in?

**Comment by tierra** [comment]
New one actually just came in that did match the silenced words, and was properly sent to review queue this time. So that does appear to be working after all now.

**Comment by tierra** [comment]
Akismet appears to be working, even for this post that avoided spammy content (but is definitely spam attempting to get a first post through, and if this did go through, it would likely come back to post actual spam on the same account):

![image](https://github.com/user-attachments/assets/330d4064-cf42-4440-bbd5-f77dd924ef55)

**Comment by swt2c** [comment]
Seems to be running well now with the new anti-spam stuff, so closing this issue.
