### ISSUE TITLE
Pickle of wx.RealPoint objects

### ISSUE THREAD

**Issue by lorenzonebolosi** [wxWidgets/Phoenix#2644]
**Operating system**: Windows 10
**wxPython version & source**:  4.2.2,  from PyPi
**Python version & source**:  Python 3.12.7, installer

**Description of the problem**: When pickling a wx.RealPoint object it gets pickled as wx.Rect. The code in the example returns an error, saying that when unpickling the file, the two arguments of the RealPoint are passed to a Rect object which can not be created with those two arguments:
```    
loaded_point = pickle.load(file)
               ^^^^^^^^^^^^^^^^^
TypeError: Rect(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 1 has unexpected type 'float'
  overload 3: argument 1 has unexpected type 'float'
  overload 4: argument 1 has unexpected type 'float'
  overload 5: argument 1 has unexpected type 'float'
  overload 6: argument 1 has unexpected type 'float'
```
This error was not present in previous version of wxPython, in fact when running the same script (adjusting the print statements) with python 2.7 and wxPython 3.0.2.0 this error does not occure.

**Mitigation of the problem**: 
A possible solution to this problem that I've adopted is to use a custom class that overwrites the find_class method of the Unpickler that when trying to unpickle a rect object, it passes those arguments to a wx.RealPoint object instead and returns it. However this is a temporary solution and can not be used everytime since it forces this convertion even when the object to unpickle is intended to be a Rect.

<details>
  <summary>Code Example (click to expand)</summary>

```
import wx
import pickle

point = wx.RealPoint(10.5, 20.75)
with open("realpoint.pkl", "wb") as file:
    pickle.dump(point, file)
with open("realpoint.pkl", "rb") as file:
    loaded_point = pickle.load(file)

print(f"Original point: ({point.x}, {point.y})")
print(f"Unpickled point: ({loaded_point.x}, {loaded_point.y})")

```
</details>

<details>
  <summary>Temporary solution (if anyone is in the same situation)</summary>

```
import pickle
import wx

class CustomUnpickler(pickle.Unpickler):
    def find_class(self, module, name):
        # Check if we are loading wx._core.Rect
        if module == "wx._core" and name == "Rect":
            # Intercept wx.Rect calls
            print(f"Unpickling {module}.{name}")
            # Return a custom function to simulate `wx.Rect` instantiation
            return self._rect_to_real
        return super().find_class(module, name)
    
    def _rect_to_real(self, *args):
        print(f"wx.Rect called with args: {args}")
        return wx.RealPoint(*args)  # Return a properly constructed wx.Rect


point = wx.RealPoint(10.5, 20.75)
with open("realpoint.pkl", "wb") as file:
    pickle.dump(point, file)
with open("realpoint.pkl", "rb") as file_obj:
    loaded_point = CustomUnpickler(file_obj).load()

print(f"Original point: ({point.x}, {point.y})")
print(f"Unpickled point: ({loaded_point.x}, {loaded_point.y})")


```
</details>

**Comment by infinity77** [comment]
It seems to me that the `__reduce__` code for wxRealPoint is not setup correctly in the etg code:

https://github.com/wxWidgets/Phoenix/blob/73cbeec90519047270f90c23bbd291c35e49822d/etg/gdicmn.py#L342

I’m not so expert in that part of the code but I don’t think `__reduce__` should return Rect()…

**Comment by swt2c** [comment]
> It seems to me that the `__reduce__` code for wxRealPoint is not setup correctly in the etg code:
> 
> https://github.com/wxWidgets/Phoenix/blob/73cbeec90519047270f90c23bbd291c35e49822d/etg/gdicmn.py#L342
> 
> I’m not so expert in that part of the code but I don’t think `__reduce__` should return Rect()…

Nice find @infinity77 :-)

**Comment by RobinD42** [comment]
This issue has been mentioned on **Discuss wxPython**. There might be relevant details there:

https://discuss.wxpython.org/t/rect-typeerror-while-converting-from-python-2-to-python-3/40016/3
