### ISSUE TITLE
DrawRoundedRectangle casting to int

### ISSUE THREAD

**Issue by lorenzonebolosi** [wxWidgets/Phoenix#2648]
**Operating system**: Windows 10
**wxPython version & source**:          wxPython 4.2.2 from pip, wxPython 4.2.3 from Snapshot builds
**Python version & source**:            Python 3.7 (wxPython 4.2.2) Python 3.10 (wxPython 4.2.3)

**Description of the problem**:
I am opening a rectangle that I had previously saved in a pickle and trying to draw it, however It was saved in python 2.7 and height and width are floats, so are x and y cordinates. However in  https://github.com/wxWidgets/Phoenix/blob/8908dd6c518cbddf4f7e956ab4e6f05293747d3a/wx/lib/ogl/basic.py#L2772 the casting of the x and y cordinates is done, but not of height and width, which results in an error when drawing it. Can this be solved with a casting also on height and width? This problem was not present with python 3.7, in fact the simple script that I attach run perfectly in 3.7 but not in 3.10 with wxPython 4.2.3, probably due to a change in the implementation of the DrawRoundedRectangle method. 

<details>
  <summary>Code Example (click to expand)</summary>

        import wx
        
        class RoundedRectangleFrame(wx.Frame):
            def __init__(self, *args, **kw):
                super(RoundedRectangleFrame, self).__init__(*args, **kw)
        
                # Set up the size and position for the rounded rectangle
                self._x1, self._y1 = 400.0, 112.42         # Top-left corner coordinates
                self._width, self._height = 80.0, 55.14 # Rectangle width and height
                self._cornerRadius = 15              # Corner radius
        
                # Bind the paint event
                self.Bind(wx.EVT_PAINT, self.OnPaint)
        
                # Set frame properties
                self.SetSize((700, 500))
                self.SetTitle("Rounded Rectangle with wxPython")
                self.Centre()
                
            def OnPaint(self, event):
                # Create a device context for drawing
                dc = wx.PaintDC(self)
        
                # Set the background color
                dc.SetBackground(wx.Brush("white"))
                dc.Clear()
        
                # Set pen and brush for the rectangle
                dc.SetPen(wx.Pen("black", width=2))
                dc.SetBrush(wx.Brush("sky blue"))
        
                # Draw the rounded rectangle with specified parameters
                dc.DrawRoundedRectangle(int(self._x1), int(self._y1), self._width, self._height, self._cornerRadius)
        
          if __name__ == "__main__":
              app = wx.App(False)
              frame = RoundedRectangleFrame(None)
              frame.Show()
              app.MainLoop()

</details>

**Comment by swt2c** [comment]
Yes, you are seeing a breaking change that was introduced in Python 3.10, see:
https://github.com/python/cpython/issues/82180

Yes, the correct fix would be to add the int() casts for the width and height as well.

**Comment by lorenzonebolosi** [comment]
Okay, do you mean in https://github.com/wxWidgets/Phoenix/blob/8908dd6c518cbddf4f7e956ab4e6f05293747d3a/wx/lib/ogl/basic.py#L2772? Can you do it or tag who should do that?

**Comment by swt2c** [comment]
Pull requests are welcome.
