### ISSUE TITLE
Incompatible bleBdistWheel wheel.bdist_wheel is deprecated please import it from setuptools how do i solve it or import it from setuptools?

### ISSUE THREAD

**Issue by thesuseuser114** [wxWidgets/Phoenix#2653]
So First I'm Using OpenSUSE Tumbleweed and python 3.11.0 And Here's The Message

× Building wheel for wxPython (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [58 lines of output]
      /usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py:251: _IncompatibleBdistWheel: wheel.bdist_wheel is deprecated, please import it from setuptools
      !!
      
              ********************************************************************************
              Ensure that any custom bdist_wheel implementation is a subclass of
              setuptools.command.bdist_wheel.bdist_wheel.
      
              By 2025-Oct-15, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
      
              See https://github.com/pypa/wheel/pull/631 for details.
              ********************************************************************************
      
      !!
        return _build_backend().build_wheel(wheel_directory, config_settings,
      running bdist_wheel
      running build
      /tmp/pip-install-_q770btl/wxpython_ef3c69bf02514840a9b074c8737f8ef7/build.py:44: DeprecationWarning: dep_util is Deprecated. Use functions from setuptools instead.
        from distutils.dep_util import newer, newer_group
      Will build using: "/usr/bin/python3.11"
      3.11.10 (main, Sep 09 2024, 17:03:08) [GCC]
      Python's architecture is 64bit
      cfg.VERSION: 4.2.2
      
      Running command: build
      Running command: build_wx
      wxWidgets build options: ['--wxpython', '--unicode', '--gtk3']
      Configure options: ['--enable-unicode', '--with-gtk=3', '--enable-sound', '--enable-graphics_ctx', '--enable-display', '--enable-geometry', '--enable-debug_flag', '--enable-optimise', '--disable-debugreport', '--enable-uiactionsim', '--enable-autoidman', '--with-sdl']
      /tmp/pip-install-_q770btl/wxpython_ef3c69bf02514840a9b074c8737f8ef7/ext/wxWidgets/configure --enable-unicode --with-gtk=3 --enable-sound --enable-graphics_ctx --enable-display --enable-geometry --enable-debug_flag --enable-optimise --disable-debugreport --enable-uiactionsim --enable-autoidman --with-sdl
      checking build system type... x86_64-pc-linux-gnu
      checking host system type... x86_64-pc-linux-gnu
      checking for toolkit... gtk
      checking for gcc... no
      checking for cc... no
      checking for cl.exe... no
      configure: error: in `/tmp/pip-install-_q770btl/wxpython_ef3c69bf02514840a9b074c8737f8ef7/build/wxbld/gtk3':
      configure: error: no acceptable C compiler found in $PATH
      See `config.log' for more details
      Error running configure
      ERROR: failed building wxWidgets
      Traceback (most recent call last):
        File "/tmp/pip-install-_q770btl/wxpython_ef3c69bf02514840a9b074c8737f8ef7/build.py", line 1588, in cmd_build_wx
          wxbuild.main(wxDir(), build_options)
        File "/tmp/pip-install-_q770btl/wxpython_ef3c69bf02514840a9b074c8737f8ef7/buildtools/build_wxwidgets.py", line 379, in main
          exitIfError(wxBuilder.configure(dir=wxRootDir, options=configure_opts),
        File "/tmp/pip-install-_q770btl/wxpython_ef3c69bf02514840a9b074c8737f8ef7/buildtools/build_wxwidgets.py", line 72, in exitIfError
          raise builder.BuildError(msg)
      buildtools.builder.BuildError: Error running configure
      Finished command: build_wx (0.796s)
      Finished command: build (0.796s)
      WARNING: Building this way assumes that all generated files have been
      generated already.  If that is not the case then use build.py directly
      to generate the source and perform the build stage.  You can use
      --skip-build with the bdist_* or install commands to avoid this
      message and the wxWidgets and Phoenix build steps in the future.
      
      "/usr/bin/python3.11" -u build.py build
      Command '"/usr/bin/python3.11" -u build.py build' failed with exit code 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for wxPython
Failed to build wxPython
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (wxPython)

**Comment by swt2c** [comment]
Your problem is nothing to do with bdist_wheel (that's just a warning).

This is your actual problem:
```
  configure: error: in `/tmp/pip-install-_q770btl/wxpython_ef3c69bf02514840a9b074c8737f8ef7/build/wxbld/gtk3':
  configure: error: no acceptable C compiler found in $PATH
```

**Comment by Metallicow** [comment]
OMG there is a overflow of garbage and it is overwhelming,... Uhhhh. Garbage up to my neck. I can clean the place up better....mmhmmmm
