### ISSUE TITLE
Snapshots build

### ISSUE THREAD

**Issue by lorenzonebolosi** [wxWidgets/Phoenix#2654]
I'm sorry this isn't a real code issue and I don't know if it belongs here or on the forum.
Anyway: The snapshot builds are not being published anymore on the website and therefore I cannot access new versions of the package.
I have no idea how the builds are automatically generated so I wouldn't really know how to solve this.

**Comment by swt2c** [comment]
Where are you looking?

https://wxpython.org/Phoenix/snapshot-builds/

**Comment by lorenzonebolosi** [comment]
There. They were published every 2/3 maximum 4 days. While now the last one is from the 11/19

**Comment by swt2c** [comment]
They are only published when there are changes.  The last change committed was on 11/19.

**Comment by Metallicow** [comment]
It appears that they are being built again upon changes... Can you verify this @swt2c ? 
If so, then this can be closed.
running 
wxPython 4.2.3a1.dev5782+8a0d4e77 msw (phoenix) wxWidgets 3.2.6 Scintilla 3.7.2
Python 3.13.0 (tags/v3.13.0:60403a5, Oct  7 2024, 09:38:07) [MSC v.1941 64 bit (AMD64)] on win32
