### ISSUE TITLE
Phoenix >3.0.3.dev2869 and cx_freeze: terrible windows style

### ISSUE THREAD

**Issue by Nutznieser** [wxWidgets/Phoenix#275]
If you freeze an app with cx_freeze that use phoenix higher than 3.0.3.dev2869 the windows style looks very terrible: All buttons are raised, columns of listctrls are closer together, icons with black background, ... It looks like a very old windows style.

This effect appears **only if you freeze the app and with phoenix builds higher than 3.0.3.dev2869!** So I think, something would changed between build 2869 and build 2875 that leads to this effect.

I checked the problem with ...
- Win 7 / Win 10
- Python 3.5 / 3.6
- cx_freeze 5.0.1

and I got always the same behavior I described above.

Have anybody an idea what works wrong? I'am also not sure if this is really a phoenix problem or rather a cx_freeze problem? But I didn't have the problem with older phoenix builds, so I think it is originally based on phoenix.

**Comment by RobinD42** [comment]
That usually means that the themeable version of the MS Common Controls DLL is not found or can't be loaded for some reason. In the past one of those reasons could have been that the manifest file telling the system to load that DLL was not included or was misformatted. However wxPython has been doing that in code (instead of a separate file) for a very long time so that seem unlikely to be the problem.

The only change in that timeframe that dealt with the Windows builds in any way was #255, but I don't see how that could have had an effect like this issue.

**Comment by Nutznieser** [comment]
Thanks for your response. Meanwhile I made some tests and recognized the following:

1. I Produced two cx_freeze builds - one with phoenix build 2869 and one with build 2875 or newer (using on Python 3.6.1)
2. After it, I copied the `_core.pyd` from the cx_freeze build that includes 2869 version to the other cx_freeze build.

If I do so, my app works perfect and the look is right. I also compared the two `_core.pyd` from the different phoenix builds and I can see the 2869 build contains an application manifest like this:
```
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
    <security>
      <requestedPrivileges>
        <requestedExecutionLevel level="asInvoker" uiAccess="false"></requestedExecutionLevel>
      </requestedPrivileges>
    </security>
  </trustInfo>
  <dependency>
    <dependentAssembly>
      <assemblyIdentity type="win32" name="Microsoft.Windows.Common-Controls" version="6.0.0.0" processorArchitecture="x86" publicKeyToken="6595b64144ccf1df" language="*"></assemblyIdentity>
    </dependentAssembly>
  </dependency>
</assembly>
```
But the newer phoenix build doesn't contain this application manifest! I don't know if that makes the different or if this good or wrong?

**Comment by wossx** [comment]
That is not only freeze problem. In script mode too.
And in Python 2.7 too. (Win 7)

**Comment by Nutznieser** [comment]
> wossx wrote: In script mode too.

Which version of Python? 2.7 or >3.4?
I can confirm to have the problem for python 3.5 and 3.6 and only in freeze mode. In script mode all looks ok. But I can't check it for Python 2.7, because I haven't installed it.

**Comment by wossx** [comment]
wx          in script mode           with py2exe
Py2.7   build2869           OK                             OK
Py2.7   build2875          UGLY                          OK
Py2.7   build2902          UGLY                          OK

                 wx          in script mode         with PyInstaller
Py3.6   build2869           OK                             OK
Py3.6   build2875           OK                             OK
Py3.6   build2902           OK                             OK

OS: Win 7 SP1 64bit
Both Python is 32 bit.
Same program source code.

I think this is an OS environment problem. Or not.
Or I don't know. I'm not happy. :(

**Comment by RobinD42** [comment]
Thanks guys, I'm not sure how the manifest could have gotten lost. Maybe there is an error that is not triggering a build failure or something. I'll check into it today.

**Comment by RobinD42** [comment]
Reverted #255. This issue should be fixed in the next snapshot build.
