### ISSUE TITLE
Cannot pass StandardID to SetYesNoLabels and friends

### ISSUE THREAD

**Issue by adrientetar** [wxWidgets/Phoenix#276]
In msgdlg.py, per [this comment](https://github.com/wxWidgets/Phoenix/blob/3f01517c830de1cdd60eb7c5988d09984bf865dd/etg/msgdlg.py#L43-L45):

> These argument types are actually ButtonLabel, but the class is a private helper. We will always be passing in strings, and ButtonLabel will implicitly convert.

ButtonLabel can take wxString and wxStandardID, but wxPython defines the argument as wxString because ButtonLabel is private.  
The thing is without wxStandardID you loose the standard labels and the standard icons on wxGTK, see for instance this screenshot of a native application:

![selection_001](https://cloud.githubusercontent.com/assets/1250894/25042538/23cf2c04-2119-11e7-87ff-83e96666ca74.png)

@RobinD42 Is it possible to allow standard IDs there? I know PyQt5 uses a Union annotation in such cases.

**Comment by RobinD42** [comment]
Added a TODO to take care of this: be47177b34ae4e6413b25c236bdc76364e53e8b4
