### ISSUE TITLE
Building from wxWidgets master branch

### ISSUE THREAD

**Issue by adrientetar** [wxWidgets/Phoenix#282]
@RobinD42 I see that your patches to wxWidgets are in WX_3_0_BRANCH, but not in the master branch it seems. Why not?

**Comment by swt2c** [comment]
I think Robin's plan is to get Phoenix released based on wx 3.0 first, then he'll work on 3.1 support.

**Comment by RobinD42** [comment]
I think there are only a few recent changes that still need to be ported to wxWidgets master branch, which will happen when I shift my focus to 3.1 if not sooner.

**Comment by adrientetar** [comment]
I just found out that 3.0 doesn't support high DPI displays on Windows... I hope we can switch to 3.1 soon.

**Comment by adrientetar** [comment]
I'm trying to build from master and besides deleted some stuff that was removed, it seems the commit https://github.com/wxWidgets/wxWidgets/commit/1d5119acf5498ab356c0ddaea30d8b34a3722fc3 is missing from the master branch. @RobinD42 should it be committed to master as well?

**Comment by swt2c** [comment]
I think this can be closed now that a 4.1.x release is out?

**Comment by RobinD42** [comment]
Yes, indeed.
