### ISSUE TITLE
ImportError: No module named 'wx._adv' when building a standalone

### ISSUE THREAD

**Issue by belangeo** [wxWidgets/Phoenix#289]
Hi,

I'm trying to build a standalone on osx with py2app and wxPython. Since I installed 4.0.0a1 (worked with 3.0.3dev2902), I got this error:

Oliviers-Mac-mini:~ olivier$ /Users/olivier/git/cecilia5/Cecilia5.app/Contents/MacOS/Cecilia5 ; exit;
pyo version 0.8.5 (uses single precision)
Loading Cecilia Preferences...
Traceback (most recent call last):
  File "/Users/olivier/git/cecilia5/Cecilia5.app/Contents/Resources/__boot__.py", line 81, in <module>
    _run()
  File "/Users/olivier/git/cecilia5/Cecilia5.app/Contents/Resources/__boot__.py", line 66, in _run
    exec(compile(source, path, 'exec'), globals(), globals())
  File "/Users/olivier/git/cecilia5/Cecilia5.app/Contents/Resources/Cecilia5.py", line 25, in <module>
    from Resources import audio, CeciliaMainFrame
  File "Resources/CeciliaMainFrame.pyc", line 25, in <module>
  File "Resources/PreferencePanel.pyc", line 24, in <module>
  File "Resources/Widgets.pyc", line 22, in <module>
  File "wx/richtext.pyc", line 17, in <module>
  File "wx/_richtext.pyc", line 14, in <module>
  File "wx/_richtext.pyc", line 10, in __load
  File "imp.pyc", line 342, in load_dynamic
ImportError: No module named 'wx._adv'
2017-04-18 15:07:03.813 Cecilia5[11664:707] Cecilia5 Error

I tried to copy the file manually in lib-dynload folder but it doesn't resolve the problem... 

Any ideas? Thanks!

**Comment by RobinD42** [comment]
IIRC, py2app has a way to explicitly include certain modules or packages that it doesn't find on its own.  Have you tried that?

**Comment by belangeo** [comment]
But py2app does find wx, only some modules are missing. A manual copy did not do it, I will take another look at py2app options to see how I can include only the missing modules. In the mean time, here is what is already included:
In Frameworks:
![py2app_frameworks](https://cloud.githubusercontent.com/assets/7251148/25157551/12e1c618-2470-11e7-8b4e-66743f20f416.png)

In lib-dynload:
![py2app_lib-dynload](https://cloud.githubusercontent.com/assets/7251148/25157566/266c20de-2470-11e7-8c47-5a10b5bb363f.png)

Olivier

**Comment by RobinD42** [comment]
Yep, but IME tools like this still need help sometimes because they tend to optimize things out if they don't see an explicit import for it or whatever they are using to figure out what needs to be included, and sometimes they get it wrong.

**Comment by mesalu** [comment]
If I remember correctly adding this in your setup.py file should do the trick:
`
OPTIONS = {
    'packages': ['wx._adv']
    }
`
Or adding it to the `'packages'` list if you've already configured `OPTIONS`

Another option would be to explicitly import wx._adv in code visible to py2exe. This should get it to notice and bundle the _adv submodule.

On another note:
If it is an option, I'd consider swapping to pyinstaller as they seem to be keeping up with python op code updates better than everyone else and they've done a better job at finding and packaging necessary modules with out any configuration. I've only used it on Windows so far, but it was far more favorable than py2exe.

**Comment by belangeo** [comment]
On Windows, I've always use PyInstaller, it does a great job. I tried it yesterday on OSX, to see if it can be a good alternative and it does not seem so... I had to explicitly add every modules I use, very annoying!

For future references, this does the job:
`OPTIONS = {'includes': 'wx.adv,wx.html,wx.xml'}`

**Comment by wettenhj** [comment]
@belangeo, I'm currently working on switching my wxPython application's Mac builds from py2app to PyInstaller, so I can then use PyUpdater for automatic updates.  I think you might have given up on PyInstaller on OSX too quickly - I haven't seen the problem you reported of having to explicitly add every module.  If you can provide a way to reproduce the problems you're having with PyInstaller, I'd be interested to see it.

**Comment by belangeo** [comment]
I have to admit that I didn't spend a lot of time trying pyinstaller! My focus was more on fixing my py2app setup than creating a new one! I just tried the command that does almost everything for me on Windows. On Mac, that does a very minimal build:

`pyinstaller --clean -F -w --icon=Resources\Cecilia5.icns "Cecilia5.py"`

**Comment by wettenhj** [comment]
@belangeo, your PyInstaller command looks OK.  There's not enough information here to determine why it isn't working the way you expect it to.  Thanks for sharing your method for including the missing wxPython modules in py2app.  It sounds like you're happy sticking with py2app, but if you want to try PyInstaller on OSX again, you could post your errors to https://groups.google.com/forum/#!forum/PyInstaller

**Comment by Himura2la** [comment]
Windows, PyInstaller
```
Traceback (most recent call last):
  File "main.pyw", line 26, in <module>
  File "c:\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "text_window.py", line 5, in <module>
  File "c:\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\wx\richtext.py", line 17, in <module>
  File "c:\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 714, in load_module
    module = loader.load_module(fullname)
ModuleNotFoundError: No module named 'wx._adv'
```

**Comment by belangeo** [comment]
You can also use PyInstaller's `hidden-import` flag to force the packaging of the missing modules. 

From the python script used to build Soundgrain:

```
flags = "--clean -F -c"
hidden = "--hidden-import wx.adv --hidden-import wx.html --hidden-import wx.xml"
icon = "--icon=Resources\SoundGrain.ico"
os.system('pyinstaller %s %s %s "SoundGrain.py"' % (flags, hidden, icon))

```
