### ISSUE TITLE
Python ports of classes from Classic wx.gizmos

### ISSUE THREAD

**Issue by RobinD42** [wxWidgets/Phoenix#302]
Port these modules from gizmos in wxCode to a pure-python wx.lib implementation?

- [x] DynamicSashWindow
- [x] LEDNumberCtrl
- [ ] SplitTree ??
- [x] TreeListCtrl

**Comment by mesalu** [comment]
@RobinD42 Do you intend on porting SplitTree too?

**Comment by RobinD42** [comment]
No. The implementation was a little sketchy, and there hasn't been any complaints about not having it, so probably not worth the effort.
