### ISSUE TITLE
agw.CustomTreeCtrl lose custom text colour

### ISSUE THREAD

**Issue by wossx** [wxWidgets/Phoenix#310]
This is in line 7981:
```
#TODO/Bug?: Temp Hack - MCow. Phoenix after rightclick menu item gets set to white or background colour
# and becomes invisible. Set to black in meantime
self.SetItemTextColour(thisItem, wx.BLACK) #self.GetItemTextColour(thisItem)
```

That remains so ? Destroys the custom text colour.
I have to comment out every time.

**Comment by Metallicow** [comment]
@wossx 
Try commenting that line out. It was a temp fix. See if that helps and report back.

**Comment by wossx** [comment]
Works for me too on windows.
Thanks.
