### ISSUE TITLE
wx.PopupTransientWindow opens very slowly over wx.agw.aui.Manager

### ISSUE THREAD

**Issue by Nutznieser** [wxWidgets/Phoenix#317]
For presenting this problem I created a small test app. It shows a wx.PopupTransientWindow over wx.agw.aui.Manager. The popup window contains a wx.lib.scrolledpanel.ScrolledPanel with a grid of 500 wx.StaticBitmap and wx.StaticText lines.

In the test app you can check the popup with and without the aui.Manager (just switch the variable `show_on_aui_mgr`).

And here is the problem:
If the popup is shown over the aui.Manager it needs much more time for making it visible. You can also see the aui.Manager window seems to be refreshed many times until the popup is completely loaded.

Another interesting thing: That problem appears only since the wxPython/Phoenix build dev2902. Before it that problem doesn't exist; all works very well. So it seems there was any change that produce the problem. But unfortunately I can't figured out where.

My environment is Windows 10-64bit with python 3.6.1 32bit.
(If you want to run the test app, please rename it from .txt to .py)

[test_PopupTransientWindowOnAui.txt](https://github.com/wxWidgets/Phoenix/files/949112/test_PopupTransientWindowOnAui.txt)

**Comment by Metallicow** [comment]
The agw.aui.Manager redraw code has some unneeded extra redraw/update calls somewhere. Hard to find tho... as it fires off refreshing a dozen times; who knows why.
I get this too with multiple panes and moving a aui.Toolbar. in my app.

**Comment by Nutznieser** [comment]
I found the code change that led to this problem. See issue #270 and the belonging commit. As a result of this change the whole frame manager is updated for each single window/widget within the ScrolledPanel. And that requires much time.

I think we have to find a better solution for issue #270.

**Comment by RobinD42** [comment]
Does #330 take care of the problem for you?

**Comment by Nutznieser** [comment]
Yes, #330 solves the issue I described here.
