### ISSUE TITLE
wx.Font unhashable type

### ISSUE THREAD

**Issue by kg-2** [wxWidgets/Phoenix#319]
```
font_dict = {}
a_font = wx.Font(size, 74, 90, 90, True, "Tempus Sans ITC")
font_dict[a_font] = "any value"
```

works fine with py 2.7.13, raises TypeError unhashable type: 'Font'  in py 3.6.1, using phoenix 4.0.0.1a

**Comment by RobinD42** [comment]
Python 3 has stricter rules for what is hashable and what isn't.  See https://docs.python.org/2/reference/datamodel.html#object.__hash__ and https://docs.python.org/3/reference/datamodel.html#object.__hash__

In a nutshell, objects in Python 2.7 have a default `__hash__()` that is based on the `id()` of the object, which is basically just an integer representation of the pointer to the PyObject instance in memory.  This means that you could have equivalent font objects (that compare equal with `==`) but which have different hash values. In addition, font objects are mutable, which means that it is a bad idea to use them as dictionary keys in either version of Python. 

In Python 3 it's a little more complicated than that. Objects do not get a default `__hash__` if they have a custom `__eq__`, and if they have a custom `__hash__` then it is supposed to be meaningful based on the contents of the object, and `__eq__` is supposed to fail if the compared object is not the same type.  We could do all that for `wx.Font`, but we would still have the problem of mutability.

We could probably add a `GetIM` method like what has recently been done for `wx.Size`, `wx.Colour` and such, but there is already `GetNativeFontInfoDesc` which will give you a hashable value (a string) that can be used to reconstruct a matching `wx.Font` if need.

**Comment by RobinD42** [comment]
@kg-2, does using `GetNativeFontInfoDesc` to get a hashable representation of the font work for your needs?

**Comment by kg-2** [comment]
Sorry about the delayed reply, yes that should work. I'll close this issue. Thanks for your continued work on this
