### ISSUE TITLE
Neither wx.grid. nor wx has a GRID_AUTOSIZE attribute

### ISSUE THREAD

**Issue by david-hughes** [wxWidgets/Phoenix#331]
Classic docs:
> SetColLabelSize(height)
    Sets the height of the column labels.
    If height equals to wx.grid.GRID_AUTOSIZE then the height is calculated automatically so that no label is truncated.
    This flag is new since wxPython version 2.8.8.

Phoenix docs:
>  SetColLabelSize(self, height)
    Sets the height of the column labels.
    If height equals to GRID_AUTOSIZE then height is calculated automatically so that no label is truncated.

In Phoenix neither wx.grid. nor wx has an attribute GRID_AUTOSIZE

**Comment by RobinD42** [comment]
Thanks, I'll get it added.  In the meantime the value is -1 so you can move forward with using that.
