### ISSUE TITLE
RichTextXMLHandler stream methods

### ISSUE THREAD

**Issue by RobinD42** [wxWidgets/Phoenix#333]
from wxPython-users:

> I'm migrating an application that was originally developed in Python 2 and wxPython 3.0.2 to Python 3 and wxPython 4.0.0. The last thing I get stuck with is the use of the XML format in RichTextCtrl to keep the layout
> 
> For backup, in python 2, I wrote this (where rtc is a RichTextCtrl and txt a string then saved in a database) :
> 

```
import cStringIO as io  
handler = wx.richtext.RichTextXMLHandler()
stream = io.StringIO()
handler.SaveStream(rtc.GetBuffer(), stream)
stream.seek(0)
txt = stream.read()

```

> For reading :

```
stream = io.StringIO()
handler = wx.richtext.RichTextXMLHandler()
buffer = rtc.GetBuffer()
buffer.AddHandler(handler)
stream.write(txt)
stream.seek(0)
handler.LoadStream(buffer, stream)

```

> With wxPython 4.0.0, this way does not work as RichTextXMLHandler has no longer methods "LoadStream" and "SaveStream". There are now methods "ImportXML" and "ExportXML" but I have not found any examples to understand how to use them.

**Comment by swt2c** [comment]
Looks like Classic had a rename for LoadStream/SaveStream -> LoadFile/SaveFile for some reason:
https://github.com/wxWidgets/wxPython/blob/master/src/_richtextbuffer.i#L2334

**Comment by RobinD42** [comment]
Thanks, I thought that might be the case, but didn't have time to look into it right away.
