### ISSUE TITLE
wx.agw.aui auinotebook tab rearrangement leads to segfault in demo

### ISSUE THREAD

**Issue by braidedlogix** [wxWidgets/Phoenix#334]
In both the AUI and the AUI_notebook demos, both using agw-based notebooks, will give the following or similar error after rearranging tabs.
"""wx._core.wxAssertionError: C++ assertion "!wxMouseCapture::stack.empty()" failed at ..\..\src\common\wincmn.cpp(3319) in wxWindowBase::ReleaseMouse(): Releasing mouse capture but capture stack empty?"""  
These lead to segfaulting on close of the main demo.

**Comment by mprosperi** [comment]
are you seeing it with the pypi wheel? is solved in the daily snapshots

**Comment by braidedlogix** [comment]
I just installed wxPython-4.0.0a1-cp36-cp36m-win_amd64.whl, and not the daily snapshot. Glad to hear it's fixed.
