### ISSUE TITLE
missing OnPaint methods

### ISSUE THREAD

**Issue by mprosperi** [wxWidgets/Phoenix#342]
wx.Grid sub-windows (GridRowLabelWindow, GridColLabelWindow,..) miss the OnPaint method in phoenix. Didn' find anything in the docs about their renaming/replacement (win7, python3.5).
In wxpython3 I use this method to manage a row label marker depending on grid cursor position

**Comment by RobinD42** [comment]
In Classic the fact that wx.Window.OnPaint was accessible on Windows was probably a bad idea. It's platform specific, undocumented, unsupported and could disappear at any time in the C++ class.  Could you do what you need simply by catching the `EVT_PAINT` and handling it yourself?

**Comment by mprosperi** [comment]
ok, solved
