### ISSUE TITLE
Frame name is duplicated in frame title bar and pane for macOS

### ISSUE THREAD

**Issue by BrendanSimon** [wxWidgets/Phoenix#347]
The name of the frame is in the title bar of the frame and also in the top part of the main pane.  This occurs on macOS but not on Windows (see attached screenshots from the demo).

<img width="350" alt="wxdemo_frame_macos" src="https://cloud.githubusercontent.com/assets/472245/25768998/af791860-3252-11e7-93db-a32498b54ef1.png">
![wxdemo_frame_win7](https://cloud.githubusercontent.com/assets/472245/25768999/af7a8696-3252-11e7-992c-978242b24170.png)

**Comment by RobinD42** [comment]
I'm not able to duplicate this.  Anything unusual about your system, python, or your copy of wxPython?

**Comment by BrendanSimon** [comment]
I hope not.  Python 3.6, wxPython 4.0.0a1, macOS Sierra 10.12.4.

**Comment by DietmarSchwertberger** [comment]
Working fine for me with Python 3.6.1 and wxPython 4.0.0.a1

**Comment by BrendanSimon** [comment]
Maybe it is something with my installtion, but I can't figure out what it could be.

if `wx-config --version` reports 2.9.4, does that mean there is some hang over for older classic builds/installs that could be interfering?

My path looks ok and there aren't any obvious environment variables set.

```
$ echo $PATH
/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin:/Applications/Wireshark.app/Contents/MacOS
```

Guess I'll try an uninstall and reinstall of everything.

**Comment by RobinD42** [comment]
The `wx-config` result likely just means that you have an old installation of wxWidgets on the system, perhaps from a wxPython classic install.  For Phoenix (4.0+), if you installed via the wheel files, wxWidgets libs are embedded in the package folder instead of being more publicly visible. So there should be no cross-talk between a current wxPython and an older wxWidgets.

**Comment by BrendanSimon** [comment]
Definitely an issue with my setup.  I logged in as another user and the exact same code works fine.  It must be something with my environment but I haven't worked it out yet.

I've set `PATH` to the basic `bin` directories and still the same.  I even tried clearing `PATH` and invoking python with absolute path, but still the same result.

Environment looks ok too.

Currently stumped :-/

**Comment by ZanderBrown** [comment]
OSX now has native support for tabs, looking at that i expect it's the tab bar with only one tab showing
[Some info](http://www.macworld.com/article/3088342/macs/how-to-use-tabs-in-macos-sierra.html)

**Comment by BrendanSimon** [comment]
Not a tab.  It definitely is the frame.  It happens in the wxpython demo app too.

<img width="737" alt="wxglade_duplicate_frame_info" src="https://cloud.githubusercontent.com/assets/472245/25918659/95519f8c-360f-11e7-903d-2c8586a7a4e1.png">

<img width="970" alt="wxdemo_duplicate_frame_info" src="https://cloud.githubusercontent.com/assets/472245/25918689/ab155d04-360f-11e7-9667-c70a6a636759.png">

**Comment by ZanderBrown** [comment]
Defiently looks like the OSX tab bar (not had much experience with it though)

**Comment by RobinD42** [comment]
Is there a preference or keyboard shortcut somewhere that turns on a forced tab mode by default?

**Comment by ZanderBrown** [comment]
https://github.com/atom/atom/issues/12690#issuecomment-246930784

**Comment by BrendanSimon** [comment]
Yep.  It was the macOS tab bar.  Everything says Preferences=>Dock to select tab options, but the limited options didn't do anything.

However I did notice in `wxglade` in the `View` menu that there was an option `Show Tab Bar <shift-apple-T>`.  This was greyed out but pressing <shift-apple-T> did work.  i.e. the preview window in `wxglade` toggled the tab bar.

What's "interesting" is that when toggled off, I can now run my app, and the wxdemo app and the tab bar is no longer present.  So I guess it is a global user setting.

Thanks all :)

**Comment by RobinD42** [comment]
I guess the good news about all this is that this shows that wxMac is using the correct type of native window to get this new system feature applied to it. 😃

**Comment by DietmarSchwertberger** [comment]
Even more than that: it seems that this menu item is not from wxGlade, but automatically inserted by Mac OS into the menu if it finds a menu named "View". If you rename it, the additional item is gone...

**Comment by RobinD42** [comment]
Yep, wxMac will also merge system items into the Window menu if it exists.

**Comment by ZanderBrown** [comment]
@BrendanSimon so i wasn't compleatly off then 😄

**Comment by BrendanSimon** [comment]
@ZanderBrown : yes you were not completely off :)  I misunderstood your pointer to "tabs".  I thought you were referring to wx.Notebook tabs, rather than the new fangdangle macOS tabs :)

Thanks heaps !!

**Comment by itsayellow** [comment]
Is there a way to have the View menu on the Mac without the Mac system-added menu items (such as "Show Tab Bar")?

My apologies if it's bad etiquette to comment on a closed item, but this was the only help I could find for this.
