### ISSUE TITLE
DataViewVirtualListModel issue with 'PyObject' column type

### ISSUE THREAD

**Issue by acollange** [wxWidgets/Phoenix#350]
Associating a `DataViewVirtualListModel` to a `DataViewListCtrl `when a column of type 'PyObject' is declared generates the following message on the console:

```
TypeError: Sequence of string or unicode objects expected.
The above exception was the direct cause of the following exception:
SystemError: PyEval_EvalFrameEx returned a result with an error set
```

The same code works as expected with Classic.
All other column types (int, double, bool, string) seems to works too.

See the attached test case.
Platform GTK / Python 3.6.1 / wxPhoenix 4.0.0a2

[test_dvc_virtuallistmodel.txt](https://github.com/wxWidgets/Phoenix/files/986712/test_dvc_virtuallistmodel.txt)

**Comment by RobinD42** [comment]
I've not been able to duplicate this with a2, but I did with a1. Are you sure you've successfully installed a2? The issue sounds like it would have been covered by one of the dataview fixes implemented for a2.

**Comment by acollange** [comment]
I was using a2.dev2994. I have compiled and installed a2.dev3038.
This issue seems to be fixed in this version. You are moving too fast for me !
Thanks !
