### ISSUE TITLE
Can't see checkboxes with CheckListCtrlMixin in Linux

### ISSUE THREAD

**Issue by swprojects** [wxWidgets/Phoenix#355]
Using the following:

```python
class CheckList(wx.ListCtrl, ListCtrlAutoWidthMixin, CheckListCtrlMixin):
    
    def __init__(self, parent, style=wx.LC_REPORT|wx.LC_HRULES|wx.LC_VRULES|wx.LC_SINGLE_SEL):
        
        wx.ListCtrl.__init__(self, parent, style=style)
        # ListCtrlAutoWidthMixin.__init__(self)
        CheckListCtrlMixin.__init__(self)
```

Works normally in Windows 10 64-bit but there are no checkboxes in Ubuntu 16.04

edit: think it is related to gtk? Can't remember if I read it somewhere before...

**Comment by RobinD42** [comment]
Yes, it could be due to gtk, the version of gtk, or a particular theme. However I'm seeing the problem too so I'll dig into it a little deeper to see if I can diagnose it.

**Comment by RobinD42** [comment]
@swprojects Are you using a Phoenix build for gtk2 or for gtk3? Is it one of the released builds or a snapshot?

**Comment by swprojects** [comment]
pretty sure I installed using the snapshot. According to wx.version() it is

```
3.0.3.dev2812+b3485d4 gtk3 (phoenix)
```
but in my terrminal, searching for wx

```wxPython (4.0.0a2)          - Cross platform GUI toolkit for Python, "Phoenix" version
INSTALLED: 4.0.0a2.dev3038+953a2e5
 LATEST:    4.0.0a2
```

more specifically, testing on xubuntu 16.04

**Comment by RobinD42** [comment]
Hmm... The `wx.version()` should match the version number shown the other way so you are probably using a Python or a venv with an older snapshot than what you are expecting. Try to solve that and let me know if you are still seeing the issue in the latest.

**Comment by swprojects** [comment]
ah.. oops had an older ./local wx install which had priority.

Installed to 4.0.0a3.dev3059+4a5c5d9 gtk3 (Phoenix) and issue still persists.
