### ISSUE TITLE
size problem with agw.auibook

### ISSUE THREAD

**Issue by mprosperi** [wxWidgets/Phoenix#358]
in aui_notebook demo, if you drag a tab and drop it near a border of the auibook you get two visible book pages as expected. But in Classic they have the same size while in Phoenix (latest snapshot and a2) the new one is very narrow. Comparing auibook.py files of Classic and Phoenix I can't see any explicit statement on sizes that could explain this (python 3.5-64, win7)

**Comment by zanfio** [comment]
https://www.bountysource.com/issues/45160106-size-problem-with-agw-auibook/backers

**Comment by infinity77** [comment]
Hi,

    this specific issue on auibook.py seems to be fixed on my machine (Python 2.7 64 bit Windows 7, wxPython 4.0.0b2 msw) with the ridiculously simple patch attached. @mprosperi , could you please test and see if it works?

[auibook_patch.txt](https://github.com/wxWidgets/Phoenix/files/1443955/auibook_patch.txt)

Andrea.

**Comment by mprosperi** [comment]
yes, it works, thank you. Split method needs the same patch too

**Comment by infinity77** [comment]
Deal, I’ll patch it and make a pull request for Robin to apply... I’m not sure if I still have the write access rights I used to have back in time 😊

**Comment by infinity77** [comment]
Pull request up and running: https://github.com/wxWidgets/Phoenix/pull/593
