### ISSUE TITLE
Iterating wx.Point() can crash the interpreter. 

### ISSUE THREAD

**Issue by henniss** [wxWidgets/Phoenix#360]
The following code will crash the interpreter in Python 2:

```python
import wx

updates = []
for i in range(10000):
    x = wx.Point((1, 2))
    a, b = x
    updates.append((a, b))
```

If we replace `a, b = x` with `a, b = x.x, x.y`, it will instead run without issue.

Version info:

Python 2.7.10 and 2.7.13, 64 bit, but not Python 3.5 or 3.6.
Windows 10
wxPython 4.0.0a2

**Comment by RobinD42** [comment]
I've not been able to duplicate this problem, even with a debug build of Python...

**Comment by henniss** [comment]
Huh, that's odd. This will also segfault consistently on my linux machine after installing via pip into a clean virtualenv. (64 bit 2.7.13 with wxpython 4.0.0a2). 

Stack trace: 
```
#0  0x00007fdd55763a4a PyErr_Occurred (libpython2.7.so.1.0)
#1  0x00007fdd5578a365 _PyObject_GC_Malloc (libpython2.7.so.1.0)
#2  0x00007fdd5578a435 _PyObject_GC_NewVar (libpython2.7.so.1.0)
#3  0x00007fdd5570eeaf PyTuple_New (libpython2.7.so.1.0)
#4  0x00007fdd49c8bc9e sip_api_build_result (siplib.so)
#5  0x00007fdd5411e881 _Z12_wxPoint_GetP7wxPoint (_core.so)
#6  0x00007fdd5411ebd5 meth_wxPoint_Get (_core.so)
#7  0x00007fdd557576f0 call_function (libpython2.7.so.1.0)
#8  0x00007fdd5575b35c PyEval_EvalCodeEx (libpython2.7.so.1.0)
#9  0x00007fdd556e3f4c function_call (libpython2.7.so.1.0)
#10 0x00007fdd556beea3 PyObject_Call (libpython2.7.so.1.0)
#11 0x00007fdd556cddb2 instancemethod_call (libpython2.7.so.1.0)
#12 0x00007fdd556beea3 PyObject_Call (libpython2.7.so.1.0)
#13 0x00007fdd5571a476 slot_sq_item (libpython2.7.so.1.0)
#14 0x00007fdd556e709b iter_iternext (libpython2.7.so.1.0)
#15 0x00007fdd556c026b PyIter_Next (libpython2.7.so.1.0)
#16 0x00007fdd55758c1e unpack_iterable (libpython2.7.so.1.0)
#17 0x00007fdd5575b35c PyEval_EvalCodeEx (libpython2.7.so.1.0)
#18 0x00007fdd5575b459 PyEval_EvalCode (libpython2.7.so.1.0)
#19 0x00007fdd55774b4f run_mod (libpython2.7.so.1.0)
#20 0x00007fdd55775d92 PyRun_FileExFlags (libpython2.7.so.1.0)
#21 0x00007fdd55776fa5 PyRun_SimpleFileExFlags (libpython2.7.so.1.0)
#22 0x00007fdd55788c50 Py_Main (libpython2.7.so.1.0)
#23 0x00007fdd550d1511 __libc_start_main (libc.so.6)
#24 0x000000000040066a _start (python2)
```

Is there anything I can provide that might help you reproduce this?

**Comment by RobinD42** [comment]
The stacktrace helps. I'll see if I can figure anything out. Is the for loop required for the error to manifest?

In the meantime, could you try it with a a3 preview snapshot build? There was a recent change in `Point.Get` (and similar methods in other classes) that could have had a positive impact on this issue as well.

**Comment by henniss** [comment]
The loop is necessary. It seems like it works fine most of the time, but occasionally (depending on memory management internals, I guess) choke. On my windows machine, that happens for `i=86`, every time, for example, although importing anything will change that. 

Did you run it with a normal Python build, or just the debug build? It seems this bug disappears when running in visual studio with the debugger attached, and I wonder if the debug build is causing something similar. 

I'll try the a3 snapshot tonight, and also see if a debug build of Python changes anything for me.

**Comment by henniss** [comment]
This seems to work fine with 4.0.0a3.dev3059. Thanks!
