### ISSUE TITLE
page.FindWidnowByName() in wx.Notebook

### ISSUE THREAD

**Issue by niki-sp** [wxWidgets/Phoenix#361]
[test_nb.py.txt](https://github.com/wxWidgets/Phoenix/files/1003927/test_nb.py.txt)

When testing notebook with 2 pages:
- Attached program prints None for `FindWidnowByName()` in wx Classic.
- In wx Phoenix a `wx.StaticText` from previous page is found.

**Comment by niki-sp** [comment]
Ubuntu 16.07 64bit wx 4.0.0.a2

**Comment by topic2k** [comment]
I would say that's the correct behaviour in Phoenix. The [doc ](https://wxpython.org/Phoenix/docs/html/wx.Window.html#wx.Window.FindWindowByName)say: 

> If parent is None, the search will start from all top-level frames 

so, if you add `parent=p2` to FindWindowByName, you get None as result.

**Comment by RobinD42** [comment]
Try `p2.FindWindow('abc')`

See https://wxpython.org/Phoenix/docs/html/MigrationGuide.html#findwindow-methods for more info.

**Comment by niki-sp** [comment]
i am using
`wx.Window.FindWindowById = lambda self, i: self.FindWindow(i)`
`wx.Window.FindWindowByName = lambda self, n: self.FindWindow(n)`
for running code in Classic & Phoenix.
Is there a better way?

**Comment by RobinD42** [comment]
Using the module level functions with the parent parameter should work the same in Classic and Phoenix:

`wx.FindWindowById(theID, self)`
