### ISSUE TITLE
wx.Wizard does not support ShowPage

### ISSUE THREAD

**Issue by davidfraser** [wxWidgets/Phoenix#369]
In wxPython 3, you could call `wizard.ShowPage(page)` to directly transition to a page. This method is not exposed in Phoenix (and it's quite hard to manipulate the next/previous controls to achieve exactly the same thing)

**Comment by RobinD42** [comment]
Thanks. It is marked as "implementation only" in the C++ source which is probably why it wasn't documented (which is why it didn't automatically added to Phoenix.) But I think it's useful so I'll look into getting it added.
