### ISSUE TITLE
PrintData class is missing `GetPaperSize` and `SetPaperSize` methods

### ISSUE THREAD

**Issue by mrjoes** [wxWidgets/Phoenix#374]
```
>> print(wx.version())
'4.0.0a2 osx-cocoa (phoenix)'
>> cfg = wx.PrintData()
<wx._core.PrintData object at 0x108eabcc8>
>> print(cfg.GetPaperSize())
*** AttributeError: 'PrintData' object has no attribute 'GetPaperSize'
>> print(cfg.SetPaperSize)
*** AttributeError: 'PrintData' object has no attribute 'SetPaperSize'
```

According to the documentation, they should be present: https://wxpython.org/docs/api/wx.PrintData-class.html

Just in case, `SetPaperId` is there, but I need to set a custom page size.

**Comment by RobinD42** [comment]
I'm adding the wrappers for those methods, however be aware that there is this comment in the C++ code:

```
// Not used yet: confusable with paper size
// in wxPageSetupDialogData
```

So there may not be any actual functionality there yet.  Or the comment could be out of date.
