### ISSUE TITLE
"sudo python build.py install" fails due to multiple "linking [file path] -> [file name] error: [Errno 17] File exists"

### ISSUE THREAD

**Issue by krichter722** [wxWidgets/Phoenix#381]
After building with `python build.py dox && python build.py build_wx --jobs=4 && python build.py etg --nodoc && python build.py sip && python build.py build_py --jobs=4` both `sudo python build.py install` and `sudo python setup.py install` fails due to multiple errors in the form of

    linking [file path] -> [file name]
    error: [Errno 17] File exists

e.g.

    linking /usr/local/lib/python2.7/dist-packages/wx/libwx_gtk2u_stc-3.0.so -> libwx_gtk2u_stc-3.0.so.0
    error: [Errno 17] File exists

existing files causing trouble include at least `/usr/local/lib/python2.7/dist-packages/wx/libwx_gtk2u_stc-3.0.so.0 /usr/local/lib/python2.7/dist-packages/wx/libwx_gtk2u_ribbon-3.0.so.0 /usr/local/lib/python2.7/dist-packages/wx/libwx_baseu_net-3.0.so.0 /usr/local/lib/python2.7/dist-packages/wx/libwx_gtk2u_webview-3.0.so.0 /usr/local/lib/python2.7/dist-packages/wx/libwx_baseu_xml-3.0.so.0 /usr/local/lib/python2.7/dist-packages/wx/libwx_gtk2u_richtext-3.0.so /usr/local/lib/python2.7/dist-packages/wx/libwx_gtk2u_xrc-3.0.so.0 /usr/local/lib/python2.7/dist-packages/wx/libwx_gtk2u_aui-3.0.so.0 /usr/local/lib/python2.7/dist-packages/wx/libwx_gtk2u_aui-3.0.so /usr/local/lib/python2.7/dist-packages/wx/libwx_gtk2u_gl-3.0.so /usr/local/lib/python2.7/dist-packages/wx/libwx_gtk2u_core-3.0.so.0 /usr/local/lib/python2.7/dist-packages/wx/libwx_gtk2u_media-3.0.so /usr/local/lib/python2.7/dist-packages/wx/libwx_baseu-3.0.so.0`. Removing one file causes the installation to proceed one or more steps further so that the next existing file causes an error.

experienced with wxPython-4.0.0a2-65-g85f11ff1

**Comment by RobinD42** [comment]
Try removing the previous install before installing again.

**Comment by RobinD42** [comment]
Also, all those separate commands can be done in a single command line, like this :

```
python build.py dox build_wx --jobs=4 etg --nodoc sip build_py 
```

Like your compound commands it will terminate early if there is an error in any of the subcommands.

**Comment by krichter722** [comment]
> Try removing the previous install before installing again.

That's the workaround I'm using. Please note that I'd like to see the issue fixed or the install to fail with a verbose error message (e.g. one suggesting that installation is only supported after removal of previous installations + instructions)

> Also, all those separate commands can be done in a single command line, like this :
> 
>     python build.py dox build_wx --jobs=4 etg --nodoc sip build_py 
>
> Like your compound commands it will terminate early if there is an error in any of the subcommands.

That's nice to know, thank you!

**Comment by mesalu** [comment]
Closing. Old and inactive.
Please reopen if necessary.
