### ISSUE TITLE
warnings.simplefilter() before import wx

### ISSUE THREAD

**Issue by niki-sp** [wxWidgets/Phoenix#385]
[test_warn.py.txt](https://github.com/wxWidgets/Phoenix/files/1057889/test_warn.py.txt)
If `warnings.simplefilter('ignore')` is before `import wx` then `wxPyDeprecationWarning` is visible.
Tested on Ubuntu 17.04 64bit

**Comment by RobinD42** [comment]
Because importing wx does a `warnings.simplefilter('default', wxPyDeprecationWarning)` which overrides the 'ignore' for that warning class. If you want to ignore all then you'll need to do it after the import of wx.

If you would like to propose something else I'll gladly review a PR.

**Comment by niki-sp** [comment]
Maybe after beta warning control should be left to Python -W
