### ISSUE TITLE
Printing or escaping "&" not working in wx.RadioBox but OK in wx.RadioButton

### ISSUE THREAD

**Issue by HelioGuilherme66** [wxWidgets/Phoenix#39]
I was not able to test with C++ but with all versions of wxPython it is not possible to escape the "&" by using the "&&" in radio items labels when in a wx.RadioBox. If the radio items are built with wx.RadioButton the "&" are processed as special function, or printed by using "&&".
Below are screenshots for the different wxPython versions I tested. (I really need to print values like &{dictionary}).
![radio_box_no_double_ampersand_281201](https://cloud.githubusercontent.com/assets/2866630/13440481/2c60ec2a-dfea-11e5-9817-aef4ab633cc7.png)
![radio_box_no_double_ampersand_295](https://cloud.githubusercontent.com/assets/2866630/13440490/3266d3a0-dfea-11e5-99e3-3d33d8849900.png)
![radio_box_no_double_ampersand_302](https://cloud.githubusercontent.com/assets/2866630/13440495/3a3472ae-dfea-11e5-83a2-4cd7e10e8614.png)
![radio_box_no_double_ampersand_303](https://cloud.githubusercontent.com/assets/2866630/13440508/4a2a53f4-dfea-11e5-916c-00658e2818cc.png)

**Comment by swt2c** [comment]
wxWidgets issue (as you reported):
http://trac.wxwidgets.org/ticket/17419

**Comment by HelioGuilherme66** [comment]
@swt2c @RobinD42 
Thank you for having this fixed.
Here is the evidence :)
![imagem](https://user-images.githubusercontent.com/2866630/35200826-6c72e9b0-ff0c-11e7-935a-be4a3151d1ca.png)

**Comment by swt2c** [comment]
Sorry it took almost two years.  :-)  It had been fixed upstream for a while, just needed a poke to be backported.
