### ISSUE TITLE
No image handler for type 9 defined

### ISSUE THREAD

**Issue by DietmarSchwertberger** [wxWidgets/Phoenix#395]
Today I upgraded one of my installations to the latest snapshot and got problems when starting wxGlade.

wxGlade loads its icons from xpm files. The icons are displayed in the main window and as icons in the tree control.

The first 20 still get loaded OK. The following fail.
The error message is "No image handler for type 9 defined".
Honestly, I don't know where the bug is raised or logged exactly.

Printing the Size after loading via wx.Bitmap(path, wx.BITMAP_TYPE_XPM) gives (0,0) when failing.

This snapshot is OK: 99cc9cc
  wxPython-4.0.0a4.dev3135+99cc9cc-cp35-cp35m-win_amd64.whl    2017-06-08 06:47

This one fails: 18e35f5
  wxPython-4.0.0a4.dev3141+18e35f5-cp35-cp35m-win_amd64.whl    2017-06-09 06:56

(The installation where I first found the problem is a 32 bit Python 3.5, so it should not be related to 32 vs. 64 bit.)

From looking at the commit messages, I could not see something obvious.
I tried to prepare a minimum sample which just loads the icons, but that's working fine.

Sorry that I can't provide more details. If the solution is not obvious for you, I probably need to build myself going through all commits.

Regards,
Dietmar

**Comment by Metallicow** [comment]
Make a sample app and attach a couple of icons(one good and one bad)

**Comment by DietmarSchwertberger** [comment]
I tried. It's not a question of good vs. bad icons. If I make a script loading all the icons several times, that's working fine. It looks like a more complex interaction....
I tried adding wx.InitAllImageHandlers() at the start, but that does not make a difference.

The full application can be downloaded from https://bitbucket.org/wxglade/wxglade/get/default.zip
or just be cloned from https://bitbucket.org/wxglade/wxglade

After downloading, execute wxglade.py
The main palette window will then display some icons. The rest of the icons will be empty and the bug reported.


I will try to prepare a low complexity application, but my confidence about that is not too high.

**Comment by RobinD42** [comment]
`wx.BITMAP_TYPE_XPM` is type 9, so it is at least trying to use the right handler. The confusing part is that some load and some don't...  Is it always the same ones that fail or is it random? Anything different about the structure of the files that fail? How about the one before the ones that fail?  (I'm thinking that perhaps something is causing the handler to refuse to load the xpm files, perhaps some bad state that the handler gets into when loading the previous ones...)

**Comment by Metallicow** [comment]
Yeah that is strange. Confirmed nothing wrong with the XPMs. Only does this with Phoenix(Classic loads fine)
Maybe look at the commits starting with `wxPyReinitializeModules` stuff.....?!?!?
I'm not sure what is causing it...?

**Comment by DietmarSchwertberger** [comment]
I've found a workaround:
Things are OK if I call wx.InitAllImageHandlers() before loading of each file. Calling it once at program start did not fix it.

It's always that the first 20 load OK.
Even if I always load exactly the same xpm file, the problem is the same.

The files are loaded with wx.Bitmap(path, wx.BITMAP_TYPE_XPM). That's where the info about the type 9 comes from.
If I try wx.Bitmap(path, wx.BITMAP_TYPE_ANY) then I get "Unknown image data format" instead after loading the 20 first files.

So it seems that the image handler registry gets overwritten by something else, maybe when the data structure before the registry gets written and is too long.

I just tried the latest snapshot with Python 3.4 32 bit and the problem still persists. (Btw. there are no 3.5 snapshots online).

**Comment by DietmarSchwertberger** [comment]
It certainly has to do with `wxPyReinitializeModules`.
When I add an `import wx.adv` anywhere before creating the App, then the problem is gone.

**Comment by Metallicow** [comment]
@DietmarSchwertberger Ok. Next question. Will it load a large number of icons with the `import adv`. 
Ex. 10000000 XPMs and not choke...?

**Comment by DietmarSchwertberger** [comment]
The attached sample illustrates the problem:
[XPM.zip](https://github.com/wxWidgets/Phoenix/files/1077785/XPM.zip)


```
import wx
import sys, os

print(sys.version)
print(wx.VERSION)

app = wx.App()

path = os.path.join(sys.path[0],"calendar_ctrl.xpm")
bmp = wx.Bitmap( path, wx.BITMAP_TYPE_XPM )
print(bmp.Size)

import wx.adv
bmp = wx.Bitmap( path, wx.BITMAP_TYPE_XPM )
print(bmp.Size)

wx.InitAllImageHandlers()
bmp = wx.Bitmap( path, wx.BITMAP_TYPE_XPM )
print(bmp.Size)

app.MainLoop()
```


The second bitmap is of size (0,0); after calling InitAllImageHandlers, it's loaded OK again:


```
d:\python\python34\python.exe XPMBug.py
3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:43:06) [MSC v.1600 32 bit (Intel)]
(4, 0, 0, 'a4.dev3150+888e0ef')
(21, 21)
(0, 0)
(21, 21)
```

**Comment by RobinD42** [comment]
> (Btw. there are no 3.5 snapshots online).

The build was still running at the time of that message.

> The second bitmap, after import wx.adv is of size (0,0); after calling InitAllImageHandlers, it's loaded OK again:

Ok, thanks.  I'll dig into it this evening.
