### ISSUE TITLE
wx.RA_HORIZONTAL and wx.RA_VERTICAL missing in Docs

### ISSUE THREAD

**Issue by Metallicow** [wxWidgets/Phoenix#400]
It appears that `wx.RA_HORIZONTAL` and `wx.RA_VERTICAL` are missing from the [docs](https://wxpython.org/Phoenix/docs/html/wx.RadioBox.html#styles-window-styles).

It looks like `wx.RA_HORIZONTAL` is an alternate name for `wx.RA_SPECIFY_COLS` and
`wx.RA_VERTICAL` is an alternate name for `wx.RA_SPECIFY_ROWS`.
Is this right?

And if so, shouldn't these be documented on the RadioBox page as being so.
Zen: There should be one-- and preferably only one --obvious way to do it.

**Comment by RobinD42** [comment]
No. The `wx.RA_HORIZONTAL` and `wx.RA_VERTICAL` names are present only for backwards compatibility with very old code.  The `wx.RA_SPECIFY_*` names are the new and correct flag names to use, and so they are the ones that are documented.
