### ISSUE TITLE
wx.SL_TICKS and wx.SL_BOTH missing from docs

### ISSUE THREAD

**Issue by Metallicow** [wxWidgets/Phoenix#401]
wx.SL_TICKS and wx.SL_BOTH
They are missing from the docs https://wxpython.org/Phoenix/docs/html/wx.Slider.html#styles-window-styles
They appear in the unittests
https://github.com/wxWidgets/Phoenix/blob/master/unittests/test_slider.py#L44

**Comment by RobinD42** [comment]
`wx.SL_TICKS` is now known as `wx.SL_AUTOTICKS`

**Comment by infinity77** [comment]
@swt2c : wx.SL_AUTOTICKS and wx.SL_BOTH are very well defined in the documentation as of now.
