### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by Korijn** [wxWidgets/Phoenix#409]
Hi, I'm working on a conda package for wxPython Phoenix over at https://github.com/conda-forge/staged-recipes/pull/3073 and the review committee is asking for some clarification on licensing. Basically this is their request:

> Can you include the license file in the Python source code and please make sure the license file is added to the `MANIFEST.in` so it shows up on PyPI?

If it's too much hassle for you, can you explain to me what to do so I can open a PR for you?

I believe this is the license file we're talking about: https://github.com/wxWidgets/wxWidgets/blob/master/docs/licence.txt

Is that correct?

**Comment by RobinD42** [comment]
Yes, that is the correct license, and I thought it was being included.  I'll check into why it isn't. (Probably due to some change that was done in the build script...)
