### ISSUE TITLE
wx.lib.plot.PolySpline() crashes if not enough data

### ISSUE THREAD

**Issue by BrendanSimon** [wxWidgets/Phoenix#413]
`wx.lib.plot.PolySpline()` causes crashes if not enough data is supplied.

* a dataset that contains 1 or 2 points will causes a crash (using OS X Sierra 10.12.5 and wxPython 4.0.0a3)
* a dataset of 3 or points plots ok.
* a dataset with 0 points also plots ok (i.e. an empty plot).

Using `PolyLine()` does not cause any crashes (even if only 1 point is supplied).

Should these functions raise an exception if there is not enough data?

At the very least `PolySpline()` should fail silently/gracefully if not enough data (e.g. do nothing)

**Comment by RobinD42** [comment]
It looks like there is an assert error for the length of the points list on some platforms but not all.  I'll go ahead and add a check in PolySpline.
