### ISSUE TITLE
AttributeError: 'module' object has no attribute 'CONFIG_USE_LOCAL_FILE'

### ISSUE THREAD

**Issue by esitarski** [wxWidgets/Phoenix#415]
Happens with:

    self.config = wx.Config(appName="MyApp",
        vendorName="MyCompany",
	style=wx.CONFIG_USE_LOCAL_FILE)

Is wx.CONFIG_USE_LOCAL_FILE defined somewhere else in Phoenix?

**Comment by mesalu** [comment]
It looks like all the flags from wxWidget's config are missing. 
Phoenix has to jump through some hoops to get wxConfig wrapped, as wxWidget's wxConfig is actually just a macro used to get the platform's specialized wxConfig class. 

That being said, wxCONFIG_USE_LOCAL_FILE (and wxCONFIG_USE_GLOBAL_FILE) is the default mode for wx.Config:
```CPP
    class wxConfig : wxConfigBase
    {
    public:
        wxConfig(const wxString& appName = wxEmptyString,
                 const wxString& vendorName = wxEmptyString,
                 const wxString& localFilename = wxEmptyString,
                 const wxString& globalFilename = wxEmptyString,
                 long style = wxCONFIG_USE_LOCAL_FILE | wxCONFIG_USE_GLOBAL_FILE);
```

so you should be okay while we dig into the missing flags.

**Comment by esitarski** [comment]
Appreciate the quick response.  I am porting some code with CONFIG_USE_LOCAL_FILE.  Now that I know that CONFIG_USE_LOCAL_FILE is the default I will go with that.

**Comment by RobinD42** [comment]
It's still an issue that needs to be solved.  Reopening.

**Comment by mesalu** [comment]
Pull Request submitted.
