### ISSUE TITLE
"label" vs "bitmap" in wx.StaticBitmap and wx.BitmapButton parameters

### ISSUE THREAD

**Issue by esitarski** [wxWidgets/Phoenix#420]
In Phoenix, wx.StaticBitmap takes parameter "label" for the bitmap, and wx.BitmapButton takes "bitmap".
In Classic, both took parameter "bitmap".

This is confusing because In the rest of Phoenix, bitmap means a wx.Bitmap.  If you pass text to the wx.StaticBitmap, you get:

    b = wx.StaticBitmap(frame, label=u'')
    overload 1: too many arguments
    overload 2: argument 'label' has unexpected type 'unicode'

Furthering the confusion.

Is there a reason for the change?  Any chance we could use "bitmap" for both?

**Comment by RobinD42** [comment]
Generation of the wrapper code is driven by how the APIs are documented in wxWidgets, and they use "label" there. I expect that there was some historical or consistency reason for it, but I also expect that I had manually changed it for Classic. So I'll do the same for Phoenix.
