### ISSUE TITLE
Timer causes hard crash during shutdown

### ISSUE THREAD

**Issue by AndersMunch** [wxWidgets/Phoenix#429]
A timer that triggers during shutdown causes Python to crash hard with no traceback and no useful error message.

Version: "4.0.0a3 msw (phoenix)"

To reproduce, run this:

```python
import wx
    
class BogeyFrame(wx.Frame):
    def __init__(self):
        wx.Frame.__init__(self, None, -1)
        wx.StaticText(self, -1, "Running a timer")
        self._timer = wx.Timer(self)
        self.Bind(wx.EVT_TIMER, self.timer_event)
        self._timer.Start(1, wx.TIMER_CONTINUOUS)

    def timer_event(self, event):
        pass

if __name__=='__main__':
    app = wx.App()
    fr = BogeyFrame()
    fr.Show(True)
    app.MainLoop()
```

When closing, this usually causes a "python.exe stopped working" MSWin message. It's timing-sensitive, so it might not; adding more controls makes the failure more likely (because shutdown takes longer).

Note that if "fr = BogeyFrame(); fr.Show(True)" is replaced by "BogeyFrame().Show(True)", removing the extra reference and causing the Frame to be cleaned up a little sooner, then it doesn't crash.

**Comment by RobinD42** [comment]
It also doesn't crash when running in the C++ debugger so I can't see for sure what is happening...

Of course you can avoid it by having an `EVT_CLOSE` handler that does something like this, which is a good idea anyway:

```python
    def OnClose(self, evt):
        if self._timer:
            self._timer.Stop()
            self._timer = None
        evt.Skip()
```

**Comment by RobinD42** [comment]
It finally crashed while running in the debugger, and it is as I thought. There is a timer notification that happens between the destruction of the frame and the end of the program. The timer C++ code has no way to ensure that the target of the event still exists, so you'll need to take care of it with a close handler as I mentioned.  (It's also a good idea to do the same for `wx.TaskBarIcon`.)

In general you can't ever depend on exactly when Python objects are destroyed, either from reference counts going to zero or from the garbage collector. If you toss in the can of worms of having the Python objects being wrappers for C++ objects, and sometimes the C++ objects having to hold extra references to the Python objects, then it's always better to be safe than sorry and do a little work yourself to ensure that stray events can't get to windows after they are destroyed.

**Comment by RobinD42** [comment]
Closing as "wontfix" because I don't think anything can be done. (I'd be happy to be proven wrong however.)

**Comment by AndersMunch** [comment]
I thought wxPython had a general solution to the window/event lifetime issue.  I mean, you don't see crashes because a keyboard event arrives a millisecond after the Window it goes to is destroyed.  Is this particular to Timer events?  Or should I expect the same thing to happen for a custom event from a long-running background thread? 

I'd like to offer ideas but I don't understand the problem well enough. 

Here's the motivation for changing something: This was extremely difficult to debug. There's no traceback, no error message, and every time I removed half the code to close in on the problem, the problem became half as frequent.  Whittling a large application down to a reproducing sample that didn't even consistently reproduce it, took me the better part of a day.

This is for code that worked in Classic.  (Unless I was just lucky that it happened extremely rarely.)

If only the problem produced some scrap of googlable information that could hint at a Timer lifetime issue, then even if it did crash after that, then that would be something.

**Comment by Metallicow** [comment]
@AndersMunch I'd like to see a better solution also, but I as you also, have learned the hard way and try to recognize certain things. I lack the ability to quite understand how to fix this issue codewise.
Most often I find myself writing something like this to workaround closing crashes in other apps. sometimes not exactly tied to a timer as far as I know. Yep, It's a pain in the ass to debug(usually done line by line with a print statement).
```python
# Kill all timers first. and handle the rest of the possibilities with this shit.
if not self.someObject:  # Avoid a etc. PyThisOrThatError, PyAssertionError, PyDeadObjectError, RunTimeError.
    return
```

**Comment by AndersMunch** [comment]
@Metallicow not really arguing, I can and will fix this in my own code with EVT_CLOSE handlers. The problem is that someone else is bound to run into this as well, and be as mystified as I was by a bug that cannot be debugged even with print statements. 

@RobinD42 I'm starting to get the impression that `owner` is a misnomer in the context of a Timer. Whereas a `wx.Window` parent destroys it when being destroyed itself, apparently the owner of a timer doesn't destroy it. So in what sense is it any kind of owner? Is it just the event recipient and nothing else? There may be room for improvement of the `wxTimer` docs.

**Comment by RobinD42** [comment]
> I thought wxPython had a general solution to the window/event lifetime issue. 

In the general case, yes. This is not a general case however. As @Metallicow surmised, there isn't the same kind of ownership relationship with timers as there is with child windows, menubars, etc. The `owner` in this case is more like `thing_to_send_the_event_to`

Another non-general case in play here is the order that these events can be delivered. A Frame's actual destruction will normally be delayed until the event loop enters into a no-events-pending state. But at least on Windows, IIRC,  this is about the same priority that timer events will be delivered so it's easy to imagine that those streams could get crossed.
