### ISSUE TITLE
Suggest adding wxDocs and wxDemo to scripts

### ISSUE THREAD

**Issue by GadgetSteve** [wxWidgets/Phoenix#437]
Currently for wxPython Phoenix the user has to locate the appropriate "Extras" package at https://sourceforge.net/projects/wxpython/files/wxPython4/extras/ download & unpack it.

This is a shame as the new documentation and demos package are invaluable _especially to new users_ 
 and is usually the first step in isolating potential bug reports, so making them hard to find is the last thing that is needed.

What I would like to suggest is adding to the Phoenix package two scripts to be automatically installed in the appropriate location:

 - wxDocs - when first run _possibly offer to_ download & unpack to a suitable location the docs package, subsequent runs _identified by the presence of the docs_ check if the docs version matches the current wx version, (if not offer to download), and open the docs at the root.  If the user declines the offline download direct them to the web documents.
 - wxDemo - If _the matching version_ demos package not available _offer to_ download and install to an appropriate location the demos package. Start the demos package.

_(As an aside while on the "Extras" page for wxPython 4 the user is prompted "Looking for the latest version? Download wxPython3.0-win64-**3.0.2.0**-py27.exe (16.8 MB)" or similar)_

**Comment by RobinD42** [comment]
Interesting idea, I'll give it some thought.  If you feel like putting together a PR for it please do.

> (As an aside while on the "Extras" page for wxPython 4 the user is prompted "Looking for the latest version? Download wxPython3.0-win64-3.0.2.0-py27.exe (16.8 MB)" or similar)

I noticed that too.  Not sure why and I haven't had time to chase it down yet. Using SourceForge this way was kind of a last minute decision as my regular server was getting throttled down to a few dozen kbps (while the hosting provider claims they don't throttle) and I was desperate for someplace else to put the files. I've got a new hosting provider now so maybe I'll put them there...

**Comment by GadgetSteve** [comment]
Wouldn't https://github.com/wxWidgets/Phoenix/releases/wxPython-4.... be the natural place to put them?

The only "downsides" of putting them within the releases would be that the build process would also have to build the documentation, (I think it does already), then bundle it & the demos and, _potentially,_ needing to have Docs/Demos only releases if an issue with either is found that is serious enough to warrant a new release when potentially the code hasn't changed.

**Comment by RobinD42** [comment]
Hmm... I always thought that github releases were just source tarballs automatically created from a tag. I didn't realize other files could be put there too. I'll read up on that.

**Comment by GadgetSteve** [comment]
Robin, https://help.github.com/articles/creating-releases/ step 7. Once you have tagged a release you can add more information and release files.

**Comment by Ryex** [comment]
You can also have build bots upload the release builds for you with a
relatively simple http request.
https://developer.github.com/v3/repos/releases/#upload-a-release-asset

**Comment by GadgetSteve** [comment]
Made a start towards the required functionality but it would be **much** easier if there was a direct download link, (SourceForge doesn't allow this GitHub does).

**Comment by RobinD42** [comment]
There are a couple potential issues that I see with using GitHub to host extra downloads. 

1. The tarball automatically made by GitHub from the release tag does not include everything that's included in the tarball I create, so people will not be able to use it very easily. I could upload my own tarball but then there would be 2 and there would likely be confusion about why and which should be used. So IMO it would be better to avoid

2. I need subfolders for the linux wheels, and it doesn't look like the GitHub interface supports that, so there would need to be a separate place for those anyway, so it may as well host the rest of it too.

So instead I've set up a new server to host the extras which seems to have good bandwidth with no practical limits, and enough disk space to last for quite a while: https://extras.wxpython.org/wxPython4/. I'll likely move the Phoenix snapshots and tools folders there too eventually.

**Comment by GadgetSteve** [comment]
Thanks @RobinD42 I will target that in a PR soon.
