### ISSUE TITLE
Case sensitive ordering in API docs

### ISSUE THREAD

**Issue by butscher** [wxWidgets/Phoenix#440]
Only a very minor issue but the ordering of lists in the documentation is case sensitive.

E. g. for class summary on https://wxpython.org/Phoenix/docs/html/wx.1moduleindex.html this results in the slightly irritating order "..., ListBox, ..., ListView, Listbook, ..."

Probably there are only one or two items in the whole docs affected by this.

**Comment by RobinD42** [comment]
See also sorting-related item in #292

**Comment by RobinD42** [comment]
Closed by #618
