### ISSUE TITLE
wx.FileDropTarget does not work.

### ISSUE THREAD

**Issue by maskedw** [wxWidgets/Phoenix#448]
Operating system: Windwos10 64bit  
wxPython version: 4.0.0b1
Stock or custom build: Stock
Python version:  3.5 32bit, 64bit, 36 32bit, 64bit
Stock or custom build: Stock
Description of the problem:
`wx.FileDropTarget` does not work.

The sample application also does not work.
demo/GridDragAndDrop.py
demo/DragAndDrop.py

The minimum source code is shown below.

```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import wx


class MyFileDropTarget(wx.FileDropTarget):
    def __init__(self):
        super().__init__()

    def OnDropFiles(self, x, y, filenames):
        print('OnDropFiles!! {}'.format(filenames))


class MyFrame(wx.Frame):
    def __init__(self):
        super().__init__(None)
        self.SetTitle("wxPython Frame")
        self.SetSize((300, 200))
        panel = wx.Panel(self)
        sizer = wx.BoxSizer(wx.VERTICAL)
        label = wx.StaticText(panel, label = "Hello World")
        sizer.Add(label, 0, wx.ALL, 5)
        panel.SetSizer(sizer)

        dt = MyFileDropTarget()
        self.SetDropTarget(dt)

app = wx.App()
window = MyFrame()
window.Show(True)
app.MainLoop()
```

**Comment by DietmarSchwertberger** [comment]
Works fine for me on Windows 7, except that OnDropFiles should return True or False.
Tested on Windows 7, 64 bit with Python 3.5.1, wx (4, 0, 0, 'b1')

**Comment by maskedw** [comment]
From mouse double click:  work  
From cmd.exe: work  
From cmd.exe(Admin): not work  

Does it work when running with administrator privileges?

**Comment by DietmarSchwertberger** [comment]
Try to run the Explorer as admin as well. Then it should work.
If the application and the Explorer have different rights, then I would expect it to fail. I don't think that can be changed on Windows.

**Comment by maskedw** [comment]
Why does not it work as an administrator?

**Comment by DietmarSchwertberger** [comment]
see e.g. here:
https://blogs.msdn.microsoft.com/patricka/2010/01/28/q-why-doesnt-drag-and-drop-work-when-my-application-is-running-elevated-a-mandatory-integrity-control-and-uipi/

**Comment by maskedw** [comment]
Thank you. This is not an application problem.
