### ISSUE TITLE
enhancement request: ListCtrl with LC_VIRTUAL and LC_ICON flags

### ISSUE THREAD

**Issue by kg-2** [wxWidgets/Phoenix#455]
The LC_VIRTUAL flag is indispensable for dealing with large amounts of data. I'm not sure how feasible it is, but extending this feature to lists created in LC_ICON mode would provide developers with considerably more flexibility when choosing how to display hundreds of thumbnails.

**Comment by RobinD42** [comment]
This would require changes or additions to wxWidgets, so you should file this request there. https://github.com/wxWidgets/wxWidgets or https://trac/wxwidgets.org/
