### ISSUE TITLE
Setting item data in ListCtrl

### ISSUE THREAD

**Issue by SweRavn** [wxWidgets/Phoenix#467]
**Operating system**: Windows 10 64 bit
**wxPython version**: 4.0.0a4.dev3167+3bb2a52 msw (phoenix)
**Stock or custom build**: Anaconda 4.4.0
**Python version**: 3.6 64 bit
**Stock or custom build**: Anaconda 4.4.0

**Description of the problem**:
If too large integer is given to SetItemData for a ListCtrl (maybe other controls also, I have not checked) some random (but fixed during the execution and maybe also between executions) large number is returned. Maybe it is not possible to assign such a large integers, but if it is not possible, a warning should be raised or exception.

The code blow will generate the following output (or some other number):
Data set: 143571234234, data get: 18446744073709551615
Data set: 234567456733, data get: 18446744073709551615

```python
import wx

class MainFrame(wx.Frame):
    def __init__(self):
        super().__init__(None, -1, "My app", size=(1024, 768))
        self._panel = wx.Panel(self)
        hbox = wx.BoxSizer(wx.HORIZONTAL)
        self.list = wx.ListCtrl(self._panel, wx.ID_ANY,
                                style=wx.LC_REPORT 
                                | wx.LC_EDIT_LABELS
                                | wx.LC_SORT_ASCENDING
                                )
        self.list.AppendColumn("C1", width=110)
        self.list.AppendColumn("C2", width=110)

        hbox.Add(self.list, 1, wx.LEFT|wx.TOP|wx.GROW)

        self._panel.SetSizer(hbox)
        
        data = {143571234234: ('first 1', 'first 2'),
                234567456733: ('second 1', 'second 2'),}
        for key, row in data.items():
            index = self.list.InsertItem(1000000, row[0])
            self.list.SetItem(index, 1, row[1])
            self.list.SetItemData(index, key)
            print("Data set: {}, data get: {}".format(key, self.list.GetItemData(index)))

if __name__ == "__main__":
    print("Wx version: %s", wx.version())
    app = wx.App(False)
    main_frame = MainFrame()
    main_frame.Show()
    app.MainLoop()
```

**Comment by RobinD42** [comment]
Yep, it is an overflow problem. In addition the types used for the set and get are not the same sign, otherwise the value returned from `GetItemData` would have been -1 and it might have been a better clue as to what was happening.

Currently SIP is ignoring integer type overflows. I'm checking into that, and in the meantime I'll add an explicit range check in `SetItemData`.

**Comment by RobinD42** [comment]
Newer SIP now handles integer overflows. See #589
