### ISSUE TITLE
GetVirtualSize in ScrolledWindowBase returns tuple

### ISSUE THREAD

**Issue by robmcmullen** [wxWidgets/Phoenix#474]
**Operating system**: linux
**wxPython version**: git
**Stock or custom build**: custom
**Python version**: 2.7.13
**Stock or custom build**: custom

**Description of the problem**:

```python
app = wx.App()

frame = wx.Frame(None, -1, "Test", size=(400,400))
s = wx.ScrolledWindow(frame, -1)
w = wx.Window(frame, -1)
frame.Show(True)
print("scrolled GetVirtualSize: %s" % type(s.GetVirtualSize()))
print("window GetVirtualSize: %s" % type(w.GetVirtualSize()))
app.MainLoop()
```
produces:
```
scrolled GetVirtualSize: <type 'tuple'>
window GetVirtualSize: <class 'wx._core.Size'>
```
I don't know enough (anything!) about sip to come up with a patch, but the issue seems to be that ``sip_corewxWindow.cpp`` uses
```
            Py_BEGIN_ALLOW_THREADS
            sipRes = new  ::wxSize(sipCpp->GetVirtualSize());
            Py_END_ALLOW_THREADS

            if (PyErr_Occurred())
                return 0;

            return sipConvertFromNewType(sipRes,sipType_wxSize,NULL);
```
while ``sip_core_ScrolledWindowBase.cpp`` has:
```
            Py_BEGIN_ALLOW_THREADS
            sipCpp->GetVirtualSize(&x,&y);
            Py_END_ALLOW_THREADS

            if (PyErr_Occurred())
                return 0;

            return sipBuildResult(0,"(ii)",x,y);
```

**Comment by mesalu** [comment]
the sip code is generated, I could be wrong but I don't think any of it is hand created*

Instead Phoenix uses the etg files (Extensible Tweaker Generator I believe). It's possible there is an automatic conversion implemented to/from tuple in one of these classes. That'd be a question for @RobinD42. 

Anyways, a place to start would be to determine if anything is actively being done in etg, and work from there to conform these method calls to desired behavior.

* Some raw code is injected from handwritten python strings in the aforementioned etg
