### ISSUE TITLE
wxToolBar.AddTool variants are differing for optional arguments (shortHelp vs. shortHelpString)

### ISSUE THREAD

**Issue by jensgoe** [wxWidgets/Phoenix#475]
**Description of the problem**:

The method AddTool for a ToolBar currently expects different names for some optional arguments:

- shortHelp vs. shortHelpString
- longHelp vs. longHelpString

```python
# Put code sample here
toolbar.AddTool(wx.NewId(), "My Label", wx.Bitmap(32, 32), shortHelp="My short help")
toolbar.AddTool(wx.NewId(), "My Label", wx.Bitmap(32, 32), wx.Bitmap(32, 32), shortHelpString="My short help")
```

I would prefer using shortHelp and longHelp. I looked into the code and noticed these differences in wxWidgets too. Maybe it has to be modified there.

**Comment by mesalu** [comment]
Yep, looks like this stems from inconsistencies in wxWidgets itself. Luckily we can tweak these parameters. 
I'll push a change in a few hours to fix this, corrected keyword arguments will be in the next release, or in an updated build any point after that fix is merged.

~~Mesalu
