### ISSUE TITLE
The 'filemenu' does not display when i run the right code,  on macOS.

### ISSUE THREAD

**Issue by Raymon9** [wxWidgets/Phoenix#476]
**Operating system**:macOS Sierra 10.12.6
**wxPython version**:4.0.0b1
**Stock or custom build**:custom
**Python version**:Python 3.6.2
**Stock or custom build**:custom

**Description of the problem**:
The 'filemenu' does not display when i run the code,  which i copied from the wiki of wxpython.  My laptop's system is macOS.  The problem is not exist when I asked others for help, who use the Windows system. Is this a bug or any other problem? Thank you.
(http://wx4.sinaimg.cn/mw690/4bcb5221ly1firpu66lnsj20sg0wgwha.jpg)

```python
#!/usr/bin/env python3
#-*- coding:utf-8 -*-

import wx

class MainWindow(wx.Frame):
    def __init__(self, parent, title):
        wx.Frame.__init__(self, parent, title=title, size=(200, 100))
        self.control = wx.TextCtrl(self, style=wx.TE_MULTILINE)
        self.CreateStatusBar()
        filemenu = wx.Menu()

        filemenu.Append(wx.ID_ABOUT, '&About', 'Information about this program')
        filemenu.AppendSeparator()
        filemenu.Append(wx.ID_EXIT, '&Exit', 'Terminate the programe')

        menuBar = wx.MenuBar()
        menuBar.Append(filemenu, '&File')
        self.SetMenuBar(menuBar)
        self.Show(True)

app = wx.App(False)
frame = MainWindow(None, 'Sample editor')
app.MainLoop()
```

**Comment by RobinD42** [comment]
On Mac the menu items for `wx.ID_EXIT`, `wx.ID_ABOUT` and a few others are automatically moved to their *correct* place (according to Apple UI guidelines) on the application's menu. Until you make an app bundle for your application that will be the "Python" menu next to the apple menu. (With an app bundle then it will be the name you give your application.)

**Comment by Raymon9** [comment]
Oh, I feel quite ashamed，it looks like a stupid question. Thank you very much for your quick reply.

**Comment by jconti13** [comment]
I was confused by the same thing, don't feel bad.  It actually looks like appending a menu item with wx.ID_EXIT is simply ignored.  Simply adding:
```
menubar` = wx.MenuBar()
self.SetMenuBar(menubar)

```
Seems to be enough to get the default items including a "Quit" item to appear under the "Python" menu.
