### ISSUE TITLE
Install on debian stretch (python 3.5)

### ISSUE THREAD

**Issue by damufo** [wxWidgets/Phoenix#477]
**Operating system**: debian 9 stretch
**wxPython version**: https://wxpython.org/Phoenix/snapshot-builds/wxPython-4.0.0b2.dev3307+d7cae3f.tar.gz
**Stock or custom build**:
**Python version**: 3.5.3
**Stock or custom build**:

**Description of the problem**:
 pip3 install --upgrade --pre -f https://wxpython.org/Phoenix/snapshot-builds/ wxPython 

Debian 9 stretch no has package python-gst0.10-dev,

  checking for cairo_push_group... yes
  checking for GST... configure: WARNING: GStreamer 1.0 not available, falling back to 0.10
  checking for GST... configure: WARNING: GStreamer 0.10 not available, falling back to 0.8
  configure: error: GStreamer not available
  Error running configure
  ERROR: failed building wxWidgets
  Traceback (most recent call last):
    File "build.py", line 1270, in cmd_build_wx
      wxbuild.main(wxDir(), build_options)
    File "/tmp/pip-build-ktru3cfl/wxPython/buildtools/build_wxwidgets.py", line 376, in main
      "Error running configure")
    File "/tmp/pip-build-ktru3cfl/wxPython/buildtools/build_wxwidgets.py", line 85, in exitIfError
      raise builder.BuildError(msg)
  buildtools.builder.BuildError: Error running configure
  Finished command: build_wx (0m7.249s)
  Finished command: build (0m7.249s)
  Command '"/home/user/.virtualenvs/app-py3/bin/python3" -u build.py build' failed with exit code 1.

Any alternative?

**Comment by mesalu** [comment]
https://wxpython.org/blog/2017-08-17-builds-for-linux-with-pip/index.html

**Comment by damufo** [comment]
I installed 
$ sudo apt-get install python3-gst-1.0

but same problem
checking for GST... configure: WARNING: GStreamer 1.0 not available, falling back to 0.10
    checking for GST... configure: WARNING: GStreamer 0.10 not available, falling back to 0.8
    configure: error: GStreamer not available
    Error running configure
    ERROR: failed building wxWidgets
    Traceback (most recent call last):
      File "build.py", line 1270, in cmd_build_wx
        wxbuild.main(wxDir(), build_options)
      File "/tmp/pip-build-jjx12as1/wxPython/buildtools/build_wxwidgets.py", line 376, in main
        "Error running configure")
      File "/tmp/pip-build-jjx12as1/wxPython/buildtools/build_wxwidgets.py", line 85, in exitIfError
        raise builder.BuildError(msg)
    buildtools.builder.BuildError: Error running configure
    Finished command: build_wx (0m7.111s)
    Finished command: build (0m7.111s)
    Command '"/home/user/.virtualenvs/app-py3/bin/python3" -u build.py build' failed with exit code 1.

Exists any how to install wxpython on debian 9 (python 3)?
Very thanks for your help.

**Comment by RobinD42** [comment]
Look for libsgstreamer-*-dev packages, as mentioned in the README.rst file.

**Comment by damufo** [comment]
Now I installed
sudo apt-get install gstreamer1.0 libgstreamer-plugins-base1.0-dev libgstreamer1.0-dev
The gstreamer problem seems resolved.
Then error
Checking for library python3.5 in LIBDIR : not found
I probed from out virtualenv
Then error
task in '_html2' failed (exit status 1)
I installed:
sudo apt-get install libgtk2.0-dev libwebkitgtk-dev libwebkitgtk-3.0-dev
And finally compile!!

Very thanks!!!

user@debianstretch:~$ sudo pip3 install --upgrade --pre -f https://wxpython.org/Phoenix/snapshot-builds/ wxPython
[sudo] password for user: 
Collecting wxPython
  Using cached https://wxpython.org/Phoenix/snapshot-builds/wxPython-4.0.0b2.dev3307+d7cae3f.tar.gz
Requirement already up-to-date: six in /usr/lib/python3/dist-packages (from wxPython)
Building wheels for collected packages: wxPython
  Running setup.py bdist_wheel for wxPython ... done
  Stored in directory: /root/.cache/pip/wheels/84/7f/a5/c8259920ef35976c848549797679223097cb7bd964a492d505
Successfully built wxPython
Installing collected packages: wxPython
Successfully installed wxPython-4.0.0b2.dev3307+d7cae3f
user@debianstretch:~$ python3
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import wx
>>> wx.version()
'4.0.0b2.dev3307+d7cae3f gtk3 (phoenix)'
>>> 
user@debianstretch:~$
