### ISSUE TITLE
wx.THICK_FRAME missing

### ISSUE THREAD

**Issue by topic2k** [wxWidgets/Phoenix#481]
**Operating system**: Windows 10 64Bit
**wxPython version**: 4.0.0b2.dev3314+3de6e63 msw (phoenix)
**Stock or custom build**: stock
**Python version**: 2.7.12 Stackless 3.1b3 060516 (default, Oct 31 2016, 18:42:08) [MSC v.1500 32 bit (Intel)] on win32
**Stock or custom build**: stock

**Description of the problem**:
Missing the dialog style `THICK_FRAME`, getting `AttributeError: 'module' object has no attribute 'THICK_FRAME'`

**Comment by RobinD42** [comment]
`wx.THICK_FRAME` has been effectively gone from wxWIdgets for a long time and it's bit has been reassigned to wx.RESIZE_BORDER. It's one of the "old aliases and other crud" that have been removed for Project Phoenix.

**Comment by dhyams** [comment]
THICK_FRAME needs to be removed from the wx.Dialog documentation.
