### ISSUE TITLE
grid.Grid.DeleteRow not behaving according to documentation

### ISSUE THREAD

**Issue by SweRavn** [wxWidgets/Phoenix#483]
**Operating system**: Windows 10 64 bit
**wxPython version**: 4.0.0a4.dev3167+3bb2a52 msw (phoenix)
**Stock or custom build**: Anaconda
**Python version**: Python 3.6.1 :: Anaconda 4.4.0 (64-bit)
**Stock or custom build**: Anaconda

**Description of the problem**:
The documentation says:
https://wxpython.org/Phoenix/docs/html/wx.grid.Grid.html#wx.grid.Grid.DeleteRows

But I get an exception when I try to delete rows that do not exist. I expected, according to documentation, to to just receive False. Here is runable code:

```python
import wx
from wx import grid

class MainFrame(wx.Frame):
    def __init__(self):
        super().__init__(None, -1, "Wx test", size=(1024, 768))
        panel = wx.Panel(self)
        grd = grid.Grid(panel)
        grd.CreateGrid(0, 2)
        grd.SetColLabelValue(0, "Col 1")
        grd.SetColLabelValue(1, "Col 2")
        grd.DeleteRows(0, 1) # This line causes an exception which it should not according to documentation.

if __name__ == "__main__":
    print("Wx version: %s", wx.version())
    app = wx.App(False)
    main_frame = MainFrame()
    main_frame.Show()
    app.MainLoop()
```

**Comment by RobinD42** [comment]
`wxAssertionError` exceptions are raised when an assertion or other debug check in the wx C++ code fails. For some of them it indicates a fatal error, others just mean that you are doing something wrong and is intended to tell the programmer they need to do more checking something in their code. For wxPython we decided to turn all of the runtime asserts and debug checks into Python exceptions as that would be the best way to avoid unexpected and unexplained crashes.

In this case I believe that the False return value would indicate that the table does not allow deletion of rows. In other words, that you didn't do anything wrong, it's just the table that won't support it. OTHO, the assert exception indicates that the passed parameters are incorrect, and that you need to correct your code.

**Comment by RobinD42** [comment]
Although it's not true in all cases, it would be valid to assume that any method call to wx code can result in a `wxAssertionError`.
