### ISSUE TITLE
Strcmp Error from wx.Bitmap

### ISSUE THREAD

**Issue by RandyERaymond** [wxWidgets/Phoenix#484]
**Operating system**: (sys.version: '3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)]')
**wxPython version**: wx.version(): '4.0.0b1 msw (phoenix)'
**Stock or custom build**: Stock
**Python version**: 'Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)] on win32'
**Stock or custom build**: Stock

**Description of the problem**:

```
File "C:\Users\Randy\Documents\SanDiskRoot\programmingStuff\Python\VideoLibrary\smallApp.py", line 100, in ToolData
    decRec_bmp =  wx.Bitmap("MthDec.png", type=wx.BITMAP_TYPE_PNG)
wx._core.wxAssertionError: C++ assertion "strcmp(setlocale(LC_ALL, NULL), "C") == 0" failed at ..\..\src\common\intl.cpp(1579) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
Things are going to break, please only change locale by creating wxLocale objects to avoid this!
```

I looked this up and this error has been reported before. But, I could not find any fixes. I tried several things, but the creation of the ToolBar seems to cause it. I have included a zipfile with smallApp and the PNGs & ICOs that I use that cause the error. 

[exampleApp.zip](https://github.com/wxWidgets/Phoenix/files/1254589/exampleApp.zip)

**Comment by RobinD42** [comment]
It seems your system locale is set in a way that something is changing it at the C runtime level. What that somethign is I'm not sure. Maybe Python, maybe some OS level thing on your system, or maybe some other modules or DLLs being imported or wrapped around system libs.

Either way, the workaround is to (re)set the locale using `wx.Locale` so wx's locale is the same as the C runtime setting.  See https://stackoverflow.com/questions/33505916/wx-image-is-throwing-pyassertionerror
