### ISSUE TITLE
missing wx.ListCtrl.DeleteAllColumns

### ISSUE THREAD

**Issue by mprosperi** [wxWidgets/Phoenix#486]
**Operating system**: win10
**wxPython version**: phoenix latest snapshot
**Stock or custom build**: stock
**Python version**: 2.7
**Stock or custom build**: stock

**Description of the problem**: wx.ListCtrl.DeleteAllColumns is missing in phoenix and present in classic (difference not documented in https://wxpython.org/Phoenix/docs/html/classic_vs_phoenix.html#classic-vs-phoenix)

**Comment by mesalu** [comment]
Looks like an issue with wxWidgets, the method (and probably some others) fell off the radar in the header files Phoenix utilizes to generate bindings.

**Comment by mesalu** [comment]
@RobinD42  oops. ;)
