### ISSUE TITLE
wrong exception message from  wx.dataview.DataViewCustomRenderer.Render

### ISSUE THREAD

**Issue by mprosperi** [wxWidgets/Phoenix#492]
**Operating system**: win10
**wxPython version**: wxPython-4.0.0b2.dev3324+4ef6bc8-cp27-cp27m-win_amd64.whl
**Stock or custom build**: stock
**Python version**: 2.7
**Stock or custom build**: stock

**Description of the problem**: if wx.dataview.DataViewCustomRenderer.Render returns None, the exception message is "TypeError: invalid result from BomTreeRenderer.Render(), an **integer** is required" but should be TypeError: invalid result from BomTreeRenderer.Render(), an **bool** is required

**Comment by RobinD42** [comment]
In C there are no bools, just zero and non-zero integers. In C++ bools and ints are mostly interchangeable, and in many ways the Python C API follows that same pattern. So the wxPython wrapper code does the same. Integers are what is looked for and accepted by the wrapper code. If the value was a bool already then it will auto-convert to an int in the API. Then the integer object will be converted to a C++ bool when needed in a similar way.

In this particular case, the sipParseResult function is being used to validate the return object and convert it, and it is using the 'b' format code, which "Convert a Python integer to a C/C++ bool."  See http://pyqt.sourceforge.net/Docs/sip4/c_api.html

**Comment by RobinD42** [comment]
FTR: It looks like a future version of sip will give us better exception messages in cases like this.

**Comment by RobinD42** [comment]
And I'm in the process of switching to that new version of SIP now. See #589.
