### ISSUE TITLE
Hello World instructions and example

### ISSUE THREAD

**Issue by cztomczak** [wxWidgets/Phoenix#496]
On the http://wxwidgets.org/ site I can see in the right menu "Quick Links", a link to a Hello World example. I don't see such link on the https://wxpython.org/ website. It would be nice if on the main page I could quickly find Hello World instructions, something like:

1. Install wxPython using command: `pip install wxPython`
2. Fetch the hello world example by cloning the github repository: `git clone...`
3. Run the hello world example: `cd wxPython/examples/` and `python hello_world.py`

**Comment by cztomczak** [comment]
After a few clicks and a bit of scrolling I got here:
https://wiki.wxpython.org/Getting%20Started#A_First_Application:_.22Hello.2C_World.22

When I copy that example and paste it in my editor and then run it, I get this error:
```py
  File "helloworld.py", line 1
    1 #!/usr/bin/env python
    ^
IndentationError: unexpected indent
```

:) 

This should have been easier!

**Comment by RobinD42** [comment]
Toggle off the display of the line numbers before copying the text.

**Comment by RobinD42** [comment]
Done. I added a link to the Hello World already on the overview page.

**Comment by cztomczak** [comment]
Looks great now! :)
