### ISSUE TITLE
exception with customtreectrl

### ISSUE THREAD

**Issue by mprosperi** [wxWidgets/Phoenix#500]
**Operating system**: win10
**wxPython version**:  wxPython-4.0.0b2.dev3324+4ef6bc8-cp27-cp27m-win_amd64
**Stock or custom build**: stock
**Python version**: 2.7-64bit
**Stock or custom build**: stock

**Description of the problem**:

  File "C:\Users\me\Envs\af427\lib\site-packages\wx\lib\agw\customtreectrl.py", line 5938, in SortChildren
    children = six.sort(children, self.OnCompareItems)
AttributeError: 'module' object has no attribute 'sort'

Cannot find anything in six docs about compatible sorting

**Comment by ThomasP0815** [comment]
already reported in #463
