### ISSUE TITLE
wx.BusyInfo fails when used as context manager

### ISSUE THREAD

**Issue by kg-2** [wxWidgets/Phoenix#505]
Windows 10
4.0.0.1b, stock
python 3.6.2 stock

when wx.BusyInfo is used as a context manager
```
with wx.BusyInfo("...") as busy_info:
    do_something()

```
 it produces the following traceback
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\wx\core.py", line 3108, in _BusyInfo___exit__
    self.Destroy()
AttributeError: 'BusyInfo' object has no attribute 'Destroy'

**Comment by RobinD42** [comment]
This has already been fixed for b2. See #449 and #450.
