### ISSUE TITLE
Exception when running Demo ShortcutEditor

### ISSUE THREAD

**Issue by HelioGuilherme66** [wxWidgets/Phoenix#51]
Using latest git version, I am getting the below exception (DoShowScrollbars(): window must be created):
```
19:20:25: Debug: Invalid key string "f21"
19:20:25: Debug: Unrecognized accel key 'f21', accel string ignored.
19:20:25: Debug: Invalid key string "f21"
19:20:25: Debug: Unrecognized accel key 'f21', accel string ignored.
19:20:25: Debug: Unrecognized accel key 'start', accel string ignored.
19:20:25: Debug: Invalid key string "f24"
19:20:25: Debug: Unrecognized accel key 'f24', accel string ignored.
19:20:25: Debug: Invalid key string "f17"
19:20:25: Debug: Unrecognized accel key 'f17', accel string ignored.
Traceback (most recent call last):
  File "agw/ShortcutEditor.py", line 380, in OnButton1
    self.win = ShortcutEditorDemo(self, self.log)
  File "agw/ShortcutEditor.py", line 168, in __init__
    dlg = SE.ShortcutEditor(self)
  File "/opt/Phoenix/wx/lib/agw/shortcuteditor.py", line 2214, in __init__
    self.CreateWidgets()
  File "/opt/Phoenix/wx/lib/agw/shortcuteditor.py", line 2236, in CreateWidgets
    self.listShortcut = ListShortcut(self)
  File "/opt/Phoenix/wx/lib/agw/shortcuteditor.py", line 1694, in __init__
    wx.TR_FULL_ROW_HIGHLIGHT|HTL.TR_ELLIPSIZE_LONG_ITEMS)
  File "/opt/Phoenix/wx/lib/agw/hypertreelist.py", line 4169, in __init__
    self._main_win = TreeListMainWindow(self, -1, wx.Point(0, 0), size, main_style, agwStyle, validator)
  File "/opt/Phoenix/wx/lib/agw/hypertreelist.py", line 2075, in __init__
    CustomTreeCtrl.__init__(self, parent, id, pos, size, style, agwStyle, validator, name)
  File "/opt/Phoenix/wx/lib/agw/customtreectrl.py", line 2820, in __init__
    wx.ScrolledWindow.__init__(self, parent, id, pos, size, style|wx.HSCROLL|wx.VSCROLL, name)
wx._core.wxAssertionError: C++ assertion "scrolled" failed at /opt/Phoenix/ext/wxWidgets/src/gtk/scrolwin.cpp(227) in DoShowScrollbars(): window must be created
```
Attached image 
![shortcuteditor_nok_f780b216881e6afd81584ae49453630734e023c5](https://cloud.githubusercontent.com/assets/2866630/13826365/f815421a-ebae-11e5-8c98-adb1fec558bd.png)
---
This problem was not happening with a previous snapshot (dev1851_eedf718). Attached image 
![shortcuteditor_ok_dev1851_eedf718](https://cloud.githubusercontent.com/assets/2866630/13826427/66cb1d6a-ebaf-11e5-809b-8d5947f62b43.png)

I am porting RIDE from Classic to Phoenix and this issue is BLOCKING my progress, because Tree Panel cannot be created and main frame depends heavily on it. If anyone wants to try my RIDE fork (compatible with 2.8.12.1, 2.9.5, 3.0.2 and Phoenix) it is [here](https://github.com/HelioGuilherme66/RIDE/tree/wxPhoenix). 
@RobinD42 how can I help debugging/fixing this? Thanks.

My system is Fedora Core 22 x64 with Python 2.7.10

**Comment by swt2c** [comment]
Can you try my patch in https://github.com/wxWidgets/Phoenix/pull/45?  I think it might fix that.

**Comment by HelioGuilherme66** [comment]
@swt2c Yes I confirm that it does fix it! Thanks!

**Comment by swt2c** [comment]
Great!  Hopefully @RobinD42 can merge that as soon as possible.
