### ISSUE TITLE
Missing LICENSE.txt from main repo wxWidgets/Phoenix raw download

### ISSUE THREAD

**Issue by ioandev** [wxWidgets/Phoenix#510]
Hi,

The LICENSE.txt file is missing.

From https://github.com/wxWidgets/Phoenix/blob/master/setup.cfg : 
```
[metadata]
license-file = LICENSE.txt
```

Having a license file a mandatory requirement when building any package for the Yocto project. It verifies its md5 immediately after cloning the repo.

Regards

**Comment by RobinD42** [comment]
The LICENSE.txt file and a ton of other stuff are generated as part of the build. I do not recommend using a raw git checkout unless you are working on wxPython itself.  

Instead, I suggest to use the official release source tarball from PyPI, or if you need recent changes you can grab a source tarball from the snapshot builds folder, or if a true cutting edge version is needed, you can generate a source tarball from a git checkout with a command like this:

```
python build.py setrev dox etg sip sdist
```

**Comment by infinity77** [comment]
@swt2c : @RobinD42 answer makes perfect sense to me - and it’s kind of obvious. I believe you can close this, unless there really is some legal issue related to a missing license in GitHub (but why? IANAL)
