### ISSUE TITLE
interpreter crash with PyPlot demo

### ISSUE THREAD

**Issue by mprosperi** [wxWidgets/Phoenix#522]
**Operating system**: win10
**wxPython version**: wxPython-4.0.0b2.dev3363+03edeca-cp35-cp35m-win_amd64
**Stock or custom build**: stock
**Python version**: 3.5
**Stock or custom build**: stock

**Description of the problem**: crash with python 3.5, no problem with python 2.7 (always on win10)

**Comment by RobinD42** [comment]
What needs to be done to cause the crash?

**Comment by mprosperi** [comment]
just double-clicked on the PyPlot item in the demo apps tree. But I tried several times now and it works... don't know. I close it
