### ISSUE TITLE
lib.plot: lowercase conversion in SaveFile()

### ISSUE THREAD

**Issue by innomatica** [wxWidgets/Phoenix#526]
**Operating system**: Windows 10
**wxPython version**: 4.0.0.b3
**Stock or custom build**:
**Python version**: 3.6
**Stock or custom build**:

**Description of the problem**:
_string.lower() in SaveFile() function at line number 345 generates error in Python 3.

```python
# Put code sample here
```

**Comment by RobinD42** [comment]
What is the actual error? What filename did you try to use? What are the steps to duplicate the problem? I can guess, but it would be so much better to include that info with the issue report.

https://wxpython.org/pages/how-to-submit-issue/

**Comment by innomatica** [comment]
Sorry for the sloppiness. Error output is

```NameError: name _string' is not defined```

Changing line 345 to

```fType = fileName[-3:].lower()```

seems to solve the issue at least in Python 3.
