### ISSUE TITLE
Cancel Button bitmap in wx.SearchCtrl has an opaque white background

### ISSUE THREAD

**Issue by JeffHanna** [wxWidgets/Phoenix#533]
**Operating system**: Windows 10
**wxPython version**: 4.0.0b1
**Stock or custom build**: n/a
**Python version**: 3.6.2 64-bit
**Stock or custom build**: n/a

The grey-circle-with-white-'x' bitmap used for the cancel button in wx.SearchCtrl does not have a transparent background. If the color of the text entry field in a wx.SearchCtrl is changed from white the bitmap no longer looks acceptable, showing as a white square with an image inside of it. Please make the background pixels of that image transparent.

```python
import wx

class Test_Frame( wx.Frame ):
    def __init__( self ):
       super( Test_Frame, self ).__init__( None, title = 'wx.SearchCtrl Test' )
       main_sizer = wx.BoxSizer( wx.HORIZONTAL )

       search_ctrl = wx.SearchCtrl( self )
       search_ctrl.ShowCancelButton( True )
       search_ctrl.SetBackgroundColour( wx.GREEN )
       main_sizer.Add( search_ctrl, 1, wx.ALL | wx.EXPAND, 5 )

       self.SetSizer( main_sizer )
       self.Fit( )
       self.CenterOnScreen( )



app = wx.App( )
frame = Test_Frame( )
frame.Show( )
app.MainLoop( )


```

**Comment by RobinD42** [comment]
The fix for this will have to happen in the wxWIdgets C++ code. Please report this issue in their tracker: https://trac.wxwidgets.org/

**Comment by JeffHanna** [comment]
Thank you. I reposted the defect on track.wxwidgets.org

**Comment by RobinD42** [comment]
Please post a link, or at list the item number, here in case anybody comes across this in the future and would like to follow the trail over there.

**Comment by JeffHanna** [comment]
Sure thing. I found a similar, but confusingly worded, defect from about 19 months ago. I added a comment to that one.

https://trac.wxwidgets.org/ticket/17392

**Comment by RobinD42** [comment]
Closing now that it is on wxTrac.
