### ISSUE TITLE
wx.adv.TaskBarIcon.ShowBalloon not showing balloon

### ISSUE THREAD

**Issue by kg-2** [wxWidgets/Phoenix#534]
**Operating system**: windows 10
**wxPython version**: 4.0.0b2.dev3337+03248e0
**Stock or custom build**: stock
**Python version**: 3.6.2
**Stock or custom build**: stock

**Description of the problem**: ShowBalloon will show the task bar icon, but no message is displayed.  It will also keep the program running unless the user explicitly destroys the task bar icon at close.

```python
import wx
import wx.adv
import sys


class TestFrame(wx.Frame):
    def __init__(self):
        wx.Frame.__init__(self, None)
        self.tb_icon = wx.adv.TaskBarIcon()
        icon = wx.Icon(sys.executable + ";0", wx.BITMAP_TYPE_ICO)
        self.tb_icon.SetIcon(icon, "tooltip")

        self.Bind(wx.EVT_CLOSE, self.on_close)
        self.Show()

    def show_balloon(self, msg):
        print("showing balloon message '%s'" % msg)
        self.tb_icon.ShowBalloon("Title", msg, 6 * 1000, wx.ICON_INFORMATION)

    def on_close(self, event):
        event.Skip()
        print("frame closing")
        # this is required to force the app to quit
        # self.tb_icon.Destroy()


app = wx.App()
frame = TestFrame()
wx.CallLater(1000, frame.show_balloon, "Test Message")
app.MainLoop()

```

**Comment by RobinD42** [comment]
> It will also keep the program running unless the user explicitly destroys the task bar icon at close.

That is by-design. This way the application can close all its windows and still keep running in just the taskbar. If you want to completely exit the program then you need to remove the taskbar icon.

I'll check into the balloon issue later.

**Comment by RobinD42** [comment]
It is showing the message balloon for me here on Win10. Is it possible that you have notifications turned off in the system preferences or something?

**Comment by kg-2** [comment]
windows took a dump on me and I had to reinstall it, everything works now.
