### ISSUE TITLE
The youtube link is not rendering when added using sphinxcontib.youtube

### ISSUE THREAD

**Issue by 28Toto** [wxWidgets/Phoenix#535]
Installed Python 2.7.13 and Sphinx on Windows 10. 
No error is reported when the HTMLs are build. But, the YouTube URL does not get embedded in the HTML page.

Note that I have followed the cardinal requirements such as adding the extension in the config.py and adding the topic in the index.rst.

Could this be due the incompatible extension version?

**Comment by RobinD42** [comment]
I think you've posted this to the wrong project.
