### ISSUE TITLE
PropertyGrid.SetPropertyValues truncates floats

### ISSUE THREAD

**Issue by BrendanSimon** [wxWidgets/Phoenix#536]
**Operating system**: observed on `macOS Sierra` and `Debian 8 Jessie`
**wxPython version**: `v4.0.0b1`
**Stock or custom build**: `Stock` -- installed wheel via `pip`
**Python version**: `3.4` on `Debian 8 Jessie` and `3.6` on `macOS Sierra`
**Stock or custom build**: `Stock`

**Description of the problem**:

The first time a float value is set in the property grid it renders fine.

All subsequent sets that overwrite a float property will truncate it (as if it were an integer).

This can be observed in the `demo` by clicking on `SetPropertyValues` button and editing the line

```Python
obj.Float = 123.456
```

Actually that is wrong.  There are bugs in the demo when clicking the `SetPropertyValues` button, however you can still see that `100.0` is rendered as `100` !!

The bug appears if `autofill` parameter is set to `True` or `False`.

```Python
pg.SetPropertyValues(settings, autofill=True)
pg.SetPropertyValues(settings, autofill=False)
```

**However, if `AutoFill()` is called then the float does render correctly every time !!**

```Python
vo = ValueObject(settings)
pg.AutoFill(vo)
```

**However, using `AutoFill()` seems to expose another bug (Categories disappear)**
Actually not really sure if it is a bug or not, as documentation says properties are cleared first.  Is there a way of retaining the categories using `AutoFill()` or another method?

**Comment by BrendanSimon** [comment]
The only work around I've gotten to work is to delete float properties, and the set properties with `autofill` parameter set to true.

```Python
pg.DeleteProperty('MyFloat')
#pg.SetPropertyValues(settings)
pg.SetPropertyValues(settings, autofill=True)
```

**Comment by BrendanSimon** [comment]
Alternatively, I do clear and add all properties, including pages and categories, again.
That's a bit more generic (and more maintainable) than my app having built in knowledge to delete specific properties.

**Comment by RobinD42** [comment]
Fix is incoming, but for the record another workaround would be to set the value as a string instead of as a float. Then the `FloatProperty` class itself would do the conversion to a C `double`.
