### ISSUE TITLE
wxpg.PropertyGrid & wxpg.PGEditorDialogAdapter crash

### ISSUE THREAD

**Issue by GGRI** [wxWidgets/Phoenix#544]
**Operating system**: Windows 7
**wxPython version**: wxPython-4.0.0b1 & wxPython-4.0.0b2
**Python version**: 2.7.13

**Description of the problem**:

This problem is related to issue #394. 
There is a python crash using wxpg.PGEditorDialogAdapter in wxpg.PropertyGrid.
It can be reproduced in wxPython-demo-4.0.0b2/demo/PropertyGrid.py when clicking to the "..." button on the line **SingleChoiceProperty**.

Guillaume

**Comment by GGRI** [comment]
I solved the problem on the demo using (line 401 of the demo file):

```python
    def GetEditorDialog(self):
        # Set what happens on button click
        self.dialog_adapter = SingleChoiceDialogAdapter(self.dialog_choices)
        return self.dialog_adapter
```

instead of 
```python
    def GetEditorDialog(self):
        # Set what happens on button click
        return SingleChoiceDialogAdapter(self.dialog_choices)
```

**Comment by RobinD42** [comment]
Ok, thanks. Looks like it probably needs an ownership transfer there. I'll take a closer look at it in the next few days.
