### ISSUE TITLE
4.0.0b1 to 4.0.0b2 update fails within virtualenv: exit code 1

### ISSUE THREAD

**Issue by kierun** [wxWidgets/Phoenix#559]
**Summary**: I try to update wxPython from beta 1 to 2 and get 

`Command '"/home/usr/.virtualenvs/raiju/bin/python3" -u build.py build' failed with exit code 1.`

**Operating system**:  

CentOS 7

Linux serval 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**wxPython version**:

4.0.0b1 works fine but 4.0.0b2 does not install.

**Stock or custom build**:

`pip install -U wxPython`

**Python version**:

3.6.2 …

**Stock or custom build**:

Stock from CentOS 7 packages.

**Description of the problem**:

I try to update wxPython using pip with `pip install -U wxPython`. The process compiles a lot of code then fails with `exit code 1`. 

The compiler returns rather a lot of errors which makes me think that something else could potentially be going on. Attached is the whole [pip install output](https://github.com/wxWidgets/Phoenix/files/1348218/pip-install.log)

**Comment by swt2c** [comment]
The problem appears to be that you're missing the webkit or webkit2 development packages:
>   checking for WEBKIT... configure: WARNING: webkit2gtk not found, falling back to webkitgtk
  checking for WEBKIT... configure: WARNING: webkitgtk not found.
  configure: WARNING: WebKit not available, disabling wxWebView

On CentOS 7, try installing the webkitgtk4-devel package and run the build process again.

**Comment by kierun** [comment]
That fixed it. Thank you.
