### ISSUE TITLE
Upload to pypi?

### ISSUE THREAD

**Issue by jesse-git** [wxWidgets/Phoenix#56]
Are there any plans to upload releases considered stable (or "mostly" stable) to pypi? I assume that's an obvious question, but:
- It's the defacto standard for python packages.
- It would make it very easy for projects to require phoenix as a dependency in `setup.py` (which is why I'm creating this issue).
- It would expose phoenix to a broader community and the fact that wxpython can actually be run under python 3 rather successfully.
- It would prevent any downtime of the wxpython.org website affecting availability of obtaining wxpython, reading the documentation, or deterring users for other embarrassing reasons such as this:

![image](https://cloud.githubusercontent.com/assets/14930091/14054668/5520603a-f2b1-11e5-9ddb-392afde8d0c9.png)

In the event that automatic installation fails via `pip` because of external dependencies needed, such as a missing compiler, etc., further instructions could be given to the user to read the `README.rst` or the like.

Appreciate the consideration and all of the work in this project!

**Comment by eldarkg** [comment]
:+1:

**Comment by RobinD42** [comment]
The plan is to start uploading to pypi with the first official alpha release.  I'm expecting that to happen within the next several weeks if all goes well.

**Comment by grzanka** [comment]
Hi, is there any update on the plan to upload to pypi ? I am looking forward for easy installation.

Now on Windows I am forced to do:
```pip install --upgrade --trusted-host wxpython.org --pre -f http://wxpython.org/Phoenix/snapshot-builds/ wxPython_Phoenix --only-binary="all" -V```
which is not very much convenient

**Comment by RobinD42** [comment]
Adding some automation for releases and pypi uploads is my next big task.  It should be happening soon.

BTW, wxpython.org is accessible via https now, so you can removed the `--trusted-host` parameter and make the pip command a little easier.

**Comment by grzanka** [comment]
I did some automation on travis with a simple script and twine: https://github.com/pytrip/pytrip/blob/master/.travis/deploy_package.sh

The only risky aspect is that pypi password is stored as secured env variable. It may leak easily if some part of your CI machinery dumps all env vars.

Otherwise it works really well.

PS. Thanks for hint with HTTPS
