### ISSUE TITLE
wxtreectrl text edit 

### ISSUE THREAD

**Issue by cnof00** [wxWidgets/Phoenix#560]
**Operating system**:
macos high Sierra
**wxPython version**:
wxPython 4.0.0b2 Released
**Stock or custom build**:
stock
**Python version**:
2.7.10
**Stock or custom build**:
stock
**Description of the problem**:
wxtreectrl items with variable row height set do not resize as they have in the past.

The project is at buzz.sf.net, if you want to see.

```python
# Put code sample here
  wx.TreeCtrl.__init__(self, parent, ID, wx.DefaultPosition, wx.DefaultSize, wx.TR_HAS_BUTTONS| wx.TR_HAS_VARIABLE_ROW_HEIGHT|wx.TR_NO_LINES | wx.TR_TWIST_BUTTONS |wx.TR_SINGLE | wx.TR_EDIT_LABELS)```

**Comment by infinity77** [comment]
@swt2c : this is a very badly written/reported  issue - suggest killing it
