### ISSUE TITLE
Unable to compile latest version on Ubuntu 17.10

### ISSUE THREAD

**Issue by binarykitchen** [wxWidgets/Phoenix#567]
Unable to compile following on Ubuntu 17.10:

```
Collecting wxPython
  Using cached wxPython-4.0.0b2.tar.gz
Requirement already up-to-date: six in /home/michael-heuberger/.local/lib/python2.7/site-packages (from wxPython)
Building wheels for collected packages: wxPython
  Running setup.py bdist_wheel for wxPython ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/michael-heuberger/pip-build-OWfOuj/wxPython/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/michael-heuberger/tmpYWf7OLpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  WARNING: Building this way assumes that all generated files have been
  generated already.  If that is not the case then use build.py directly
  to generate the source and perform the build stage.  You can use
  --skip-build with the bdist_* or install commands to avoid this
  message and the wxWidgets and Phoenix build steps in the future.
  
  "/usr/bin/python" -u build.py build
  Will build using: "/usr/bin/python"
  2.7.14 (default, Sep 23 2017, 22:06:14)
  [GCC 7.2.0]
  Python's architecture is 64bit
  cfg.VERSION: 4.0.0b2

... (long list) ...

Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/michael-heuberger/pip-build-OWfOuj/wxPython/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/michael-heuberger/pip-FxBUrt-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/michael-heuberger/pip-build-OWfOuj/wxPython/
```

happens when I run that command:

```
pip freeze --local | grep -v '^\-e' | cut -d = -f 1 | xargs -n1 pip install --user -U
```

**Comment by RobinD42** [comment]
What are the actual error messages leading up to the failure message?

**Comment by binarykitchen** [comment]
hard to say - the output is super super super long - would take me 10 mins to parse through them all ...

**Comment by mesalu** [comment]
Please copy and paste the output into a comment here please. We can't help if we don't know whats wrong.

I'd wager its a dependency issue, Here's a rundown of why we depend on packages, and don't install them ourselves: [here](https://wxpython.org/blog/2017-08-17-builds-for-linux-with-pip/index.html)

**Comment by adrientetar** [comment]
I think two packages not mentioned in the README are needed under recent ubuntu: libwebkit2gtk-4.0-dev libsdl2-dev

**Comment by peredur02** [comment]
I have the same problem.  The full output is in the attached file.
[pip-wxpython-output.txt](https://github.com/wxWidgets/Phoenix/files/1464559/pip-wxpython-output.txt)

**Comment by peredur02** [comment]
I also tried again after installing the packages mentioned by adrentetar.  Still no luck.

**Comment by peredur02** [comment]
Also tried again using pip3.  Same result (attached)
[pip3-wxpython-output.txt](https://github.com/wxWidgets/Phoenix/files/1464569/pip3-wxpython-output.txt)

**Comment by adrientetar** [comment]
sudo apt-get install libglu1-mesa-dev freeglut3-dev mesa-common-dev

**Comment by peredur02** [comment]
Still no luck:
[pip3-wxpython-output-2.txt](https://github.com/wxWidgets/Phoenix/files/1464575/pip3-wxpython-output-2.txt)

**Comment by adrientetar** [comment]
Have you installed the packages mentioned in the README?

**Comment by peredur02** [comment]
If you mean the ones mentioned by adrientetar above, then yes.

**Comment by adrientetar** [comment]
https://github.com/wxWidgets/Phoenix/blob/master/README.rst

**Comment by peredur02** [comment]
dpkg-dev - already installed and up-to-date
build-essential - already installed and up-to-date
python3 (obviously installed - python 3.6.3) - python 2.7 is also, obviously, installed
libjpeg-dev - NOT installed or not up-to-date.  Now installed
libtiff-dev - NOT installed or not up-to-date.  Now installed
libsdl1.2-dev - NOT installed or not up-to-date.  Now installed
libgstreamer-plugins-base0.10-dev - NO SUCH PACKAGE
E: No se ha podido localizar el paquete libgstreamer-plugins-base0.10-dev
E: No se pudo encontrar ningún paquete usando «*» con «libgstreamer-plugins-base0.10-dev»
E: No se pudo encontrar ningún paquete con la expresión regular «libgstreamer-plugins-base0.10-dev»
libnotify-dev - updated
freeglut3 - installed and up-to-date
freeglut3-dev - installed and up-to-date
libsm-dev - installed and up-to-date
libgtk2.0-dev - NOT installed or up-to-date.  Now installed
libwebkitgtk-dev - NOT installed or up-to-date.  Now installed
libgtk-3-dev - installed and up-to-date
libwebkitgtk-3.0-dev - NOT installed.  Now installed and up-to-date
libgstreamer-plugins-base1.0-dev - NOT installed.  Now installed and up-to-date

Now seems to be running OK, except that setup.py has been running for about 15 minutes with no sign of progress (other than the /-|\ thingy).

**Comment by peredur02** [comment]
Ha!  As ever, it finished as soon as I hit the button.  Thanks to adrientetar for patience and the RTFM :)
All works now.

**Comment by adrientetar** [comment]
@RobinD42 I'd suggest adding to the README: libwebkit2gtk-4.0-dev libsdl2-dev
