### ISSUE TITLE
you've got three questions.I did not write in the title as the question would not fit

### ISSUE THREAD

**Issue by omerfeyyaz** [wxWidgets/Phoenix#569]
Question 1: Is it compatible with all operating systems?
Question 2: Are all operating systems and AGW objects compatible with all operating systems?
Question 3: Is there a way to remove C or C ++?
Thank you in advance for your help.

**Comment by mesalu** [comment]
1. Yes, some minor behaviors vary from platform to platform, but these are usually documented.
2. Yes, AGW is built from wx classes, and has no direct tether to specific operating systems
3. I find this question ambiguous so I will look at it as "Will I need to write any C or C++ code to use wxPython?", the answer to which is No.  

For more resources please refer to the plethora of online resources such as:
- [The wxWidgets wiki](https://wiki.wxwidgets.org/Main_Page)
- [The wxPython website](https://wxpython.org/)
- [wxPython's documentation](https://docs.wxpython.org/)
- [The wxPython Google group](https://groups.google.com/forum/#!forum/wxpython-users) 

Closing as off-topic and not an issue report.
