### ISSUE TITLE
2 listctrls assigned to 1 imagelist causes crashes

### ISSUE THREAD

**Issue by kg-2** [wxWidgets/Phoenix#574]
**Operating system**: Windows 10
**wxPython version**:  '4.0.0rc1.dev3441+ec00c6b msw (phoenix)' stock
**Python version**: '3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:14:34) [MSC v.1900 32 bit (Intel)]'
**Stock or custom build**: stock

**Description of the problem**:
python crashes after closing a window if 2 listctrls are assigned the same wx.ImageList

```python
# Put code sample here
```

**Comment by RobinD42** [comment]
The `AssignImageList` method transfers ownership of the image list to the list control, so by using `AssignImageList` more than once you are essentially giving ownership of the object to more than one widget, and they will both try to destroy it when they are destroyed.

Instead, to share an image list you should be using `SetImageList` which will let the listctrl use the image list but not assume ownership of it. You'll also need to save a reference to it in the Python code so it won't be automatically destroyed when the Python variable goes out of scope.
