### ISSUE TITLE
wx.Gauge with wx.GA_VERTICAL is not working

### ISSUE THREAD

**Issue by petrasovaa** [wxWidgets/Phoenix#577]
**Operating system**:
Mac OS Sierra 10.12.6
**wxPython version**:
4.0.0b2 osx-cocoa (phoenix)
**Python version**:
Python 2.7.10

**Description of the problem**:
When using vertical style of wx.Gauge, it is still horizontal, and also it is rendered in a weird way. It segfaults when I close the application.

Use wx.Gauge demo, but change style:
```python
self.g1 = wx.Gauge(self, -1, 50, (110, 50), (25, 250), style=wx.GA_VERTICAL)
```

**Comment by RobinD42** [comment]
The vertical style is not supported by the native gauge widget on OSX/macOS.
