### ISSUE TITLE
Smaller size of ComboBox with GTK3 (Linux) causes unreadable text

### ISSUE THREAD

**Issue by HelioGuilherme66** [wxWidgets/Phoenix#585]
**Operating system**: Fedora Core 26
**wxPython version**: 4.0.0rc1
**Stock or custom build**: Custom Build [GTK2 and GTK3 here](https://robotframework.transformidea.com/RIDE/packages/Linux/Fedora_26/)
**Python version**: 2.7.13 and 3.6.2
**Stock or custom build**: Stock

**Description of the problem**: 
Selected text at ComboBox is unreadable when using GTK3 build.
To reproduce run the demo ComboBox.py. Notice the smaller white space on "default value" on GTK3.
Images taken with Python2 and GTK2 vs Python3 and GTK3 (is OK with GTK2):

![combo_box_py2_gtk2](https://user-images.githubusercontent.com/2866630/32138949-a023b750-bc34-11e7-98ce-8c0e1846255a.png)
![combo_box_py3_gtk3](https://user-images.githubusercontent.com/2866630/32138948-9ffd8206-bc34-11e7-98e8-aa8598a7af82.png)
---
To better see the effect here are screenshots of my application [RIDE](https://github.com/HelioGuilherme66/RIDE/tree/python3):

![ride_combo_box_py2_gtk2](https://user-images.githubusercontent.com/2866630/32138964-076c6e70-bc35-11e7-90b9-db5e4dd2f29e.png)
![ride_combo_box_py3_gtk3](https://user-images.githubusercontent.com/2866630/32138965-0791cb16-bc35-11e7-9a35-4376bfc51cd8.png)

**Comment by HelioGuilherme66** [comment]
For comparison with Classic here is the same screenshot taken on CentOS 7 with wxPython 2.8.12.1 (custom build) on Python 2.7.5.
![ride_combobox_centos7_wxpython2_8_12_1](https://user-images.githubusercontent.com/2866630/32148733-12c2a690-bcf3-11e7-89f2-5f258b71f61a.png)

**Comment by swt2c** [comment]
This isn't a wxPython issue, but really has to do with differences in the underlying widgets between GTK2 and GTK3.  Unfortunately, the GTK3 widgets are usually larger than their GTK2 counterparts.  Are you using hard-coded widget sizes?  If so you will probably have to adjust your sizes.
