### ISSUE TITLE
No way to identify frame on destroy

### ISSUE THREAD

**Issue by butscher** [wxWidgets/Phoenix#587]
**Operating system**: Win 7 SP1 Pro 64bit
**wxPython version**: 4.0.0rc1.dev3436+efbe850 32bit
**Stock or custom build**: Stock
**Python version**: 3.4.4 32bit
**Stock or custom build**: Stock

**Description of the problem**:

When handling a EVT_WINDOW_DESTROY event there is no way to find out if the frame returned from the event object with `GetWindow()` is identical to another frame referenced in a variable.

Example:

```python
#!python3

import wx, time, traceback

theFrame = None

class TestFrame(wx.Frame):
    def __init__(self):
        wx.Frame.__init__(self, None, -1, "Test", size=(300, 200))
        
        self.Bind(wx.EVT_WINDOW_DESTROY, OnDestroyed)
        self.Close()


def OnDestroyed(evt):
    global theFrame
    
    evt.Skip()
    print("Destroying")
    
    print("--Check1", evt.GetWindow() is theFrame)
    try:
        print("--Check2", evt.GetWindow().IsSameAs(theFrame))
    except:
        print("--Check2 fail:")
        traceback.print_exc()

    print("--Check3", evt.GetWindow() == theFrame)
    
    try:
        print("--Check4", evt.GetWindow().GetRefData() == theFrame.GetRefData())
    except:
        print("--Check4 fail:")
        traceback.print_exc()
    
    # More checks with RefData not useful
    


app = wx.App()
theFrame = TestFrame()
theFrame.Show()
app.MainLoop()
```

Output:
```
Destroying
--Check1 False
--Check2 fail:
Traceback (most recent call last):
  File "wxDestroyProblem.py", line 23, in OnDestroyed
    print("--Check2", evt.GetWindow().IsSameAs(theFrame))
RuntimeError: wrapped C/C++ object of type TestFrame has been deleted
--Check3 False
--Check4 fail:
Traceback (most recent call last):
  File "wxDestroyProblem.py", line 31, in OnDestroyed
    print("--Check4", evt.GetWindow().GetRefData() == theFrame.GetRefData())
RuntimeError: wrapped C/C++ object of type TestFrame has been deleted
```

One use case is to set the referring variable `theFrame` to `None` when the frame is destroyed but other destruction may also be handled by the same event handler function. So it must be distinguished what was destroyed.

**Comment by mesalu** [comment]
```RuntimeError: wrapped C/C++ object of type TestFrame has been deleted```
Indicates exactly what it seems to. The underlying C++ object is either already gone, or far enough in the destruction process that it is  not safe to access. This event exists to allow parent widgets to track what is happening to their children, which doesn't really apply to Frames.
The `EVT_WINDOW_DESTROY` event is placed into the queue with `wx.ProcessEvent` during deletion, meaning the event is dispatched and processed at any point during or after deletion. Whereas `EVT_CLOSE` will be queued and processed before deletion is started.

I recommend exploring different routes than using `wx.EVT_WINDOW_DESTROY`, such as binding `wx.EVT_CLOSE` to a bound member function of TestFrame
and having that event handler convey personal information (most concisely the frame's wx ID) to whatever governing entity you have to run these
identity comparisons. 

Or you could have the frame deallocate its associated resources at this time too.

**Comment by butscher** [comment]
> Indicates exactly what it seems to. The underlying C++ object is either already gone, or far enough in the destruction process that it is not safe to access.

I know why the exception arises.

Using `EVT_CLOSE` may be a problem in some situations because it can be vetoed. Receiving a `EVT_CLOSE` doesn't mean for sure that the frame will be destroyed.

The way I see to work around this is to create some kind of wrapper event handler which is created separately for each bind to a `EVT_WINDOW_DESTROY` event. The wrapper holds a separate reference to the frame it was bound. When the wrapper is called, it creates its own `wx.WindowDestroyEvent` where the event object is set to the stored reference which can then be compared. This modified event is then sent to the actual wrapped event handler.

A much simpler way could be to add a method to `wx.Object` to retrieve the address of the C++ object. This address could then be used for equality checks and as keys in dictionaries/sets to easily identify objects. For the `TestFrame` object it might be necessary to retrieve the address before destruction but that should be feasible.

**Comment by RobinD42** [comment]
You can get the address of the C++ object as an integer value with `wx.siplib.unwrapinstance(pyobj)`.  

This works only for wrapped C++ objects, is part of the SIP runtime library so it is technically an implementation detail, and so it is intentionally not documented as part of wxPython, but it should be safe to rely on it for the foreseeable future.
