### ISSUE TITLE
UltimateListCtrl broken(?) on Python 3

### ISSUE THREAD

**Issue by tekhedd** [wxWidgets/Phoenix#59]
I'm on OS/X using Python 3 and the latest release, and the code appears identical to what's currently in trunk. I'm trying to display a very simple ULC_VIRTUAL list with one string column. 

I'm getting an error on line (seriously?) 8059 of ultimatelistctrl.py: "AttributeError: 'KeyEvent' object has no attribute 'm_keyCode'" Which seems entirely likely given that the code indicates support for >= or < v2.9. :)

Apparently ULC directly accesses the raw members of KeyEvent, and... maybe these are different in the v3 port? No idea.

Normally I'd submit a patch but I don't have a wxPython build environment at the moment.

**Comment by swt2c** [comment]
Can you provide a sample program that reproduces the error?

**Comment by tekhedd** [comment]
Certainly; I'll get an example together this weekend. It should be pretty simple: instantiate a list, focus, and hit some keys. :) It manually copies the member properties of KeyEvent, which of course change every major version.

**Comment by swt2c** [comment]
Did you have a chance to pull together a sample reproducer?

**Comment by tekhedd** [comment]
Sorry, I straight up forgot. After work today I promise. (I'm getting the sticky notes out NOW.)

**Comment by RobinD42** [comment]
Yep, `m_keyCode` is no longer part of the public interface.  It should be changed to GetKeyCode().

**Comment by tekhedd** [comment]
OK, now I don't want you to be overwhelmed by the complexity of this code, but I'm just going to paste it in here. ;)

`#!python3
import wx
from wx.lib.agw import ultimatelistctrl as ULC 

class Frame(wx.Frame):
    def __init__(self):
        wx.Frame.__init__(self, None, title = "Set focus to the empty list and press any keyboard key")

        ctl = ULC.UltimateListCtrl(self, agwStyle = ULC.ULC_REPORT)
        return
    
app = wx.App() 
top = Frame()
top.Show()
app.MainLoop()
`

Seriously, just instantiate an empty list, set focus to it, and hit any keyboard key. I'm doing on OSX, so you might have to add something to make the list focusable on other platforms, dunno.

I have some understanding of how to use Events in wx, but I don't understand what ULC is trying to accomplish in this piece of code--I guess there's no portable way to clone the KeyEvent and do... unsavory things with it? *Because8 I have some understanding of Events, I understand that the built in event system often does not provide a way to send events to the window/control that you want. I'm running into this now myself...but I don't understand what is occurring in this piece of code.

Hope this helps.

**Comment by RobinD42** [comment]
I think the usages of that function can be replaced with a call to `Clone` instead.  For example in the caller replace 
```
    ke = wx.KeyEvent(event.GetEventType())
    self.SetEventAttrs(event, ke)
```

with

```
    ke = event.Clone()
```

Give that a try and let us know if it works.

**Comment by swt2c** [comment]
That does resolve the traceback at least.  :-)  Not knowing that much about UltimateListCtrl, I can't tell that easily if it still works, though.

**Comment by tekhedd** [comment]
I'll give it a try. It did seem to work with mouse controls at the time.

**Comment by tekhedd** [comment]
Finally had time to try it. I can confirm that ULC works very nicely now, at least in virtual REPORT mode. I'm not using any of the advanced features yet (images etc). I'll try to bring PRs if I find anything broken.

My application does some custom navigation; I can confirm that (on OSX) it correctly propagates key events, correctly handles focus traversal, sends the correct focus events, and respects focus-refusal by overriding AcceptsFocus etc. (The standard ListBox does not. Maybe I should open a ticket? But that would go upstream to wxWindows I think.) 

And thank you.
