### ISSUE TITLE
error compiling on win10

### ISSUE THREAD

**Issue by mprosperi** [wxWidgets/Phoenix#590]
**Operating system**: win10
**wxPython version**: wxPython-4.0.0rc1.dev3450+0fb1ce9.tar.gz
**Stock or custom build**: custom
**Python version**: 3.5.4
**Stock or custom build**: custom (debug)

**Description of the problem**: error while compiling wxwidgets

python_d.exe C:\Users\mypc\Documents\python\wxPython-4.0.0rc1.dev3450+0fb1ce9.tar\wxPython-4.0.0rc1.dev3450+0fb1ce9\build.py build install

[omissis]

volume.cpp
        rc /fovcFIXME_mswudll_x64\basedll_version.res  /d WIN32  /d _CRT_SECURE_NO_DEPRECATE=1 /d _CRT_NON_CONFORMING_SWPRINTFS=1 /d _SCL_SECURE_NO_WARNINGS=1 /d __NO_VC_CRTDBG__  /d __WXMSW__   /d NDEBUG    /d _UNICODE  /i ..\..\lib\vcFIXME_x64_dll\mswu /i ..\..\include  /d WXBUILDING /d WXDLLNAME=wxbase30u_vcFIXME_x64  /i ..\..\src\tiff\libtiff /i ..\..\src\jpeg /i ..\..\src\png /i ..\..\src\zlib /i ..\..\src\regex /i ..\..\src\expat\lib /d wxUSE_GUI=0 /d WXMAKINGDLL_BASE /d wxUSE_BASE=1 ..\..\src\msw\version.rc
"rc" non è riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.
NMAKE : fatal error U1077: 'rc' : codice restituito '0x1'
Stop.
Error building
ERROR: failed building wxWidgets

**Comment by RobinD42** [comment]
Which version of Visual Studio do you have installed? Is there a rc.exe present in that Visual Studio installation? It should be in the same place that cl.exe (the C/C++ compiler) is found, but if something unexpected happened with the install then perhaps it isn't available or is somewhere else.

Also, probably not related, but you may want to try running build.py with python.exe and passing the --debug flag. That is the way that I usually do things so there may be some case that was missed with running without the flag and using python_d.exe.

**Comment by infinity77** [comment]
@mprosperi @swt2c is this still the case? I assumed compilation on Win10 works now as CI builds seems to be working…
