### ISSUE TITLE
missing DataViewCtrl.Select(item)

### ISSUE THREAD

**Issue by mprosperi** [wxWidgets/Phoenix#591]
**Operating system**: win10
**wxPython version**: 4.0rc1
**Stock or custom build**: stock
**Python version**: 2.7
**Stock or custom build**: stock

**Description of the problem**: Select(item) method for DataViewCtrl is present in Classic but missing in Phoenix and the removal seems not documented

**Comment by RobinD42** [comment]
Are you sure?

```
>>> import wx.dataview
>>> wx.dataview.DataViewCtrl.Select
<built-in function Select>
>>> wx.dataview.DataViewCtrl.Select.__doc__
'Select(item)\n\nSelect the given item.'
>
```

Also, https://docs.wxpython.org/wx.dataview.DataViewCtrl.html#wx.dataview.DataViewCtrl.Select
