### ISSUE TITLE
Ultimatelistctrl error getting data

### ISSUE THREAD

**Issue by floatingshed** [wxWidgets/Phoenix#592]
**Operating system**: win10
**wxPython version**: 4.0.0b2
**Stock or custom build**: stock
**Python version**: 3.6.3
**Stock or custom build**: stock

**Description of the problem**: Clicking any item in the report or virtual demo returns:
```
Traceback (most recent call last):
File "agw\UltimateReportDemo.py", line 802, in OnItemDeselected
self.log.write("OnItemDeselected: %d\n" % evt.Index)
AttributeError: Index
Traceback (most recent call last):
File "agw\UltimateReportDemo.py", line 782, in OnItemSelected
self.currentItem = event.Index
AttributeError: Index
```

**Comment by swt2c** [comment]
You can use `GetIndex()` instead.

**Comment by floatingshed** [comment]
I don't know how to do that.
This is the official demo, surely it should work?

**Comment by RobinD42** [comment]
The change was reverted, reopening ticket.
