### ISSUE TITLE
Crash when comparing DataViewItem with None

### ISSUE THREAD

**Issue by jensgoe** [wxWidgets/Phoenix#595]
**Operating system**: Win7 64bit
**wxPython version**: (4, 0, 0, 'b2')
**Stock or custom build**: stock
**Python version**: 2.7.13 (64bit)
**Stock or custom build**: stock

**Description of the problem**:
Crash when comparing a DataViewItem with None

```python
# Put code sample here
import wx.dataview as dv
dv.NullDataViewItem == None
```

**Comment by swt2c** [comment]
The same thing happens in Classic, so it's at least not a new issue.  :-)

**Comment by jensgoe** [comment]
Yes thats right. In classic i fixed myself by implementing the __eq__ and __neq__ operators for wxDataViewItem.
```
    %extend {
        bool __eq__(const wxDataViewItem* other) { return other ? (*self == *other) : false; }
        bool __ne__(const wxDataViewItem* other) { return other ? (*self != *other) : true;  }
    }
```
I currently don't know how to do it with sip.

**Comment by jensgoe** [comment]
I didn't see this before, but the same with wxTreeListItem.
etg/treelist.py

**Comment by RobinD42** [comment]
Reopening
