### ISSUE TITLE
PropertyGrid is missing

### ISSUE THREAD

**Issue by firodj** [wxWidgets/Phoenix#60]
I'am using this sanpshot: http://wxpython.org/Phoenix/snapshot-builds/wxPython_Phoenix-3.0.3.dev1964+f780b21-cp27-cp27m-win32.whl

and there is no `wx.propgrid`

**Comment by swt2c** [comment]
That appears to still be on the to-do list for Phoenix:
https://github.com/wxWidgets/Phoenix/blob/master/TODO.txt#L134

**Comment by firodj** [comment]
oic, thx @swt2c
