### ISSUE TITLE
Selected text is not highligthed in Grid Cell element on GTK3 (Linux) builds.

### ISSUE THREAD

**Issue by HelioGuilherme66** [wxWidgets/Phoenix#610]
**Operating system**: Fedora Core 26
**wxPython version**: 4.0.0rc1
**Stock or custom build**: Custom Build [GTK2 and GTK3 here](https://robotframework.transformidea.com/RIDE/packages/Linux/Fedora_26/)
**Python version**: 2.7.14 and 3.6.2
**Stock or custom build**: Stock

**Description of the problem**: 
Selected text at GridCell is not highlighted on GTK3 build.
To reproduce run the demo GridCustEditor.py (or GridSimple.py) and double-click a cell containing text (or select text in edit mode). The text is not highlighted on GTK3, but it is OK on GTK2.
Images taken with Python3 and GTK2 vs Python2 and GTK3:

With GTK2:
![grid_wxgtk2](https://user-images.githubusercontent.com/2866630/32751718-b69b99f8-c8be-11e7-841c-89ec5936d3dd.png)

With GTK3:
![screenshot_20171113_214759](https://user-images.githubusercontent.com/2866630/32751675-9cf65150-c8be-11e7-9cc5-1fb642ddeb78.png)

**Comment by RobinD42** [comment]
It seems to be working fine here...

**Comment by HelioGuilherme66** [comment]
Strange.
You think it is because I am using KDE on Fedora?

**Comment by swt2c** [comment]
It's not KDE.  I also see it on Fedora, but with Gnome Shell.

**Comment by swt2c** [comment]
This is another wxWidgets issue.  I can reproduce it with the grid sample.

**Comment by swt2c** [comment]
Filed https://trac.wxwidgets.org/ticket/18005

**Comment by swt2c** [comment]
Fixed upstream.
