### ISSUE TITLE
TextEntryDialog keeps the same TextCtrl around in memory, FindWindowById gets wrong object

### ISSUE THREAD

**Issue by blitzmann** [wxWidgets/Phoenix#611]
**Operating system**: Windows 10
**wxPython version**: 4.0.0b2
**Stock or custom build**: Stock
**Python version**: 3.6
**Stock or custom build**: Stock

**Description of the problem**:

I have an old customization of the wx.TextEntryDialog class that allows me to attach my own Validator to the TextCtrl inside of it. The method was taken from this thread: http://wxpython-users.1045709.n5.nabble.com/Adding-Validation-to-wx-TextEntryDialog-td2371082.html

A bit of background: it basically gets the TextCtrl by a static ID. This worked well, and instead of creating my own dialog, I went with this method.

However, I'm having issues with it on wxPython v4. It seems that the TextCtrl is not re-instantiated when the dialog is created; it still references any previously opened ones, which is different behavior from v3.0.2.0 (python 2.7). Apparently, this causes the Validator to not run it's `Validate()` method.

EDIT: After a bit more testing, apparently it is re-instantiated (can verify by iterating over `self.Children`), but the `FindWindowById` doesn't bring back the most recent one, instead of brings back the first instantiated one.

The script below shows this. it contains my custom dialog, as well as a control (taken from the demo) which works. The validator is also taken from the demo. Take note of the `print(self, self.txtctrl)` in `TextEntryValidatedDialog`. 

Reproduction steps:
1) Click "Pop my Dialog"
2) Attempt submitting without entering any text. Note that the error happens as expected.
3) Close dialog.
4) Click "Pop my Dialog" again
5) Attempt to submit data - it goes through without the Validate() method running

The print statements when I pop the dialog look like this:

```
<__main__.TextEntryValidatedDialog object at 0x02E5CA80> <wx._core.TextCtrl object at 0x02E5CAD0>
<__main__.TextEntryValidatedDialog object at 0x02E5CB20> <wx._core.TextCtrl object at 0x02E5CAD0>
<__main__.TextEntryValidatedDialog object at 0x02E5CBC0> <wx._core.TextCtrl object at 0x02E5CAD0>
```

Note how it's a different object for each dialog, however the TextCtrl references the same thing in memory.

I would think a new TextCtrl would be instantiated with the old control destroyed, as it is in 3.0.2.0:

```
(<TextEntryValidatedDialog; proxy of <Swig Object of type 'wxTextEntryDialog *' at 0x88f5e30> >, <wx._controls.TextCtrl; proxy of <Swig Object of type 'wxTextCtrl *' at 0x3b29540> >)
(<TextEntryValidatedDialog; proxy of <Swig Object of type 'wxTextEntryDialog *' at 0x88f4228> >, <wx._controls.TextCtrl; proxy of <Swig Object of type 'wxTextCtrl *' at 0x3b2a828> >)
(<TextEntryValidatedDialog; proxy of <Swig Object of type 'wxTextEntryDialog *' at 0x88f4ac8> >, <wx._controls.TextCtrl; proxy of <Swig Object of type 'wxTextCtrl *' at 0x3b27e90> >)
```

Additionally, if I were to use this block of code instead of my current "okay button" logic:
```
if dlg.ShowModal() == wx.ID_OK:
    print(dlg.txtctrl.GetValue().strip())
```

It will only ever show the first value entered into the text box, regardless of how many times you spawn the dialog and change it, further supporting the fact that the TextCtrl is simply not being destroyed.

### Workaround
This are two workarounds currently:
* Create your own dialog
* Use the following in place of the `FindWindowbyId`

```
  for x in self.Children:
      if isinstance(x, wx.TextCtrl):
          self.txtctrl = x
```

Granted, I'm probably overly complicating it, and also am probably one of the only idiots trying to utilize the TextEntryDialog in this way. However, I'm curious as to why this object seems cached in memory when everything tells me it should bring back the actual in-use TextCtrl, and I also just wanted to bring this up for attention in case it wasn't intended to function this way. :)

Thanks!

### Script for wxPython 4

```python
import wx


#####
# Classes from Demo
#####

class TextObjectValidator(wx.Validator):
    """ This validator is used to ensure that the user has entered something
        into the text object editor dialog's text field.
    """

    def __init__(self):
        """ Standard constructor.
        """
        wx.Validator.__init__(self)

    def Clone(self):
        """ Standard cloner.

            Note that every validator must implement the Clone() method.
        """
        return TextObjectValidator()

    def Validate(self, win):
        """ Validate the contents of the given text control.
        """
        textCtrl = self.GetWindow()
        text = textCtrl.GetValue()

        if len(text) == 0:
            wx.MessageBox("A text object must contain some text!", "Error")
            textCtrl.SetBackgroundColour("pink")
            textCtrl.SetFocus()
            textCtrl.Refresh()
            return False
        else:
            textCtrl.SetBackgroundColour(
                wx.SystemSettings.GetColour(wx.SYS_COLOUR_WINDOW))
            textCtrl.Refresh()
            return True

    def TransferToWindow(self):
        """ Transfer data from validator to window.

            The default implementation returns False, indicating that an error
            occurred.  We simply return True, as we don't do any data transfer.
        """
        return True  # Prevent wxDialog from complaining.

    def TransferFromWindow(self):
        """ Transfer data from window to validator.

            The default implementation returns False, indicating that an error
            occurred.  We simply return True, as we don't do any data transfer.
        """
        return True  # Prevent wxDialog from complaining.

class TestValidateDialog(wx.Dialog):
    def __init__(self, parent, validator=None):
        wx.Dialog.__init__(self, parent, -1, "Validated Dialog")

        self.SetAutoLayout(True)
        VSPACE = 10

        fgs = wx.FlexGridSizer(cols=2)

        fgs.Add((1, 1))
        fgs.Add(wx.StaticText(self, -1,
                              "These controls must have text entered into them.  Each\n"
                              "one has a validator that is checked when the Ok\n"
                              "button is clicked."))

        fgs.Add((1, VSPACE))
        fgs.Add((1, VSPACE))

        label = wx.StaticText(self, -1, "First: ")
        fgs.Add(label, 0, wx.ALIGN_RIGHT | wx.CENTER)

        self.txtctrl = wx.TextCtrl(self, -1, "")
        self.txtctrl.SetValidator(validator())
        fgs.Add(self.txtctrl)

        buttons = wx.StdDialogButtonSizer()  # wx.BoxSizer(wx.HORIZONTAL)
        b = wx.Button(self, wx.ID_OK, "OK")
        b.SetDefault()
        buttons.AddButton(b)
        buttons.AddButton(wx.Button(self, wx.ID_CANCEL, "Cancel"))
        buttons.Realize()

        border = wx.BoxSizer(wx.VERTICAL)
        border.Add(fgs, 1, wx.GROW | wx.ALL, 25)
        border.Add(buttons, 0, wx.GROW | wx.BOTTOM, 5)
        self.SetSizer(border)
        border.Fit(self)
        self.Layout()

#####
# Custom Classes
#####

# Custom class that forces the TextEntryDialog to accept a Validator on the TextCtrl
class TextEntryValidatedDialog(wx.TextEntryDialog):
    def __init__(self, parent, validator=None, *args, **kargs):
        wx.TextEntryDialog.__init__(self, parent, *args, **kargs)
        self.parent = parent

        self.txtctrl = self.FindWindowById(3000)
        print(self, self.txtctrl)
        if validator:
            self.txtctrl.SetValidator(validator())

class MyForm(wx.Frame):
    def __init__(self):
        wx.Frame.__init__(self, None, wx.ID_ANY, "List Control Tutorial")

        # Add a panel so it looks the correct on all platforms
        panel = wx.Panel(self, wx.ID_ANY)
        self.index = 0

        btn = wx.Button(panel, label="Pop Demo Dialog")
        btn.Bind(wx.EVT_BUTTON, self.pop_demo_dialog)

        btn2 = wx.Button(panel, label="Pop My Dialog")
        btn2.Bind(wx.EVT_BUTTON, self.pop_my_dialog)

        sizer = wx.BoxSizer(wx.VERTICAL)
        sizer.Add(btn, 0, wx.ALL | wx.CENTER, 5)
        sizer.Add(btn2, 0, wx.ALL | wx.CENTER, 5)
        panel.SetSizer(sizer)

    def pop_my_dialog(self, event):
        dlg = TextEntryValidatedDialog(self, TextObjectValidator, "Enter some text", "Title")
        dlg.txtctrl.SetInsertionPointEnd()
        dlg.CenterOnParent()

        if dlg.ShowModal() == wx.ID_OK:
            print("Entered Value: " + dlg.txtctrl.GetValue().strip())

    def pop_demo_dialog(self, event):
        dlg = TestValidateDialog(self, TextObjectValidator)
        dlg.txtctrl.SetInsertionPointEnd()
        dlg.CenterOnParent()

        if dlg.ShowModal() == wx.ID_OK:
            print("Entered Value: " + dlg.txtctrl.GetValue().strip())


if __name__ == "__main__":
    app = wx.App(False)
    frame = MyForm()
    frame.Show()
    app.MainLoop()
```

**Comment by david-hughes** [comment]
Dialogs and their contents are not destroyed when you exit them. That is so their results can be accessed afterwards as you do. So until you specify **dlg.Destroy()** then each instance - with its associated TxtCtrl (id=3000) - will still be present.

Also, the behaviour of FindWindowById has changed a little:  **

       wx.Window.FindWindowById(id, parent=None)

If parent is not specified then ALL windows in your application will be searched and your undestroyed TxtCtrl's will, presumably, be discovered in the order of their creation. So, to find the one associated with your most recent dialog instance, use:

     wx.Window.FindWindowById(3000, parent=self) 

** I was badly bitten by this myself once!

Regards,
David Hughes

**Comment by blitzmann** [comment]
Thanks David for the quick on concise response! I will test these out.

> So until you specify dlg.Destroy() then each instance - with its associated TxtCtrl (id=3000) - will still be present.

IIRC, I did try this, but `FindWindowById` was still getting the previous object in memory. Will try again later tonight. :)

**Comment by blitzmann** [comment]
` wx.Window.FindWindowById(3000, parent=self)` works great, but `dlg.Destroy()` doesn't do anything. Good to know though, thanks! Will close this now as `FindWindowById` is known to have changed functionality. :)

**Comment by david-hughes** [comment]
The following works for me: 

    def pop_my_dialog(self, event):
        dlg = TextEntryValidatedDialog(self, TextObjectValidator, "Enter some text", "Title")
        dlg.txtctrl.SetInsertionPointEnd()
        dlg.CenterOnParent()

        if dlg.ShowModal() == wx.ID_OK:
            print("Entered Value: " + dlg.txtctrl.GetValue().strip())
        dlg.Destroy()
