### ISSUE TITLE
wx.grid.GetSelectionBlockTopLeft() and GetSellectedCells()

### ISSUE THREAD

**Issue by worn76** [wxWidgets/Phoenix#615]
**Operating system**: Windows 7
**wxPython version**: 4.0.0b2
**Stock or custom build**: pip install
**Python version**: 3.6.1
**Stock or custom build**: anaconda 4.4.0

**Description of the problem**:
I've implemented copy and paste using the following code
https://stackoverflow.com/questions/28509629/work-with-ctrl-c-and-ctrl-v-to-copy-and-paste-into-a-wx-grid-in-wxpython

Now I'm trying to convert my code from python2 to python3, but I got problem with GetSelectionBlockTopLeft() and GetSelectionBlockBottomRight()

I thought that I can use GetSelectedCells() instead. but I didn't work.

```python
# -*- coding: UTF-8 -*-

from __future__ import print_function
import wx
import wx.grid as  gridlib
 
class MyForm(wx.Frame):
    def __init__(self):
        wx.Frame.__init__(self, None, wx.ID_ANY, "Grid Test")
 
        panel = wx.Panel(self, wx.ID_ANY)
        self.grid1 = gridlib.Grid(panel)
        self.grid1.CreateGrid(3,2)
 
        sizer = wx.BoxSizer(wx.VERTICAL)
        sizer.Add(self.grid1, 1, wx.EXPAND, 5)

        self.Bind(wx.EVT_CHAR_HOOK, self.onkey)
        panel.SetSizer(sizer)
 
    def onkey(self, event):
        print('selected cells', self.grid1.GetSelectedCells())
        print(self.grid1.GetSelectionBlockTopLeft())
        print(self.grid1.GetSelectionBlockBottomRight())
        print(list(self.grid1.GetSelectionBlockTopLeft()))
        print(list(self.grid1.GetSelectionBlockBottomRight()))

if __name__ == "__main__":
    app = wx.PySimpleApp()
    frame = MyForm().Show()
    app.MainLoop()

```
after select grid A1:B3, hit any key
python 2
selected cells []
[(0, 0)]
[(2, 1)]
[(0, 0)]
[(2, 1)]

python 3
selected cells GridCellCoordsArray: []
GridCellCoordsArray: [GridCellCoords(0, 0)]
GridCellCoordsArray: [GridCellCoords(2, 1)]
[GridCellCoords(7, 0)]
[GridCellCoords(7, 1)]

How can I get the selected region and use it?
Can I get [[0,0], [0,1], [1,0], [1,1], [2,0], [2,1]] or [0,0] and [2,1]

**Comment by DietmarSchwertberger** [comment]
This report has two components:
 - How to get the selected cells?
 - Why does print(list(...)) print incorrect row numbers?

The first question would have been more appropriate for the mailing list.
I have similiar code which you can modify to solve your problem. Basically you need to have a look at both SelectedCells and SelectionBlock....
```python
if self.grid.SelectedCells:
    # non-contiguous
    for cell in self.grid.SelectedCells:
        selected_rows.add(cell[0])
        selected_cols.add(cell[1])
    if self.grid.SelectionBlockTopLeft:
        for tl, br in zip(self.grid.SelectionBlockTopLeft, self.grid.SelectionBlockBottomRight):
            top,left = tl
            bottom,right = br
            selected_cols.update( range(left,right+1) )
            selected_rows.update( range(top,bottom+1) )
```

The second item really seems to be a bug. I can see this here as well, but not always.
Currently I don't see it when running under the Wing IDE debugger, but when trying this afternoon on another installation, I got different results without changing the selection inbetween:
```python

>>> list( self.grid1.GetSelectionBlockTopLeft() )
[GridCellCoords(22, 0)]
>>> list( self.grid1.GetSelectionBlockTopLeft() )
[GridCellCoords(86, 0)]
```
Strange enough, the 'normal' iteration is working fine:
```python
>>> for tl in self.grid1.GetSelectionBlockTopLeft(): print(tl)
(0, 0)
>>> for tl in self.grid1.GetSelectionBlockTopLeft(): print(tl)
(0, 0)
```

**Comment by swt2c** [comment]
I had a completely different interpretation of worn56's issue.  :-)  What I noticed was that the output differs between Classic and Phoenix - it appears that in Classic, there was some helper code that converted GridCellCoords into a Python list.  That probably needs to be implemented in Phoenix.

**Comment by RobinD42** [comment]
The return value of those methods is a `wxGridCellCoordsArray` and instead of auto-converting it to a list, Phoenix has an actual wrapper type for `GridCellCoordsArray` which has some list-like methods added to it. Using `list()` to convert it is the correct thing to do if a real list is needed.

**Comment by DietmarSchwertberger** [comment]
The bug is that the list conversion at least sometimes returns `GridCellCoords` that are not initalized correctly.
If you look at the printed output of worn76, then the second last row is `[GridCellCoords(7, 0)]` where it should be `[GridCellCoords(0, 0)]` .
Probably the returned wrapper is initialized with a wrong pointer.

When I run his code in the Wing debugger, I get something like this at the breakpoint (note that this is from just one run, i.e. nothing modified inbetween and still I get different row and col numbers):
```python
>>> print(self.grid1.GetSelectionBlockTopLeft())
GridCellCoordsArray: [GridCellCoords(0, 0)]
>>> print(list(self.grid1.GetSelectionBlockTopLeft()))
[GridCellCoords(12, 0)]
>>> l = list(self.grid1.GetSelectionBlockTopLeft())
l[0]
>>> GridCellCoords(38535000, 5439489)
l[0]
>>> GridCellCoords(38535000, 5439489)
l[0]
>>> GridCellCoords(38535000, 5439489)
l[0]
>>> GridCellCoords(54452392, 5439489)
l[0]
>>> GridCellCoords(54452392, 5439489)
l[0]
>>> GridCellCoords(54452392, 5439489)
l[0]
>>> GridCellCoords(54452392, 5439489)
>>> l[0]
GridCellCoords(54452392, 5439489)
>>> l[0]
GridCellCoords(54460415, 5439489)
>>> l[0][0]
54460415
>>> l[0][0]
38534400
>>> l[0][0]
38534400
>>> l[0][0]
38534400
>>> l[0][0]
1441874
>>> l[0][0]
54481544
 
>>> l[0][0], l[0][1]
(54428856, 5439488)
>>> l[0][0], l[0][1]
(54428856, 5439488)
>>> l[0][0], l[0][1]
(54428856, 5439488)
>>> l[0][0], l[0][1]
(54428856, 5439488)
>>> l[0][0], l[0][1]
(54394962, 5439488)
>>> l[0][0], l[0][1]
(54483144, 5439489)
>>> l[0][0], l[0][1]
(54483144, 5439489)
>>> l[0][0], l[0][1]
(54483144, 5439489)
>>> l[0][0], l[0][1]
(54483144, 5439489)
>>> l[0][0], l[0][1]
(54483144, 5439489)
>>> l[0][0], l[0][1]
(54460488, 5439489)
>>> l[0][0], l[0][1]
(39190628, 5439561)
>>> l[0][0], l[0][1]
(54455672, 5439488)
>>> l[0][0], l[0][1]
(54455672, 5439488)
```

**Comment by RobinD42** [comment]
Please try it with a current snapshot build. There was a change a few weeks ago (#568) that will have an effect here.

**Comment by worn76** [comment]
I didn't know that the following two methods are different.
1. drag a region to select cells
2. click cells with control key down.

I thought that GetSelectedCells will return values regardless of the selection methods.
Is this a bug or intended?
Still I can't understand why list(self.grid1.GetSelectionBlockTopLeft()) returns [GridCellCoords(7, 0)] not [GridCellCoords(0, 0)] like DietmarSchwertberger said.

when I did with 1st way(drag from A1 to B2) python3 result is
   get selected cells GridCellCoordsArray: []
   GridCellCoordsArray: [GridCellCoords(0, 0)]
   GridCellCoordsArray: [GridCellCoords(1, 1)]
   [GridCellCoords(5, 0)]
   [GridCellCoords(5, 1)]
with 2nd way(click A1, A2, B1, B2 with control down) python3 result
   selected cells GridCellCoordsArray: [GridCellCoords(0, 0), GridCellCoords(0, 1), GridCellCoords(1, 0), 
   GridCellCoords(1, 1), GridCellCoords(2, 0), GridCellCoords(2, 1)]
   GridCellCoordsArray: []
   GridCellCoordsArray: []
   []
   []

@RobinD42 Actually I don't know how to try with a current snapshot build. Should I download grid.py, tweeaker_tools.py from [#568](https://github.com/wxWidgets/Phoenix/pull/568/commits/66b4a7966dff3fd6937858a95df683612c600f71#diff-09f662e14e1b954b1e05d27e22147eef) and copy to my local folder(C:\ProgramData\Anaconda3\Lib\site-packages\wx)?

**Comment by DietmarSchwertberger** [comment]
@RobinD42 : (4, 0, 0, 'rc1.dev3456+e141c95') seems to work for me

@worn76 : You can find the snapshots here: https://wxpython.org/Phoenix/snapshot-builds/
The documentation is here: https://docs.wxpython.org/wx.grid.Grid.html#wx.grid.Grid.GetSelectedCells

**Comment by worn76** [comment]
@DietmarSchwertberger with wxPython-4.0.0rc1.dev3503+d3ac0d6-cp36-cp36m-win_amd64.whl, 
list(self.grid1.GetSelectionBlockTopLeft()) works fine.

> selected cells GridCellCoordsArray: []
> GridCellCoordsArray: [GridCellCoords(0, 0)]
> GridCellCoordsArray: [GridCellCoords(2, 1)]
> [GridCellCoords(0, 0)]
> [GridCellCoords(2, 1)]
