### ISSUE TITLE
Cannot unbind events 

### ISSUE THREAD

**Issue by blitzmann** [wxWidgets/Phoenix#624]
**Operating system**: Windows 10
**wxPython version**: v4.0.0b2
**Stock or custom build**: stock
**Python version**: 3.6
**Stock or custom build**: stock

**Description of the problem**:

I cannot seem tog get `.Unbind` to actually unbind. It seems to always return false (meaning unsuccessful). Not sure if there's a way to get wxPython to tell me why it was unsuccessful.

Attached is a sample demonstrating this issue. If you open the frame, then click the button to Post the event, the new frame handles the event as expected (prints `Handling event!`). When closing the child frame, it's supposed to Unbind from the event. However, this returns False and, upon trying to post it again, the event is still handled by the child frame.

This is different behavior from 3.0.2.0 (on python 2.7) where the Unbind returns True, and the old frame object (which has since been closed) does not attempt to handle the event. I use this convention in my application to Unbind from events when a window closes or a certain part of the application is hidden.

```python
import wx
import wx.lib.newevent

MyCustomEvent, EVT_CUSTOM = wx.lib.newevent.NewEvent()

class MyFrame(wx.Frame):
    def __init__(self, parent):
        wx.Frame.__init__(self, parent, title="Other frame", size=(520, 390))
        self.mainFrame = parent

        self.mainFrame.Bind(EVT_CUSTOM, self.HandleEvent)
        self.Bind(wx.EVT_CLOSE, self.close)

        self.SetMinSize(self.GetSize())

    def close(self, event):
        print(self.mainFrame.Unbind(EVT_CUSTOM, handler=self.HandleEvent))
        event.Skip()

    def HandleEvent(self, evt):
        print("Handling event!")
        evt.Skip()


class MainFrame(wx.Frame):
    def __init__(self,*args):
        wx.Frame.__init__(self,*args)
        mainSizer = wx.BoxSizer(wx.VERTICAL)
        b = wx.Button(self,-1,"Open Frame")
        b.Bind(wx.EVT_BUTTON,self.openOtherFrame)
        b2 = wx.Button(self, -1, "PostEvent")
        b2.Bind(wx.EVT_BUTTON, self.postEvent)

        mainSizer.Add(b, 0, wx.ALL | wx.EXPAND, 2)
        mainSizer.Add(b2, 0, wx.ALL | wx.EXPAND, 2)

        self.SetSizer(mainSizer)

    def openOtherFrame(self, event):
        self.otherFrame = MyFrame(self)
        self.otherFrame.Show()

    def postEvent(self, evt):
        print("Posting!")
        wx.PostEvent(self, MyCustomEvent(data="test"))
        evt.Skip()

a = wx.App(redirect=False)
f = MainFrame(None,-1,"Main Frame")
f.Show()
a.MainLoop()
```

**Comment by blitzmann** [comment]
Here is n updated example that utilizes a TextCtrl in the child frame to write text to the control when the event is triggered. This causes an error when the child frame is closed because the C++ object is destroyed, but the python object sticks around. This is why I use `Unbind` in the application to remove the handler for the events, so that errors don't happen when the window is closed.

```python
import wx
import wx.lib.newevent

MyCustomEvent, EVT_CUSTOM = wx.lib.newevent.NewEvent()

class MyFrame(wx.Frame):
    def __init__(self, parent):
        wx.Frame.__init__(self, parent, title="Other frame", size=(520, 390))
        self.mainFrame = parent

        self.mainFrame.Bind(EVT_CUSTOM, self.HandleEvent)
        self.Bind(wx.EVT_CLOSE, self.close)

        mainSizer = wx.BoxSizer(wx.VERTICAL)

        self.txtCtrl = wx.TextCtrl(self, wx.ID_ANY, "",
                                         wx.DefaultPosition, wx.DefaultSize,
                                         wx.TE_AUTO_URL | wx.TE_MULTILINE | wx.TE_READONLY | wx.DOUBLE_BORDER | wx.TRANSPARENT_WINDOW)
        self.SetMinSize(self.GetSize())

        mainSizer.Add(self.txtCtrl, 1, wx.ALL | wx.EXPAND, 2)

        self.SetSizer(mainSizer)

    def close(self, event):
        print(self.mainFrame.Unbind(EVT_CUSTOM, handler=self.HandleEvent))
        event.Skip()

    def HandleEvent(self, evt):
        self.txtCtrl.AppendText("Handling Event!\n")
        evt.Skip()


class MainFrame(wx.Frame):
    def __init__(self,*args):
        wx.Frame.__init__(self,*args)
        mainSizer = wx.BoxSizer(wx.VERTICAL)
        b = wx.Button(self,-1,"Open Frame")
        b.Bind(wx.EVT_BUTTON,self.openOtherFrame)
        b2 = wx.Button(self, -1, "PostEvent")
        b2.Bind(wx.EVT_BUTTON, self.postEvent)

        mainSizer.Add(b, 0, wx.ALL | wx.EXPAND, 2)
        mainSizer.Add(b2, 0, wx.ALL | wx.EXPAND, 2)

        self.SetSizer(mainSizer)

    def openOtherFrame(self, event):
        self.otherFrame = MyFrame(self)
        self.otherFrame.Show()

    def postEvent(self, evt):
        print("Posting!")
        wx.PostEvent(self, MyCustomEvent(data="test"))
        evt.Skip()

a = wx.App(redirect=False)
f = MainFrame(None,-1,"Main Frame")
f.Show()
a.MainLoop()
```

**Comment by RobinD42** [comment]
I'm checking into this, but in the meantime you can easily check if the C++ part of a widget still exists like this:

```
    def HandleEvent(self, evt):
        if self.txtCtrl:
            self.txtCtrl.AppendText("Handling Event!\n")
        evt.Skip()
```

**Comment by blitzmann** [comment]
> I'm checking into this, but in the meantime you can easily check if the C++ part of a widget still exists like this:

Yep, that's the only workaround so far that I'm aware of. But I would rather not have to do that with all my events and instead properly clean up the bound handlers when they are destroyed. Looking forward to your response after looking into it :) thanks!

**Comment by RobinD42** [comment]
TIL: each time you do `obj.Method` you get a new instance of the bound method type, which means in C++ I can have two different PyObject pointer values referring to the same method, which means that `win.Unbind` fails even if you pass it the same `self.HandlerMethod` as was used with the `Bind` because it was just comparing the pointers.

**Comment by RobinD42** [comment]
Another possible workaround for you while waiting for the fix, if there's no more than one binding for the event type on the window, is to simply not specify the handler.  That will work in the current builds.

**Comment by blitzmann** [comment]
> Another possible workaround for you while waiting for the fix, if there's no more than one binding for the event type on the window, is to simply not specify the handler. That will work in the current builds.

Excellent, I don't know why I didn't try that! Thanks for the quick responses and maintaining the project 👍
