### ISSUE TITLE
how python install Phoenix

### ISSUE THREAD

**Issue by SwpuEsine** [wxWidgets/Phoenix#628]
i am a newer in Phoenix, and i want to know how to use Phoenix in python

**Comment by blitzmann** [comment]
On Windows and OSX, it's usually as easy as `pip install wxPython`. On linux it can be a little trickier and you may need to build it yourself, unless you have one of these systems:

https://extras.wxpython.org/wxPython4/extras/linux/gtk3/

If so, you can download the wheel file and use pip to install manually from file.

**Comment by RobinD42** [comment]
See also:

* https://wxpython.org/pages/downloads/
* https://wxpython.org/blog/2017-08-17-builds-for-linux-with-pip/
