### ISSUE TITLE
Crash if wx.Timer isn't stopped before window closes

### ISSUE THREAD

**Issue by blitzmann** [wxWidgets/Phoenix#632]
**Operating system**: Windows 10
**wxPython version**: 4.0b2
**Stock or custom build**: stock
**Python version**: 3.6
**Stock or custom build**: stock

**Description of the problem**:

If there is a `wx.Timer` running in a window, that timer must be stopped with the OnClose event, otherwise there is a crash. Not sure if it's a wxPython issue, or an issue with wx itself. The sample allows opens a secondary frame and starts a timer when the button is pressed. If you close the frame, there is a crash. In the OnClose event handler for the frame, if you `self.timer.Stop()`, there is no crash. Just seems like it's an oversight, and this is behavior that didn't happen with Classic 3.0.2.0 on py2.7

![image](https://user-images.githubusercontent.com/3904767/33235404-ed4df5a4-d205-11e7-8163-d0004fba5c02.png)

```python
import wx
import time
import calendar

class MyFrame(wx.Frame):
    def __init__(self, parent):
        wx.Frame.__init__(self, parent, title="Other frame", size=(520, 390))
        self.mainFrame = parent

        mainSizer = wx.BoxSizer(wx.VERTICAL)
        b = wx.Button(self,-1,"Start timer")
        b.Bind(wx.EVT_BUTTON,self.StartTimer)

        mainSizer.Add(b, 0, wx.ALL | wx.EXPAND, 2)

        self.timer = wx.Timer(self)
        self.Bind(wx.EVT_TIMER, self.UpdateTimerStatus, self.timer)

        self.statusbar = wx.StatusBar(self)
        self.statusbar.SetFieldsCount()
        self.SetStatusBar(self.statusbar)

        self.Bind(wx.EVT_CLOSE, self.OnClose)
        self.SetMinSize(self.GetSize())

        self.SetSizer(mainSizer)

    def OnClose(self, event):
        # self.timer.Stop()  # this needs to be here, otherwise program crashes
        event.Skip()


    def UpdateTimerStatus(self, event):
        t = time.gmtime(self.time - time.time())

        if calendar.timegm(t) < 0:  # calendar.timegm gets seconds until time given
            self.timer.Stop()
        else:
            sTime = time.strftime("%H:%M:%S", t)
            self.statusbar.SetStatusText("%s" % sTime, 0)

    def StartTimer(self, evt):
        self.time = time.time() + (60 * 60 * 15) # 15 minutes
        self.timer.Start(1000)
        evt.Skip()


class MainFrame(wx.Frame):
    def __init__(self,*args):
        wx.Frame.__init__(self,*args)
        mainSizer = wx.BoxSizer(wx.VERTICAL)
        b = wx.Button(self,-1,"Open Frame")
        b.Bind(wx.EVT_BUTTON,self.openOtherFrame)
        mainSizer.Add(b, 0, wx.ALL | wx.EXPAND, 2)
        self.SetSizer(mainSizer)

    def openOtherFrame(self, event):
        self.otherFrame = MyFrame(self)
        self.otherFrame.Show()


a = wx.App(redirect=False)
f = MainFrame(None,-1,"Main Frame")
f.Show()
a.MainLoop()
```

**Comment by RobinD42** [comment]
It was possible for this to happen in Classic too, although not always as consistently. 

Unfortunately I don't think there is an easy way to fix this in an automatic manner as there is are reference cycles between the frame, timer, the event binding and handler and it can only be broken by deleting the frame or the timer C++ objects or stopping the timer or unbinding the handler.
