### ISSUE TITLE
wx.Clipboard documentation

### ISSUE THREAD

**Issue by DietmarSchwertberger** [wxWidgets/Phoenix#633]
**wxPython version**: 4.0.0rc1
**Stock or custom build**: stock

The clipboard documentation sample code at the top of the page is not correct.

https://wxpython.org/Phoenix/docs/html/wx.Clipboard.html

This won't work:
```python
wx.TheClipboard.IsSupported(wx.DF_TEXT)
```

The argument to wx.TheClipboard.IsSupported must be a wx.DataFormat, not a DataFormatId.

```python

>>> wx.TheClipboard.IsSupported(wx.DF_UNICODETEXT)
Traceback (most recent call last):
  Debug Probe, prompt 1, line 1
builtins.TypeError: Clipboard.IsSupported(): argument 1 has unexpected type 'DataFormatId'

>>> wx.TheClipboard.IsSupported(wx.DataFormat(wx.DF_UNICODETEXT))
True

**Comment by swt2c** [comment]
In case you want to submit a PR:
https://github.com/wxWidgets/Phoenix/blob/master/docs/sphinx/rest_substitutions/snippets/python/converted/wx.Clipboard.1.py

**Comment by DietmarSchwertberger** [comment]
I'm not sure what the best option would be.
Either the modification as above or better code like in the wxPython book:
```python
text_data = wx.TextDataObject()
if wx.TheClipboard.Open():
    success = wx.TheClipboard.GetData(text_data)
    wx.TheClipboard.Close()
if success:
    return text_data.GetText()
```

The test `wx.TheClipboard.IsSupported(wx.DataFormat(wx.DF_UNICODETEXT))` seems to be working on it's own, without `...Open()`.

So maybe it would be best to have the full documentation like this:

```python

        # Write some text to the clipboard
        if wx.TheClipboard.Open():

            # This data objects are held by the clipboard,
            # so do not delete them in the app.
            wx.TheClipboard.SetData(wx.TextDataObject("Some text"))
            wx.TheClipboard.Close()


        # Test for text content
        not_empty = wx.TheClipboard.IsSupported(wx.DataFormat(wx.DF_TEXT))


        # Read some text
        text_data = wx.TextDataObject()
        if wx.TheClipboard.Open():
            success = wx.TheClipboard.GetData(text_data)
            wx.TheClipboard.Close()
        if success:
            return text_data.GetText()
```
