### ISSUE TITLE
How to determine when an event is fully processed?

### ISSUE THREAD

**Issue by blitzmann** [wxWidgets/Phoenix#634]
**Operating system**: Windows 10
**wxPython version**: 4.0.0b2
**Stock or custom build**: stock
**Python version**: Python 3.6
**Stock or custom build**: stock

**Description of the problem**:

Not really a problem, but rather an inquiry. What would be the best way to determine when an event that I emit has been fully processed? For example, I am wanting to send an event 10 times in a `for` loop in a thread separate from the GUI - I plan to use `wx.PostEvent` to post it to my main window, which many other windows / panels / controls bind to to catch the event and process it. Before sending the next event in line, I want to make sure all the other controls have finished processing the previous event. Hope that makes sense. Is there a way to watch an event for an `IsFinished` flag of some sort?

**Comment by RobinD42** [comment]
The event system isn't really designed for things like this, especially with `wx.PostEvent`. It's kind of a "fire and forget missile."

If you need the thread to wait until certain things are finished (more specific than just that all the handlers have been called) before posting the next event, then perhaps a viable alternative would be to use some of the thread locking or synchronization helpers in the threading module to set that up.
