### ISSUE TITLE
Storing `wx.PaintDC(self)` will cause other widgets not showing

### ISSUE THREAD

**Issue by Aahung** [wxWidgets/Phoenix#647]
**Operating system**: Ubuntu 16.04
**wxPython version**: 4.0.0b2
**Stock or custom build**: Stock (through pip)
**Python version**: 3.5.2
**Stock or custom build**: Stock

**Description of the problem**: 

See [BeeVeeH#2](https://github.com/Aahung/BeeVeeH/issues/2)
Although on [doc site](https://wxpython.org/Phoenix/docs/html/wx.PaintDC.html#wx-paintdc) says

> This should normally be constructed as a temporary stack object; don’t store a wx.PaintDC object 

Storing the `wx.PaintDC` causing any abnormality is weird.  

```python
import wx

class widget(wx.Panel):
    def __init__(self, parent):
        wx.Panel.__init__(self, parent, size=(-1, 30))
        self.Bind(wx.EVT_PAINT, self.OnPaint)

    def OnPaint(self, event):
        dc = wx.PaintDC(self)
        # replacing the above line with the next line will cause the problem
        # self.dc = wx.PaintDC(self)

class AppFrame(wx.Frame):
    def __init__(self, *args, **kw):
        super(AppFrame, self).__init__(*args, **kw)

        panel = wx.Panel(self)

        vbox = wx.BoxSizer(wx.VERTICAL)
        vbox.Add(widget(panel), 1, wx.EXPAND | wx.ALL, 0)
        vbox.Add(wx.StaticText(self, -1, 'Some text'), 1, wx.EXPAND | wx.ALL, 0)

        panel.SetSizer(vbox)

        self.Centre()
        self.Show()

app = wx.App()
frame = AppFrame(None)
app.MainLoop()
```

**Comment by DietmarSchwertberger** [comment]
I don't see the bug here.
The behaviour is documented. All available examples do not store a reference.
Storing a permanent reference does not serve any purpose.
Storing the reference as attribute until the end of painting and then deleting it again, should work. I did not try this, though, as my code usually passes the DC instance around.

**Comment by RobinD42** [comment]
It's somewhat platform specific, but in general you *must* get rid of the `wx.PaintDC` before the end of the paint event handler for everything to behave properly, as there may be system level things that will not happen until the dc is destroyed.

**Comment by RobinD42** [comment]
In other words, DCs are intended to be short-lived transitory objects. You create it, use it and then throw it away.
