### ISSUE TITLE
Compilation failure: c++11-narrowing, clang 4.0.1

### ISSUE THREAD

**Issue by nehaljwani** [wxWidgets/Phoenix#653]
**Operating system**: Mac OS X 10.9.5 13F1911
**wxPython version**: 4.0.0b2
**Stock or custom build**: Custom (From source tarball obtained from PyPI)
**Python version**: 3.6.3
**Stock or custom build**: Custom (Anaconda Distribution)

**Description of the problem**:  Build of wxPython fails with the following error (using compiler clang version 4.0.1):

```
[634/869] cxx: sip/cpp/sip_richtextcmodule.cpp -> build/waf/2.7/sip/cpp/sip_richtextcmodule.cpp.23.o
[635/869] cxx: sip/cpp/sip_richtextwxRichTextAction.cpp -> build/waf/2.7/sip/cpp/sip_richtextwxRichTextAction.cpp.23.o
../../../sip/cpp/sip_richtextcmodule.cpp:4133:37: error: non-constant-expression cannot be narrowed from type 'wxChar' (aka 'wchar_t') to 'char' in initializer list [-Wc++11-narrowing]
    {sipName_RichTextLineBreakChar, wxRichTextLineBreakChar, 'N'},
                                    ^~~~~~~~~~~~~~~~~~~~~~~
../../../sip/cpp/sip_richtextcmodule.cpp:4133:37: note: insert an explicit cast to silence this issue
    {sipName_RichTextLineBreakChar, wxRichTextLineBreakChar, 'N'},
                                    ^~~~~~~~~~~~~~~~~~~~~~~
                                    static_cast<char>(     )
1 error generated.
```

I got around it by patching the generated sip file with this patch:
```patch
diff --git a/sip/cpp/sip_richtextcmodule.cpp b/sip/cpp/sip_richtextcmodule.cpp
index 3488e81..2614e8a 100644
--- a/sip/cpp/sip_richtextcmodule.cpp
+++ b/sip/cpp/sip_richtextcmodule.cpp
@@ -4130,7 +4130,7 @@ static sipImportedModuleDef importsTable[] = {
 
 /* Define the chars to be added to this module dictionary. */
 static sipCharInstanceDef charInstances[] = {
-    {sipName_RichTextLineBreakChar, wxRichTextLineBreakChar, 'N'},
+    {sipName_RichTextLineBreakChar, static_cast<char>(wxRichTextLineBreakChar), 'N'},
     {0, 0, 0}
```

Could someone please point me to the location where this code is generated from? I am willing to send a patch there.

**Comment by swt2c** [comment]
I am not sure that's the right solution, though.  The real problem here seems that wxChar is being treated as a 'char' and not a 'wchar_t.'

**Comment by RobinD42** [comment]
What commands did you use to do the build?

Is it possible that there is another installation of wxWidgets that may be being included instead of the one included in the wxPython tarfile?

Since you're using Anaconda, have you tried using the conda recipe here: https://anaconda.org/conda-forge/wxpython ?

**Comment by swt2c** [comment]
Robin, this appears to be a bug.  GCC warns about this same problem.  After looking at it closer, it appears to be that SIP doesn't handle wchar_t constants.  I reported it to the SIP mailing list.

**Comment by swt2c** [comment]
I haven't tried this yet:
https://www.riverbankcomputing.com/hg/sip/rev/c0436cb89959

**Comment by RobinD42** [comment]
Thanks @swt. I'll update our sip shortly...
