### ISSUE TITLE
wx.lib.graphics.GraphicsPath.AddArc requires "default" arg to be explicitly passed

### ISSUE THREAD

**Issue by kg-2** [wxWidgets/Phoenix#654]
**Operating system**: w10
**wxPython version**: 4.0.0rc1.dev3510+3a2ecb7 msw (phoenix)
**Stock or custom build**: stock
**Python version**: 3.6.3
**Stock or custom build**: stock
**Description of the problem**:

The documentation describes AddArc as:

> AddArc(self, x, y, radius, startAngle, endAngle, clockwise=True)
> Adds an arc of a circle centering at (x,y) with radius, from startAngle to endAngle.

The 'clockwise' param default value is True, but calling the method without the clockwise param results in:

```python
`path.AddArc(x, y, R, math.radians(-90), math.radians(0))`

>     TypeError: GraphicsPath.AddArc(): arguments did not match any overloaded call:
>       overload 1: not enough arguments
>       overload 2: argument 1 has unexpected type 'int'
```

**Comment by RobinD42** [comment]
Which documentation are you looking at? It's not shown having a default value here: https://docs.wxpython.org/wx.GraphicsPath.html#wx.GraphicsPath.AddArc

**Comment by RobinD42** [comment]
Ah, I just noticed that you said "wx.**lib.graphics**.GraphicsPath" in the subject.  That version of the API does have a default value for the clockwise arg, both in the docs and in the code. Which version are you using?
