### ISSUE TITLE
agw.aui.framemanager doesn't restore perspective when caption or name has '=' character

### ISSUE THREAD

**Issue by robmcmullen** [wxWidgets/Phoenix#660]
**Operating system**: any
**wxPython version**: 4.0
**Stock or custom build**: stock
**Python version**: 2.7
**Stock or custom build**: custom

**Description of the problem**: Creating an AUI pane with a caption including an *=* character, saving the perspective, and attempting to restore the perspective results in:

```
  File "/home/rob/src/omnivore/omnivore8bit/byte_edit/byte_editor.py", line 781, in create_viewers
    self.mgr.LoadPerspective(perspective)
  File "/code/venv/wx4/lib/python2.7/site-packages/wx/lib/agw/aui/framemanager.py", line 5500, in LoadPerspective
    pane = self.LoadPaneInfo(pane_part, pane)
  File "/code/venv/wx4/lib/python2.7/site-packages/wx/lib/agw/aui/framemanager.py", line 5335, in LoadPaneInfo
    val_name, value = items.split("=")
ValueError: too many values to unpack
```
Three delimiter characters are used in the layout string: *|*, *;*, and *=*. The *|* and *;* characters are escaped and are allowed in captions, but *=* is not.

**Comment by Metallicow** [comment]
gee, your right. never noticed that when restoring caption panes on a app restart. I knew there was a problem with some captions reloading but never looked to far into it as I viewed it as a low level item. Thanks for the fix. Now I know there wasn't a problem in my code. :)
