### ISSUE TITLE
TextCtrl, SetBackgroundColour and selected text background

### ISSUE THREAD

**Issue by Jenyay** [wxWidgets/Phoenix#662]
**Operating system**: Ubuntu 17.10
**wxPython version**: 4.0b2
**Stock or custom build**: from PyPi
**Python version**: 3.6
**Stock or custom build**: stock

**Description of the problem**: The SetBackgroundColour method changes the colour of the selected text. SetBackgroundColour(wx.Colour(255, 255, 255)) is called in the example bellow and the background of the selected text in this control becomes white.

```python
# -*- coding: utf-8 -*-

import wx


class MyTestFrame(wx.Frame):
    def __init__(self, parent, title):
        wx.Frame.__init__(self, parent, wx.ID_ANY, title, size=(400, 300))
        self.panel = wx.Panel(self)

        self.textctrl = wx.TextCtrl(self.panel)
        self.textctrl.SetSize((150, -1))
        self.textctrl.SetBackgroundColour(wx.Colour(255, 255, 255))


if __name__ == '__main__':
    app = wx.App()
    frame = MyTestFrame(None, 'ToggleButton Test')
    frame.Show()
    frame.SetSize((500, 600))
    app.MainLoop()
```

**Comment by mesalu** [comment]
I'm not sure I see what the issue here is.
Would you mind replying with screen captures indicating what precisely is wrong?

I don't have a Ubuntu 17.10 VM I can load up offhand, but other GTK2 and GTK3 installations look fine to me.

Speaking of, knowing which version of GTK in use would be helpful. If you don't know off hand we can check which one should have been used during pypi installation if you provide the pypi package version.

```bash
pip show wxpython
```

**Comment by Jenyay** [comment]
![wxpython](https://user-images.githubusercontent.com/166281/34477005-f3a9223e-efa6-11e7-87c3-2ebae7360294.gif)

```
$ pip show wxpython
Name: wxPython
Version: 4.0.0b2
Summary: Cross platform GUI toolkit for Python, "Phoenix" version
Home-page: http://wxPython.org/
Author: Robin Dunn
Author-email: robin@alldunn.com
License: wxWindows Library License (https://opensource.org/licenses/wxwindows.php)
Location: /home/jenyay/projects/venv/outwiker-py3/lib/python3.6/site-packages
Requires: six
```

**Comment by mesalu** [comment]
Now that is interesting.

I'm able to reproduce it now that I have 17.10.

@RobinD42, I figure this is an issue with wxWidgets, or a change in GTK that's causing wx to misuse it. What're your thoughts?

Some extra info from my environment:
Desktop Environment: Stock (I believe its gnome shell now, right?)
Theme: Stock

```Python
Python 3.6.3 (default, Oct  3 2017, 21:45:48) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import wx
>>> 'gtk3' in wx.PlatformInfo
True
>>> 
```
```Bash
sdunn@UbnB:~$ apt show libgtk-3-dev
Package: libgtk-3-dev
Version: 3.22.25-0ubuntu0.1
Priority: optional
Section: libdevel
Source: gtk+3.0
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian GNOME Maintainers <pkg-gnome-maintainers@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 11.1 MB
Depends: libgtk-3-0 (= 3.22.25-0ubuntu0.1), gir1.2-gtk-3.0 (= 3.22.25-0ubuntu0.1), libgtk-3-common, dconf-gsettings-backend | gsettings-backend, libglib2.0-dev (>= 2.49.4), libgdk-pixbuf2.0-dev (>= 2.30.0), libmirclient-dev (>= 0.13.3), libmircookie-dev (>= 0.17.0), libpango1.0-dev (>= 1.40.5), libatk1.0-dev (>= 2.15.1), libatk-bridge2.0-dev, libcairo2-dev (>= 1.14.0), libepoxy-dev (>= 1.0), libfontconfig1-dev, libx11-dev, libxext-dev, libxinerama-dev, libxi-dev, libxrandr-dev, libxcursor-dev, libxfixes-dev, libxcomposite-dev, libxdamage-dev, pkg-config, libegl1-mesa-dev, libwayland-dev (>= 1.9.91), wayland-protocols (>= 1.9), libxkbcommon-dev
Suggests: libgtk-3-doc
Homepage: http://www.gtk.org/
Supported: 9m
Download-Size: 897 kB
APT-Manual-Installed: yes
APT-Sources: http://us.archive.ubuntu.com/ubuntu artful-updates/main amd64 Packages
Description: development files for the GTK+ library
 GTK+ is a multi-platform toolkit for creating graphical user
 interfaces. Offering a complete set of widgets, GTK+ is suitable
 for projects ranging from small one-off tools to complete application
 suites.
 .
 This package contains the header and development files which are
 needed for building GTK+ applications.
```
Package: libgtk-3-0
Version: 3.22.25-0ubuntu0.1
Priority: optional
Section: libs
Source: gtk+3.0
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian GNOME Maintainers <pkg-gnome-maintainers@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 9,258 kB
Provides: gtk3-binver-3.0.0
Depends: libgtk-3-common (>= 3.22.25-0ubuntu0.1), libatk-bridge2.0-0 (>= 2.5.3), libatk1.0-0 (>= 2.15.1), libc6 (>= 2.14), libcairo-gobject2 (>= 1.10.0), libcairo2 (>= 1.14.0), libcolord2 (>= 0.1.10), libcups2 (>= 1.6.2), libepoxy0 (>= 1.0), libfontconfig1 (>= 2.11.94), libgdk-pixbuf2.0-0 (>= 2.30.1), libglib2.0-0 (>= 2.51.2), libjson-glib-1.0-0 (>= 0.12.0), libmirclient9 (>= 0.28.0+17.10.20171011.1), libpango-1.0-0 (>= 1.40.5), libpangocairo-1.0-0 (>= 1.40.5), libpangoft2-1.0-0 (>= 1.40.5), librest-0.7-0 (>= 0.7), libwayland-client0 (>= 1.9.91), libwayland-cursor0 (>= 1.9.91), libwayland-egl1-mesa (>= 10.0.2) | libwayland-egl1, libx11-6 (>= 2:1.4.99.1), libxcomposite1 (>= 1:0.3-1), libxcursor1 (>> 1.1.2), libxdamage1 (>= 1:1.1), libxext6, libxfixes3, libxi6 (>= 2:1.2.99.4), libxinerama1, libxkbcommon0 (>= 0.5.0), libxrandr2 (>= 2:1.5.0), hicolor-icon-theme, adwaita-icon-theme, shared-mime-info
Recommends: libgtk-3-bin
Suggests: librsvg2-common, gvfs
Breaks: gnome-themes-standard (<< 3.6), gtk3-engines-oxygen (<< 1.4.1-3)
Homepage: http://www.gtk.org/
Task: ubuntu-desktop, ubuntu-usb, kubuntu-desktop, edubuntu-desktop, edubuntu-usb, xubuntu-core, xubuntu-desktop, lubuntu-gtk-core, lubuntu-desktop-share, lubuntu-gtk-desktop, lubuntu-gtk-desktop, lubuntu-core, lubuntu-core, lubuntu-desktop, lubuntu-qt-desktop, ubuntustudio-desktop-core, ubuntustudio-desktop, ubuntu-gnome-desktop, ubuntu-touch-core, ubuntu-touch, ubuntukylin-desktop, ubuntu-mate-core, ubuntu-mate-desktop, ubuntu-budgie-desktop
Supported: 9m
Download-Size: 2,540 kB
APT-Manual-Installed: yes
APT-Sources: http://us.archive.ubuntu.com/ubuntu artful-updates/main amd64 Packages
Description: GTK+ graphical user interface library
 GTK+ is a multi-platform toolkit for creating graphical user
 interfaces. Offering a complete set of widgets, GTK+ is suitable
 for projects ranging from small one-off tools to complete application
 suites.
 .
 This package contains the shared libraries.
```


An equivalent configure log:
```
Running command: build
  Running command: build_wx
  wxWidgets build options: ['--wxpython', '--unicode', '--gtk3']
  Configure options: ['--enable-unicode', '--with-gtk=3', '--with-opengl', '--enable-sound', '--enable-graphics_ctx', '--enable-mediactrl', '--enable-display', '--enable-geometry', '--enable-debug_flag', '--enable-optimise', '--disable-debugreport', '--enable-uiactionsim', '--with-sdl']
  /tmp/pip-build-il_b5hz4/wxpython/ext/wxWidgets/configure --enable-unicode --with-gtk=3 --with-opengl --enable-sound --enable-graphics_ctx --enable-mediactrl --enable-display --enable-geometry --enable-debug_flag --enable-optimise --disable-debugreport --enable-uiactionsim --with-sdl
  checking build system type... x86_64-unknown-linux-gnu
  checking host system type... x86_64-unknown-linux-gnu
  checking for --disable-gui... no
  checking for --enable-monolithic... no
  checking for --enable-plugins... no
  checking for --without-subdirs... no
  checking for --enable-official_build... no
  checking for --disable-all-features... no
  checking for --enable-universal... no
  checking for --enable-nanox... no
  checking for --enable-gpe... no
  checking for toolkit... gtk
  checking for --with-libpng... yes
  checking for --with-libjpeg... yes
  checking for --with-libtiff... yes
  checking for --without-libjbig... no
  checking for --without-liblzma... no
  checking for --with-libxpm... yes
  checking for --with-libiconv... yes
  checking for --with-libmspack... no
  checking for --without-gtkprint... no
  checking for --with-gnomevfs... no
  checking for --with-libnotify... yes
  checking for --with-hildon... no
  checking for --with-opengl... yes
  checking for --with-dmalloc... no
  checking for --with-sdl... yes
  checking for --with-regex... yes
  checking for --with-zlib... yes
  checking for --with-expat... yes
  checking for --with-macosx-sdk...
  checking for --with-macosx-version-min...
  checking for --enable-debug... default
  checking for --disable-debug_flag... no
  checking for --enable-debug_info... no
  checking for --enable-debug_gdb... no
  checking for --enable-debug_cntxt... no
  checking for --enable-mem_tracing... no
  checking for --disable-shared... no
  checking for --enable-stl... no
  checking for --enable-std_containers... no
  checking for --enable-std_iostreams... yes
  checking for --enable-std_string... yes
  checking for --enable-std_string_conv_in_wxstring... no
  checking for --disable-unicode... no
  checking for --enable-mslu... no
  checking for --enable-utf8... no
  checking for --enable-utf8only... no
  checking for --enable-extended_rtti... no
  checking for --disable-optimise... no
  checking for --enable-profile... no
  checking for --enable-no_rtti... no
  checking for --enable-no_exceptions... no
  checking for --enable-permissive... no
  checking for --enable-no_deps... no
  checking for --disable-vararg_macros... no
  checking for --enable-universal_binary... no
  checking for --enable-macosx_arch... no
  checking for --enable-compat26... no
  checking for --disable-compat28... no
  checking for --disable-rpath... no
  checking for --enable-objc_uniquifying... no
  checking for --disable-visibility... no
  checking for --disable-tls... no
  checking for --enable-intl... yes
  checking for --enable-xlocale... yes
  checking for --enable-config... yes
  checking for --enable-protocols... yes
  checking for --enable-ftp... yes
  checking for --enable-http... yes
  checking for --enable-fileproto... yes
  checking for --enable-sockets... yes
  checking for --enable-ipv6... no
  checking for --enable-ole... yes
  checking for --enable-dataobj... yes
  checking for --enable-ipc... yes
  checking for --enable-baseevtloop... yes
  checking for --enable-epollloop... yes
  checking for --enable-selectloop... yes
  checking for --enable-any... yes
  checking for --enable-apple_ieee... yes
  checking for --enable-arcstream... yes
  checking for --enable-base64... yes
  checking for --enable-backtrace... yes
  checking for --enable-catch_segvs... yes
  checking for --enable-cmdline... yes
  checking for --enable-datetime... yes
  checking for --enable-debugreport... no
  checking for --enable-dialupman... yes
  checking for --enable-dynlib... yes
  checking for --enable-dynamicloader... yes
  checking for --enable-exceptions... yes
  checking for --enable-ffile... yes
  checking for --enable-file... yes
  checking for --enable-filehistory... yes
  checking for --enable-filesystem... yes
  checking for --enable-fontenum... yes
  checking for --enable-fontmap... yes
  checking for --enable-fs_archive... yes
  checking for --enable-fs_inet... yes
  checking for --enable-fs_zip... yes
  checking for --enable-fsvolume... yes
  checking for --enable-fswatcher... yes
  checking for --enable-geometry... yes
  checking for --enable-log... yes
  checking for --enable-longlong... yes
  checking for --enable-mimetype... yes
  checking for --enable-printfposparam... yes
  checking for --enable-snglinst... yes
  checking for --enable-sound... yes
  checking for --enable-stdpaths... yes
  checking for --enable-stopwatch... yes
  checking for --enable-streams... yes
  checking for --enable-sysoptions... yes
  checking for --enable-tarstream... yes
  checking for --enable-textbuf... yes
  checking for --enable-textfile... yes
  checking for --enable-timer... yes
  checking for --enable-variant... yes
  checking for --enable-zipstream... yes
  checking for --enable-url... yes
  checking for --enable-protocol... yes
  checking for --enable-protocol_http... yes
  checking for --enable-protocol_ftp... yes
  checking for --enable-protocol_file... yes
  checking for --enable-threads... yes
  checking for --enable-iniconf... no
  checking for --enable-regkey... yes
  checking for --enable-docview... yes
  checking for --enable-help... yes
  checking for --enable-mshtmlhelp... yes
  checking for --enable-html... yes
  checking for --enable-htmlhelp... yes
  checking for --enable-xrc... yes
  checking for --enable-aui... yes
  checking for --enable-propgrid... yes
  checking for --enable-ribbon... yes
  checking for --enable-stc... yes
  checking for --enable-constraints... yes
  checking for --enable-loggui... yes
  checking for --enable-logwin... yes
  checking for --enable-logdialog... yes
  checking for --enable-mdi... yes
  checking for --enable-mdidoc... yes
  checking for --enable-mediactrl... yes
  checking for --enable-gstreamer8... no
  checking for --enable-richtext... yes
  checking for --enable-postscript... yes
  checking for --enable-printarch... yes
  checking for --enable-svg... yes
  checking for --enable-webkit... yes
  checking for --enable-webview... yes
  checking for --enable-graphics_ctx... yes
  checking for --enable-clipboard... yes
  checking for --enable-dnd... yes
  checking for --disable-controls... no
  checking for --enable-markup... yes
  checking for --enable-accel... yes
  checking for --enable-animatectrl... yes
  checking for --enable-bannerwindow... yes
  checking for --enable-artstd... yes
  checking for --enable-arttango... auto
  checking for --enable-bmpbutton... yes
  checking for --enable-bmpcombobox... yes
  checking for --enable-button... yes
  checking for --enable-calendar... yes
  checking for --enable-caret... yes
  checking for --enable-checkbox... yes
  checking for --enable-checklst... yes
  checking for --enable-choice... yes
  checking for --enable-choicebook... yes
  checking for --enable-collpane... yes
  checking for --enable-colourpicker... yes
  checking for --enable-combobox... yes
  checking for --enable-comboctrl... yes
  checking for --enable-commandlinkbutton... yes
  checking for --enable-dataviewctrl... yes
  checking for --enable-datepick... yes
  checking for --enable-detect_sm... yes
  checking for --enable-dirpicker... yes
  checking for --enable-display... yes
  checking for --enable-editablebox... yes
  checking for --enable-filectrl... yes
  checking for --enable-filepicker... yes
  checking for --enable-fontpicker... yes
  checking for --enable-gauge... yes
  checking for --enable-grid... yes
  checking for --enable-headerctrl... yes
  checking for --enable-hyperlink... yes
  checking for --enable-imaglist... yes
  checking for --enable-infobar... yes
  checking for --enable-listbook... yes
  checking for --enable-listbox... yes
  checking for --enable-listctrl... yes
  checking for --enable-notebook... yes
  checking for --enable-notifmsg... yes
  checking for --enable-odcombobox... yes
  checking for --enable-popupwin... yes
  checking for --enable-prefseditor... yes
  checking for --enable-radiobox... yes
  checking for --enable-radiobtn... yes
  checking for --enable-richmsgdlg... yes
  checking for --enable-richtooltip... yes
  checking for --enable-rearrangectrl... yes
  checking for --enable-sash... yes
  checking for --enable-scrollbar... yes
  checking for --enable-searchctrl... yes
  checking for --enable-slider... yes
  checking for --enable-spinbtn... yes
  checking for --enable-spinctrl... yes
  checking for --enable-splitter... yes
  checking for --enable-statbmp... yes
  checking for --enable-statbox... yes
  checking for --enable-statline... yes
  checking for --enable-stattext... yes
  checking for --enable-statusbar... yes
  checking for --enable-taskbaricon... yes
  checking for --enable-tbarnative... yes
  checking for --enable-textctrl... yes
  checking for --enable-datepick... yes
  checking for --enable-tipwindow... yes
  checking for --enable-togglebtn... yes
  checking for --enable-toolbar... yes
  checking for --enable-toolbook... yes
  checking for --enable-treebook... yes
  checking for --enable-treectrl... yes
  checking for --enable-treelist... yes
  checking for --enable-commondlg... yes
  checking for --enable-aboutdlg... yes
  checking for --enable-choicedlg... yes
  checking for --enable-coldlg... yes
  checking for --enable-filedlg... yes
  checking for --enable-finddlg... yes
  checking for --enable-fontdlg... yes
  checking for --enable-dirdlg... yes
  checking for --enable-msgdlg... yes
  checking for --enable-numberdlg... yes
  checking for --enable-splash... yes
  checking for --enable-textdlg... yes
  checking for --enable-tipdlg... yes
  checking for --enable-progressdlg... yes
  checking for --enable-wizarddlg... yes
  checking for --enable-menus... yes
  checking for --enable-miniframe... yes
  checking for --enable-tooltips... yes
  checking for --enable-splines... yes
  checking for --enable-mousewheel... yes
  checking for --enable-validators... yes
  checking for --enable-busyinfo... yes
  checking for --enable-hotkey... auto
  checking for --enable-joystick... yes
  checking for --enable-metafile... auto
  checking for --enable-dragimage... yes
  checking for --enable-accessibility... no
  checking for --enable-uiactionsim... yes
  checking for --enable-dctransform... yes
  checking for --enable-webviewwebkit... yes
  checking for --enable-palette... yes
  checking for --enable-image... yes
  checking for --enable-gif... yes
  checking for --enable-pcx... yes
  checking for --enable-tga... yes
  checking for --enable-iff... yes
  checking for --enable-pnm... yes
  checking for --enable-xpm... yes
  checking for --enable-ico_cur... yes
  checking for --enable-dccache... yes
  checking for --enable-ps-in-msw... yes
  checking for --enable-ownerdrawn... yes
  checking for --enable-uxtheme... yes
  checking for --enable-wxdib... yes
  checking for --enable-webviewie... yes
  checking for --enable-autoidman... no
  checking for gcc... gcc
  checking whether the C compiler works... yes
  checking for C compiler default output file name... a.out
  checking for suffix of executables...
  checking whether we are cross compiling... no
  checking for suffix of object files... o
  checking whether we are using the GNU C compiler... yes
  checking whether gcc accepts -g... yes
  checking for gcc option to accept ISO C89... none needed
  checking whether we are using the Intel C compiler... no
  checking how to run the C preprocessor... gcc -E
  checking for grep that handles long lines and -e... /bin/grep
  checking for egrep... /bin/grep -E
  checking whether gcc needs -traditional... no
  checking for g++... g++
  checking whether we are using the GNU C++ compiler... yes
  checking whether g++ accepts -g... yes
  checking whether we are using the Intel C++ compiler... no
  checking whether we are using the Sun C++ compiler... no
  checking for ar... ar
  checking for ANSI C header files... yes
  checking for sys/types.h... yes
  checking for sys/stat.h... yes
  checking for stdlib.h... yes
  checking for string.h... yes
  checking for memory.h... yes
  checking for strings.h... yes
  checking for inttypes.h... yes
  checking for stdint.h... yes
  checking for unistd.h... yes
  checking for langinfo.h... yes
  checking for wchar.h... yes
  checking for sys/select.h... yes
  checking for cxxabi.h... yes
  checking for an ANSI C-conforming const... yes
  checking for inline... inline
  checking size of short... 2
  checking size of void *... 8
  checking size of int... 4
  checking size of long... 8
  checking size of size_t... 8
  checking size of long long... 8
  checking size of wchar_t... 4
  checking for va_copy... yes
  checking whether the compiler supports variadic macros... yes
  checking for _FILE_OFFSET_BITS value needed for large files... 64
  checking if large file support is available... yes
  checking for _LARGEFILE_SOURCE value needed for large files... no
  checking whether byte ordering is bigendian... no
  checking for iostream... yes
  checking if C++ compiler supports the explicit keyword... yes
  checking for std::wstring in <string>... yes
  checking for std::istream... yes
  checking for std::ostream... yes
  checking how to run the C++ preprocessor... g++ -E
  checking type_traits usability... yes
  checking type_traits presence... yes
  checking for type_traits... yes
  checking for __sync_fetch_and_add and __sync_sub_and_fetch builtins... yes
  checking for libraries directories... /usr/lib/x86_64-linux-gnu /usr/lib
  checking for cos... no
  checking for floor... no
  checking if floating point functions link without -lm... no
  checking for sin... yes
  checking for ceil... yes
  checking if floating point functions link with -lm... yes
  checking for strtoull... yes
  configure: WARNING: Defaulting to the builtin regex library for Unicode build.
  checking for zlib.h >= 1.1.4... yes
  checking for zlib.h... (cached) yes
  checking for deflate in -lz... yes
  checking for png.h > 0.90... yes
  checking for png.h... (cached) yes
  checking for png_sig_cmp in -lpng... yes
  checking for jpeglib.h... yes
  checking for jpeg_read_header in -ljpeg... yes
  checking for tiffio.h... yes
  checking for TIFFError in -ltiff... yes
  checking for expat.h... yes
  checking if expat.h is valid C++ header... yes
  checking for XML_ParserCreate in -lexpat... yes
  checking for GTK+ version...
  checking for pkg-config... /usr/bin/pkg-config
  checking for GTK+ - version >= 3.0.0... yes (version 3.22.25)
  checking for X11/Xlib.h... yes
  checking for X11/XKBlib.h... yes
  checking for Xxf86vm... yes
  checking for X11/extensions/xf86vmode.h... yes
  checking for SM... yes
  checking for OpenGL headers... found in /usr/include
  checking for GL/gl.h... yes
  checking for GL/glu.h... yes
  checking for GL... yes
  checking for GLU... yes
  checking if the linker accepts --version-script... yes
  checking for symbols visibility support... yes
  checking for broken libstdc++ visibility... no
  checking for mode_t... yes
  checking for off_t... yes
  checking for pid_t... yes
  checking for size_t... yes
  checking for ssize_t... yes
  checking if size_t is unsigned int... no
  checking if size_t is unsigned long... yes
  checking if wchar_t is separate type... yes
  checking for pw_gecos in struct passwd... yes
  checking for wcslen... yes
  checking for wcsftime... yes
  checking for strnlen... yes
  checking for wcsdup... yes
  checking for wcsnlen... yes
  checking for wcscasecmp... yes
  checking for wcsncasecmp... yes
  checking for mbstate_t... yes
  checking for wcsrtombs... yes
  checking for snprintf... yes
  checking for vsnprintf... yes
  checking for vsscanf... yes
  checking for vsnprintf declaration... yes
  checking if vsnprintf declaration is broken... no
  checking for snprintf declaration... yes
  checking if snprintf supports positional arguments... yes
  checking for vsscanf declaration... yes
  checking if vsscanf() declaration is broken... no
  checking for putws... no
  checking for fputws... yes
  checking for wprintf... yes
  checking for vswprintf... yes
  checking for vswscanf... yes
  checking for _vsnwprintf... no
  checking for fsync... yes
  checking for round... no
  checking for iconv... yes
  checking if iconv needs const... no
  checking for sigaction... yes
  checking for sa_handler type... int
  checking for backtrace() in <execinfo.h>... checking for library containing backtrace... none required
  yes
  checking for __cxa_demangle() in <cxxabi.h>... yes
  checking for mkstemp... yes
  checking for statfs... yes
  checking for statfs declaration... yes
  checking for fcntl... yes
  checking for setenv... yes
  checking for unsetenv... yes
  checking for nanosleep... yes
  checking for uname... yes
  checking for strtok_r... yes
  checking for inet_addr... yes
  checking for inet_aton... yes
  checking for fdopen... yes
  checking for sysconf... yes
  checking for getpwuid_r... yes
  checking for getgrgid_r... yes
  checking whether pthreads work with -pthread... yes
  checking if more special flags are required for pthreads... no
  checking for pthread_setconcurrency... yes
  checking for pthread_cleanup_push/pop... yes
  checking for sched.h... yes
  checking for sched_yield... yes
  checking for pthread_attr_getschedpolicy... yes
  checking for pthread_attr_setschedparam... yes
  checking for sched_get_priority_max... yes
  checking for pthread_cancel... yes
  checking for pthread_mutex_timedlock... yes
  checking for pthread_attr_setstacksize... yes
  checking for pthread_mutexattr_t... yes
  checking for pthread_mutexattr_settype declaration... yes
  checking for __thread keyword... yes
  checking if gcc accepts -dumpversion option... yes
  checking gxx version... 7
  checking whether __thread support in g++ is usable... yes, it works
  checking for abi::__forced_unwind() in <cxxabi.h>... yes
  checking for localtime_r... yes
  checking for gmtime_r... yes
  checking how many arguments gethostbyname_r() takes... six
  checking how many arguments getservbyname_r() takes... six
  checking for dlopen... no
  checking for dlopen in -ldl... yes
  checking for dlerror... no
  checking for dlerror in -ldl... yes
  checking for sys/inotify.h... yes
  checking for SNDCTL_DSP_SPEED in sys/soundcard.h... yes
  checking pkg-config is at least version 0.9.0... yes
  checking for SDL... configure: SDL 2.0 not available. Falling back to 1.2.
  checking for sdl-config... no
  checking for SDL - version >= 1.2.0... no
  *** The sdl-config script installed by SDL could not be found
  *** If SDL was installed in PREFIX, make sure PREFIX/bin is in
  *** your path, or set the SDL_CONFIG environment variable to the
  *** full path to sdl-config.
  checking pkg-config is at least version 0.9.0... yes
  checking for GTKPRINT... yes
  checking for LIBNOTIFY... checking for LIBNOTIFY... configure: WARNING: libnotify not found, wxNotificationMessage will use generic implementation.
  checking for complete xlocale... no
  checking for sys/epoll.h... yes
  checking for gettimeofday... yes
  checking whether gettimeofday takes two arguments... yes
  checking for timezone variable in <time.h>... timezone
  checking for localtime... yes
  checking for tm_gmtoff in struct tm... yes
  checking for setpriority... yes
  checking for socket... yes
  checking what is the type of the third argument of getsockname... socklen_t
  checking what is the type of the fifth argument of getsockopt... socklen_t
  checking for linux/joystick.h... yes
  checking for python... /home/sdunn/tenv3/bin/python3
  checking for WEBKIT... configure: WARNING: webkit2gtk not found, falling back to webkitgtk
  checking for WEBKIT... yes
  checking for CAIRO... yes
  checking for cairo_push_group... yes
  checking for GST... yes
  checking CXXWARNINGS for gcc -Woverloaded-virtual... -Woverloaded-virtual
  checking for gcc precompiled header bug... no
  checking for a BSD-compatible install... /usr/bin/install -c
  checking for ranlib... ranlib
  checking whether ln -s works... yes
  checking whether make sets $(MAKE)... yes
  checking for ar... (cached) ar
  checking for strip... strip
  checking for nm... nm
  checking if make is GNU make... yes
  checking for dependency tracking method... gcc
  checking if the compiler supports precompiled headers... yes
  checking whether make sets $(MAKE)... (cached) yes
  checking for cppunit-config... no
  checking for Cppunit - version >= 1.8.0... no
  configure: creating ./config.status
  config.status: creating lib/wx/config/gtk3-unicode-3.0
  config.status: creating lib/wx/config/inplace-gtk3-unicode-3.0
  config.status: creating utils/ifacecheck/rungccxml.sh
  config.status: creating version-script
  config.status: creating Makefile
  config.status: creating samples/xrc/Makefile
  config.status: creating samples/wrapsizer/Makefile
  config.status: creating samples/wizard/Makefile
  config.status: creating samples/widgets/Makefile
  config.status: creating samples/webview/Makefile
  config.status: creating samples/vscroll/Makefile
  config.status: creating samples/validate/Makefile
  config.status: creating samples/uiaction/Makefile
  config.status: creating samples/typetest/Makefile
  config.status: creating samples/treelist/Makefile
  config.status: creating samples/treectrl/Makefile
  config.status: creating samples/toolbar/Makefile
  config.status: creating samples/thread/Makefile
  config.status: creating samples/text/Makefile
  config.status: creating samples/taskbar/Makefile
  config.status: creating samples/taborder/Makefile
  config.status: creating samples/svg/Makefile
  config.status: creating samples/stc/Makefile
  config.status: creating samples/statbar/Makefile
  config.status: creating samples/splitter/Makefile
  config.status: creating samples/splash/Makefile
  config.status: creating samples/sound/Makefile
  config.status: creating samples/sockets/Makefile
  config.status: creating samples/shaped/Makefile
  config.status: creating samples/scroll/Makefile
  config.status: creating samples/sashtest/Makefile
  config.status: creating samples/richtext/Makefile
  config.status: creating samples/ribbon/Makefile
  config.status: creating samples/render/Makefile
  config.status: creating samples/propgrid/Makefile
  config.status: creating samples/printing/Makefile
  config.status: creating samples/popup/Makefile
  config.status: creating samples/opengl/penguin/Makefile
  config.status: creating samples/opengl/isosurf/Makefile
  config.status: creating samples/opengl/cube/Makefile
  config.status: creating samples/opengl/Makefile
  config.status: creating samples/notebook/Makefile
  config.status: creating samples/minimal/Makefile
  config.status: creating samples/menu/Makefile
  config.status: creating samples/mediaplayer/Makefile
  config.status: creating samples/mdi/Makefile
  config.status: creating samples/listctrl/Makefile
  config.status: creating samples/layout/Makefile
  config.status: creating samples/keyboard/Makefile
  config.status: creating samples/joytest/Makefile
  config.status: creating samples/ipc/Makefile
  config.status: creating samples/internat/Makefile
  config.status: creating samples/image/Makefile
  config.status: creating samples/html/zip/Makefile
  config.status: creating samples/html/widget/Makefile
  config.status: creating samples/html/virtual/Makefile
  config.status: creating samples/html/test/Makefile
  config.status: creating samples/html/printing/Makefile
  config.status: creating samples/html/helpview/Makefile
  config.status: creating samples/html/help/Makefile
  config.status: creating samples/html/about/Makefile
  config.status: creating samples/html/Makefile
  config.status: creating samples/htlbox/Makefile
  config.status: creating samples/help/Makefile
  config.status: creating samples/grid/Makefile
  config.status: creating samples/fswatcher/Makefile
  config.status: creating samples/font/Makefile
  config.status: creating samples/exec/Makefile
  config.status: creating samples/except/Makefile
  config.status: creating samples/event/Makefile
  config.status: creating samples/erase/Makefile
  config.status: creating samples/drawing/Makefile
  config.status: creating samples/dragimag/Makefile
  config.status: creating samples/docview/Makefile
  config.status: creating samples/dnd/Makefile
  config.status: creating samples/display/Makefile
  config.status: creating samples/dialup/Makefile
  config.status: creating samples/dialogs/Makefile
  config.status: creating samples/dataview/Makefile
  config.status: creating samples/controls/Makefile
  config.status: creating samples/console/Makefile
  config.status: creating samples/config/Makefile
  config.status: creating samples/combo/Makefile
  config.status: creating samples/collpane/Makefile
  config.status: creating samples/clipboard/Makefile
  config.status: creating samples/caret/Makefile
  config.status: creating samples/calendar/Makefile
  config.status: creating samples/aui/Makefile
  config.status: creating samples/artprov/Makefile
  config.status: creating samples/animate/Makefile
  config.status: creating samples/Makefile
  config.status: creating demos/forty/Makefile
  config.status: creating demos/life/Makefile
  config.status: creating demos/Makefile
  config.status: creating demos/poem/Makefile
  config.status: creating demos/bombs/Makefile
  config.status: creating demos/fractal/Makefile
  config.status: creating utils/helpview/Makefile
  config.status: creating utils/helpview/src/Makefile
  config.status: creating utils/Makefile
  config.status: creating utils/wxrc/Makefile
  config.status: creating utils/screenshotgen/Makefile
  config.status: creating utils/screenshotgen/src/Makefile
  config.status: creating utils/ifacecheck/src/Makefile
  config.status: creating utils/hhp2cached/Makefile
  config.status: creating utils/execmon/Makefile
  config.status: creating utils/emulator/Makefile
  config.status: creating utils/emulator/src/Makefile
  config.status: creating lib/wx/include/gtk3-unicode-3.0/wx/setup.h
  config.status: executing wx-config commands

  Configured wxWidgets 3.0.4 for `x86_64-unknown-linux-gnu'

    Which GUI toolkit should wxWidgets use?                 GTK+ 3 with support for GTK+ printing libnotify
    Should wxWidgets be compiled into single library?       no
    Should wxWidgets be linked as a shared library?         yes
    Should wxWidgets support Unicode?                       yes (using wchar_t)
    What level of wxWidgets compatibility should be enabled?
                                         wxWidgets 2.6      no
                                         wxWidgets 2.8      yes
    Which libraries should wxWidgets use?
                                         STL                no
                                         jpeg               sys
                                         png                sys
                                         regex              builtin
                                         tiff               sys
                                         zlib               sys
                                         expat              sys
                                         libmspack          no
                                         sdl                no
```

I'm presently waiting for a gtk2 based build to compare between gtk versions as well.

**Comment by RobinD42** [comment]
> @RobinD42, I figure this is an issue with wxWidgets, or a change in GTK that's causing wx to misuse it. What're your thoughts?

I agree.  It's probably a bug in this function, https://github.com/wxWidgets/wxWidgets/blob/WX_3_0_BRANCH/src/gtk/window.cpp#L4437, which does something different for the selection color in GTK pre- and post-3.20.0

**Comment by swt2c** [comment]
Reported:
https://trac.wxwidgets.org/ticket/18036

**Comment by RobinD42** [comment]
And Paul's fixed it already. Awesome! I'll update things on our end in the next day or two.
