### ISSUE TITLE
AUI Notebook Tab Control is instance of wx.Control instead of wx.aui.AuiTabCtrl

### ISSUE THREAD

**Issue by konstantinbo** [wxWidgets/Phoenix#664]
**Operating system**:
Windows 7 
**wxPython version**:
4.0.0b2
**Stock or custom build**:
stock
**Python version**:
2.7.14
**Stock or custom build**:
stock
**Description of the problem**:
When calling the `GetChildren()` method on an `wx.aui.AuiNotebook` object the Tab Control object is an instance of the class `wx.Control`, whereas in wxPython Classic it's `wx.aui.AuiTabCtrl.`
Example:

```python
import wx
import wx.aui


class TestPanel(wx.Panel):
    def __init__(self, parent):
        wx.Panel.__init__(self, parent, -1)

        self.nb = wx.aui.AuiNotebook(self)
        page = wx.TextCtrl(self.nb, -1, 'foobar')
        self.nb.AddPage(page, "Page 1")

        sizer = wx.BoxSizer()
        sizer.Add(self.nb, 1, wx.EXPAND)
        self.SetSizer(sizer)
        wx.CallAfter(self.nb.SendSizeEvent)
        print (self.nb.GetChildren())

if __name__ == '__main__':
    app = wx.App()
    f = wx.Frame(None, title='Notebook', size=(600, 400))
    win = TestPanel(f)
    f.Show()
    app.MainLoop()

```

Output in Classic:
> wxWindowList: [<wx._core.Window; proxy of <Swig Object of type 'wxWindow *' at 0x385bf40> >, <wx._windows.Frame; proxy of <Swig Object of type 'wxFrame *' at 0x234b120> >, <wx._controls.TextCtrl; proxy of <Swig Object of type 'wxTextCtrl *' at 0x368e7e0> >, <wx.aui.AuiTabCtrl; proxy of <Swig Object of type 'wxAuiTabCtrl *' at 0x242fa80> >]

Output in Phoenix:
> WindowList: [<wx._core.Window object at 0x0000000002822168>, <wx._core.Frame object at 0x00000000028221F8>, <wx._core.TextCtrl object at 0x0000000002741E58>, <wx._core.Control object at 0x0000000002822288>]

**Comment by mesalu** [comment]
Looks like wxAuiTabCtrl isn't properly documented in wxWidgets/interface causing the class name info to skip to wx.Control (the first wrapped class that SIP knows of.)
