### ISSUE TITLE
Make it easier to find the pre-built linux wheels

### ISSUE THREAD

**Issue by Korijn** [wxWidgets/Phoenix#667]
I tought I remembered there were linux wheels on pypi, but they are no longer there. Was this a conscious choice?

**Comment by Nutznieser** [comment]
Look at the Download section of the [wxPython Homepage](https://www.wxpython.org/pages/downloads/). There you can find an explanation according linux wheels plus a download link, but also the reason why they are not on PyPi.

**Comment by DietmarSchwertberger** [comment]
I think that the info about Linux binaries should be more prominent.

This hint in the first section usually results in trying to build from source first:
**"If there is no binary wheel file available for your platform or Python, then pip will download the source archive and will attempt to build it for you."**

This happened to me last week. Only after struggling an hour with the dependencies and googling around I found the way how to install from binaries.
(And Google did not find the downloads page, but https://stackoverflow.com/questions/47246947/not-able-to-install-new-wxpython .)

It would be better to include the Linux hint right in the first section and also on the PyPI page
(or maybe restructure the downloads page a bit with obvious sections for binary and source installs).
I don't know about pip, but maybe it would be possible to include a hint.

**Comment by Korijn** [comment]
Honestly with this info I will be able to manage. I really admire the effort being put into the pypi wheels here. Excellent work!

**Comment by RobinD42** [comment]
> I think that the info about Linux binaries should be more prominent.

Good idea.

TODO: Tweak the downloads page and other info sources to emphasize linux binaries.

**Comment by mesalu** [comment]
@Robind42
I seem to recall linux sources being more prominent last I looked at the builds, is this issue resolved already?

**Comment by RobinD42** [comment]
I reordered and added to the content on the downloads page on the website to make things a little more clear, and so the linux user will see the info about the wheels before the paragraphs about building with pip.

https://github.com/wxWidgets/wxPyWeb/commit/cadacee58c1e9eeb134dd61fdc6ca4432a575816
