### ISSUE TITLE
Linux build for Fedora seems incomplete

### ISSUE THREAD

**Issue by Nutznieser** [wxWidgets/Phoenix#668]
**Operating system**: Linux Fedora 27
**wxPython version**: 4.0.0b2 from https://extras.wxpython.org/wxPython4/extras/linux/gtk3/fedora-26/
**Stock or custom build**:
**Python version**: 3.6.3
**Stock or custom build**:

**Description of the problem**:

When I load the html2 package with ...
```python
import wx.html2 as html2
```
I got the error message ...
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/harry/.local/lib/python3.6/site-packages/wx/html2.py", line 15, in <module>
    from ._html2 import *
ImportError: libwebkitgtk-3.0.so.0: cannot open shared object file: No such file or directory
```
If I look into the wxpython installation directory I didn't find this specific library. It seems it is missing inside the provided wheel on the wxPython Extras linux folder.

**Comment by HelioGuilherme66** [comment]
If you want to try newer packages, got them [here](http://robotframework.transformidea.com/RIDE/packages/Linux/Fedora_26/gtk3/)

**Comment by RobinD42** [comment]
You probably don't have the webkitgtk library installed. Search in your system's package manager (yum on Fedora) and install what you find there, (probably "webkit3".)

**Comment by Nutznieser** [comment]
Thanks for your hints!

@RobinD42: If I try to install webkitgtk3 it isn't available in default rpm's on Fedora 27. Package manager (dnf) only found webkitgtk4 and it is already installed. But it seems wxPython doesn't works with it.

**Comment by swt2c** [comment]
If you are trying to use Fedora 26 packages on Fedora 27, that is probably not going to work.

If you'd like use some RPMs built for Fedora 27, you can use my COPR:
https://copr.fedorainfracloud.org/coprs/swt2c/wxPython-Phoenix/

I try to keep them updated periodically.  Looks like they are about 45 days old, I'll update them now.

**Comment by Nutznieser** [comment]
@swt2c: Thanks for your info! But I guess it is for python2 and not python3, isn't it?

**Comment by swt2c** [comment]
My COPR has both python2 and python3 packages.  The python2 packages are not installed into the standard python path so as to not conflict with the official classic package.

**Comment by Nutznieser** [comment]
@swt2c: Thanks it works for now!
