### ISSUE TITLE
Collision between wx.LANGUAGE_HEBREW and wx.StaticBoxSizer

### ISSUE THREAD

**Issue by ofersadan85** [wxWidgets/Phoenix#675]
**Operating system**: Windows 10
**wxPython version**: 4.0.0b2
**Stock or custom build**: PyPi
**Python version**: Python 3.6.4rc1
**Stock or custom build**: stock, 32 bit

**Description of the problem**: When initializing app with a hebrew locale (wx.LANGUAGE_HEBREW) and setting a wx.StaticBoxSizer within another sizer, the wx.StaticBoxSizer distorts various widgets (like TextCtrl and more noticibly - ComboBox). 

In the sample code provided, commenting out the locale line fixes the problem, also switching to a regular wx.BoxSizer fixes it, but when the locale is mixed with wx.StaticBoxSizer the GUI is messed up...

# Sample code: 

```
import wx
class TestFrame(wx.Frame):
    def InitUI(self):
        self.panel = wx.Panel(self)
        #box = wx.BoxSizer() #uncomment here and comment next line to fix
        box = wx.StaticBoxSizer(wx.VERTICAL, self.panel, 'test')
        box.Add(wx.ComboBox(self.panel, style=wx.CB_READONLY, name='z', choices=['1','2','3']))
        self.panel.SetSizer(box)
        self.Show()

if __name__ == '__main__':
    app = wx.App()
    app.locale = wx.Locale(wx.LANGUAGE_HEBREW) #commenting this line also fix
    f=TestFrame(None)
    f.InitUI()
    app.MainLoop()
```

# Screenshots:

above code:
![normal](https://user-images.githubusercontent.com/18385610/34789948-cc6be1a4-f648-11e7-9a64-f19c5ab4b39c.PNG)

different sizer:
![sizer](https://user-images.githubusercontent.com/18385610/34789949-cc900bce-f648-11e7-89ca-84482a7020a5.PNG)

no locale:
![without_locale](https://user-images.githubusercontent.com/18385610/34789951-ccb53b7e-f648-11e7-8b63-7b6fbdd7400f.PNG)

**Comment by HelioGuilherme66** [comment]
Could you try a 4.0.0rc1 build?

At least on Linux, there is no problem:
**Operating system:** Fedora Core 26
**wxPython version:** 4.0.0rc1
**Stock or custom build:** vagrant build [4.0.0rc1.dev3549+ea4969d gtk3](https://robotframework.transformidea.com/RIDE/packages/Linux/Fedora_26/gtk3/wxPython-4.0.0rc1.dev3549+ea4969d-cp36-cp36m-linux_x86_64.whl) 
**Python version:**  3.6.3
**Stock or custom build:** stock

**Comment by RobinD42** [comment]
I've duplicated it on Windows with rc1. I expect that this issue is Windows-specific and is in wxWidget's ballpark. Please file a ticket for this at https://trac.wxwidgets.org and post a link here so we can track it.

**Comment by ofersadan85** [comment]
@RobinD42 I do not have a user there and prefer not to register so I cannot file a ticket over there, I just discovered this issue and saw no reference to it anywhere else, thought i'd let the devs know

**Comment by ofersadan85** [comment]
btw I have also tried to create a wx.StaticBox and then a wx.StaticBoxSizer (instead of doing it in one step) and it's the same problem. Also, the problem isn't limited to wx.ComboBox like in the example, a wx.TextCtrl has similar issues (flickers when the mouse passes over it) but other than that did not try other widgets

**Comment by RobinD42** [comment]
> @RobinD42 I do not have a user there and prefer not to register so I cannot file a ticket over there, I just discovered this issue and saw no reference to it anywhere else, thought i'd let the devs know

Since it's a wxWidgets issue then reporting at trac.wxwidgets.org is how you let the appropriate devs know.

**Comment by seanbudd** [comment]
I've filed a bug report for this here https://trac.wxwidgets.org/ticket/19086

Also, here is a wxPython workaround for this. Use this instead of StaticBoxSizer, which will fix the behaviour but also cause the group headers (StaticBox labels) to be on the left-hand side even if RTL is desired.

`
class LTRStaticBoxSizer(wx.StaticBoxSizer):
	"""
	An Overridden StaticBoxSizer as the original is buggy for RTL languages
	Awaiting bug-fix for issue: https://trac.wxwidgets.org/ticket/19086
	This override has a side effect of left alignment of grouping headers (StaticBox labels) for RTL languages
	"""
	def __init__(self, *args, **kw):
		super().__init__(*args, **kw)
		self.StaticBox.SetLayoutDirection(wx.Layout_LeftToRight)
`

**Comment by ofersadan85** [comment]
As [this ticket](https://trac.wxwidgets.org/ticket/19086) is closed and labeled "fixed" (thanks again @seanbudd ) I have tested it with the latest version using `pip install -u wxPython` and the problem still exists.

It seems that this is no longer a wxWidgets issue, is there any update planned that will include this fix in wxPython as well?

**Comment by swt2c** [comment]
@ofersadan85, well the fix was to the wxWidgets documentation, so there won't be a code fix coming to wxPython.  The wxWidgets documentation fix recommends that windows added to `wx.StaticBoxSizer` be created as children of `wx.StaticBox` itself.  Does that work for you?

**Comment by ofersadan85** [comment]
@swt2c If that's the best fix available then of course, I don't mind the issue closed (worked around that problem ages ago) just wanted to remind if necessary
