### ISSUE TITLE
Button with wx.BU_NOTEXT style returns empty string with GetLabel() in Linux/GTK

### ISSUE THREAD

**Issue by swprojects** [wxWidgets/Phoenix#678]
**Operating system**: Xubuntu 16.04
**wxPython version**: 4.0.0a2.dev3038+953a2e5 (GTK3)
**Python version**: 3.5.2

```python
import wx
                
class Main(wx.Frame):
    
    def __init__(self):
        wx.Frame.__init__(self, None)
        
        panel = wx.Panel(self)   
        sizer = wx.BoxSizer(wx.HORIZONTAL)
        
        # no text button
        btn = wx.Button(panel, label="BtnLabel1", style=wx.BU_NOTEXT)
        btn.Bind(wx.EVT_BUTTON, self.OnButton)
        sizer.Add(btn, 0, wx.ALL, 2)  
        
        # normal button
        btn = wx.Button(panel, label="BtnLabel2")
        btn.Bind(wx.EVT_BUTTON, self.OnButton)
        sizer.Add(btn, 0, wx.ALL, 2)   
        
        panel.SetSizer(sizer)
        self.Show()
        self.Centre() 
        
    def OnButton(self, event):
        e = event.GetEventObject()
        label = e.GetLabel()
        print(e.GetLabel()) # return ""
 
if __name__ == "__main__": 
    app = wx.App()
    frame = Main()
    app.MainLoop()
```

In Linux/GTK (but not Windows), creating a button with wx.BU_NOTEXT style returns empty string with GetLabel().

**Comment by RobinD42** [comment]
On GTK a different gtk widget is used when the `wx.BU_NOTEXT` is used and the label is never assigned to it.  I think this could be considered an implementation detail or a quirk of the platform. If you don't agree then please post the issue at trac.wxwidgets.org.

**Comment by DietmarSchwertberger** [comment]
I also would not see this as a bug. A button without a label does not have one...
It seems the OP is using the label to get a reference/data.

@swprojects:
You may assign an attribute to the button and retrieve this in the event handler:
```
btn.data = "1"
...
print(event.GetEventObject().data)
```

**Comment by Metallicow** [comment]
@DietmarSchwertberger  I understand assigning an attribute.

I believe the assumption is, is that when a button is created, that the button has a label(whether that be blank it should still represent what was sent to the original button). I would like to agree on this part...

if `button.myhack = 'woot'`
and I call `button.myhack`
whether it be built in or not it should return
`'woot'`
yep.

**Comment by Metallicow** [comment]
Solution: One might call this "operator error", depending on your point of view.
