### ISSUE TITLE
AGW Aui Pane Header Drawing Bug

### ISSUE THREAD

**Issue by Metallicow** [wxWidgets/Phoenix#686]
@infinity77 
While I have optimized and fixed bugs in my own xwx(Classic/Phoenix) custom copy of agw aui used for my SourceCoder, this is a bigger bug that I still haven't figured out how to fix yet and it is an obvious one that sticks out in the wxPy demo also. The best I can put it is it is a bug in the long looping process of drawing out agw aui interface.

**How to reproduce:**
Open the demo and start the agw 'AUI' demo. With the mouse grab one of the aui toolbars(I use a vertical one) by the gripper and start to move the toolbar up and down a bit in the available space without ripping it out of the user interface. You will notice the looping drawing steps of the aui auto notebook caption at the bottom(A third Auto-NB pane) flickering through all the pages captions. This seems to affect anything drawn as a pane header(icons, caption, min max close buttons, etc)

![agwaui](https://user-images.githubusercontent.com/4668356/34976662-26151320-fa5d-11e7-95cb-087756357970.png)

**Comment by RobinD42** [comment]
Fixed by #852
