### ISSUE TITLE
CustomDragAndDrop demo sluggish/focus problem

### ISSUE THREAD

**Issue by Metallicow** [wxWidgets/Phoenix#689]
**Operating system**: Win7
**wxPython version**: wxPython-4.0.0rc1.dev3597+5f1ee01-cp27-cp27m-win32
**Stock or custom build**: snapshots-build
**Python version**: 2.7.14
**Stock or custom build**: stock

**Description of the problem**:
In the CustomDragAndDrop demo drawing in the window updates as expected the first time, then when dragged to copy it works also as expected. When using the Draw radio button to draw again afterward, the drawing does not update as expected. I noticed when bringing the mouse back over the radio buttons it then updates the draw area. But drawing after the first getgo is still the same way.

**Comment by RobinD42** [comment]
Not sure I completely understand your description, but it all seems fine here.

**Comment by Metallicow** [comment]
I'm working on a new install for a testbox at the moment, I'll see if I can reproduce it there also...

**Comment by Metallicow** [comment]
This issue seems to have disappeared on the new testbox Win7 Ultimate SP1 with py2.7.14 fresh install.
I believe the only difference is a updated graphics driver and SP1. Closing.
