### ISSUE TITLE
FloatSpin not handling spin event correctly when near initial value

### ISSUE THREAD

**Issue by scaramallion** [wxWidgets/Phoenix#69]
``` python
import wx
import wx.lib.agw.floatspin as FS

class MainApp(wx.App):
    def OnInit(self):
        frame = Main(None, -1, 'floatspin test')
        frame.Show()
        return True

class Main(wx.Frame):
    def __init__(self, parent, id, title):
        wx.Frame.__init__(self, parent, id, title)

        spn = FS.FloatSpin(self, -1, increment=0.1, value=4.0)

        vb = wx.BoxSizer(wx.VERTICAL)
        vb.Add(spn)
        self.SetSizer(vb)

if __name__ == "__main__":
    app = MainApp(0)
    app.MainLoop()
```

Clicking up button to 4.2 and then down button to 3.9 gives the following: 4.0, 4.1, 4.2, 4.1, **4.0, 4.1**, 4.0, 3.9
Clicking up button from 3.9 gives: 3.9, 4.0, **4.1, 4.0**, 4.1, 4.2

This only occurs at the initial value. If you set an initial value of 5.0 then the same behaviour occurs around there. Also, you can see the button animation is correct when clicking.

Python version: 3.5.1
`wx.version()` gives 3.03.dev1964+f780b21

**Comment by scaramallion** [comment]
Also, using the mouse wheel works correctly, but after using the mouse wheel the value at which the mouse clicks produce the wrong values shifts to where you scroll to.

**Comment by scaramallion** [comment]
The problem seems to lie with wx.SpinButton. Transitioning down from the initial value causes the wx.SpinEvent.GetPosition() value to go from 0 to 100, which counts as a wx.EVT_SPIN_UP instead of a wx.EVT_SPIN_DOWN. The opposite then occurs when going back up to the initial value.

**Comment by swt2c** [comment]
I see what you mean.  This seems tricky to resolve as with the underlying wx.SpinButton, you have an underlying integer.

**Comment by swt2c** [comment]
There's a patch here that might address this issue:
http://trac.wxwidgets.org/ticket/16426

**Comment by scaramallion** [comment]
I've tried applying the patch but I end up with a TypeError during init:

```
   File ".../lib/python3.5/site_packages/wx/lib/agw/floatspin.py", line 935, in SetValue
      spinvalue = int(round(((value - min_val) / float(max_val - min_val)) *
TypeError: unsupported operand type(s) for /: 'FixedPoint' and 'float'
OnInit returned false, exiting...
```

It looks like the python3 `__truediv__` and `__round__` operators haven't been implemented for the FixedPoint class.

**Comment by swt2c** [comment]
Yeah, it looks like it needs some work.  Can you use `wx.SpinCtrlDouble`?

**Comment by scaramallion** [comment]
Things are OK on my end, I just added a couple of workarounds to fix the missing operators. Should I close the issue?

**Comment by swt2c** [comment]
Using the patch for FloatSpin?  No, I would leave it open until maybe Robin merges the patch.

**Comment by mesalu** [comment]
I'm not able to reproduce this, so I think its safe to assume a fix made its way in at some point. :)

**Comment by mbrennwa** [comment]
I am observing the same issue with FloatSpin, with integers. Here's a full example to illustrate the problem:

    import wx
    from wx.lib.agw.floatspin import FloatSpin

    class MainFrame(wx.Frame):

    def __init__(self):
        wx.Frame.__init__(self, None, title="FloatSpin Issue Demo")
        FloatSpin(self, value=1, min_val=0, increment=1, digits=0, size=(120, -1))
        self.Show()
        
    if __name__ == "__main__":
        app = wx.App(False)
        frame = MainFrame()
        app.MainLoop()

If the first click on the FloatSpin is on the "-" button, the initial value (1) should be decreased by 1 (to 0). However, in reality it gets _increased_ by 1 (to 2).

I am using GTK with wxPython 4.0.7 and Python 3.8.6 on Debian unstable. I believe this bug report should be re-opened. Or should I file a new report?

Is there a way (or a workaround) to make FloatSpin work correctly?

**Comment by swt2c** [comment]
If you are just wanting to have a spin control with integers, could you not use `wx.SpinCtrl` instead?

**Comment by mbrennwa** [comment]
I could use SpinCntrl in this example. However, the bug still exists in FloatSpin, which I also need in a different application for non-integers.Am 15.10.2020 01:53 schrieb Scott Talbert <notifications@github.com>:
If you are just wanting to have a spin control with integers, could you not use wx.SpinCtrl instead?
