### ISSUE TITLE
ImportError when trying to build the html docs using Sphinx

### ISSUE THREAD

**Issue by Demolishun** [wxWidgets/Phoenix#693]
**Operating system**: Windows 7
**wxPython version**:  4.0.0rc1
**Stock or custom build**: stock
**Python version**: 2.7.14
**Stock or custom build**: stock

**Description of the problem**:
After downloading the source from Github and running make in the docs/sphinx directory with the command: "make html" I get the following error:
Running Sphinx v1.6.6

Configuration error:
There is a programable error in your configuration file:

Traceback (most recent call last):
  File "c:\python27\lib\site-packages\sphinx\config.py", line 157, in __init__
    execfile_(filename, config)
  File "c:\python27\lib\site-packages\sphinx\util\pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "c:\python27\lib\site-packages\six.py", line 709, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "conf.py", line 60, in <module>
    from buildtools.config import Config
ImportError: No module named buildtools.config

I did do a pip install buildtools --upgrade and I still get the same error.  Is there another place I can download the docs for pheonix?  

```python
# Put code sample here
```

**Comment by mesalu** [comment]
All docs are available online:
https://wxpython.org/Phoenix/docs/html/

If I remember correctly there are tarballs here:
https://wxpython.org/Phoenix/snapshot-builds/
containing the documentation as well.

**Comment by RobinD42** [comment]
The prerelease snapshot builds include the documentation. You can get them here: https://wxpython.org/Phoenix/snapshot-builds/

For the record, there is a lot of content for the docs that is generated during the build, and as you've seen there is also some supporting code that is needed during the build of the docs. So just downloading and running sphinx is not enough. Nearly everything in the project relating to project development is driven by the `build.py` script. To do a build from a git checkout, including the docs, you'll need to do something like this:

```
    python build.py dox etg sip build wxlib sphinx
```

If you're working from a source tarball instead of the git checkout, then only the last three command args are needed.

**Comment by Demolishun** [comment]
I downloaded a tarball as suggested.  I am running "python build.py build wxlib sphinx".  I installed visual c++ 2008 as it matches the version of python I have 32 bit and all that.  It now errors out at with this message: "msvc: Impossible to find a valid architecture for building (in setup_msvc)".  The tarball is: wxPython-4.0.0rc1.dev3549+ea4969d.tar.gz

All I want is an offline version of the docs for a machine that does not have internet all the time.  

Are you using msvc 2008 for the Phoenix code?

Thanks

**Comment by Demolishun** [comment]
Okay, I solved the issue another way, I hope.  I saw on the documentation site I could wxdocs to get the documentation.  I tried that and it gave me an error not being able to find wxget.  Then I ran wxget and it popped up and asked if I wanted to download a tarball with wx documentation in it.  So I said yes!  It seems to have retrieved an HTML version of the docs.

**Comment by RobinD42** [comment]
The docs can also be downloaded manually if desired.  The release versions are in https://extras.wxpython.org/wxPython4/extras/ and as mentioned before the preview snapshot version of the docs are in https://wxpython.org/Phoenix/snapshot-builds/
