### ISSUE TITLE
DC logical operations are broken in gtk3

### ISSUE THREAD

**Issue by robmcmullen** [wxWidgets/Phoenix#696]
**Operating system**: linux
**wxPython version**: git-head, 4.0b2
**Stock or custom build**: custom or stock, shows up in both
**Python version**: 2.7
**Stock or custom build**: stock

**Description of the problem**:

The "Mask" demo under the **Using Images** category in  in the wxpython demo shows this on windows:

![windows-masks](https://user-images.githubusercontent.com/896656/35117915-05181476-fc45-11e7-9864-6e8352768a69.png)

and shows this on linux/gtk3:

![gtk3-masks](https://user-images.githubusercontent.com/896656/35117931-11c4e79e-fc45-11e7-9ce8-c604f2d747ef.png)

**Comment by swt2c** [comment]
This doesn't appear to be specific to wxPython, can you report at https://trac.wxwidgets.org/

**Comment by robmcmullen** [comment]
Seems like it's been an issue for a long time. I added the GTK image to https://trac.wxwidgets.org/ticket/2461

**Comment by robmcmullen** [comment]
I'll go ahead and close this since it seems to be in wxWidgets, not wxPython.

**Comment by RobinD42** [comment]
@robmcmullen, it's to be expected on OSX due to the design of the system UI, but I don't think I've heard anything about it being expected on GTK3 so you should probably make a new ticket for it.

**Comment by swt2c** [comment]
I agree, that ticket is only about macOS, I would open a separate ticket.

**Comment by robmcmullen** [comment]
https://trac.wxwidgets.org/ticket/18050

**Comment by robmcmullen** [comment]
What do you think, is this the same problem or a new one? This is lines, not images; the first column of horizontal lines is drawn normally, the second column of is a line XORed with itself.

Windows:

![virtualbox_omnimon dev py32_20_01_2018_18_00_26](https://user-images.githubusercontent.com/896656/35189979-b4d5e4d4-fe0b-11e7-8328-f3b9a6fee3a8.png)

GTK3:

![screenshot_2018-01-20_17-59-53](https://user-images.githubusercontent.com/896656/35189981-bc0724b6-fe0b-11e7-8640-5e37936ab3e9.png)

```python
import wx

class DrawPanel(wx.Panel):
    def __init__(self, *args, **kwargs):
        wx.Panel.__init__(self, *args, **kwargs)

        self.Bind(wx.EVT_PAINT, self.OnPaint)
        self.Bind(wx.EVT_SIZE, self.OnSize)

    def OnPaint(self, event):
        dc = wx.PaintDC(self)
        dc.SetBackground(wx.Brush(wx.Colour(80, 140, 180)))
        dc.Clear()
        w, h = self.GetClientSize()
        dc.SetBrush(wx.Brush(wx.WHITE))
        for y in range(0, 350, 20):
            dc.SetLogicalFunction(wx.COPY)
            dc.SetPen(wx.Pen(wx.Colour(80, y/2, 20)))
            dc.DrawLine(30, y, 170, y)

            dc.SetLogicalFunction(wx.XOR)
            dc.DrawLine(230, y, 370, y)
            dc.DrawLine(230, y, 370, y)

    def OnSize(self, event):
        self.Refresh()
        self.Update()


if __name__ == "__main__":
    app = wx.App()
    frame = wx.Frame(None, -1, "Test", size=(400,400))
    s = DrawPanel(frame, 1000)
    frame.Show(True)
    app.MainLoop()
```

**Comment by RobinD42** [comment]
Yep, it is probably the same.

**Comment by robmcmullen** [comment]
Not good news from vadz:

> I'm afraid it might well be fundamentally impossible to implement the logical operations concept with modern graphics systems such as CoreGraphics or recent GTK+ versions, so I don't think this is ever going to be fixed and we'll probably end up deprecating and then removing this API.

The SetLogicalFunction call is used in only a handful of places, mostly for feedback when not using live updates (MultiSash, FourWaySplitter, CubeColorDialog, etc.) so the feedback is invisible on GTK3.
