### ISSUE TITLE
[Tracking] Elementary OS 'Double Border' issue. 

### ISSUE THREAD

**Issue by mesalu** [wxWidgets/Phoenix#698]
**This is a tracking issue**, wxWidgets has a bug that causes this. This issue is set to help us track the progress of their issue.

**wxWidgets trac ticket**  https://trac.wxwidgets.org/ticket/17971#no1

**Operating system**: Elementary OS (Ubuntu based linux flavor)
**wxPython version**: Any GTK3
**Stock or custom build**: Any
**Python version**: Any
**Stock or custom build**:  

**Description of the problem**: Under Elementary OS Loki, a double 'border' is drawn around top level windows.

Just launching the demo is sufficient. 

An example:

![double_border_issue](https://user-images.githubusercontent.com/6109654/35169582-e7de9b8c-fd11-11e7-88c5-f9adc4c65778.jpg)

**Comment by zalech** [comment]
Look into this thread: https://github.com/numixproject/numix-gtk-theme/issues/206

**Comment by mesalu** [comment]
Sweet, thanks @zalech. I'll take a look.

**Comment by mesalu** [comment]
I was able to reduce the shadow-area by setting:
```css
.window-frame {
    box-shadow: none;
    margin: 1;
}

However the secondary header bar remains, and seems immune to style changes. (E.g. changed the background colour and the inner headerbar changed, but not the outer)

**Comment by aventrax** [comment]
Same here on Elementary OS 0.4.1 but it's still there on Ubuntu 18.04 on gnome.

The problem disappear using openbox in place of Gala/gnome-session/Xfwm4 (all affected).

**Comment by ianharrigan** [comment]
Is there anymore info on this issue? Im using 3.1.2 and am getting the exact same issue. 

Thanks,
Ian

**Comment by mesalu** [comment]
Looks like the ticket on wxWidget's side hasn't been modified in nearly 2 years. :\

**Comment by RobinD42** [comment]
There's some more discussion about this happening this week, but no real progress yet on determining the cause, other than it is probably some weird interaction with the Pantheon DE.

https://groups.google.com/d/msg/wx-dev/ecynXuLDFc4/jsUsNuOXDgAJ

**Comment by DGxInfinitY** [comment]
Has anyone by chance noticed any progress yet? Still having this problem and now with more mainstream applications such as Audacity.

**Comment by mesalu** [comment]
It looks like a fix went into wxWidgets ~4 months ago and was backported to older versions of wx. It also looks like Phoenix's master branch includes that commit, though the fix is not included in Phoenix's 4.0.x branch.

I'm not certain if an official release of Phoenix has the fix included, but builds off of master branch *should* (note: I have not verified it myself) work.

**Comment by mesalu** [comment]
<img width="1591" alt="Screen Shot 2020-07-08 at 11 54 06 PM" src="https://user-images.githubusercontent.com/6109654/87006965-58e62180-c176-11ea-92f8-7de1b0368a09.png">

Just tested a fresh build from master, looks like its fixed there.

**Comment by ianharrigan** [comment]
I can also confirm, master wx as of today also no longer has the double border issue! Elementary is a go once again! Thanks for the heads up @mesalu 

Ian

**Comment by RobinD42** [comment]
That's good news indeed.
