### ISSUE TITLE
wx.ProgressDialog SetRange Problem

### ISSUE THREAD

**Issue by wekay102200** [wxWidgets/Phoenix#701]
**Operating system**:
windows7
**wxPython version**:
3.0.2
**Stock or custom build**:
**Python version**:
2.7
**Stock or custom build**:

**Description of the problem**:

I create a ProgressDialog:
dlg = wx.ProgressDialog("Progress dialog example",
"An informative message",
maximum = 100,
parent=self,
style = 0
| wx.PD_APP_MODAL
| wx.PD_CAN_ABORT
#| wx.PD_CAN_SKIP
#| wx.PD_ELAPSED_TIME
| wx.PD_ESTIMATED_TIME
| wx.PD_REMAINING_TIME
#| wx.PD_AUTO_HIDE
)
When I call dlg.SetRange method,It occur problem below:
Traceback (most recent call last):
File "D:\env\wxpython_test\thread_test_2.py", line 137, in onButton2
dlg.SetRange(120)
File "C:\Python27\lib\site-packages\wx-3.0-msw\wx_windows.py", line 3744, in SetRange
return windows.GenericProgressDialog_SetRange(*args, **kwargs)
wx._core.PyAssertionError: C++ assertion "m_gauge" failed at ....\src\generic\progdlgg.cpp(610) in wxGenericProgressDialog::SetRange(): dialog should
be fully created

But the dlg.Update and other method work ok.
this probem only occur on windows os system,It work fine on linux os system.
What's the probelm may be and How to avoid this ?

```python
import time
import wx

########################################################################
class MyForm(wx.Frame):
 
    #----------------------------------------------------------------------
    def __init__(self):
        wx.Frame.__init__(self, None, wx.ID_ANY, "Tutorial")
 
        # Add a panel so it looks the correct on all platforms
        panel = wx.Panel(self, wx.ID_ANY)
        self.displayLbl = wx.StaticText(panel, label="Amount of time since thread started goes here")
        self.btn = btn = wx.Button(panel, label="Start Thread")
 
        btn.Bind(wx.EVT_BUTTON, self.onButton2)
 
        sizer = wx.BoxSizer(wx.VERTICAL)
        sizer.Add(self.displayLbl, 0, wx.ALL|wx.CENTER, 5)
        sizer.Add(btn, 0, wx.ALL|wx.CENTER, 5)
        panel.SetSizer(sizer)
 
        # create a pubsub receiver

    def onButton2(self,event):
        dlg = wx.ProgressDialog("Progress dialog example",
                               "An informative message",
                               maximum = 100,
                               parent=self,
                               style = 0
                                | wx.PD_APP_MODAL
                                | wx.PD_CAN_ABORT
                                #| wx.PD_CAN_SKIP
                                #| wx.PD_ELAPSED_TIME
                                | wx.PD_ESTIMATED_TIME
                                | wx.PD_REMAINING_TIME
                                #| wx.PD_AUTO_HIDE
                                )
        dlg.SetRange(120)
    #----------------------------------------------------------------------
    def updateDisplay(self, msg):
        """
        Receives data from thread and updates the display
        """
        t = msg
        if isinstance(t, int):
            self.displayLbl.SetLabel("Time since thread started: %s seconds" % t)
        else:
            self.displayLbl.SetLabel("%s" % t)
            self.btn.Enable()
 
#----------------------------------------------------------------------
# Run the program
if __name__ == "__main__":
    app = wx.PySimpleApp()
    frame = MyForm().Show()
    app.MainLoop()
```

**Comment by RobinD42** [comment]
We're working on understanding this problem but in the meantime you can use the `wx.GenericProgressDialog` as a workaround.

**Comment by mesalu** [comment]
We've come to a conclusion and should have it implemented soon.
