### ISSUE TITLE
NameError: name 'AuiPaneInfoArray' is not defined

### ISSUE THREAD

**Issue by hungta** [wxWidgets/Phoenix#703]
After building and installing Phoenix (by: 
`python build.py dox etg --nodoc sip build`

And:

```
python build.py install)
run the demo: python demo/demo.py, the error occurred:
Traceback (most recent call last):
  File "demo/demo.py", line 3, in <module>
    import Main
  File "/home/clovis/wxWidgets/Phoenix/demo/Main.py", line 133, in <module>
    module = __import__(mod)
  File "/usr/local/lib/python2.7/dist-packages/wx/aui.py", line 21, in <module>
    AuiPaneInfoArray.__repr__ = _AuiPaneInfoArray___repr__
NameError: name 'AuiPaneInfoArray' is not defined
```

Can someone look at it?
Thanks.

**Comment by RobinD42** [comment]
Did you install to `/usr/local/lib/python2.7/dist-packages`? The build command you gave would not have done that. If not then you may be importing the wrong wx at runtime, or perhaps it's getting the two mixed up. 

By default the build sets things up to be used from the source folder. You can ensure that is the version of wxPython being imported by setting `PYTHONPATH` appropriately, or you can use `pip install -e .` to have pip install a file in Python to redirect the import to the wx package in your source folder.

**Comment by hungta** [comment]
Hi Robin,
Yes, the /usr/local/lib/python2.7/dist-packages was installed:
ls -l /usr/local/lib/python2.7/dist-packages/
total 1180
drwxr-sr-x  3 root staff   4096 Th01  2 09:10 asn1crypto
drwxr-sr-x  2 root staff   4096 Th01  2 09:10 asn1crypto-0.24.0.dist-info
drwxr-sr-x  2 root staff   4096 Th01  2 09:10 bcrypt
drwxr-sr-x  2 root staff   4096 Th01  2 09:10 bcrypt-3.1.4.dist-info
drwxr-sr-x  2 root staff   4096 Th01 19 14:47 certifi
drwxr-sr-x  2 root staff   4096 Th01 19 14:47 certifi-2018.1.18.dist-info
drwxr-sr-x  2 root staff   4096 Th01  2 09:10 cffi
drwxr-sr-x  2 root staff   4096 Th01  2 09:10 cffi-1.11.2.dist-info
-rwxr-xr-x  1 root staff 779576 Th01  2 09:10 _cffi_backend.so
drwxr-sr-x  3 root staff   4096 Th01 19 14:15 chardet
drwxr-sr-x  2 root staff   4096 Th01 19 14:15 chardet-3.0.4.dist-info
drwxr-sr-x 10 root staff   4096 Th01  2 09:09 Crypto
drwxr-sr-x  4 root staff   4096 Th01  2 09:10 cryptography
drwxr-sr-x  2 root staff   4096 Th01  2 09:10 cryptography-2.1.4.dist-info
drwxr-sr-x  4 root staff   4096 Th01 19 09:46 dox
drwxr-sr-x  2 root staff   4096 Th01 19 09:46 dox-0.2.0.dist-info
drwxr-sr-x  2 root staff   4096 Th01  2 09:10 enum
drwxr-sr-x  2 root staff   4096 Th01  2 09:10 enum34-1.1.6.dist-info
drwxr-sr-x  2 root staff   4096 Th01  2 09:10 idna
drwxr-sr-x  2 root staff   4096 Th01  2 09:10 idna-2.6.dist-info
drwxr-sr-x  2 root staff   4096 Th01  2 09:09 ipaddress-1.0.19.egg-info
-rw-r--r--  1 root staff  79852 Th12 17 04:18 ipaddress.py
-rw-r--r--  1 root staff  76934 Th01  2 09:09 ipaddress.pyc
drwxr-sr-x  2 root staff   4096 Th01 19 14:15 jinja2
drwxr-sr-x  2 root staff   4096 Th01 19 14:15 Jinja2-2.10.dist-info
drwxr-sr-x  5 root staff   4096 Th01  2 09:09 lxml
drwxr-sr-x  2 root staff   4096 Th01  2 09:09 lxml-4.1.1.dist-info
drwxr-sr-x  2 root staff   4096 Th01 19 14:15 markupsafe
drwxr-sr-x  2 root staff   4096 Th01 19 14:15 MarkupSafe-1.0.egg-info
drwxr-sr-x  4 root staff   4096 Th01  2 09:10 nacl
drwxr-sr-x  5 root staff   4096 Th01 19 09:46 pbr
drwxr-sr-x  2 root staff   4096 Th01 19 09:46 pbr-0.11.1.dist-info
drwxr-sr-x 10 root staff   4096 Th01 19 09:47 pip
drwxr-sr-x  2 root staff   4096 Th01 19 09:47 pip-9.0.1.dist-info
drwxr-sr-x  5 root staff   4096 Th01  2 09:10 pyasn1
drwxr-sr-x  2 root staff   4096 Th01  2 09:10 pyasn1-0.4.2.dist-info
drwxr-sr-x  3 root staff   4096 Th01  2 09:10 pycparser
drwxr-sr-x  2 root staff   4096 Th01  2 09:10 pycparser-2.18.egg-info
drwxr-sr-x  2 root staff   4096 Th01  2 09:09 pycrypto-2.6.1.egg-info
drwxr-sr-x  6 root staff   4096 Th01 19 14:15 pygments
drwxr-sr-x  2 root staff   4096 Th01 19 14:15 Pygments-2.2.0.dist-info
drwxr-sr-x  2 root staff   4096 Th01  2 09:10 PyNaCl-1.2.1.dist-info
drwxr-sr-x  2 root staff   4096 Th01 19 09:46 PyYAML-3.12.egg-info
drwxr-sr-x  2 root staff   4096 Th01 19 14:47 requests
drwxr-sr-x  2 root staff   4096 Th01 19 14:47 requests-2.18.4.dist-info
drwxr-sr-x  2 root staff   4096 Th01  2 09:10 six-1.11.0.dist-info
-rw-r--r--  1 root staff  30888 Th01  2 09:10 six.py
-rw-r--r--  1 root staff  30210 Th01  2 09:10 six.pyc
drwxr-sr-x  5 root staff   4096 Th01 19 14:47 urllib3
drwxr-sr-x  2 root staff   4096 Th01 19 14:47 urllib3-1.22.dist-info
drwxr-sr-x  7 root staff   4096 Th01 22 16:22 wx
drwxr-sr-x  2 root staff   4096 Th01 17 15:25 wxPython-3.0.3.0.egg-info
drwxr-sr-x  2 root staff   4096 Th01 22 16:22 wxPython-4.0.0rc1.egg-info
drwxr-sr-x  2 root staff   4096 Th01 19 09:46 yaml

And:

ls -l /usr/local/lib/python2.7/dist-packages/wx
total 195200
-rw-rw-r--  1 root staff     6407 Th01 22 15:50 adv.py
-rw-r--r--  1 root staff     6412 Th01 22 16:22 adv.pyc
-rw-rw-r--  1 root staff   122390 Th01 22 15:48 adv.pyi
-rwxrwxr-x  1 root staff 10138696 Th01 22 16:15 _adv.so
-rw-r--r--  1 root staff     9600 Th01 17 12:56 animate.py
-rw-r--r--  1 root staff    15450 Th01 17 14:49 animate.pyc
-rwxrwxr-x  1 root staff   943221 Th01 17 13:15 _animate.so
-rw-rw-r--  1 root staff     4350 Th01 22 15:50 aui.py
-rw-r--r--  1 root staff     5151 Th01 22 16:22 aui.pyc
-rw-rw-r--  1 root staff    82634 Th01 22 15:48 aui.pyi
-rwxrwxr-x  1 root staff  3267609 Th01 17 13:15 _aui.so
drwxr-sr-x  2 root staff     4096 Th01 17 15:25 build
-rw-r--r--  1 root staff    26779 Th01 17 12:56 calendar.py
-rw-r--r--  1 root staff    35705 Th01 17 14:49 calendar.pyc
-rwxrwxr-x  1 root staff  1079253 Th01 17 13:14 _calendar.so
-rw-r--r--  1 root staff    37784 Th01 17 12:56 combo.py
-rw-r--r--  1 root staff    48905 Th01 17 14:49 combo.pyc
-rwxrwxr-x  1 root staff  1547098 Th01 17 13:14 _combo.so
-rw-r--r--  1 root staff   332374 Th01 17 12:56 _controls.py
-rw-r--r--  1 root staff   437348 Th01 17 14:49 _controls.pyc
-rwxrwxr-x  1 root staff  7007107 Th01 17 13:14 _controls_.so
-rw-r--r--  1 root staff   635313 Th01 17 12:56 _core.py
-rw-rw-r--  1 root staff   131891 Th01 22 15:49 core.py
-rw-r--r--  1 root staff   833055 Th01 17 14:49 _core.pyc
-rw-r--r--  1 root staff   144705 Th01 22 16:22 core.pyc
-rw-rw-r--  1 root staff  1189785 Th01 22 15:48 core.pyi
-rwxrwxr-x  1 root staff  8881927 Th01 17 13:12 _core_.so
-rwxrwxr-x  1 root staff 94682120 Th01 22 16:13 _core.so
-rw-rw-r--  1 root staff     8817 Th01 22 15:49 dataview.py
-rw-r--r--  1 root staff     8835 Th01 22 16:22 dataview.pyc
-rw-rw-r--  1 root staff    89219 Th01 22 15:48 dataview.pyi
-rwxrwxr-x  1 root staff  7125208 Th01 22 16:17 _dataview.so
-rw-r--r--  1 root staff   321841 Th01 17 12:56 _gdi.py
-rw-r--r--  1 root staff   424995 Th01 17 14:49 _gdi.pyc
-rwxrwxr-x  1 root staff  6311383 Th01 17 13:13 _gdi_.so
-rw-rw-r--  1 root staff      643 Th01 19 09:42 gizmos.py
-rw-r--r--  1 root staff      182 Th01 22 16:22 gizmos.pyc
-rwxrwxr-x  1 root staff  4491786 Th01 17 13:17 _gizmos.so
-rw-rw-r--  1 root staff      288 Th01 22 15:50 glcanvas.py
-rw-r--r--  1 root staff      316 Th01 22 16:22 glcanvas.pyc
-rw-rw-r--  1 root staff     4052 Th01 22 15:46 glcanvas.pyi
-rwxrwxr-x  1 root staff   835816 Th01 22 16:20 _glcanvas.so
-rw-rw-r--  1 root staff     8723 Th01 22 15:49 grid.py
-rw-r--r--  1 root staff     9452 Th01 22 16:22 grid.pyc
-rw-rw-r--  1 root staff   105261 Th01 22 15:48 grid.pyi
-rwxrwxr-x  1 root staff  7665288 Th01 22 16:18 _grid.so
-rw-rw-r--  1 root staff     1482 Th01 22 15:50 html2.py
-rw-r--r--  1 root staff     1400 Th01 22 16:22 html2.pyc
-rw-rw-r--  1 root staff    15782 Th01 22 15:48 html2.pyi
-rwxrwxr-x  1 root staff  1093271 Th01 17 13:16 _html2.so
-rw-rw-r--  1 root staff     1489 Th01 22 15:50 html.py
-rw-r--r--  1 root staff     1647 Th01 22 16:22 html.pyc
-rw-rw-r--  1 root staff    71183 Th01 22 15:49 html.pyi
-rwxrwxr-x  1 root staff  8028096 Th01 22 16:20 _html.so
-rw-rw-r--  1 root staff      621 Th01 19 09:42 __init__.py
-rw-r--r--  1 root staff      286 Th01 22 16:22 __init__.pyc
drwxr-sr-x 16 root staff     4096 Th01 22 16:22 lib
drwxr-sr-x 43 root staff     4096 Th01 22 16:22 locale
-rw-rw-r--  1 root staff     1142 Th01 22 15:50 media.py
-rw-r--r--  1 root staff     1259 Th01 22 16:22 media.pyc
-rw-rw-r--  1 root staff     6640 Th01 22 15:48 media.pyi
-rwxrwxr-x  1 root staff   952486 Th01 17 13:14 _media.so
-rw-r--r--  1 root staff   264089 Th01 17 12:56 _misc.py
-rw-r--r--  1 root staff   382538 Th01 17 14:49 _misc.pyc
-rwxrwxr-x  1 root staff  5663473 Th01 17 13:14 _misc_.so
-rw-rw-r--  1 root staff      270 Th01 22 15:50 msw.py
-rw-r--r--  1 root staff      293 Th01 22 16:22 msw.pyc
-rw-rw-r--  1 root staff     3851 Th01 22 15:48 msw.pyi
-rw-rw-r--  1 root staff    64197 Th01 22 15:50 propgrid.py
-rw-r--r--  1 root staff    26569 Th01 22 16:22 propgrid.pyc
-rw-rw-r--  1 root staff   205659 Th01 22 15:49 propgrid.pyi
-rwxrwxr-x  1 root staff  6357724 Th01 17 13:16 _propgrid.so
drwxr-sr-x  3 root staff     4096 Th01 22 16:22 py
-rw-rw-r--  1 root staff     2307 Th01 22 15:49 ribbon.py
-rw-r--r--  1 root staff     2489 Th01 22 16:22 ribbon.pyc
-rw-rw-r--  1 root staff    70204 Th01 22 15:48 ribbon.pyi
-rw-rw-r--  1 root staff     6426 Th01 22 15:50 richtext.py
-rw-r--r--  1 root staff     8100 Th01 22 16:22 richtext.pyc
-rw-rw-r--  1 root staff   292267 Th01 22 15:49 richtext.pyi
-rwxrwxr-x  1 root staff  4899509 Th01 17 13:15 _richtext.so
-rwxrwxr-x  1 root staff   399024 Th01 22 15:50 siplib.so
-rw-rw-r--  1 root staff     2591 Th01 22 15:50 stc.py
-rw-r--r--  1 root staff     2674 Th01 22 16:22 stc.pyc
-rw-rw-r--  1 root staff   173842 Th01 22 15:46 stc.pyi
-rwxrwxr-x  1 root staff  2075400 Th01 22 16:18 _stc.so
drwxr-sr-x  4 root staff     4096 Th01 22 16:22 tools
-rw-rw-r--  1 root staff      246 Th01 22 15:50 __version__.py
-rw-r--r--  1 root staff      349 Th01 22 16:22 __version__.pyc
-rw-rw-r--  1 root staff      725 Th01 22 15:49 webkit.py
-rw-r--r--  1 root staff      777 Th01 22 16:22 webkit.pyc
-rw-rw-r--  1 root staff     7464 Th01 22 15:48 webkit.pyi
-rwxrwxr-x  1 root staff  1007601 Th01 17 13:14 _webkit.so
-rw-r--r--  1 root staff   245598 Th01 17 12:56 _windows.py
-rw-r--r--  1 root staff   342654 Th01 17 14:49 _windows.pyc
-rwxrwxr-x  1 root staff  5120723 Th01 17 13:13 _windows_.so
-rw-r--r--  1 root staff    19603 Th01 17 12:56 wizard.py
-rw-r--r--  1 root staff    27664 Th01 17 14:49 wizard.pyc
-rwxrwxr-x  1 root staff  1201625 Th01 17 13:15 _wizard.so
-rw-rw-r--  1 root staff      411 Th01 22 15:49 xml.py
-rw-r--r--  1 root staff      460 Th01 22 16:22 xml.pyc
-rw-rw-r--  1 root staff    11620 Th01 22 15:46 xml.pyi
-rw-rw-r--  1 root staff     2180 Th01 22 15:49 xrc.py
-rw-r--r--  1 root staff     2730 Th01 22 16:22 xrc.pyc
-rw-rw-r--  1 root staff    18689 Th01 22 15:46 xrc.pyi
-rwxrwxr-x  1 root staff  1489634 Th01 17 13:15 _xrc.so

I don't know why there is that issue. Do I miss some installation steps?
Thanks.

**Comment by RobinD42** [comment]
> And:
> ls -l /usr/local/lib/python2.7/dist-packages/wx

It looks like there are some files from Classic in there too. You'll probably want to clean out all traces of wx in dist-packages and try again.

**Comment by RobinD42** [comment]
P.S. Building a wheel file and installing it in a virtualenv would help insulate you from things like this.

**Comment by hungta** [comment]
After I cleaned up the dist-packages and reinstalled Phoenix, I could run the demo/demo.py.
But I still got an error while running demo/AUI_Notebook.py:
clovis@clovis-VirtualBox:~/Phoenix$ python demo/AUI_Notebook.py 
Traceback (most recent call last):
  File "demo/AUI_Notebook.py", line 4, in <module>
    import wx.aui as aui
  File "/usr/local/lib/python2.7/dist-packages/wx/aui.py", line 15, in <module>
    from ._aui import *
ImportError: No module named _aui
Some questions:
1.Why doesn't your installation script overwrite the existing dist-packages/wx contents?
2. Why does demo/AUI_Notebook.py have the above error?
Thanks!

**Comment by mesalu** [comment]
Phoenix wants to 'play nice' with other packages. Including itself.  Blowing out another managed package upon installation would be categorically not-playing-nice.
Along these lines, Phoenix doesn't move libraries to system folders and insteads chooses to use them locally. This is done to encapsulate separate installations from eachother. E.g. virtualenv.

Another result of keeping things local is simplicity. Its far easier to manage local paths across all distros than system paths that vary by distro. 

As for the import error. I suspect that some phoenix-files got blown out and weren't reinstalled. I'll defer to @RobinD42's opinion there though.

**Comment by RobinD42** [comment]
@hungta what exact commands are you using to build and install? Which linux distro are you working on?

I strongly suggest to build a Python wheel for wxPython and then using pip to install that, instead of using build.py's or setuptools' install command.  Pip will take care of cleaning out old installs when you upgrade (assuming the prior install was done with pip or easy_install or at least has proper package info available such as manually installed eggs.) It will also remove and clean everything when pip uninstalls the package. Pip also better understands working with virtualenvs, installing to user-local site-packages, etc.

If you're working from a wxPython source tree then you can have wxPython's `build.py` build a wheel by adding `bdist_wheel` to whatever you're already using on the command-line, like: 

```
$ python etg sip build.py build bdist_wheel
```

Or you can use pip to build the wheel for you. It can fetch the source archive from PyPI: 

```
$ pip install -v wxPython
```
Or pip can use a specified source archive file, such as one of the snapshot builds, or etc. 

```
pip install -v wxPython-4.0.0rc1.dev3607+c1a0a4d.tar.gz
```

It can build and install in a single step as shown above, or just build the wheel file which you can save and install later as needed.

```
$ pip wheel -v wxPython
...
$ ls -al *.whl
-rw-r--r-- 1 robind robind 91049212 Jan 25 11:05 wxPython-4.0.0b2-cp27-cp27mu-linux_x86_64.whl
$ pip install -U wxPython-4.0.0b2-cp27-cp27mu-linux_x86_64.whl
```

As you can see here I have no trouble importing wx.aui after doing the above, either with the system python or with a virtualenv (tested on Ubuntu 17.04):

```
# using the system python
$ python
Python 2.7.13 (default, Nov 23 2017, 15:37:09) 
[GCC 6.3.0 20170406] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import wx
>>> wx.version()
'4.0.0b2 gtk3 (phoenix)'
>>> import wx.aui
>>> wx
<module 'wx' from '/home/robind/.local/lib/python2.7/site-packages/wx/__init__.pyc'>
>>> wx.aui
<module 'wx.aui' from '/home/robind/.local/lib/python2.7/site-packages/wx/aui.pyc'>
>>> 

# using a virtualenv
$ source ~/.myPyEnv/Py27/bin/activate
$ pip install wxPython-4.0.0b2-cp27-cp27mu-linux_x86_64.whl
...
$ python
Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import wx
>>> wx.version()
'4.0.0b2 gtk3 (phoenix)'
>>> import wx.aui
>>> wx
<module 'wx' from '/home/robind/.myPyEnv/Py27/local/lib/python2.7/site-packages/wx/__init__.pyc'>
>>> wx.aui
<module 'wx.aui' from '/home/robind/.myPyEnv/Py27/local/lib/python2.7/site-packages/wx/aui.pyc'>
>>> 
```

**Comment by mesalu** [comment]
DId you run the `dox` command?
It generates xml that the other stages are dependent on to properly wrap wxWidgets.

**Comment by RobinD42** [comment]
> But still failed.

If you don't tell us how it failed then we don't know what to fix.

> So, I think building and installing wxPython Phoenix from source using build.py still contain bugs 

Actually, if it worked with pip then using `build.py` directly will work too, if used correctly, because it does nearly the same thing. It just uses a different path to get there. Pip uses `setup.py`, which in our case then uses `build.py` to do all the build steps. The `build.py` script will also go back to `setup.py` for some things like installs or building wheels.

Also, unless you need the bleeding edge snapshot builds then there are already built packages for Ubuntu 14 and 16 for the wxPython releases available in the extras archive. See "Yes, we have Linux Wheels. Sort of." at https://wxpython.org/pages/downloads/

**Comment by mesalu** [comment]
Looks like there was a typo in a previous comment as well.

```bash
$ python etg sip build.py build bdist_wheel
```

Should be:

```bash
$python build.py dox etg sip build bdist_wheel
```
I also recommend using `--nodoc` after etg.
I've edited the source comment accordingly
