### ISSUE TITLE
dataview.TreeListCtrl.DeleteAllItems Not Clearing On First Attempt

### ISSUE THREAD

**Issue by swprojects** [wxWidgets/Phoenix#704]
**Operating system**: windows 10 64bit MSW
**wxPython version**: '4.0.0rc1.dev3617+346e3b7'
**Stock or custom build**: stock
**Python version**: 3.5.3
**Stock or custom build**: stock

**Description of the problem**:
Possibly related to https://github.com/wxWidgets/Phoenix/issues/679 but i'm not sure as I haven't tested on GTK/Linux.

I installed latest snapshot of Phoenix. '4.0.0rc1.dev3617'.

The example below is an example of a TreeListCtrl with a respective Clear and Populate buttons.

When the tree contains items, it needs to be cleared twice, before you can re-add to the list.

Otherwise it will crash

![2018-01-23 19_24_19-4 0 0rc1 dev3617 346e3b7](https://user-images.githubusercontent.com/10121727/35296153-0ed85ed0-0073-11e8-9328-ef467f8e616a.png)

For example:

clear, clear, populate will not crash

but 

clear, populate **will** crash

```python
import wx
import wx.dataview
 
class Main(wx.Frame):
    
    def __init__(self):
        wx.Frame.__init__(self, None)
        
        self.SetTitle(wx.__version__)
        panel = wx.Panel(self)   
        sizer = wx.BoxSizer(wx.VERTICAL)
        
        hsizer = wx.BoxSizer(wx.HORIZONTAL)
        self.tree1 = wx.dataview.TreeListCtrl(panel)
        self.tree1.AppendColumn("column")
        hsizer.Add(self.tree1, 1, wx.ALL|wx.EXPAND, 10)
        
        for x in range(50):
            item = self.tree1.AppendItem(self.tree1.GetRootItem(), str(x))
            
        btn = wx.Button(panel, label="Clear List")    
        btn.Bind(wx.EVT_BUTTON, self.OnButton1)
        hsizer.Add(btn, 1, wx.ALL|wx.EXPAND, 10)  
        
        btn = wx.Button(panel, label="Populate List")    
        btn.Bind(wx.EVT_BUTTON, self.OnButton2)
        hsizer.Add(btn, 1, wx.ALL|wx.EXPAND, 10)  
        sizer.Add(hsizer, 1, wx.ALL|wx.EXPAND, 10)  
        
        panel.SetSizer(sizer)
        self.SetSize((500,400))
        self.Show()
        self.Centre() 
        
    def OnButton1(self, event):
        self.tree1.DeleteAllItems()
        
    def OnButton2(self, event):    
        for x in range(50):
            item = self.tree1.AppendItem(self.tree1.GetRootItem(), str(x))
        
if __name__ == "__main__":
    app = wx.App()
    Main()
    app.MainLoop()
```

**Comment by RobinD42** [comment]
Looks like it is related, although not quite the same since different dataview classes are involved. Reverting that wxWidgets change fixes this problem, so you should reopen that ticket and let Vadim know about the problem. An easy change would be to call Cleared()  at the beginning of the method only for GTK and at the end for the others, but he may have a better idea.

**Comment by RobinD42** [comment]
Actually, since I originally opened that one I'll reopen it.

**Comment by RobinD42** [comment]
Also, I found that while running in the debugger the crash could happen at different points, so a clear-clear-populate isn't as much of a clue as one would hope. It was probably just a case of the trash happening to be in the right place so as to not harm future operations.

**Comment by RobinD42** [comment]
See https://github.com/wxWidgets/wxWidgets/pull/683

**Comment by swprojects** [comment]
Thanks will follow the ticket and pr now.

**Comment by RobinD42** [comment]
I'll leave this open for now, so I don't forget to update the wxWidgets changeset pointer in our submodule.
