### ISSUE TITLE
Access violation:Faulting module name: wxmsw30u_core_vc90.dll, version: 3.0.4.0, 

### ISSUE THREAD

**Issue by algahsimou** [wxWidgets/Phoenix#711]
**Operating system**: windows 10
**wxPython version**: 2.7
**Stock or custom build**: Python 2.7.13 |Enthought, Inc. (x86)| (default, Mar  2 2017, 16:00:27) [MSC v.1500 32 bit (Intel)] on win32
**Python version**:
**Stock or custom build**:

**Description of the problem**: Getting access violation on windows 10, application works fine on windows 7
Faulting application name: EXCEL.EXE, version: 14.0.7192.5000, time stamp: 0x5a347152
Faulting module name: wxmsw30u_core_vc90.dll, version: 3.0.4.0, time stamp: 0x59bda1ae
Exception code: 0xc0000005
Fault offset: 0x00080a3b
Faulting process id: 0x30f8
Faulting application start time: 0x01d39864ba681f7d

```python
# Put code sample here
```

**Comment by algahsimou** [comment]
Application is a python/excel integration that works on windows 7 but fails on windows 10. Just wondering if anyone run into this issue perhaps dll needs to be recompiled?

**Comment by infinity77** [comment]
@swt2c @algahsimou Python 2.7 is dead - not to mention that there is zero information in this bug report on how to reproduce the problem.

Is this still relevant?
