### ISSUE TITLE
wx Translate Problem

### ISSUE THREAD

**Issue by wekay102200** [wxWidgets/Phoenix#712]
**Operating system**:
windows7
**wxPython version**:
3.0.2
**Stock or custom build**:
**Python version**:
2.7
**Stock or custom build**:

**Description of the problem**:
when translate application to chinese language,and open a mdi document,it occur problem below:
  File "c:\python27\lib\site-packages\wx-3.0-msw\wx\lib\pydocview.py", line 1050, in ProcessUpdateUIEvent
    return DocMDIParentFrameMixIn.ProcessUpdateUIEvent(self, event)
  File "c:\python27\lib\site-packages\wx-3.0-msw\wx\lib\pydocview.py", line 374, in ProcessUpdateUIEvent
    return wx.GetApp().ProcessUpdateUIEvent(event)
  File "c:\python27\lib\site-packages\wx-3.0-msw\wx\lib\pydocview.py", line 1840, in ProcessUpdateUIEvent
    if service.ProcessUpdateUIEvent(event):
  File "c:\python27\lib\site-packages\wx-3.0-msw\wx\lib\pydocview.py", line 2973, in ProcessUpdateUIEvent
    self.BuildWindowMenu(event.GetEventObject())  # build file list only when we are updating the windows menu
  File "c:\python27\lib\site-packages\wx-3.0-msw\wx\lib\pydocview.py", line 3015, in BuildWindowMenu
    windowMenu = currentFrame.GetMenuBar().GetMenu(windowMenuIndex)
  File "c:\python27\lib\site-packages\wx-3.0-msw\wx\_core.py", line 12282, in GetMenu
    return _core_.MenuBar_GetMenu(*args, **kwargs)
ValueError: in method 'MenuBar_GetMenu', expected argument 2 of type 'size_t'

```python
# Put code sample here
        locale = wx.Locale(wx.LANGUAGE_DEFAULT)
        if locale.IsOk():
            locale.AddCatalogLookupPathPrefix('locale')
            ibRet = locale.AddCatalog('zh_CN')
            print ibRet

```

**Comment by wekay102200** [comment]
How to avoid this problem?

**Comment by RobinD42** [comment]
```python
        windowMenuIndex = currentFrame.GetMenuBar().FindMenu(_("&Window"))
        windowMenu = currentFrame.GetMenuBar().GetMenu(windowMenuIndex)
```

It looks like `windowMenuIdex` is probably being set to `wx.NOT_FOUND` which means it was not able to find a menu in the menubar with the label of whatever `"&Window"` is translated to. I'll add an assertion there to make it more clear what is wrong, but I'm not sure why the menu would not have been added, it may have something to do with your use of the module.

**Comment by wekay102200** [comment]
Hi,I found the _("&Window") does not translate into Chinese，But the main window menu has been translated. @RobinD42

**Comment by wekay102200** [comment]
The main windows menu has been translated ,but  the _("&Window") in pydocview does not translate into Chinese .so windowMenuIndex = currentFrame.GetMenuBar().FindMenu(_("&Window")) the windowMenuIndex is -1. @RobinD42

**Comment by wekay102200** [comment]
@RobinD42 Hi,I suppose I know the reason.
All the translation was loaded when the application start up.
The translation after  application start up will not be tranlated.
so the ("&Window") in pydocview will not be translated into local lanauge(here is chinese)
wx.GetTranslation method is not dynamic,when call after application start up ,it's not wokable,and return the raw text.
Does What i say is correct?
