### ISSUE TITLE
i_wxPyCheckForApp should check for wxAppConsole::GetInstance()

### ISSUE THREAD

**Issue by RobinD42** [wxWidgets/Phoenix#720]
**Operating system**: any
**wxPython version**: any
**Stock or custom build**: any
**Python version**: any
**Stock or custom build**: any

**Description of the problem**:

See https://groups.google.com/d/msg/wxpython-users/-toyOZZ-2ms/akyCN-9nAwAJ

"""
There are other problems i_wxPyCheckForApp should check for wxAppConsole::GetInstance() being non-null, not wxTheApp. This is because the python interpreter might embedded in an application with its own wxApp.
"""

**Comment by mesalu** [comment]
Fixed by #724, and will be available in 4.0.1 and on.
