### ISSUE TITLE
wx_compat issue:  ToolBar.AddTool(): arguments did not match any overloaded call

### ISSUE THREAD

**Issue by italian-buzz** [wxWidgets/Phoenix#722]
**Operating system**:  Windows 10
**wxPython version**:  4.0.0
**Stock or custom build**:  Stock build
**Python version**: 3.6 
**Stock or custom build**: stock build

**Description of the problem**:

I got this error when running a program that worked on the previous beta version of wxPython

  File "C:\Python36-32\lib\site-packages\matplotlib\backends\wx_compat.py", line 174, in _AddTool
    return add_tool(wx_ids[text], **kwargs)
TypeError: ToolBar.AddTool(): arguments did not match any overloaded call:
  overload 1: argument 1 has unexpected type 'int'
  overload 2: 'bmpDisabled' is not a valid keyword argument
  overload 3: 'shortHelpString' is not a valid keyword argument
OnInit returned false, exiting...

```python

If I modify the code in wx_compat.py like this, it works fine.  I think the problem is in the version comparison.

    # if not is_phoenix or LooseVersion(wx.VERSION_STRING) >= str("4.0.0b2"):
    #     # NOTE: when support for Phoenix prior to 4.0.0b2 is dropped then
    #     # all that is needed is this clause, and the if and else clause can
    #     # be removed.
    kwargs = dict(label=text,
                  bitmap=bmp,
                  bmpDisabled=wx.NullBitmap,
                  shortHelp=text,
                  longHelp=tooltip_text,
                  kind=kind)
    # else:
    #     kwargs = dict(label=text,
    #                   bitmap=bmp,
    #                   bmpDisabled=wx.NullBitmap,
    #                   shortHelpString=text,
    #                   longHelpString=tooltip_text,
    #                   kind=kind)
```

**Comment by mesalu** [comment]
#475 
#527

**Comment by mesalu** [comment]
Basically, the same py-method with different input had different keywords, in some cases (short/long)HelpString and in others (short/long)Help. #478 fixed this by changing everything to just '(short/long)Help' 
Moving forward calls to AddTool should just use (short/long)Help

**Comment by mesalu** [comment]
```python
>>> from distutils.version import LooseVersion
>>> LooseVersion(wx.VERSION_STRING)
LooseVersion ('4.0.0')
>>> LooseVersion(wx.VERSION_STRING) >= "4.0.0b2"
False
>>>
```

@RobinD42 Thoughts? Rev'ing to 4.0.1 seems like the quick-fix... but also... just wrong.

**Comment by HelioGuilherme66** [comment]
In our project [RIDE](https://github.com/HelioGuilherme66/RIDE), we use:
```
>>> from pkg_resources import parse_version
>>> 
>>> 
>>> def cmp_versions(version1, version2):
...     if version1 is None:
...         if version2 is None:
...             return 0
...         else:
...             return -1
...     if version2 is None:
...         return 1
...     if parse_version(version1) == parse_version(version2):
...         return 0
...     elif parse_version(version1) > parse_version(version2):
...         return 1
...     return -1
... 
>>> import wx
>>> cmp_versions(wx.VERSION_STRING, "4.0.0b2")
1
```

**Comment by mesalu** [comment]
That looks like a good solution to me. 
A quick note is that it still isn't _entirely_  PEP440 compliant as it doesn't recognize 'X.Y.Z.postN' as newer than 'X.Y.Z', but that's pretty darn nit-picky.  It does consider 'X.Y.ZpN' as newer.

**Comment by mesalu** [comment]
Looks like matplotlib is ahead of us.
https://github.com/matplotlib/matplotlib/pull/10362

**Comment by mesalu** [comment]
For the sake of maintaining pedantic-ness I'll point out that `StrictVersion` still doesn't adhere to PEP440 fully. :)
