### ISSUE TITLE
Ubuntu 16.04 - wxPython 4.0 Unable to use after following the docs(core dump)

### ISSUE THREAD

**Issue by iongion** [wxWidgets/Phoenix#725]
**Operating system**: Ubuntu 16.04
**wxPython version**: 4.0
**Stock or custom build**: stock
**Python version**:  2.7.12
**Stock or custom build**: stock

**Description of the problem**:

After installing using this https://www.wxpython.org/pages/downloads:

```
pip install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-16.04  --user  wxPython
```

Install completes successfuly, then I try to run a test program:
```
python2.7 main.py
Segmentation fault (core dumped)
istoica@istoica-u1604h:source-arbre$ 
```

Where main.py is:
```
#!/usr/bin/python
import os, sys
# vendors
import wx

app = wx.App(redirect=True)
top = wx.Frame(None, title="Hello World", size=(300,200))
top.Show()
app.MainLoop()
```

And then, when I try to run with ```python main.py```, I get:
```
python Wizard.py 
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609]
wx.version: 4.0.0 gtk3 (phoenix)
Segmentation fault (core dumped)
```

What can be done ?

**Comment by RobinD42** [comment]
There is a new build on the way that fixes this and a couple other things. See #648
