### ISSUE TITLE
Question: About Release Code Names

### ISSUE THREAD

**Issue by Metallicow** [wxWidgets/Phoenix#728]
I just noticed "Lemonade" after the version number in the changes.

Are these supposed to be project code names given to releases, and if so is there some sort of rhyme or reason to the ones given.

Example: Google gives android some sort of sweet candy or dessert and Ubuntu uses an adjective and an animal with the same first letter (e.g. Dapper Drake)

I recall some projects always looked at these things as when are you gonna run outta names. I think one person got a laugh outta one idea. Ex: name each release after a character in toy story.

Thoughts?

**Comment by mesalu** [comment]
I'm not sure if there's rhyme or reason...

Historically @RobinD42 is pretty damn good at picking random arbitrary names.

**Comment by mesalu** [comment]
Ah:
> "When life gives you lemons..."

**Comment by Metallicow** [comment]
Ok, not sure where the quote came from but I used github's search repository box for 'lemon' and I get LEMON CHIFFON... mmmmm yum

... but it didn't catch the lemon in lemonade...

**Comment by RobinD42** [comment]
No rhyme nor reason, just whatever pops into my head as I'm typing the release date in the CHANGES file.

This time around I was a little torqued at myself for letting some serious bugs slip through Nasty, tart, sour bugs. Like lemons. The full quote is "When life gives you lemons, make lemonade." So I made lemonade and called it wxPython 4.0.1.
