### ISSUE TITLE
font point size 70, creates font with size of 9

### ISSUE THREAD

**Issue by kg-2** [wxWidgets/Phoenix#733]
**Operating system**: windows 10
**wxPython version**: '4.0.0rc1.dev3635+bcb3444 msw (phoenix)'
**Stock or custom build**:
**Python version**: 3.6.2
**Stock or custom build**: stock

**Description of the problem**:
When I try to make a font with a point size of 70, it creates a font with a point size of 9

```python
import wx

fonts = ["Tempus Sans ITC", "Times New Roman"]

app = wx.App()
for face in fonts:
    print(f"testing font: {face}")
    for size in range(5, 100):
        font = wx.Font(size, 74, 90, 90, False, face)
        if font.GetPointSize() != size:
            print(f"font size mismatch, face: {face} requested size: {size} actual size: {font.GetPointSize()}")


input("done")
```

which gives me:

```
testing font: Tempus Sans ITC
font size mismatch, face: Tempus Sans ITC requested size: 70 actual size: 9
testing font: Times New Roman
font size mismatch, face: Times New Roman requested size: 70 actual size: 9
done
```

**Comment by RobinD42** [comment]
http://trac.wxwidgets.org/ticket/12315

This is due to some ancient history in wxWidgets with the `wxDEFAULT` constant being set to a value of 70. Due to the huge amount of existing code it can't be changed to something that makes more sense without causing lots of trouble, but you can set a point size of 70 with `SetPointSize` as a workaround.

**Comment by kg-2** [comment]
can you have it raise an error or warning? This was a frustrating bug to track down

**Comment by RobinD42** [comment]
Probably not. That would block the feature of being able to select a default size for a default font. It looks like the docs have been updated on the wxWidgets master to include a note about the flag and a point size of 70.
