### ISSUE TITLE
No icon on wx.MessageDialog

### ISSUE THREAD

**Issue by FreeHarry** [wxWidgets/Phoenix#735]
**Operating system**: Fedora 27 (64 bit) with KDE Plasma 5
**wxPython version**: 4.0.1 gtk3 (phoenix)
**Stock or custom build**:
**Python version**: Python 3.6.4 (64bit)
**Stock or custom build**:

**Description of the problem**:
When I start the wxPython demo.py and run the wx.MessageDialog the dialog shows no icon (see image). On my windows system all runs well. My questions: Is that an bug or my fault?

![screenshot_20180207_165123](https://user-images.githubusercontent.com/24735031/35927264-90338dfc-0c2a-11e8-85d3-b21a81d0ecdb.png)

**Comment by RobinD42** [comment]
`wx.MessageDialog` uses the native GTK dialog for its implementation, and so I would guess that whether to show the icon or not is being managed by GTK or GNOME. There may be a global configuration available for this, similar to the option for displaying icons on menu items, etc.

**Comment by Nutznieser** [comment]
Ok, I guessed also this is a configuration problem on my system. But I searched all my settings and didn't found anything that solves the problem, so I wanted to exclude the possibility to have an bug in wxPython.  ... I will search further to find the proper setting. Thanks!

**Comment by Nutznieser** [comment]
Thanks Robin for the info!

The last days I did investigating very intensive how I can configure my linux fedora system to show the icons on wx.MessageDialog. But I couldn't find the right setting. Later I looked a little deeper into the wxPython documentation and found the following hint below the [MessageDialog Overview](https://docs.wxpython.org/common_dialogs_overview.html#messagedialog-overview):

> This dialog shows a message, plus buttons that can be chosen from OK, Cancel, Yes, and No. Under Windows, an optional icon can be shown, such as an exclamation mark or question mark.

Does that mean that on linux/macOS no Icon is shown near the message text?

**Comment by RobinD42** [comment]
No, that text is probably very old the implication doesn't match with current behavior. Each of the platforms is a little different though, as you've seen, and doesn't completely match with MSW. On OSX the icon will be default be the application's main icon. On Linux it is definitely a distro/system/DE/GTK/theme/something-specific preference somewhere, and the gtk api is just following that. 

Here it is on my Ubuntu-16.04 VM for example:

![snap001](https://user-images.githubusercontent.com/808502/36186497-4110d030-10f4-11e8-8e73-21672515e889.png)

**Comment by infinity77** [comment]
@swt2c : I’m not sure this is a wxPython/wxWidgets issue - @RobinD42 ‘s answer is pretty conclusive to me
