### ISSUE TITLE
Why wx.dataview.DataViewListCtrl has no method GetItemCount?

### ISSUE THREAD

**Issue by noval102200** [wxWidgets/Phoenix#736]
**Operating system**:
windows7
**wxPython version**:
3.0.2
**Stock or custom build**:
**Python version**:
2.7
**Stock or custom build**:

**Description of the problem**:
when I use wx.dataview.DataViewListCtrl cand call it's method GetItemCount to know the item count of control.but it report error below:
Traceback (most recent call last):
  File "D:\env\Noval\noval\tool\DebuggerService.py", line 2395, in OnCombo
    dlg = InterpreterConfigDialog.InterpreterConfigDialog(wx.GetApp().GetTopWindow(),-1,_("Configure Interpreter"))
  File "D:\env\Noval\noval\tool\InterpreterConfigDialog.py", line 148, in __init__
    self.ScanAllInterpreters()
  File "D:\env\Noval\noval\tool\InterpreterConfigDialog.py", line 280, in ScanAllInterpreters
    self.AddOneInterpreter(interpreter)
  File "D:\env\Noval\noval\tool\InterpreterConfigDialog.py", line 217, in AddOneInterpreter
    self.dvlc.GetItemCount()
AttributeError: 'DataViewListCtrl' object has no attribute 'GetItemCount'

but i see the offcial document say wx.dataview.DataViewListCtrl should have method GetItemCount.
attch is screenshot.

How can i know the item count of  wx.dataview.DataViewListCtrl?

```python
# Put code sample here
self.dvlc = dataview.DataViewListCtrl(self)
self.dvlc.GetItemCount()
```

**Comment by noval102200** [comment]
https://www.wxpython.org/Phoenix/docs/html/wx.dataview.DataViewListCtrl.html#wx.dataview.DataViewListCtrl.GetItemCount

**Comment by RobinD42** [comment]
The docs are for 4.0.1, you are using 3.0.2. The method does exist in wxPython 4.

**Comment by mesalu** [comment]
If you can, you should update to 4.0.0. Classic is being phased out and I'm honestly not sure if much more support will be given to it.
There are migration tips here: https://wxpython.org/Phoenix/docs/html/MigrationGuide.html
You can install wxPython 4.0.0 directly from pip! There are some caveats for Linux distributions. Please refer to this document for those: https://wxpython.org/blog/2017-08-17-builds-for-linux-with-pip/index.html
If are using linux, and its a more standard distribution you can probably find a prebuilt wheel here:
https://extras.wxpython.org/wxPython4/extras/linux/

**Comment by wekay102200** [comment]
@RobinD42 @mesalu .Yes,I have try wxPython4.0.0. But it generate a lot of run error.
such as class or property is not exist problem.
so I return to wx 3.0.2
