### ISSUE TITLE
wx.html2.EVT_WEBVIEW_NAVIGATING is not called in Ubuntu 16.04

### ISSUE THREAD

**Issue by Jenyay** [wxWidgets/Phoenix#741]
**Operating system**: Ubuntu 16.04
**wxPython version**: 4.0.1
**Stock or custom build**: from PyPi
**Python version**: Python 3.5
**Stock or custom build**: stock

In Ubuntu 16.04 with Python 3.5 wx.html2.EVT_WEBVIEW_NAVIGATING is not called when clicking on a link in the loaded with wx.html2.WebView class HTML file. 

In Ubuntu 17.10 with Python 3.6 the event work fine.

**Comment by swt2c** [comment]
This is *probably* a wx issue.  In each case, are you using WebKit1 or WebKit2?

**Comment by Jenyay** [comment]
WebKit2.

**Comment by Jenyay** [comment]
The problem turned out to be more interesting than I thought at first.

With WebKit1 the EVT_WEBVIEW_NAVIGATING event work fine, but with WebKit2 the event is not called. It turns out that in Ubuntu 17.10 I did **not** have the libwebkit2gtk -...- dev library installed (and everything worked perfectly).

In Ubuntu 16.04 I have libwebkitgtk-3.0-dev and libwebkit2gtk-4.0-dev and the EVT_WEBVIEW_NAVIGATING event is not called.

The proble with WebKit2, but not WebKit1.

**Comment by swt2c** [comment]
That's good news.  I have some ideas about what the problem is (in wxWidgets).

**Comment by swt2c** [comment]
This was fixed upstream by b4bcb8e4483ffb67d336021c40e2d9455082e97e while fixing a different bug.  If/when Robin does another 4.0.x release and updates the wx commit, this should be fixed.

**Comment by Jenyay** [comment]
Thank you, I will wait for the next version.

**Comment by mesalu** [comment]
The wxWidgets reference has been updated to include @swt2c's changes now. The next formal release from the 4.0.X branch will include the change.

**Comment by Jenyay** [comment]
I saw one more problem. EVT_WEBVIEW_NAVIGATING is not called if on the loaded HTML page to click on the relative link or a link with file:// protocol. 

Python 3.5. Ubuntu 16.04. wxPython 4.0.3.

**Comment by swt2c** [comment]
@Jenyay probably open a new issue, since this one is closed.

**Comment by Jenyay** [comment]
If the message is not noticed here, then I will create a new issue.

**Comment by swt2c** [comment]
Well, I'm probably the one who would do something about it, so technically I've noticed it but I'll probably forget.  ;-)
