### ISSUE TITLE
ClientDC not working on Wayland

### ISSUE THREAD

**Issue by DietmarSchwertberger** [wxWidgets/Phoenix#743]
**Operating system**: Ubuntu 17.10
**wxPython version**: 4.0.1
**Stock or custom build**: Stock
**Python version**: 3.6.3
**Stock or custom build**: Stock

**Description of the problem**: When using ClientDC, the screen content is not updated. It will only update with a large delay or on resizing etc.
As workaround, an additional `Refresh()` solves the problem.
Switching from Wayland to X also solves the problem.

The oxboxes Ubuntu 17.10 VM is fine for reproducing the issue.

For verification, try the `ScrolledWindow.py` demo with `BUFFERED = False`.
On Python 2.7 / wxPython 3.0.2 (gtk3.0) everything works fine.
On Python 3.6 / wxPython 4.0.1, when drawing with the mouse, the screen is not updated before it is resized.

This was reported on wxpython-dev by Riccardo Borgani who has problems with the Matplotlib WxAgg backend: https://groups.google.com/d/msg/wxpython-dev/8E4jtTjEmjI/5H3CboaNAAAJ

When trying with Python 2.7 and wxPython 3.0.2 (gtk3.0) his example worked as expected.

**Comment by swt2c** [comment]
I think this is a wxWidgets issue, probably something that regressed from wx3.0.2 to wx3.0.3, as I can reproduce with wxPython Classic, built against (unbundled) wx 3.0.3.

**Comment by DietmarSchwertberger** [comment]
Maybe, but as Classic 3.0.2 is working, this one seems to be a bug and not a problem in principle.
The situation is the same with Overlays. They are working with Classic 3.0.2 but not with 4.0.1.

I have no example for `SetLogicalFunction` at hand to try. That one also fails on OS X.

**Comment by DietmarSchwertberger** [comment]
Update about lib/mixins/rubberband.py:
Classic: working on X11 and Wayland
Phoenix on X11: redraw errors
Phoenix on Wayland: not working at all

**Comment by DietmarSchwertberger** [comment]
About the Overlays and the `SetLogicalFunction`: maybe they are working, but just not displayed. I did not try with a normal `PaintDC`.

**Comment by DietmarSchwertberger** [comment]
@swt2c : Would you have the possibility to do a bisection between 3.0.2 and 3.0.3 to identify the commit that broke ClientDC?

**Comment by swt2c** [comment]
Yes, I will try to do that.

**Comment by wsyzxcn** [comment]
I have the same issue on osx, ClientDC never shows while PaintDC works,. Python 3.6 / wxPython 4.0.1, macOS High Sierra

**Comment by DietmarSchwertberger** [comment]
@wsyzxcn : Are you just trying to re-paint or do you want to use `DCOverlay` or `SetLogicalFunction`? The latter are not working on Mac OS also with 3.0, but I thought I had successfully tested `ClientDC` with 'normal' drawing functions like `DrawRectangle` or `DrawBitmap` with Phoenix.

**Comment by wsyzxcn** [comment]
The problem seems to be I use ClientDC to paint before MainLoop() is called. If i call it after MainLoop() is called, either delay the drawing with  wx.CallLater   or invoke it with click event, it works fine. Note that windows don't have this issue.

**Comment by DietmarSchwertberger** [comment]
@swt2c : Do you think that you will find the time do to a bisection? Otherwise I would need to try to set up an environment to build on my Ubuntu VM. I have never tried this and never tried to build a wxPython version with non-standard wxWidgets version...
It would really be great to have this fixed. Otherwise, a re-write of the Matplotlib wx backend needs to be started.

**Comment by swt2c** [comment]
I started to do it but then I ran into some problem, I can't remember what.  :-)  I think maybe I had problems reproducing the problem in the first place.  So feel free to give it a try.

**Comment by DietmarSchwertberger** [comment]
I never did this before. Did you build wxWidgets separately or from within wxPython? Do you know which commit for x3.0.3 you did use?

**Comment by swt2c** [comment]
When I reported that I saw the problem with wxWidgets 3.0.3 + wxPython 3.0.2.0, I was probably using the Fedora packages.

You can build wxWidgets separately.  Just point your LD_LIBRARY_PATH to the directory where the built wxWidgets libraries are written, and run wxPython.

**Comment by DietmarSchwertberger** [comment]
There are so many branches and tags in the wxWidgets repository that I would not know where to start and end with a reasonable chance that the wx library would work with wxPython. If I have two commits working/non-working and a linear history inbetween, then I would give it a try. Otherwise, it's probably pointless.

**Comment by DietmarSchwertberger** [comment]
I've now built wxPython from the 3.0.2 source archive.
It seems that the root cause is not a change in wxWidgets but caused by gtk2 vs. gtk3.
When I build with `--gtk3` then `ClientDC` does not work. A gtk2 build works fine.

My info in the first post was wrong. I had the impression that the working python-wxgtk3.0 was gtk3, but it's actually gtk2 based.

On trac there's a related ticket: https://trac.wxwidgets.org/ticket/17820

**Comment by swt2c** [comment]
That ticket is about Wayland, though, not GTK+ 2 vs GTK+ 3.  Are you sure you're using Wayland?  Does the problem go away if you set GDK_BACKEND=x11 and then run your test?

**Comment by DietmarSchwertberger** [comment]
Yes, as the original problem is under Wayland: "Switching from Wayland to X also solves the problem."
Both the gtk2 and gtk3 builds work fine under X but only the gtk2 build is OK under Wayland.

**Comment by swt2c** [comment]
OK.  GTK+ 2 doesn't support Wayland natively, so it will always run under X, so that's why it works.

**Comment by DietmarSchwertberger** [comment]
So wxWidgets with GTK3 does not support ClientDC at all? Shouldn't that be stated somewhere or trigger a warning?

**Comment by swt2c** [comment]
Sorry, I guess I was confused by your original post where you said wxPython Classic + gtk3 worked.

No, wxWidgets with GTK3 does support ClientDC, but only with X.  So, it seems this is really a wxWidgets + Wayland issue rather than a regression.  I guess the only thing to do would be to try to convince one of the wx devs to look into this further.  It is beyond my knowledge at this point.
