### ISSUE TITLE
ThumbnailCtrl

### ISSUE THREAD

**Issue by FelipeCalliari** [wxWidgets/Phoenix#746]
**Operating system**: Windows 10 x64 Build 1709
**wxPython version**: 4.0.1
**Stock or custom build**: Stock build
**Python version**: 3.6.4
**Stock or custom build**: Stock build

**Description of the problem**: While running the [wxPython-demo-4.0.1.tar.gz](https://extras.wxpython.org/wxPython4/extras/4.01/wxPython-demo-4.0.1.tar.gz), I tried the ``ThumbnailCtrl`` object and received the following error:

```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\wx\lib\agw\thumbnailctrl.py", line 2242, in OnMouseDown
    self.ScrollToSelected()
  File "C:\ProgramData\Anaconda3\lib\site-packages\wx\lib\agw\thumbnailctrl.py", line 1950, in ScrollToSelected
    y1 = row*(self._tHeight + self._tBorder) + self.GetCaptionHeight(0, row)
  File "C:\ProgramData\Anaconda3\lib\site-packages\wx\lib\agw\thumbnailctrl.py", line 1778, in GetCaptionHeight
    for ii in range(begRow, begRow + count):
TypeError: 'float' object cannot be interpreted as an integer
```

In Python 2, when we divide 2 integers the result is a integer, ie, ``int/int = int``, but in Python 3 the result is a float, ie, ``int/int = float``.

So, I was able to make this module (``wx/lib/agw/thumbnailctrl.py``) work by modifying the following lines:

```python
1785 =    def GetItemIndex(self, x, y):
1793 -        col = (x - self._tBorder)/(self._tWidth + self._tBorder)
1793 +        col = (x - self._tBorder)//(self._tWidth + self._tBorder)

1938 =    def ScrollToSelected(self):
1945 -        row = self.GetSelection()/self._cols
1945 +        row = self.GetSelection()//self._cols
```

**Comment by Metallicow** [comment]
Yeah there are bound to be some floor division lines that might pop up still when running on Py3.
You can go ahead and make a pull request.
