### ISSUE TITLE
Build Python2 and Python3 modules in same dir -> Py2 extensions get installed for Py3

### ISSUE THREAD

**Issue by swt2c** [wxWidgets/Phoenix#75]
Is building Py2 and Py3 modules in the same directory supposed to work?

When I do so, I end up with the Py2 modules getting installed into the Py3 directory (in addition to the Py3 modules):

```
[talbert@easel wxPython_Phoenix-3.0.3.dev1976+d9956d6]$ find . -name _core*.so
./wx/_core.cpython-34m.so
./wx/_core.so
./build/waf/2.7/_core.so
./build/waf/3.4/_core.cpython-34m.so
./build/lib.linux-x86_64-3.4/wx/_core.cpython-34m.so
./build/lib.linux-x86_64-3.4/wx/_core.so
./build/lib.linux-x86_64-2.7/wx/_core.so
```

I think this is because the .so's get copied from build/waf/<pyversion>/ to wx/ and then wx/* gets bulk copied to the install dir.  I can't for the life of me see where in the code this is happening, though.

**Comment by swt2c** [comment]
OK, I see where it is now... `copyFileToPkg` in `wscript` copies from build/waf/x/ to wx/.  Then I assume distutils is doing a bulk copy from wx/* to the install dir.

**Comment by swt2c** [comment]
Probably low priority if this is even supposed to work.

**Comment by RobinD42** [comment]
It's not intended to work for making installations or distributions, I assumed that it would start with a clean build dir for those tasks.  It is nice for development mode however, where you can build and test for different versions of python without wiping and rebuilding when switching between them.

**Comment by swt2c** [comment]
Indeed.  That's what I'm doing now, thanks.
