### ISSUE TITLE
Source Build: Limit Parallelism

### ISSUE THREAD

**Issue by ax3l** [wxWidgets/Phoenix#750]
**Operating system**: Linux (Travis-CI)
**wxPython version**: 4.0.1
**Stock or custom build**:
**Python version**: 3.6
**Stock or custom build**:

**Description of the problem**:

I have read the notes on the Linux wheels and would like to build from source with `pip install wxpython` on Linux.

That works well on my machine, but on cloud computers such as Travis-CI it automatically builds with `make --jobs=32`. This is bad, since the maximum supported softlimit on Travis is `make -j 2` (it just has 32 "physical cores" but those are not *mine* to use).

Can you please add a simple option we can pass through `pip install wxpython --install-option=""` so that we can limit the parallelism? Or maybe just an environment var that can overwrite the default of `num_cpus()` for `-j`?

Thx for considering and congrats on 4.0.1!

**Comment by RobinD42** [comment]
You can set parameters to be used by `build.py` (which is called from `setup.py` when building with pip) by setting `WXPYTHON_BUILD_ARGS` in the environment. So setting `WXPYTHON_BUILD_ARGS="--jobs=2"` should work.

Alternatively, I believe others just have pip fetch the pre-built wheels from https://extras.wxpython.org/wxPython4/extras/linux/ and use those in their TravisCI builds. That would save you a significant amount of build time if that option fits your needs.

**Comment by ax3l** [comment]
Thank you for the detailed answers, that's exactly what I was looking for!

Both the env variable for passing options through to `build.py` and the pre-build linux wheels are really helpful. On travis, I can directly use the ubuntu 14.04 wheels for downstream tests - great! `WXPYTHON_BUILD_ARGS` is very helpful for my builds from source.
