### ISSUE TITLE
import wx, output: undefined symbol: _Py_ZeroStruct

### ISSUE THREAD

**Issue by rove21** [wxWidgets/Phoenix#760]
**Operating system**: ubuntu 17.10, 4.13.0-32-generic, x86_64
**wxPython version**: 4.0.1
**Stock or custom build**: 
**Python version**: 3.6.3
**Stock or custom build**:

**Description of the problem**:
when run python cli, import wx, prompt _core.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _Py_ZeroStruct.

```python
# Put code sample here
```
>>> import wx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wei/.local/lib/python3.6/site-packages/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "/home/wei/.local/lib/python3.6/site-packages/wx/core.py", line 12, in <module>
    from ._core import *
ImportError: /home/wei/.local/lib/python3.6/site-packages/wx/_core.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _Py_ZeroStruct

**Comment by RobinD42** [comment]
Did you install the binary wheel for 16.04? Or did you build wxPython from the source (using pip or manually)?

**Comment by luwei0711** [comment]
sudo pip install wxPython

**Comment by luwei0711** [comment]
I also encountered this problem. I installed "sudo pip install wxPython" in this way“

**Comment by luwei0711** [comment]
Have you solved it?

**Comment by luwei0711** [comment]
Solved, Re-install as below. 
pip install -U  -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-16.04 wxPython
https://www.wxpython.org/pages/downloads/
