### ISSUE TITLE
EvtHandler.Bind fails to call handler when id keyword is supplied

### ISSUE THREAD

**Issue by bob-white** [wxWidgets/Phoenix#761]
**Operating system**: Windows 10
**wxPython version**: 4.0.1
**Stock or custom build**: Stock
**Python version**: 3.5.4
**Stock or custom build**: stock

**Description of the problem**:
Sometimes calling `EvtHandler.Bind` with the `id` keyword argument seems to keep the handler from ever being called. 
I say sometimes, because in parts of our code-base using the id parameter works just fine.
I've also tried `wx.NewId()` in place of `self.GetId()` that also failed to work.

```python
import wx

class TestPanel(wx.Panel):
    def __init__(self, parent):
        wx.Panel.__init__(self, parent)
        self.gauge = wx.Gauge(self, range=100, pos=(20,20), size=(100,-1))
        self.Bind(wx.EVT_IDLE, self.OnIdle, id=self.GetId())
        self.count = 1
        self.skipNext = False

    def OnIdle(self, evt):
        if self.skipNext:
            self.skipNext = False
            return
        self.skipNext = True

        print("OnIdle:", self.count)
        self.gauge.SetValue(self.count)
        self.count += 1
        if self.count >= 100:
            self.count = 1

app = wx.App(False)
frm = wx.Frame(None)
pnl = TestPanel(frm)
frm.Show()
app.MainLoop()
```

**Comment by Metallicow** [comment]
```
Welcome To PyCrust 0.9.8 - The Flakiest Python Shell
wx.stc.StyledTextCtrl VersionInfo: Scintilla 3.21
wxPython 4.0.0rc1.dev3607+c1a0a4d msw (phoenix)
Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> gWidget.Bind(event, handler, source=None, id=-1, id2=-1)
```
I'm not on Win10 but your code looks right according to docs. I've noticed not to use the id keyword with the close handlers... maybe the same issue is happening here also...
Looks like you are binding the panel, not the guage.

Is this what you wanted?
```
self.gauge.Bind(wx.EVT_IDLE, self.OnIdle)
```

**Comment by RobinD42** [comment]
The `id` or the `source` parameters to `Bind` are meant to indicate the source of the event in order to disambiguate when the same event type comes from different widgets, like when there is more than one button in a form. You can use the `id` or `source` to have different handlers for the different buttons.

In the case of `EVT_IDLE` events there really isn't a source in the same sense, so I suspect that the ID is not set in the event object. That means that if you set an id in the event binding then when the event is being processed there will never be a matching handler found. So the right thing to do is to just leave off the `id` and `source` parameter when calling `Bind` for `EVT_IDLE` handlers.

**Comment by bob-white** [comment]
I'm guessing the same would apply to things like `wx.EVT_KEY_DOWN`, as they aren't directly tied to a widget either?

**Comment by RobinD42** [comment]
Actually they are. Key events come from the widget with the keyboard focus. Likewise, mouse events come from the widget either containing or capturing the pointer.  

Additionally, those kinds of events are not command events (they're derived directly from `wx.Event`, not `wx.CommandEvent`) so the events are only sent to the target widget and do not propagate up to the parent of the widget. In practice that means that for non-command events you need to bind the handler directly to the widget, not to a parent. So something like this:

```python
self.textCtrl1.Bind(wx.EVT_KEY_DOWN, self.OnKey)
```

Not this:

```python
self.Bind(wx.EVT_KEY_DOWN, self.OnKey, self.textCtrl1)
```

There is some more explanation about this at https://wiki.wxpython.org/self.Bind_vs._self.button.Bind

**Comment by bob-white** [comment]
Awesome. Yeah that explains the behavior I was seeing then. Thanks for the pointers.
