### ISSUE TITLE
TreeListCtrl: Hard crash when deleting all items and repopulating tree

### ISSUE THREAD

**Issue by blitzmann** [wxWidgets/Phoenix#767]
**Operating system**:  Windows 10
**wxPython version**: 4.0.1
**Stock or custom build**: stock
**Python version**: 3.6
**Stock or custom build**: Stock

**Description of the problem**:

This issue started in v4.0.0. v4.0.0b2 does not exhibit this behavior.

Our project has a need to display a TreeListCtrl, and to repopulate it based on an event to display new data. It seems that if you attempt to delete all items from a tree, and regenerate it, there is a hard crash where python stops responding.

I've attempted to reproduce it in the simplest way below, while remaining as true to the implementation of our code as possible. See below. To reproduce: simply click the "Regenerate" button a few times (if it doesn't break immediately after the first time)

I know that TreeListCtrl has a bit of work done for the 4.0 release, possibly some regression? See fixes for #679, #704 for possible reasons for regression?

Additionally, there are screenshots below that may help in evaluating what is going on. It seems that `DeleteAllItems()` may not be working. The first screenshot shows a huge blank spot above the (new? old?) list items. The other screenshot shows the same issue, but this time with what seems to be corrupted data.

Also, seem the regenerate button breaks it near immediately if all the content is in view (height 1000), while if you reduce the height of the window to something like 200, you can click it a few times before it crashes (if it ever crashes). This might all be just coincidence though.

```python
import wx
from wx.dataview import TreeListCtrl


class MyForm(wx.Frame):
    list = [
        255,
        256,
        257,
        258,
        266,
        268,
        269,
        270,
        272,
        273,
        274,
        275,
        278,
        1209,
        1210,
        1213,
        1216,
        1217,
        1218,
        1220,
        1240,
        1241,
        1545,
    ]

    def __init__(self):
        wx.Frame.__init__(self, None, wx.ID_ANY, "Tutorial", size=(500,1000))

        mainSizer = wx.BoxSizer(wx.VERTICAL)

        panel = wx.Panel(self, wx.ID_ANY)

        button = wx.Button(panel, wx.ID_OK, "Regenerate")
        button.Bind(wx.EVT_BUTTON, self.generateTree)
        mainSizer.Add(button, 0, wx.ALL, 5)

        self.tree = TreeListCtrl(panel, wx.ID_ANY, style=wx.dataview.TL_DEFAULT_STYLE)
        self.tree.AppendColumn("Skill")
        self.tree.AppendColumn("Level")
        self.root = self.tree.GetRootItem()

        mainSizer.Add(self.tree, 1, wx.EXPAND | wx.ALL, 5)

        panel.SetSizer(mainSizer)
        self.generateTree()

        self.Layout()

    def generateTree(self, event=None):
        print("Generate Tree")
        root = self.root
        tree = self.tree
        tree.DeleteAllItems()

        for id in self.list:
            tree.AppendItem(root, "Group {}".format(id))

# Run the program
if __name__ == "__main__":
    app = wx.PySimpleApp()
    frame = MyForm().Show()
    app.MainLoop()
```

![test2](https://user-images.githubusercontent.com/3904767/36633442-c8b7dcaa-1963-11e8-9c0a-8b18e28ac2c3.PNG)

![treebug](https://user-images.githubusercontent.com/3904767/36633446-cb308388-1963-11e8-92b2-d27f3025f8de.PNG)

**Comment by efahl** [comment]
Windows 10.0.16299.248
Standard installers for Python 2.7.14 and 3.6.3 on the same machine.
pip install wxPython, version: 4.0.1

I can reproduce your problem in Python 3.6.3 with 1-2 clicks, but with Python 2.7.14, it works fine (did maybe 40 clicks, killed it and started over 5-6 times).  Looks like it's just the Py3 build, if that helps at all.

**Comment by swt2c** [comment]
There was also some work in wxWidgets recently related to `DeleteAllItems()` I believe, so that might be another source of problems.

**Comment by swt2c** [comment]
@vadz I think 4a981f0 needs to be reverted in WX_3_0_BRANCH to match the revert that was done in master in ad03c84 to fix the MSW part of this.

**Comment by blitzmann** [comment]
Thanks for the info guys.

@RobinD42 any time to look into this? This is preventing our application from updating to anything beyond beta2, would be nice to get an idea on what it involved.

**Comment by swt2c** [comment]
@blitzmann I'm 95% sure that reverting the commit I referenced is what needs to be done.  Hopefully vadz will get to that soon.  You could try doing that in your own build.

**Comment by blitzmann** [comment]
> You could try doing that in your own build.

@swt2c  If only I had the knowledge lol. I know nothing of the underlying framework, how to build it, how to build wxPython on top of it, etc... ;_;

**Comment by blitzmann** [comment]
Looks like @vadz reverted the offending commit, thank you! @RobinD42 will this fix be available with 4.0.2? I'm not sure how the wxPython releases sync with the wxWidget releases / fixes.

**Comment by RobinD42** [comment]
Yes. It's simply a matter of updating which git revision wxPython pulls in from wxWidgets. (And testing.)

**Comment by mlacunza** [comment]
I just test the code in Ubuntu 18.04 + Python3 + wxPython 4 (all installed from sources) and the app works fine, never crash. The code give me an error under Python 2.7:
`mario@pc:~/Escritorio$ python t.py 
Traceback (most recent call last):
  File "t.py", line 2, in <module>
    from wx.dataview import TreeListCtrl
ImportError: cannot import name TreeListCtrl`
``

**Comment by mlacunza** [comment]
mario@pc:~/Escritorio$ python
Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import wx
>>> print wx.__versio__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute '__versio__'
>>> print wx.__version__
3.0.2.0
>>>

**Comment by RobinD42** [comment]
Confirmed that this is no longer crashing.
