### ISSUE TITLE
What's the purpose of define ifDefPy and endIfDef?

### ISSUE THREAD

**Issue by noval102200** [wxWidgets/Phoenix#768]
**Operating system**:
**wxPython version**:
3.0.2
**Stock or custom build**:
**Python version**:
**Stock or custom build**:

**Description of the problem**:
Hi,master:
When I browse sample code of wxPython,I found some function was bracketed by  ifDefPy and endIfDef.
I 'm wondering the purpose of its definition.
such as:

# Bracket Python only code.  The Cross-compiler will ignore the bracketed code.
def ifDefPy(comment=False):
    pass
    
def endIfDef():
    pass

ifDefPy()
import warnings
warnings.filterwarnings("ignore", message="tmpnam is a potential security risk to your program")
def getTmpFile():
    return os.tmpnam()
endIfDef()

What's the purpose of define ifDefPy and endIfDef?

```python
# Put code sample here
```

**Comment by RobinD42** [comment]
Where did you see that?
