### ISSUE TITLE
overriden method OnCompareItems of wx.TreeCtrl not called

### ISSUE THREAD

**Issue by jensgoe** [wxWidgets/Phoenix#774]
**Operating system**: Win7
**wxPython version**:  (4, 0, 2, 'a1')
**Stock or custom build**: custom (official source)
**Python version**: 2.7.14
**Stock or custom build**: stock

**Description of the problem**:
If i derive from wx.TreeCtrl and override OnCompareItems it is not called after calling SortChildren.
Click the right mouse button to sort the children of an item. The output of OnCompareItem is not shown out log. The items are not sorted in numerical order like expected (implemented in OnCompareItems).

```python
import wx
print(wx.VERSION)

class MyTreeCtrl(wx.TreeCtrl):

    def __init__(self, parent):
        wx.TreeCtrl.__init__(self, parent, style=wx.TR_HAS_BUTTONS)  # | wx.TR_HIDE_ROOT)

        root = self.AddRoot("Root")
        for i in range(20):
            item = self.AppendItem(root, str(i))
            for i in range(20):
                self.AppendItem(item, str(i))

        self.Expand(root)
        self.Bind(wx.EVT_RIGHT_DOWN, self.OnRightDown)

    def OnRightDown(self, event):
        pt = event.GetPosition();
        item, flags = self.HitTest(pt)
        if item:
            print("OnRightClick")
            self.SortChildren(item)

    def OnCompareItems(self, item1, item2):
        print('OnCompareItems')
        t1 = int(self.GetItemText(item1))
        t2 = int(self.GetItemText(item2))

        if t1 < t2: return -1
        if t1 == t2: return 0
        return 1

class MyApp(wx.App):

    def OnInit(self):
        f = wx.Frame(None)
        tc = MyTreeCtrl(f)
        f.Show()
        self.SetTopWindow(f)
        return True

if __name__ == "__main__":
    app = MyApp()
    app.MainLoop()
```

**Comment by jensgoe** [comment]
i fixed this by modifying the sip generated cpp code like in the attached patch.  but i don't know how to tweak this modification within the etg scripts.
[0001-modified-generated_patch.txt](https://github.com/wxWidgets/Phoenix/files/1792713/0001-modified-generated_patch.txt)

**Comment by RobinD42** [comment]
Unfortunately there isn't a good way to inject code into that class so I think I'm going to have to be more creative...

**Comment by jensgoe** [comment]
Are you planning to merge this into the 4.0.x branch?

**Comment by RobinD42** [comment]
It already has been.
