### ISSUE TITLE
wx.FileDialog registers the parents wx.EVT_LEFT_UP event when double clicking a file.

### ISSUE THREAD

**Issue by blitzmann** [wxWidgets/Phoenix#777]
**Operating system**: Windows 10
**wxPython version**: 4.0.0b2
**Stock or custom build**: stock
**Python version**: 3.6
**Stock or custom build**: stock

**Description of the problem**:

Not sure if this is a bug, or if there's a dialog style that I should be applying... 

(from https://groups.google.com/forum/#!topic/wxpython-users/Ns87yYCOPzM)

I have a window that has a wx.EVT_LEFT_UP event. I also have a button that opens a file dialog. When the file dialog is open, and the user selects a file (by double clicking it), the up event is registered on the main window. I assume this is because the FileDialog waits for the double click down, which closes the FileDialog, but then the up action is registered wherever the mouse happens to be. What is the best way to make sure that event is suppressed, without losing regular functionality of the event on the main window?

Using wxPython v4.0.0b2, Python 3.6

```python
import wx


class MyFrame(wx.Frame):

    def __init__(self):
        wx.Frame.__init__(self, None, wx.ID_ANY, size=(600, 600))

        mainSizer = wx.BoxSizer(wx.VERTICAL)

        panel = wx.Panel(self, wx.ID_ANY)

        button = wx.Button(panel, wx.ID_OK, "Open File Dialog")
        button.Bind(wx.EVT_BUTTON, self.OpenFileDialog)
        mainSizer.Add(button, 0, wx.ALL, 5)

        panel.SetSizer(mainSizer)

        panel.Bind(wx.EVT_LEFT_DOWN, self.OnLeftDown)
        panel.Bind(wx.EVT_LEFT_UP, self.OnLeftUp)

        self.Layout()

    def OnLeftDown(self, event):
        print("Left Down")

    def OnLeftUp(self, event):
        print("Left Up")

    def OpenFileDialog(self, event=None):
        dlg = wx.FileDialog(
            self,
            "Open file",
            wildcard="XML (*.xml)|*.xml|All Files (*)|*",
            style=wx.FD_OPEN | wx.FD_FILE_MUST_EXIST | wx.FD_MULTIPLE
        )

        if dlg.ShowModal() == wx.ID_OK:
            print("File selected")

# Run the program
if __name__ == "__main__":
    app = wx.PySimpleApp()
    frame = MyFrame().Show()
    app.MainLoop()
```

**Comment by RobinD42** [comment]
This annoying issue has been around forever. I think your analysis in the email thread is on the right track. Basically the double-click in the file dialog's listview widget activates the item on the 2nd mouse-down, and that activation does the equivalent of wx's EndModal and completes the dialog. By the time that the remaining mouse-up event is processed the dialog is gone so the event is attributed to the window that is now visible which was under the dialog.

One workaround I've done in the past is to set a flag when using the dialog that the left-up handler will check and only do its thing if the flag is not set. Then after the ShowModal returns I call wx.Yield to allow that possible left-up event to be eaten, and then clear the flag.

**Comment by blitzmann** [comment]
@RobinD42 Thanks for the insight! Would you be able to provide a quick example of how you would use `wx.Yeild()`? I'm not familiar with this method and don't think I've ever really seen it used.

**Comment by michaelHL** [comment]
@blitzmann Change a little bit of your code, this should work:
```python
import wx


class MyFrame(wx.Frame):

    def __init__(self):
        wx.Frame.__init__(self, None, wx.ID_ANY, size=(600, 600))
        self.supress_left_up = False

        mainSizer = wx.BoxSizer(wx.VERTICAL)

        panel = wx.Panel(self, wx.ID_ANY)

        button = wx.Button(panel, wx.ID_OK, "Open File Dialog")
        button.Bind(wx.EVT_BUTTON, self.OpenFileDialog)
        mainSizer.Add(button, 0, wx.ALL, 5)

        panel.SetSizer(mainSizer)

        panel.Bind(wx.EVT_LEFT_DOWN, self.OnLeftDown)
        panel.Bind(wx.EVT_LEFT_UP, self.OnLeftUp)

        self.Layout()

    def OnLeftDown(self, event):
        print("Left Down")

    def OnLeftUp(self, event):
        if self.supress_left_up:
            wx.Yield()
            self.supress_left_up = False
            return
        print("Left Up")

    def OpenFileDialog(self, event=None):
        dlg = wx.FileDialog(
            self,
            "Open file",
            wildcard="XML (*.xml)|*.xml|All Files (*)|*",
            style=wx.FD_OPEN | wx.FD_FILE_MUST_EXIST | wx.FD_MULTIPLE
        )

        if dlg.ShowModal() == wx.ID_OK:
            self.supress_left_up = True
            print("File selected")

# Run the program
if __name__ == "__main__":
    app = wx.PySimpleApp()
    frame = MyFrame().Show()
    app.MainLoop()
```

**Comment by blitzmann** [comment]
@michaelHL thanks! That seems to work well, will implement in my project. 😄
