### ISSUE TITLE
wx.ListCtrl horizontal scrolling problem

### ISSUE THREAD

**Issue by Jenyay** [wxWidgets/Phoenix#786]
**Operating system**: Ubuntu 17.10
**wxPython version**: 4.0.1
**Stock or custom build**: from PyPi
**Python version**: Python 3.6
**Stock or custom build**: stock

**Description of the problem**: It seems that the horizontal scrolling parameters are incorrectly calculated  for ListCtrl with wx.LC_LIST style. In the attached example, the horizontal scroll bar can not be scrolled to the end. 

Scrolling works fine in the example if to increase window height by 10 pixels (from 150 to 160).

![listctrl_test](https://user-images.githubusercontent.com/166281/37388115-33693688-2770-11e8-9105-e2a9b3c0693a.png)
 

```python
# -*- coding: utf-8 -*-

import wx


class MyTestFrame(wx.Frame):
    def __init__(self, parent, title):
        super().__init__(parent, wx.ID_ANY, title, size=(400, 150))
        self._listCtrl = wx.ListCtrl(self, style=wx.LC_LIST)

        for n in range(20):
            self._listCtrl.InsertItem(0, 'bla-bla-bla-bla-bla')

        self.Show()


if __name__ == '__main__':
    app = wx.App()
    frame = MyTestFrame(None, 'Test')
    app.MainLoop()
```

**Comment by RobinD42** [comment]
Works correctly for me with a current 4.0.2a1 build, on Ubuntu-mate 18.04.

**Comment by Metallicow** [comment]
Sidenote... In certain widgets if you are trying to do this by something such as a keyboard shortcut, then code sometimes works other widgets don't.
Ex: Shift + Mouse Wheel

I try to have shift + mouse wheel functionality for every widget in SourceCoder, but certain widgets are still problematic.

Not sure exactly the context of 'doesn't work'. Please explain further... How you are performing the action specifically, how it responded, and what you expected it to do.

**Comment by Jenyay** [comment]
It seems that this is a problem in some GTK themes. The problem with scrolling is observed with the themes Radiance and Ambiance. With other themes, everything is fine. Most likely wxPython is not to blame.

**Comment by infinity77** [comment]
@swt2c : blame the theme, possibly can be closed
