### ISSUE TITLE
Stock labels don't conform to Windows Design Guidelines

### ISSUE THREAD

**Issue by dhowland** [wxWidgets/Phoenix#787]
**Operating system**: Windows 10
**wxPython version**: 4.0.1
**Stock or custom build**: Stock
**Python version**: 3.6
**Stock or custom build**: Stock

**Description of the problem**:

A menu item or button that opens a dialog for more information is supposed to end with "..." according to Microsoft.

Using `wx.ID_OPEN` produces "Open..." but using `wx.ID_SAVEAS` produces "Save as" which is incorrect.

See the bottom of [this page](https://msdn.microsoft.com/en-us/library/windows/desktop/dn742402(v=vs.85).aspx) for guidelines.

Note that the docs are actually correct on the "Stock Items" page, but the generated label is not.

**Comment by dhowland** [comment]
This appears to be a bug in wxWidgets in src/common/stockitem.cpp.

I don't have a login to the wxWidgets trac system, so I'll leave this here.

**Comment by dhowland** [comment]
Pull request has been issued to wxWidgets: https://github.com/wxWidgets/wxWidgets/pull/763

**Comment by RobinD42** [comment]
> Pull request has been issued to wxWidgets

Thanks. You may want to ask that it be merged into the 3.0 branch too.

**Comment by RobinD42** [comment]
I've cherry-picked the change into the WX_3_0_BRANCH and will update our submodule link.

**Comment by RobinD42** [comment]
Fixed by #879
