### ISSUE TITLE
"sudo pip install wxpython" fails due to "../../../../sip/siplib/siplib.c:5369:47: warning: format '%s' expects argument of type 'char *', but argument 3 has type 'int' [-Wformat=]                PyErr_Format(PyExc_OverflowError, "argument %s overflowed: %s"

### ISSUE THREAD

**Issue by krichter722** [wxWidgets/Phoenix#788]
**Operating system**: Ubuntu 17.10
**wxPython version**: 4.0.1
**Stock or custom build**: stock
**Python version**: 2.7.14
**Stock or custom build**: stock

**Description of the problem**:
`sudo pip install wxpython` fails due to
```
'configure' finished successfully (3.603s)
  Waf: Entering directory `/tmp/pip-build-r9kQxo/wxpython/build/waf/2.7/gtk3'
  [  1/863] c: sip/siplib/apiversions.c -> build/waf/2.7/gtk3/sip/siplib/apiversions.c.1.o
  [  2/863] c: sip/siplib/array.c -> build/waf/2.7/gtk3/sip/siplib/array.c.1.o
  [  3/863] cxx: sip/siplib/bool.cpp -> build/waf/2.7/gtk3/sip/siplib/bool.cpp.1.o
  [  4/863] c: sip/siplib/descriptors.c -> build/waf/2.7/gtk3/sip/siplib/descriptors.c.1.o
  [  5/863] c: sip/siplib/int_convertors.c -> build/waf/2.7/gtk3/sip/siplib/int_convertors.c.1.o
  [  6/863] c: sip/siplib/objmap.c -> build/waf/2.7/gtk3/sip/siplib/objmap.c.1.o
  [  7/863] c: sip/siplib/qtlib.c -> build/waf/2.7/gtk3/sip/siplib/qtlib.c.1.o
  [  8/863] c: sip/siplib/siplib.c -> build/waf/2.7/gtk3/sip/siplib/siplib.c.1.o
  [  9/863] c: sip/siplib/threads.c -> build/waf/2.7/gtk3/sip/siplib/threads.c.1.o
  [ 10/863] c: sip/siplib/voidptr.c -> build/waf/2.7/gtk3/sip/siplib/voidptr.c.1.o
  ../../../../sip/siplib/siplib.c: In function 'parsePass1':
  ../../../../sip/siplib/siplib.c:5369:47: warning: format '%s' expects argument of type 'char *', but argument 3 has type 'int' [-Wformat=]
               PyErr_Format(PyExc_OverflowError, "argument %s overflowed: %s",
                                                 ^
  ../../../../sip/siplib/siplib.c:5379:47: warning: format '%s' expects argument of type 'char *', but argument 3 has type 'int' [-Wformat=]
               PyErr_Format(PyExc_OverflowError, "argument '%s' overflowed: %s",
                                                 ^
  [ 11/863] cxx: sip/cpp/sip_core_ScrolledWindowBase.cpp -> build/waf/2.7/gtk3/sip/cpp/sip_core_ScrolledWindowBase.cpp.3.o
```

on many Debian-based OS, I provided an overview at https://gitlab.com/krichter/wxpython-pypi-install/pipelines/18724913. In case this failure occurs due to a missing prerequisite, it'd be nice if the `configure` script was improved so that it fails with a verbose, helpful error message.

**Comment by RobinD42** [comment]
Those are just warnings, not errors.

It looks to me like the builds in your gitlab failed due to not having the appropriate libwebkitgtk devel packages installed.

**Comment by krichter722** [comment]
> It looks to me like the builds in your gitlab failed due to not having the appropriate libwebkitgtk devel packages installed.

OK, I'll check that out. However, your answer makes it hard to tell whether you read and understood my complete report since you're not reacting to the necesity to improve the configure script (note that I'm not questioning that you think that it's necessary to read the list of build dependencies, I'm just suggesting to improve the build process).

**Comment by RobinD42** [comment]
The main configure script comes from wxWidgets, we just execute it from wxPython's build. You'll need to raise the issue or send PRs to them.
