### ISSUE TITLE
AttributeError: 'module' object has no attribute 'ListViewComboPopup'

### ISSUE THREAD

**Issue by swprojects** [wxWidgets/Phoenix#79]
Hi,

I'm trying to use a ComboCtrl in my application. From the docs:

http://wxpython.org/Phoenix/docs/html/ComboCtrl.html

I tried their example:

```python
comboCtrl = wx.ComboCtrl(self, wx.ID_ANY, "")

popupCtrl = wx.ListViewComboPopup()

# It is important to call SetPopupControl() as soon as possible
comboCtrl.SetPopupControl(popupCtrl)

# Populate using wx.ListView methods
popupCtrl.InsertItem(popupCtrl.GetItemCount(), "First Item")
popupCtrl.InsertItem(popupCtrl.GetItemCount(), "Second Item")
popupCtrl.InsertItem(popupCtrl.GetItemCount(), "Third Item")

```

Which raises an attribute error:
```python
AttributeError: 'module' object has no attribute 'ListViewComboPopup'
```

In the docs example, an instance of wx.ComboPopup named "ListCtrlComboPopup" is created.

Am I correct in saying, this should be passed to comboCtrl.SetPopupControl? And not wx.ListViewComboPopup(), which does not actually exist?

**Comment by swt2c** [comment]
Yes, the example is slightly wrong.  You need to create the class `ListViewComboPopup` yourself, and then pass it to `SetPopupControl`.  The example should really say:
```
popupCtrl = ListViewComboPopup()
```
not
```
popupCtrl = wx.ListViewComboPopup()
```

**Comment by swprojects** [comment]
Thanks. Have it working now.
