### ISSUE TITLE
colourchooser: use of super() not compatible with Python 2.7

### ISSUE THREAD

**Issue by DietmarSchwertberger** [wxWidgets/Phoenix#798]
**Operating system**: any / MSW
**wxPython version**: 4.0.1
**Stock or custom build**:
**Python version**: 2.7
**Stock or custom build**:

**Description of the problem**:

`wx/lib/colourchooser/pycolourchooser.py` uses `super()` without arguments. That's fine with Python 3, but not with Python 2.7.

(reported by Steve https://github.com/wxGlade/wxGlade/issues/313 )

**Comment by DietmarSchwertberger** [comment]
Thanks a lot.

**Comment by RobinD42** [comment]
Closed by #801
