### ISSUE TITLE
python crash with pandas dataframe in wxgrid

### ISSUE THREAD

**Issue by mprosperi** [wxWidgets/Phoenix#803]
**Operating system**: win10
**wxPython version**: 4.0.1 (also latest wxPython-4.0.2a1.dev3717+d4bd2fe-cp35-cp35m-win_amd64)
**Stock or custom build**: stock
**Python version**: 3.5-64bit
**Stock or custom build**: stock

**Description of the problem**: a component of my application which uses pandas dataframe shown in a grid crashes the python interpreter (it works with classic). 
To reproduce you can run this (quite slow to start)
https://gist.github.com/szs8/3669688

**Comment by mprosperi** [comment]
seems like a reference must be kept. As a workaround, in my original code everything works if I add

`self._virtual_table = self.GetTable()`

at the end of MyGrid.__init__

With the code in the above link we should add 
`grid._inner_table = grid.GetTable()`
in the create_grid method

**Comment by RobinD42** [comment]
Yes, you either need to hold the reference to the table yourself somewhere in your code, or you need to tell the Grid to take ownership of the table by passing `takeOwnership=True` to the `SetTable` method.
