### ISSUE TITLE
DirPicker and DirDialog not working when pythonnet is imported

### ISSUE THREAD

**Issue by miikeat** [wxWidgets/Phoenix#810]
**Operating system**: Windows 10
**wxPython version**: 4.0.1
**Stock or custom build**: Stock
**Python version**: 3.6.3
**Stock or custom build**: Stock
**Pythonnet version**: 2.3.0

**Description of the problem**:

If you run the following example and click on the browse button the program stops working

```python
import wx
import clr
if __name__ == '__main__':
    app = wx.App()
    frame = wx.Frame(None)
    wx.DirPickerCtrl(frame)
    frame.Show()
    app.MainLoop()
```

**Comment by miikeat** [comment]
Seems like this could be an explanation https://github.com/pythonnet/pythonnet/issues/657

I experienced the same behaviour when opening a Windows.Forms.FolderBrowserDialog via pythonnet without starting a seperate thread. 
Maybe that's the same issue here...

**Comment by mesalu** [comment]
I don't think this falls within the scope of wxWidgets/Python. By making .NET calls directly you're sidestepping wxWidgets and its intent.

**Comment by righthandabacus** [comment]
@mesalu I don't think the sidestepping part here. Yes, .NET is loaded but at most you're expanding the module space accessible. I would not expect the behaviour of wxWidgets will change. The sample code in the OP does not event invoke any .NET function. It worth to know the root cause to this.

**Comment by miikeat** [comment]
@mesalu Sorry for replying so late to your message, but I think you misunderstood something in my post!

The first message is the actual problem! I need python.net to load some dll's and use them to commuincate with another device. I dont think wxWidgets offers this functionality so i wouldn't call that sidestepping!

In the third message I was just sharing an example where the DirDialogs are working to help someone who is able to investigate this bug!
