### ISSUE TITLE
Python 3 support? (Build Failure)

### ISSUE THREAD

**Issue by kotoroshinoto** [wxWidgets/Phoenix#814]
using the build command: python build.py dox etg --nodoc sip build
Python 3.6.3 :: Anaconda, Inc.
on Windows 10 x64

dox command fails

Running command: dox
Checking for C:\Users\mgooc\REPOS\Phoenix\bin\doxygen-1.8.8-win32.exe...
Traceback (most recent call last):
  File "build.py", line 2020, in <module>
    main(sys.argv[1:])
  File "build.py", line 194, in main
    function(options, args)
  File "build.py", line 854, in cmd_dox
    _doDox('xml')
  File "build.py", line 838, in _doDox
    doxCmd = runcmd(cygwin_path+'/bin/cygpath -u '+doxCmd, True, False)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
Finished command: dox (0.237s)

I have seen this sort of error in code written for python 2 before so I suspect this is the case here  as well.

Python is transitioning away from supporting version 2 in favor of 3, so there is an imperative to start making all tools work on 3. I hope Phoenix keeps this as an important factor to keep in mind during development

I also notice it seems to be assuming a cygwin environment. Is that the only supported build setup?

python 3 seems to only support builds using visual studio compilers (I think the version i'm on might want version 14)

EDIT: (i did miss a step, so I apologize for the 2 pointless notification emails. I removed those comments and will be running a build attempt after running a submodule init)

**Comment by kotoroshinoto** [comment]
Building without the dox or etg commands (python build.py --nodoc sip build) results in the following:

Will build using: "E:\Anaconda3\python.exe"
3.6.3 |Anaconda, Inc.| (default, Oct 15 2017, 03:27:45) [MSC v.1900 64 bit (AMD64)]
Python's architecture is 64bit
cfg.VERSION: 4.1.0a1

Running command: sip
Finished command: sip (0.1s)
Running command: build
Running command: build_wx
MSVC: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\cl.exe
wxWidgets build options: ['--wxpython', '--unicode']
ERROR: failed building wxWidgets
Traceback (most recent call last):
  File "build.py", line 1321, in cmd_build_wx
    wxbuild.main(wxDir(), build_options)
  File "C:\Users\mgooc\REPOS\Phoenix\buildtools\build_wxwidgets.py", line 187, in main
    VERSION = tuple([int(i) for i in getWxRelease().split('.')[:2]])
  File "C:\Users\mgooc\REPOS\Phoenix\buildtools\build_wxwidgets.py", line 95, in getWxRelease
    configureText = open(os.path.join(wxRoot, "configure.in"), "r").read()
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\mgooc\\REPOS\\Phoenix\\ext\\wxWidgets\\configure.in'
Finished command: build_wx (0m9.313s)
Finished command: build (0m9.314s)

**Comment by kotoroshinoto** [comment]
it doesn't appear to be able to obtain/download the submodule for wx as part of the build process, should I have run a command on that ahead of time? Did I miss a step?

**Comment by RobinD42** [comment]
> I also notice it seems to be assuming a cygwin environment. Is that the only supported build setup?

Currently, yes. The intent is that most people will not need to use the git source tree unless they are actually working on wxPython itself, and so requiring cygwin in those cases didn't seem to be that big of stretch. 

For all others the intent is that they will use either a released source archive or a source archive from the pre-release snapshots server. Those files contain wxWidgets source and also all of the files generated by the dox, etg, sip, etc. commands. That means that all that needs to be done are the `build.py` or `setup.py` commands for building, packaging and perhaps installing, and at last check those should not be doing anything that needs cygwin commands.

> python 3 seems to only support builds using visual studio compilers (I think the version i'm on might want version 14)

That is correct. Stock Python 3.5+ requires version 14, which is also known as Visual Studio 2015. I assume that Anaconda follows the same pattern. I think that VS 2017 can be set to optionally install and use the 2015 version of the compilers too, but I haven't tried that.  There are free community edition versions of the compiler that are supposed to include enough to work for building Python extensions, but I haven't tried that yet either.

**Comment by RobinD42** [comment]
What was the build command you used? Was it done in a freshly unarchived source tree?

**Comment by kotoroshinoto** [comment]
It has been a while so i'd have to give it another go to be certain. I think it was fresh, as I do not do development for the project and when testing I try to make sure intermediate artifacts are cleaned before running things.

I think I had dropped some of the build directives as they didn't work. (like dox or sip), so I was probably only using python build.py --nodoc build or similar by that point
