### ISSUE TITLE
An simple interface plotted by matplotlib and cartopy isn't showed in wxpython

### ISSUE THREAD

**Issue by lyw615** [wxWidgets/Phoenix#821]
**Description of the problem**:
I'm completely a newcomer in wxpython.I have tried to make an simple interface showed  in wxpython.But some problem are meeted.The details and codes are put  on this web:https://stackoverflow.com/questions/49893460/an-simple-interface-plotted-by-matplotlib-and-cartopy-isnt-showed-in-wxpython
Any resolutions are appreciated

**Comment by DietmarSchwertberger** [comment]
Shouldn't this be closed now as you found the solution?
Anyway, this issue tracker is more for bugs.
For questions, best post to the wxpython-users mailing list.
