### ISSUE TITLE
The wx.TextCtrl can't deal control char in ascii table?

### ISSUE THREAD

**Issue by jekoie** [wxWidgets/Phoenix#826]
i have a string need to place into wx.TextCtrl and show , but the string contains control char and show messy chars in it，need help?

just like, s = "Raisecom# hel\x08\x08\x08help"   and  \0x08 is back char .

> s = "Raisecom# hel\x08\x08\x08help" 
> te = wx.TextCtrl(self, -1, style=wx.TE_MULTILINE)
> te.AppendText(s)

but in TextCtrl is show  something like this   "Raisecom# hel□□□help"

**Comment by RobinD42** [comment]
While ASCII 8 is defined as backspace for terminals and terminal emulators, its behavior is undefined for GUI elements. What you are seeing is one of the ways that GUIs will show you that there is no glyph in the current font for that character.

If you need to support using ASCII 8 in a backspace-like manner, then you'll need to parse the incoming string and modify it appropriately before adding it to the textctrl.
