### ISSUE TITLE
Display gauge before call subprocess

### ISSUE THREAD

**Issue by ShuaiW** [wxWidgets/Phoenix#831]
I have the following code where I would want to display the gauge before calling the subprocess. However, the gauge was always displayed after the subprocess function. I tried `wx.AfterCall`, `ex.FutureCall`, and even `time.sleep(n)` and none works. FYI the subprocess would usually generate a pause (on Mac it's a rotating palette)

```python
import wx
import subprocess

class Example(wx.Frame):
  def __init__(self):
    wx.Frame.__init__(...)
    self.InitUI()

  def InitUI(self):
    self.pnl = wx.Panel(self)

    btn = wx.Button(self.pnl, ...)
    btn.Bind(wx.EVT_BUTTON, self.OnClick)

    self.SetSize(...)
    self.Centre()
    self.Show(True)

  def OnClick(self, e):
    self.LoadGauge()
    self.CLI()

  def LoadGauge(self):
    self.gauge = wx.Gauge(self.pnl, ...)
    self.gauge.Pulse()

  def CLI(self):
    cmd = ...
    subprocess.call(cmd, shell=True)


if __name__ == '__main__':
  app = wx.App()
  Example()
  app.MainLoop()
    
```

**Comment by RobinD42** [comment]
You call to `subprocess.call` is blocking until the subprocess is done, and so control will not return to the main event loop until then. That means that pending and future events (such as painting the gauge) will not be able to be processed while waiting. If you need to keep the UI responsive then all long-running tasks should be run from a separate thread, or adapt your code in other ways to use one of the other [common techniques](https://wiki.wxpython.org/LongRunningTasks) to prevent blocking the GUI thread.
