### ISSUE TITLE
TextCompleterSimple still requires the "Start" and "GetNext" method to be overriden.

### ISSUE THREAD

**Issue by RobinD42** [wxWidgets/Phoenix#836]
**Operating system**:any
**wxPython version**:4.02
**Stock or custom build**:any
**Python version**:any
**Stock or custom build**:any

**Description of the problem**:

https://groups.google.com/d/msg/wxpython-users/PSwmwPI4itA/cTZ5BuDJAwAJ

**Comment by swt2c** [comment]
I would think that the test case I added would expose this but it seems that it does not.

**Comment by RobinD42** [comment]
Yeah, I was also wondering about why it didn't show up there.

**Comment by RobinD42** [comment]
Oh, right. Classes that are marked as abstract get an exception when constructed, but those that aren't only raise the exception when the base class virtual is called without having been overridden in Python. 

> I think that all that needs to be done here is Wig in the Start() and GetNext() method declarations since they're not declared in the interface header.

Or just copy the MethodDefs from the base ClassDef. 😃 (I wish I had thought of doing it this way a long time ago...)

**Comment by XPsoud** [comment]
Well, this doesn't seems to be enough... 
**Start** and **GetNext** methods are not required anymore, but the **GetCompletions** one does nothing.

Attached is a small app showing the use of both TextCompleter (witch works fine) and TextCompleterSimple (witch doesn't works).

And as a complement of informations : if the **Start** and **GetNext** methods of **TextCompleterSimple** are overriden, it works like the **TextCompleter** class (you can try copy/paste these methods from one class to the other to see)

[AutoComplete.zip](https://github.com/wxWidgets/Phoenix/files/1963745/AutoComplete.zip)

**Comment by RobinD42** [comment]
Ok, thanks for the sample. I'll work on a fix soonish.

**Comment by RobinD42** [comment]
Fixed by #840
