### ISSUE TITLE
Problem building on Ubuntu 18.04 - anyone know what is missing?

### ISSUE THREAD

**Issue by sildeag** [wxWidgets/Phoenix#841]
**Operating system**: Ubuntu 18.04
**wxPython version**: 4.1.0a1
**Stock or custom build**: python build.py etg sip build clean touch test
**Python version**: 2.7.15rc1
**Stock or custom build**: stock

Output from `python build.py etg sip build clean touch test`

`[GCC 7.3.0]`
`Python's architecture is 64bit`
`cfg.VERSION: 4.1.0a1`

`Running command: etg`
`"/usr/bin/python" etg/numdlg.py --sip`
`Unable to find xml file for ITEM: wxNumberEntryDialog`
... 
Ouput without `etg sip`
`IOError: [Errno 2] No such file or directory: 'sip/cpp/_core.sbf'`

Thanking you in advance for any help.

**Comment by DietmarSchwertberger** [comment]
Did you try the commands from here https://github.com/wxWidgets/Phoenix ?
On Ubuntu 17 they work, once you have all dependencies installed:
`python3 build.py dox etg --nodoc sip build`
Missing XML files are probably related to the missing `dox`.

**Comment by mesalu** [comment]
You need to run the `dox` command in addition to the other build commands
ex:
`python build.py dox etg --nodoc sip build test`
Also, in case you haven't, you'll need to initialize the wxWidgets submodule with git.
`git submodule init`
`git sumodule update
I believe you may need to pass a recursive flag to that now too while on the master branch

**Comment by sildeag** [comment]
Thanks.  With all `Ubuntu` dependencies mentioned in build instructions.
`sudo apt-get install dpkg-dev python2.7-dev libjpeg-dev libtiff-dev libsdl1.2-dev libgstreamer-plugins-base1.0-dev libnotify-dev freeglut3 freeglut3-dev libsm-dev libgtk-3-dev  libwebkit2gtk-4.0-dev libxtst-dev` and `sudo apt-get install  libwebkitgtk-dev libwebkitgtk-3.0-dev`

`cd Phoenix`
` git submodule update --init --recursive`

For `Python 3.6.5` stock `Ubuntu 18.04 LTS` and `Python 2.7.15` same error...

Output from `python3 build.py dox etg --nodoc sip build`
`Checking for /home/gordon/Phoenix/bin/doxygen-1.8.8-linux...`
`bash ./regen.sh xml`
`Finished command: dox (0m19.917s)`
`Running command: etg`
`"/usr/bin/python3" etg/numdlg.py --sip --nodoc`
`Unable to find xml file for ITEM: wxNumberEntryDialog`

**Comment by RobinD42** [comment]
> It looks like you may be trying to build the master branch from git? If so, you should build the wxPy-4.0.x branch instead.

Yes, the master needs some attention. The current and next releases are based on the wxPy-4.0.x branch, and at the moment that is what everyone should be using. 

Additionally, if you just need to make a build and are not planning on contributing PRs[1] then I suggest using either the released (from [PyPI](https://pypi.org/project/wxPython/)) or snapshot (from [here](https://wxpython.org/Phoenix/snapshot-builds/)) source archives as your starting point. They contain all the files that would take extra steps to get or generate if you are using a git checkout. This way you should be able to do just `python build.py build` to get a build you can test in-place, and then an additional `build.py` command can be used to install or make an installable wheel, or whatever you need.

[1] And even if you are planning on making PRs it might be a good idea to do your first build from the source archive in order to simplify things while you are getting dependent libs installed, etc.

**Comment by sildeag** [comment]
Thanks RobinD42, I tried `git checkout -b wxPy-4.0.x remotes/origin/wxPy-4.0.x` and no further ahead.  Now I'll try the snapshot source archives as dependency must be missing.

**Comment by sildeag** [comment]
Thank you Deitmar.  I used the dependencies mentioned in the build instructions which are incomplete as they make no mention of using a `branch`  - my comment earlier lists what I used for `Ubuntu 18.04 LTS` and `python2.7`, I also have `python3.6` and `python3.6-dev` previously installed, ie. `sudo apt-get install dpkg-dev python2.7-dev libjpeg-dev libtiff-dev libsdl1.2-dev libgstreamer-plugins-base1.0-dev libnotify-dev freeglut3 freeglut3-dev libsm-dev libgtk-3-dev libwebkit2gtk-4.0-dev libxtst-dev` and `sudo apt-get install libwebkitgtk-dev libwebkitgtk-3.0-dev `.  I will let everyone know what is missing when I figure it out.  I suspect it is a couple of `xml` files and `sip`.  It could be more.  I just wanted to build everything from source code.  I intend to use `gtk=3`

**Comment by RobinD42** [comment]
> I think it would be good to have wheels for Ubuntu 17/18 as the wheel for 16 depends on libpng12-0 while only libpng16 is available.

Yep, I have an in-progress branch for setting up a builder for 18.04.

**Comment by RobinD42** [comment]
> I used a snapshot, wxPython-4.0.2a1.dev3711+f5a4523.tar.gz, and am happy that `cd <wxPython folder>` and `python build.py etg sip build clean touch test` worked. gtk=3 seemed to be the default.

Is that really the command line you used? Are you sure it worked? Doing the `clean` after the `build` should have resulted in wiping out most of what was just built. Also, since you're using the snapshot source archive, all that was really needed was the `build` command.
