### ISSUE TITLE
wxAsserttionError when wxTextCtrl AppendText in a or many threads???

### ISSUE THREAD

**Issue by jekoie** [wxWidgets/Phoenix#842]
i have a frame that run **wxAssertionError:C++ assertion "idx<m_size" failed at  C:\PROJETS\buildbots\win7-py27\dist-win32-py27\Phoenix\..\wx/vector.h(404) in wxVector<int>::at():** Error when  wx.TextCtrl  AppendText in a or many  thread.
i use python2.7 and run the app in windows XP(SP3), it may be run an hour can  throw this error and restart  
app then run similar an hour it will throw this error again.

Below is a demo:
```
import wx
import threading
import time

def write_log(data):
    while True:
        text_tc, toggle =  data['text_tc'],data['toggle']
        text_tc.AppendText(u"Your news feed helps you keep up with recent activity on repositories you watch and people you follow.\n")
        time.sleep(0.1)
        if toggle == True:
            break

class MyFrame(wx.Frame):
    def __init__(self):
        wx.Frame.__init__(self, None)
        self.panel = wx.Panel(self)
        self.thread = None
        self.thread_data = {}

        self.start = wx.Button(self.panel, label='start')
        self.stop = wx.Button(self.panel, label='stop')
        self.text_tc = wx.TextCtrl(self.panel, -1, style=wx.TE_MULTILINE |wx.TE_READONLY| wx.TE_RICH|wx.TE_PROCESS_TAB|wx.TE_PROCESS_ENTER)

        sizer = wx.BoxSizer(wx.VERTICAL)
        sizer.Add(self.start, 0, wx.EXPAND)
        sizer.Add(self.stop, 0, wx.EXPAND)
        sizer.Add(self.text_tc, 1, wx.EXPAND)
        self.panel.SetSizer(sizer)

        self.Bind(wx.EVT_BUTTON, self.OnStart, self.start)
        self.Bind(wx.EVT_BUTTON, self.OnStop, self.stop)


    def OnStart(self, evt):
        if self.thread is None:
            self.thread_data = {'text_tc':self.text_tc, 'toggle':False}
            self.thread = threading.Thread(target=write_log, args=(self.thread_data,))
            self.thread.start()


    def OnStop(self, evt):
        if self.thread:
            self.thread_data['toggle'] = True
            self.thread = None

class App(wx.App):
    def __init__(self):
        wx.App.__init__(self)

    def OnInit(self):
        frame = MyFrame()
        frame.Show()
        return True


app = App()
app.MainLoop()
```
Can anyone can help me and solve the problem???

![img_1556](https://user-images.githubusercontent.com/6836400/39658530-231ce850-5048-11e8-91b6-cba6d53200f8.JPG)

**Comment by swt2c** [comment]
It looks like you are accessing GUI elements from a secondary thread.  This is likely to lead to problems as you are seeing.  You can usually use `wx.CallAfter` in these types of situations:
https://wiki.wxpython.org/CallAfter

**Comment by RobinD42** [comment]
In addition to the potential threading problems...  Since it takes an hour to have the problem manifest, and since it is XP and appears to be a 32-bit build, I wonder how much text is in the control at that time. If it's quite large then you may be running into limitations on size of the content of the native control, or perhaps overflowing a C `int` or `long` value somewhere.

**Comment by jekoie** [comment]
the wxTextCtrl recevie about 10k bytes and then clear it. and run another a thread to receive.many time it run well but sometimes it run error.

**Comment by swt2c** [comment]
Sorry, but you can't write to wxTextCtrl from anything other than the main thread.  You can use wx.CallAfter from a secondary thread to update your TextCtrl.

**Comment by RobinD42** [comment]
> if i use wx.CallAfter place it in main thread and then transfer data to child thread, it will be difficulty for me.

It really isn't that difficult. In your example above it would look like this:

```python
    wx.CallAfter(text_tc.AppendText, theText)
```

If you need to do more with UI elements at the same time then it's easy to just refactor those things out into another method and pass it to the `wx.CallAfter`

**Comment by jekoie** [comment]
i will try this method and do the same things to reproduce the issues that will be raise or not.
