### ISSUE TITLE
agw/AUI.py demo asserts 

### ISSUE THREAD

**Issue by tianzhuqiao** [wxWidgets/Phoenix#843]
When run the awg/AUI.py demo, it asserts, which looks like the same issue mentioned in http://trac.wxwidgets.org/ticket/17080

Apply the similar patch in http://trac.wxwidgets.org/attachment/ticket/17080/auibar.cpp.patch to wx/lib/agw/aui/auibar.py seems solve the issue.
 
> Traceback (most recent call last):
>   File "agw/AUI.py", line 3038, in OnButton1
>     self.win = MainAUI(self, self.log)
>   File "agw/AUI.py", line 3009, in MainAUI
>     frame = AuiFrame(parent, -1, "AUI Test Frame", size=(800, 600), log=log)
>   File "agw/AUI.py", line 910, in __init__
>     self.BuildPanes()
>   File "agw/AUI.py", line 1301, in BuildPanes
>     ToolbarPane().Top().Row(2))
>   File "/home/tianzhu/temp/Phoenix/wx/lib/agw/aui/framemanager.py", line 4735, in AddPane
>     return self.AddPane1(window, arg1)
>   File "/home/tianzhu/temp/Phoenix/wx/lib/agw/aui/framemanager.py", line 4804, in AddPane1
>     tb.SetGripperVisible(True)
>   File "/home/tianzhu/temp/Phoenix/wx/lib/agw/aui/auibar.py", line 2511, in SetGripperVisible
>     self.Realize()
>   File "/home/tianzhu/temp/Phoenix/wx/lib/agw/aui/auibar.py", line 3082, in Realize
>     ctrl_sizer_item = vert_sizer.Add(item.window, 0, wx.EXPAND)
> wx._core.wxAssertionError: C++ assertion ""!m_containingSizer"" failed at /home/tianzhu/temp/Phoenix/ext/wxWidgets/src/common/wincmn.cpp(2476) in SetContainingSizer(): Adding a window already in a sizer, detach it first!

**Comment by RobinD42** [comment]
Fixed by #859
