### ISSUE TITLE
agw/AUI.py demo window flickering

### ISSUE THREAD

**Issue by tianzhuqiao** [wxWidgets/Phoenix#851]
On Linux (e.g., buntu 16.04) 
1. run the agw/aui.py demo,
2. turn on "Live Resize Update" option (in Options menu)
3. drag the gripper, the screen will flicker 
![2018-05-10_20-48-48](https://user-images.githubusercontent.com/12435643/39953524-5f42dc6c-5562-11e8-9d4b-81b9072fc674.gif)

**Comment by tianzhuqiao** [comment]
After remove unnecessary notebook updating (#852),

![2018-05-10_21-52-58](https://user-images.githubusercontent.com/12435643/39953704-0b0f02a2-5566-11e8-9707-ce3233bb6bd2.gif)

**Comment by RobinD42** [comment]
Fixed by #852
