### ISSUE TITLE
linux x64 dev2054 --gtk3 python 3.5 builds fine but fails tests

### ISSUE THREAD

**Issue by psionprime** [wxWidgets/Phoenix#87]
Building with gtk2 does not have the unreferenced var. I googled around and found some fringe things near wxWidget space but was old and my system is XOrg, not Wayland *I think*, and thought _mir_ was for that but frustrated I don't have enough experience to fix this myself. Thank you devs for your efforts. I wish I could contribute more than this.

I note there is a very similar issue [https://github.com/wxWidgets/Phoenix/issues/86](url) but that was affected by _adv and this appears to be _core...

I built fresh wxWidgets 3.1.0 --with-gtk=3 from the March tar ball without issue and a git clone from a few minutes ago without issue; for perspective.

System:

Ubuntu Studio 16.04 x64 
Linux 4.4.0-22-lowlatency #40-Ubuntu SMP PREEMPT Thu May 12 22:54:03 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Build line:

python3 build.py 3.5 dox etg --nodoc sip build --gtk3 --jobs=8

------------ BUILD FINISHED ------------
To use wxPython from the build folder (without installing):
 - Set your PYTHONPATH variable to /.../wxPython_Phoenix-3.0.3.dev2054+14a1ddd.
 - You may also need to set your (DY)LD_LIBRARY_PATH to /.../wxPython_Phoenix-3.0.3.dev2054+14a1ddd/build/wxbld/lib,
   or wherever the wxWidgets libs have been installed.

Finished command: build_py (6m18.824s)
Finished command: build (8m58.18s)
Done!

Running tests:

python3 build.py test

Build using: "/usr/bin/python3"
3.5.1+ (default, Mar 30 2016, 22:46:26) 
[GCC 5.3.1 20160330]
Python's architecture is 64bit
cfg.VERSION: 3.0.3.dev2054+14a1ddd

Running command: test
"/usr/bin/python3" unittests/runtests.py  
Traceback (most recent call last):
  File "unittests/runtests.py", line 41, in <module>
    import wx
  File "/.../wxPython_Phoenix-3.0.3.dev2054+14a1ddd/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "/.../wxPython_Phoenix-3.0.3.dev2054+14a1ddd/wx/core.py", line 6, in <module>
    from ._core import *
ImportError: /.../wxPython_Phoenix-3.0.3.dev2054+14a1ddd/wx/libwx_gtk3u_core-3.0.so.0: undefined symbol: _Z24gdk_mir_display_get_typev
Command '"/usr/bin/python3" unittests/runtests.py  ' failed with exit code 1.
Finished command: test (0.221s)
Done!

**Comment by RobinD42** [comment]
This type of undefined symbol error typically means that there is a mismatch between the compilation environment and the runtime environment. In other words, something that the compiler expected to be available at runtime is not.  Either the source code headers (for gdk in this case apparently) do not match the runtime shared libraries installed, or perhaps the wrong set of libraries are being found at runtime.

To track down the cause of the problem you can double check which "-dev" packages are installed and that they seem reasonable for what you are trying to build, check what shared libs are on the system, and check which are trying to be loaded by the wxPython modules at runtime (by using commands like `ldd libwx_gtk3u_core-3.0.so.0`)  You can influence which libs will be loaded at runtime by setting `LD_LIBRARY_PATH`.  If you make changes for the build be sure to clean everything from the previous build before redoing it. (The `build.py` tool has a `clean` command.)  Also pay close attention to the output at the beginning of the wxWidgets build when it is doing its configuration, sometimes there are clues there about what libs may be missing on your system.

Good luck.

**Comment by psionprime** [comment]
Thank you for your reply. The gtk libs came from the Ubuntu 16.04 LTS repositories *** but *** I just though a little bit ago I am running Cinnamon 3 desktop on top of Ubuntu Studio and I think they forked gnome 3 for it so *maybe* there is something going on there. I'll build inside the ubuntu livecd environment and see what happens.

I understand the lib conflict and what you described. I thought of that but I built regular wxWidgets and it was fine. I only just found out by checking the git modules that you are using the py3 branch of it though I saw a merge. /shrug No worries I'll track down what's going on :) thanks for the pointers

Btw, if the build bot is not running the unit tests, maybe it should and report the results, as so far, not once have the unit tests all ran fine. So perhaps an auto message added to the build bot report on what unit test failed might help track things better. I can also contribute space on my machines to run a vm build bot for Ubuntu Linux LTS 16.04 x64 if needed.

**Comment by swt2c** [comment]
This is a actually a Gtk+3 bug but only on Ubuntu.  wxWidgets has a workaround for it on master.  I asked Paul to cherry-pick it to the 3.0 branch also:
https://github.com/wxWidgets/wxWidgets/commit/1908c41f36880b9b8f55c0abb25d3d80700b2193

**Comment by RobinD42** [comment]
Looks like he has done it.  Thanks

**Comment by swt2c** [comment]
Great, now you just need to update the wxWidgets ref in Phoenix.  :-)
