### ISSUE TITLE
The controls on agw.aui.AuiToolBar may overlap with overflow button

### ISSUE THREAD

**Issue by tianzhuqiao** [wxWidgets/Phoenix#872]
Run demo/agw/AUI.py; as shown in the following image, the control on toolbar may overlap with the overflow button (near the mouse). 

It seems that in this case, the tool item (with control) does not fit into the toolbar; thus, the control should also be hidden. 

![virtualbox_2018-05-30_23-05-03](https://user-images.githubusercontent.com/12435643/40764467-ffd5ea66-645d-11e8-819c-3eab5d6f9e88.png)

**Comment by tianzhuqiao** [comment]
After the change

![virtualbox_2018-06-02_18-41-58](https://user-images.githubusercontent.com/12435643/40882465-7b5cd2b8-6697-11e8-9a9b-009a5573d084.png)

**Comment by RobinD42** [comment]
Fixed by #876
