### ISSUE TITLE
wx.adv.EVT_CALENDAR_WEEK_CLICKED missing

### ISSUE THREAD

**Issue by DietmarSchwertberger** [wxWidgets/Phoenix#875]
**Operating system**: Windows
**wxPython version**: (4, 0, 2, 'a1.dev3761+22c12acb')
**Stock or custom build**: Stock
**Python version**:  3.6.4
**Stock or custom build**: stock

**Description of the problem**:

`wx.adv.EVT_CALENDAR_WEEK_CLICKED` is documented, but not defined in `etg/calctrl.py`

(it's referenced by `module.insertItemAfter(module.find('wxEVT_CALENDAR_WEEK_CLICKED'), item)`, though...)

**Comment by RobinD42** [comment]
Fixed by #878
