### ISSUE TITLE
When drag a floating AuiToolBar around a edge, its size and orientation may not be correct.

### ISSUE THREAD

**Issue by tianzhuqiao** [wxWidgets/Phoenix#880]
When drag a floating AuiToolBar to a edge, and then drag it back (without releasing the mouse), sometimes,
1. the floating frame size may not be correct;
2. the AuiToolBar orientation may not be correct.

It looks like,
1. OnFloatingPaneResized() may change the **floating_size** of a AuiToolBar pane (which should not be allowed);
2. OnMotion_DragToolbarPane( ) may change the orientation.

![2018-06-05_21-14-01](https://user-images.githubusercontent.com/12435643/41018761-53f1dd88-6910-11e8-9cd5-16fcffcbdf82.gif)

![virtualbox_2018-06-05_22-48-44](https://user-images.githubusercontent.com/12435643/41019225-9fc71906-6912-11e8-9aff-47b1b616ca67.png)

**Comment by RobinD42** [comment]
Fixed by #881
