### ISSUE TITLE
awg.aui.AuiManager may reset the automatic notebook pages order

### ISSUE THREAD

**Issue by tianzhuqiao** [wxWidgets/Phoenix#882]
awg.aui.AuiManager may reset the automatic notebook page order
1) run agw/aui.py
2) drag the the page in an automatic notebook to change its order
3) drag any pane to change its size (to trigger AuiManager.Update())
4) the order of automatic notebook pages will be reset

It looks like it is due to
1) in UpdateNotebook() (~ line 6669), if an automatic notebook has more than 1 pages, it will order its pages by the **dock_pos** of their corresponding panes
2) however, when drag a page on an automatic notebook, the notebook will not change its **dock_pos** (notebook does not know anything about the pane of its page)

One potential fix may be
1) when UpdateNotebook() is called, 
    1) when multiple pages are added to a same notebook, order them by their **dock_pos** (e.g., so after LoadPerspective(), the pages order are correct. )
    2) otherwise, do not check and re-order automatic notebook pages 
2) In LayoutAll() (~line 6185), if a pane is a notebook page, set its **dock_pos** to the page index in the notebook 

![2018-06-12_22-22-01](https://user-images.githubusercontent.com/12435643/41331745-7886eefc-6e8f-11e8-8ed0-f80e26490950.gif)

**Comment by tianzhuqiao** [comment]
After the change

![2018-06-16_21-32-48](https://user-images.githubusercontent.com/12435643/41504719-0780d90e-71ad-11e8-94f8-77ed08154b97.gif)

**Comment by RobinD42** [comment]
Fixed by #885
