### ISSUE TITLE
wxPython 4.0.2 loses Py27 compatibility (partial)

### ISSUE THREAD

**Issue by jensgoe** [wxWidgets/Phoenix#887]
**Operating system**: all
**wxPython version**: 4.0.2
**Stock or custom build**: stock
**Python version**: 2.7.15
**Stock or custom build**: stock

**Description of the problem**:

If i install wxPython via pip with `pip install wxpython`
It installs PyPubSub as well. The problem is version 4.0.0 of PyPubSub got installed, that is not compatible with Python2. 
Running `pip install PyPubSub==3.3.0` fixes this.

This is probably a PyPubSub problem, because installing PyPubSub standalone in a clean Py27 virtual env already installs version 4.0.0. Somehow the pubsub team should publish the version 4.0.0 release for Py3 only.

Another problem might be the setupkwargs api for PyPubSub. It is activated with `from pubsub import setupkwargs` before importing pub from pubsub. At least with version 3.3.0. The user must do this on its own before importing wx (at least wx.lib.evtmgr).

**Comment by swt2c** [comment]
This seems bad.  Does wxPython 4.0.2's pubsub stuff actually work when you install PyPubSub 3.3.0?  If not, seems like fixing this would require either:
1. Convince the PyPubSub maintainer to add Python 2 support back in.
2. Roll back the PyPubSub removal in wxPython.

CC: @david-hughes

**Comment by Lokla** [comment]
Had to switch pyPubSub to 3.3.0 a while ago due to that problem (using dev branch since the fix for #742) .

All seems to work for me so far.

Michael

**Comment by mesalu** [comment]
I haven't looked at it closely, but if @Lokla is right, and we don't require any internal changes to adapt to API changes, we should be able to just adjust dependencies such that any py2 bundle requires pypubsub==3.3.0 and py3+ has no strict versioning requirements.

This could run into some issues (e.g. the pypubsub package is updated post-install) but *IMO* that's user error.

@RobinD42, thoughts?

**Comment by swt2c** [comment]
> I haven't looked at it closely, but if @Lokla is right, and we don't require any internal changes to adapt to API changes, we should be able to just adjust dependencies such that any py2 bundle requires pypubsub==3.3.0 and py3+ has no strict versioning requirements.

Yeah, I thought about that approach, too.  It could work in theory, but will create more work for packagers (like me) as I'll have to package both pypubsub versions.  :P

**Comment by jensgoe** [comment]
pypubsub 3.3.0 is working for me too with wxPython4.0.2. May this be fixed by pubsub maintainers? installing pypubsub with pip in a Py27 environment installs version 4.0.0 which is indeed not working. The last version that pip should install for Py27 is 3.3.0

**Comment by swt2c** [comment]
> pypubsub 3.3.0 is working for me too with wxPython4.0.2. May this be fixed by pubsub maintainers? installing pypubsub with pip in a Py27 environment installs version 4.0.0 which is indeed not working. The last version that pip should install for Py27 is 3.3.0

I opened a ticket at the PyPubSub tracker to see what he says about Python 2 support.

**Comment by mesalu** [comment]
For the sake of tracking:
https://github.com/schollii/pypubsub/issues/9

**Comment by schollii** [comment]
This might be fixed by latest patch to pypubsub's setup.py which adds python_requires. In theory a pip install of wxpython from python 2.x will fetch the 3.3.0 version of pypubsub, but I have not tried, any feedback would be much appreciated.

**Comment by jensgoe** [comment]
outdated
