### ISSUE TITLE
Minor typo for GenericDatePickerCtrl in Classic vs Phoneix guide

### ISSUE THREAD

**Issue by will133** [wxWidgets/Phoenix#890]
**Operating system**: Any
**wxPython version**: 4.0.1
**Stock or custom build**: N/A
**Python version**: N/A
**Stock or custom build**: N/A

**Description of the problem**:
The https://github.com/wxWidgets/Phoenix/blob/master/docs/classic_vs_phoenix.rst documentation states that the wx.GenericDatePickerCtrl is moved to wx.adv.GenericPickerCtrl, which I think should be wx.adv.Generic**Date**PickerCtrl.

**Comment by RobinD42** [comment]
Fixed in 527fca7cd3779d4a652662c09205c0d452ea80f1
