### ISSUE TITLE
IntCtrl fails on Python3 due to the usage of long

### ISSUE THREAD

**Issue by gatagat** [wxWidgets/Phoenix#898]
**Operating system**: NA (OSX/Linux)
**wxPython version**: 4.0.2 (pip installed from pypi)
**Python version**: 3.6

**Description**
An IntCtrl raises NameError on Python 3 when it parses an unparseable string. This happens because it tries to use the Python 2 `long` type. The unparseable string can be input by typing `-1` and then deleting the `1`.

**Expected behavior**
I would not expect wx to distinguish between `int` and `long`, since `long` does not exist. I would propose to deprecate the `allow_long` on Python 3 unless it has some special meaning I did not get.

A quick & dirty fix would be: `if not six.PY2: long = int`

**Minimal example**:

```python
import wx
from wx.lib.intctrl import IntCtrl

app = wx.App()
frame = wx.Frame(None)
intctrl = IntCtrl(frame, min=0, max=None)
intctrl._fromGUI('-')
```

**Traceback**

```
Traceback (most recent call last):
  File "/.../lib/python3.6/site-packages/wx/lib/intctrl.py", line 860, in _fromGUI
    return int( value )
ValueError: invalid literal for int() with base 10: '-'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/.../lib/python3.6/site-packages/wx/lib/intctrl.py", line 511, in OnText
    value = self.GetValue()
  File "/.../lib/python3.6/site-packages/wx/lib/intctrl.py", line 527, in GetValue
    return self._fromGUI( wx.TextCtrl.GetValue(self) )
  File "/.../lib/python3.6/site-packages/wx/lib/intctrl.py", line 863, in _fromGUI
    return long( value )
NameError: name 'long' is not defined
```

**Comment by mesalu** [comment]
Looks like a variable is set to the correct `type`  early on in the module
So a change like this in that try/except (and anywhere else that's applicable) should do:

```Python
try:
    return int(value)
except ValueError:
    if self.IsLongAllowed():  # Could add a six.PY2 check here too, in order to deprecate any `long` usage in py3
        return LONGTYPE(value)
else:
    raise
```

**Comment by RobinD42** [comment]
Fixed by #899

**Comment by mesalu** [comment]
@RobinD42  did you click `reopen and comment` on accident? ;)

**Comment by RobinD42** [comment]
Yep
