### ISSUE TITLE
Warnings enabled inappropriately

### ISSUE THREAD

**Issue by efahl** [wxWidgets/Phoenix#902]
**Operating system**: Win 10 64
**wxPython version**: 4.0.2 and 4.0.3, stock, pip installed.
**Python version**: CPython 3.6.5, stock.

In wx/lib/plot/polyobjects.py at line 40 there is a line that re-enables warnings with sort of a shotgun approach:

warnings.simplefilter('default')

This causes a bunch of regressions in our Py 3 tests, with various stdlib or PyPI modules now producing deprecation warnings.  Maybe it should be a bit more surgical in its targeting, like the one in core.py (or should this even be there???).

warnings.simplefilter('default', wxPyDeprecationWarning)

Here's any easy test:

> python -c 'import imp ; print("nothing")'
nothing
> python -c 'import wx.lib.plot ; import imp'
-c:1: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses

**Comment by RobinD42** [comment]
It looks like the `wx.lib.plot` code is using the stock `PendingDeprecationWarning` instead of `wxPyDeprecationWarning`, so probably a better fix would be to derive a new class from `PendingDeprecationWarning`, update the plot modules to use it, and then set the filter using that one.

**Comment by RobinD42** [comment]
Or just switch it to use `wxPyDeprecationWarning`

**Comment by RobinD42** [comment]
Fixed by #911
