### ISSUE TITLE
How to use wx.grid.Grid.SetSelectionMode in 4.0.x?

### ISSUE THREAD

**Issue by daemondazz** [wxWidgets/Phoenix#907]
**Operating system**: Windows and MacOS
**wxPython version**: 4.0.3
**Stock or custom build**: stok
**Python version**: 3.6.1
**Stock or custom build**: stock

**Description of the problem**:

With wxPython-Pheonix 3.0.3 it was possible to do this:

```python
class MyPanel(wx.Panel)
    def __init__(self, *args, **kwargs):
        self.grid = wx.grid.Grid(self, -1)
        self.grid.SetSelectionMode(wx.grid.Grid.GridSelectRows)
```

But in 4.0.3 installed from pip GridSelectRows no longer exists and I cannot see any attributes on the wx.grid.Grid.GridSelectionModes enum to select the correct value by name.

What is the correct way to do this now?

**Comment by swt2c** [comment]
It seems that it changed to `wx.grid.Grid.wxGridSelectRows` at some point.  I'm not sure if this was intentional or not.

**Comment by swt2c** [comment]
`wx.grid.Grid.SelectRows` also works.

**Comment by daemondazz** [comment]
Argh, thanks for that. Must have been short on caffeine, especially as I saw #391.
