### ISSUE TITLE
Cannot get Button with image and text

### ISSUE THREAD

**Issue by gsemet** [wxWidgets/Phoenix#913]
Hello.

The following code http://zetcode.com/wxpython/widgets/ (wx.Gauge) does not display stock icon on the button.
I am under Ubuntu 16.04, GTK 3.18.9.
WxPython 4.0.0b1

I also tried to load bitmap with `wx.ArtProvider.GetBitmap(wx.ART_FILE_SAVE)` to a button, without text, I can get the icon only on the image, but once I manually set the label, the icon disappear.

**Comment by gsemet** [comment]
Same on wxPython 4.0.3

**Comment by Metallicow** [comment]
Did it ever occur to you that the pics are old pics and Jan only updated the code.
I don't recall if the icons are supposed to be default.... The StockButtons demo doesn't show them. I think it did at one time...
@RobinD42 what is the correct way by default. Or was there an option for this somewhere...

**Comment by RobinD42** [comment]
Whether a text button is allowed to have an icon on GTK is controlled by a global configuration option that may or may not be accessible in the Desktop Environment's configuration UI. IIRC there is some generic tool that lets you browse and edit those global options, although I don't recall the name of it. It's probably related to `gconf` somehow.

**Comment by gsemet** [comment]
I have the same behavior when I try this gauge example under windows

**Comment by Metallicow** [comment]
Yea I recall a option on linux os's to allow icons(menu's and other stuff) but, yes there is no icons under windows either.

**Comment by RobinD42** [comment]
It's not expected for the icons to be used on Windows, as that does not follow the platform's style guidelines for the stock buttons. (IOW, it's not native look-and-feel.) It is mentioned in the docs that it is just GTK where you can expect it to use the icon for the stock IDs, but as mentioned that is now controlled by the GTK configuration.

If you don't care about native LnF and must have buttons with both a label and an icon then take a look at the `wx.lib.buttons.GenBitmapTextButton` class, or some of the other generic widgets in `wx.lib`.

**Comment by gsemet** [comment]
Ok thanks!

**Comment by RobinD42** [comment]
I should also mention that `wx.Button` will allow you to explicitly set a bitmap in addition to the label. It's just when using the stock IDs with an empty label that is dependent on platform standards for whether a stock icon is added too. There's an example in the demo.
