### ISSUE TITLE
wx.stc doesn't respect user's cursor blink preference on Windows or Linux

### ISSUE THREAD

**Issue by mark-summerfield** [wxWidgets/Phoenix#914]
**Operating system**:
Windows 7-64
Ubuntu 16.04.4 LTS-64
**wxPython version**:
4.0.3 msw (phoenix) wxWidgets 3.0.5
4.0.3 gtk3 (phoenix) wxWidgets 3.0.5
**Stock or custom build**:
stock
**Python version**:
3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]
3.7.0 (default, Jul  6 2018, 15:33:53) \n[GCC 5.4.0 20160609]
**Stock or custom build**:
stock
**Description of the problem**:

wx.stc does not respect the user's cursor blink preference.
You can see this by running demo.py and clicking on the Demo Code tab, then clicking in amongst the code. Even if the user has set no blinking, the cursor blinks.
The other entry widgets (that I've tried) do respect the user's preference. 

I realise that >99.9% of people find cursor blink useful: but that still leaves 0.1% or 0.01% who can't work with blinking cursors---which is still a *lot* of people given how many computers are in use.
(See, for example, [jurta noblink](http://www.jurta.org/en/prog/noblink).)

**Comment by mesalu** [comment]
IIRC wx.StyledTextCtrl is a passthrough layer to Scintilla, so its either Scintilla not respecting OS configuration or perhaps the wxWidgets layer not correctly allowing  Scintilla to do so.

Either way I believe this belongs to wxWidgets.

**Comment by RobinD42** [comment]
Yep, the caret in this case is Scintilla's responsibility. It has APIs (which wxSTC wraps) for setting the period of the caret's blinking, but I don't see anything setting whether it will blink or be solid. It does have blink options for the "alternate carets" (which I didn't know it could do...) so maybe not allowing it for the primary caret is an oversight.

**Comment by Metallicow** [comment]
@mark-summerfield, @RobinD42, @mesalu 

https://wxpython.org/Phoenix/docs/html/wx.stc.StyledTextCtrl.html#wx.stc.StyledTextCtrl.SetCaretPeriod

```
stcinstance.SetCaretPeriod(slvalue)
```
CaretSpeed 0= SteadyOn, 1000 = 1 second


This works fine in SourceCoder on windows and linux. Not sure what your issue is....

**Comment by mark-summerfield** [comment]
SetCaretPeriod() works fine for me on Linux and Windows. My point is that it should be set to 0 if the user's preference is for no blinking. After all, all the other edit controls (that I've tried) respect the user's preference, so it is an annoying anomaly that this one doesn't.

**Comment by Metallicow** [comment]
@mark-summerfield That would be an issue to bring up with Scintilla dev then. The issues are on sourceforge iirc.

**Comment by Metallicow** [comment]
You could however program a function to run the replicates your OS settings tho as a workaround in the meantime.
