### ISSUE TITLE
Segmentation Fault with glcanvas on certain machines

### ISSUE THREAD

**Issue by lpuglia** [wxWidgets/Phoenix#915]
**Operating system**: Fedora 27
**wxPython version**: 4.0.X
**Stock or custom build**: Stock
**Python version**: 2.7
**Stock or custom build**: Stock

I'm trying to run this simple (and useless) script on different machines:

```python
    import wx
    from wx import glcanvas
    
    app = wx.App()
    frame = wx.Frame(None)
    glcanvas.GLCanvas(frame)
```

It seems to work (it ends gracefully without errors) on most PCs, but i'm encoutering problem with lenovo machines, in fact, if I launch the very same script on these machines (in particular the T470p) it fails with `segfault` on all of them (we have a bunch of them in the office).

I tried to use `pyinstaller`, I thought of a problem in the default libraries, but even when i use the libraries that are working on other machines the `segfault` is still there. Can someone point me in the right direction to solve this bug?

**Comment by lpuglia** [comment]
By chances all the new Lenovo machine came with Fedora 27 and Gnome3 - Wayland as default, if I switch to Xorg at login time, segmentation fault doesn't occur.

Thank you

**Comment by swt2c** [comment]
Okay, then most likely you are running into:
https://trac.wxwidgets.org/ticket/17702

Rather than have to use the Xorg session, another workaround you should be able to use is set `GDK_BACKEND=x11` before running your program.  For example:
`GDK_BACKEND=x11 python program.py`
should work.

**Comment by lpuglia** [comment]
This instruction makes the glcanvas work for both Xorg and Wayland:
`os.environ["GDK_BACKEND"] = "x11"`
