### ISSUE TITLE
Demo file Throbber.py throwing exception (minor bug)

### ISSUE THREAD

**Issue by TSN-ADMIN** [wxWidgets/Phoenix#924]
**Operating system**: Microsoft Windows 7 SP1 [Version 6.1.7601]
**wxPython version**: 4.0.3 msw (phoenix) wxWidgets 3.0.5
**Stock or custom build**: Stock
**Python version**: v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]
**Stock or custom build**: Stock

**Description of the problem**:

- Run the wxPython Demo
- Select Throbber
- **Exception** (when directly run from command line):
```
Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]
wx.version: 4.0.3 msw (phoenix) wxWidgets 3.0.5
Traceback (most recent call last):
  File "D:\Dev\Python27\Lib\site-packages\wxPython-demo-4.0.1\demo\run.py", line 80, in OnInit
    win = self.demoModule.runTest(frame, frame, Log())
  File ".\Throbber.py", line 235, in runTest
    win = TestPanel(nb, log)
  File ".\Throbber.py", line 49, in __init__
    if isinstance(seq, range):
TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and types
OnInit returned false, exiting...
```
See [last commit on demo file Throbber.py](https://github.com/wxWidgets/Phoenix/commit/c394c30f01e132f578c42d7043a76641958d2a91)

Changing **`range`** in line 49 from Throbber.py to **`list`** fixed this for me.

**Comment by RobinD42** [comment]
Fixed by #946
