### ISSUE TITLE
Add Python 3.7 build for Fedora-28

### ISSUE THREAD

**Issue by RobinD42** [wxWidgets/Phoenix#925]
https://groups.google.com/d/msg/wxpython-users/oXHL8trnTHE/y4-CagX2AQAJ

**Comment by RobinD42** [comment]
https://extras.wxpython.org/wxPython4/extras/linux/gtk3/fedora-28/wxPython-4.0.3-cp37-cp37m-linux_x86_64.whl

**Comment by RobinD42** [comment]
Fixed by #929

**Comment by cykerway** [comment]
While this issue has been closed, may I know if there is a wheel for gtk2 binding? Thank you

**Comment by RobinD42** [comment]
If I remember correctly, the reason I disabled gtk2 builds for Fedora-28 is that one or more of the dependencies did not have dev packages in the stock Fedora repositories. Without those wxWidgets/wxPython can not be built for gtk2

**Comment by cykerway** [comment]
Thank you for reply.

Does this mean there won't be gtk2 bindings for Fedora any more in the future? Do you still remember those package names? Can we get them from rpmfusion or other sources?

**Comment by RobinD42** [comment]
I don't remember, but I expect they are available elsewhere. For the wheels I build I prefer that they do not require things that are not available from the distro's default repositories. I don't always follow that rule but so far it's only been broken for fetching versions of Python from other sources, not for UI library build dependencies.
