### ISSUE TITLE
Investigate wxNotebook and DeleteAllPages issue on Windows.

### ISSUE THREAD

**Issue by RobinD42** [wxWidgets/Phoenix#928]
**Operating system**: any
**wxPython version**: 4.0+
**Stock or custom build**: 
**Python version**: any
**Stock or custom build**: any

**Description of the problem**:

See: https://groups.google.com/d/msg/wxpython-dev/vSKZzLsbhcA/bapcGOHwAAAJ

**Comment by TSN-ADMIN** [comment]
Robin,

FYI, I just encountered the same symptoms under 4.0.3 in my editor app under development. It uses `wx.aui.AuiNotebook`. `DeletePage()` is the culprit and here also: unable to close the notebook tab. No exception thrown.

I checked with 4.0.1: works fine. Version 4.0.2. has the same issue as 4.0.3. HTH

Cheers,
Thom

**Comment by RobinD42** [comment]
Yep, this was fixed by #939

**Comment by CrawfordW** [comment]
Also having this problem - wx.aui.AuiNotebook.DeletePage is not working. Has this been fixed? I'm just learning wx, and installed version 4.0.3 in late November 2018. Not sure why this issue was closed.

**Comment by CrawfordW** [comment]
OK, I see the difference - I was using wx.aui but Robin's demo uses agw.aui. I changed to that and it works fine.

**Comment by CrawfordW** [comment]
But there is another problem ... Closing tab n also closes tab n+1. Robin's demo does this too.
