### ISSUE TITLE
exception with wx.lib.agw.aui.AuiNotebook

### ISSUE THREAD

**Issue by mprosperi** [wxWidgets/Phoenix#93]
from the demo, dragging a tab and dropping it in another position raises this (win7, phoenix 64bit-py3.4):

Traceback (most recent call last):
  File "c:\python34\lib\site-packages\wx\lib\agw\aui\auibook.py", line 2023, in
OnLeftUp
    self.ReleaseMouse()
wx._core.wxAssertionError: C++ assertion "!wxMouseCapture::stack.empty()" failed
 at ....\src\common\wincmn.cpp(3319) in wxWindowBase::ReleaseMouse(): Releasing
 mouse capture but capture stack empty?

**Comment by swt2c** [comment]
I can confirm this.  This happens in Classic, too, so it's at least not a new bug.  :-)

**Comment by RobinD42** [comment]
The capture can sometimes be taken by the system or possibly other elements in the application, so code needs to either handle `EVT_MOUSE_CAPTURE_LOST` and deal with the change in state, or check if it still has the capture before trying to release it.  Try adding a `if self.HaseCapture():` before the release method call.

**Comment by RobinD42** [comment]
(and submit a PR 😉  )

**Comment by mprosperi** [comment]
there's already an `if self.HaseCapture():` in auibook.py both in phoenix sources and classic (wxPython3.0-win64-3.0.2.0-py27.exe) and for classic this exception is not raised. See this:
http://trac.wxwidgets.org/ticket/15947
http://trac.wxwidgets.org/changeset/76967/svn-wx

a wxwidgets-3.0.3 problem? may I report it on trac?

**Comment by Nutznieser** [comment]
Does anybody know how we can solve this problem? It does still exist and although there is a `if self.HaseCapture():` directly before calling `self.ReleaseMouse()`, it fails.

**Comment by stevenj** [comment]
try using:
import wx.aui as aui
instead of:
import wx.lib.agw.aui as aui

**Comment by Nutznieser** [comment]
Thanks for your hint. But it doesn't works. The `wx.aui` and `wx.lib.agw.aui` package are not completely equal in functions, attributes, behavior, etc. So I got other errors.

**Comment by Nutznieser** [comment]
Please see request #321 for a possible solution ...

**Comment by RobinD42** [comment]
Fixed by #321
