### ISSUE TITLE
wx.lib.pubsub submodules

### ISSUE THREAD

**Issue by swt2c** [wxWidgets/Phoenix#932]
Are wx.lib.pubsub submodule imports still supposed to work?

______________ ERROR collecting unittests/test_lib_pubsub_api3.py ______________
ImportError while importing test module '/builddir/build/BUILD/python-wxpython4-4.0.3/python3/unittests/test_lib_pubsub_api3.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
unittests/test_lib_pubsub_api3.py:14: in <module>
    from wx.lib.pubsub.core import getListenerID
E   ModuleNotFoundError: No module named 'wx.lib.pubsub.core'
___________ ERROR collecting unittests/test_lib_pubsub_defaultlog.py ___________
ImportError while importing test module '/builddir/build/BUILD/python-wxpython4-4.0.3/python3/unittests/test_lib_pubsub_defaultlog.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
unittests/test_lib_pubsub_defaultlog.py:12: in <module>
    from wx.lib.pubsub.utils import notification
E   ModuleNotFoundError: No module named 'wx.lib.pubsub.utils'
____________ ERROR collecting unittests/test_lib_pubsub_listener.py ____________
ImportError while importing test module '/builddir/build/BUILD/python-wxpython4-4.0.3/python3/unittests/test_lib_pubsub_listener.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
unittests/test_lib_pubsub_listener.py:12: in <module>
    from wx.lib.pubsub.core.weakmethod import WeakMethod
E   ModuleNotFoundError: No module named 'wx.lib.pubsub.core'
______________ ERROR collecting unittests/test_lib_pubsub_spec.py ______________
ImportError while importing test module '/builddir/build/BUILD/python-wxpython4-4.0.3/python3/unittests/test_lib_pubsub_spec.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
unittests/test_lib_pubsub_spec.py:12: in <module>
    from wx.lib.pubsub.core.topicargspec import (
E   ModuleNotFoundError: No module named 'wx.lib.pubsub.core'
_____________ ERROR collecting unittests/test_lib_pubsub_topic.py ______________
ImportError while importing test module '/builddir/build/BUILD/python-wxpython4-4.0.3/python3/unittests/test_lib_pubsub_topic.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
unittests/test_lib_pubsub_topic.py:12: in <module>
    from wx.lib.pubsub.core.topicobj     import Topic
E   ModuleNotFoundError: No module named 'wx.lib.pubsub.core'
____________ ERROR collecting unittests/test_lib_pubsub_topicmgr.py ____________
ImportError while importing test module '/builddir/build/BUILD/python-wxpython4-4.0.3/python3/unittests/test_lib_pubsub_topicmgr.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
unittests/test_lib_pubsub_topicmgr.py:12: in <module>
    from wx.lib.pubsub.pub import (
E   ModuleNotFoundError: No module named 'wx.lib.pubsub.pub'

**Comment by RobinD42** [comment]
I guess not.

I was thinking at one time that we could still make them work by importing from the real `pubsub.{submodule}` but with pubsub v4.0.0+ only working with Python3 I expect it would be too fragile to keep things working with more than one version.

**Comment by RobinD42** [comment]
If anybody cares to take on some import magic to map all the wx.lib.pubsub module and subpackage names to the real pypubsub package, and that works for both Python2.7/pypubsub-3.3.0 and Python3/pypubsub-4.0.0+ let me know. Otherwise we can merge the PR.

**Comment by swt2c** [comment]
Is `wx.lib.pubsub.*` considered part of the wxPython API though?  If so, then we really ought to fix this as these modules have disappeared since 4.0.1.

**Comment by swt2c** [comment]
Well, I'm aware of at least one open source app (Taskcoach) that uses it.  I suppose you could make a statement that wx.lib.pubsub is deprecated in Phoenix, though, and tell users they have to port to the standalone package if they need it as part of porting to Phoenix.

I might try to make the imports work, though, if I get the time.

**Comment by RobinD42** [comment]
Okay, here's a new PR that restores `wx.lib.pubsub`, updates it to 3.3.0, and adds an actual deprecation warning upon import.

**Comment by swt2c** [comment]
I like that solution!  :+1:

**Comment by RobinD42** [comment]
Fixed by #938
