### ISSUE TITLE
wxPython 2.8 problem installation on mac os x

### ISSUE THREAD

**Issue by aluckin3** [wxWidgets/Phoenix#943]
I download wxPython from this page, because RIDE needs 2.8.12.1: http://sourceforge.net/projects/wxpython/files/wxPython/2.8.12.1/
i download from this link: https://sourceforge.net/projects/wxpython/files/wxPython/2.8.12.1/wxPython2.8-osx-unicode-2.8.12.1-universal-py2.7.dmg/download

When i start installation, and i get this...
<img width="621" alt="screen shot 2018-07-26 at 00 37 11" src="https://user-images.githubusercontent.com/37189604/43231300-149ca54a-906c-11e8-8099-b5682990e039.png">

**Comment by HelioGuilherme66** [comment]
There are known problems installing that version of wxPython on MacOS. Some solutions include using `homebrew` or a workaround which is to extract the package to the desktop and lower the security level.
In my fork of RIDE, I have several [releases](https://github.com/HelioGuilherme66/RIDE/releases) which work with newer wxPython. Unfortunately  there are bugs that on Mac maybe more annoying.

**Comment by mesalu** [comment]
I'm going to close this for inactivity, not related to Phoenix itself (but rather Classic), and is ultimately a defect for RIDE and not wxPython.

If I find any guides for successfully installing a .pkg'd distribution of classic on newer versions of OSX I'll post it as an edit to this comment. 

Cheers,
    Mesalu.
