### ISSUE TITLE
GraphicsContext does not work with AutoBufferedPaintDC

### ISSUE THREAD

**Issue by itsayellow** [wxWidgets/Phoenix#944]
**Operating system**: macOS 10.13.6 and Windows 10 (both)
**wxPython version**: 4.0.3
**Stock or custom build**: Stock (pypi)
**Python version**: 3.6.6 (Windows), 3.7.0 (macOS)
**Stock or custom build**: Stock (Windows) Stock/homebrew (macOS)

**Description of the problem**: 
I have an application where I draw a rectangle into a PaintDC using
a `GraphicsContext.Create(paintdc)` first.

This works perfectly fine with both `PaintDC` and `BufferedPaintDC`, but if I use `AutoBufferedPaintDC` I see no drawing into the DC with the GraphicsContext.

I'm guessing this is related to recent activity implementing `AutoBufferedPaintDC` as an overload for `GraphicsContext.Create()` (Issue #783 , Pull Request #874 )  I'm hoping that it might be a simple error in implementation.

I don't have a small test case right now, but my code using GraphicsContext is here:
[Line setting up PaintDC/AutoBufferedPaintDC](https://github.com/itsayellow/marcam/blob/05fe6f7093172d83bd4b56f7d926b655bdbdd374/marcam/image_scrolled_canvas.py#L947)
[Line using GraphicsContext.Create](https://github.com/itsayellow/marcam/blob/05fe6f7093172d83bd4b56f7d926b655bdbdd374/marcam/image_scrolled_canvas.py#L1187)

**Comment by RobinD42** [comment]
Fixed by #996
