### ISSUE TITLE
Feature request: a method to undo SetDefault() on a button

### ISSUE THREAD

**Issue by mhucka** [wxWidgets/Phoenix#945]
**Operating system**:
MacOS 10.13
**wxPython version**:
4.0.0b1
**Stock or custom build**:
Obtained via pip
**Python version**:
3.5.5
**Stock or custom build**:
Obtained via MacPorts
**Description of the problem**:

Currently, there appears to be no way to undo the effect of calling `SetDefault()` on a button. I have a situation in which I have a simple GUI, and use `SetDefault()` on a button when the user has filled in the necessary text fields so that it's obvious that if the user now presses the return key, the button will be pressed. However, if the user deletes types some text then deletes it, I want to reverse the default button setting, because if the field is empty it no longer makes sense to submit the contents. `SetDefault()` in wxPython 4.0 does not take an argument, so I cannot call `SetDefault(False)`, and I cannot find a suitable API call to reverse the default state. If it were possible to `SetDefault()` on a different button, I would do that, but there are only two buttons in the simple GUI and the other button does not make any sense to suddenly become the default.

So, my feature request is the addition of an optional parameter to `SetDefault()`, such that handing it a value of `False` will undo the default setting.

**Comment by DietmarSchwertberger** [comment]
Just make the accept button the default and then use Enable/Disable. That's the common behaviour. A dynamic Default would be quite unexpected.

**Comment by mhucka** [comment]
Ah, I see: the behavior of `Enable()`/`Disable()` is actually what I was looking for. This works. Thanks, and thanks also for the super-fast reply.
