### ISSUE TITLE
Add wrappers for wxAccessible

### ISSUE THREAD

**Issue by RobinD42** [wxWidgets/Phoenix#958]
**Operating system**: Windows
**wxPython version**: any
**Stock or custom build**: any
**Python version**: any
**Stock or custom build**: any

See https://groups.google.com/d/msg/wxpython-users/RLmgXW0qNLc/Vptj0eCVCQAJ

**Comment by RobinD42** [comment]
Fixed by #1034

**Comment by josephsl** [comment]
Hi Robin,

I'm afraid this may have introduced accName regression (see #1129). Specifically, with wx.Accessible active, if a wx.Control widget leaves name kwarg empty, a generic label is announced by screen readers (tested via two screen readers, with a colleague of mine using Microsoft Inspect tool).

Thanks.

CC @MichaelDCurran, @LeonardDer, @JCSTeh
