### ISSUE TITLE
allow inclusion of wxpy_api.h by other projects

### ISSUE THREAD

**Issue by pointhi** [wxWidgets/Phoenix#961]
I'm currently working on getting Phoenix working with KiCad. To do this we currently need to include the file ```wxpy_api.h``` from the Phoenix source directory.

Would it be possible to add such headers into the Phoenix release packages?

**Comment by pointhi** [comment]
we fixed this issue by incorporating some of the macros and changing some of the codepaths

**Comment by RobinD42** [comment]
I think it does make sense to provide the file, so I'm reopening this issue.

**Comment by RobinD42** [comment]
Fixed by #1035
