### ISSUE TITLE
Low-res checkbox images in CheckListBox

### ISSUE THREAD

**Issue by feerrenrut** [wxWidgets/Phoenix#963]
**Operating system**: Windows 10 Version `10.0.17134 Build 17134`
**wxPython version**: 4.03
**Stock or custom build**: Stock
**Python version**: 2.7.14
**Stock or custom build**: Stock

**Description of the problem**:
On a system with 125% or more scaling (Display settings, "change the size of text, apps and other items"). When using `ctypes.windll.user32.SetProcessDPIAware()` with `CheckListBox` the check marks seems to have scaling issues. 

This is related to #835 ("Low-res checkbox images ChecklistCtrlMixin"), but I believe a new issue should be created due to differences in OS, the exact control in question, and the relevance of `SetProcessDPIAware`. I also tested `CheckListCtrlMixin` and could not reproduce the same issue.

This can be demonstrated by including the following at the top of the `CheckListBox` wxPython demo:

```
import ctypes
ctypes.windll.user32.SetProcessDPIAware()
```

And full demo code:

```python
import ctypes
ctypes.windll.user32.SetProcessDPIAware()
import wx

class TestPanel(wx.Panel):
    def __init__(self, parent):
        wx.Panel.__init__(self, parent, -1)

        sampleList = ['zero', 'one', 'two', 'three', 'four', 'five',
                      'six', 'seven', 'eight', 'nine', 'ten', 'eleven',
                      'twelve', 'thirteen', 'fourteen']

        lb = wx.CheckListBox(self, -1, (80, 50), wx.DefaultSize, sampleList)
        lb.SetSelection(0)
        lb.SetCheckedItems([1,])
        self.lb = lb

#----------------------------------------------------------------------

class RunDemoApp(wx.App):
    def __init__(self):
        wx.App.__init__(self, redirect=False)


    def OnInit(self):
        frame = wx.Frame(None, -1, "test", pos=(50,50), size=(200,100),
                        style=wx.DEFAULT_FRAME_STYLE, name="test")
        frame.Show(True)
        win = TestPanel(frame)

        # so set the frame to a good size for showing stuff
        frame.SetSize((640, 480))
        win.SetFocus()
        self.window = win

        self.SetTopWindow(frame)
        self.frame = frame

        return True

    def OnExitApp(self, evt):
        self.frame.Close(True)


if __name__ == "__main__":
    app = RunDemoApp()
    app.MainLoop()

```

Which produces the following, first with the call to `SetProcessDPIAware` and then without:
![image](https://user-images.githubusercontent.com/3491346/44073346-ab0c9e02-9fd2-11e8-8a26-63b63445d7ca.png)

![image](https://user-images.githubusercontent.com/3491346/44073383-c56e7bf8-9fd2-11e8-9f33-732407fd6582.png)

The following is a screenshot comparing the check mark of `CheckListCtrlMixin` with `CheckListBox`, produced with [code available in a gist.](https://gist.github.com/feerrenrut/e344f66cb3d9f0ae34a34e60b83ea449)

![image](https://user-images.githubusercontent.com/3491346/44074403-99179292-9fd7-11e8-87f8-f51b85e0001f.png)

**Comment by seanbudd** [comment]
It appears this has been resolved based on https://github.com/nvaccess/nvda/issues/8635

**Comment by infinity77** [comment]
@swt2c This seems to have been solved - unclear if it’s still an issue or not
