### ISSUE TITLE
EVT_MOTION not emitted when left is down on button

### ISSUE THREAD

**Issue by cykerway** [wxWidgets/Phoenix#967]
**Operating system**: Fedora 28
**wxPython version & source**: _(pypi, self-built, etc.)_ 4.0.3 gtk2 wxWidgets 3.0.5 prebuilt wheel
**Python version & source**: _(stock, anaconda, EDM, distro, self-built, etc.)_ distro 3.6.6

**Description of the problem**:

-   If you move mouse over button, it's OK.

-   If you press left in the blank and keep it down, then move mouse over button, it's OK.

-   However, if you press left on the button and keep it down, then move mouse over button, there's no EVT_MOTION emitted. So this effectively doesn't allow you to drag a button.

```python
# Put code sample here
#!/usr/bin/env python3

# -*- coding: utf-8 -*-

import wx

class MyTestFrame(wx.Frame):
    def __init__(self, parent, title):
        super().__init__(parent, wx.ID_ANY, title, size=(240, 480))
        btn = wx.Button(self, label='Button1')
        btn.Bind(wx.EVT_MOTION, self.on_evt_motion, btn)
        sizer = wx.BoxSizer(wx.VERTICAL)
        sizer.Add(btn)
        self.SetSizer(sizer)
        self.Center()
        self.Show()

    def on_evt_motion(self, evt):
        print(evt.Dragging())

if __name__ == '__main__':
    app = wx.App()
    frame = MyTestFrame(None, 'Test')
    app.MainLoop()

```

**Comment by cykerway** [comment]
This is what I found on a 15-year-old post: http://wxpython-users.1045709.n5.nabble.com/Is-it-possible-to-grab-mouse-button-motion-events-in-a-wxButton-tp2302267p2302274.html

Hmm... I'd like to know if things have improved or there is a workaround to make dragging a button possible.

**Comment by RobinD42** [comment]
Apparently not. 

Things like this are the downside to using native widgets, sometimes they don't behave consistently with other widgets or with generic controls. We also have no control over what events a native widget might eat before we can see them, etc.
