### ISSUE TITLE
Website: New link for wxWidgets blog (Location has changed)

### ISSUE THREAD

**Issue by itsayellow** [wxWidgets/Phoenix#968]
Currently on https://wxpython.org/, there is a link to the wxWidgets Blog under "Friends of wxPython".  The link has changed, and the new link should be:
https://www.wxwidgets.org/blog/

(Funny, the wxwidgets homepage itself does not seem to be pointing to the new blog entries!)

**Comment by RobinD42** [comment]
Updated, finally.
