### ISSUE TITLE
wx.ChoiceBook().DeleteAllPages() doesn't update Choice control

### ISSUE THREAD

**Issue by mprosperi** [wxWidgets/Phoenix#972]
**Operating system**: win10
**wxPython version & source**: wxPython-4.0.4a1.dev3929+55c51b25-cp35-cp35m-win_amd64.whl
**Python version & source**: stock

**Description of the problem**: DeleteAllPages() in classic also deleted all entries in choicectrl. Now I should add explicitly obj.GetChoiceCtrl().Clear()

**Comment by RobinD42** [comment]
CLosed by #1022
