### ISSUE TITLE
HyperTreeList draw very slow

### ISSUE THREAD

**Issue by cbeytas** [wxWidgets/Phoenix#973]
Issue marked outdated is still present:
[HyperTreeList dotted lines drawing optimization](https://trac.wxwidgets.org/ticket/15424)

The demo for HyperTreeList works fine until you increase the number of items. Change:
`for x in range(15):` to `for x in range(300):`

Scrolling the window takes 100% CPU on my PC (almost all of it "system" usage).
I've tested the fix with Python 2.7.13 and wxPython 4.0.3 msw and it's a huge improvement.

**Comment by infinity77** [comment]
This can probably be applied to CustomTreeCtrl too, seems like a very useful optimization

**Comment by RobinD42** [comment]
Please create a PR for CustomTreeCtrl. It wasn't clear to me with a quick glance where to apply the change there.

**Comment by infinity77** [comment]
It’s actually not necessary for CustomTreeCtrl, the drawing code is different and CustomTreeCtrl appears to be doing the right thing. Sorry for the noise, I misremembered...

**Comment by RobinD42** [comment]
Ok, thanks Andrea.

**Comment by RobinD42** [comment]
Fixed by #979
