### ISSUE TITLE
wx.StaticBox positioning issue

### ISSUE THREAD

**Issue by blitzmann** [wxWidgets/Phoenix#974]
**Operating system**: Windows 10
**wxPython version & source**: 4.0.3 stock
**Python version & source**: 3.6 stock

**Description of the problem**:
Using a `wx.StaticBox`, as laid out in the demo, causes positioning issues wherein the children overlap the title of the box

![image](https://user-images.githubusercontent.com/3904767/44621580-8a9dba00-a876-11e8-9eb9-d18c76ddf3cc.png)

See the demo for example

**Comment by blitzmann** [comment]
Using the inspector, it seems that the sizer insider the static box actually takes up the same space.

![image](https://user-images.githubusercontent.com/3904767/44621636-64c4e500-a877-11e8-847c-6ce4eb50f5ce.png)

A work around for this would be to adjust the border amount in this line on the demo:

`bsizer1.Add(t1, 1, wx.EXPAND|wx.TOP|wx.LEFT|wx.RIGHT, 10)`

to add the bottom but also a bit more to the top.

Now the question is, is this intended? Seems a bit strange.

**Comment by blitzmann** [comment]
Seems this might be a windows-only bug. getting a report from one of our linux users suggesting that the work around that I implemented makes linux gui look jacked while Windows UI looks fine. :/

**Comment by blitzmann** [comment]
The only solve I have for it right now is to check if it's a windows machine and do adjustments. Pretty hacky. @RobinD42 is there a better solution?

**Comment by RobinD42** [comment]
Fixed by #980
