### ISSUE TITLE
Event Watcher -> Watch not stopping after deselection

### ISSUE THREAD

**Issue by feyyd** [wxWidgets/Phoenix#975]
**Operating system**: 
Windows 10
**wxPython version & source**: _(pypi, self-built, etc.)_
wxPython 4.0.0b2 msw (phoenix) pypi
**Python version & source**: _(stock, anaconda, EDM, distro, self-built, etc.)_
Python 3.6 stock
**Description of the problem**:
After adding an event like EVT_IDLE or EVT_UPDATE_UI_RANGE to Watch, deselecting item has no effect and will infinitely spam the event window.

**Comment by RobinD42** [comment]
Does this happen to you in 4.0.3 too? How long do you leave EVT_IDLE selected before disabling it again? (IOW, could a bunch of events be stacked up waiting to logged in the watcher.) If you're seeing this in your own application then are you doing anything that could be causing nested or recursive idle events? (Doing something within a EVT_IDLE hander that causes more EVT_IDLE events to be sent before returning.) Also, be aware that some things like update-ui events are actually sent from within EVT_IDLE.

**Comment by infinity77** [comment]
@swt2c : yet another one deserving to be closed.
