### ISSUE TITLE
libwx_gtk3u_core-3.0.so.0 conflict (wxPython and wxgtk3)

### ISSUE THREAD

**Issue by pointhi** [wxWidgets/Phoenix#982]
**Operating system**: Linux
**wxPython version & source**: [python-wxpython](https://www.archlinux.org/packages/community/x86_64/python-wxpython) 4.0.3-3
**Python version & source**: 3.7.0-3

wxPyhon exports it own ```libwx_gtk3u_core-3.0.so.0``` which conflicts with the normally distributed wx library. For example both [wxgtk3](https://www.archlinux.org/packages/extra/x86_64/wxgtk3) and [python-wxpython](https://www.archlinux.org/packages/community/x86_64/python-wxpython) distribute this library. When a wx based application tries to do a ```import wx``` in its own created python enviroment the following happens: 

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "/usr/lib/python3.7/site-packages/wx/core.py", line 12, in <module>
    from ._core import *
ImportError: /usr/lib/python3.7/site-packages/wx/_core.cpython-37m-x86_64-linux-gnu.so: symbol wxWindowIDRef::Assign(int) version WXU_3.0 not defined in file libwx_gtk3u_core-3.0.so.0 with link time reference
```

**Comment by RobinD42** [comment]
The expectation is that a wxPython installed from system/distro packages then it should be built such that it uses the system/distro package for wxWidgets. The default build options for wxPython are intended for use in building a self-contained standalone wheel file.

Passing the `--use_syswx` flag to `build.py` will build wxPython to use the system wxWidgets and not build its own copy.

**Comment by pointhi** [comment]
Reported to the Package Maintainers: https://bugs.archlinux.org/task/59880

**Comment by FFY00** [comment]
I tried porting the build to `build.py` but I get the following error.

Log: http://ix.io/1lXJ

**Comment by swt2c** [comment]
> I tried porting the build to build.py but I get the following error.
> Log: http://ix.io/1lXJ

It looks like your system wxWidgets is built with GTK+2 but you are trying to build the GTK+3 version of wxPython.  Try building the GTK+2 version of wxPython.

**Comment by FFY00** [comment]
The problem was that you were calling `/usr/bin/wx-config`, which is provided by `wxgtk2`. I patched `build.py` to use `/dev/bin/wx-config-gtk3` instead and it's working.
