### ISSUE TITLE
FileHistory puts non-intuitive mix of full paths and file-name-only items in managed menu

### ISSUE THREAD

**Issue by itsayellow** [wxWidgets/Phoenix#984]
**Operating system**: macOS 10.13.6 & Windows 10
**wxPython version & source**: wxPython 4.0.3 from pip3
**Python version & source**: python 3.7.0 (macOS) & python 3.6.6 (Win 10)

**Description of the problem**: For the menu that wx.FileHistory manages showing  recent files, there seems to be an implicit idea of a "current directory".  Any files in that "current directory" (seemingly the directory of the last added file) are shown without the full path, with filename only.  Any files from different directories are show with their full path.

From a user standpoint it's not obvious why there is a mix of full paths for some menu items and filename-only menu items.  The user is not aware of the implicit "current directory", and the mix of styles for file paths looks like a bug.  Plus, every time the user opens a file in a different directory, the items which have full paths and which are file-name-only switch around, which adds to the random feeling.

__Note__ that you must open files to add to the history from different directories to observe the issue.

Sample code is below, but this is also observable from the FileHistory demo code in the wxPython demo directory.  

```python
#!/usr/bin/env python3
  
import wx

class MainWindow(wx.Frame):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # FileHistory
        self.file_history = wx.FileHistory()

        # menu bar stuff
        menubar = wx.MenuBar()
        
        # File
        open_recent_menu = wx.Menu()
        file_menu = wx.Menu()
        file_open_item = file_menu.Append(wx.ID_OPEN,
                'Open File...\tCtrl+O',
                'Open file'
                )
        file_menu.AppendSubMenu(open_recent_menu,
                'Open Recent',
                'Open recent files'
                )

        menubar.Append(file_menu, '&File')

        # register Open Recent menu, put under control of FileHistory obj
        self.file_history.UseMenu(open_recent_menu)
        self.file_history.AddFilesToMenu(open_recent_menu)

        self.SetMenuBar(menubar)

        # setup event handlers for menus
        # File menu items
        self.Bind(wx.EVT_MENU, self.on_open, file_open_item)

        self.Show(True)

    def on_open(self, evt):
        open_file_dialog = wx.FileDialog(self,
                "Open File",
                style=wx.FD_OPEN | wx.FD_FILE_MUST_EXIST)

        if open_file_dialog.ShowModal() == wx.ID_CANCEL:
            # the user canceled
            return

        file_path = open_file_dialog.GetPath()
        self.file_history.AddFileToHistory(file_path)

def main():
    my_app = wx.App()
    main_win = MainWindow(None)
    my_app.MainLoop()

if __name__ == '__main__':
    main()
```

**Comment by itsayellow** [comment]
Also, on Windows, there seems to be a mix of forward slash paths (for relative paths) and backslash paths (for absolute paths).

<img width="698" alt="screen shot 2018-09-02 at 3 54 58 pm" src="https://user-images.githubusercontent.com/12565784/44961599-bbaa6a00-aec8-11e8-9139-357ad60bc29e.png">

**Comment by itsayellow** [comment]
I worked up a wrapper of wx.FileHistory that is a subclass of it that formats the entries in the menu the way I like it.  My logic is to use paths relative to the user's home directory if possible, and failing that the absolute path.

In the code below I made a separate method `FormatFilePathMenu` that accepts a full path string and returns the string as it should look in the menu.  Overriding this function alone allows for different rules for how filepaths should be displayed in the menu.

```python3
import pathlib
import wx

class FileHistory(wx.FileHistory):
    """Like wx.FileHistory, but changing how menu items are displayed
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.managed_menus = []
        self.base_id = super().GetBaseId()

    def _remove_file_from_menu(self, menu, i):
        # Delete specified item and all lower items
        # range + 1 because we've already removed the item in super()
        #   but not in our own menu
        for file_hist_i in range(i, super().GetCount() + 1):
            menu.Delete(self.base_id + file_hist_i)

        # Add back items with new IDs
        self._add_all_files_to_menu(menu, starting_file=i)

    def _remove_file_from_menus(self, i):
        for menu in self.managed_menus:
            self._remove_file_from_menu(menu, i)

    def _add_file_to_menu(self, menu):
        # Delete all history items
        # range - 1 because we've already added the item in super()
        #   but not in our own menu
        for file_hist_i in range(0, super().GetCount() - 1):
            menu.Delete(self.base_id + file_hist_i)

        # Add back items with new IDs
        self._add_all_files_to_menu(menu)

    def _add_file_to_menus(self):
        for menu in self.managed_menus:
            self._add_file_to_menu(menu)

    def _add_all_files_to_menu(self, menu, starting_file=0):
        # Add all items to end of menu
        for file_hist_i in range(starting_file, super().GetCount()):
            menu.Append(
                    self.base_id + file_hist_i,
                    self.FormatFilePathMenu(super().GetHistoryFile(file_hist_i))
                    )

    def _add_all_files_to_menus(self):
        for menu in self.managed_menus:
            self._add_all_files_to_menu(menu)

    def FormatFilePathMenu(self, file_path):
        file_path = pathlib.Path(file_path)
        try:
            # Attempt to find path relative to home directory
            file_path = file_path.relative_to(pathlib.Path.home())
        except ValueError:
            # keep absolute path if path not under home directory
            pass
        return str(file_path)

    def UseMenu(self, menu):
        self.managed_menus.append(menu)

    def RemoveMenu(self, menu):
        self.managed_menus.remove(menu)

    def AddFilesToMenu(self, *args, **kwargs):
        if args or kwargs.get('menu', False):
            self._add_all_files_to_menu(args[0])
        elif kwargs.get('menu', False):
            self._add_all_files_to_menu(kwargs['menu'])
        else:
            self._add_all_files_to_menus()

    def AddFileToHistory(self, filename):
        super().AddFileToHistory(filename)
        self._add_file_to_menus()

    def RemoveFileFromHistory(self, i):
        super().RemoveFileFromHistory(i)
        self._remove_file_from_menus(i)

```

**Comment by RobinD42** [comment]
I believe that this behavior is by design. The process does have a current working directory, which you can check with `os.getcwd()`. If you always want absolute path names then you can ensure that your cwd is not where the files being opened are located. Also, if you're using the `wx.FD_CHANGE_DIR` with the `wx.FileDialog` then it will automatically change the cwd to be the location of the opened file, so you may want to check into how you are using the file dialog.

The forward slashes could be happening because that is how the user typed the name into the file open dialog, or something like that. I had it one time because some file names were based on a path stored in an environment variable set by the user. It's easy enough to replace `/` with `\` when adding the names to the history.

**Comment by itsayellow** [comment]
Actually the paths don't seem to be based on os.getcwd().  In fact, every time a new file is added to the recent file list, the directory that the paths are relative to changes to that directory.  It's this last behavior that makes all the paths in the menu change every time you open a file from a new directory.

If it was really based on os.getcwd() that would be a lot more predictable.

**Comment by itsayellow** [comment]
I also added a
```
print(os.getcwd())
```
every time I open a new file, and it's always the directory from where I started the program, and it never changes.

**Comment by infinity77** [comment]
It looks like it’s by design, as I have been fighting with this as well recently, and I ended up writing my own wx.FileHistory.

You can see the odd behavior here:

https://github.com/wxWidgets/wxWidgets/blob/master/src/common/filehistorycmn.cpp

From line 138 to 150 approximately. It seems like it determines the “current working directory” based on the last file you added to wx.FileHistory...

**Comment by RobinD42** [comment]
Indeed. I'm pretty sure it was relative to CWD in the past, but I guess it has changed somewhere along the way. 

I expect that a PR submitted to wxWidgets that added a flag that caused it to only show full paths would probably be accepted. Or something like that.
