### ISSUE TITLE
NovalIDE opensource project.

### ISSUE THREAD

**Issue by wekay102200** [wxWidgets/Phoenix#985]
**Operating system**:
**wxPython version & source**: _(pypi, self-built, etc.)_
**Python version & source**: _(stock, anaconda, EDM, distro, self-built, etc.)_

**Description of the problem**:

```python
# Put code sample here
```
Hi,Dear all:
I have launch a opensource project named NovalIDE which developed by python2.7, and wxPython3.0.
NovalIDE is an opensource python ide which based on activegrid.
Now I want to recruit some developers which love opensource cause.and be faimilar with python and wxpython 3.0 or 4.0.
the official website is http://www.novalide.com
windows downoad address is:http://www.novalide.com/member/download_app?lang=zh_cn&os_name=win32
linux download address is:http://www.novalide.com/member/download_app?lang=zh_cn&os_name=linux

Below is my personal information:
qq:273655394
phone:15173133233
email:kan.wu@genetalks.com

**Comment by RobinD42** [comment]
This type of thing should go to the mail list
