### ISSUE TITLE
wx.html2 load error

### ISSUE THREAD

**Issue by wekay102200** [wxWidgets/Phoenix#988]
**Operating system**:
**wxPython version & source**: _(pypi, self-built, etc.)_
**Python version & source**: _(stock, anaconda, EDM, distro, self-built, etc.)_

**Description of the problem**:

```python
# Put code sample here
```

  File "/home/wukan/work/Noval/noval/tool/HtmlEditor.py", line 21, in <module>
    import wx.html2 as webview
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/html2.py", line 8, in <module>
    import _html2
ImportError: /usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_html2.x86_64-linux-gnu.so: undefined symbol: wxEVT_WEBVIEW_NAVIGATED

os system:
ubuntu 16.04

**Comment by swt2c** [comment]
It appears you are using wxPython Classic.  This issue tracker is for wxPython Phoenix.

It also appears that you are using the distribution packages in Ubuntu.  Unfortunately, in Ubuntu 16.04 the wxPython Classic package was not built with webview support, which is the error you are seeing.  You will probably have to resolve this by building wxPython Classic yourself, or better yet, use Phoenix.
