### ISSUE TITLE
Mouse button not released when focusing a TextCtrl

### ISSUE THREAD

**Issue by cykerway** [wxWidgets/Phoenix#990]
**Operating system**: Fedora 28
**wxPython version & source**: _(pypi, self-built, etc.)_ stock
**Python version & source**: _(stock, anaconda, EDM, distro, self-built, etc.)_ distro 3.6

**Description of the problem**:

Dismissing a dialog popped in a `EVT_SET_FOCUS` event handler doesn't seem to release the mouse button. After the dialog is dismissed, moving the mouse over the text in the `TextCtrl` highlights the text, which looks like the mouse button is always kept down.

A case where this problem doesn't happen is when you hold the left button on the `TextCtrl` and dismiss the dialog by pressing the Enter key. Then release the left button on the `TextCtrl`. After that the mouse over operation doesn't highlight the text. However, users typically click rather than hold the left button to give a `TextCtrl` focus, so this problem still affects its usage when popping a dialog in a focus event.

Further debugging shows, if I create my own `Dialog` and call `Dialog.ShowModal()`, then the problem is the same as using `MessageBox` here. But if I call `Dialog.Show()` then the bug doesn't seem to appear. Probably something goes wrong between `TextCtrl` and `ShowModal`. My guess is that the modal dialog creates its own event loop. So if you mouse-up when the dialog shows then the mouse-up event is consumed by the dialog and the `TextCtrl` still thinks your mouse button is down.

```python
# Put code sample here
import wx
def focus(evt):
    if wx.GetApp().n % 2 == 0:
        wx.MessageBox(
            'After dismissing this dialog, move mouse over text on the text in '
            'the 2nd TextCtrl and it seems the mouse button is not released.')
    wx.GetApp().n += 1
app = wx.App()
app.n = 0
frame = wx.Frame(None, title='Mousedown Bug', size=(400, 300))
tc1 = wx.TextCtrl(frame, value='Focusing on TextCtrl below pops dialog')
tc2 = wx.TextCtrl(frame, value='Move mouse over me after dismissing dialog')
tc2.Bind(wx.EVT_SET_FOCUS, focus)
sizer = wx.BoxSizer(wx.VERTICAL)
sizer.Add(tc1, 0, wx.EXPAND)
sizer.Add(tc2, 0, wx.EXPAND)
frame.SetSizer(sizer)
frame.Show()
app.MainLoop()
```

**Comment by cykerway** [comment]
Now here's something interesting: I think `wx.CallLater` may be able to give a similar user experience but with a parameter we can control. So I turned the dialog popup into a functional object:

```python
import wx
def focus(evt):
    if wx.GetApp().n % 2 == 0:
        f = lambda: wx.MessageBox(
            'After dismissing this dialog, move mouse over text on the text in '
            'the 2nd TextCtrl and it seems the mouse button is not released.')
        wx.CallLater(100, f)
    wx.GetApp().n += 1
app = wx.App()
app.n = 0
frame = wx.Frame(None, title='Mousedown Bug', size=(400, 300))
tc1 = wx.TextCtrl(frame, value='Focusing on TextCtrl below pops dialog')
tc2 = wx.TextCtrl(frame, value='Move mouse over me after dismissing dialog')
tc2.Bind(wx.EVT_SET_FOCUS, focus)
sizer = wx.BoxSizer(wx.VERTICAL)
sizer.Add(tc1, 0, wx.EXPAND)
sizer.Add(tc2, 0, wx.EXPAND)
frame.SetSizer(sizer)
frame.Show()
app.MainLoop()
```
The result is that, if you set the delay to 100ms then things seem fine. But if you set it to 10ms then the bug is nearly identical to the first post. So there's definitely something to do with event scheduling.

**Comment by cykerway** [comment]
I finally got something that's closer to the behavior I wanted. The idea is to detect if the focus is due to a tab or a left button click. If a tab, then just show the dialog since it's nothing to do with mouse events. If a left button click, then monkey bind the dialog function to the mouse-up event (and unbind after the dialog is shown). There are some caveats (for example if you use middle button to set focus then things can go wrong). Furthermore, monkey patch is ugly so I still hope there would be a *normal* solution.

```python
import wx
def f(evt):
    wx.MessageBox(
        'After dismissing this dialog, move mouse over text on the text in '
        'the 2nd TextCtrl and it seems the mouse button is not released.')
    evt.GetEventObject().Unbind(wx.EVT_LEFT_UP)
    evt.Skip()
def focus(evt):
    if wx.GetApp().n % 2 == 0:
        if wx.GetMouseState().LeftIsDown():
            evt.GetEventObject().Bind(wx.EVT_LEFT_UP, f)
        else:
            f(evt)
    wx.GetApp().n += 1
    evt.Skip()
app = wx.App()
app.n = 0
frame = wx.Frame(None, title='Mousedown Bug', size=(400, 300))
tc1 = wx.TextCtrl(frame, value='Focusing on TextCtrl below pops dialog')
tc2 = wx.TextCtrl(frame, value='Move mouse over me after dismissing dialog')
app.tc2 = tc2
tc2.Bind(wx.EVT_SET_FOCUS, focus)
sizer = wx.BoxSizer(wx.VERTICAL)
sizer.Add(tc1, 0, wx.EXPAND)
sizer.Add(tc2, 0, wx.EXPAND)
frame.SetSizer(sizer)
frame.Show()
app.MainLoop()
```

**Comment by RobinD42** [comment]
In case it's not clear from your experiments, doing anything within focus event handlers which can cause the focus to change again are notoriously prone to having troubles. Also, in your first two samples you didn't call `evt.Skip()` which meant that the default focus behavior in the native widget would not get a chance to run, which also tends to be problematic.

It's usually best for focus handlers to not do much more than setting flags or something, perhaps do a CallAfter to do the real work later, and then call Skip so the native behavior will happen.
