### ISSUE TITLE
Installed wxpython .whl from extras. Raises libSDL import error when importing dataview 

### ISSUE THREAD

**Issue by swprojects** [wxWidgets/Phoenix#991]
**Operating system**: Ubuntu18.04.1 LTS (Bionic Beaver) 64-bit
**wxPython version & source**: https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04/

wxPython-4.0.3-cp36-cp36m-linux_x86_64.whl

**Python version & source**: stock - python 3.6.5
**Description of the problem**: Downloaded whl and installed. Cannot open shared object file libSDL when trying to import dataview.

```python
import wx
import wx.dataview
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/***/.local/lib/python3.6/site-packages/wx/dataview.py", line 12, in <module>
    from ._dataview import *
ImportError: libSDL-1.2.so.0: cannot open shared object file: No such file or directory

```

**Comment by RobinD42** [comment]
```
vagrant@ubuntu-bionic:~$ apt-file search libSDL-1.2.so.0
libsdl1.2debian: /usr/lib/x86_64-linux-gnu/libSDL-1.2.so.0
libsdl1.2debian: /usr/lib/x86_64-linux-gnu/libSDL-1.2.so.0.11.4
```

Install the `libsdl1.2debian` package.
