### ISSUE TITLE
Context menu's "Insert Unicode control character" in any text field can crash program with the error “m_menuDepth > 0”

### ISSUE THREAD

**Issue by ruohola** [wxWidgets/Phoenix#992]
**Operating system:** Win 10 Enterprise 2016 LTSB / Win 10 Pro (tested on both)
**wxPython version & source:** 4.0.2 / 4.0.3 from pip3 (tested on both)
**Python version & source**: Python 3.6.5 from python.org

When right clicking a text field in a wxPython widget, if the user selects the [`Insert Unicode control character`](https://i.gyazo.com/a5952988805d40dd5df661b4320216f5.png) option and inserts any of those characters the program will throw this error:

>     wx._core.wxAssertionError: C++ assertion "m_menuDepth > 0" failed at ..\..\src\msw\toplevel.cpp(1545) in wxTopLevelWindowMSW::DoSendMenuOpenCloseEvent(): No open menus?
>     
>     The above exception was the direct cause of the following exception:
>     
>     SystemError: <class 'wx._core.CommandEvent'> returned a result with an error set

Here's an example code which will throw the error:
```python
import wx

class Program(wx.Frame):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.panel = wx.Panel(self)
        self.sizer = wx.GridBagSizer(0, 0)
        self.panel.SetSizer(self.sizer)

        self.text_ctrl = wx.TextCtrl(self.panel)
        self.sizer.Add(self.text_ctrl, wx.GBPosition(0, 0))

        # Needed, because there probably has to be some events which
        # can be processed for the error to show before closing the program.
        # Without this the error only appears after exiting.
        self.text_ctrl.Bind(wx.EVT_TEXT, lambda e: print("text changed"))

        self.sizer.Layout()
        self.Show()


app = wx.App()
program = Program(parent=None)
app.MainLoop()
```

**Comment by RobinD42** [comment]
It looks like this is an issue in wxWidgets. Please add a ticket at https://trac.wxwidgets.org/ if there isn't already one about this there. Reply here with the ticket number there so we can track it.

**Comment by RobinD42** [comment]
The fix will be included in 4.1, but probably can not be backported to 4.0.x.

**Comment by ruohola** [comment]
Has this been fixed in the latest release? Can this be closed?

**Comment by infinity77** [comment]
@swt2c : looking at https://github.com/wxWidgets/wxWidgets/issues/18221 , I believe this might have been fixed.
