### ISSUE TITLE
Can't set wx.ProgressDialog properties

### ISSUE THREAD

**Issue by BrendanSimon** [wxWidgets/Phoenix#995]
**Operating system**: OS X (High Sierra 10.13.6)
**wxPython version & source**: wxPython 4.0.3 (install via pip)
**Python version & source**: python 3.6 (installed via homebrew)

**Description of the problem**:

Can't set wx.ProgressDialog properties (Message, Range, Value).  The `Update()` method is the only way I could change the value and message.

python generates an exception: `AttributeError: can't set attribute`

```python
import wx

app = wx.App()

prog = wx.ProgressDialog( title="Test", message="Starting..." )

prog.Update( 50, "updating - 50%" )

prog.Value = 75
prog.Message = "updating - 75%"
```

**Comment by RobinD42** [comment]
That's because there are no setter methods for those properties, they don't exist in the C++ class. IOW, there's a `GetMessage()` but no `SetMessage()` so the wrappers can generate a Python property with only a getter.
