### ISSUE TITLE
Joystick demo: Gauge has no attribute OnPaint

### ISSUE THREAD

**Issue by mickp** [wxWidgets/Phoenix#997]
**Operating system**:  Win7
**wxPython version & source**: pypi, 4.0.3 msw (phoenix) wxWidgets 3.0.5
**Python version & source**: WinPython 3.5.2

**Description of the problem**:
Running Phoenix/demo/Joystick.py produces attribute errors
   type object 'Gauge' has no attribute 'OnPaint'
when it hits
```        wx.Gauge.OnPaint(self, evt)```
in demo.Joystick.AxisBar.ShowValue (line 651 as at d49953b7cd12eec1689382c81fd7ea9460ebe20b)

```python
    def ShowValue(self, dc, evt):
        # This method handles actual painting of and drawing
        # on the gauge.

        # Clear out the gauge
        dc.Clear()
        # and then carry out business as usual
        wx.Gauge.OnPaint(self, evt)
```

**Comment by RobinD42** [comment]
Fixed by #1063
